In [ ]:
import json
import numpy as np
import matplotlib.pyplot as plt
from datasets import Dataset
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import bitsandbytes as bnb
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification, 
    TrainingArguments, 
    Trainer,
    DataCollatorWithPadding,
    EarlyStoppingCallback
)
import evaluate
from peft import LoraConfig, get_peft_model, TaskType
from collections import Counter
from transformers import BitsAndBytesConfig
from collections import Counter

from dotenv import load_dotenv
import os
load_dotenv()
YOUR_HF_TOKEN = os.getenv("YOUR_HF_TOKEN")

/home/bistreamt/Desktop/master/research 3/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def combine_text(row):
    # Collect all existing description parts in order
    desc_parts = [row.get(f"case_description_{i}", "") for i in range(1, 9) if row.get(f"case_description_{i}")]
    # Collect all existing justification parts in order
    just_parts = [row.get(f"justification_{i}", "") for i in range(1, 5) if row.get(f"justification_{i}")]
    
    # Prioritize description by putting it first
    return " ".join(desc_parts + just_parts)

In [3]:
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
            
        loss_fct = torch.nn.CrossEntropyLoss(label_smoothing=0.1)
        loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))
        return (loss, outputs) if return_outputs else loss

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    # predictions = (logits > 0).astype(int)
    return {
        "accuracy": accuracy_score(labels, predictions),
        "f1_macro": f1_score(labels, predictions, average="macro"),
        "precision_macro": precision_score(labels, predictions, average="macro"),
        "recall_macro": recall_score(labels, predictions, average="macro")
    }

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda

In [5]:
with open("data/regional-court-data.json", 'r', encoding='utf-8') as f:
    data = json.load(f)

if isinstance(data, list):
    labels = [item["label"] for item in data if "label" in item]
    
    label_counts = Counter(labels)
    
    print("Number of samples per label:")
    for label, count in sorted(label_counts.items()):
        print(f"{label:12} : {count:4d} samples")
    
    print(f"\nTotal samples in Regional Court Data: {len(data)}")

Number of samples per label:
nevinovat    : 3626 samples
vinovat      : 5244 samples

Total samples in Regional Court Data: 8870

In [6]:
# Define your mapping
path = "data/regional-court-data.json"
label_map = {
    "vinovat": 0,
    "nevinovat": 1
}

def prepare_dataset(json_file_path):
    with open(json_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    formatted_data = []
    for entry in data:
        # Combine description (1-8) and justification (1-4)
        desc = " ".join([entry.get(f"case_description_{i}", "") for i in range(1, 9)]).strip()
        # just = " ".join([entry.get(f"justification_{i}", "") for i in range(1, 5)]).strip()
        
        formatted_data.append({
            "text": f"{desc}", # Description prioritized by order
            "label": label_map[entry["label"]]
        })
    
    # Split into train and validation (85/15)
    train_data, val_data = train_test_split(
        formatted_data, 
        test_size=0.15, 
        stratify=[d["label"] for d in formatted_data], # Keep class ratios same
        random_state=42
    )
    
    return Dataset.from_list(train_data), Dataset.from_list(val_data)

train_raw, val_raw = prepare_dataset(path)

# RoBERTBase

In [7]:
model_name = "dumitrescustefan/bert-base-romanian-cased-v1"

tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    # tokenizer.pad_token = tokenizer.eos_token
    # tokenizer.padding_side = "right"
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=512)

tokenized_train = train_raw.map(tokenize_function, batched=True)
tokenized_val = val_raw.map(tokenize_function, batched=True)

Map: 100%|██████████| 7539/7539 [00:05<00:00, 1285.04 examples/s]
Map: 100%|██████████| 1331/1331 [00:01<00:00, 1170.41 examples/s]

In [9]:
# !pip install textattack

Collecting textattack
  Downloading textattack-0.3.10-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: bert-score>=0.3.5 in ./.venv/lib/python3.12/site-packages (from textattack) (0.3.13)
Collecting editdistance (from textattack)
  Downloading editdistance-0.8.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting flair (from textattack)
  Downloading flair-0.15.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: filelock in ./.venv/lib/python3.12/site-packages (from textattack) (3.20.3)
Collecting language-tool-python (from textattack)
  Downloading language_tool_python-3.4.0-py3-none-any.whl.metadata (13 kB)
Collecting lemminflect (from textattack)
  Downloading lemminflect-0.2.3-py3-none-any.whl.metadata (7.0 kB)
Collecting lru-dict (from textattack)
  Downloading lru_dict-1.4.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: datasets>=2.4.0 in ./.venv/lib/python3.12/site-packages (from textattack) (4.5.0)
Requirement already satisfied: nltk in ./.venv/lib/python3.12/site-packages (from textattack) (3.9.2)
Requirement already satisfied: numpy>=1.21.0 in ./.venv/lib/python3.12/site-packages (from textattack) (2.4.1)
Requirement already satisfied: pandas>=1.0.1 in ./.venv/lib/python3.12/site-packages (from textattack) (3.0.0)
Requirement already satisfied: scipy>=1.4.1 in ./.venv/lib/python3.12/site-packages (from textattack) (1.17.0)
Requirement already satisfied: torch!=1.8,>=1.7.0 in ./.venv/lib/python3.12/site-packages (from textattack) (2.10.0)
Requirement already satisfied: transformers>=4.30.0 in ./.venv/lib/python3.12/site-packages (from textattack) (4.57.6)
Collecting terminaltables (from textattack)
  Downloading terminaltables-3.1.10-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: tqdm in ./.venv/lib/python3.12/site-packages (from textattack) (4.67.1)
Collecting word2number (from textattack)
  Downloading word2number-1.1.zip (9.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting num2words (from textattack)
  Downloading num2words-0.5.14-py3-none-any.whl.metadata (13 kB)
Collecting more-itertools (from textattack)
  Downloading more_itertools-11.1.0-py3-none-any.whl.metadata (41 kB)
Collecting pinyin>=0.4.0 (from textattack)
  Downloading pinyin-0.4.0.tar.gz (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 6.6 MB/s  0:00:00 eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting jieba (from textattack)
  Downloading jieba-0.42.1.tar.gz (19.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 8.7 MB/s  0:00:02 eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting OpenHowNet (from textattack)
  Downloading OpenHowNet-2.0-py3-none-any.whl.metadata (821 bytes)
Requirement already satisfied: requests in ./.venv/lib/python3.12/site-packages (from bert-score>=0.3.5->textattack) (2.32.5)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.12/site-packages (from bert-score>=0.3.5->textattack) (3.10.8)
Requirement already satisfied: packaging>=20.9 in ./.venv/lib/python3.12/site-packages (from bert-score>=0.3.5->textattack) (26.0)
Requirement already satisfied: pyarrow>=21.0.0 in ./.venv/lib/python3.12/site-packages (from datasets>=2.4.0->textattack) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in ./.venv/lib/python3.12/site-packages (from datasets>=2.4.0->textattack) (0.4.0)
Requirement already satisfied: httpx<1.0.0 in ./.venv/lib/python3.12/site-packages (from datasets>=2.4.0->textattack) (0.28.1)
Requirement already satisfied: xxhash in ./.venv/lib/python3.12/site-packages (from datasets>=2.4.0->textattack) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in ./.venv/lib/python3.12/site-packages (from datasets>=2.4.0->textattack) (0.70.18)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in ./.venv/lib/python3.12/site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=2.4.0->textattack) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in ./.venv/lib/python3.12/site-packages (from datasets>=2.4.0->textattack) (0.36.0)
Requirement already satisfied: pyyaml>=5.1 in ./.venv/lib/python3.12/site-packages (from datasets>=2.4.0->textattack) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in ./.venv/lib/python3.12/site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=2.4.0->textattack) (3.13.3)
Requirement already satisfied: anyio in ./.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=2.4.0->textattack) (4.12.1)
Requirement already satisfied: certifi in ./.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=2.4.0->textattack) (2026.1.4)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=2.4.0->textattack) (1.0.9)
Requirement already satisfied: idna in ./.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=2.4.0->textattack) (3.11)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.4.0->textattack) (0.16.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=2.4.0->textattack) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=2.4.0->textattack) (1.2.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=2.4.0->textattack) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in ./.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=2.4.0->textattack) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in ./.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=2.4.0->textattack) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=2.4.0->textattack) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=2.4.0->textattack) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in ./.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=2.4.0->textattack) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=2.4.0->textattack) (1.22.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas>=1.0.1->textattack) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->textattack) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests->bert-score>=0.3.5->textattack) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.12/site-packages (from requests->bert-score>=0.3.5->textattack) (2.6.3)
Requirement already satisfied: setuptools in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (80.10.1)
Requirement already satisfied: sympy>=1.13.3 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (3.6.1)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in ./.venv/lib/python3.12/site-packages (from torch!=1.8,>=1.7.0->textattack) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in ./.venv/lib/python3.12/site-packages (from cuda-bindings==12.9.4->torch!=1.8,>=1.7.0->textattack) (1.3.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch!=1.8,>=1.7.0->textattack) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in ./.venv/lib/python3.12/site-packages (from transformers>=4.30.0->textattack) (2026.1.15)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.venv/lib/python3.12/site-packages (from transformers>=4.30.0->textattack) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in ./.venv/lib/python3.12/site-packages (from transformers>=4.30.0->textattack) (0.7.0)
Collecting boto3>=1.20.27 (from flair->textattack)
  Downloading boto3-1.43.24-py3-none-any.whl.metadata (6.6 kB)
Collecting conllu<5.0.0,>=4.0 (from flair->textattack)
  Downloading conllu-4.5.3-py2.py3-none-any.whl.metadata (19 kB)
Collecting deprecated>=1.2.13 (from flair->textattack)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting ftfy>=6.1.0 (from flair->textattack)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Collecting gdown>=4.4.0 (from flair->textattack)
  Downloading gdown-6.1.0-py3-none-any.whl.metadata (8.3 kB)
Collecting langdetect>=1.0.9 (from flair->textattack)
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 4.9 MB/s  0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: lxml>=4.8.0 in ./.venv/lib/python3.12/site-packages (from flair->textattack) (6.1.1)
Collecting mpld3>=0.3 (from flair->textattack)
  Downloading mpld3-0.5.12-py3-none-any.whl.metadata (5.3 kB)
Collecting pptree>=3.1 (from flair->textattack)
  Downloading pptree-3.1.tar.gz (3.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytorch-revgrad>=0.2.0 (from flair->textattack)
  Downloading pytorch_revgrad-0.2.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: scikit-learn>=1.0.2 in ./.venv/lib/python3.12/site-packages (from flair->textattack) (1.8.0)
Collecting segtok>=1.5.11 (from flair->textattack)
  Downloading segtok-1.5.11-py3-none-any.whl.metadata (9.0 kB)
Collecting sqlitedict>=2.0.0 (from flair->textattack)
  Downloading sqlitedict-2.1.0.tar.gz (21 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tabulate>=0.8.10 in ./.venv/lib/python3.12/site-packages (from flair->textattack) (0.10.0)
Collecting transformer-smaller-training-vocab>=0.2.3 (from flair->textattack)
  Downloading transformer_smaller_training_vocab-0.4.2-py3-none-any.whl.metadata (7.9 kB)
Collecting wikipedia-api>=0.5.7 (from flair->textattack)
  Downloading wikipedia_api-0.15.0-py3-none-any.whl.metadata (43 kB)
Collecting bioc<3.0.0,>=2.0.0 (from flair->textattack)
  Downloading bioc-2.1-py3-none-any.whl.metadata (4.6 kB)
Collecting jsonlines>=1.2.0 (from bioc<3.0.0,>=2.0.0->flair->textattack)
  Downloading jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Collecting intervaltree (from bioc<3.0.0,>=2.0.0->flair->textattack)
  Downloading intervaltree-3.2.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting docopt (from bioc<3.0.0,>=2.0.0->flair->textattack)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in ./.venv/lib/python3.12/site-packages (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair->textattack) (0.2.1)
Requirement already satisfied: protobuf in ./.venv/lib/python3.12/site-packages (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair->textattack) (6.33.4)
Collecting botocore<1.44.0,>=1.43.24 (from boto3>=1.20.27->flair->textattack)
  Downloading botocore-1.43.24-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.20.27->flair->textattack)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.19.0,>=0.18.0 (from boto3>=1.20.27->flair->textattack)
  Downloading s3transfer-0.18.0-py3-none-any.whl.metadata (1.7 kB)
Collecting wrapt<3,>=1.10 (from deprecated>=1.2.13->flair->textattack)
  Downloading wrapt-2.2.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (7.4 kB)
Requirement already satisfied: wcwidth in ./.venv/lib/python3.12/site-packages (from ftfy>=6.1.0->flair->textattack) (0.3.2)
Collecting beautifulsoup4 (from gdown>=4.4.0->flair->textattack)
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.12/site-packages (from matplotlib->bert-score>=0.3.5->textattack) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.12/site-packages (from matplotlib->bert-score>=0.3.5->textattack) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.12/site-packages (from matplotlib->bert-score>=0.3.5->textattack) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.12/site-packages (from matplotlib->bert-score>=0.3.5->textattack) (1.4.9)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.12/site-packages (from matplotlib->bert-score>=0.3.5->textattack) (12.1.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.12/site-packages (from matplotlib->bert-score>=0.3.5->textattack) (3.3.2)
Requirement already satisfied: joblib>=1.3.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn>=1.0.2->flair->textattack) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn>=1.0.2->flair->textattack) (3.6.0)
Requirement already satisfied: accelerate>=0.26.0 in ./.venv/lib/python3.12/site-packages (from transformers>=4.30.0->textattack) (1.12.0)
Requirement already satisfied: psutil in ./.venv/lib/python3.12/site-packages (from accelerate>=0.26.0->transformers>=4.30.0->textattack) (7.2.1)
Collecting click==8.4.1 (from wikipedia-api>=0.5.7->flair->textattack)
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting tenacity==9.1.4 (from wikipedia-api>=0.5.7->flair->textattack)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->gdown>=4.4.0->flair->textattack)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Collecting sortedcontainers (from intervaltree->bioc<3.0.0,>=2.0.0->flair->textattack)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.12/site-packages (from jinja2->torch!=1.8,>=1.7.0->textattack) (3.0.3)
Collecting toml (from language-tool-python->textattack)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Collecting anytree (from OpenHowNet->textattack)
  Downloading anytree-2.13.0-py3-none-any.whl.metadata (8.0 kB)
Collecting PySocks!=1.5.7,>=1.5.6 (from requests[socks]->gdown>=4.4.0->flair->textattack)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Downloading textattack-0.3.10-py3-none-any.whl (445 kB)
Downloading editdistance-0.8.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (418 kB)
Downloading flair-0.15.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.8 MB/s  0:00:00 eta 0:00:01
Downloading bioc-2.1-py3-none-any.whl (33 kB)
Downloading conllu-4.5.3-py2.py3-none-any.whl (16 kB)
Downloading boto3-1.43.24-py3-none-any.whl (140 kB)
Downloading botocore-1.43.24-py3-none-any.whl (15.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 2.6 MB/s  0:00:05 eta 0:00:01
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.18.0-py3-none-any.whl (88 kB)
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading wrapt-2.2.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (169 kB)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
Downloading gdown-6.1.0-py3-none-any.whl (19 kB)
Downloading jsonlines-4.0.0-py3-none-any.whl (8.7 kB)
Downloading more_itertools-11.1.0-py3-none-any.whl (72 kB)
Downloading mpld3-0.5.12-py3-none-any.whl (203 kB)
Downloading pytorch_revgrad-0.2.0-py3-none-any.whl (4.6 kB)
Downloading segtok-1.5.11-py3-none-any.whl (24 kB)
Downloading transformer_smaller_training_vocab-0.4.2-py3-none-any.whl (14 kB)
Downloading wikipedia_api-0.15.0-py3-none-any.whl (129 kB)
Downloading click-8.4.1-py3-none-any.whl (116 kB)
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Downloading intervaltree-3.2.1-py2.py3-none-any.whl (25 kB)
Downloading language_tool_python-3.4.0-py3-none-any.whl (63 kB)

In [11]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, 
    num_labels=2
    ).to(device) 
print(f"Using device: {device}")

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at dumitrescustefan/bert-base-romanian-cased-v1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Using device: cuda

In [13]:
training_args = TrainingArguments(
    output_dir="results/good/district-ro-bert-base",
    learning_rate=2e-5,
    lr_scheduler_type="cosine",
    warmup_steps=200,
    warmup_ratio=0.1,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    num_train_epochs=5,
    weight_decay=0.1,
    fp16=True,
    logging_steps=50,
    eval_steps=50,
    eval_strategy="steps",
    save_strategy="epoch",
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    compute_metrics=compute_metrics,
    data_collator=DataCollatorWithPadding(tokenizer=tokenizer)
)

trainer.train()

TrainOutput(global_step=2360, training_loss=0.34182550932391215, metrics={'train_runtime': 1411.2783, 'train_samples_per_second': 26.71, 'train_steps_per_second': 1.672, 'total_flos': 9917971231795200.0, 'train_loss': 0.34182550932391215, 'epoch': 5.0})

In [14]:
from transformers import AutoModelForSequenceClassification

# Load the trained model from checkpoint

checkpoint_path = "results/good/district-ro-bert-base/checkpoint-1888"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint_path).to(device)
print(f"Model loaded from {checkpoint_path}")

Model loaded from results/good/district-ro-bert-base/checkpoint-1888

In [31]:
import torch
from textattack.models.wrappers import HuggingFaceModelWrapper
from textattack.datasets import Dataset
from textattack import Attack, AttackArgs, Attacker
from textattack.search_methods import GreedyWordSwapWIR
from textattack.transformations import WordSwapNeighboringCharacterSwap
from textattack.constraints.pre_transformation import RepeatModification, StopwordModification
from textattack.goal_functions import UntargetedClassification  # <--- Added this
from textattack import Attacker

# 1. Force evaluation settings and batch sizing
model.eval()
model_wrapper = HuggingFaceModelWrapper(model, tokenizer) 

# 2. Set up the Goal Function (Untargeted means: change the prediction to anything else)
goal_function = UntargetedClassification(model_wrapper)

print("Goal function set up successfully.")

# 3. Use a Character-Swap Transformation (No downloads required!)
transformation = WordSwapNeighboringCharacterSwap(
    random_one=True, 
    skip_first_char=True, 
    skip_last_char=True
)

print("Transformation set up successfully.")

# Stopwords to avoid breaking fundamental legal tokens (e.g., "Art.", "Cod")
constraints = [
    RepeatModification(),
    StopwordModification()
]

print("Constraints set up successfully.")

# 4. Initialize Search Method with the Goal Function
search_method = GreedyWordSwapWIR(wir_method="unk")

print("Search method set up successfully.")

# 5. Construct the custom attack passing all components correctly
attack = Attack(goal_function, constraints, transformation, search_method)

print("Attack constructed successfully.")

textattack: Unknown if model of class <class 'transformers.models.bert.modeling_bert.BertForSequenceClassification'> compatible with goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'>.

Goal function set up successfully.
Transformation set up successfully.
Constraints set up successfully.
Search method set up successfully.
Attack constructed successfully.

In [32]:
# 6. Format dataset
attack_samples = []
for item in val_raw.select(range(200)):
    truncated_text = " ".join(item["text"].split()[:512]) 
    attack_samples.append((truncated_text, int(item["label"])))
textattack_dataset = Dataset(attack_samples)

# 7. Force execution over a wider evaluation block to confirm the ~20% rate
attack_args = AttackArgs(
    num_examples=50, # Evaluates until it gets 30 valid samples to build a stable metric
    attack_n=True
)

attacker = Attacker(attack, dataset=textattack_dataset, attack_args=attack_args)
attacker.attack_dataset()

Attack(
  (search_method): GreedyWordSwapWIR(
    (wir_method):  unk
  )
  (goal_function):  UntargetedClassification
  (transformation):  WordSwapNeighboringCharacterSwap(
    (random_one):  True
  )
  (constraints):
    (0): RepeatModification
    (1): StopwordModification
  (is_black_box):  True
)

--------------------------------------------- Result 1 ---------------------------------------------
[[1 (85%)]] --> [[[FAILED]]]

xxxxNUMExxxx, pretinzînd că este avocata xxxxNUMExxxx, care activează în baza licenței nr. 2295 din 21.12.2011, urmărind scop de profit, prin înșelăciune și abuz de încredere, a încheiat contract de asistență juridică, nr. 26 din 16.01.2014, cu xxxxNUMExxxx, succesorul părții vătămate pe cauza penală nr. 2013320554, de învinuire a lui Petcu Viorel, în comiterea infracțiunii prevăzute de art. 145 alin. (1) Cod Penal, și a prezentat în instanța de judecată, mandatul nr. 0474957 din 16.01.2014, prin care s­a împuternicit să acorde lui xxxxNUMExxxx asistență juridică în toate instanțele de judecată, dobîndind ilicit de la ultimul mijloace bănești în sumă de 5000 lei. În cadrul părţii pregătitoare a şedinţei de judecată, partea vătămată xxxxNUMExxxx a depus cerere prin care a solicitat încetarea procesului penal din motivul că s­a împăcat cu inculpata xxxxNUMExxxx şi careva pretenţii faţă de ea nu are. Inculpata xxxxNUMExxxx vina în comiterea infracţiunii încriminate a recunoscut­o integral, de asemenea a depus cerere, prin care a solicitat încetarea procesului penal în legătură că s­a împăcat cu partea vătămată xxxxNUMExxxx, paguba materială fiind restituită integral. Vina inculpatei xxxxNUMExxxx în comiterea faptei prejudiciabile mai este confirmată prin: procesul­verbal cu declaraţiile părții vătămate xxxxNUMExxxx (f. d.71), care a declarat că 19 septembrie 2013, a fost omorît fiul U.M.. Pe cazul dat a fost intentată o cauză penală în cadrul căreia a fost recunoscut în calitate de succesor al părții vătămate. Fiica O., care locuiește în Federația Rusă, i­a comunicat că are o prietenă, care activează în calitate de avocat în mun. Chișinău și poate să­l ajute în instanța de judecată. După discuția cu fiica, s­a întîlnit cu xxxxNUMExxxx (la acel moment nu cunoştea numele ei adevărat), cu care a semnat un contract, potrivit căruia ultima se angaja s­i apere interesele. În instanța de judecată persona în cauză s­a prezentat ca fiind avocatul xxxxNUMExxxx. Pentru serviciile acordate i­a achitat suma de 5000 lei. Ulterior, a plecat în Federația Rusă, solicitînd în baza cererii examinarea cauzei în lipsa sa, interesele în continuare urmînd a­i fi apărate de către avocat. În timp ce se afla în Federația Rusă, a aflat că persoana cu care a încheiat contract de asistență juridică, nu este avocat și în instanța de judecată s­a prezentat din numele altei persoane. La revenirea în Republica Moldova, a aflat că persoana în cauză este xxxxNUMExxxx. Ultima i­a restituit integral paguba pricinuită și careva pretenții față de ea nu are; procesul­verbal cu declaraţiile martorului xxxxNUMExxxx (f. d.73), care a declarat că, activează în calitate de președinte al Centrului de Investigații și Apărare a Drepturilor Omului. Avocatul xxxxNUMExxxx este în contract de colaborare cu centrul, din care motiv toate scrisorile, răspunsurile și citațiile ce țin de dosarele sale, le deschide, le citește și le înregistrează în registru de evidență. În ceea ce privește cealaltă corespondență, doar semnează avizul de recepție, fără a o deschide. Scrisoarea din 19.05.2014, expediată în adresa avocatului xxxxNUMExxxx, a primit­o, iar ulterior i­a transmis­o ultimei; procesul­verbal cu declaraţiile martorului xxxxNUMExxxxxxxxNUMExxxxu (f. d.74­75), care a declarat că, activează în calitate de avocat în mun. Chișinău. La 14.01.2014, i­a transmis lui xxxxNUMExxxx, mandatul nr. 0474957 din

--------------------------------------------- Result 2 ---------------------------------------------
[[1 (98%)]] --> [[0 (50%)]]

[[Prin]] sentinţa nominalizată xxxxNUMExxxx a fost [[condamnat]] [[pentru]], că în noaptea de 08.10.2012, intenționat, cu scopul sustragerii bunurilor altei persoane, aflîndu­se în casa lui G R de pe str.r.din or.[[xxxxORAS_SATxxxx]], a atacat­o pe G R cu un cuțit de bucătărie și i­a aplicat acesteia mai multe lovituri în regiunea [[toracelui]] și abdomenului cauzîndu­i astfel leziuni corporale grave periculoase pentru viață sub formă de plagă [[nepenetrantă]] la peretele abdominal anterior pe stînga cu dimensiunile 2,5 cm x 0,8 cm și [[adîncimea]] de 2,3 cm, trei plăgi [[nepetetrante]] în regiunea [[toracelui]] pe stînga la nivelul intercostal 3­5 linia anatomică [[parasternală]] cu dimensiunile 1,6 cm x 0,5 cm, 1,8 cm x0,5 cm, 2,9 cm x 0,7 cm și adfîncimea de pînă la 1,8 cm, o plagă penetrabtă în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică [[parasternală]] amplasată inferior la glanda [[mamară]] cu dimensiunile 4,6 cm x 1,3 cm cu lezarea lobului superior a pulmonului stîng pe suprafața anterior laterală stînga, hematorox masiv pe stînga, două plăgi tăiate la degetele patru și cinci a mîinii stîngi la falanga distală cu dimensiunile de 1,1 x 0,2 cm și 1,5 x 0,2 cm, [[excoreație]] în regiunea [[zigomatică]] stînga în urma cărora GR a decedat pe loc, luînd din casă un telefon mobil de model „” cu prețul de 600 lei, un lanț din aur cu greutatea de 19 gr. la prețul de 13680 lei și un pandativ din aur cu greutatea de 2 gr. la prețul de 1440 lei. Tot el, în [[noaptea]] de 08.10.2012, aproximativ în jurul orelor 03:00, fiind în stare de [[ebrietate]] alcoolică, aflîndu­se în lociunța cet.G R, asmplasată în orașul xxxxORAS_SATxxxx, str., [[intenționat]], urmărind scopul de profit, de sustragere a bunurilor altei persoane, avînd în mînă un cuțit de bucătărie, care l­a utilizat în calitate de armă, aplicînd o violență periculoasă pentru viața și sănătatea persoanei agresate, a atacat gazda casei, lovind­o în repetate rînduri cu pumnul, piciorul, precum și cu cuțitul în regiunea toracelui și abdomenului, pricinuindu­i lui G R leziuni corporale Grave periculoase pentru viața persoanei sub formă de plagă nepenetrantă la peretele abdominal anterior pe stînga cu dimensiunile 2,5 cm x 0,8 cm și adîncimea 2,3 cm, trei plăgi nepenetrante în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică parasternală, cu dimensiunile 1,6 cm x 0,5 cm, 1,8 cm x 0,5 cm, 2,9 cm x 0,7 cm și adîncimea de pînă la 1,8 cm, o plagă penetrantă în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică parasternală amplasată inferior la glnda mamară cu dimensiunile 4,6 cm x 1,3 cm cu lezarea lobului superior a pulmonului stîng pe suprafața anterioar – laterală stînga, hematorox masiv pe stînga, două plăgi tăiate la degetele 4 și 5 a mînei stîngi la falanga distală cu dimensiunile de 1,1 x 0,2 cm și 1,5 x 0,2 cm, excoreație în regiunea zigomatică stînga, după care în mod deschis a sustras de la victimă un telefon mobil de model „ la prețul de 600 lei, un lanț din aur cu greutatea de 19 grame la preț de 13680 lei și un

[[Pirn]] sentinţa nominalizată xxxxNUMExxxx a fost [[condamant]] [[pnetru]], că în noaptea de 08.10.2012, intenționat, cu scopul sustragerii bunurilor altei persoane, aflîndu­se în casa lui G R de pe str.r.din or.[[xxxxORASS_ATxxxx]], a atacat­o pe G R cu un cuțit de bucătărie și i­a aplicat acesteia mai multe lovituri în regiunea [[toracleui]] și abdomenului cauzîndu­i astfel leziuni corporale grave periculoase pentru viață sub formă de plagă [[nepenterantă]] la peretele abdominal anterior pe stînga cu dimensiunile 2,5 cm x 0,8 cm și [[adînciema]] de 2,3 cm, trei plăgi [[npeetetrante]] în regiunea [[troacelui]] pe stînga la nivelul intercostal 3­5 linia anatomică [[paratsernală]] cu dimensiunile 1,6 cm x 0,5 cm, 1,8 cm x0,5 cm, 2,9 cm x 0,7 cm și adfîncimea de pînă la 1,8 cm, o plagă penetrabtă în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică [[paarsternală]] amplasată inferior la glanda [[mmaară]] cu dimensiunile 4,6 cm x 1,3 cm cu lezarea lobului superior a pulmonului stîng pe suprafața anterior laterală stînga, hematorox masiv pe stînga, două plăgi tăiate la degetele patru și cinci a mîinii stîngi la falanga distală cu dimensiunile de 1,1 x 0,2 cm și 1,5 x 0,2 cm, [[excoerație]] în regiunea [[zigoamtică]] stînga în urma cărora GR a decedat pe loc, luînd din casă un telefon mobil de model „” cu prețul de 600 lei, un lanț din aur cu greutatea de 19 gr. la prețul de 13680 lei și un pandativ din aur cu greutatea de 2 gr. la prețul de 1440 lei. Tot el, în [[noatpea]] de 08.10.2012, aproximativ în jurul orelor 03:00, fiind în stare de [[ebriettae]] alcoolică, aflîndu­se în lociunța cet.G R, asmplasată în orașul xxxxORAS_SATxxxx, str., [[intențoinat]], urmărind scopul de profit, de sustragere a bunurilor altei persoane, avînd în mînă un cuțit de bucătărie, care l­a utilizat în calitate de armă, aplicînd o violență periculoasă pentru viața și sănătatea persoanei agresate, a atacat gazda casei, lovind­o în repetate rînduri cu pumnul, piciorul, precum și cu cuțitul în regiunea toracelui și abdomenului, pricinuindu­i lui G R leziuni corporale Grave periculoase pentru viața persoanei sub formă de plagă nepenetrantă la peretele abdominal anterior pe stînga cu dimensiunile 2,5 cm x 0,8 cm și adîncimea 2,3 cm, trei plăgi nepenetrante în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică parasternală, cu dimensiunile 1,6 cm x 0,5 cm, 1,8 cm x 0,5 cm, 2,9 cm x 0,7 cm și adîncimea de pînă la 1,8 cm, o plagă penetrantă în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică parasternală amplasată inferior la glnda mamară cu dimensiunile 4,6 cm x 1,3 cm cu lezarea lobului superior a pulmonului stîng pe suprafața anterioar – laterală stînga, hematorox masiv pe stînga, două plăgi tăiate la degetele 4 și 5 a mînei stîngi la falanga distală cu dimensiunile de 1,1 x 0,2 cm și 1,5 x 0,2 cm, excoreație în regiunea zigomatică stînga, după care în mod deschis a sustras de la victimă un telefon mobil de model „ la prețul de 600 lei, un lanț din aur cu greutatea de 19 grame la preț de 13680 lei și un

--------------------------------------------- Result 3 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Prin sentinţa Judecătoriei Soroca din 21.10.2004 x a fost condamnat în baza art.172 al.(3) pct.c) Cod penal RM la pedeapsă sub formă de 15 ani închisoare în peniteciar de tip închis. Începutul termenului –03.09.2004, sfîrşitul termenului ­02.09.2019. La data de 28.06.2016 șeful­adjunct al Penitenciarului nr.6 Soroca Cebotari Alexandru a înaintat în instanța de judecată demers, prin care a solicitat examinarea posibilității liberării condiționate de pedeapsă înainte de termen a condamnatului x. În motivarea demersului a indicat, că condamnatul x a ispășit ¾ din pedeapsa stabilită în conformitate cu legislația în vigoare, se caraterizează satisfăcător, pe perioada executării pedepsei a fost stimulat de două ori, a fost sancționat disciplinar o singură dată cu mustrare la data de 21.12.2005, sancțiune care la moment este stinsă, anterior a participat la muncile neremunerate, prejudiciul material lipsește și menține relațiile cu rudele. Prin încheierea Judecătoriei Soroca din XXXXXXXXX s­a dispus respingerea demersului administrației Penitenciarului nr.6 Soroca privind liberarea condiționată de pedeapsă înainte de termen a condamnatului x ca fiind neîntemeiat. Împotriva încheierei nominalizate în termen a declarat recurs condamnatul x, care nu este de acord cu încheierea instanței de fond. În motivarea recursului a indicat că a executat deja 11 ani din pedeapsa stabilită, este bonav de tuberculoză de formă deschisă și nu poate lucra din cauza bolii de care suferă. Solicită admiterea recursului, cu aplicarea în privința sa a prevederilor art.91 Cod penal RM și liberarea condiționată de pedeapsă înainte de termen. În instanţa de recurs condamnatul x a susținut recursul declarat și a solicitat admiterea acestuia din motivele invocate, cu aplicarea în privința sa a prevederilor art.91 Cod penal RM. Avocatul Pralea Grigore a solicitat admiterea recursului, casarea încheierii şipronunţarea unei noi hotărîri, prin care în privința condamnatului să fie aplicate prevederile art.91 Cod penal RM. Procurorul participant Prisacari Lilia a solicitat respingerea recursului declarat de condamnat ca fiind nefondat, cu menţinerea încheierii instanţei de fond ca fiind legală şi întemeiată. Verificînd argumentele invocate în recurs în raport cu materialele cauzei prezentate instanţei şi audiind opinia participanţilor la proces, Colegiul penal ajunge la concluzia, că recursul declarat de condamnatul x urmează a fi respins ca fiind nefondat din următoarele considerente. Conform art.449 al.(1) pct.1) lit.a) CPP RM judecînd recursul, instanţa adoptă una din următoarele decizii: 1) respinge recursul, menţinînd hotărîrea atacată, dacă: lit.a) recursul este nefondat. În conformitate cu prevederile art.91 al.(1) Cod penal RM persoanelor care execută pedeapsa cu închisoare, care au reparat integral daunele cauzate de infracţiunea pentru care sînt condamnate, care au participat la executarea şi care nu au refuzat executarea, în conformitate cu prevederile art.253 din Codul de executare, a muncilor remunerate sau neremunerate de îngrijire sau amenajare a penitenciarului şi a teritoriului, de îmbunătăţire a condiţiilor de trai şi medico­sanitare de detenţie li se poate aplica liberarea condiţionată de pedeapsă înainte de termen dacă instanţa de judecată va considera posibilă corectarea condamnatului fără executarea deplină a pedepsei. Totodată, persoana poate fi liberată, în întregime sau parţial, şi de pedeapsa complementară. Colegiul consideră că instanţa de fond la examinarea demersului înaintat de șeful adjunct al penitenciarului nr.6 Soroca Cebotari Alexandru a

--------------------------------------------- Result 4 ---------------------------------------------
[[1 (84%)]] --> [[0 (74%)]]

Inculpații xxxxNUMExxxx și xxxxNUMExxxx se învinuiesc de că către organul de urmărire penală de faptul că, la 10.05.2014, ora 15:30, fiind efectuată de către colaboratorii Penitenciarului nr. 17 Rezina, percheziţia corporală a deţinutului xxxxNUMExxxx, la finele întrevederii de scurtă durată a acestuia cu soţia sa xxxxNUMExxxx, s­a depistat la acesta un pachet din material polimeric de culoare galben­transparent, o seringă medicală de unică folosinţă capacitatea de 20 ml., două „bile” din material polimeric transparent, în care în care se afla o masă vegetală uscată, de culoare verde, mărunţită, cu miros specific, asemănător cu cel de cînepă. Conform concluziei raportului de constatare tehnico­ştiinţifică nr. 4444 din 20.05.2014, masele vegetale de culoare verde, mărunţită, uscată, prezentată la examinare într­un pachet din material polimeric de culoare galben­transparent (21,20 grame), într­o seringă medicală de unică folosinţă capacitatea de 20 ml ( 16,72 grame) şi în două „bile” din material polimeric transparent (19,42 grame şi 4,50 grame), depistate şi ridicate la 10.05.2014 de către colaboratorii Penitenciarului nr. 17 Rezina, reprezintă marihuană, care face parte in categoria substanţelor narcotice. Cantitatea substanţei narcotice ­ marihuana constituie 61,84 grame (stare uscată), care conform Hotărîrei de Guvern nr.79 din 23.01.2006 privind aprobarea listei substanţelor narcotice, psihotrope şi a plantelor care conţin astfel de substanţe depistate în trafic ilicit, precum şi cantităţile acestora, reprezintă substanţe narcotice în proporţii mari. Inculpații xxxxNUMExxxx și xxxxNUMExxxx se învinuiesc că prin acţiunile lor intenţionate au săvîrşit infracţiunile prevăzute de art. 217/1 alin. (3) lit. b), e), f) şi art. 322 alin. (1) Cod [[penal]], adică păstrarea substanţelor narcotice în proporţii mari, de două persoane, pe teritoriul instituţiilor penitenciare, săvîrşite în scop de instrănare, substanţe care au fost transmise tănuit de la control, deţinutului în penitenciar. În ședința de judecată s­a constatat că, la 10.05.2014, ora 15:30, fiind efectuată de către colaboratorii Penitenciarului nr. 17 Rezina, percheziţia corporală a deţinutului xxxxNUMExxxx , la finele întrevederii de scurtă durată a acestuia cu soţia sa xxxxNUMExxxx , la el s­a depistat un pachet din material polimeric de culoare galben­transparent, o seringă medicală de unică folosinţă capacitatea de 20 ml., două „bile” din material polimeric transparent, în care se afla o masă vegetală uscată, de culoare verde, mărunţită, cu miros specific, asemănător cu cel de cînepă. xxxxNUMExxxx nu a fost prezentă la efectuarea percheziției lui xxxxNUMExxxx. În cadrul efectuării percheziției corporale a xxxxNUMExxxxristinei , atît la trecerea punctului de control,cît și la finele întrevederii, nu au fost depistate nici un fel de obiecte sau substanțe interzise. Inculpatul xxxxNUMExxxx, în cadrul urmăririi penale în calitate de bănuit și învinuit nu a recunoscut vina și nu a dorit să depună careva declarații, folosindu­se de dreptul de a tăcea. În şedinţa de judecată, inculpatul, la fel, a negat vina și a declarat că, se deține în Penitenciarul nr. 17 din februarie 2014. A avut întrevederi cu soția. A început a consuma marihuana de cînd era la libertate, iar în IP­17 Rezina s­a interesat la băieți cum obține marihuană. Condamnatul , cu care se deținea în aceeași celulă i­a spus că cunoaște pe cineva din colaboratori care poate să hotăracă întrebarea și i­l va

Inculpații xxxxNUMExxxx și xxxxNUMExxxx se învinuiesc de că către organul de urmărire penală de faptul că, la 10.05.2014, ora 15:30, fiind efectuată de către colaboratorii Penitenciarului nr. 17 Rezina, percheziţia corporală a deţinutului xxxxNUMExxxx, la finele întrevederii de scurtă durată a acestuia cu soţia sa xxxxNUMExxxx, s­a depistat la acesta un pachet din material polimeric de culoare galben­transparent, o seringă medicală de unică folosinţă capacitatea de 20 ml., două „bile” din material polimeric transparent, în care în care se afla o masă vegetală uscată, de culoare verde, mărunţită, cu miros specific, asemănător cu cel de cînepă. Conform concluziei raportului de constatare tehnico­ştiinţifică nr. 4444 din 20.05.2014, masele vegetale de culoare verde, mărunţită, uscată, prezentată la examinare într­un pachet din material polimeric de culoare galben­transparent (21,20 grame), într­o seringă medicală de unică folosinţă capacitatea de 20 ml ( 16,72 grame) şi în două „bile” din material polimeric transparent (19,42 grame şi 4,50 grame), depistate şi ridicate la 10.05.2014 de către colaboratorii Penitenciarului nr. 17 Rezina, reprezintă marihuană, care face parte in categoria substanţelor narcotice. Cantitatea substanţei narcotice ­ marihuana constituie 61,84 grame (stare uscată), care conform Hotărîrei de Guvern nr.79 din 23.01.2006 privind aprobarea listei substanţelor narcotice, psihotrope şi a plantelor care conţin astfel de substanţe depistate în trafic ilicit, precum şi cantităţile acestora, reprezintă substanţe narcotice în proporţii mari. Inculpații xxxxNUMExxxx și xxxxNUMExxxx se învinuiesc că prin acţiunile lor intenţionate au săvîrşit infracţiunile prevăzute de art. 217/1 alin. (3) lit. b), e), f) şi art. 322 alin. (1) Cod [[peanl]], adică păstrarea substanţelor narcotice în proporţii mari, de două persoane, pe teritoriul instituţiilor penitenciare, săvîrşite în scop de instrănare, substanţe care au fost transmise tănuit de la control, deţinutului în penitenciar. În ședința de judecată s­a constatat că, la 10.05.2014, ora 15:30, fiind efectuată de către colaboratorii Penitenciarului nr. 17 Rezina, percheziţia corporală a deţinutului xxxxNUMExxxx , la finele întrevederii de scurtă durată a acestuia cu soţia sa xxxxNUMExxxx , la el s­a depistat un pachet din material polimeric de culoare galben­transparent, o seringă medicală de unică folosinţă capacitatea de 20 ml., două „bile” din material polimeric transparent, în care se afla o masă vegetală uscată, de culoare verde, mărunţită, cu miros specific, asemănător cu cel de cînepă. xxxxNUMExxxx nu a fost prezentă la efectuarea percheziției lui xxxxNUMExxxx. În cadrul efectuării percheziției corporale a xxxxNUMExxxxristinei , atît la trecerea punctului de control,cît și la finele întrevederii, nu au fost depistate nici un fel de obiecte sau substanțe interzise. Inculpatul xxxxNUMExxxx, în cadrul urmăririi penale în calitate de bănuit și învinuit nu a recunoscut vina și nu a dorit să depună careva declarații, folosindu­se de dreptul de a tăcea. În şedinţa de judecată, inculpatul, la fel, a negat vina și a declarat că, se deține în Penitenciarul nr. 17 din februarie 2014. A avut întrevederi cu soția. A început a consuma marihuana de cînd era la libertate, iar în IP­17 Rezina s­a interesat la băieți cum obține marihuană. Condamnatul , cu care se deținea în aceeași celulă i­a spus că cunoaște pe cineva din colaboratori care poate să hotăracă întrebarea și i­l va

--------------------------------------------- Result 5 ---------------------------------------------
[[1 (53%)]] --> [[0 (93%)]]

Prin sentinţa Judecătoriei raionale Sankt Petersburg Federaţia Rusă din 20.02.2013, GA a fost condamnat în baza art.30 alin.(1), art. 228­1 alin.(3) CP al Federaţiei Ruse la 8 ani închisoare cu regim înăsprit. Prin încheierea Judecătoriei Buiucani mun.Chişinău din 20.11.2014, condamnatul GA a fost transferat pentru ispășirea pedepsei penale în instituţiile penitenciare din R.Moldova, fiindu­i recunoscută condamnarea în baza art.26, 217/1 alin.(4) lit.d) CP la pedeapsa închisorii pe un termen de 8 ani şi calcularea termenului din 22.07.2010 cu posibilitatea liberării condiționate de pedeapsă înainte de termen la ispășirea efectivă a 3/4 din termenul de pedeapsă stabilit. Începutul termenului 22.07.2010 și sfârșitul termenului 21.07.2018. GA s­a adresat în instanța de judecată cu o cerere privind liberarea condiționată de pedeapsă înainte de termen, motivând că a sesizat comisia administrației Penitenciarului nr.6 Soroca, unde i­a fost refuzat de a fi prezentate materialele în instanţa de judecată, fapt cu care nu a fost de acord. Judecând cererea condamnatului, [[instanța]] a stabilit, că GA, la 22.07.2016 a executat fracția de 3/4 din pedeapsă pentru aplicarea prevederilor cu privire la liberarea condiționată înainte de termen, deci condiția legală relativă la timpul din pedeapsă ce trebuie executat este îndeplinită şi depășită cu 3 luni. Pe lângă acest criteriu obiectiv, instanța a notat că condamnatul nu are sancțiuni disciplinare valabile şi dă dovezi temeinice de îndreptare. Conform extrasului din procesul verbal al comisiei Penitenciarului nr.6 Soroca, GA a fost prezentat la comisie la 15.08.2016, în urma căreia i­a fost refuzat în aplicarea art.91 CP, din motiv că pe perioada ispășirii pedepsei a fost sancționat de 3 ori, toate în F.Rusă, ultima la 14.08.2013, sancțiuni care la moment sunt stinse, nu participă la procesul de instruire generală şi/sau profesională, nu este implicat în activități de educație socială şi nu este încadrat în câmpul muncii. Instanţa a apreciat, că caracteristica prezentată de administrație nu conține o concluzie corectă privind comportamentul lui GA, de unde reiese, că regimul de detenție în ultimii 3 ani nu­l încalcă, în conflicte cu administrația nu intră, pe parcursul ispășirii termenului de pedeapsă a dat dovadă de un comportament satisfăcător, nu se bucură de autoritate în mediul deținuților care mențin tradițiile hoțești sau care necesită supraveghere sporită, menține legătura cu familia şi rudele, la moment se caracterizează ca tip echilibrat, sociabil, prezintă risc de recidivă mediu. Instanța a notat, că atitudinea şi comportamentul condamnatului din ședința de judecată, precum şi raportul de evaluare prezentat, dau temei de a avea încredere că riscul lui de recidivare a scăzut considerabil. Făcând referire la prevederile art.240 alin.(1),(5),(7) Codului de executare instanța a reținut, că GA are studii superioare de scurtă durată şi în asemenea condiții nu există careva perspective de a­i evalua calitățile profesioniste ca negative. Instanța a concluzionat, că nu există dovezi că GA nu s­ar fi îndreptat şi nu ar fi înțeles rolul pedepsei și că ar fi refuzat vreodată de a munci. Poziția administrației instituției unde își ispășește pedeapsa condamnatul şi a procurorului instanța a considerat­o formală, nejustificată, or, nu are la bază dovezi din care să rezulte contrariul situației de îndreptare al condamnatului şi comportamentului corespunzător. În

Prin sentinţa Judecătoriei raionale Sankt Petersburg Federaţia Rusă din 20.02.2013, GA a fost condamnat în baza art.30 alin.(1), art. 228­1 alin.(3) CP al Federaţiei Ruse la 8 ani închisoare cu regim înăsprit. Prin încheierea Judecătoriei Buiucani mun.Chişinău din 20.11.2014, condamnatul GA a fost transferat pentru ispășirea pedepsei penale în instituţiile penitenciare din R.Moldova, fiindu­i recunoscută condamnarea în baza art.26, 217/1 alin.(4) lit.d) CP la pedeapsa închisorii pe un termen de 8 ani şi calcularea termenului din 22.07.2010 cu posibilitatea liberării condiționate de pedeapsă înainte de termen la ispășirea efectivă a 3/4 din termenul de pedeapsă stabilit. Începutul termenului 22.07.2010 și sfârșitul termenului 21.07.2018. GA s­a adresat în instanța de judecată cu o cerere privind liberarea condiționată de pedeapsă înainte de termen, motivând că a sesizat comisia administrației Penitenciarului nr.6 Soroca, unde i­a fost refuzat de a fi prezentate materialele în instanţa de judecată, fapt cu care nu a fost de acord. Judecând cererea condamnatului, [[insatnța]] a stabilit, că GA, la 22.07.2016 a executat fracția de 3/4 din pedeapsă pentru aplicarea prevederilor cu privire la liberarea condiționată înainte de termen, deci condiția legală relativă la timpul din pedeapsă ce trebuie executat este îndeplinită şi depășită cu 3 luni. Pe lângă acest criteriu obiectiv, instanța a notat că condamnatul nu are sancțiuni disciplinare valabile şi dă dovezi temeinice de îndreptare. Conform extrasului din procesul verbal al comisiei Penitenciarului nr.6 Soroca, GA a fost prezentat la comisie la 15.08.2016, în urma căreia i­a fost refuzat în aplicarea art.91 CP, din motiv că pe perioada ispășirii pedepsei a fost sancționat de 3 ori, toate în F.Rusă, ultima la 14.08.2013, sancțiuni care la moment sunt stinse, nu participă la procesul de instruire generală şi/sau profesională, nu este implicat în activități de educație socială şi nu este încadrat în câmpul muncii. Instanţa a apreciat, că caracteristica prezentată de administrație nu conține o concluzie corectă privind comportamentul lui GA, de unde reiese, că regimul de detenție în ultimii 3 ani nu­l încalcă, în conflicte cu administrația nu intră, pe parcursul ispășirii termenului de pedeapsă a dat dovadă de un comportament satisfăcător, nu se bucură de autoritate în mediul deținuților care mențin tradițiile hoțești sau care necesită supraveghere sporită, menține legătura cu familia şi rudele, la moment se caracterizează ca tip echilibrat, sociabil, prezintă risc de recidivă mediu. Instanța a notat, că atitudinea şi comportamentul condamnatului din ședința de judecată, precum şi raportul de evaluare prezentat, dau temei de a avea încredere că riscul lui de recidivare a scăzut considerabil. Făcând referire la prevederile art.240 alin.(1),(5),(7) Codului de executare instanța a reținut, că GA are studii superioare de scurtă durată şi în asemenea condiții nu există careva perspective de a­i evalua calitățile profesioniste ca negative. Instanța a concluzionat, că nu există dovezi că GA nu s­ar fi îndreptat şi nu ar fi înțeles rolul pedepsei și că ar fi refuzat vreodată de a munci. Poziția administrației instituției unde își ispășește pedeapsa condamnatul şi a procurorului instanța a considerat­o formală, nejustificată, or, nu are la bază dovezi din care să rezulte contrariul situației de îndreptare al condamnatului şi comportamentului corespunzător. În

--------------------------------------------- Result 6 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Inculpata XXXXXXXXXX, la 11.03.2015, în a doua jumătate a zilei, ora exactă nu a fost posibil de stabilit în cadrul urmăririi penale, aflându­se în s. XXXXXXXXX, r­1 Ştefan Vodă, urmărind scopul răpirii copiilor săi minori, comuni cu fostul soţ XXXXXXXXX, şi anume XXXXXXXXa, a. n. XXXXXXX. XXXXX. a. n. XXXXXX şi XXXXXa, a. n. XXXXXX, care conform hotărârii Judecătoriei Ştefan Vodă, din 30.03.2011, au fost determinați cu traiul, la tatăl său, i­a luat pe aceștea împotriva voinţei cet. XXXXXXi, care este responsabil de educaţia copiilor sus indicaţi, şi i­a dus în s. XXXXXX r­1 Căuşeni, schimbându­i locul de trai, la domiciliul concubinului său, XXXXXXXXi. În şedinţa de judecată, pînă la începerea cercetării judecătoreşti, prin înscris autentic, inculpata XXXXXXXa declarat personal că recunoaşte săvîrşirea faptelor indicate în rechizitoriu şi solicită ca judecata să se facă pe baza probelor administrate în faza de urmărire penală, fără cercetarea martorilor. Obiecţii asupra probelor administrate nu are şi le recunoaşte fără careva rezerve. Apărătorul Olesea Durguz și acuzatorul de stat Diana Cernomorcenco au susţinut demersul inculpatei XXXXXX care în opinia lor a recunoscut în fond şi în totalitate faptele indicate în rechizitoriu, nu solicită administrarea de noi probe şi a solicitat ca judecata să se facă pe baza probelor administrate în faza de urmărire penală. În faţa instanţei inculpata XXXXXXX, sub jurămînt, prin expunerea factologică, ce nu contravine învinuirii formulate în rechizitoriu și­a recunoscut integral vinovăția și a declarat, că în una din zilele lunii martie 2015, se afla la domiciliul fostului său soţ, XXXXXX situat s. XXXXXXXXX r­nul Ştefan Vodă. Seara, XXXXXXXXi a început să o numească cu cuvinte înjurioase, cerîndu­i să plece. Ea a început să­şi strângă hainele pentru a merge în s. XXXXXXXX. Înainte de a se porni, fiicele sale minore, XXXX,XXXXXX şi XXXXXXX, au început să plângă, spunând că doresc să meargă cu ea, astfel a acceptat, deoarece îi era milă de acestea. Dînsa a îmbrăcat fiicele sale şi s­au dus în s. XXXXXXXXX, r­1 Căuşeni, fără a­1 informa pe fostul său soţ, care dormea. Împreună cu fiicele ei, au mers la domiciliul concubinului său, XXXXXXXXXX, la care şi locuieşte în prezent. Ulterior dînsa i­a comunicat fiicelor că urmează să plece la şcoală, la ce dînsele au început a plângă şi i­au spus că nu doresc acasă, deoarece le este frică de tatăl lor. A fost telefonată de către poliţistul de sector din s. XXXXXXXXX r­1 Ştefan Vodă, căruia i­a comunicat că fiicele sunt la ea. În următoarea zi, la domiciliul unde locuieşte, a venit poliţistul din satul XXXXXXXXX r­nul Ștefan Vodă și a luat fiicele. De cele comise se căieşte şi regretă. Culpa lui XXXXXXXXXX în răpirea minorelor de către o rudă apropiată, se confirmă și prin următoarele probe examinate în ședința de judecată, administrate la urmărirea penală: ­ plîngerea cetățeanului XXXXXXXXX, prin care solicită de a lua măsuri cu fosta soțieXXXXXXXX care la data de 11.03.2015 în jurul orelor 21:00 a luat copii de acasă fără voia lui, fără a­i comunica despre aceasta (f.d.­6); ­ proces ­ verbal de audiere a martorului XXXXXXXXX și XXXXXXXX(f.d.10­11); ­ hotărîrea instanței de judecată Ștefan

--------------------------------------------- Result 7 ---------------------------------------------
[[1 (60%)]] --> [[0 (51%)]]

Prin sentinţa Judecătoriei C din 08 iulie 2014, T D a fost recunoscut [[vinovat]] de săvîrşirea infracţiunilor prevăzute de 1 art.361 alin.(2) lit.b), c), art.264 alin.(1) Cod penal, şi i s­a stabilit pedeapsă: ­ în baza art. 361 alin.(2) lit.b),c) Cod penal­2 ani închisoare; 1 ­ în baza art. 264 alin.(1) Cod penal – amendă în mărime de 450 unități convenționale, echivalentul a 9000 lei, cu privarea de dreptul de a conduce mijloace de transport pe un termen de 3 ani. În conformitate cu art.84 alin.(3) Cod penal, pedepsele stabilite de executat de sine stătător. În conformitate cu art.85 Cod penal,prin cumul de sentințe, de cumulat parțial la pedeapsa aplicată prin noua sentință, pedeapsa neexecutată stabilită prin sentința Judecătoriei B, mun.Chișinău din 29 iunie 2011, stabilindu­i inculpatului XXXXXXXXX pedeapsa definitivă de 4 ani și 01 lună închisoare, cu executarea pedepsei în penitenciar de tip semiînchis și amendă în mărime de 450 unități convenționale, echivalentul a 9000 lei, care vor fi executate de sine stătător, cu privarea de dreptul de a conduce mijloace de transport pe un termen de 3 ani și de a exercita activitate ce ține de perfectarea documentelor pe un termen de 3 ani. Pentru a pronunța sentința instanța de fond a reținut următoarele: XXXXXXXXX, în perioada lunii mai 2011, avînd scopul confecționării documentelor oficiale false, care acordă drepturi, la solicitarea lui B I G, acționînd coordonat cu alte persoane nestabilite, a confecționat și deținut declarații cu numerele 1250, 1253, 1261, 1262, 1263, 1272 și 1273, din numele notarului public „I V” cu sediul mun.C, str.C nr.6, din 10 mai 2011, pe numele lui RS A, născută la 19 decembrie 19xx, D C I, născut la 23 decembrie 19xx și L O A, născut la 05 mai 19xx, toți locuitori ai satului L, r.n. C, care conțin date vădit false, privind eliberarea declarațiilor sub numerele sus indicate, așa cum sub acele numere au fost deja înregistrate la 10 mai 2011, potrivit registrului de evidență a actelor notariale a notarului public „I V” altor persoane și alte acte notariale, acte care ulterior în perioada lunii mai 2011, în apropierea stației de alimentare „L” din or.C, prin intermediul unei persoane neidentificate au fost vîndute contra sumei de 300 euro și 500 lei, cetățeanului B I G. Tot el, la data de 27 decembrie 2011, aproximativ la ora 18.30 minute, deținînd permis de conducere categoria „A”, „B”, „C”, „D”, „E” nr.109300391, a condus automobilul de model „O A” cu n/î SV AK xxx, pe traseul interurban C­C, în stare de ebrietate alcoolică prin ce a încălcat cerințele pct.14 lit.a) al Regulamentului Circulației Rutiere, potrivit căruia: conducătorului de vehicul îi este interzis să conducă vehiculul în stare de ebrietate, sub influența drogurilor sau alte substanțe contraindicate, sub influența preparatelor medicamentoase care provoacă reducerea reacției, fiind bolnav, traumatizat sau într­o stare avansată de oboseală de natură să­i afecteze capacitatea de conducere. Fiind stopat de către colaboratorii poliției în apropiere de barul „H S” de pe traseul R­34, la ieșirea din orașul C, și fiind supus testului prin metoda alcooscopică s­a constatat că, concentrația vaporilor de

Prin sentinţa Judecătoriei C din 08 iulie 2014, T D a fost recunoscut [[vniovat]] de săvîrşirea infracţiunilor prevăzute de 1 art.361 alin.(2) lit.b), c), art.264 alin.(1) Cod penal, şi i s­a stabilit pedeapsă: ­ în baza art. 361 alin.(2) lit.b),c) Cod penal­2 ani închisoare; 1 ­ în baza art. 264 alin.(1) Cod penal – amendă în mărime de 450 unități convenționale, echivalentul a 9000 lei, cu privarea de dreptul de a conduce mijloace de transport pe un termen de 3 ani. În conformitate cu art.84 alin.(3) Cod penal, pedepsele stabilite de executat de sine stătător. În conformitate cu art.85 Cod penal,prin cumul de sentințe, de cumulat parțial la pedeapsa aplicată prin noua sentință, pedeapsa neexecutată stabilită prin sentința Judecătoriei B, mun.Chișinău din 29 iunie 2011, stabilindu­i inculpatului XXXXXXXXX pedeapsa definitivă de 4 ani și 01 lună închisoare, cu executarea pedepsei în penitenciar de tip semiînchis și amendă în mărime de 450 unități convenționale, echivalentul a 9000 lei, care vor fi executate de sine stătător, cu privarea de dreptul de a conduce mijloace de transport pe un termen de 3 ani și de a exercita activitate ce ține de perfectarea documentelor pe un termen de 3 ani. Pentru a pronunța sentința instanța de fond a reținut următoarele: XXXXXXXXX, în perioada lunii mai 2011, avînd scopul confecționării documentelor oficiale false, care acordă drepturi, la solicitarea lui B I G, acționînd coordonat cu alte persoane nestabilite, a confecționat și deținut declarații cu numerele 1250, 1253, 1261, 1262, 1263, 1272 și 1273, din numele notarului public „I V” cu sediul mun.C, str.C nr.6, din 10 mai 2011, pe numele lui RS A, născută la 19 decembrie 19xx, D C I, născut la 23 decembrie 19xx și L O A, născut la 05 mai 19xx, toți locuitori ai satului L, r.n. C, care conțin date vădit false, privind eliberarea declarațiilor sub numerele sus indicate, așa cum sub acele numere au fost deja înregistrate la 10 mai 2011, potrivit registrului de evidență a actelor notariale a notarului public „I V” altor persoane și alte acte notariale, acte care ulterior în perioada lunii mai 2011, în apropierea stației de alimentare „L” din or.C, prin intermediul unei persoane neidentificate au fost vîndute contra sumei de 300 euro și 500 lei, cetățeanului B I G. Tot el, la data de 27 decembrie 2011, aproximativ la ora 18.30 minute, deținînd permis de conducere categoria „A”, „B”, „C”, „D”, „E” nr.109300391, a condus automobilul de model „O A” cu n/î SV AK xxx, pe traseul interurban C­C, în stare de ebrietate alcoolică prin ce a încălcat cerințele pct.14 lit.a) al Regulamentului Circulației Rutiere, potrivit căruia: conducătorului de vehicul îi este interzis să conducă vehiculul în stare de ebrietate, sub influența drogurilor sau alte substanțe contraindicate, sub influența preparatelor medicamentoase care provoacă reducerea reacției, fiind bolnav, traumatizat sau într­o stare avansată de oboseală de natură să­i afecteze capacitatea de conducere. Fiind stopat de către colaboratorii poliției în apropiere de barul „H S” de pe traseul R­34, la ieșirea din orașul C, și fiind supus testului prin metoda alcooscopică s­a constatat că, concentrația vaporilor de

--------------------------------------------- Result 8 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Inculpatul, xxxxxxxxx, la data de 06.11.2013, în perioada de timp cupinsă între orele 18:00­21:00, aflîndu­se în apartamentul xxxxxxxxx, ce aparține unchiului său xxxxx, folosindu­se de faptul că nu este observat de nimeni, prin acces liber, a sustras pe ascun bani în sumă de 3300 lei, cauzîndu­i părții vătămate xxxxxxxx o daună în proporții considerabile, eschivîndu­se cu cele sustrase de la locul infracțiunii. În cadrul şedinţei judiciare inculpatul xxxxxxxx şi­a recunoscut vinovăţia de comiterea celor incriminate şi a menţionat că la data de 06.11.2013 a fost la unchiul său xxxxxxxxxxx, unde a stat ceva timp. Avînd nevoie de bani a sustras de la unchiul său bani în sumă de 3300 lei. În ședința de judecată partea vătămată a înaintat o cerere prin care solicită instanţei de judecată încetarea procesului penal în privinţa lui xxxxxxxxxx în legătură cu faptul împăcării cu inculpatul. Procurorul și avocatul inculpatului au susţinut cererea părţii vătămate, invocând că legea penală prevede încetarea procesului penal în cazul împăcării părţilor. Astfel, vinovăţia inculpatului se confirmă prin probele prezentate de acuzatorul de stat în şedinţă şi acceptate de inculpat. Prin justeţea probelor instanţa de judecată consideră acţiunile inculpatului xxxxxxxxx corect încadrate în baza art.186 alin.(2) lit.d) Codului penal conform indicilor: furt, adică, sustragerea pe ascuns a bunurilor altei personae, săvîrşit cu cauzarea de daune în proporţii considerabile. Faptul dat şi­a găsit confirmare prin declaraţiile inculpatului şi materialele dosarului elucidate în cadrul anchetei judiciare. Analizând probele administrate, audiind participanţii la proces, instanţa de judecată conchide că demersul părţii vătămate privind încetarea cauzei penale este întemeiat şi posibil admiterii. Inculpatul Cușciuc Evghenii şi­a recunoscut vinovăţia, se căieşte sincer în cele comise. Părţile s­au împăcat şi partrea vătămată nu are pretenţii materiale şi morale faţă de inculpat şi solicită încetarea procesului penal în privinţa inculpatului xxxxxxxxxxxxx. Având în vedere cele expuse, călăuzindu­se de prevederile art. 391 al.(1) p.1) Codului de procedură penală, instanţa de judecată consideră că poate fi încetat procesul penal faţă de inculpatul xxxxxxx intentat în baza art.186 alin.(2) lit.d) Codului penal, deoarece părţile s­au împăcat şi legea penală permite împăcarea. Călăuzindu­se de prevederile art.109 Codului penal, art.332, 391 al.(1) p.1), 396 Codului de procedură penală, instanţa de judecată,


--------------------------------------------- Result 9 ---------------------------------------------
[[0 (97%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut, că inculpatul xxxxNUMExxxx, activînd în calitate de comisar­adjunct, şef poliţie de ordine publică a CPR Edineţ, numit în această funcţie prin ordinul MAI nr. 228 EF din 15.05.2009 şi fiind, astfel, la acel moment, conform art. 123 alin. (1) din Codul penal persoană cu funcţie de răspundere, contrar prevederilor art. 3 din Convenţia Europeană pentru Apărarea Drepturilor Omului şi a Libertăţilor Fundamentale, adoptată la Roma la 04.11.1950, la care Republica Moldova a aderat la 12.09.1997; art. 24, alin. (l) şi (2), art. 25, art. 27 alin. (l), din Constituţia Republicii Moldova, adoptată la 29.07.1994; art. 1­4, 12, 15 ale Legii nr. 416­XII din 18.12.1990 cu privire la poliţie (în vigoare la data săvîrşirii infracţiunii), art. 10, 11 din Codul de procedură penală, pct. 2, 4 şi 10 ale Statutului disciplinar al organelor afacerilor interne, aprobat prin Hotărîrea Guvernului Republicii Moldova nr. 2 din 04.02.1996 şi fişa postului, care­1 obligau să­şi desfăşoare activitatea pe baza respectării stricte a legilor, să protejeze viaţa, sănătatea şi libertăţile cetăţenilor, interesele societăţii şi ale statului de atentate criminale şi de alte atacuri nelegitime; să prevină şi curme crimele şi alte infracţiuni; să ia măsuri pentru apărarea vieţii, sănătăţii, onoarei, demnităţii cetăţenilor, să le asigure dreptul la libera circulaţie; să nu aplice nejustificat forţa fizică şi mijloacele speciale iar în caz de aplicare să comunice despre aceasta şefului său direct; să nu supună pe nimeni torturii, pedepselor sau tratamentelor crude, inumane ori degradante; să oprească pe cei din jur de la încălcarea ordinii de drept şi să contribuie activ la menţinerea prestigiului colaboratorului organelor afacerilor interne şi a demnităţii cetăţenilor; să educe subordonaţii săi în spiritul devotamentului faţă de Patrie şi popor, al întăririi continue a disciplinei de serviciu, regulilor de convieţuire socială şi a ordinii de drept ­ în loc de aceasta, intenţionat, a comis acte de tortură în privinţa cet. xxxxCUSTOM2xxxx în următoarele împrejurări. Astfel, la 14.03.2013, între orele 12­13, xxxxNUMExxxx, fiind persoană cu funcţie de răspundere şi acţionând cu titlu oficial, reprezentând Ministerul Afacerilor Interne, aflându­ se în biroul său de serviciu amplasat în incinta CPR Edineţ, or. Edineţ str. Ştefan Vodă 5, sub pretextul, că inspectorul grupei de autorizări al CPR Edineţ xxxxCUSTOM2xxxx, căruia îi era şef nemijlocit, nu a acceptat să procure şi să consume cu el băuturi alcoolice, cu scopul de a­1 pedepsi pentru acest fapt, l­a instigat pe cet. xxxxCUSTOM1xxxx să­l lovească pe numit, ceea ce ultimul a şi realizat prin aplicarea unui şir de lovituri cu picioarele şi pumnii peste cap, acţiuni care fiind efectuate la instigarea cet. xxxxNUMExxxx precum şi comise în incinta unei instituţii de stat, au căpătat calitatea celor săvîrşite cu titlul oficial. În acelaşi timp şi circumstanţe, după ce xxxxCUSTOM2xxxx a căzut la podea în rezultatul loviturilor aplicate de către cet. xxxxCUSTOM1xxxx, xxxxNUMExxxx, sub acelaşi pretext, că nu a îndeplinit o solicitare ilegală, cu acelaşi scop, de a­1 pedepsi pentru nesupunere, personal i­a aplicat intenţionat lui xxxxCUSTOM2xxxx multiple lovituri cu pumnii şi cu picioarele peste mai multe părţi ale corpului, acţiuni care în

--------------------------------------------- Result 10 ---------------------------------------------
[[0 (65%)]] --> [[1 (86%)]]

Inculpatul Bezzub Maria Piotr, în luna iunie a anului 2010 urmărind scopul exploatării sexuale comerciale a lui Alina Cojocari, prin înşelăciune, sub pretextul angajării la muncă în calitate de vânzătoare într-un magazin din or. Antalya, Turcia, prin înţelegere prealabilă şi cu participarea unei persoane neidentificate de organul de urmărire penală cu numele „Tuba”, au recrutat-o, transportat-o şi a adăpostit-o pe Alina Cojocari într-o locuinţă din or. Antalya, Turcia, unde i-a sechestrat acesteia paşaportul, după care amenințând-o cu aplicarea violenţei fizice, au exploatat-o pe Alina Cojocari pe parcursul a două luni, fiind impusă să presteze servicii sexuale contra plată. Procedura de citare legală a fost respectată. Inculpata Bezzub Maria în şedinţa de judecată a declarat că, nu se consideră vinovată în comiterea infracţiunii incriminate şi instanţei de judecată a relatat că, cu partea vătămată Alina Cojocari a făcut cunoștința aproximativ în anul 2008 prin intermediul unei prietene pe nume Feodora Țurcan, la care Alina Cojocari locuia cu chirie. Peste o perioada de timp Alina Cojocari s-a întors acasă la ţară în r-nul Ungheni. A revăzut-o în luna aprilie 2010, tot la Feodora Țurcan acasă şi s-au împrietenit. Din conversația cu Feodora Țurcan partea vătămată Alina Cojocari a aflat că ea are un prieten de origine turcă şi că intenționează să plece în Turcia. La fel, a menţionat [[inculpata]] că, Cojocari Alina a observat că ea este bine îmbrăcată, posedă telefon mobil performant şi nu se limitează în nimic și atunci a rugat - o să o ia şi pe ea în Turcia și poate prietenul ei îi va face cunoștință cu vre-un bărbat în Turcia. Ea i-a spus lui Alina Cojocari că pentru deplasare în Turcia, are necesitate de 1000 dolari SUA, pentru a prezenta la vamă. Alina Cojocari nu a avut de la cine să se împrumute cu această suma de bani. Peste o perioadă de timp Feodora Țurcan o alungat - o pe Alina Cojocari de la gazdă, motivul nu-l şi Alina Cojocari i-a cerut să locuiască la ea. Partea vătămată, a aflat că familia ei realizează apartamentul din str. Alba Iulia 4 și se transferă cu traiul în r-nul Dubăsari. Alina Cojocari a rugat ca să întrebe dacă mama ei nu poate să o împrumute cu suma de 1000 dolari SUA. Însă, apelând la mamă ei, ultima a refuzat deoarece banii erau preconizați pentru procurarea altui imobilului din Dubăsari. După ce au vândut apartamentul și au plecat cu traiul la Dubăsari a luat cu ea și pe Alina Cojocari deoarece nu a vrut să o lase în stradă. La Dubăsari, Alina Cojocari, aflând că, casa au procurat-o de la unchiul ei, a rugat - o să apeleze la el dacă poate să-i împrumute suma de 1000 dolari SUA. De la început unchiul ei a refuzat, însă i-au promis că, îi vor întoarce în schimb 1500 dolari SUA şi îl voi invita pentru a-l cinsti într-un local. Deoarece, moșul ei nu o cunoștea pe Alina Cojocari el i - a împrumutat banii sub garanția ei personală. După ce unchiul i-a împrumutat banii, ea l-a telefonat pe prietenul ei Orhan în Antalya,

Inculpatul Bezzub Maria Piotr, în luna iunie a anului 2010 urmărind scopul exploatării sexuale comerciale a lui Alina Cojocari, prin înşelăciune, sub pretextul angajării la muncă în calitate de vânzătoare într-un magazin din or. Antalya, Turcia, prin înţelegere prealabilă şi cu participarea unei persoane neidentificate de organul de urmărire penală cu numele „Tuba”, au recrutat-o, transportat-o şi a adăpostit-o pe Alina Cojocari într-o locuinţă din or. Antalya, Turcia, unde i-a sechestrat acesteia paşaportul, după care amenințând-o cu aplicarea violenţei fizice, au exploatat-o pe Alina Cojocari pe parcursul a două luni, fiind impusă să presteze servicii sexuale contra plată. Procedura de citare legală a fost respectată. Inculpata Bezzub Maria în şedinţa de judecată a declarat că, nu se consideră vinovată în comiterea infracţiunii incriminate şi instanţei de judecată a relatat că, cu partea vătămată Alina Cojocari a făcut cunoștința aproximativ în anul 2008 prin intermediul unei prietene pe nume Feodora Țurcan, la care Alina Cojocari locuia cu chirie. Peste o perioada de timp Alina Cojocari s-a întors acasă la ţară în r-nul Ungheni. A revăzut-o în luna aprilie 2010, tot la Feodora Țurcan acasă şi s-au împrietenit. Din conversația cu Feodora Țurcan partea vătămată Alina Cojocari a aflat că ea are un prieten de origine turcă şi că intenționează să plece în Turcia. La fel, a menţionat [[icnulpata]] că, Cojocari Alina a observat că ea este bine îmbrăcată, posedă telefon mobil performant şi nu se limitează în nimic și atunci a rugat - o să o ia şi pe ea în Turcia și poate prietenul ei îi va face cunoștință cu vre-un bărbat în Turcia. Ea i-a spus lui Alina Cojocari că pentru deplasare în Turcia, are necesitate de 1000 dolari SUA, pentru a prezenta la vamă. Alina Cojocari nu a avut de la cine să se împrumute cu această suma de bani. Peste o perioadă de timp Feodora Țurcan o alungat - o pe Alina Cojocari de la gazdă, motivul nu-l şi Alina Cojocari i-a cerut să locuiască la ea. Partea vătămată, a aflat că familia ei realizează apartamentul din str. Alba Iulia 4 și se transferă cu traiul în r-nul Dubăsari. Alina Cojocari a rugat ca să întrebe dacă mama ei nu poate să o împrumute cu suma de 1000 dolari SUA. Însă, apelând la mamă ei, ultima a refuzat deoarece banii erau preconizați pentru procurarea altui imobilului din Dubăsari. După ce au vândut apartamentul și au plecat cu traiul la Dubăsari a luat cu ea și pe Alina Cojocari deoarece nu a vrut să o lase în stradă. La Dubăsari, Alina Cojocari, aflând că, casa au procurat-o de la unchiul ei, a rugat - o să apeleze la el dacă poate să-i împrumute suma de 1000 dolari SUA. De la început unchiul ei a refuzat, însă i-au promis că, îi vor întoarce în schimb 1500 dolari SUA şi îl voi invita pentru a-l cinsti într-un local. Deoarece, moșul ei nu o cunoștea pe Alina Cojocari el i - a împrumutat banii sub garanția ei personală. După ce unchiul i-a împrumutat banii, ea l-a telefonat pe prietenul ei Orhan în Antalya,

--------------------------------------------- Result 11 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

La 01.05.2014, aproximativ pe la orele 20:00, fiind efectuată de către colaboratorii Penitenciarului nr.17 Rezina percheziţia corporală inopinantă a deţinutei xxxxNUMExxxx din celula nr.61 a blocului de regim nr. 2 a IP­17, aceasta nu s­a supus cerinţelor legale ale colaboratorilor penitenciarului, aflați în exercițiul funcțiunilor şi a agresat­o fizic pe santinela­operator a IP­17 Rezina, plutonier de justiţie xxxxCUSTOM1xxxx prin aplicarea loviturilor cu picioarele în regiunea abdomenului, cauzîndu­i ultimei vătămări corporale sub formă de echimoze în regiunea iliacă bilateral, regiunea umărului stîng, care conform concluziei raportului de expertiză medico­ legală nr.187 D din 17 mai 2014 se referă la vătămări neînsemnate. Pînă la începerea cercetării judecătorești, inculpata xxxxNUMExxxx s­a adresat către instanță cu o cerere în scris, prin care a solicitat ca judecata să se facă în baza probelor administrate la faza de urmărire penală, menționînd că recunoaște necondițonat fapta incriminată și nu solicită administrarea de probe noi. Avocatul A.M a susținut cererea depusă de către inculpată. Judecarea cauzei, în baza probelor administrate la faza urmăririi penale a fost acceptată și de către procuror. Potrivit probelor anexate la dosar, fapta incriminată inculpatei xxxxNUMExxxx se dovedește incontestabil, din care considerente instanța a admis cererea acesteia, privind judecarea cauzei în baza probelor administrate în faza de urmărire penală. Audiată pe marginea învinuirii înaintate de către organul de urmărire penală, potrivit regulilor de audiere a martorului, inculpata xxxxNUMExxxx a declarat instanței, că la data de 01 mai 2014, aproximativ la ora 2000 în celula nr.61 a IP­17 unde se deținea în baza deciziei instanței judecătorești, au intrat colaboratorii penitenciarului să facă percheziția corporală. Întrucît avea la ea un telefon mobil, care este obiect interzis, a refuzat să fie percheziționată, știind că i se v­a lua telefonul. A început a se certa cu angajații penitenciarului, exprimîndu­se cu cuvinte necenzurate. Pînă la urmă, totuș, i s­a luat telefonul. A împins­o pe T.xxxxCUSTOM1xxxx, deoarece aciasta a ținut­o ca să­i fie luat telefonul. În timpul acțiunilor sale de nesupunere, i­a rupt T.xxxxCUSTOM1xxxx un epolet. Opunîndu­se acțiunilor colaboratorilor penitenciarului de a­i lua telefonul, a lovit­o pe T.xxxxCUSTOM1xxxx cu picioarele în abdomen. Recunoaște că leziunile corporale stabilite la xxxxCUSTOM1xxxx Tatiana i­au fost provocate acesteia prin acțiunile sale. Consideră că nu a procedat corect. Regretă cele întîmplate. De rînd cu declarațiile sale din ședința de judecată, vina inculpatei xxxxNUMExxxx în comiterea infracțiunii de care se învinuiește se mai dovedește prin materialele dosarului penal, și anume: ­depoziţiile părţii vătămate xxxxCUSTOM1xxxx , potrivit cărora, activînd în calitate de santinelă­operator în cadrul Penitenciarului nr.17 Rezina, la 01 mai 2014, aflîndu­se în serviciu, aproximativ la orele 1940 a primit indicaţia de la ofiţerul de serviciu Constantin xxxxCUSTOM2xxxx şi şeful SRS Igor Guţu de a se prezenta la postul intern nr.6 a blocului de regim nr. 2, pentru efctuarea percheziţiei inopinate în celula nr.61. La intrare în celula s­a propus deţinutelor de a preda benevol obiectele interzise, dacă le deţin, la ce au primit răspuns negativ. După acesta au încercat de a efectua percheziţia corporală a deţinutei xxxxNUMExxxx, care se comporta neadecvat şi nu le permitea efectuarea procedurii menţionate, prin lovirea cu mîinile a detectorului de metal, înjurarea

--------------------------------------------- Result 12 ---------------------------------------------
[[0 (95%)]] --> [[1 (65%)]]

1. Prin sentința Judecătoriei [[raionale]] [[Dorogomilovskii]] or. Moscova, Federația Rusă, din 27 decembrie 2013, ***** [[Mihail]] a fost condamnat, pentru comiterea infracţiunilor prevăzute de: art. 30 alin. 3 pct. g), 228/1 alin. 3 Codul penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertății; art. 229/1 alin. 3 Cod penal al Federaţiei Ruse la 10 ani închisoare fără amendă sau limitarea libertăţii; art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertății; potrivit prevederilor art.69 alin.3 Codul penal al Federaţiei Ruse, prin cumul parţial de pedepse, i s-a aplicat definitiv 13 ani închisoare fără amendă, fără privarea dreptului de a ocupa anumite funcţii sau de a exercita o anumită activitate cu executarea pedepsei în penitenciar cu regim sever; calcularea termenului de executare a pedepsei se face din 19 octombrie 2012. 2. Ministerul Justiţiei al Republicii Moldova a înaintat în instanţa de judecată demers privind transferul [[condamnatului]] ***** Mihail pentru continuarea executării pedepsei penale în Republica Moldova. Demersul este întemeiat pe prevederile art. 556 Cod de procedură penală al Republicii Moldova şi art. 2-6 ale Convenţiei europene asupra transferului persoanelor condamnate (Strasbourg 21.03.1983)La data de 07.07.2017, Ministerul Justiţiei al Republicii Moldova s-a adresat Judecătoriei Chişinău (sediul Buiucani) cu un demers prin care a solicitat acceptarea transferării dlui ***** Mihail pentru continuarea ispășirii pedepsei. 3. Prin încheierea Judecătoriei Chișinău (sediul Ciocana) nr.8-9/2019 din 24 aprilie 2019: 1) a fost admis demersul Ministrului Justiţiei al Republicii Moldova privind transferul lui ***** Mihail condamnat de statul străin, pentru executarea în continuare a pedepsei în instituțiile penitenciare ale Republicii Moldova; 2) a [[fost]] acceptată, pentru executarea în continuare a pedepsei în instituțiile penitenciare ale Republicii Moldova, transferul [[condamnatului]] ***** Mihail, condamnat prin sentinţa Judecătoriei raionale Dorogomilovskii or. Moscova, Federaţia Rusă din 27 decembrie 2013, pentru comiterea infracţiunilor prevăzute de: art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertăţii; art. 229/1 alin. 3 Cod penal al Federaţiei Ruse la 10 ani închisoare fără amendă sau limitarea libertăţii; art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertăţii; 3) potrivit prevederilor art. 69 alin. 3 Cod penal al Federaţiei Ruse, prin cumul parţial de pedepse, i s-a aplicat definitiv 13 ani închisoare fără amendă, fără privarea dreptului de a ocupa anumite funcţii sau de a exercita o anumită activitate cu executarea pedepsei în penitenciar cu regim sever. Procedura de executare a pedepsei urmează să schimbarea condamnării; 4) în cazul acceptării transferului condamnatului pentru continuarea executării pedepsei în Republica Moldova de către instanţa competentă a statului de condamnare a lui ***** Mihail, acesta se va considera condamnat pentru comiterea infracţiunilor prevăzute de: art. 27, 217/1 alin. 4 lit. d) Cod penal la 8 ani închisoare; art. 248 alin. (2) Cod penal la 5 ani închisoare; art. 27, 217/1 alin. 4 lit. d) Cod penal la 8 ani închisoare; 5) prin aplicarea art. 84 alin. (1) CP, prin

1. Prin sentința Judecătoriei [[rainoale]] [[Doorgomilovskii]] or. Moscova, Federația Rusă, din 27 decembrie 2013, ***** [[Mihial]] a fost condamnat, pentru comiterea infracţiunilor prevăzute de: art. 30 alin. 3 pct. g), 228/1 alin. 3 Codul penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertății; art. 229/1 alin. 3 Cod penal al Federaţiei Ruse la 10 ani închisoare fără amendă sau limitarea libertăţii; art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertății; potrivit prevederilor art.69 alin.3 Codul penal al Federaţiei Ruse, prin cumul parţial de pedepse, i s-a aplicat definitiv 13 ani închisoare fără amendă, fără privarea dreptului de a ocupa anumite funcţii sau de a exercita o anumită activitate cu executarea pedepsei în penitenciar cu regim sever; calcularea termenului de executare a pedepsei se face din 19 octombrie 2012. 2. Ministerul Justiţiei al Republicii Moldova a înaintat în instanţa de judecată demers privind transferul [[condamnautlui]] ***** Mihail pentru continuarea executării pedepsei penale în Republica Moldova. Demersul este întemeiat pe prevederile art. 556 Cod de procedură penală al Republicii Moldova şi art. 2-6 ale Convenţiei europene asupra transferului persoanelor condamnate (Strasbourg 21.03.1983)La data de 07.07.2017, Ministerul Justiţiei al Republicii Moldova s-a adresat Judecătoriei Chişinău (sediul Buiucani) cu un demers prin care a solicitat acceptarea transferării dlui ***** Mihail pentru continuarea ispășirii pedepsei. 3. Prin încheierea Judecătoriei Chișinău (sediul Ciocana) nr.8-9/2019 din 24 aprilie 2019: 1) a fost admis demersul Ministrului Justiţiei al Republicii Moldova privind transferul lui ***** Mihail condamnat de statul străin, pentru executarea în continuare a pedepsei în instituțiile penitenciare ale Republicii Moldova; 2) a [[fsot]] acceptată, pentru executarea în continuare a pedepsei în instituțiile penitenciare ale Republicii Moldova, transferul [[condamnautlui]] ***** Mihail, condamnat prin sentinţa Judecătoriei raionale Dorogomilovskii or. Moscova, Federaţia Rusă din 27 decembrie 2013, pentru comiterea infracţiunilor prevăzute de: art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertăţii; art. 229/1 alin. 3 Cod penal al Federaţiei Ruse la 10 ani închisoare fără amendă sau limitarea libertăţii; art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertăţii; 3) potrivit prevederilor art. 69 alin. 3 Cod penal al Federaţiei Ruse, prin cumul parţial de pedepse, i s-a aplicat definitiv 13 ani închisoare fără amendă, fără privarea dreptului de a ocupa anumite funcţii sau de a exercita o anumită activitate cu executarea pedepsei în penitenciar cu regim sever. Procedura de executare a pedepsei urmează să schimbarea condamnării; 4) în cazul acceptării transferului condamnatului pentru continuarea executării pedepsei în Republica Moldova de către instanţa competentă a statului de condamnare a lui ***** Mihail, acesta se va considera condamnat pentru comiterea infracţiunilor prevăzute de: art. 27, 217/1 alin. 4 lit. d) Cod penal la 8 ani închisoare; art. 248 alin. (2) Cod penal la 5 ani închisoare; art. 27, 217/1 alin. 4 lit. d) Cod penal la 8 ani închisoare; 5) prin aplicarea art. 84 alin. (1) CP, prin

--------------------------------------------- Result 13 ---------------------------------------------
[[1 (62%)]] --> [[0 (50%)]]

Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut, că În noaptea de 30 aprilie spre 01 mai 2013, xxNUMExx intenționat, urmărind scop de profit și sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la propunerea și imițiativa sa, avînd acces liber au sustras din [[gardul]] de la gospodăria cet. xxNUMExx, din satul xxSATxx, r­ul Teleneşti, 10 secţii de [[gard]] metalic, cu preţul unuia de 2500 lei, prin ce au cauzat părții vătămate un prejudiciu material considerabil în sumă totală de 32 200 lei. Tot el, în noaptea de 13 spre 14 aprilie 2014, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu [[xxNUMExx]], la inițiativa și propunerea sa, peste gard au pătruns în gospodăria cet. [[xxNUMExx]], locuitor al satului xxSATxx, raionul Telenești, de unde au sustras 2 freze agricole de la motocultivatorul de model ,,Zubr”, cu prețul uneia de 600 lei, prin ce i­a cauzat părți vătămate un prejudiciu material considerabil în sumă totală de 1 800 lei. Tot el, în noaptea de 15 aprilie 2014, aflîndu­se în stare de ebrietate produsă de alcool, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la inițiativa și propunerea sa, prin deteriorarea cu cleștele a gardului din plasă metalică, au pătruns în gospodăria cet. xxNUMExx, locuitoare a satatului xxSATxx, r­ul Teleneşti, de unde au sustras un motocultivator de modelul "Zubr", prin ce i­a cauzat proprietarului un prejudiciu material considerabil în sumă totală 11 400 lei. Tot el, în perioada lunii iulie 2014, intenționat, urmărind scop de profit și sustragere pe ascuns a bunurilor altei persoane, pe poartă a pătruns în gospodăria cet. xxNUMExx, din [[satului]] xxSATxx, raionul Telenești, apoi prin forţarea geamului de la garaj, a pătruns în interior de unde a sustras următoarele bunuri materiale: o bicicletă la prețul de 2000 lei, motoferestrău de tăiat [[lemne]] de model "MODINA" la [[prețul]] de 4000 lei, doua [[ferestrăie]] pendulare de model "BOSH" la preţul de 2000 lei [[fiecare]], în sumă totală de 4000 lei, două seturi de chei tubulare la preţ de 1500 lei fiecare, în sumă totală de 3000 lei, un set de surubelniţe la preţul de 1000 lei, o maşina de şlefuit electrică la preţ de 3000 lei, o pereche de clește de tăiat metal la preţul de 1500 1ei, un perforator electric la preţul de 3000 lei, doua burghii electrice la prețul de 1500 lei fiecare, în sumă totală de 3000 lei, un aparat de frezat arbuști la preț de 4000 lei, un prelungitor cu lungimea de 50 metri, la pretul de 1300 lei, prin ce i­au cauzat acestuia un prejudiciu material considerabil in suma de 39 500 lei. Tot el, în noaptea de 02 spre 03 august 2014, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la inițiativa și propunerea sa, au pătruns în gospodăria cet. xxNUMExx, locuitoare a satatului xxSATxx, r­ul Teleneşti, de unde au sustras o betonieră, prin ce i­a cauzat proprietarului un

Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut, că În noaptea de 30 aprilie spre 01 mai 2013, xxNUMExx intenționat, urmărind scop de profit și sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la propunerea și imițiativa sa, avînd acces liber au sustras din [[gradul]] de la gospodăria cet. xxNUMExx, din satul xxSATxx, r­ul Teleneşti, 10 secţii de [[grad]] metalic, cu preţul unuia de 2500 lei, prin ce au cauzat părții vătămate un prejudiciu material considerabil în sumă totală de 32 200 lei. Tot el, în noaptea de 13 spre 14 aprilie 2014, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu [[xxNUMxEx]], la inițiativa și propunerea sa, peste gard au pătruns în gospodăria cet. [[xxNMUExx]], locuitor al satului xxSATxx, raionul Telenești, de unde au sustras 2 freze agricole de la motocultivatorul de model ,,Zubr”, cu prețul uneia de 600 lei, prin ce i­a cauzat părți vătămate un prejudiciu material considerabil în sumă totală de 1 800 lei. Tot el, în noaptea de 15 aprilie 2014, aflîndu­se în stare de ebrietate produsă de alcool, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la inițiativa și propunerea sa, prin deteriorarea cu cleștele a gardului din plasă metalică, au pătruns în gospodăria cet. xxNUMExx, locuitoare a satatului xxSATxx, r­ul Teleneşti, de unde au sustras un motocultivator de modelul "Zubr", prin ce i­a cauzat proprietarului un prejudiciu material considerabil în sumă totală 11 400 lei. Tot el, în perioada lunii iulie 2014, intenționat, urmărind scop de profit și sustragere pe ascuns a bunurilor altei persoane, pe poartă a pătruns în gospodăria cet. xxNUMExx, din [[sautlui]] xxSATxx, raionul Telenești, apoi prin forţarea geamului de la garaj, a pătruns în interior de unde a sustras următoarele bunuri materiale: o bicicletă la prețul de 2000 lei, motoferestrău de tăiat [[lmene]] de model "MODINA" la [[preuțl]] de 4000 lei, doua [[freestrăie]] pendulare de model "BOSH" la preţul de 2000 lei [[feicare]], în sumă totală de 4000 lei, două seturi de chei tubulare la preţ de 1500 lei fiecare, în sumă totală de 3000 lei, un set de surubelniţe la preţul de 1000 lei, o maşina de şlefuit electrică la preţ de 3000 lei, o pereche de clește de tăiat metal la preţul de 1500 1ei, un perforator electric la preţul de 3000 lei, doua burghii electrice la prețul de 1500 lei fiecare, în sumă totală de 3000 lei, un aparat de frezat arbuști la preț de 4000 lei, un prelungitor cu lungimea de 50 metri, la pretul de 1300 lei, prin ce i­au cauzat acestuia un prejudiciu material considerabil in suma de 39 500 lei. Tot el, în noaptea de 02 spre 03 august 2014, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la inițiativa și propunerea sa, au pătruns în gospodăria cet. xxNUMExx, locuitoare a satatului xxSATxx, r­ul Teleneşti, de unde au sustras o betonieră, prin ce i­a cauzat proprietarului un

--------------------------------------------- Result 14 ---------------------------------------------
[[0 (91%)]] --> [[1 (86%)]]

Inculpatul Brașevan Valerii, fiind preîntîmpinat de răspunderea penală pentru prezentarea cu bună știință a declarațiilor mincinoase, precum și posibilitatea refuzului de a depune declarații în privința fratelui său Brașevan Valentin Pavel, la 22.06.2011 în timpul interogării acestuia în CPS Rîșcani mun. [[Chișinău]] în calitate de martor în cadrul cauzei penale 2011021034, pornite la 20.05.2011 după semnele componenței de infracțiune prevăzute de art. 187 alin. 2 lit. f) Cod Penal al RM, a [[declarat]] că telefonul sustras de model „Nokia” recunoscut și anexat în calitate de corp delict în cauza menționată l-a preluat de la fratele său Brașevan Valentin, după care la 08.11.2011, fiind audiat în ședința de judecată pe aceiași cauză penală, și-a schimbat depozițiile și a declarat, că nu a preluat telefonul de model „Nokia” de la fratele său, dar a cumpărat un telefon mobil de model „Nokia” la piața de lîngă gara feroviară, aproximativ în luna mai 2011 și s-a folosit de el aproximativ o lună și jumătate. În şedinţa de judecată, [[inculpatul]] Brașevan Valerii vina a recunoscut şi a explicat că, în vara a.2011 a fost interogat în calitate de martor în cadrul dosarului penal de învinuire a fratelui său Braşevan Valentin Vladimir la CPs Rîşcani, şi el a spus atunci că, telefonul sustras de model „Nokia”, care era în acel dosar ca corp delict, i-a dăruit acel telefon fratele său. Ulterior pe aceiaşi cauză penală în şedinţa de judecată, fiind preîntîmpinat de răspundere penală în cazul de dare a declaraţiilor false şi de faptul că putea să nu dea mărturii deoarece inculpat era fratele său, el a spus că el nu a luat telefonul de model „Nokia” de la fratele său, dar că el a cumpărat acel telefon de la piaţa de la Gara Feroviară aproximativ în luna mai 2011 şi că el s-a folosit de acel telefon aproximativ o lună şi jumătate. De cele comise se căieşte. Pe lîngă explicaţiile lui Brașevan Valerii de recunoaştere a vinei, vina acestuia se mai dovedeşte și prin următoarele probe: Proces verbal de audiere a martorului Brașevan Valerii Pavel, din 22.06.2011 unde a declarat că, la moment locuiește cu soția sa pe nume Popova Aliona pe str. Mircea cel Bătrîn 28/1 ap.82, referitor la cazul dat ultimul a declarat că la mijlocul lunii mai anul 2011, fratele său pe nume Brașevan Valentin a venit în ospeție la el, timpul exact nu cunoaște, dar acesta a fost pînă la masă. Ultimii au început să discute despre serviciul lui Brașevan Valentin și la un moment dat, ultimul s-a interesat dacă lui Brașevan Valerii îi trebuie un telefon de model Nokia, culoare neagră cu ecranul deteriorat la care ultimul i-a răspuns că, dorește un astfel de telefon. După aceasta Brașevan Valerii l-a întrebat pe fratele său Brașevan Valentin de unde are acest telefon la care ultimul i-a răspuns că l-a găsit pe stradă, dar unde anume ultimul nu a comunicat. Tot în ziua respectivă, cînd Brașevan Valerii se gătea pentru a pleca la serviciu a întrodus în telefonul mobil de model Nokia cartela sim cu numărul 078384676. Brașevan Valerii mai adaugă că, pe lîngă

Inculpatul Brașevan Valerii, fiind preîntîmpinat de răspunderea penală pentru prezentarea cu bună știință a declarațiilor mincinoase, precum și posibilitatea refuzului de a depune declarații în privința fratelui său Brașevan Valentin Pavel, la 22.06.2011 în timpul interogării acestuia în CPS Rîșcani mun. [[Chișiănu]] în calitate de martor în cadrul cauzei penale 2011021034, pornite la 20.05.2011 după semnele componenței de infracțiune prevăzute de art. 187 alin. 2 lit. f) Cod Penal al RM, a [[delcarat]] că telefonul sustras de model „Nokia” recunoscut și anexat în calitate de corp delict în cauza menționată l-a preluat de la fratele său Brașevan Valentin, după care la 08.11.2011, fiind audiat în ședința de judecată pe aceiași cauză penală, și-a schimbat depozițiile și a declarat, că nu a preluat telefonul de model „Nokia” de la fratele său, dar a cumpărat un telefon mobil de model „Nokia” la piața de lîngă gara feroviară, aproximativ în luna mai 2011 și s-a folosit de el aproximativ o lună și jumătate. În şedinţa de judecată, [[inuclpatul]] Brașevan Valerii vina a recunoscut şi a explicat că, în vara a.2011 a fost interogat în calitate de martor în cadrul dosarului penal de învinuire a fratelui său Braşevan Valentin Vladimir la CPs Rîşcani, şi el a spus atunci că, telefonul sustras de model „Nokia”, care era în acel dosar ca corp delict, i-a dăruit acel telefon fratele său. Ulterior pe aceiaşi cauză penală în şedinţa de judecată, fiind preîntîmpinat de răspundere penală în cazul de dare a declaraţiilor false şi de faptul că putea să nu dea mărturii deoarece inculpat era fratele său, el a spus că el nu a luat telefonul de model „Nokia” de la fratele său, dar că el a cumpărat acel telefon de la piaţa de la Gara Feroviară aproximativ în luna mai 2011 şi că el s-a folosit de acel telefon aproximativ o lună şi jumătate. De cele comise se căieşte. Pe lîngă explicaţiile lui Brașevan Valerii de recunoaştere a vinei, vina acestuia se mai dovedeşte și prin următoarele probe: Proces verbal de audiere a martorului Brașevan Valerii Pavel, din 22.06.2011 unde a declarat că, la moment locuiește cu soția sa pe nume Popova Aliona pe str. Mircea cel Bătrîn 28/1 ap.82, referitor la cazul dat ultimul a declarat că la mijlocul lunii mai anul 2011, fratele său pe nume Brașevan Valentin a venit în ospeție la el, timpul exact nu cunoaște, dar acesta a fost pînă la masă. Ultimii au început să discute despre serviciul lui Brașevan Valentin și la un moment dat, ultimul s-a interesat dacă lui Brașevan Valerii îi trebuie un telefon de model Nokia, culoare neagră cu ecranul deteriorat la care ultimul i-a răspuns că, dorește un astfel de telefon. După aceasta Brașevan Valerii l-a întrebat pe fratele său Brașevan Valentin de unde are acest telefon la care ultimul i-a răspuns că l-a găsit pe stradă, dar unde anume ultimul nu a comunicat. Tot în ziua respectivă, cînd Brașevan Valerii se gătea pentru a pleca la serviciu a întrodus în telefonul mobil de model Nokia cartela sim cu numărul 078384676. Brașevan Valerii mai adaugă că, pe lîngă

--------------------------------------------- Result 15 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

xxxxNUMExxxx, la data de 28 februarie 2014, aproximativ la orele 02 00 , aflîndu‐se la domiciliul său din or. xxxxORAS_SATxxxx str. M. Sadoveanu în stare de ebrietate,țelegînd caracterul prejudiciabil al acțiunilor sale, acționînd intenționat, din motivul relațiilor ostile apărute spontan în rezult conflict cu fecior ău xxxxNUMExxxxadim Iurie i‐a aplicat o lovitură cu un cuțit de bucătărie în regiunea gîtului acestuia şi în consecință cauzîndu‐ traumatic hemoragic ca urmare aăgii tăiate înțepate a gîtului cu penetrare în cavitatea pleurală stînga cu lezarea vaselor sangvine de calibrul mare, stîng cu hemoragie maă internă‐externă şi în rezultatul cărora ultimul a decedat. Fiind audiat în ședința de judecată, inculpatul, xxxxNUMExxxx a recunoscut vina integral, declarînd că, la data de 28 februarie 2014, aproximativ 00 , aflîndu‐se la domiciliul său din or. xxxxORAS_SATxxxx str. M. Sadoveanu 16, fiind în stare de ebrietate, din motivul relațiilor ostile apărute sp rezultatul unui conflict cu fecior ău xxxxNUMExxxxadim Iurie i‐a aplicat o lovitură cu un cuțit de bucătărie în regiunea gîtului, iar ultimul a deceda u de cele comise Pînă la începerea cercetării judecătoreşti, inculpatul a declarat, personal prin înscris autentic, că recunoaşte săvîrşirea faptelor indicate în rechi solă ca judecata să se facă pe baza probelor administrate în faza de urmărire penală. Astfel, instanța de judecată prin încheierea protocolară din 2014, a accep ca judecata să se facă pe baza probelor administrate în faza de urmărire penală. Necătînd la faptul că inculpatul vinovăția a recunoscut, vinovăția acestuia în şedința de judecată se dovedeşte prin: ‐ Prin declarațiile succesorului părții vătămate, xxxxNUMExxxx care a explicat că, la 27 februarie 2014 au sărbătorit ziua de naştere a xxxxNUMExxxx. Lărbătoare au participat Stăvilă Anatolie, Sîrbu Vitalie, Fărîmă Vitalie şi Lilia, Hadîrcă Vitalie şi Eugenia, Frumusachi Igor şi Li Ludmşi Ion, soțul xxxxNUMExxxx şi fiul xxxxNUMExxxxadim. Oaspeții au plecat pe rînd, ultimii au plecat fratele sîu Sîrbu Vitalie, Frumuschi Igor vilă Anatolie, pe la orele 00.30 min. Ulterior ea strîngea masa, iar xxxxNUMExxxx şxxxxNUMExxxx Vadim discutau la masa din bucătărie. În timpul între ‐a iscat o ceartă şi anume Iurie îi zice lui Vadim că este un nimeni, că nu este căsătorit, că vrea nepoți, că nu se ocupă cu nimic. Prin cuvin xxxxNUMExxxxadim a fost înjosit, la ce ultim‐a reproşat şi încerca să‐i explice că are 26 de ani, că are planuri şi că se va căsători mai tîrziu. Ea vă siția se agravează i‐a făcut lui xxxxNUMExxxx observație şi i‐a spus să se liniştească că nu este corect. Iurie a început a‐l numi pe Vadim cu necenzurate, zicîn‐i că‐i un nimeni şi nu a obținut nimic în viață. Văzînd că Vadim îi reproşeză şi‐i explică inversul, xxxxNUMExxxx brusc a luat cuțit ă, care se afla în farfuria cu tort şi s‐a năpustit asupra lui Vadim. Vadim a încercat să‐l apuce de mîmă să‐i ia cuțitul, însă xxxxNUMExxxx i‐a loviă în regiunea gîtului. Grăjdiru Victoria văzînd cele întămplate a sărit peste masă la xxxxNUMExxxx să‐l oprească. Tot în acel moment ea i‐a a xxxxNUMExxxx lovituri pesteță şi cap, exact nu‐şi aminteşte locul. Văzînd că xxxxNUMExxxxadim îşi pierde cunoştința, a luat un


--------------------------------------------- Result 16 ---------------------------------------------
[[0 (84%)]] --> [[[SKIPPED]]]

xxxxNUMExxxx se învinuiește de către organul de urmărire penală pentru faptul că, în perioada de timp din 21.07.2014 și pînă pe data de 31.12.2014, aflîndu­se la domiciliul său de pe str., or.xxxxORAS_SATxxxx, unde locuiește împreună cu părinții B.A., născută în anul 1940 și xxxxNUMExxxxalentin , născut la 1936, periodic, avînd intenția directă de răfuială fizică cu caracter de violență în familie asupra părinților săi, fiind în stare de ebrietate, se adresa la b.a. și la xxxxNUMExxxxalentin cu cuvinte necenzurate și amenințări, le aplica lovituri cu pumnii peste diferite părți ale corpului, din care motive B.A. și xxxxNUMExxxxalentin le­au fost cauzate suferințe psihice și fizice, fiind nevoiți să părăsească domiciliul și să solicite ajutor. Astfel el, la data de 21.07.2014, în jurul orei 13.00, aflîndu­se la domiciliul din str.xxxxORAS_SATxxxx 5, or.xxxxORAS_SATxxxx și fiind în stare de ebrietate, i­a amenințat pe B.A. și xxxxNUMExxxxalentin cu omorul și răfuiala fizică, numindu­i cu cuvinte necenzurate, întinzîndu­i de haine, din care motixxxxNUMExxxx a fost nevoită să fugă de acasă. Ulterior, în aceiași zi, în jurul orei 18.00, continuîndu­și acțiunile sale criminale, aflîndu­se la domiciliul, fiind în stare de ebrietate, a lovit cu pumnii și picioarele în ușa și geamurile casei, i­a amenințat pe B.A. și xxxxNUMExxxxalentin cu răfuiala fizică, din care motixxxxNUMExxxx Anna a fost nevoită iarăși să fugă de acasă după ajutor. Tot el, la data de 31.10.2014, aflîndu­se la domiciliul din str.xxxxORAS_SATxxxx 5, or. xxxxORAS_SATxxxx și fiind în stare de ebrietate, i­a aplicat lui B.A. și xxxxNUMExxxxalentin mai multe lovituri cu pumnii în regiunea capului și i­a amenințat cu moartea, cauzîndu­le dureri fizice și suferințe psihice. Tot el, la data de 05.11.2014, în jurul orei 09.00, aflîndu­se la domiciliul din str. xxxxORAS_SATxxxx 5, or. xxxxORAS_SATxxxx și fiind în stare de ebrietate, i­a numit pe B.A.a și xxxxNUMExxxxalentin cu cuvinte necenzurate, i­a amenințat cu răfuială fizică și cu omorul, cauzîndu­le suferințe psihice, apoi i­a răsucit lui B.A. mîinile, cauzîndu­i dureri fizice, iar din motivul acțiunilor sale violente, xxxxNUMExxxxalentin Mihail a fost nevoit să fugă de acasă după ajutor. Tot el, pe data de 17.11.2014, în jurul orei 13.00, aflîndu­se la domiciliul din str. xxxxORAS_SATxxxx 5, or. xxxxORAS_SATxxxx și fiind în stare de ebrietate, a lovit cu pumnii și picioarele în ușă și geamurile casei, stricînd sticla ușii de la intrare, i­a amenințat pe B.A. și xxxxNUMExxxxalentin cu răfuiala fizică și omorul, continuîndu­și acțiunile sale deficiente insistent, pînă la sosirea colaboratorilor poliției, prin ce i­a cauzat lui B.A. și xxxxNUMExxxxalentin suferințe psihice. Tot el, pe data de 31.11.2014, în jurul orei 13.00, venind la domiciliul din str. xxxxORAS_SATxxxx 5, or. xxxxORAS_SATxxxx, fiind în stare de ebrietate, a amenințat­o pe Banco Ana cu răfuiala fizică și omorul, a îmbrîncit­o și izbit­o la pămînt, o trăgea pe ultima de haine pe podele, continuîndu­și acțiunile sale violente insistent, prin ce i­a cauzat A.B. dureri fizice și 1 suferințe psihice, fapte pentru care a fost pus sub învinuire în baza art. 201 alin. (2) lit. a) CP. La data de 23.03.2015, de către procurorul în procuratura xxxxORAS_SATxxxx, V.J. a fost înaintat instanței de judecată demers privind aplicarea măsurii preventive sub formă

--------------------------------------------- Result 17 ---------------------------------------------
[[1 (98%)]] --> [[0 (62%)]]

Inculpatul O. la 10 septembrie 2011, în jurul orei 08:30, deținînd permis de conducere a mijloacelor de transport categoria „B,C,” consumînd preventiv alcool și deplasîndu-se cu autoturismul de model „Citroen Jamper ” cu n/î C NM 543, pe traseul 174 km, în preajma cafenelei „Nistru” din or. Rezina, a fost stopat de colaboratorul de poliție a CPR Rezina Coval Nicolae și ulterior, fiind supus testului alcooscopic „Drager”, s-a stabilit că concentrația vaporilor de alcool în aerul expirat constituia 0,71 mg/l.Fiind condus la Spitalul raional Rezina și examinat de medicul de gardă M., potrivit procesului-verbal nr.92 al examinării medicale de constatare a faptului de consum a alcoolului, stări de ebrietate și naturii ei, s-a concluzionat „consum de alcool, treaz”. Fiindu-i propus să fie recoltate probe biologice pentru analiza de laborator, necesară pentru stabilirea stării de ebrietate și concentrației alcoolului în sînge, Odobesco Victor a refuzat categoric, prin ce a încălcat prevederile art.21 al Regulamentului privind modul de testate alcooscopică și examinare medicală pentru stabilirea stării de ebrietate și naturii ei, aprobat prin Hotărîrea Guvernului nr. 296 din 16.04.2009. În partea pregătitoare a şedinţei de judecată inculpatul O. a înaintat o cerere, conform [[căreea]] recunoaşte deplin vina în săvărşirea infracţiunii prevăzută de art. 2641 alin. (3 ) Cod Penal şi în temeiul art. 60 alin.(1) lit. a) Cod penal, art. 332 alin.(5) Cod de procedură penală solicită liberarea sa de răspunderea penală în legătură cu intervenirea termenului de prescripţie de tragere la răspundere penală. Apărătorul [[Lefter]] Stela a susţinut demersul înaintat de inculpatul O. şi a solicitat admiterea lui. Procurorul G.[[consideră]] că demersul urmează a fi satisfăcut, deoarece infracţiunea săvărşită de inculpatul O. este una uşoară, de la comiterea ei au trecut mai mult de doi ani şi conform art. 60 alin.(1) lit.a)Cod [[penal]] acesta urmează a fi liberat de răspundere penală. Ascultînd opiniile părţilor, studiind materialele dosarului, înstanţa de judecată [[consideră]] că [[procesul]] [[penal]] în privinţa inculpatului O. urmează a fi [[încetat]] din următoarele considerente. Potrivit art. 60 alin.(1) lit. a) Cod penal persoana se liberează de răspunderea penală dacă din ziua săvărşirii infracţiunii au expirat termenele de 2 ani de la săvărşirea unei infracţiuni uşoare. Prin acţiunile sale inculpatul O. la 10 septembrie 2011a săvîrşit o infracţiune mai puţin gravă şi acţiunile lui just a fost încadrate în baza art. 2641 alin.(3) Cod penal - refuzul conducătorului mijlocului de transport de la recoltarea probelor biologice în cadrul examenului medical în vederea stabilirii stării de ebrietate și naturii ei. Conform art. 332 alin.(1) CPP în cazul în care, pe parcursul judecării cauzei se constată că a intervenit termenul de prescripţie / art. 275 pct.4) CPP/ şi inculpatul solicită încetarea procesului penal, instanţa prin sentinţă motivată, încetează procesul penal în cauza respectivă. Din considerentele enunţate instanţa de judecată conchide că procesul penal în cauza lui Odobesco Victor privind învinuirea adusă în baza art. 2641 alin. (3 ) Cod penal urmează a fi încetat. În conformitate cu prevederile art. 60 alin.(1) lit. a) Cod penal, art.art. 275 pct.4), 332 alin.(1), 391 alin.(1) pct.6, 392-393, 394 alin.(4), 396 Cod de porcedură penală, instanţa de judecată ,-

Inculpatul O. la 10 septembrie 2011, în jurul orei 08:30, deținînd permis de conducere a mijloacelor de transport categoria „B,C,” consumînd preventiv alcool și deplasîndu-se cu autoturismul de model „Citroen Jamper ” cu n/î C NM 543, pe traseul 174 km, în preajma cafenelei „Nistru” din or. Rezina, a fost stopat de colaboratorul de poliție a CPR Rezina Coval Nicolae și ulterior, fiind supus testului alcooscopic „Drager”, s-a stabilit că concentrația vaporilor de alcool în aerul expirat constituia 0,71 mg/l.Fiind condus la Spitalul raional Rezina și examinat de medicul de gardă M., potrivit procesului-verbal nr.92 al examinării medicale de constatare a faptului de consum a alcoolului, stări de ebrietate și naturii ei, s-a concluzionat „consum de alcool, treaz”. Fiindu-i propus să fie recoltate probe biologice pentru analiza de laborator, necesară pentru stabilirea stării de ebrietate și concentrației alcoolului în sînge, Odobesco Victor a refuzat categoric, prin ce a încălcat prevederile art.21 al Regulamentului privind modul de testate alcooscopică și examinare medicală pentru stabilirea stării de ebrietate și naturii ei, aprobat prin Hotărîrea Guvernului nr. 296 din 16.04.2009. În partea pregătitoare a şedinţei de judecată inculpatul O. a înaintat o cerere, conform [[crăeea]] recunoaşte deplin vina în săvărşirea infracţiunii prevăzută de art. 2641 alin. (3 ) Cod Penal şi în temeiul art. 60 alin.(1) lit. a) Cod penal, art. 332 alin.(5) Cod de procedură penală solicită liberarea sa de răspunderea penală în legătură cu intervenirea termenului de prescripţie de tragere la răspundere penală. Apărătorul [[Letfer]] Stela a susţinut demersul înaintat de inculpatul O. şi a solicitat admiterea lui. Procurorul G.[[considreă]] că demersul urmează a fi satisfăcut, deoarece infracţiunea săvărşită de inculpatul O. este una uşoară, de la comiterea ei au trecut mai mult de doi ani şi conform art. 60 alin.(1) lit.a)Cod [[pneal]] acesta urmează a fi liberat de răspundere penală. Ascultînd opiniile părţilor, studiind materialele dosarului, înstanţa de judecată [[consiedră]] că [[proecsul]] [[peanl]] în privinţa inculpatului O. urmează a fi [[încteat]] din următoarele considerente. Potrivit art. 60 alin.(1) lit. a) Cod penal persoana se liberează de răspunderea penală dacă din ziua săvărşirii infracţiunii au expirat termenele de 2 ani de la săvărşirea unei infracţiuni uşoare. Prin acţiunile sale inculpatul O. la 10 septembrie 2011a săvîrşit o infracţiune mai puţin gravă şi acţiunile lui just a fost încadrate în baza art. 2641 alin.(3) Cod penal - refuzul conducătorului mijlocului de transport de la recoltarea probelor biologice în cadrul examenului medical în vederea stabilirii stării de ebrietate și naturii ei. Conform art. 332 alin.(1) CPP în cazul în care, pe parcursul judecării cauzei se constată că a intervenit termenul de prescripţie / art. 275 pct.4) CPP/ şi inculpatul solicită încetarea procesului penal, instanţa prin sentinţă motivată, încetează procesul penal în cauza respectivă. Din considerentele enunţate instanţa de judecată conchide că procesul penal în cauza lui Odobesco Victor privind învinuirea adusă în baza art. 2641 alin. (3 ) Cod penal urmează a fi încetat. În conformitate cu prevederile art. 60 alin.(1) lit. a) Cod penal, art.art. 275 pct.4), 332 alin.(1), 391 alin.(1) pct.6, 392-393, 394 alin.(4), 396 Cod de porcedură penală, instanţa de judecată ,-

--------------------------------------------- Result 18 ---------------------------------------------
[[0 (97%)]] --> [[1 (55%)]]

Prin încheierea judecătorului de instrucţie din 23.07.2015 s­a respins ca inadmisibilă [[plîngerea]] înaintată de [[Dogotari]] Alexandru în baza art. 313 Cod Procedură Penală privind contestarea ordonanței procurorului Lilia Selevestru din 29.05.2015. Nefiind de acord cu încheierea emisă, la data de 28.07.2015, Dogotari Alexandru a înaintat recurs, solicitînd anularea încheierii Judecătoriei Bălți din 23.07.2015 ca ilegală cu emiterea unei noi hotărîri în beneficiul său. În motivarea recursului a invocat că judecătorul de instrucție [[Eremciuc]] Ghenadie la examinarea cauzei a încălcat prevederile art. 313 alin. (1) Cod Procedură Penală, și anume el a tăinuit faptul că procurorul Lilia Selevestru a încălcat termenul de examinare pe cauza penală nr. B20159780008 din 19.05.2015 R­1, invocînd că el a primit ordonanța din 29.05.2015 a procuraturii Anticorupție cu o mare întîrziere și anume la 09.07.2015. Procurorul și judecătorul din Bălți au încălcat drepturile și interesele legitime prevăzute la art. 1,19 alin. (3), 95, 100,252, 254 Cod procedură Penală și nu a 1 1 fost efectuată de către aceștia o cercetare obiectivă și completă fiind încălcate prevederile art. 6 p.37 , 52 alin. (2) p.3 , 231, 255 Cod procedură penală. Dogotari Alexandru a refuzat să fie escortat în şedinţa instanței de recurs, totodată prezentînd cerere prin care susține recursul declarat, solicitînd examinarea cauzei în absența sa, Colegiul considerînd posibil și dispunînd judecarea recursului în lipsa lui. Avocatul Rotari Mihaela în ședința instanței de recurs a indicat că recursul înaintat este întemeiat, solicitînd admiterea acestuia cu anularea încheierii judecătorului de instrucție. În ședința instanței de recurs procurorul participant Lilia Selevestru a solicitat respingerea recursului, pe motiv că încheierea judecătorului de instrucție este irevocabilă și nu se supune căilor ordinare de atac, iar în afară de aceasta potrivit ordinii stabilite de [[legiuitor]] condamnatul nu a atacat ordonanța procurorului la procurorul ierarhic superior. Verificînd argumentele invocate în recurs în raport cu materialele cauzei şi cu prevederile legii, Colegiul penal consideră recursul inadmisibil şi pasibil de respins, cu menţinerea încheierii judecătorului de instrucţie din 23.07.2015 din următoarele considerente. Instanța de recurs menționează că, Codul de procedură penală prevede expres actele şi acţiunile organului de urmărire penală care pot fi atacate judecătorului de instrucţie. Conform art.313 alin.(1,2) CPP, [[plîngerile]] împotriva acţiunilor şi actelor ilegale ale organului de urmărire penală şi ale organelor care exercită activitate specială de investigaţii pot fi înaintate judecătorului de instrucţie de către bănuit, învinuit, apărător, partea vătămată, de alţi participanţi la proces sau de către alte persoane drepturile şi interesele legitime ale cărora au fost încălcate de aceste organe, în cazul în care persoana nu este de acord cu rezultatul examinării plîngerii sale de către procuror sau nu a primit răspuns la plîngerea sa de la procuror în termenul prevăzut de lege. (2) Persoanele indicate în alin.(1) sînt în drept de a ataca judecătorului de instrucţie: 1) refuzul organului de urmărire penală: a) de a primi plîngerea sau denunţul privind pregătirea sau săvîrşirea infracţiunii; b) de a satisface demersurile în cazurile prevăzute de lege; c) de a începe urmărirea penală; 2) ordonanţele privind încetarea urmăririi penale, clasarea cauzei penale sau scoaterea persoanei de sub urmărire penală; 3) alte acţiuni

Prin încheierea judecătorului de instrucţie din 23.07.2015 s­a respins ca inadmisibilă [[plîgnerea]] înaintată de [[Dogotrai]] Alexandru în baza art. 313 Cod Procedură Penală privind contestarea ordonanței procurorului Lilia Selevestru din 29.05.2015. Nefiind de acord cu încheierea emisă, la data de 28.07.2015, Dogotari Alexandru a înaintat recurs, solicitînd anularea încheierii Judecătoriei Bălți din 23.07.2015 ca ilegală cu emiterea unei noi hotărîri în beneficiul său. În motivarea recursului a invocat că judecătorul de instrucție [[Erecmiuc]] Ghenadie la examinarea cauzei a încălcat prevederile art. 313 alin. (1) Cod Procedură Penală, și anume el a tăinuit faptul că procurorul Lilia Selevestru a încălcat termenul de examinare pe cauza penală nr. B20159780008 din 19.05.2015 R­1, invocînd că el a primit ordonanța din 29.05.2015 a procuraturii Anticorupție cu o mare întîrziere și anume la 09.07.2015. Procurorul și judecătorul din Bălți au încălcat drepturile și interesele legitime prevăzute la art. 1,19 alin. (3), 95, 100,252, 254 Cod procedură Penală și nu a 1 1 fost efectuată de către aceștia o cercetare obiectivă și completă fiind încălcate prevederile art. 6 p.37 , 52 alin. (2) p.3 , 231, 255 Cod procedură penală. Dogotari Alexandru a refuzat să fie escortat în şedinţa instanței de recurs, totodată prezentînd cerere prin care susține recursul declarat, solicitînd examinarea cauzei în absența sa, Colegiul considerînd posibil și dispunînd judecarea recursului în lipsa lui. Avocatul Rotari Mihaela în ședința instanței de recurs a indicat că recursul înaintat este întemeiat, solicitînd admiterea acestuia cu anularea încheierii judecătorului de instrucție. În ședința instanței de recurs procurorul participant Lilia Selevestru a solicitat respingerea recursului, pe motiv că încheierea judecătorului de instrucție este irevocabilă și nu se supune căilor ordinare de atac, iar în afară de aceasta potrivit ordinii stabilite de [[legiutior]] condamnatul nu a atacat ordonanța procurorului la procurorul ierarhic superior. Verificînd argumentele invocate în recurs în raport cu materialele cauzei şi cu prevederile legii, Colegiul penal consideră recursul inadmisibil şi pasibil de respins, cu menţinerea încheierii judecătorului de instrucţie din 23.07.2015 din următoarele considerente. Instanța de recurs menționează că, Codul de procedură penală prevede expres actele şi acţiunile organului de urmărire penală care pot fi atacate judecătorului de instrucţie. Conform art.313 alin.(1,2) CPP, [[plîngeirle]] împotriva acţiunilor şi actelor ilegale ale organului de urmărire penală şi ale organelor care exercită activitate specială de investigaţii pot fi înaintate judecătorului de instrucţie de către bănuit, învinuit, apărător, partea vătămată, de alţi participanţi la proces sau de către alte persoane drepturile şi interesele legitime ale cărora au fost încălcate de aceste organe, în cazul în care persoana nu este de acord cu rezultatul examinării plîngerii sale de către procuror sau nu a primit răspuns la plîngerea sa de la procuror în termenul prevăzut de lege. (2) Persoanele indicate în alin.(1) sînt în drept de a ataca judecătorului de instrucţie: 1) refuzul organului de urmărire penală: a) de a primi plîngerea sau denunţul privind pregătirea sau săvîrşirea infracţiunii; b) de a satisface demersurile în cazurile prevăzute de lege; c) de a începe urmărirea penală; 2) ordonanţele privind încetarea urmăririi penale, clasarea cauzei penale sau scoaterea persoanei de sub urmărire penală; 3) alte acţiuni

--------------------------------------------- Result 19 ---------------------------------------------
[[1 (95%)]] --> [[0 (51%)]]

xxxxNUMExxxx, este învinuit în faptul că, în noaptea de 17.10.2014 spre 18.10.2014, aflîndu­se împreună cu cet. L. I. M., a.n.­­, locuitor s. U., raionul R., precum și minorul L. V. I., a.n. ­­, în locuința situată în s. U., raionul R., cu care au servit băuturi alcoolice, având scopul de ­l omoră, intenționat, cu o deosebită cruzime, i­au aplicat ultimului multiple lovituri cu pumnii și picioarele peste diferite ărți ale corpului, după care, cu ajutorul unui băț din lemn, pe care­l avea la sine, i­au aplicat cet. S. D.A., multiple lovituri, peste organele de importa ță vitală­cutie toracică și cap, astfel cauzîndu­i ultimului, conform raportului de examinare medico­legale nr. 115„c” din 20.10.2014, leziuni corporale GRAVE, periculoase pentru viața și sănătatea persoanei, sub formă de: Hemoragii în țesuturile moi percraniene, hemoragii subarahnoidiene, ruptuă postraumatică a [[aparatului]] ligamentar a vertebre II cervicale, echimoze, plăgi contuze pe diferite regiuni ale corpului, în rezultatul ărora ultimul a decedat. Prin acțiunile sale intenționate xxxxNUMExxxx a săvîrșit infracțiunea prevăzută și sancționată de prevederile art. 145 alin.(2) lit.i),j) Cod penal al R. Moldova (omorul inte ționat) cu indicii de calificare: omorul intenționat al unei persoane, săvîrșit de două persoane, cu deosebiă cruzime. La 18 octombrie 2014, de către organul de urmărire penală al IP R. pe [[cazul]] dat a fost pornită urmărirea penală cu nr. 2014300367, în baza elementelor constitutive ale infra ţiunii prevăzute de art. 145 alin. (2 lit. i), j) Cod penal.. La 18 octombrie 2014, la ora 13:15, xxxxNUMExxxx a fost reţinut în ordinea prevederilor art. 165­166 CPP al R. Moldova. La 21 octombrie 2014, xxxxNUMExxxx a fost pus sub învinuire de comitere a infracţiunii [[prevăzute]] de art.145 alin.(2) lit. i), j) Cod [[penal]] La 21 octombrie 2014, în [[privința]] învinuitului xxxxNUMExxxx a fost aplicată măsura preventivă­arestul preventiv, și eliberat mandat de arest pe un termen de 30 (treizeci) yile, din momentul r ținerii, pînă la 17 noiembrie 2014, ora 13:15. La data de 13 noiembrie 2014, în privința învinuitului xxxxNUMExxxx, a fost prelungită durata ținerii în stare de arest preventiv pe un termen de 30 zile, pî ă la data de 17 decembrie, ora 13:15. La data de 15 decedmbrie 2014, în privința învinuitului xxxxNUMExxxx, a fost prelungită durata ținerii în stare de arest preventiv pe un termen de 30 zile, pî ă la data de 16 ianuarie 2015, ora 13:15. La data de 06 ianuarie 2015, procurorul în procuratura raionului Rîșcani Victor Rauh a înaintat demers privind prelungirea duratei inerii sub arest preventiv a învinuitului xxxxNUMExxxx pentru o perioadă de 30 zile, invocînd următoarele motive: Actualmente la momentul reținerii organul de urmărire penală are suspiciuni că învinuitul ar putea să se ascundă de la prezența în f ța organului de urmărire penală, să împiedice stabilirea adevărului în procesul penal sau să săvîrșească acțiuni criminale asupra eventualilor martori și victime, să­i influințeze în continuare la darea depozițiilor false sau prin diferite metode ilegale să influențeze organul de ur ărire în vederea tărăgănării și examinării injuste a cazului. Conform datelor operative de investigație, care pot fi dezvăluite confidențial doar judecătorului de instrucție, precum celor rezultate din

xxxxNUMExxxx, este învinuit în faptul că, în noaptea de 17.10.2014 spre 18.10.2014, aflîndu­se împreună cu cet. L. I. M., a.n.­­, locuitor s. U., raionul R., precum și minorul L. V. I., a.n. ­­, în locuința situată în s. U., raionul R., cu care au servit băuturi alcoolice, având scopul de ­l omoră, intenționat, cu o deosebită cruzime, i­au aplicat ultimului multiple lovituri cu pumnii și picioarele peste diferite ărți ale corpului, după care, cu ajutorul unui băț din lemn, pe care­l avea la sine, i­au aplicat cet. S. D.A., multiple lovituri, peste organele de importa ță vitală­cutie toracică și cap, astfel cauzîndu­i ultimului, conform raportului de examinare medico­legale nr. 115„c” din 20.10.2014, leziuni corporale GRAVE, periculoase pentru viața și sănătatea persoanei, sub formă de: Hemoragii în țesuturile moi percraniene, hemoragii subarahnoidiene, ruptuă postraumatică a [[apartaului]] ligamentar a vertebre II cervicale, echimoze, plăgi contuze pe diferite regiuni ale corpului, în rezultatul ărora ultimul a decedat. Prin acțiunile sale intenționate xxxxNUMExxxx a săvîrșit infracțiunea prevăzută și sancționată de prevederile art. 145 alin.(2) lit.i),j) Cod penal al R. Moldova (omorul inte ționat) cu indicii de calificare: omorul intenționat al unei persoane, săvîrșit de două persoane, cu deosebiă cruzime. La 18 octombrie 2014, de către organul de urmărire penală al IP R. pe [[czaul]] dat a fost pornită urmărirea penală cu nr. 2014300367, în baza elementelor constitutive ale infra ţiunii prevăzute de art. 145 alin. (2 lit. i), j) Cod penal.. La 18 octombrie 2014, la ora 13:15, xxxxNUMExxxx a fost reţinut în ordinea prevederilor art. 165­166 CPP al R. Moldova. La 21 octombrie 2014, xxxxNUMExxxx a fost pus sub învinuire de comitere a infracţiunii [[prevzăute]] de art.145 alin.(2) lit. i), j) Cod [[pneal]] La 21 octombrie 2014, în [[pirvința]] învinuitului xxxxNUMExxxx a fost aplicată măsura preventivă­arestul preventiv, și eliberat mandat de arest pe un termen de 30 (treizeci) yile, din momentul r ținerii, pînă la 17 noiembrie 2014, ora 13:15. La data de 13 noiembrie 2014, în privința învinuitului xxxxNUMExxxx, a fost prelungită durata ținerii în stare de arest preventiv pe un termen de 30 zile, pî ă la data de 17 decembrie, ora 13:15. La data de 15 decedmbrie 2014, în privința învinuitului xxxxNUMExxxx, a fost prelungită durata ținerii în stare de arest preventiv pe un termen de 30 zile, pî ă la data de 16 ianuarie 2015, ora 13:15. La data de 06 ianuarie 2015, procurorul în procuratura raionului Rîșcani Victor Rauh a înaintat demers privind prelungirea duratei inerii sub arest preventiv a învinuitului xxxxNUMExxxx pentru o perioadă de 30 zile, invocînd următoarele motive: Actualmente la momentul reținerii organul de urmărire penală are suspiciuni că învinuitul ar putea să se ascundă de la prezența în f ța organului de urmărire penală, să împiedice stabilirea adevărului în procesul penal sau să săvîrșească acțiuni criminale asupra eventualilor martori și victime, să­i influințeze în continuare la darea depozițiilor false sau prin diferite metode ilegale să influențeze organul de ur ărire în vederea tărăgănării și examinării injuste a cazului. Conform datelor operative de investigație, care pot fi dezvăluite confidențial doar judecătorului de instrucție, precum celor rezultate din

--------------------------------------------- Result 20 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

XXse învinuieşte în aceia, că în a doua jumătate a zilei de 10 decembrie 2015, aflîndu­se la locuinţa familiei XXdin satul XXa, din intenţii de profit, avînd scopul sustragerii bunurilor altei persoane, a sustras pe ascuns dintr­o cutie de carton, bani în sumă totală de 1800 (una mie opt sute) lei. În rezultatul furtului dat proprietarului XX i­a fost cauzată o daună materială considerabilă. Acţiunile inculpatei XXau fost calificate de către organul de urmărire penală în baza art.186 alin.2 lit. d) Cod Penal, furtul, adică sustragerea pe ascuns a bunurilor altei persoane săvîrşite cu cauzarea de daune în proporţii considerabile. În partea pregătitoare a şedinţei de judecată partea vătămată XXa depus o cerere, solicitînd încetarea procesului penal de învinuire a lui XX în legătură cu împăcarea sa cu inculpata. Pretenţii materiale sau morale faţă XX nu are. Inculpata XX în ședința de judecată a confirmat faptul împăcării sale cu partea vătămată XX, acceptînd ca procesul penal, pornit împotriva sa fie încetat în legătură cu împăcarea. Potrivit dispoziei alin.(1) art.109 CP, împăcarea este actul de înlăturare a răspunderii penale pentru o infracţiune uşoară sau mai puţin gravă, infracţiuni prevăzute de de capitolul II­VI din Partea specială, precum şi în cazurile pervăzute de procedura penală. Sancţiunea alin.(2) art.186 prevede amendă în mărime de la 300 la 1000 unităţi convenţionale sau muncă neremunerată în folosul comunităţii de la 180 la 240 de ore, sau închisoare de pînă la 4 ani, şi conform art.16 CP, infracțiunea respectivă este considerată mai puţin gravă. În cazul dat, legea penală permite admite împăcarea părţilor. Procurorul a susţinut poziţia părţii vătămate şi a solicitat încetarea procesului penal. Pentru această soluţie a pledat şi apărătorul inculpatei. Din considerentele enunţate, instanţa de judecată conchide că procesul penal în cauza ce o privește pe MXX privind învinuirea adusă în baza art.186 alin.(2) lit.d) CP urmează a fi încetat. În temeiul celor elucidate şi expuse, călăuzindu­se de art.109 alin.1 CP, 340,384, 385, 391 al.1 pct1), art.392­394, 396 şi 397 CPP, instanţa de judecată,

--------------------------------------------- Result 21 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

La data de 23.02.2015, consilierul de probațiune din cadrul Biroului de Probațiune xxxxORAS_SATxxxx­V.Vacarciuc a înaintat un deners instanței de n judecată, prin care solicită anunțarea în căutare a condamnatului Brînză xxxxNUMExxxx, a.n.xxxxDATA_NASTERIIxxxx, domiciliat s.Răspopeni r.xxxxORAS_SATxxxx. Consilierul de probațiune V.Vacarciuc a invocat în demersul înaintat că, la data de 17.02.2014 în adresa Biroului de Probațiune xxxxORAS_SATxxxx a fost n expediată spre executare copia sentinței nr.1­3/2014 din 28.01.2014 emisă de Judecătoria Militară mun.Chișinău privind condamnarea, în baza art.188 alin.(2) lit.b), e), f) CP, a lui Brînză xxxxNUMExxxx stabilindu­i ca pedeapsă închisoare pe termen de 4 (patru)ani, cu suspendarea condiționată a pedepsei în conformitate cu prevederile art.90 Cod Penal pe un termen de probă de 5(cinci) ani, cu obigarea să nu­şi schimbe locul de trai fără acordul organului competent. Pe perioada ispășirii pedepsei, condamnatul Brînză Serghei Noicolai a încălcat obligațiunile și cerințele legale, neprezentîndu­se în termenii stabiliți la Biroul de n Probațiune xxxxORAțS_SATxxxx. Iar în urma măsurșilor dțe rigoare întreprinse de Biroul de Probațiune s­a constatat că condamnatul Brînză Serghei nu se află la domiciliu și este plecat într­o direcție necunoscută ț Consilierul de probaiune V. Vacarciuc, a solicită în edină de judecată admiterea demersului şi anunţarea în căutare a condamnatului Brînză Serghei. n Procurorul a susținut demersul reprezentantului Biroului de probaiune. n n Analizînd materialețle demersului, audiind opinia consilierșului de probațiune și cea a procurorului, instanţa consideră demȘersul întșemeiat şi necesar a fi satisfăcut deoarece sînt prezentate probe suficiente pentru confirmarea faptului că condamnatul Brînză xxxxNUMExxxx se ascunde de la organul care pune în executare sentina Judecătoriei Militare mun.Chișinău i anume : certificatul eliberat de primăria s. Răspopeni raionul oldăne ti, ce confirmă că condamnatul în timpul actual nșu se află pe teritoriul primăriei, şi raportul ispectorului de sector M.Timercan, potrivit căruia nici rudele apropiate nu cunosc locul aflării condamnatului Brînză Serghei. În baza celor expuse, de fapt i de drept, conform art. 469 p.10 ,470 – 472 , instanţa de judecată,­ n

--------------------------------------------- Result 22 ---------------------------------------------
[[0 (98%)]] --> [[1 (63%)]]

Prin sentinţa judecătoriei or. Căușeni din 04 iunie 2014, xxxxNUMExxxx a fost condamnat la muncă [[neremunerată]] în folosul comunităţii pe un termen de 160 ore, pentru comiterea infracţiunii prevăzute de art. 287al. (1) CP RM, din care el nu a executat nici o ora. În demersul înaintat, se solicită înlocuirea muncii neremunerate în folosul comunităţii,cu închisoarea motivînd cu faptul, că xxxxNUMExxxx se [[eschivează]] cu rea voinţă de la executarea pedepsei aplicate. În şedinţa de judecata consilierul de [[probatiune]] a susţinut demersul înaintat pe deplin. [[Condamnatul]] in sedinta de judecata nu s­a prezentat, desi a fost legal citat si nici n­a comunicat motivele [[neprezentarii]]. Nu a fost posibil de executat nici aducerea silita a [[condamnatului]] din motiv ca el a parasit locul de trai, de aceia instanta a decis examinarea cauzei in lipsa lui. Procurorul si aparatorul in sedinta de judecata au solicitat respingerea demersului ca fiind [[neintemeiat]]. [[Ascultînd]] consilierul de probatiune, apărătorul si procurorul,examinînd materialele cauzei,judecata consideră demersul intemeiat si care urmeaza a fi admis din urmatoarele considerente. Astfel,conform art.67 p.3 CP, condamnatilor ce se [[eschiveaza]] cu rea vointa de la executarea pedepsei sub forma de munca [[neremunerata]] in folosul comunitatii, pedeapsa aplicata, se inlocuieste cu inchisoare, calculindu­se o zi de inchisoare pentru 2 ore de munca neremunerata in folosul comunitatii. Conform Regulamentului cu privire la modul de executare a muncii neremunerate in folosul comunitatii,adoptat prin [[Hotarirea]] Guvernului nr.1643 din 31.12.2003,p. 33,se consideră eschivare cu rea voinţă de la executarea pedepsei sub formă de muncă neremunerată, neprezentarea la citarea serviciului de executare a condamnatului de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei,încălcarea de către [[condamnat]] a disciplinei muncii de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei (sosirea la locul de muncă cu întîrziere sau părăsirea acestuia înainte de termen, neexecutarea sau executarea intenţionat eronată a dispoziţiilor şi indicaţiilor persoanei responsabile de executarea lucrărilor etc. ,neprezentarea condamnatului la muncă fără motive întemeiate de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei. Conform art. 191 Cod de executare,condamnatul la munca neremunerată în folosul comunităţii este obligat să se prezinte la citare la organul de probaţiune, să respecte modul şi condiţiile de executare a pedepsei, regulamentul de ordine interioară a organizaţiei în care este antrenat la muncă, să lucreze conştiincios la obiectele la care a fost repartizat, să execute termenul de prestare a muncii neremunerate în folosul comunităţii, să informeze oficiul de executare despre schimbarea domiciliului sau despre imposibilitatea temporară de a presta munca. Aliniatul (2) al acestui articol stipuleaza ca dacă persoana condamnată la munca neremunerată în folosul comunităţii nu execută această pedeapsă sau, în timpul executării, are o conduită necorespunzătoare manifestată prin neîndeplinirea obligaţiilor care îi revin sau prin îndeplinirea lor defectuoasă, organul de probaţiune adresează instanţei de judecată un demers privind înlocuirea muncii neremunerate în folosul comunităţii cu o altă pedeapsă. In cazul dat,insa instanta de judecata considera,ca de catre Biroul de probatiune nu s­a dovedit faptul ca condamnatul xxxxNUMExxxx se eschiveaza cu rea vointa de la executarea pedepsei aplicate.Desi indata dupa

Prin sentinţa judecătoriei or. Căușeni din 04 iunie 2014, xxxxNUMExxxx a fost condamnat la muncă [[nreemunerată]] în folosul comunităţii pe un termen de 160 ore, pentru comiterea infracţiunii prevăzute de art. 287al. (1) CP RM, din care el nu a executat nici o ora. În demersul înaintat, se solicită înlocuirea muncii neremunerate în folosul comunităţii,cu închisoarea motivînd cu faptul, că xxxxNUMExxxx se [[eschievază]] cu rea voinţă de la executarea pedepsei aplicate. În şedinţa de judecata consilierul de [[porbatiune]] a susţinut demersul înaintat pe deplin. [[Condmanatul]] in sedinta de judecata nu s­a prezentat, desi a fost legal citat si nici n­a comunicat motivele [[neprezentairi]]. Nu a fost posibil de executat nici aducerea silita a [[cnodamnatului]] din motiv ca el a parasit locul de trai, de aceia instanta a decis examinarea cauzei in lipsa lui. Procurorul si aparatorul in sedinta de judecata au solicitat respingerea demersului ca fiind [[neinetmeiat]]. [[Asclutînd]] consilierul de probatiune, apărătorul si procurorul,examinînd materialele cauzei,judecata consideră demersul intemeiat si care urmeaza a fi admis din urmatoarele considerente. Astfel,conform art.67 p.3 CP, condamnatilor ce se [[eschivezaa]] cu rea vointa de la executarea pedepsei sub forma de munca [[neremunreata]] in folosul comunitatii, pedeapsa aplicata, se inlocuieste cu inchisoare, calculindu­se o zi de inchisoare pentru 2 ore de munca neremunerata in folosul comunitatii. Conform Regulamentului cu privire la modul de executare a muncii neremunerate in folosul comunitatii,adoptat prin [[Hotariera]] Guvernului nr.1643 din 31.12.2003,p. 33,se consideră eschivare cu rea voinţă de la executarea pedepsei sub formă de muncă neremunerată, neprezentarea la citarea serviciului de executare a condamnatului de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei,încălcarea de către [[condanmat]] a disciplinei muncii de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei (sosirea la locul de muncă cu întîrziere sau părăsirea acestuia înainte de termen, neexecutarea sau executarea intenţionat eronată a dispoziţiilor şi indicaţiilor persoanei responsabile de executarea lucrărilor etc. ,neprezentarea condamnatului la muncă fără motive întemeiate de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei. Conform art. 191 Cod de executare,condamnatul la munca neremunerată în folosul comunităţii este obligat să se prezinte la citare la organul de probaţiune, să respecte modul şi condiţiile de executare a pedepsei, regulamentul de ordine interioară a organizaţiei în care este antrenat la muncă, să lucreze conştiincios la obiectele la care a fost repartizat, să execute termenul de prestare a muncii neremunerate în folosul comunităţii, să informeze oficiul de executare despre schimbarea domiciliului sau despre imposibilitatea temporară de a presta munca. Aliniatul (2) al acestui articol stipuleaza ca dacă persoana condamnată la munca neremunerată în folosul comunităţii nu execută această pedeapsă sau, în timpul executării, are o conduită necorespunzătoare manifestată prin neîndeplinirea obligaţiilor care îi revin sau prin îndeplinirea lor defectuoasă, organul de probaţiune adresează instanţei de judecată un demers privind înlocuirea muncii neremunerate în folosul comunităţii cu o altă pedeapsă. In cazul dat,insa instanta de judecata considera,ca de catre Biroul de probatiune nu s­a dovedit faptul ca condamnatul xxxxNUMExxxx se eschiveaza cu rea vointa de la executarea pedepsei aplicate.Desi indata dupa

--------------------------------------------- Result 23 ---------------------------------------------
[[0 (96%)]] --> [[1 (52%)]]

1.1.***** în noaptea de 09.08.2018 în jurul orelor 02:00, aflîndu-se în s. Grigorăuca, r-nul Sîngerei, acționînd în scopul răpirii mijlocului de transport, în comun cu minorii ***** (în privința cărora dosarul este disjungat pentru examinare într-o procedură separată) profitînd de faptul că nu sunt observați de [[cineva]] au răpit autocamionul de model ”Mercedes Vito 112C” cu numărul de înmatriculare FUE 746 de culoare albastru închis, în valoare de 80 000 lei, ce-i aparține lui *****, care era parcat în ograda casei, cheile acestuia fiind în lacătul de la ușă. ***** împreună cu minorii ***** (în privința cărora dosarul este disjungat pentru examinare într-o procedură separată) s-au folosit de aceste autocamion după propriul lor plac [[pînă]] la 09.08.2018 orele 06:00 cînd epuizînd carburanții l-au abandonat în preajma s. Hîrtopul Mare, r-nul Criuleni. 1.2.Tot, el împreună și de comun acord cu minorul *****, în noaptea de 20.03.2019 spre 21.03.2019, au pătruns în biserica sat. Flămînzeni r-nul Sîngerei, de unde prin deteriorarea ușii unui dulap unde se păstrau surse bănești a [[bisericii]], pe ascuns au sustras 3 200 euro, echivalentul a 62 688 lei și 54 000 lei, prin ce i-au cauzat victimei un prejudiciu material în proporții considerabile în sumă de 116 688 lei. 1.3.Tot el, împreună și de comun acord cu minorul ***** în noaptea de 20.03.2019 spre 21.03.[[2019]], folosindu-se de faptul că nu sunt observați de [[nimeni]], prin spargerea geamului au pătruns în [[biserica]] „Sf. Ar. Gavriil și Mihail” din sat. Coșcodeni r-nul Sîngerei, de unde pe ascuns au sustras 10 000 lei, prin ce i-au cauzat [[victimei]] un prejudiciu material în proporții [[considerabile]] în sumă de 10 000 lei. 1.4.Tot el, împreună și de comun acord cu [[minorul]] ***** la data de 22.03.[[2019]] aproximativ în jurul orelor 00:30 min., urmărind scopul sustragerii [[bunurilor]] altei persoane, [[folosindu-se]] de faptul că nu sunt observați de nimeni, prin deteriorarea ferestrei au pătruns în biserica „Sf. Nicolai” din sat. Chișcăreni r-nul Sîngerei, de unde au încercat să sustragă pe ascuns mai multe bunuri din biserică, acțiuni însă, care nu și-au produs efectul din motive independente de voința făptuitorilor și anume din motivul că au fost observați de către o persoană, astfel ne permițându-le realizarea scopului de a sustrage bunurile, totodată determinându-i să înceteze acțiunile sale ilegale. 2.ANALIZA PROBELOR. Fiindcă cauza s-a judecat în procedura simplificată, prevăzută de art.364/1 CPP pe baza probelor administrate în faza de urmărire penală, instanţa de judecată a analizat următoarele probe prezentate de procuror şi acceptate de inculpatul minor şi care demonstrează integral vinovăţia acestuia: 2.1.EPISODUL RĂPIRII MIJLOCULUI DE TRANSPORT FĂRP SCOP DE ÎNSTRĂINARE DE LA GADÎRCA GHEORGHE. -declarațiile părții vătămate ***** depuse în cadrul urmăririi și din care în esență rezultă că din primăvara anului 2015 are în proprietate un autocamion de model ”Mercedes Vito 112C” cu n/î FUE 746 de culoare albastru închis, care valorează aproximativ 80 000 lei. În seara de 08 august 2018 a parcat acest mijloc de transport în ograda casei. A doua zi dimineața, în jurul orelor 05:00 fiul său trezindu-l din somn i-a comunicat că autocamionul lipsește în ogradă și respectiv a fost răpit.

1.1.***** în noaptea de 09.08.2018 în jurul orelor 02:00, aflîndu-se în s. Grigorăuca, r-nul Sîngerei, acționînd în scopul răpirii mijlocului de transport, în comun cu minorii ***** (în privința cărora dosarul este disjungat pentru examinare într-o procedură separată) profitînd de faptul că nu sunt observați de [[cinvea]] au răpit autocamionul de model ”Mercedes Vito 112C” cu numărul de înmatriculare FUE 746 de culoare albastru închis, în valoare de 80 000 lei, ce-i aparține lui *****, care era parcat în ograda casei, cheile acestuia fiind în lacătul de la ușă. ***** împreună cu minorii ***** (în privința cărora dosarul este disjungat pentru examinare într-o procedură separată) s-au folosit de aceste autocamion după propriul lor plac [[pnîă]] la 09.08.2018 orele 06:00 cînd epuizînd carburanții l-au abandonat în preajma s. Hîrtopul Mare, r-nul Criuleni. 1.2.Tot, el împreună și de comun acord cu minorul *****, în noaptea de 20.03.2019 spre 21.03.2019, au pătruns în biserica sat. Flămînzeni r-nul Sîngerei, de unde prin deteriorarea ușii unui dulap unde se păstrau surse bănești a [[bsiericii]], pe ascuns au sustras 3 200 euro, echivalentul a 62 688 lei și 54 000 lei, prin ce i-au cauzat victimei un prejudiciu material în proporții considerabile în sumă de 116 688 lei. 1.3.Tot el, împreună și de comun acord cu minorul ***** în noaptea de 20.03.2019 spre 21.03.[[2109]], folosindu-se de faptul că nu sunt observați de [[nimnei]], prin spargerea geamului au pătruns în [[bsierica]] „Sf. Ar. Gavriil și Mihail” din sat. Coșcodeni r-nul Sîngerei, de unde pe ascuns au sustras 10 000 lei, prin ce i-au cauzat [[vitcimei]] un prejudiciu material în proporții [[considreabile]] în sumă de 10 000 lei. 1.4.Tot el, împreună și de comun acord cu [[minroul]] ***** la data de 22.03.[[2109]] aproximativ în jurul orelor 00:30 min., urmărind scopul sustragerii [[buunrilor]] altei persoane, [[foloisndu-se]] de faptul că nu sunt observați de nimeni, prin deteriorarea ferestrei au pătruns în biserica „Sf. Nicolai” din sat. Chișcăreni r-nul Sîngerei, de unde au încercat să sustragă pe ascuns mai multe bunuri din biserică, acțiuni însă, care nu și-au produs efectul din motive independente de voința făptuitorilor și anume din motivul că au fost observați de către o persoană, astfel ne permițându-le realizarea scopului de a sustrage bunurile, totodată determinându-i să înceteze acțiunile sale ilegale. 2.ANALIZA PROBELOR. Fiindcă cauza s-a judecat în procedura simplificată, prevăzută de art.364/1 CPP pe baza probelor administrate în faza de urmărire penală, instanţa de judecată a analizat următoarele probe prezentate de procuror şi acceptate de inculpatul minor şi care demonstrează integral vinovăţia acestuia: 2.1.EPISODUL RĂPIRII MIJLOCULUI DE TRANSPORT FĂRP SCOP DE ÎNSTRĂINARE DE LA GADÎRCA GHEORGHE. -declarațiile părții vătămate ***** depuse în cadrul urmăririi și din care în esență rezultă că din primăvara anului 2015 are în proprietate un autocamion de model ”Mercedes Vito 112C” cu n/î FUE 746 de culoare albastru închis, care valorează aproximativ 80 000 lei. În seara de 08 august 2018 a parcat acest mijloc de transport în ograda casei. A doua zi dimineața, în jurul orelor 05:00 fiul său trezindu-l din somn i-a comunicat că autocamionul lipsește în ogradă și respectiv a fost răpit.


--------------------------------------------- Result 24 ---------------------------------------------
[[1 (95%)]] --> [[[SKIPPED]]]

xxxxNUMExxxx, fiind în stare de iresponsabilitate a comis fapta prejudiciabilă vătămarea intenţionată gravă a integrităţii corporale, care a provocat decesul victimei în următoarele circumstanţe. xxxxNUMExxxx la 09.07.2011 ora 23:10 aflîndu­se în odaia nr.7 blocul 3 a internatului psihoneurologic din m.Bălţi str. 4, în ospeţie la cet.Boguş Ion, aflîdu­se în stare de ebrietate alcoolică, în procesul conflictului apărzt între ei, l­a lovit de cîteva ori în regiunea corpului, după ce victim a căzut şos şi folosindu­se de aceasta, xxxxNUMExxxx a continuat să­i provoace vătămări lui Boguş Ion, lovindu­l cu piciorul în regiunea gîtului, cauzîndu­i potrivit raprtului de expertiză medico­legală nr. 279D din 27.07.2011, leziuni corporale sub formă de echimoză masivă pe partea anterioară a gîtului cu răspîndire pe regiunea toracală, hemoragii difuze pronunţate în ţesuturile moi ale gîtului, fractura aschiată a cartilajului ureodian cu deplasare, hemoragii sub pleurale şi sub epicardiene, care au adus la decesul victimei prin asfexie mecanică prin comprimare /lovire/. Prin acţiunile sale xxxxNUMExxxx a săvîrşit infracţiunea prevăzută de art.151 al.(4) Cod penal ­ vătămarea intenţionată gravă a integrităţii corporale, care este periculoasă pentru viaţă şi a provocat decesul victimei. Comiterea faptei prejudiciabile de către xxxxNUMExxxx este dovedită şi confirmată prin: ­depoziţiile reprezentantului legal al persoanei iresponsabile – Goncear Nina, care a menţionat că lucrează medic la internatului psihoneurologic din m.Bălţi str. 4. xxxxNUMExxxx este beneficiarul instituţiei medicale, adică pacientă, prezintă diagnosticul “retard mintal sever”. La fel şi Boguş Ion a fost beneficiarul instituţiei medicale, adică pacient. Despre moartea violentă a cet. Boguş Ion din iulie 2011, a menţionat că cadavrul acestuia a fost depistat în odaia nr.7 blocul 3 a internatului psihoneurologic din m.Bălţi str. 4. xxxxNUMExxxx, cît şi alţi pacienţi mergeau în ospeţie unul la altul, inclusiv şi la Boguş Ion, care avea bani, ţigări, poate că şi alcool, ce­l vindea la pacienţi pe ascuns, deoarece conform regulilor se interzice consumul de alcool pe terituriul instituţiei. Presupune că xxxxNUMExxxx şi Boguş Ion erau în relaţii mai aproape, inclusiv intime. În convorbire cu xxxxNUMExxxx, acesta i­a spus că a la lovit pe Boguş Ion, dar nu ţine minte amănuntele conflictului. xxxxNUMExxxx în situaţii de criză prezintă periol, poate manifesta violenţă /f.d.___/. ­depoziţiile martorului Chiatol Lilia, care a declarat că lucrează la internatul psihoneurologic din m.Bălţi str. 4 şi adat delaraţii similare declaraţiilor reprezentantului legal a inculpatei Goncear Nina /f.d.142­143/. ­depoziţiile martorului reprezentantului părţii vătămate BoguşxxxxNUMExxxx, care a relatat că este sora victimei Boguş Ion, fratele s­a aflat ca pacient la internatului psihoneurologic din m.Bălţi str. 4, deoarece suferea de boli mintale. Despre moartea violentă a fratelui său cet. Boguş Ion a aflat în iulie 2011 cadavrul acestuia a fost depistat în odaia sa din instutuţia medicală vizată. Circumstanţele decesului nu le cunoaşte /f.d.141­143, 190/. ­depoziţiile martorului Şaptefraţi Galina, făcute la organul de urmărire penală şi citite în cadrul şedinţei de judecată, care a declarat că este pacientă al internatului psihoneurologic din m.Bălţi str. 4, este în relaţii bune cu xxxxNUMExxxx şi locuiesc într­o odaie. La 09.07.2011 ora 17:00 ea cu xxxxNUMExxxx s­au dus în ospeţie la Boguş Ion,car ia dat bani şi a trimis­o să cumpere o sticlă de

--------------------------------------------- Result 25 ---------------------------------------------
[[0 (86%)]] --> [[[FAILED]]]

XXXXXXXXX la data de 25.06.2013 aproximativ la ora 11.00 împreună cu Preida Vasili, au procurat de la cet. Andrieş Alexandru o cantitate nestabilită a substanţelor narcotice sub formă de marihuană, iar ulterior aflîndu­se în apropierea Dispanserului Ftiziologic, pe strada Ştefan cel Mare din mun. Bălţi, contra sumei de 100 lei au înstrăinat lui Dubovicov Maxim substanţele narcotice procurate ilegal, din care ultimul o parte a consumat personal, iar o altă parte, a predat benevol colaboratorilor de poliţie, sub formă de masă vegetală uscată, mărunţită de culoare verde, care conform raportului de expertiză nr.1663 din 05.07.2013, reprezintă marihuana, cu greutatea de 1,1 gr., în care a fost depistat componentul narcotic activ – tetrahydrocannabinol, prin urmare se atribuie către substanţele narcotice. Marihuana – este inclusă în lista Nr.1, tabelul Nr.1 „Substanţele narcotice, substanţele psohotrope neutilizate în scopuri medicale aprobată prin Hotărîrea Guvernului R.Moldova Nr.1088 din 05.10.2004 şi lista “Substanţelor narcotice, psihotrope şi a plantelor car conţin astfel de substanţe, depistate în trafic ilicit, precum şi cantităţile acestora” aprobată prin Hotărîrea Guvernului nr.79 di 25.01.2006. XXXXXXXXX la data de 25.06.2013 aproximativ la ora 11.00 împreună cu Groşovan Roman, au procurat de la cet.Andrieş Alexandru o cantitate nestabilită a substanţelor narcotice sub formă de marihuană, iar ulterior aflîndu­se în apropierea Dispanserului Ftiziologic, pe strada Ştefan cel Mare, mun. Bălţi contra sumei de 100 lei au înstrăinat lui Dubovicov Maxim substanţele narcotice procurate ilegal, din care ultimul o parte a consumat personal, iar o altă parte, a predat benevol colaboratorilor de poliţie, sub formă de masă vegetală uscată, mărunţită de culoare verde, care conform raportului de expertiză nr.1663 din 05.07.2013, reprezintă marihuana, cu greutatea de 1,1 gr., în care a fost depistat componentul narcotic activ – tetrahydrocannabinol, prin urmare se atribuie către substanţele narcotice. Marihuana – este inclusă în lista Nr.1, tabelul Nr.1 „Substanţele narcotice, substanţele psohotrope neutilizate în scopuri medicale” aprobată prin Hotărîrea Guvernului R.Moldova Nr.1088 din 05.10.2004 şi lista “Substanţelor narcotice, psihotrope şi a plantelor care conţin astfel de substanţe, depistate în trafic ilicit, precum şi cantităţile acestora” aprobată prin Hotărîrea Guvernului nr.79 din 25.01.2006. Inculpatul Preida Vasili Nicolae, după cum s­a constatat în cadrul cercetării judecătoreşti, la data de 23 august 2014, a decedat, fapt confirmat prin extrasul din Registrul de Stat al Populaţiei. Instanţa de judecată a dispus judecarea în continuare a cauzei de învinuire a dînsului cu participarea avocaţilor: XXXXXXXXX şi Rodica Palade. Inculpatul Groşovan Roman în cadrul şedinţei de judecată vina şi­a recunoscut­o integral, declarînd instanţei următoarele: Dînsul în perioada verii anului 2013 se afla la tratament la Dispensarul Ftiziologic din mun. Bălţi; tot acolo se trata şi Preida Vasili, însă într­o altă secţie. În ziua respectivă de ei, care se aflau afară şi fumau împreună cu mai mulţi băieţi, s­a apropiat Dubovicov Maxim care a întrebat dacă poate procura marihuana. Pentru 50 lei, i­a vîndut lui Dubovicov Maxim o cantitate de marihuană care era pusă într­o cutie de chibrituri; această cantitate a luat de la un moş pe nume Andrieş care se afla atunic la fel în spital la tratament. A precizat că afară împreună cu mai mulţi băieţi, la

--------------------------------------------- Result 26 ---------------------------------------------
[[1 (95%)]] --> [[[FAILED]]]

Cet. CURTEAN GHENADIE este învinuit de organul de urmărire penală în aceia că el în perioada de timp al anilor 2009 ­ luna mai 2010, aflându­se în mun.Bălți, acționând în comun acord cu alte persoane nestabilite de organul de urmărire penală, în scopul exploatării sexuale comerciale, prin abuz de poziţia de vulnerabilitate a victimelor, datorită situaţiei precare a acestora, din punct de vedere a supravieţuirii sociale şi prin înșelăciune, sub pretextul angajării la un lucru bine plătit în calitate de dansatoare, le­a recrutat pe Solonari Anna Valeri, născută la 26.11.1986 şi Sugac (Eremciuc) Alexandra, născută la 05.12.1990. Ulterior, cet. Curtean Ghenadie, acționând în comun acord cu alte persoane neidentificate de către organul de urmărire penală, întru realizarea intențiilor sale infracționale, aproximativ la 05.05.2010 a organizat transportarea cet.Sugac (Eremciuc) Alexandra şi Solonari Anna în or.Peatigorsc, Federaţia Rusă, pentru exploatare sexuală. Ajungând în or. Peatigorsc, Sugac (Eremciuc) Alexandra şi Solonari Anna au fost transmise de către Curtean Ghenadie persoanei nestabilite pe nume „Aşot”, care le­a transportat în or.Essentuki, Federaţia Rusă şi le­a adăpostit într­un hotel, confiscând pașapoartele acestora, de unde ultimele regulat au fost transferate către deferiți beneficiari de servicii intime, fiind exploatate sexual aproximativ o lună jumătate. Ulterior, Eremciuc Alexandra şi Solonari Anna, împreună cu paşapoartele lor au fost transmise de către persoana nestabilită pe nume „Aşot”, persoanei nestabilite pe nume „Liliana”, care le­a transportat şi adăpostit într­o saună din același oraş, unde ultimele regulat au fost transferate către deferiți beneficiari, fiind exploatate sexual aproximativ o lună. Aceste acţiuni ale lui Curtean Ghenadie au fost calificate de organul de urmărire penală ca infracţiune prevăzută de art.165 alin.(2) lit.b),d) Cod penal, traficul de fiinţe umane, adică recrutarea, transportarea unei persoane, cu consimţământul acesteia, în scop de exploatare sexuală comercială, săvîrşită prin confiscare a documentelor, precum și prin înșelăciune și abuz de poziţie de vulnerabilitate, de mai multe personae, asupra a mai multe persoane. Tot Curtean Ghenadie, este învinuit de organul de urmărire penală în aceia că el în perioada lunilor martie ­ mai 2010, aflându­se în mun. Bălţi, acţionând în comun acord cu alte persoane nestabilite de organul de urmărire penală, în scopul organizării practicării prostituţiei de către alte persoane pe teritoriul Federaţiei Ruse, a îndemnat şi înlesnit practicarea prostituţiei, prin acordarea contra plată a unor servicii sexuale de către cet. Dibijeva (Daraban) Vera Anatolie, născută la 01.12.1988. Ulterior cet.Curtean Ghenadie, acționând în comun acord cu alte persoane neidentificate de către organul de urmărire penală, întru realizarea intenţiilor sale infracționale, aproximativ la 05.05.2010 a organizat transportarea cet.Dibijeva (Daraban) Vera în or. Peatigorsc, Federaţia Rusă, pentru practicarea prostituției. Ajungând în or. Peatigorsc, Dibijeva (Daraban) Vera a fost transmisă de către Curtean Ghenadie persoanei nestabilite pe nume „Aşot”, care a transportat­o în or.Essentuki, Federaţia Rusă, unde ultima a practicat prostituția aproximativ 2 săptămâni. Aceste acţiuni ale lui Curtean Ghenadie au fost calificate de organul de urmărire penală ca infracţiune prevăzută de art.220 alin.(2) lit.a),c) Cod penal, proxenetism, adică îndemnul şi înlesnirea practicării prostituţiei de către alte persoane, acţiuni săvîrşite de două sau mai multe persoane, asupra a două sau mai multor persoane. În şedinţa de judecată

  2%|▏         | 11.0M/481M [6:22:41<271:52:28, 481B/s]

--------------------------------------------- Result 27 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Prin sentința nominalizată instanța a reținut, că la 22 decembrie 2013, aproximativ pe la orele 20.00, XXX XXX, aflîndu­se în incinta magazinului nr.2 ce aparţine ’’Universcoop Drochia”, amplasat în or.Drochia str.Cecal a scos din buzunarul hainei un cuţit, s­a repezit spre vînzătoarea magazinului XXX XXX a.n. 19XX, ameninţînd­o cu cuţitul dat pe care l­a îndreptat înspre ea în regiunea pieptului, însă el nu şi­a dus acţiunile sale pînă la realizare, deoarece a fost îmbrîncit de către vînzătoarea magazinului, care a fugit afară chemînd în ajutor. Ameninţările lui XXX XXX ­ pătimita XXX XXX, în circumstanţele date le­a perceput ca reale. În şedinţa instanței de fond inculpatul XXX XXX nu a fost prezent, din motive necunoscute, fiind respectată citarea legală, fiind supus aducerii silite, s­a constat că ultimul a părăsit domiciliul şi a plecat într­o direcţie necunoscută. Instanţa considerînd necesar de a examina cauza penală pe învinuirea lui XXX XXX în lipsa inculpatului deoarece ultimul intenţionat s­a ascuns de la prezentarea în instanța de judecată. Examinarea cauzei fiind cu participarea avocatului inculpatului Alexandru Covdii. Apreciind în ansamblu probele administrate în şedinţa judiciară, instanța a conchis, că vinovăţia lui XXX XXX este dovedită integral, în aceia că a comis infracțiunea prevăzută de art. 155 Cod penal al RM, deoarece amenințarea a fost reală. La stabilirea categoriei și termenului pedepsei prima instanță a ținut cont de prevederile art. 75 Cod penal și circumstanțele cauzei, ajungînd la concluzia că corectarea și reeducarea lui XXX XXX este posibilă cu numirea unei pedepse cu aplicarea art. 90 Cod penal. Împotriva sentinței instanței de fond, în termen la 17.06.2015, a declarat cerere de apel avocatul Guțu Tatiana în interesele inculpatului XXX XXX, pe motivul ilegalității sentinței. În apelul declarat se solicită admiterea apelului, casarea sentinței și dispunerea rejudecării cauzei date. În argumentarea apelului a indicat următoarele: concluziile instanței privind sustragerea lui XXX de la examinarea cauzei sunt eronate, dat fiind faptul, că ultimul nu a fost citat legal la locul său de trai, din declarațiile martorului XXX XXX, mama inculpatului pe care o solicită a fi audiată în calitate de martor se va constata, că anterior nu au fost recepționate la domiciliu careva citații din instanța de judecată, iar colaboratorii de poliție i­au vizitat la domiciliu doar după primirea sentinței; XXX XXX este o persoană ce se afla la evidenţa medicului psihiatru avînd dereglări de personalitate, fapt ce şi a făcut imposibilă participarea inculpatului la examinare cauzei, reieşind din circumstanțele create ultimul pe motiv de boală s­a aflat în mănăstire, loc în care se simte bine, însă deoarece colaboratorii de poliţe nu au vizitat la domiciliu inculpatul în s. Şuri r. Drochia, informația despre locul aflării acestuia nu a fost adusă la cunoștința instanței de judecată; instanţa făcînd trimitere la prevederile procesual legale prevăzute de art. 321 al.2 CPP, a indicat posibilitatea judecării cauzei în lipsa inculpatului şi anume cînd inculpatul se ascunde de la participarea în instanţă, pentru aplicarea acestor prevederi consideră, că instanţă de judecată urma iniţial să dispună căutarea lui XXX XXX şi numai după ce avea probe incontestabile despre faptul că ultimul se ascunde, să

--------------------------------------------- Result 28 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

La data de , în jurul orei inculpatul ără a deţine permis de conducere, fiind în stare de ebrietate alcoolică, încălcînd cerinţele art. 14 lit. a) al Regulamentului Circulaţiei Rutiere: coătorului de vehicul îi este interzis să conducă vehiculul dacă a consumat băuturi alcoolice, droguri sau alte substanţe contraindicate conducerii, ce se află sub influenţa preparatelor medicamentoase care duc la reducereaţiei”, s­a urcat la volanul automobilului de model „MS” şi conducîndu­l pe centura or. S, a fost stopat de colaboratorii poliţie i în exercţiul funcţiei. Ulterior, fiind suspectat de conducerea vehiculului în stare de ebrietate alcoolică a fost verificat cu aparatul „D A” care a indicat vaporii în aer expirat în volum de 0,85 mg/l care conform art. 134/12 CP costituie starea de ebrietate ală cu grad avansat. Prțiunile sale intenționate, inculpatul XXXXXXXXX a comis conducerea mijlocului de transport de către o persoană care se află în stare de ebrietate alcoolică cu grad avansat şită de către o persoană care nu deţine permis de conducere, faptă prejudiciabilă prevăzută de art. 264/1 alin. (4) Cod Penal. În cședinței de judecată, inculpatul XXXXXXXXX a înaintat o cerere prin care a solicitat examinarea cauzei în ordinea prevederilor art. 364/1 Cod procedură penală, deoarec recşte în totalitate săvârșirea faptelor indicate în rechizitoriu şi solicită examinarea cauzei penale în privința acestora în baza probelor administrate în faza de urmărire penală. Apărătorul inculpatului XXXXXXXXX a susținut cererea înaintată de inculpat și a solicitat ca examinarea cauzei să fie petrecută în ordinea prevăzută de art. 364/1 pro ă penală. Procurorul XXXXXXXXX nu a invocat careva obiecții și a solicitat examinarea cauzei în baza probelor administrate în faza de urmărire penală, dat fiind faptul că incul recşte vina și probele administrate la dosarul penal. Avînd în vedere faă inculpatul XXXXXXXXX își recunoaşte integral vina și solicită ca judecarea cauzei să se facă în baza probelor administrate în faza de urmărire penală, iar alte probe, care ar putea fi administrate la materialele cauzei penale nu dispune, ița de judecată, asigurîndu­se că din probele administrate în cursul urmăririi penale reiese că fa inculpatului sunt stași sunt suficiente date cu privire la persoana sa, a admis demersul inculpatului şi a dispus examinarea cauzei în ordinea prevederilor art. 364/1 CPP, totodat inculpatului ­i explicate consecințele opțiunii sale. tînd la faptul că inculpatul XXXXXXXXX recunoaşte vina în comiterea infracţiunii prevăzute de art. 264/1 alin. (4) Cod Penal, vina inculpatului se demonstrează prin probele administrate în cadruăririi penale şi anume: ţinutul declaraţiilor martorului XXXXXXXXX A care, în cadrul urmăririi penale, a declarat că la 18 iulie 2016, se afla în exerciţiul funcţiunii împreună cu II al PP al S­F Regim„N”, XXXXXXXXX pe str. O, din or. S şi anume centura or. Soroca, pe traseul M­2. În jurul orei 17:10colaboratorii de poliţie pe traseu au stopat automobilul de model ­S” cu nr./în. . Şoferul autoturismului s­a dovedit a fi XXXXXXXXX, a.n. XXXXXXXXX, domiciliat în or. Soroca, str. Burebista 6. Din discuţie cu acesta, martorul XXXXXX ţit un miros puternic de alcool, din cavitatea bucală astfel conducătorului i­a fost propus să respire în aparatul „D”, pentru verificarea concentraţiei


--------------------------------------------- Result 29 ---------------------------------------------
[[1 (97%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse mai sus instanţa de fond a reţinut, că xxxxNUMExxxx, la data de 12.07.2013, aproximativ pe la orele 07.20, fiind în stare de ebrietate, deținînd permisul de conducere cu nr.095800482 din 10.03.2009 pe categoria „B”, conducea automobilul de model „Opel­Vectra” cu n/î EDBF 716, deplasîndu­se prin orașul Edineț, cercul cu sens giratoriu „Gordinești”, unde a fost stopat de către IIPR al plutonului Edineț­Briceni­Ocnița, compania Nr.2, sergentul major de poliție V.Tabuica. Bănuind că șoferul xxxxNUMExxxx a consumat alcool, acesta a fost condus la SP Edineț pentru supunerea unei examinări medicale pentru stabilirea stării de ebrietate și conform acestei examinări, xxxxNUMExxxx se află în stare de ebrietate în timpul conducerii automobilului. Pentru stabilirea gradului de alcoolemie de la el a fost colectat sînge intravenos. Conform raportului cu nr.1131 de cercetare medico­legală toxicologică s­a constatat că în sîngele lui xxxxNUMExxxx s­a depistat alcool etilic în cantitate de 1,1% 1,1g/l și concentrația vaporilor de alcool în aerul expirat este 0,40 mg/l, ce corespunde stării de ebrietate cu grad avansat. Sentinţa a fost atacată cu recurs de către avocatul Gheorghii Radeanu în interesele inculpatului xxxxNUMExxxx, care consideră sentința instanței de fond ilegală. În motivarea recursului indică, că conform art.134/12 Cod penal RM (în vigoare din 26.10.2013), prin stare de ebrietate alcoolică cu grad avansat se înțelege starea persoanei care are concentrația de alcool în sînge de la 1,0g/l și mai mult sau concentrația de alcool în aerul expirat de la 0,5 mg/l și mai mult. La xxxxNUMExxxx concentrația de alcool în aerul expirat a fost depistat în mărime de 0,4 mg/l. Astfel consideră că în cazul dat xxxxNUMExxxx urma să fie atras la răspundere administrativă conform art.233 al.(1) Cod contravențional cu încetarea procesului penal. În recurs se solicită admiterea recursului, casarea sentinţei Judecătoriei Edineţ din 20.11.2013, recalificarea acțiunilor lui xxxxNUMExxxx conform art.233 al.(1) Cod Contravențional, cu încetarea procesului administrativ în legătură cu expirarea termenului de prescripție. În şedinţa instanţei de recurs avocatul Martin Vasile, care l­a asistat pe inculpat, a susţinut recursul şi a solicitat admiterea lui în sensul declarat. Inculpatul xxxxNUMExxxx a susținut recursul declarat și a solicitat admiterea acestuia în sensul declarat de avocat. Procurorul participant Valeriu Dubăsari a solicitat respingerea recursului declarat de avocat, cu menținerea sentinței instanței de fond fără careva modificări. Verificînd argumentele invocate în recursul declarat prin prizma probelor administrate şi în raport cu materialele cauzei penale prezentate instanţei, audiind opiniile participanţilor la proces, Colegiul penal ajunge la concluzia, că recursul declarat este nefondat şi urmează a respins. Conform art.449 al.(1) pct.1) lit.a) CPP, judecînd recursul, instanţa de recurs respinge recursul, menţinînd hotărîrea atacată, dacă recursul este nefondat. Judecînd cauza penală în privinţa lui xxxxNUMExxxx, instanţa de fond a verificat complet, sub toate aspectele şi în mod obiectiv circumstanţele cauzei şi a dat probelor administrate o apreciere legală din punct de vedere al pertinenţei, concludenţei, utilităţii şi veridicităţii lor, iar toate în ansamblu din punct de vedere al coroborării lor, corect ajungînd la concluzia privind vinovăţia inculpatului în fapta incriminată şi făcînd o încadrare juridică justă a acţiunilor lui în baza învinuirii aduse prevăzute

--------------------------------------------- Result 30 ---------------------------------------------
[[1 (97%)]] --> [[[FAILED]]]

De către organul de urmărire penală Cojocari Maxim Grigore, este învinuit precum că, urmărind scopul comiterii infracțiunii de contrabandă în vederea obținerii unui profit nejustificat, rezultat din săvârșirea infracțiunii, în perioada anului 2018, fiind în înțelegere prealabilă, de comun acord şi împreună cu persoane nestabilite de organul de urmărire penală, au elaborat un plan criminal în vederea trecerii peste frontiera vamală a Republicii Moldova a mărfurilor în proporții deosebit de mari, prin nedeclarare şi tăinuire de controlul vamal pentru a fi înstrăinate terțelor persoane. Astfel, în perioada lunilor ianuarie - mai 2018, în vederea realizării intențiilor sale criminale, conform rolurilor stabilite în baza planului anterior întocmit cu persoane neidentificate de organul de urmărire penală, prin intermediul unor însoțitori de vagon al trenului de pe ruta internațională “Moscova-Chișinău” au expediat din or. Moscova, Federația Rusă pentru a fi transportate în Republica Moldova, prin nedeclarare și tăinuire de controlul vamal un laptop marca “Macbook Pro”, 13 inch, model “MPXV2LL/A” anul fabricării 2017, număr de serie: C02VMGG3HV2L; căști fără fir “Airpods” - 1 unit; două telefoane mobil model ‘‘iPhone X” cu memoria de 256 GB; un laptop marca “Macbook Pro”, 13 inch, model “MPXQ2LL/A” anul fabricării 2017; un laptop marca “Macbook Pro”, 15 inch, model “MPTT2LL/A” anul fabricării 2017, număr de serie: C02W5AYYHTD6; un laptop marca “Macbook Pro”, 15 inch, model “MPTT2LL/A” anul fabricării 2017, număr de serie: C02VQBPOHTD6; un laptop marca “Macbook Pro”, 13 inch, anul fabricării 2017, cu memoria de 256 GB; un laptop marca “Macbook Pro”, 13 inch, model “MPXQ2LL/A” anul fabricării 2017, valoarea în vamă a cărora potrivit Raportului Secției reglementări tarifare și netarifare a biroului vamal Centru constituie 173 637,40 lei, mărfuri care au fost procurate din Federația Rusă de către Cojocari Maxim Grigore și alte persoane nestabilite de organul de urmărire penală prin intermediul magazinelor on-line specializate și care au fost recepționate de către Cojocari Maxim Grigore, după ce au fost introduse prin postul vamal “Vălcineț (PVFI feroviar)” prin nedeclarare și tăinuire de controlul vamal, fiind ulterior comercializate de către cel din urmă mai multor persoane fizice, prin intermediul anunțurilor publicate pe panoul de publicitate www.999.md. În aceeași perioadă de timp, Cojocari Maxim Grigore a mai organizat introducerea pe teritoriul Republicii Moldova a unui magic mouse număr serie: CC281060KG2J51XAZ; căști fără fir “Airpods” număr serie: FWYWKC4JH8TT; căști fără fir “Airpods” număr serie: GFHW14RSH8TT; căști fără fir “Airpods” număr serie:FWYWJMULH8TT; căști fără fir “Airpods” număr serie: GFDVXAN0H8TT; unui media Player “Apple TV” număr serie: C07W2X7HJ1WF; unui media Player “Apple TV” număr serie: C07W2D49J1WF; unui quadrocopter “DJI Mavic Air” model “U11X” număr serie: 0K1DF141AD37SP; unui notebook “Macbook Pro” Space Gray 512 GB .model “MPTT2LL/A” număr serie: C02W36URHTD6; unui smartwach “Aple Watch” model “3 series 42 mm Space Gray Aluminium Black Sport BAnd (GPS) MQL12LL/A” număr serie: FHLWD3N1J5X4; unui smartwach “Aple Watch” model “3 series 42 mm Space Gray Aluminium Black Sport Band (GPS) MQL12LL/A” număr serie: FHLW9MSPJ5X4; unui calculator “iMac” model MNE92RU/A, 27 inch, număr serie: C02VT6AGJ1GG; unui smartwach “Aple Watch” model “3 series 38 mm Space Gray Al Black Sport (GPS+Cellular) MQKH2B/A” număr serie: FHVR83EJ6GT; unui smartwach “Aple Watch” model

--------------------------------------------- Result 31 ---------------------------------------------
[[1 (98%)]] --> [[0 (60%)]]

Inculpatul xxxxNUMExxxx, în perioada lunii ianuarie a anului 2014, acţionînd cu intenţie, prin înşelăciune şi abuz de încredere, sub pretextul reparaţiei automobilului, [[proprietatea]] lui xxxxNUMExxxx, ilegal a dobîndit de la ultimul bani în sumă de 200 euro, echivalent a 3800 lei, prin ce i­a cauzat părţii vătămate xxxxNUMExxxx pagubă materială în sumă totală de [[3800]] lei. Acţiunile inculpatului au fost încadrate de către organele de urmărire penală în baza art.190 al.(1) Cod penal RM. Inculpatul xxxxNUMExxxx, în şedinţa de judecată, a recunoscut integral vina, a declarat că de cele comise se căieşte sincer. Partea [[vătămată]] xxxxNUMExxxx, în şedinţa de judecată, a [[depus]] cerere scrisă, prin care [[cere]] [[încetarea]] [[procesului]] penal în privinţa inculpatului xxxxNUMExxxx, indicînd că s­a împăcat cu inculpatul, nu are pretenţii faţă de inculpat. Vinovăţia inculpatului în comiterea infracţiunii a fost stabilită în şedinţa de judecată, găsindu­şi confirmare în materialele cauzei, după cum urmează: ­ plîngerea părţii vătămate (f.d.3,6); ­ proces­verbal de audiere a părţii vătămate (f.d.15); ­ proces­[[verbal]] de confruntare din 24.07.2014 (f.d.35­36); ­ procese­[[verbale]] de audiere a martorilor, care coroborate cu celelalte probe scrise anexate la materialele dosarului sînt probe concludente, pertinente şi utile cauzei. Instanţa reţine că, fapta inculpatului există, este comisă de acesta şi întruneşte elementele constitutive ale infracţiunii prevăzute de art.190 al.(1) Cod penal RM, escrocheria, adică dobîndirea ilicită a bunurilor altei persoane prin înşelăciune sau abuz de încredere. Avînd în vedere faptul că, [[partea]] vătămată s­a împăcat cu inculpatul, infracţiunea comisă este clasificată mai puţin gravă, iar conform art.109 al.(1) Cod penal RM, împăcarea este actul de înlăturare a răspunderii penale pentru o infracţiune uşoară sau mai puţin gravă, instanţa de judecată ajunge la concluzia că, [[procesul]] [[penal]] în privinţa lui xxxxNUMExxxx urmează de încetat. În temeiul celor expuse, conform art.109 alin.(1) CP RM, art.art.275, 332, 384­385, 394, 396 CPP RM, instanţa de judecată

Inculpatul xxxxNUMExxxx, în perioada lunii ianuarie a anului 2014, acţionînd cu intenţie, prin înşelăciune şi abuz de încredere, sub pretextul reparaţiei automobilului, [[prporietatea]] lui xxxxNUMExxxx, ilegal a dobîndit de la ultimul bani în sumă de 200 euro, echivalent a 3800 lei, prin ce i­a cauzat părţii vătămate xxxxNUMExxxx pagubă materială în sumă totală de [[3080]] lei. Acţiunile inculpatului au fost încadrate de către organele de urmărire penală în baza art.190 al.(1) Cod penal RM. Inculpatul xxxxNUMExxxx, în şedinţa de judecată, a recunoscut integral vina, a declarat că de cele comise se căieşte sincer. Partea [[vătmăată]] xxxxNUMExxxx, în şedinţa de judecată, a [[dpeus]] cerere scrisă, prin care [[cree]] [[îcnetarea]] [[procesuuli]] penal în privinţa inculpatului xxxxNUMExxxx, indicînd că s­a împăcat cu inculpatul, nu are pretenţii faţă de inculpat. Vinovăţia inculpatului în comiterea infracţiunii a fost stabilită în şedinţa de judecată, găsindu­şi confirmare în materialele cauzei, după cum urmează: ­ plîngerea părţii vătămate (f.d.3,6); ­ proces­verbal de audiere a părţii vătămate (f.d.15); ­ proces­[[vrebal]] de confruntare din 24.07.2014 (f.d.35­36); ­ procese­[[verable]] de audiere a martorilor, care coroborate cu celelalte probe scrise anexate la materialele dosarului sînt probe concludente, pertinente şi utile cauzei. Instanţa reţine că, fapta inculpatului există, este comisă de acesta şi întruneşte elementele constitutive ale infracţiunii prevăzute de art.190 al.(1) Cod penal RM, escrocheria, adică dobîndirea ilicită a bunurilor altei persoane prin înşelăciune sau abuz de încredere. Avînd în vedere faptul că, [[pratea]] vătămată s­a împăcat cu inculpatul, infracţiunea comisă este clasificată mai puţin gravă, iar conform art.109 al.(1) Cod penal RM, împăcarea este actul de înlăturare a răspunderii penale pentru o infracţiune uşoară sau mai puţin gravă, instanţa de judecată ajunge la concluzia că, [[prcoesul]] [[peanl]] în privinţa lui xxxxNUMExxxx urmează de încetat. În temeiul celor expuse, conform art.109 alin.(1) CP RM, art.art.275, 332, 384­385, 394, 396 CPP RM, instanţa de judecată

--------------------------------------------- Result 32 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Prin încheierea Judecătoriei Soroca din 12.06.2014 a fost respins demersul sefului Penitenciarului nr.6 Soroca privind stabilirea termenului de pedeapsă a condamnatului xxxxNUMExxxx ca neîntemeiat. În termen încheierea instanţei a fost contestată cu recurs de către condamnatul xxxxNUMExxxx, care solicită corectarea erorilor admise de instanța de judecată, cu aplicarea prevederilor art.84 al.4 CP și nu prevederile art.85 CP RM prin care a fost condamnat. În instanţa de recurs condamnatul xxxxNUMExxxx a declarat că nu este de acord cu încheierea instanţei de judecată. Avocatul Gligor Vadim în şedinţa instanţei de recurs a susținut recursul și a solicitat admiterea lui, deoarece instanţa de fond nu a soluţionat cererea adresată de administraţia penitenciarului. În instanţa de recurs procurorul Dubăsari Valeriu a solicitat admiterea recursului din alte motive decît cele invocate de condamnat, cu casarea încheierii și dispunerea rejudecării cauzei în prima instanță în alt complet de judecată. Audiind participanţii la proces, verificînd argumentele invocate în recurs şi verificînd legalitatea şi temeinicia încheierii atacate, Colegiul penal ajunge la concluzia că recursul declarat de condamnat urmează a fi admis, cu casarea încheierii contestate, din alte motive decît cele invocate, cu remiterea cauzei la rejudecare reeşind din următoarele considerente. Conform art. 449 al.1 p.2 lit.c CPP RM judecînd recursul, instanţa adoptă una din următoarele decizii: 2) admite recursul, casînd hotărîrea, parţial sau integral, şi ia una din următoarele soluţii: c) dispune rejudecarea cauzei de către instanţa de fond dacă este necesară administrarea de probe suplimentare. Colegiul penal conchide, că la examinarea demersului şefului Penitenciarului nr.6 Soroca privind stabilirea termenului de pedeapsă a condamnatului xxxxNUMExxxx, instanţa de fond nu a respectat normele procesuale şi nu a verificat complet şi în mod obiectiv circumstanţele cauzei, de fapt nu a soluţionat fondul demersului. Din materialele prezentate pentru verificare rezultă, că administrația Penitenciarului nr.6 Soroca, unde își execută pedeapsa condamnatul xxxxNUMExxxx, la 22.04.2014 a înaintat demers în fața instanței prin care solicită verificarea timpului aflării în stare de arest inclus în termenul de pedeapsă condamnatului, conform sentinței de condamnare a Judecătoriei Soroca din 04.10.2013 lui xxxxNUMExxxx i­a fost inclus timpul aflării în stare de arest de la 04.10.2013, însă conform procesului­verbal de reținere xxxxNUMExxxx a fost reținut la 17.04.2013. Colegiul penal ţine să menţioneze în sensul dat, că conform art.88 al.3 CP RM timpul aflării persoanei sub arest preventiv pînă la judecarea cauzei se include în termenul închisorii, calculîndu­se o zi pentru o zi, iar în termenul muncii neremunerate în folosul comunităţii – calculîndu­se o zi de arest preventiv pentru 2 ore de muncă neremunerată în folosul comunităţii. Prin sentința Judecătoriei Soroca din 04.10.2013 xxxxNUMExxxx a fost condamnat în baza art.186 al.2 lit.b,c,d CP RM, art.85 CP RM cu stabilirea pedepsei definitive 3 ani 2 luni închisoare în penitenciar de tip închis, termenul de pedeapsă fiind calculat din 04.10.2013. Colegiul penal constată, că instanța de fond eronat a motivat referitor la soluționarea corectării erorii solicitate privind aplicarea art.84 al.4 CP RM şi 85 CP RM, de fapt prin demersul administrației Penitenciarului nr.6 Soroca fiind solicitată verificarea includerii timpului aflării în stare de arest al inculpatului, care nici nu a fost examinat în fond.

--------------------------------------------- Result 33 ---------------------------------------------
[[0 (100%)]] --> [[1 (54%)]]

La 09 noiembrie 2013, aproximativ la ora 1200, [[xxxxNUMExxxx]] aflîndu­se pe lotul său de teren arabil, situat la marginea satului, în aproierea traseului [[Rezina]] ­ [[Orhei]], ca urmare a unui conflict apărut între el şi consăteanul xxxxCUSTOM1xxxx Serghei, i­a aplicat ultimului trei lovituri cu pumnul în regiunea feţei, cauzîndu­i astfel părţii vătămate xxxxCUSTOM1xxxx Serghei potrivit concluziei raportului de expertiză medico­legală nr.498 D din 22.12.2014 o vătămare medie sub formă de: fractură dublă a [[madibulei]] stîngi cu deplasare. [[Pînă]] la începerea cercetării judecătorești, [[inculpatul]] xxxxNUMExxxx s­a adresat către instanță cu o cerere în scris, prin care a solicitat ca judecata să se facă în baza probelor administrate la faza de urmărire penală, menționînd că [[recunoaște]] [[necondițonat]] fapta incriminată și nu solicită administrarea de probe noi. Avocatul A.M susținut cererea depusă de către [[inculpat]]. Judecarea cauzei, în baza probelor administrate la faza urmăririi penale a fost acceptată și de către procuror. Potrivit probelor anexate la dosar, fapta [[incriminată]] inculpatului se dovedește incontestabil, din care considerente instanța a admis cererea acestuia privind judecarea cauzei în baza probelor administrate în faza de urmărire penală. [[Audiat]] pe marginea învinuirii înaintate de către organul de urmărire penală, potrivit regulilor de audiere a martorului, [[inculpatul]] xxxxNUMExxxx a declarat instanței, că la data de 09 noiembrie [[2013]] s­a înțeles cu [[tractoristul]] M I să­i are cota de teren arabil. Fiind vecini cu terenurile, urma să plece în cîmp și xxxxCUSTOM1xxxx Serghei, dar ultimul n­a fost de găsit acasă. Împreună cu fiul său cel mic a plecat la cota de teren. I­a atătat tractoristului sectorul său, continuînd să rămînă acolo. Între timp a venit și S.xxxxCUSTOM1xxxx. Anterior a avit cu el neînțelegeri, privitor la hotar. A [[măsurat]] cu [[pasul]] și i­a [[arătat]] că cu patru metri a trecut hotarul. Fiind în stare de ebrietate S.[[xxxxCUSTOM1xxxx]], care ave în mîni o [[lopată]], l­a [[înjurat]] și l­a înjosit. N­ a putut să se abțină și i­a [[aplicat]] 3 ori cu pumnul în regiunea [[feței]]. El s­a urcat în căruță să plece. [[Calul]] s­a [[speriat]] și s­a izbit, el căzînd jos. [[Peste]] [[două]] săptămîni de la polițist a aflat că S.xxxxCUSTOM1xxxx s­a adresat la poliție. Recunoaște că leziunile corporale stabilite la S.xxxxCUSTOM1xxxx i­au fost pricinuite în urma acțiunilor sale. Regretă cele întîmplate și promite că nu v­a mai comite așa fapte. Este de acord, în baza documentelor, să­i restituie lui S.xxxxCUSTOM1xxxx cheltuielile pentru tratament. Și­a cerut scuze de la partea vătămată, acesta depunînd cerere de împăcare la poliție, iar mai tîrziu și­a retras­o. De rînd cu declarațiile sale din ședința de judecată, vina inculpatului xxxxNUMExxxx în comiterea infracțiunii de care se învinuiește se mai dovedește prin materialele dosarului penal, și anume: ­depoziţiile părţii vătămate xxxxCUSTOM1xxxx Serghei, potrivit cărora, la 09.11.2013 aproximativ la ora 1200 în timp ce se afla pe terenul său arabil situat lîngă Cuizăuca raionul Rezina, a venit consăteanul său xxxxNUMExxxx pentru a­şi ara terenul arabil care se mărgineşte cu al său. În timpul discuţiei s­au referit la delimitarea terenurilor arabile, în urma la ce între ei s­a iscat o ceartă, în rezultatul căruia ambii sau numit cu cuvinte înjurioase. Ulterior, V.M

La 09 noiembrie 2013, aproximativ la ora 1200, [[xxxNxUMExxxx]] aflîndu­se pe lotul său de teren arabil, situat la marginea satului, în aproierea traseului [[Reizna]] ­ [[Orehi]], ca urmare a unui conflict apărut între el şi consăteanul xxxxCUSTOM1xxxx Serghei, i­a aplicat ultimului trei lovituri cu pumnul în regiunea feţei, cauzîndu­i astfel părţii vătămate xxxxCUSTOM1xxxx Serghei potrivit concluziei raportului de expertiză medico­legală nr.498 D din 22.12.2014 o vătămare medie sub formă de: fractură dublă a [[maidbulei]] stîngi cu deplasare. [[Pnîă]] la începerea cercetării judecătorești, [[icnulpatul]] xxxxNUMExxxx s­a adresat către instanță cu o cerere în scris, prin care a solicitat ca judecata să se facă în baza probelor administrate la faza de urmărire penală, menționînd că [[recnuoaște]] [[necodnițonat]] fapta incriminată și nu solicită administrarea de probe noi. Avocatul A.M susținut cererea depusă de către [[inculapt]]. Judecarea cauzei, în baza probelor administrate la faza urmăririi penale a fost acceptată și de către procuror. Potrivit probelor anexate la dosar, fapta [[incrmiinată]] inculpatului se dovedește incontestabil, din care considerente instanța a admis cererea acestuia privind judecarea cauzei în baza probelor administrate în faza de urmărire penală. [[Aduiat]] pe marginea învinuirii înaintate de către organul de urmărire penală, potrivit regulilor de audiere a martorului, [[inculaptul]] xxxxNUMExxxx a declarat instanței, că la data de 09 noiembrie [[2103]] s­a înțeles cu [[tractorsitul]] M I să­i are cota de teren arabil. Fiind vecini cu terenurile, urma să plece în cîmp și xxxxCUSTOM1xxxx Serghei, dar ultimul n­a fost de găsit acasă. Împreună cu fiul său cel mic a plecat la cota de teren. I­a atătat tractoristului sectorul său, continuînd să rămînă acolo. Între timp a venit și S.xxxxCUSTOM1xxxx. Anterior a avit cu el neînțelegeri, privitor la hotar. A [[măusrat]] cu [[psaul]] și i­a [[artăat]] că cu patru metri a trecut hotarul. Fiind în stare de ebrietate S.[[xxxxCUSTO1Mxxxx]], care ave în mîni o [[loptaă]], l­a [[înjruat]] și l­a înjosit. N­ a putut să se abțină și i­a [[apliact]] 3 ori cu pumnul în regiunea [[fțeei]]. El s­a urcat în căruță să plece. [[Caull]] s­a [[spreiat]] și s­a izbit, el căzînd jos. [[Petse]] [[duoă]] săptămîni de la polițist a aflat că S.xxxxCUSTOM1xxxx s­a adresat la poliție. Recunoaște că leziunile corporale stabilite la S.xxxxCUSTOM1xxxx i­au fost pricinuite în urma acțiunilor sale. Regretă cele întîmplate și promite că nu v­a mai comite așa fapte. Este de acord, în baza documentelor, să­i restituie lui S.xxxxCUSTOM1xxxx cheltuielile pentru tratament. Și­a cerut scuze de la partea vătămată, acesta depunînd cerere de împăcare la poliție, iar mai tîrziu și­a retras­o. De rînd cu declarațiile sale din ședința de judecată, vina inculpatului xxxxNUMExxxx în comiterea infracțiunii de care se învinuiește se mai dovedește prin materialele dosarului penal, și anume: ­depoziţiile părţii vătămate xxxxCUSTOM1xxxx Serghei, potrivit cărora, la 09.11.2013 aproximativ la ora 1200 în timp ce se afla pe terenul său arabil situat lîngă Cuizăuca raionul Rezina, a venit consăteanul său xxxxNUMExxxx pentru a­şi ara terenul arabil care se mărgineşte cu al său. În timpul discuţiei s­au referit la delimitarea terenurilor arabile, în urma la ce între ei s­a iscat o ceartă, în rezultatul căruia ambii sau numit cu cuvinte înjurioase. Ulterior, V.M

--------------------------------------------- Result 34 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

1. Conform sentinței Judecătoriei Bălți din 14.12.2015 xxx au fost recunoscuți vinoveți în săvîrşirea infracţiunii prevăzută de art.312 alin.(2) lit.a) Cod Penal, și le­au fost numite următoarele pedepse: ­ xxx a fost declarat vinovat de comiterea infracţiunii prevăzute de art.312 alin.(2) lit.a) Cod Penal şi în baza acestei legi i s­a aplicat pedeapsă cu închisoare pe un termen de 2 (doi) ani, fără privare de dreptul de a ocupa anumite funcții sau de a exercita o anumită activitate. Conform art.90 Cod penal a fost dispusă suspendarea condiţionată a executării pedepsei aplicate vinovatului cu închisoare pe un termen de probă de 2 (doi) ani, obligînd condamnatul să nu­şi schimbe domiciliul fără consimţămîntul organului competent. Măsura preventivă aplicată în privinţa lui xxx pînă la intrarea sentinţei în vigoare se menţine obligarea de a nu părăsi ţara. ­ xxx a fost declarată vinovată de comiterea infracţiunii prevăzute de art.312 alin.(2) lit.a) Cod penal, şi în baza acestei legi i s­a stabilit pedeapsă sub formă de închisoare pe un termen de 2 (doi) ani, fără privarea de dreptul de a ocupa anumite funcţii sau de a exercita o anumită activitate. Conform art.90 Cod penal dispune suspendarea condiţionată a executării pedepsei aplicate cu închisoare pe un termen de probă de 2 (doi) ani, obligînd condamnata să nu­şi schimbe domiciliul fără consimţămîntul organului competent. Măsura preventivă aplicată în privinţa lui xxx pînă la intrarea sentinţei în vigoare se menţine obligarea de a nu părăsi ţara. 2. Instanța de fond a reținut că xxx, avînd scopul prezentării cu bună­ştiinţă a declaraţiei mincinoase, pe parcursul efectuării urmăririi penale pe cauza penală cu nr.2012978119 pornită de către Procuratura Anticorupţie la 10.08.2012 în baza art.324 alin.(2) lit.b) şi c) Cod penal, pe faptul coruperii pasive comise de colaboratorii Secţiei ’’Nord” a Direcţiei Combaterea Crimei Organizate a Direcţiei Generale Servicii Operative din cadrul Ministerului Afacerilor de Interne, care ulterior la data de 28.09.2012 a fost conexată la cauza penală nr.2010990418, fiind recunoscut şi audiat la 14.08.2012 în calitate de martor, iar la 27.09.2012 participînd în calitate de parte vătămată la confruntări cu învinuiţii xxx, fiindu­i explicat faptul survenirii răspunderii penale conform art.312 Cod penal, în caz de prezentare cu bună­ştiinţă a declaraţiei mincinoase, fapt confirmat prin semnăturile acestuia în rubricile corespunzătoare a proceselor­ verbale ale acţiunilor procesuale nominalizate, intenţionat şi cu bună­ştiinţă a prezentat în cadrul audierilor date declaraţii mincinoase, legate de învinuirea lui xxx de săvîrşirea coruperii pasive prevăzute la art.324 alin.(2) lit.b) şi c) Cod penal, infracţiune ce s­a manifestat prin pretinderea şi primirea banilor de la el în sumă de 1000 euro pentru eliberarea mărfii şi microbuzului reţinut şi care în cazul dat conform prevederilor art.16 alin.(4) Cod penal se clasifică la categoria infracţiunilor grave. Ulterior, fiind audiat în calitate de parte vătămată în cadrul şedinţelor de judecată, pe cauza penală de învinuire a cet.xxx de săvîrșirea infracțiunii prevăzute de art.324 alin.(2) lit.b) şi c) Cod penal, petrecute în perioada de timp 16.09.2013 ­ 06.11.2014, cet.xxx a declarat că declaraţiile anterioare date în cadrul urmăririi penale în calitate de martor și ca parte vătămată în cadrul confruntărilor, precum că cet.xxx

--------------------------------------------- Result 35 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

În Judecătoria xxxxORAS_SATxxxx a parvenit plîngerea înaintată de avocatul T.Guțu declarată în interesele părților vătămate E.P și M.M împotriva ordonanței procurorului în procuratura xxxxORAS_SATxxxx A.Gordilă din 05.01.2015 și împotriva ordonanței procurorului ierarhic superior din procuratura xxxxORAS_SATxxxx V.Tureac din 31.01.2015. Prin încheierea Judecătoriei Ungheni din 02.03.2015 respectiva plîngere a fost respinsă ca neîntemeiată. Nefiind de acord cu încheierea nominalizată, avocatul T.Guțu, în termen, a atacat­o cu recurs. Recurentul solicită admiterea recursului și anularea încheierii atacate. În motivarea recursului recurentul invocă, că instanța la emiterea încheierii nu a ținut cont de obiecțiile înaintate de avocat în interesele părților vătămate în plîngerea depusă. Consideră că de către organul de urmărire penală verificarea plîngerii a fost efectuată formal cu deviere de la normele de drept. Se consideră, că concluzia formulată este contrară declarațiilor făcute de părțile vătămate referitior la aplicarea violenței, constrîngerea de a face declarații și relinerea ilegală de către colaboratorii poliției. În ședința de judecată a instanței de recurs recurenta T.Guțu și părțile vătămate E.P și M. M au solicitat admiterea recursului pe motivele invocate, anularea încheierii contestate cu remiterea materialelor pentru un control suplimentar procuraturii xxxxORAS_SATxxxx. Procurorul participant a solicitat respingerea recursului cu menținerea încheierii Judecătoriei xxxxORAS_SATxxxx din 02.03.2015 pe cazul dat fără modificări. Verificînd argumentele recursului în raport cu materialele cauzei şi cu prevederile legii, Colegiul penal consideră recursul neîntemeiat şi pasibil de a fi respins, păstrînd fără modificări încheierea Judecătoriei xxxxORAS_SATxxxx din 02.03.2015. Conform art. 274 alin.(1) CPP, ”Organul de urmărire penală sau procurorul sesizat în modul prevăzut în art.262 şi 273 dispune în termen de 30 de zile, prin ordonanţă, începerea urmăririi penale în cazul în care, din cuprinsul actului de sesizare sau al actelor de constatare, rezultă o bănuială rezonabilă că a fost săvîrşită o infracţiune şi nu există vreuna din circumstanţele care exclud urmărirea penală, informînd despre aceasta persoana care a înaintat sesizarea sau organul respectiv”. După cum denotă actele cauzei, la 03.12.2014 și respectiv la 10.12.2014 în adresa procuraturii xxxxORAS_SATxxxx au parvenit plîngerile lui E.P și M.M, prin care a solicitat atragerea la răspundere a colaboratorilor poliției A.S și A.M, pe faptul aplicării violenței fizice și psihice aplicate de aceștea în cadrul instrumentării unei cauze penale de trafic de ființe umane unde ele sunt recunoscute în calitate de părți vătămate. Conform art. 274 alin. (5) CPP, ”În cazul în care procurorul refuză pornirea urmăririi penale, el confirmă faptul prin ordonanța motivată și anunță despre aceasta, într­un termen cît mai scurt posibil, dar nu maimare de 15 zile, persoana care a înaintat sesizarea. În cazul în care consideră că lipsesc temeiurile pentru a începe urmărirea penal, procurorul, prin ordonanță, abrogă ordonanța de începere a urmăririi penale și dispune refuzul în pornirea urmăririi penale și clasarea procesului penal”. Prin ordonanța din 05.01.2015 procurorul A.Gordilă a dispus neînceperea pe caz a urmăririi penale pe motivul lipsei faptei infracționale in acțiunile colaboratorilor poliției. Prin respectiva ordonanță procesul penal a fost clasat. În conformitate cu art. 275 CPP ”Urmărirea penală nu poate fi pornită, iar dacă a fost pornită, nu poate fi efectuată, și va fi încetată în cazurile în care: ...


--------------------------------------------- Result 36 ---------------------------------------------
[[1 (52%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse instanţa de fond a reţinut că xxx, la 19 iulie 2015, în jurul orelor 22.30, deţinînd permisul de conducere cu numărul de înregistrare 988301152, eliberat la 03.06.1998, intenţionat, încălcând cerinţele pct.14 lit.a) din Regulamentul circulaţiei rutiere, care stipulează că conducătorului de vehicul îi este interzis să conducă vehiculul dacă a consumat băuturi alcoolice, droguri sau alte substanţe contraindicate conducerii conducînd în stare de ebrietate alcoolică automobilul de model „Wolkswagen T4” cu n/î xxx, în timpul deplasării prin satul xxx raionul xxx, a fost stopat de către colaboratorii secţiei poliţiei rutiere ai PP Soroca­Floreşti pentru verificarea actelor. Tot atunci, din motiv că a fost suspectat de ultimii că conducea mijlocul de transport în stare de ebrietate alcoolică, a fost supus de către colaboratorii de poliţie testării alcooscopice cu alcotestul din dotare „Drager” şi s­a constatat că concentraţia vaporilor de alcool în aerul expirat de către acesta este de 0,71 mg/L, ceea ce constituie stare de ebrietate cu grad avansat. Conform art.134/12 al.3 din Codul Penal, starea persoanei care are concentraţia de alcool în sînge de la 1,0 g/l şi mai mult sau concentraţia vaporilor de alcool în aerul expirat de la 0,5 mg/l şi mai mult, corespunde stării de ebrietate alcoolică cu grad avansat. În baza art.134 al.3 din Codul penal, prin stare de ebrietate alcoolică cu grad avansat se înţelege starea persoanei care are concentraţia de alcool în sînge de la 1,0 g/l şi mai mult sau concentraţia vaporilor de alcool în aerul expirat de la 0,5 mg/l şi mai mult. Cauza penală în privința lui xxx a fost examinată pe baza probelor administrate în faza de urmărire penală, în conformitate cu prevederile art.364/1 CPP RM. În termen sentinţa a fost contestată cu recurs de către avocatul Olșanski Alexandr în interesele inculpatului xxx, care în motivare invocă următoarele considerente: ­nu este deacord cu sentința în partea aplicării pedepsei complementare, deoarece instanţa n­a luat în consideraţie conţinutul actelor medicale prezentate de inculpat şi anexate la materialele cauzei, la inculpatul xxx s­a constatat: necroza aseptică a capului femural etapa V, fractura impresională a şoldului drept (ce se confirmă prin certificat de tomografie computerizată spiralată nr.2826 din 31.10.2015, f.d.56), în legătură cu ce, în certificatul medical nr.434 din 31.10.2015 fiind notate recomandări: limita presiune asupra articulaţiilor, a exclude plimbări lungi: a se deplasa cu automobul (f.d.55), cu boala de care suferă a fost îndreptat la Spitalul Republican, secţia de raumatologie, pentru operaţie (f.d.57), ­fiind audiat în calitate de bănuit, învinuit şi inculpat, xxx a recunoscut vina sa şi s­a căit în cele omise, fără antecedente penale, la locul de trai se caracterizează pozitiv, ­ţinînd cont de circumstanţele exepţionale ale cauzei prezente, legate de comportarea vinovatului în timpul şi după consumarea infracţiunii, de starea sănătăţii a lui şi de recomandările medicului relevate, consideră că prima instanţă în conformitate cu art.79 al.1 CP avea temei şi putea să nu aplice pedeapsa complementară obligatorie, ­solicitînd admiterea apelului, casarea sentinței instanței de fond în partea aplicării inculpatului a pedepsei complementare și pronunțarea unei hotărîri noi, fără privarea de dreptul de a


--------------------------------------------- Result 37 ---------------------------------------------
[[1 (62%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse mai sus, instanţa de fond a reţinut, că inculpatul XXXXXXXXX la data de 29.06.2015 aproximativ la orele 10.30, fiind la volanul automobilului de model „Opel Omega” cu n/î BL BD 945, deplasîndu­se pe str.Ştefan cel Mare mun.Bălţi, din direcţia autogării în direcţia regiunii „Molodovo” mun.Bălţi, în preajma blocului numărul 52 de pe str.Ştefan cel Mare din mun.Bălţi, încălcînd grosolan art.45 al.(1) al Regulamentului Circulaţiei Rutiere, care prevede că conducătorul trebuie să conducă vehiculul în conformitate cu limita de viteză stabilită, ţinînd permanent seama de următorii factori: a) starea psihofiziologică ce influenţează atenţia şi reacţia; b) dexteritatea în conducere care i­ar permite să prevadă situaţiile periculoase; c) starea tehnică a vehiculului şi particularităţile încărcăturii; d) situaţia rutieră, precum şi art.45 al.(2) al Regulamentului Circulaţiei Rutiere, potrivit căruia în cazul în care în limita vizibilităţii apar obstacole care pot fi observate de conducător, el trebuie să reducă viteza sau chiar să oprească, pentru a nu pune în pericol siguranţa traficului, a tamponat pietonul Graur Ion Ananie, a.n.04.05.1949, care traversa partea carosabilă a străzii Ştefan cel Mare din partea dreaptă la stînga după direcţia de deplasare a automobilului. Conform raportului de expertiză medico­legală nr 275 D din 16.07.2015 pietonul Graur Ion Ananie în urma accidentului rutier s­a ales cu leziuni corporale grave, sub formă de traumatism cranio­cerebral acut închis sub formă de hematom subcutanat, hematom epidural masiv occipital pe stînga în fază acută, fractură os parietal pe stînga cu trecere pe bază. În cadrul urmării penale XXXXXXXXX Anton a încheiat acord de recunoaştere a vinovăţiei, care a fost acceptat de instanţa de judecată prin încheierea judiciară din 18.01.2016 şi în şedinţa de judecată a recunoscut pe deplin vinovăţia de săvîrşirea infracţiunii încriminate şi probele înaintate de acuzare. Împotriva sentinței în termen a declarat recurs procurorul în procuratura mun.Bălți Gagiu Leonid, care în motivarea recursului a indicat, că: ­fiind audiat sub jurămînt inculpatul XXXXXXXXX vina în cele incriminate a recunoscuta pe deplin; ­în pofida faptului că inculpatul XXXXXXXXX vina sa a recunoscut­o integral, fapta inputată se dovedeşte deplin prin următoarele probe: declaraţiile învinuitului XXXXXXXXX Anton, declaraţiile părţii vătămate XXXXXXXXX, declaraţiile martorilor Oganovscaia Maria Petru, Şevciuc Elena Vasile, Revenco Nina, proces­verbal de cercetare a locului accidentului rutier din 29.06.2015, foto­tabel anexă la procesul­verbal de cercetare a locului accidentului rutier din 29.06.2015, schiţa accidentului rutier întocmită la data de 29.06.2015, certificatul accidentului rutier din 29.06.2015, proces­verbal despre examinarea şi verificarea stării tehnice a unităţii de transport, proces­verbal de experiment, raport de expertiză judiciară nr.1330 din 21.08.2015, precum şi prin alte materiale ale cauzei penale; ­considerînd că activitatea infracţională a lui XXXXXXXXX pe deplin se încadrează conform art.264 al.(3) lit.a) Cod penal RM şi ţinînd cont de faptul că nu are antecedente penale, a săvîrşit o infracţiune din imprudenţă, se căieşte sincer în cele comise, a încheiat acord de recunoaştere a vinovăţiei, s­a solicitat instanţei a recunoaşte culpabil pe XXXXXXXXX de comiterea infracţiunii prevăzute de art.264 al.(3) lit.a) Cod penal RM şi în baza aceluiaşi articol a­i stabili pedeapsă sub formă de închisoare pe un termen de 4 ani cu aplicarea

--------------------------------------------- Result 38 ---------------------------------------------
[[0 (94%)]] --> [[1 (52%)]]

[[Prin]] încheierea [[Judecătoriei]] Rîșcani, mun.Chișinău din 17.04.[[2014]] s-a dispus [[respingerea]] ca fiind neîntemeiată a plîngerii depuse de Colțov Vadim privind obligarea Procuraturii Generale a [[Republicii]] Moldova să examineze plîngerea sa din 19.11.[[2013]], în baza art.274 Cod de procedură penală privind pretinsa pronunțare cu bună-știință de către judecătorii Curții de Apel Chișinău a unei încheieri contrare Legii din 17.11.2010 în cauza civilă cu nr.2a-523/10. Pentru a emite încheierea dată, prima instanță a [[constatat]] că, la 19.11.2013, petiţionarul Colţov Vadim a depus o plîngere la Procuratura Generală a Republicii Moldova privind pronunţarea cu bună-ştiinţă de către judecătorii Curţii de Apel Chişinău a unei încheieri contrare legii, în cauza civilă nr.2a-523/10. Prin scrisoarea procurorului pentru misiuni speciale a Procuraturii Generale, Radeţchi Viorel, cu nr.36-194/13-756 din 02.12.2013, Colţov Vadim a fost informat că, nu sunt temeiuri, plîngerea fiind apreciată ca un act înaintat în conformitate cu prevederile Legii cu privire la petiţionare, motiv din care aceasta nu poate să fie examinată potrivit art.274 Cod de procedură penală or, [[examinarea]] acestei plîngeri în [[fond]], poate fi considerată ca un amestec în înfăptuirea justiţiei. Nefiind de acord, petiţionarul Colţov Vadim a depus din nou o plîngere la Procuratura Generală a Republicii Moldova, prin care a solicitat pornirea urmăririi penale în baza art.307 Cod penal în privinţa completului de judecători ai Curţii de Apel Chişinău, care au emis la 17.11.2010, о încheiere contrară legii în cauza civilă nr.2a-523/10, iar prin scrisoarea procurorului pentru misiuni speciale a Procuraturii Generale, Radeţchi Viorel, cu nr.36- 194/13-71 din 21.01.2014, Colţov Vadim a fost informat că, în plîngerea depusă nu se conţin fapte sau argumente, ce ar putea fi examinate în conformitate cu prevederile art.274 Cod de procedură penală. La 18.02.2014, Colţov Vadim a depus o plîngere prin care a solicitat recunoaşterea ca fiind ilegale refuzurile Procuraturii Generale în pornirea urmăririi penale în baza denunţului înaintat la 19.11.2013 şi examinarea acestuia în conformitate cu prevederile Legii cu privire la petiţionale, precum şi obligarea procurorului la înregistrarea acestuia în mod respectiv şi efectuarea unui control în conformitate cu prevederile art.274 Cod de procedură penală. În motivarea plîngerii, petiționarul a indicat că, potrivit hotărârii Judecătoriei Rîşcani, mun.Chişinău, în pricina civilă nr.3c/a-222/2011, intentată la 27.01.2011, acţiunea sa împotriva Comisiei pentru Etică şi Disciplină a Uniunii Avocaţilor din Republica Moldova, cu intervenienţii Uniunea Avocaţilor din Republica Moldova şi SRL „Lima” privind anularea fără efecte juridice pentru viitor a hotărîrii Comisiei privind retragerea licenţei, a fost admisă, hotărârea fiind menţinută fără modificări, prin Decizia Curţii de Apel Chişinău din 05 iunie 2013, astfel, fiind în prezența puterii lucrului judecat, s-a constatat următoarele. În baza contractului de asistenţă juridică nr.22 din 25.03.2008, procura fiind eliberată de SRL „Lima” din 03.03.2008 cu termenul de valabilitate de un an de zile şi a mandatului de avocat eliberat la 26.03.2008, pentru perioada 26 martie 2008-15 iulie 2009, el, Colțov Vadim a exercitat obligaţiunile contractuale, acordarea asistenţei juridice clientului - SRL „Lima”, inclusiv la 19 aprilie 2008. Prin scrisoarea recomandată nr.44746, a înaintat conform procedurii, o cerere de apel asupra unei hotărîri a primei instanţe, care a fost înregistrată de cancelaria Judecătoriei Ialoveni cu

[[Pirn]] încheierea [[Judecătroiei]] Rîșcani, mun.Chișinău din 17.04.[[2104]] s-a dispus [[rsepingerea]] ca fiind neîntemeiată a plîngerii depuse de Colțov Vadim privind obligarea Procuraturii Generale a [[Rpeublicii]] Moldova să examineze plîngerea sa din 19.11.[[2103]], în baza art.274 Cod de procedură penală privind pretinsa pronunțare cu bună-știință de către judecătorii Curții de Apel Chișinău a unei încheieri contrare Legii din 17.11.2010 în cauza civilă cu nr.2a-523/10. Pentru a emite încheierea dată, prima instanță a [[cnostatat]] că, la 19.11.2013, petiţionarul Colţov Vadim a depus o plîngere la Procuratura Generală a Republicii Moldova privind pronunţarea cu bună-ştiinţă de către judecătorii Curţii de Apel Chişinău a unei încheieri contrare legii, în cauza civilă nr.2a-523/10. Prin scrisoarea procurorului pentru misiuni speciale a Procuraturii Generale, Radeţchi Viorel, cu nr.36-194/13-756 din 02.12.2013, Colţov Vadim a fost informat că, nu sunt temeiuri, plîngerea fiind apreciată ca un act înaintat în conformitate cu prevederile Legii cu privire la petiţionare, motiv din care aceasta nu poate să fie examinată potrivit art.274 Cod de procedură penală or, [[exmainarea]] acestei plîngeri în [[fnod]], poate fi considerată ca un amestec în înfăptuirea justiţiei. Nefiind de acord, petiţionarul Colţov Vadim a depus din nou o plîngere la Procuratura Generală a Republicii Moldova, prin care a solicitat pornirea urmăririi penale în baza art.307 Cod penal în privinţa completului de judecători ai Curţii de Apel Chişinău, care au emis la 17.11.2010, о încheiere contrară legii în cauza civilă nr.2a-523/10, iar prin scrisoarea procurorului pentru misiuni speciale a Procuraturii Generale, Radeţchi Viorel, cu nr.36- 194/13-71 din 21.01.2014, Colţov Vadim a fost informat că, în plîngerea depusă nu se conţin fapte sau argumente, ce ar putea fi examinate în conformitate cu prevederile art.274 Cod de procedură penală. La 18.02.2014, Colţov Vadim a depus o plîngere prin care a solicitat recunoaşterea ca fiind ilegale refuzurile Procuraturii Generale în pornirea urmăririi penale în baza denunţului înaintat la 19.11.2013 şi examinarea acestuia în conformitate cu prevederile Legii cu privire la petiţionale, precum şi obligarea procurorului la înregistrarea acestuia în mod respectiv şi efectuarea unui control în conformitate cu prevederile art.274 Cod de procedură penală. În motivarea plîngerii, petiționarul a indicat că, potrivit hotărârii Judecătoriei Rîşcani, mun.Chişinău, în pricina civilă nr.3c/a-222/2011, intentată la 27.01.2011, acţiunea sa împotriva Comisiei pentru Etică şi Disciplină a Uniunii Avocaţilor din Republica Moldova, cu intervenienţii Uniunea Avocaţilor din Republica Moldova şi SRL „Lima” privind anularea fără efecte juridice pentru viitor a hotărîrii Comisiei privind retragerea licenţei, a fost admisă, hotărârea fiind menţinută fără modificări, prin Decizia Curţii de Apel Chişinău din 05 iunie 2013, astfel, fiind în prezența puterii lucrului judecat, s-a constatat următoarele. În baza contractului de asistenţă juridică nr.22 din 25.03.2008, procura fiind eliberată de SRL „Lima” din 03.03.2008 cu termenul de valabilitate de un an de zile şi a mandatului de avocat eliberat la 26.03.2008, pentru perioada 26 martie 2008-15 iulie 2009, el, Colțov Vadim a exercitat obligaţiunile contractuale, acordarea asistenţei juridice clientului - SRL „Lima”, inclusiv la 19 aprilie 2008. Prin scrisoarea recomandată nr.44746, a înaintat conform procedurii, o cerere de apel asupra unei hotărîri a primei instanţe, care a fost înregistrată de cancelaria Judecătoriei Ialoveni cu

--------------------------------------------- Result 39 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Potrivit sentinței Romanadze David Temur a fost condamnat pentru, că urmărind scopul obținerii unor beneficii ilicite, în circumstanțe nestabilite de către organul de urmărire penală, a intrat în posesia a 600 formulare de timbre de acciz falsificate și fără a deține licența corespunzătoare pentru genul anumit de activitate în domeniul băuturilor alcoolice tari (vodcă), le­a aplicat pe 600 sticle cu volumul de 0,5 litri de băutură alcoolică tare ”Black Cristal”, pe care la 17.05.2014, aproximativ la ora 14:00, le transporta pe traseul Brest­Chișinău ­Odessa în automobilul propriu de model ”Mitsubischi Pajero”, cu numărul de înmatriculare BL DS 451, moment în care, angajații Ministerului Afacerilor Interne, l­au stopat pe teritoriul administrativ al satului Corlăteni, Rîșcani, respectivele acțiuni fiindu­i încadrate la art. 361 alin. (1) Cod penal cu calificativele „confecţionarea, deţinerea, vânzarea sau folosirea documentelor oficiale false, care acordă drepturi sau eliberează de obligaţii, confecţionarea sau vânzarea imprimatelor, ştampilelor sau a sigiliilor false ale unor întreprinderi, instituţii, organizaţii, indiferent de tipul de proprietate şi forma juridică de organizare”. Legalitatea și temeinicia sentinței de condamnare a fost contestată de către: ­avocatul Victor Dolghi în interesele inculpatului Romanadze David, care necontestând legalitatea încadrării juridice a faptei penale, solicită casarea sentinței în latura stabilirii pedepsei penale, cu adoptarea în această parte a unei soluții noi privind atenuarea pedepsei penale, prin stabilirea celei cu amendă, pe care inculpatul este disponibil să o achite. În motivarea cerințelor formulate invocându­se un șir de circumstanțe atenuante a cauzei penale, cum ar fi: vârsta tânără, recunoașterea vinovăției și căința sinceră, prezența la întreținere a doi copii minori, precum și intenția a se încadra în câmpul muncii, inclusiv după hotarele RM, pedeapsa lui aplicată creându­i incomodități în legătură cu aceasta. ­procurorul Igor Gherasim ce a reprezentat învinuirea în instanță de fond, care necontestând legalitatea încadrării juridice a acțiunilor infracționale, solicită casarea acestei în latura stabilirii pedepsei penale, cu pronunțarea unei soluții noi privind atenuarea pedepsei penale, fiindu­i stabilită cea cu amendă în mărime de 225 u. c., ce constituie 4500 lei, considerând, că la numirea ei instanța nu a ținut cont de prevederile art.75 Cod penal, fapt prin ce a neglijat recomandările expuse în pct.9 al Hotărârea Plenului CSJ nr. 8 din 11.11.2013 ”Cu privire la unele chestiuni ce vizează individualizarea pedepsei penale”., eronat fiind stabilită prezența circumstanței agravante prevăzute la art.77 Cod penal și anume faptul, că inculpatul anterior a comis o infracțiune analogică, mai ales că achitarea amenzii stabilite prin sentința Judecătoriei Bălți din 20.11.2013 și stingerea antecedentelor penale au fost adeverite prin certificatul prezentat de către inculpatul Romanadze David în cadrul cercetărilor judecătorești. Totodată, ne cătând la faptul că au stabilite circumstanțe atenuante și nu existau în fapt circumstanțe agravante, instanța a aplicat pedeapsa maximă prevăzută de art.361 alin.(1) Cod penal, calculată prin prisma art.364/1 Cod pr. penală, astfel că concluzia instanței cu privire la aplicarea unei pedepse mai aspre urma a fi motivată. Or, ne cătând la faptul, că acuzatorul de stat, apărătorul precum și inculpatul au solicitat aplicarea pedepsei sub formă de amendă, instanța, fără a­și motiva decizia și fără a argumenta faptul, de ce nu este echitabilă


--------------------------------------------- Result 40 ---------------------------------------------
[[1 (83%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut, că inculpatul xxxxNUMExxxx la data de 08.02.2014, în jurul orei 22.00, aflîndu­se în incinta magazinului „xxxxNUMExxxx” din sat. Chirileni r­ul xxxxORAS_SATxxxx, văzînd că cumnatul său xxxxNUMExxxx are un conflict cu cet. xxxxNUMExxxx, s­a implicat şi i­a aplicat ultimului cîteva lovituri cu pumnul în faţă, dupa care cet. xxxxNUMExxxx a fugit acasă. Peste cîteva minute după conflictul dat cet. xxxxNUMExxxx, s­a întors înapoi avînd cu sine o bărdiţă şi a încercat să discute cu cet. xxxxNUMExxxx şi xxxxNUMExxxx, însă ultimul i­a luat bardiţa din mînă și i­a mai aplicat cu ea cîteva lovituri peste corp şi peste piciorul stîng, provocîndu­i vătămăti corporale grave, sub formă de fractura deschisă a osului tibial a gambei stîngi, sector excoriat în regiunea zigomatică, plagă contuză în regiunea sprîncenoasă a ochiului stîng, edeme traumatice a ţesuturilor moi a pleoapelor ochiului stîng cu revărsat sangvin în scleră, excoreaţii în regiunea articulaţiei cotului stîng şi antebraţului stîng, plagă scalpată în regiunea nazală. Instanţa de fond a pronunţat sentinţa sus indicată. Împotriva sentinţei a declarat apel partea vătămată xxxxNUMExxxx, care solicită casarea sentinţei în latura civilă, cu dispunerea încasării de la inculpat a prejudiciului moral în sumă de 100000 lei. În motivarea apelului invocă, că prin încasarea prejudiciului moral în sumă de 2000 lei s­au ignorat prevederile art. 1423 Cod civil, ne fiind luate în calcul suferinţele la care a fost supus, şi anume că prin lovitura de topor i­a fost pricinuită fractura deschisă a piciorului, fapt care l­a imobilizat pe o perioadă de lungă durată şi din aceste considerente a fost privat de posibilitatea de a­şi întreţine familia, el lucrînd ca muncitor sezonier după hotare, avînd la întreţinere doi copii mici, că a suportat timp îndelungat dureri fizice. Consideră, că pedeapsa penală stabilită inculpatului nu echivalează cu o compensare morală, fiind doar o măsură de constrîngere pentru infracţiunea comisă, iar inculpatul nici nu a conştientizat că a fost supus unei pedepse penale. Partea vătămată xxxxNUMExxxx, fiind citată în mod legal, în şedinţa instanţei de apel nu s­a prezentat. În şedinţa instanţei de apel procurorul, inculpatul şi avocatul acestuia au solicitat respingerea apelului părţii vătămate ca nefondat, cu menținerea sentinţei instanței de fond. Verificând argumentele apelantului în raport cu materialele cauzei, ascultînd opiniile participanţilor la proces, Colegiul penal vine la concluzia, că apelul declarat este nefondat şi urmează a fi respins. În concluzia respectivă instanța de apel statuază pe prevederile art. 414, 415 al. (1) pct. 1 lit. c), 24 CPP. Așa, potrivit art. 415 al. (1) pct. 1 lit. c) CPP, instanța de apel, judecînd cauza în ordine de apel, respinge apelul dacă acesta este nefondat. Potrivit art. 414 al. (1) CPP, instanța de apel, judecînd apelul, verifică legalitatea și temeinicia hotărîrii atacate în baza probelor examinate de prima instanță, conform materialelelor din cauza penală, și în baza oricăror probe noi prezentate instanței de apel. Analizînd probele administrate de instanța de fond, materialele cauzei, Colegiul penal reține, că la examinarea cauzei respective s­a dat eficiență prevederilor art. 93­101, 26­27 Cod de procedură penală, instanța a cercetat cauza

--------------------------------------------- Result 41 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Inculpatul Fediuc Vladimir la data de 22 ianuarie 2013, aproximativ la ora 21.00, aflându­se la domiciliul său din s. Tăura­Veche, r­nul Sângerei și fiind în stare de ebrietate alcoolică, acționând intenționat, cu scopul sistării activității de serviciu legate de examinarea adresării cet. Fediuc Eugen nr. 322 din 22.01.2013 despre acțiunile de amenințare cu arma, verbal l­a amenințat cu moartea pe șeful de post, ofițerul operativ superior de sector al postului de poliție Tăura­Veche al CPR Sângerei Ceban Gheorghe, care este persoană cu funcție de răspundere, deoarece se afla în exercițiul funcției și era investită prin lege cu obligațiuni de menținere a ordinii publice și prevenire a infracțiunilor, fapt care i­a provocat temere reală și n­a intervenit în continuare. Tot el, continuând acțiunile infracționale, la 23 ianuarie 2013, aproximativ la ora 09.00, la domiciliul său din s. Tăura­Veche, r­nul Sângerei, fiind în stare de ebrietate alcoolică, intenționat, cu scopul sistării activității de cercetare a cazului de amenințare cu arma înregistrat cu nr. 322 din 22.01.2013, cu un cuțit de bucătărie ce­l avea în mână, l­a atacat pe polițistul­ șofer al serviciului de patrulă și santinelă al CPR Sângerei Podgurschi Nicolae, care era persoană cu funcție de răspundere, deoarece se afla în exercițiul funcției și era investit cu obligațiuni de menținere a ordinii publice și prevenire a infracțiunilor. Polițistul Podgurschi N. a respins atacul și cu ajutorul colaboratorilor de poliție Petrov Marcel și Ceban Gheorghe, Fediuc Vladimir a fost deposedat de cuțit și imobilizat. Procurorul Vitalie Crigan, procuror în Procuratura r­lui Sângerei a susţinut în instanţă acuzarea de stat, pledând pentru recunoaşterea inculpatului Fediuc Vladimir vinovat în conformitate cu art. 349 alin. 1 CP al RM şi în baza acestei Legi și a prevederilor art. 364/1 CPP al RM, luînd în considerație circumstanțele atenuante și agravante, principiile individualizării pedepsei a­i stabili o pedeapsă sub formă de muncă neremunerată în folosul comunității în mărime de 120 ore. Corpul delict­ cuțitul­ a fi nimicit la intrarea sentinței în vigoare. Avocatul Vasile Țâbârnă, cabinet individual de avocat, cu sediul în or. Sângerei, apărând interesele inculpatului în baza mandatului din 23.10.2013, Seria MA nr. 0379781, a pledat în dezbateri judiciare pentru aplicarea unei pedepse echitabile, fiind de acord cu cea propusă de acuzatorul de stat, luînd în consideraţie căinţa sinceră și recunoașterea vinovăției, precum și toate circumstanțele atenuante. În cadrul şedinţei judiciare inculpatul Fediuc Vladimir, fiind interogat sub jurământ, a recunoscut vina integral, explicând că în perioada sărbătorilor de iarnă 2013, exact data nu mai ține minte, a fost la cimitir la mormântul fiicei sale, acolo a consumat alcool și revenind acasă în s. Tăura­Nouă, r­nul Sângerei soția l­a certat, astfel iscându­se scandal între ei. Ține minte că a coborât în beci unde a continuat să bea, evenimentele ulterioare însă nu și le mai aduce aminte, deoarece era foarte beat. A mai declarat, că recunoaște vina integral, se căiește de cele comise și solicită să nu­i fie aplicată sancțiunea amenzii, deoarece situația sa financiară nu­i va permite s­o achite. În schimb, este de acord să muncească în folosul comunității. Părțile vătămate Ceban Gheorghe și Podgurschi Nicolae au solicitat

--------------------------------------------- Result 42 ---------------------------------------------
[[1 (100%)]] --> [[[FAILED]]]

Prin sentinţa nominalizată inculpatul xxxxNUMExxxx a fost recunoscut culpabil și condamnat pentru că în seara zilei de 28.06.2010 pe la orele 21:30, aflîndu­se pe una din străzile sat. xxxxORAS_SATxxxx, Sîngerei, în apropierea gospodăriei cet. Chișcă Natalia, din motivul relațiilor receproc ostile, în timpil cerții cu xxxxNUMExxxx, i­a aplicata acestui cîteva lovituri cu pumnii în regiunea feții, apoi cu un baston din lemn i­a aplicat mai multe lovituri peste corp, mîini și cap, cauzîndu­i vătămări corporale medii, cu dereglare de lungă durată a sănătății, acțiunile lui fiind încadrate la art. 152 alin. (1) Cod penal. Legalitatea sentinţei în termenul şi modul prevăzut de art. 402 Cod pr. penală a fost atacată cu apel de către partea vătămată xxxxNUMExxxx, care necontestînd legalitatea încadrării juridice a acțiunilor infractorice a inculpatului xxxxNUMExxxx la art. 152 alin. (1) Cod penal precum și măsura de pedeapsa lui numită, își expune dezacordul în ce privește admiterea parțială a acțiunii civile, solicitînd casarea ei în această parte, cu rejudecarea cauzei și admiterea integrală a cerințelor formulate de recuperare a daunei materiale în sumă de 1396, 83 lei pentru tratament, 382 lei cheltuieli pentru transport, 2000 lei pentru servivciul apărătorului și 5000 lei cu statut de despăgubiri morale. În fața instanței de apel apelantul a pledat pentru admiterea cererii de apel pe motivele invocate în ea, dispunîndu­se încasarea de la inculpat în beneficiul său a sumei de 2000 lei cheltuieli pentru acordarea asistenței juridice și 5000 lei cu titlu de despăgubiri morale, în rest păstrîndu­se fără modificări soluția primei instanțe. Reprezentantul acuzării a pledat pentru admiterea cerințelor formulate de apelant, pe motivele invocate de el. Inculpatul xxxxNUMExxxx și avocatul ce­i asigură apărarea garantată de stat au pledat pentru respingerea apelului ca fiind nefondat, păstrînd fără modificări sentința contestată. Verificînd legalitatea verdictului contestat și temeinicia argumentelor invocate de apelant în raport cu materialele cauzei penale, ascultînd pledoriile participanţilor procesului penal, Colegiul conchide posibilitatea admiterii în tot a cerințelor formulate de apelantul xxxxNUMExxxx în cererea de apel, dispunînd casarea sentinței în latura civilă, cu adoptarea în această parte a unei soluții noi de încasare de la Gobjilă Mihail în beneficiul lui a despăgubirilor morale în suma de 5000 lei și 2000 lei cheltuieli pentru asistența juridică, în rest păstrînd fără modificări sentința judiciară. Din start Colegiul reține, că apelul părții vătămate xxxxNUMExxxx urmează a fi considerat ca fiind depus în termenul legal, dat faptului că în materialele cauzei penale lipsesc date ce ar confirma informarea lui despre sentința redactată. Potrivit recipisei anexată pe coperta cauzei, inculpatului i­a fost înmînată copia sentinței redactate la data de 17.05.2011, dată de la care urmează a se calcula curgerea termenilor de declarare a apelului. Ținînd cont de faptul că alte date în cauză lipsesc, Colegiul consideră necesar de a considera apelul declarat de xxxxNUMExxxx ca fiind depus în termen. În motivarea concluziei adoptate, Colegiului în limita împuternicirilor procesuale de care dispune potrivit art. 414 Cod pr. penală, reține examinarea amplă, multelaterală și obiectivă a cauzei penale în ce privește constatarea faptei criminale, cu cercetarea profundă a probelor administrate de către organul de urmărire penală prin prisma dispozițiilor

--------------------------------------------- Result 43 ---------------------------------------------
[[1 (70%)]] --> [[0 (54%)]]

Prin sentinţa Judecătoriei C. din 29 ianuarie 2013 T. V. P. a [[fost]] recunoscut [[vinovat]] de săvîrşirea infracţiunilor prevăzute de 1 art.art. 188 alin.(2) lit.b), fşi 192 alin.(2) lit.a) Cod penal şi i s­a stabilit pedeapsa: ­în baza art.188 alin.(2) lit.b), f) Cod penal­ 8 ani închisoare; 1 ­în baza art.192 alin.(2) lit.a) Cod penal ­4 ani închisoare; ­în baza art.84 alin.(1) Cod penal, prin cumul total al pedepselor aplicate, s­a stabilit lui T. V. pedeapsa definitivă de 12 ani [[închisoare]] cu executarea pedepsei în penitenciar de tip închis. xxxxNUMExxxx a fost recunoscut vinovat de săvîrşirea infracţiunilor prevăzute de art.art.42 alin.(5), 188 alin.(2) lit.b), f) şi 1 art.art.42 alin.(5), 19 alin.(2) lit.a) Cod penal şi i s­a stabilit pedeapsa: 1 în baza art.art.42 alin.(5), 188 alin.(2) lit.b), f) Cod penal ­ 6 ani închisoare, ­în baza art.art.42 alin.(5), 192 alin.(2) lit.a) Cod pena­2 ani închisoare, în baza art.84 alin. (1) Cod penal, prin cumul paţial al pedepselor aplicate, s­a stabilit lui xxxxNUMExxxx pedeapsa definitivă de 7 an închisoare cu executarea pedepsei în penitenciar de tip închis; ­în baza art.85 alin. (1) Cod penal, la pedeapsa stabilită prin prezenta sentinţă, s­a adăugat parţial pedeapsa neexecutată potrivit sentiţei din 02 martie 2006, stabilind lui xxxxNUMExxxx pedeapsa definitivă de 8 ani închisoare cu executarea pedepsei în penitenciar de tip închis Acţiunea civilă depusă de xxxxNUMExxxx a fost admisă parţial. S­a încasat de la T. V. în beneficiul luxxxxNUMExxxx , 11 lei cu titlu de prejudiciul material cauzat prin infracţiune în foră de mijloacele băneşti sustrase. S­a încasat în mod solidar de la T. V. şi xxxxNUMExxxx. în [[beneficiul]] luxxxxNUMExxxx 30000 lei cu titlu de prejudiciul moral cauzat prin infraţiune. Acţiunea civilă depusă de xxxxNUMExxxxon cu privire la [[încasarea]] a 5000 lei pentru tratament, [[12000]] lei cheltuieli pentru repararea automobilului a fos admisă în principiu, urmînd ca asupra cuantumului despăgubirilor să se pronunţe instanţa în ordinea procedurii civil Pentru a se pronunţa, instanţa de fond a constatat că: T. V. P. în complicitate cu xxxxNUMExxxx, ce s­a exprimat prin faptul că xxxxNUMExxxx. la indicaţia lui T.V., pe data de 30 august 2012, aproximati la ora 17.00, prin înşelăciune 1­a chemat pe taxistul xxxxNUMExxxx , care a sosit la chemare la casa de locuit, amplasă pe str.C. 85, s.C., ce aparţine lui xxxxNUMExxxx., unde cu scopul sustragerii bunurilor altei persoane, T. V. s­ a ăpustit asupra luxxxxNUMExxxx din spate, i­a legat mîinile şi picioarele cu scotch şi o frînghie, în cap i­a pus un pachet de polietileă, l­a doborât la pământ, cerînd transmiterea banilor, a început să­1 lovească cu mîinile şi picioarele pe diferite părţi ale corpului, aplicînd violeţa periculoasă pentru viaţa şi sănătatea părţii vătămate, cauzîndu­i leziuni corporale uşoare sub formă de trauma crani­cerebrală acută, contuzie, echimoze în regiunea parieto­occipitala, pe cutia toracică din stânga, escoriaţii pe ambele picioare, antebţul drept, după ce au sustras din buzunarul pantalonilor lui xxxxNUMExxxxon 200 lei, cît şi banii din automobilul de mode M , n/î , care era parcat în faţa casei de locuit sus­indicate în sumă de 600 euro, 100 dolari SUA şi 4000 lei, iar total au

Prin sentinţa Judecătoriei C. din 29 ianuarie 2013 T. V. P. a [[fsot]] recunoscut [[vinoavt]] de săvîrşirea infracţiunilor prevăzute de 1 art.art. 188 alin.(2) lit.b), fşi 192 alin.(2) lit.a) Cod penal şi i s­a stabilit pedeapsa: ­în baza art.188 alin.(2) lit.b), f) Cod penal­ 8 ani închisoare; 1 ­în baza art.192 alin.(2) lit.a) Cod penal ­4 ani închisoare; ­în baza art.84 alin.(1) Cod penal, prin cumul total al pedepselor aplicate, s­a stabilit lui T. V. pedeapsa definitivă de 12 ani [[închisaore]] cu executarea pedepsei în penitenciar de tip închis. xxxxNUMExxxx a fost recunoscut vinovat de săvîrşirea infracţiunilor prevăzute de art.art.42 alin.(5), 188 alin.(2) lit.b), f) şi 1 art.art.42 alin.(5), 19 alin.(2) lit.a) Cod penal şi i s­a stabilit pedeapsa: 1 în baza art.art.42 alin.(5), 188 alin.(2) lit.b), f) Cod penal ­ 6 ani închisoare, ­în baza art.art.42 alin.(5), 192 alin.(2) lit.a) Cod pena­2 ani închisoare, în baza art.84 alin. (1) Cod penal, prin cumul paţial al pedepselor aplicate, s­a stabilit lui xxxxNUMExxxx pedeapsa definitivă de 7 an închisoare cu executarea pedepsei în penitenciar de tip închis; ­în baza art.85 alin. (1) Cod penal, la pedeapsa stabilită prin prezenta sentinţă, s­a adăugat parţial pedeapsa neexecutată potrivit sentiţei din 02 martie 2006, stabilind lui xxxxNUMExxxx pedeapsa definitivă de 8 ani închisoare cu executarea pedepsei în penitenciar de tip închis Acţiunea civilă depusă de xxxxNUMExxxx a fost admisă parţial. S­a încasat de la T. V. în beneficiul luxxxxNUMExxxx , 11 lei cu titlu de prejudiciul material cauzat prin infracţiune în foră de mijloacele băneşti sustrase. S­a încasat în mod solidar de la T. V. şi xxxxNUMExxxx. în [[benefciiul]] luxxxxNUMExxxx 30000 lei cu titlu de prejudiciul moral cauzat prin infraţiune. Acţiunea civilă depusă de xxxxNUMExxxxon cu privire la [[încasraea]] a 5000 lei pentru tratament, [[10200]] lei cheltuieli pentru repararea automobilului a fos admisă în principiu, urmînd ca asupra cuantumului despăgubirilor să se pronunţe instanţa în ordinea procedurii civil Pentru a se pronunţa, instanţa de fond a constatat că: T. V. P. în complicitate cu xxxxNUMExxxx, ce s­a exprimat prin faptul că xxxxNUMExxxx. la indicaţia lui T.V., pe data de 30 august 2012, aproximati la ora 17.00, prin înşelăciune 1­a chemat pe taxistul xxxxNUMExxxx , care a sosit la chemare la casa de locuit, amplasă pe str.C. 85, s.C., ce aparţine lui xxxxNUMExxxx., unde cu scopul sustragerii bunurilor altei persoane, T. V. s­ a ăpustit asupra luxxxxNUMExxxx din spate, i­a legat mîinile şi picioarele cu scotch şi o frînghie, în cap i­a pus un pachet de polietileă, l­a doborât la pământ, cerînd transmiterea banilor, a început să­1 lovească cu mîinile şi picioarele pe diferite părţi ale corpului, aplicînd violeţa periculoasă pentru viaţa şi sănătatea părţii vătămate, cauzîndu­i leziuni corporale uşoare sub formă de trauma crani­cerebrală acută, contuzie, echimoze în regiunea parieto­occipitala, pe cutia toracică din stânga, escoriaţii pe ambele picioare, antebţul drept, după ce au sustras din buzunarul pantalonilor lui xxxxNUMExxxxon 200 lei, cît şi banii din automobilul de mode M , n/î , care era parcat în faţa casei de locuit sus­indicate în sumă de 600 euro, 100 dolari SUA şi 4000 lei, iar total au

--------------------------------------------- Result 44 ---------------------------------------------
[[1 (98%)]] --> [[[FAILED]]]

Prin sentinţa pronunţată instanţa de fond a reţinut, că inculpata PL la 13.01.2005, intenționat, avînd drept scop privatizarea unui imobil, în cadrul dosarului nr.124 despre privatizarea fondului locativ, deschis la cererea cet.L P și L P, pentru privatizarea apartamentului nr.14­a de pe strada , orașul , i­a prezentat cet. V, specialist­principal în problemele privatizării și postrivatizării a Secției economice a Consiliului raional Soroca, secretar al Comisiei privind privatizarea fondului de locuințe, în original, blanchetele „лицевой счет” și “поквартирная карточка” neîndeplinite, eliberate și confirmate prin ștampila Comitetului Sindical al SU­61, filiala SA “”, care de fapt nu era împuternicit cu eliberarea acestora, determinînd­o pe cet.R V, să le completeze cu date false, indicînd în „лицевой счет” faptul, că cet.L P deține apartamentul nr.96 de pe strada , orașul în baza orderului nr.15 din 24.10.2002, cu toate că ultima a prezentat orderul nr.10 din 22.01.2001, potrivit căruia i­a fost repartizată odaia nr.14­a din căminul de pe strada , orașul , totodată înscriind la solicitarea cet.L P în blanchetele „лицевой счет” și “поквартирная карточка”, că cet.L P și L P locuiesc în apartamentul nr. de pe strada , orașul , pe cînd în buletinele de identitate a ambelor persoane domiciliul era indicată strada , orașul . Tot ea, în luna februarie 2005, intenționat, în cadrul dosarului nr.124 despre privatizarea fondului locativ, deschis la cererea cet.L P, pentru privatizarea apartamentului nr.a de pe strada orașul , a determinat­o pe cet.S R, tehnologul Oficiului Cadastral Teritorial Soroca și cet.D M, șef al Secției de Inventariere Tehnică la Oficiul Cadastral Teritorial Soroca, să îndeplinească certificatul­ caracterizare pentru privatizarea locuințelor din 10.02.2005, întocmit de către tehnologul S R și semnat de către D M, în calitate de manager al Oficiului Cadastral Teritorial Soroca, în care statutul de încăpere nelocuibilă a odăii nr.14­a din căminul de pe strada , orașul a fost schimbat în locuibil, neținîndu­se cont de faptul, că la 08.02.2005 nu exista nici un document oficial, eliberat de către Primăria orașului , care ar cataloga încăperea dată în una locuibilă, totodată acordînd ilegal încăperii date statut de apartament sub nr, pe care l­a prezentat la Comisia pentru privatizarea fondului de locuințe, în rezultatul cărui fapt, prin Hotărîrea nr.1 din 14.02.2005 a Comisiei privind privatizarea fondului de locuințe, cet.L P și cet.P L le­a fost permisă privatizarea apartamentului nr., amplasat în căminul de pe strada , orașul . Sentinţa adoptată de instanţa de fond a fost atacată cu apel de către inculpata L.P, motivul invocat fiind ilegalitatea sentinței. Apelanta consideră, că instanța de fond a emis sentința în baza unui act de învinuire din care nu este clar care acțiuni concrete comise de ea i se pun în învinuire, astfel fiind lipsită de posibilitatea de a se apăra. În apel se indică faptul, că procesul penal în privința inculpatei nu putea fi încetat în legătură cu intervenția termenului de prescripție în condițiile inexistenței în acțiunile puse în învinuire a componenței de infracțiune. Solicită admiterea apelului, casarea sentinţei judecătoriei Soroca din 02.06.2015 cu pronunţarea unei noi hotărâri prin care L.P să fie achitată. În şedinţa instanţei de apel inculpata L.P

--------------------------------------------- Result 45 ---------------------------------------------
[[1 (96%)]] --> [[0 (55%)]]

1. Prin sentința Judecătoriei Ungheni din 26 decembrie 2016, Savciuc Alexandru, a fost [[recunoscut]] [[vinovat]] în comiterea infracțiunilor prevăzute de art.48, 145 alin.(2) lit.i), j) şi art.287 alin.(3) Cod penal al RM, fiindu-i stabilită pedeapsa: - în baza art.145 alin. (2) lit. i), j) Cod penal – 16 ani închisoare; - în baza art. 287 alin. (3) Cod penal – 4 ani închisoare. În conformitate cu art.84 Cod penal, pentru concurs de infracţiuni, prin cumul parţial al pedepselor aplicate, i-a fost stabilită pedeapsa definitivă – 17 ani închisoare, cu executarea în penitenciar de tip închis. Concomitent a fost respinsă cererea acuzatorului de stat de a încasa din contul inculpatului cheltuielile în legătură cu extrădarea acestuia, în sumă de 20265,46 lei și 46 bani. 2. Pentru a pronunţa sentinţa, prima [[instanță]] a [[constatat]] că, Savciuc Alexandru, la data de 29.06.2015, aproximativ la orele 00.15 min., din motive huliganice, încălcând grosolan ordinea publică, în participaţie simplă cu Grecu D. şi Daraban I., ultimul având motiv de răzbunare, după un plan bine chibzuit cu repartizarea rolurilor, având toţi trei o înţelegere prealabilă de a-i cauza vătămări corporale lui Şişcanu Ruslan, iar ulterior lui Savciuc Alexandru şi [[Daraban]] I., apărându-le scopul [[lipsirii]] ilegale de viaţă a unei alte persoane, au intrat în ograda lui Nemţanu V. din *****, ***** şi în timp ce acolo se afla Şişcanu Ruslan care dormea, [[Savciuc]] Alexandru cu o ştachetă, împreună şi Daraban I. cu o coadă de hârleţ i-au aplicat lui Şişcanu Ruslan multiple lovituri peste toată suprafaţa corpului, iar Grecu D. i-a aplicat ultimului câteva lovituri cu picioarele în regiunea abdomenului. Tot el, Savciuc Alexandru, în aceleaşi circumstanţe sus menţionate şi în baza aceloraşi intenţii huliganice, conform raportului de [[expertiză]] medico-legală nr.105 din 06.07.2015 i-a cauzat lui Şişcanu [[Ruslan]] [[traumatism]] cranio-cerebral acut închis, hemoragii în ţesuturile moi ale capului în regiunea tempora-occipitală pe dreapta; hemoragie subdurală lichidă; hemoragie subarahnoidală difuză a ambelor emisfere a creierului covescital şi bazai la emisfera dreaptă şi a cerebelului; fractura ambelor oase zigomatice, oaselor nazale multe aşchiate; fractura mandibulei pe dreapta în protecţia dinţilor 6,7 cu deplasarea fragentelor; fractura coastelor bilateral fără lezarea pleurei parietale; multiple echimoze difuze la faţă şi a toracelui; excoriaţii la ambele mâini suprafaţa dorsală; multiple excoriaţii la faţă şi la torace, cauzându-i leziuni corporale grave în urma căruia Şişcanu Ruslan a decedat. Cauza decesului este traumatismul cranio-cerebral închis cu fractura oaselor faciale-zigomatice şi nazale, contuzia cerebrală, plaga contuză stelată masivă a ţesuturilor moi ale capului în regiunea occipitală, hemoragia subdurală şi subarahnoidală. 3. Sentința pronunțată integral la 26 decembrie 2016, a fost atacată cu apeluri de către: - procurorul în Procuratura Ungheni, Steclari Ion, la 29 decembrie 2016, prin care a solicitat casarea sentinţei, rejudecarea cauzei şi pronunţarea unei noi hotărâri, potrivit modului stabilit, pentru prima instanţă, prin care: Savciuc Alexandru să fie recunoscut culpabil în comiterea infracţiunii prevăzute de art. 48, 145 alin. (2) lit. i), j) și art. 287 alin.(3) Cod penal, și prin prisma art. 84 Cod penal, să-i fie stabilită pedeapsa sub formă de închisoare pe un termen de 17 ani cu executarea pedepsei în

1. Prin sentința Judecătoriei Ungheni din 26 decembrie 2016, Savciuc Alexandru, a fost [[recuonscut]] [[vionvat]] în comiterea infracțiunilor prevăzute de art.48, 145 alin.(2) lit.i), j) şi art.287 alin.(3) Cod penal al RM, fiindu-i stabilită pedeapsa: - în baza art.145 alin. (2) lit. i), j) Cod penal – 16 ani închisoare; - în baza art. 287 alin. (3) Cod penal – 4 ani închisoare. În conformitate cu art.84 Cod penal, pentru concurs de infracţiuni, prin cumul parţial al pedepselor aplicate, i-a fost stabilită pedeapsa definitivă – 17 ani închisoare, cu executarea în penitenciar de tip închis. Concomitent a fost respinsă cererea acuzatorului de stat de a încasa din contul inculpatului cheltuielile în legătură cu extrădarea acestuia, în sumă de 20265,46 lei și 46 bani. 2. Pentru a pronunţa sentinţa, prima [[intsanță]] a [[constaatt]] că, Savciuc Alexandru, la data de 29.06.2015, aproximativ la orele 00.15 min., din motive huliganice, încălcând grosolan ordinea publică, în participaţie simplă cu Grecu D. şi Daraban I., ultimul având motiv de răzbunare, după un plan bine chibzuit cu repartizarea rolurilor, având toţi trei o înţelegere prealabilă de a-i cauza vătămări corporale lui Şişcanu Ruslan, iar ulterior lui Savciuc Alexandru şi [[Draaban]] I., apărându-le scopul [[lipisrii]] ilegale de viaţă a unei alte persoane, au intrat în ograda lui Nemţanu V. din *****, ***** şi în timp ce acolo se afla Şişcanu Ruslan care dormea, [[Sacviuc]] Alexandru cu o ştachetă, împreună şi Daraban I. cu o coadă de hârleţ i-au aplicat lui Şişcanu Ruslan multiple lovituri peste toată suprafaţa corpului, iar Grecu D. i-a aplicat ultimului câteva lovituri cu picioarele în regiunea abdomenului. Tot el, Savciuc Alexandru, în aceleaşi circumstanţe sus menţionate şi în baza aceloraşi intenţii huliganice, conform raportului de [[expertziă]] medico-legală nr.105 din 06.07.2015 i-a cauzat lui Şişcanu [[Rsulan]] [[traumatsim]] cranio-cerebral acut închis, hemoragii în ţesuturile moi ale capului în regiunea tempora-occipitală pe dreapta; hemoragie subdurală lichidă; hemoragie subarahnoidală difuză a ambelor emisfere a creierului covescital şi bazai la emisfera dreaptă şi a cerebelului; fractura ambelor oase zigomatice, oaselor nazale multe aşchiate; fractura mandibulei pe dreapta în protecţia dinţilor 6,7 cu deplasarea fragentelor; fractura coastelor bilateral fără lezarea pleurei parietale; multiple echimoze difuze la faţă şi a toracelui; excoriaţii la ambele mâini suprafaţa dorsală; multiple excoriaţii la faţă şi la torace, cauzându-i leziuni corporale grave în urma căruia Şişcanu Ruslan a decedat. Cauza decesului este traumatismul cranio-cerebral închis cu fractura oaselor faciale-zigomatice şi nazale, contuzia cerebrală, plaga contuză stelată masivă a ţesuturilor moi ale capului în regiunea occipitală, hemoragia subdurală şi subarahnoidală. 3. Sentința pronunțată integral la 26 decembrie 2016, a fost atacată cu apeluri de către: - procurorul în Procuratura Ungheni, Steclari Ion, la 29 decembrie 2016, prin care a solicitat casarea sentinţei, rejudecarea cauzei şi pronunţarea unei noi hotărâri, potrivit modului stabilit, pentru prima instanţă, prin care: Savciuc Alexandru să fie recunoscut culpabil în comiterea infracţiunii prevăzute de art. 48, 145 alin. (2) lit. i), j) și art. 287 alin.(3) Cod penal, și prin prisma art. 84 Cod penal, să-i fie stabilită pedeapsa sub formă de închisoare pe un termen de 17 ani cu executarea pedepsei în


--------------------------------------------- Result 46 ---------------------------------------------
[[1 (67%)]] --> [[[SKIPPED]]]

În conformitate cu prevederile art.art.3641, 382-399 Cod de procedură penală, instanța de judecată,

--------------------------------------------- Result 47 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Adoptînd sentinţa în cauză instanţa de fond a reţinut, că xxxxNUMExxxx la 22.05.2014, în jurul orelor 20.00, aflîndu­se în s. xxxxORAS_SATxxxx r­l , pe ascuns și întenționat, a pătruns în gospodăria cet.xxxxNUMExxxx, unde din casa acestuia ­o geantă care se pe dulap, a sustras și însușit suma de 1400 lei, cauzînd astfel părții vătămate o daună materială considerabilă. Cauza penală a fost examenată de către instanța de fond în lipsa inculpatului, care se eschiva de la prezentare în fața instanței și care prin încheierea din 23.09.2014 a fost anunțat în căutare, fiind dispusă eliberarea pe numele acestuia a unui mandat de arestare pe un termen de 30 zile. Instanţa de fond a pronunţat sentinţa nominalizată. Inculpatul după reținerea sa și îmînarea copiei sentinței a atacat cu apel sentinţa invocînd ca motive că: consideră pedepsa stabilită de către instanţa de fond ca fiind prea aspră, dat fiind faptul, că vina în comiterea infracţiunii incriminate a recunoscut­o pe deplin şi sincer se căieşte de cele comise; invocă că executarea pedepsei în penitenciar va influenţa în mod negativ asupra sa. El a plecat la lucru peste hotare din dorința de a recupera dauna materială, însă nu a putut reveni la timp acasă. Pe aceste motive apelantul solicită admiterea apelului declarat, cu casarea sentinţei judecătoriei Soroca din 12.12.2014 şi pronunţarea unei noi hotărîri prin care să­i fie stabilită o pedepsă mai blînde nonprivative de libertate. După reluarea cercetării judecătoreşti potrivit modului stabilit pentru prima instanţă și audierea nemijlocită în şedinţa instanţei de apel a inculpatului xxxxNUMExxxx dat fiind faptul, că acesta nu a fost audiat și nu a participat în ședința instanței de fond, a parvenit o cerere în ședința instanței de apel la data de 06.05.2015 din partea părții vătămate xxxxNUMExxxx prin care a solicitat încetarea procesului penal în legătură cu faptul împăcării lui cu inculpatul. În şedinţa instanţei de apel partea vătămată xxxxNUMExxxx a susținut cererea sa cu privire la încetarea procesului penal în legătură cu împăcarea părților. Inculpatul xxxxNUMExxxx și avocatul Muntean Violina, care i­a reprezentat interesele în instanța de apel, au solicitat încetarea procesului penal în legătură cu împăcarea părților. Procurorul participant a pledat pentru respingerea cererii de încetare a procesului penal în legătură cu împăcarea părților și respingerea apelului inculpatului ca nefondat. Colegiul penal, audiind părţile, examinînd materialele dosarului, consideră posibilă admiterea cererii de împăcare a părților cu încetarea procesului penal în privința inculpatului xxxxNUMExxxx. Conform prevederilor art.391 alin.(1) pct.1) CPP sentința de încetare a procesului penal se adoptă dacă lipsește plîngerea părții vătămate, plîngerea a fost retrasă sau părțile s­au împăcat. Potrivit art.16 alin.(3) CP infracțiunea prevăzute de art.186 alin.(2) CP se califică ca mai puțin gravă, deoarece prevede pedeapsă maximă a închisorii pe un termen de pînă la 4 ani. Potrivit art.109 alin.(1) CP împăcarea este actul de înlăturare a răspunderii penale pentru o infracțiune ușoară sau mai puțin gravă, iar în cazul minorilor, și pentru o infracțiune gravă, infracțiuni incorporate în capitolele II­VI din Partea specială, precum și în cazurile prevăzute de procedura penală. Potrivit alin. (2) art. 109 CP împăcarea este personală şi produce efecte juridice din

--------------------------------------------- Result 48 ---------------------------------------------
[[0 (99%)]] --> [[1 (50%)]]

Grințevici Serghei, la data de 17.08.2015, aproximativ la ora 03:00, fiind în stare de ebrietate, înțelegînd caracterul prejudiciabil al acțiunilor sale, a condus autocamionul de model „Fiat Scudo” cu nr. de înmatriculare SG AM 213, prin s. Alexăndreni, r­nul Sîngerei unde a fost stopat de colaboratorii poliției și fiind suspectat în consum de băuturi alcoolice, a fost supus testării alcoolscopice, prin care s­a constatat o concentrație de alcool în aerul expirat de 0,5 mg/l. În ședința de [[judecată]] [[inculpatul]] Grințevici vina și­a recunoscut­o pe deplin, se căiește în cele săvîrșite de el și a [[declarat]] că la data de 17.08.2015, aproximativ la ora 03:00, fiind în stare de ebrietate, a condus autocamionul de model „Fiat Scudo” cu nr. de înmatriculare SG AM 213, prin s. Alexăndreni, r­nul [[Sîngerei]] unde a fost stopat de colaboratorii poliției și supus testării alcoolscopice, prin care s­a constatat o concentrație de alcool în aerul expirat de 0,5 mg/l. [[Inculpatul]] în ședința de judecată a solicitat aplicarea unei pedepse sub formă de amendă. În afară de recunoașterea faptei de [[către]] inculpat, vina lui în ședința judiciară este dovedită și de: ­ Raportul privind recepționarea [[apelului]] telefonic. /f.d. 7/; ­ Proces­verbal de testare alcoolscopicăcși anexe. /f.d. 9­10/; ­ Proces­verbal de constatare a faptei de conducere a mijlocuui de transport în stare de ebrietate alcoolică. /f.d. 11/; ­ Proces­[[verbal]] nr. 268 al [[examinării]] medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate și naturii ei, conform căruia Grințevici [[Serghei]] se afla în stare de ebrietate alcoolică cu [[grad]] avansat. /f.d. 10­11/; În aşa mod, instanţa consideră vina inculpatului Grințevici [[Serghei]] dovedită şi confirmată pe [[deplin]] în şedinţa [[judiciară]], iar acţiunile lui le califică în [[baza]] art. [[2641]] alin. (1) CP al Republicii [[Moldova]] după [[semnele]]: ­ [[Conducerea]] mijlocului de transport de [[către]] o persoană [[care]] se află în stare de ebrietate alcoolică cu [[grad]] [[avansat]]. Conform art. 76, 77 CP RM la stabilirea măsurii de [[pedeapsă]] in privinţa [[inculpatului]], judecata ţine cont de circumstanţele [[atenuante]] şi agravante la săvîrşirea infracţiunii. Circumstanţe atenuante în [[ședința]] de [[judecată]] nu au [[fost]] stabilite. Circumstanţe agravante în privinţa inculpatului XXXXXXXXX – săvîrșirea infracțiunii în stare de ebrietate. Prin sentința Judecătoriei Sîngerei din 13 octombrie 2015, Grințevici Serghei a fost condamnat în baza art. 27, 186 alin. (2) lit. c), d) CP RM, fiindu­i stabilită o pedeapsă sub formă de închisoare pe un termen de 2 (doi) ani, în penitenciar de tip semiînchis. Potrivit art. 87 CPP – (1) La cumularea diferitelor pedepse principale aplicate în cazul unui concurs de infracţiuni sau al unui cumul de sentinţe, unei zile de închisoare îi corespund 2 ore de muncă neremunerată în folosul comunităţii. (2) Celelalte pedepse cumulate cu închisoarea se execută de sine stătător. Ţinînd cont de circumstanţele expuse mai sus, de faptul că Grințevici Serghei și­a recunoscut vina integral, se căiește de cele săvîrșite, instanța de judecată ajunge la concluzia de a aplica în privința lui Grințevici Serghei o pedeapsă sub formă de amendă. În conformitate cu art.art. 384­386 CPP al RM instanţa de judecată,­

Grințevici Serghei, la data de 17.08.2015, aproximativ la ora 03:00, fiind în stare de ebrietate, înțelegînd caracterul prejudiciabil al acțiunilor sale, a condus autocamionul de model „Fiat Scudo” cu nr. de înmatriculare SG AM 213, prin s. Alexăndreni, r­nul Sîngerei unde a fost stopat de colaboratorii poliției și fiind suspectat în consum de băuturi alcoolice, a fost supus testării alcoolscopice, prin care s­a constatat o concentrație de alcool în aerul expirat de 0,5 mg/l. În ședința de [[judectaă]] [[icnulpatul]] Grințevici vina și­a recunoscut­o pe deplin, se căiește în cele săvîrșite de el și a [[declaart]] că la data de 17.08.2015, aproximativ la ora 03:00, fiind în stare de ebrietate, a condus autocamionul de model „Fiat Scudo” cu nr. de înmatriculare SG AM 213, prin s. Alexăndreni, r­nul [[Sîgnerei]] unde a fost stopat de colaboratorii poliției și supus testării alcoolscopice, prin care s­a constatat o concentrație de alcool în aerul expirat de 0,5 mg/l. [[Inculptaul]] în ședința de judecată a solicitat aplicarea unei pedepse sub formă de amendă. În afară de recunoașterea faptei de [[cărte]] inculpat, vina lui în ședința judiciară este dovedită și de: ­ Raportul privind recepționarea [[apleului]] telefonic. /f.d. 7/; ­ Proces­verbal de testare alcoolscopicăcși anexe. /f.d. 9­10/; ­ Proces­verbal de constatare a faptei de conducere a mijlocuui de transport în stare de ebrietate alcoolică. /f.d. 11/; ­ Proces­[[vrebal]] nr. 268 al [[examinrăii]] medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate și naturii ei, conform căruia Grințevici [[Serhgei]] se afla în stare de ebrietate alcoolică cu [[gard]] avansat. /f.d. 10­11/; În aşa mod, instanţa consideră vina inculpatului Grințevici [[Sergehi]] dovedită şi confirmată pe [[depiln]] în şedinţa [[juidciară]], iar acţiunile lui le califică în [[bzaa]] art. [[2461]] alin. (1) CP al Republicii [[Modlova]] după [[senmele]]: ­ [[Cnoducerea]] mijlocului de transport de [[cărte]] o persoană [[crae]] se află în stare de ebrietate alcoolică cu [[gard]] [[aavnsat]]. Conform art. 76, 77 CP RM la stabilirea măsurii de [[pedeaspă]] in privinţa [[inculpatluui]], judecata ţine cont de circumstanţele [[aetnuante]] şi agravante la săvîrşirea infracţiunii. Circumstanţe atenuante în [[șeidnța]] de [[jduecată]] nu au [[fsot]] stabilite. Circumstanţe agravante în privinţa inculpatului XXXXXXXXX – săvîrșirea infracțiunii în stare de ebrietate. Prin sentința Judecătoriei Sîngerei din 13 octombrie 2015, Grințevici Serghei a fost condamnat în baza art. 27, 186 alin. (2) lit. c), d) CP RM, fiindu­i stabilită o pedeapsă sub formă de închisoare pe un termen de 2 (doi) ani, în penitenciar de tip semiînchis. Potrivit art. 87 CPP – (1) La cumularea diferitelor pedepse principale aplicate în cazul unui concurs de infracţiuni sau al unui cumul de sentinţe, unei zile de închisoare îi corespund 2 ore de muncă neremunerată în folosul comunităţii. (2) Celelalte pedepse cumulate cu închisoarea se execută de sine stătător. Ţinînd cont de circumstanţele expuse mai sus, de faptul că Grințevici Serghei și­a recunoscut vina integral, se căiește de cele săvîrșite, instanța de judecată ajunge la concluzia de a aplica în privința lui Grințevici Serghei o pedeapsă sub formă de amendă. În conformitate cu art.art. 384­386 CPP al RM instanţa de judecată,­

--------------------------------------------- Result 49 ---------------------------------------------
[[0 (96%)]] --> [[1 (52%)]]

La 30.07.2015 [[condamnatul]], XXXXXXXXX, a înaintat recurs împotriva încheierii din 23.07.2015 a judecătoriei Soroca. Drept motiv, în argumentarea şi susţinerea recursului, recurentul invocă, că instanţa de fond n­a calculat corect termenul de executare a pedepsei penale şi că acesta urmează a fi de 15 ani şi 1 lună, dar nu 15 ani şi 6 luni de închisoare în penitenciar de tip închis. Avocatul D.Duca a solicitat admiterea recursului. În şedinţa instanţei de recurs procurorul a solicitat respingerea recursului. Condamnatul XXXXXXXXX a solicitat examinarea cauzei în lipsa sa, solicitînd remiterea copiei deciziei. Verificînd argumentele recurentului, ascultînd participanţii, studiind materialele cauzei, Colegiul penal consideră, că recursul declarat urmează a fi respins ca nefondat. Conform prevederilor art.449 alin.(1) pct.1) lit.a) Cod de procedură penală, ,,Judecînd recursul, instanţa adoptă una din următoarele decizii 1) respinge recursul, menţinînd hotărîrea atacată, dacă a) recursul este nefondat;” Prin sentinţa judecătoriei Ciocana mun.Chişinău din 24.05.2007, XXXXXXXXX xxxxx a fost condamnat în baza art.145 alin.(2) lit.c) Cod penal la 17 ani de închisoare cu ispăşirea în penitenciar de tip închis, fiind inclus şi termenul de ţinere în [[stare]] de arest 15.12.2006­03.05.2007. Prin sentinţa judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, XXXXXXXXX xxxxxr a fost condamnat în baza art.217 alin.(2) Cod penal la 6 luni de închisoare şi conform art.84 alin.(4) Cod penal, prin cumul partial al pedepsei stabilite prin sentinţa judecătoriei Ciocana mun.Chişinău din 24.05.2007, i­a fost stabilit definitiv 17 ani şi 1 lună de închisoare cu ispăşirea în [[penitenciar]] de tip închis, fiind inclus termenul arestului preventive din 15.12.2006­XXXXXXXXX. Prin încheierea judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, a fost admisă cererea [[condamnatului]] XXXXXXXXX Victor şi au [[fost]] recalificate acţiunile lui din prevederile art.145 [[alin]].(2) lit.c) Cod penal în prevederile art.145 alin.(1) Cod penal, stabilindu­i pedeapsă de 15 ani de închisoare cu executarea pedepsei în [[penitenciar]] de tip [[închis]], fiind înclus termenul de la 15.12.2006 pînă la XXXXXXXXX. Prin încheierea judecătoriei Soroca din XXXXXXXXX lui xxxxxx i­a fost stabilit pedeapsa penală definitivă de 15 ani şi 6 luni închisoare în penitenciar de tip închis. Instanţa de fond a adoptat o încheiere legală şi întemeiată, fiind luate în consideraţie hotărîrile de condamnare anterioare, cît şi prevederile art.84 alin.(4) Cod penal. Corect a fost calculat termenul pedepsei de 15 ani şi 6 luni de închisoare, aşa cum XXXXXXXXX xxx a fost condamnat în baza art.217 alin.(2) Cod penal la 6 luni de închisoare prin sentinţa judecătoriei Buiucani mun.Chişinău din XXXXXXXXX şi la 15 ani de închisoare prin încheierea judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, iar prin art.84 alin.(4) Cod penal aceste pedepse au fost cumulate total, aceasta rezultînd atît din parte descriptivă, cît şi din parte dispozitivă a încheierii. Prevederile art.84 alin.(4) Cod penal au fost corect aplicate de către instanţa de fond. Argumentele expuse în recurs nu pot prevala situaţiei de fapt reţinute şi prevederilor legale. În baza celor menţionate, Colegiul penal a ajuns la concluzia, că recursul este nefondat şi urmează a fi respins, cu menţinerea încheierii atacate. Conducîndu­se de art.art.447­ 448, art.449 alin.(1), p.1), lit.a) Cod de procedură penală al RM, Colegiul penal,­

La 30.07.2015 [[condamnautl]], XXXXXXXXX, a înaintat recurs împotriva încheierii din 23.07.2015 a judecătoriei Soroca. Drept motiv, în argumentarea şi susţinerea recursului, recurentul invocă, că instanţa de fond n­a calculat corect termenul de executare a pedepsei penale şi că acesta urmează a fi de 15 ani şi 1 lună, dar nu 15 ani şi 6 luni de închisoare în penitenciar de tip închis. Avocatul D.Duca a solicitat admiterea recursului. În şedinţa instanţei de recurs procurorul a solicitat respingerea recursului. Condamnatul XXXXXXXXX a solicitat examinarea cauzei în lipsa sa, solicitînd remiterea copiei deciziei. Verificînd argumentele recurentului, ascultînd participanţii, studiind materialele cauzei, Colegiul penal consideră, că recursul declarat urmează a fi respins ca nefondat. Conform prevederilor art.449 alin.(1) pct.1) lit.a) Cod de procedură penală, ,,Judecînd recursul, instanţa adoptă una din următoarele decizii 1) respinge recursul, menţinînd hotărîrea atacată, dacă a) recursul este nefondat;” Prin sentinţa judecătoriei Ciocana mun.Chişinău din 24.05.2007, XXXXXXXXX xxxxx a fost condamnat în baza art.145 alin.(2) lit.c) Cod penal la 17 ani de închisoare cu ispăşirea în penitenciar de tip închis, fiind inclus şi termenul de ţinere în [[satre]] de arest 15.12.2006­03.05.2007. Prin sentinţa judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, XXXXXXXXX xxxxxr a fost condamnat în baza art.217 alin.(2) Cod penal la 6 luni de închisoare şi conform art.84 alin.(4) Cod penal, prin cumul partial al pedepsei stabilite prin sentinţa judecătoriei Ciocana mun.Chişinău din 24.05.2007, i­a fost stabilit definitiv 17 ani şi 1 lună de închisoare cu ispăşirea în [[peintenciar]] de tip închis, fiind inclus termenul arestului preventive din 15.12.2006­XXXXXXXXX. Prin încheierea judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, a fost admisă cererea [[codnamnatului]] XXXXXXXXX Victor şi au [[fsot]] recalificate acţiunile lui din prevederile art.145 [[ailn]].(2) lit.c) Cod penal în prevederile art.145 alin.(1) Cod penal, stabilindu­i pedeapsă de 15 ani de închisoare cu executarea pedepsei în [[pentienciar]] de tip [[îcnhis]], fiind înclus termenul de la 15.12.2006 pînă la XXXXXXXXX. Prin încheierea judecătoriei Soroca din XXXXXXXXX lui xxxxxx i­a fost stabilit pedeapsa penală definitivă de 15 ani şi 6 luni închisoare în penitenciar de tip închis. Instanţa de fond a adoptat o încheiere legală şi întemeiată, fiind luate în consideraţie hotărîrile de condamnare anterioare, cît şi prevederile art.84 alin.(4) Cod penal. Corect a fost calculat termenul pedepsei de 15 ani şi 6 luni de închisoare, aşa cum XXXXXXXXX xxx a fost condamnat în baza art.217 alin.(2) Cod penal la 6 luni de închisoare prin sentinţa judecătoriei Buiucani mun.Chişinău din XXXXXXXXX şi la 15 ani de închisoare prin încheierea judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, iar prin art.84 alin.(4) Cod penal aceste pedepse au fost cumulate total, aceasta rezultînd atît din parte descriptivă, cît şi din parte dispozitivă a încheierii. Prevederile art.84 alin.(4) Cod penal au fost corect aplicate de către instanţa de fond. Argumentele expuse în recurs nu pot prevala situaţiei de fapt reţinute şi prevederilor legale. În baza celor menţionate, Colegiul penal a ajuns la concluzia, că recursul este nefondat şi urmează a fi respins, cu menţinerea încheierii atacate. Conducîndu­se de art.art.447­ 448, art.449 alin.(1), p.1), lit.a) Cod de procedură penală al RM, Colegiul penal,­

--------------------------------------------- Result 50 ---------------------------------------------
[[1 (58%)]] --> [[0 (77%)]]

Prin sentința Judecătoriei Vulcănești din 12 iulie 2013 xxxxxxxxxxxx a fost achitat de învinuirea de săvârşire a infracţiunilor prevăzută de art. 287 alin.(3) și art. 151 alin.(1) Cod penal din motivul că acțiunile inculpatului au fost săvârșite în stare de legitimă apărare. Pentru a pronunța sentința de achitare în privința inculpatului xxxxxxxxxx prima [[instanță]] a reţinut că, xxxxxxxxxxx se învinuiește că la 29 octombrie 2011, pe timp de noapte, în încăperea pentru animale a fostei ferme de produse lactate ”xxxxxxxxxx”, din intenții huliganice, în prezența altor persoane,intenționat, încălcând grosolan ordinea publică și liniștea cetățenilor, acționând cu o deosebită obrăznicie, fiind înarmat cu un cuțit, a aplicat în privința lui xxxxxxxxxxn și xxxxxxxxxxx, violența fizică, manifestată prin cauzarea diferitor leziuni corporale, de asemenea a încercat să aplice violența fizică cu cuțitul în privința lui xxxxxxxxxxxxx. Tot, el, la 29 octombrie 2011, pe timp de noapte, în încăperea pentru animale a fostei ferme de produse lactate SRL”xxxxxxxxx”, din intenții huliganice, în prezența altor persoane,intenționat, încălcând grosolan ordinea publică și liniștea cetățenilor, acționând cu o deosebită obrăznicie, fiind înarmat cu un cuțit, a aplicat în privința lui xxxxxxxxxx, violența fizică, manifestată prin cauzarea leziunilor corporale sub formă de plagă tăiată a cutiei toracice pe stânga penetrantă în cavitatea pleurei, cu lezarea părții de jos a plămânului; plagă a peretelui cavității abdominale fără penetrare în cavitatea abdominală, care conform raportului de expertiză cu nr. 48d din 16.11.2011, au fost produse prin acțiunea traumatică a unui obiect ascuțit­tăietor, posibil cu cuțit, și se califică ca leziuni corporale grave, periculoase pentru viață. Împotriva sentinței enunțate, la data de 24 iulie 2013, procurorul în Procuratura raionului Vulcănești, xxxxxxxxx, a declarat apel, prin care a solicitat casarea cesteia, cu pronunțarea unei noi hotărâri, prin care xxxxxxxxxxx să fie recunoscut vinovat în comiterea infracțiunilor prevăzute de art. 287 alin.(3) și art. 151 alin.(1) Cod penal, cu aplicarea pedepsei în baza art. 287 alin.(3) Cod penal la 03 ani închisoare, în baza art. 151 alin.(1) Cod penal, la 03 ani închisoare. Conform art. 84 Cod penal, pentru concurs de infracțiuni prin cumul parțial al pedepselor aplicate, de a stabili pedeapsa definitivă sub formă de 04 ani închisoare cu executarea pedepsei în penitenciar de tip semiînchis. Conform art. 90 Cod penal, să­i fie suspendată condiţionat executarea pedepsei pe un termen de probă de 04 ani, și cu stabilirea conform art. 90 alin.(6) Cod penal, obligații inculpatului. Concomitent, potrivit art. 90 alin.(5) și 67 Cod penal, să­i fie aplicată inculpatului pedeapsa complementară sub formă de muncă neremunerată în folosul comunității în mărime de 200 ore. În motivarea apelului s­a indicat că, acuzatorul de stat nu contestă concluzia instanței de judecată în partea cât privește prezența în acțiunile inculpatului xxxxxxxx a elementelor infracțiunilor prevăzute de art. 287 alin.(3) și art. 151 alin.(1) Cod penal, însă contestă concluzia instanței că în acțiunile inculpatului este prezentă legitima apărare, adică circumstanța care înlătură caracterul penal al faptei. Motivele dezacordului cu concluziile instanței de judecată rezultă din faptul că instanța nu a cercetat și nu a argumentat toate criteriile prevăzute la art. 36 Cod penal, fiind descris doar faptul

Prin sentința Judecătoriei Vulcănești din 12 iulie 2013 xxxxxxxxxxxx a fost achitat de învinuirea de săvârşire a infracţiunilor prevăzută de art. 287 alin.(3) și art. 151 alin.(1) Cod penal din motivul că acțiunile inculpatului au fost săvârșite în stare de legitimă apărare. Pentru a pronunța sentința de achitare în privința inculpatului xxxxxxxxxx prima [[isntanță]] a reţinut că, xxxxxxxxxxx se învinuiește că la 29 octombrie 2011, pe timp de noapte, în încăperea pentru animale a fostei ferme de produse lactate ”xxxxxxxxxx”, din intenții huliganice, în prezența altor persoane,intenționat, încălcând grosolan ordinea publică și liniștea cetățenilor, acționând cu o deosebită obrăznicie, fiind înarmat cu un cuțit, a aplicat în privința lui xxxxxxxxxxn și xxxxxxxxxxx, violența fizică, manifestată prin cauzarea diferitor leziuni corporale, de asemenea a încercat să aplice violența fizică cu cuțitul în privința lui xxxxxxxxxxxxx. Tot, el, la 29 octombrie 2011, pe timp de noapte, în încăperea pentru animale a fostei ferme de produse lactate SRL”xxxxxxxxx”, din intenții huliganice, în prezența altor persoane,intenționat, încălcând grosolan ordinea publică și liniștea cetățenilor, acționând cu o deosebită obrăznicie, fiind înarmat cu un cuțit, a aplicat în privința lui xxxxxxxxxx, violența fizică, manifestată prin cauzarea leziunilor corporale sub formă de plagă tăiată a cutiei toracice pe stânga penetrantă în cavitatea pleurei, cu lezarea părții de jos a plămânului; plagă a peretelui cavității abdominale fără penetrare în cavitatea abdominală, care conform raportului de expertiză cu nr. 48d din 16.11.2011, au fost produse prin acțiunea traumatică a unui obiect ascuțit­tăietor, posibil cu cuțit, și se califică ca leziuni corporale grave, periculoase pentru viață. Împotriva sentinței enunțate, la data de 24 iulie 2013, procurorul în Procuratura raionului Vulcănești, xxxxxxxxx, a declarat apel, prin care a solicitat casarea cesteia, cu pronunțarea unei noi hotărâri, prin care xxxxxxxxxxx să fie recunoscut vinovat în comiterea infracțiunilor prevăzute de art. 287 alin.(3) și art. 151 alin.(1) Cod penal, cu aplicarea pedepsei în baza art. 287 alin.(3) Cod penal la 03 ani închisoare, în baza art. 151 alin.(1) Cod penal, la 03 ani închisoare. Conform art. 84 Cod penal, pentru concurs de infracțiuni prin cumul parțial al pedepselor aplicate, de a stabili pedeapsa definitivă sub formă de 04 ani închisoare cu executarea pedepsei în penitenciar de tip semiînchis. Conform art. 90 Cod penal, să­i fie suspendată condiţionat executarea pedepsei pe un termen de probă de 04 ani, și cu stabilirea conform art. 90 alin.(6) Cod penal, obligații inculpatului. Concomitent, potrivit art. 90 alin.(5) și 67 Cod penal, să­i fie aplicată inculpatului pedeapsa complementară sub formă de muncă neremunerată în folosul comunității în mărime de 200 ore. În motivarea apelului s­a indicat că, acuzatorul de stat nu contestă concluzia instanței de judecată în partea cât privește prezența în acțiunile inculpatului xxxxxxxx a elementelor infracțiunilor prevăzute de art. 287 alin.(3) și art. 151 alin.(1) Cod penal, însă contestă concluzia instanței că în acțiunile inculpatului este prezentă legitima apărare, adică circumstanța care înlătură caracterul penal al faptei. Motivele dezacordului cu concluziile instanței de judecată rezultă din faptul că instanța nu a cercetat și nu a argumentat toate criteriile prevăzute la art. 36 Cod penal, fiind descris doar faptul

--------------------------------------------- Result 51 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Pe data de 22 ianuarie 2011 , în intervalul de timp cuprins între ora 05.00 – 05.47 , inculpatul xxxxNUMExxxx conducînd automobilul de marca „BMW” model 520 , cu numărul de înregistrare WW­KS 751 în or.Rezina , str.27 August a încălcat prevederile Regulamentului Circulaţiei Rutiere, aprobat prin HG RM nr.357 din 13.05.2009 , şi anume : pct.3 , care prevede – „participanţii la trafic sînt obligaţi să respecte regulile de circulaţie , condiţiile tehnice ale prezentului Regulament şi prin acţiunile lor să nu cauzeze prejudicii altor participanţi la trafic , să nu­i expună pericolului , precum şi să nu creeze neîntemeiat obstacole circulaţiei care ar depăşi pe acele care sînt provocate de circumstanţe iminente” ; pct.10 al.(2) lit.a) – „persoana care conduce un autovehicul trebuie să posede , şi la cererea lucrătorului de poliţie , ofiţerului echipe mobile al serviciului vamal , este obligată să înmîneze pentru control permisul de conducere perfectat pe numele său, valabil pentru categoria, din care face parte autovehicolul condus ; pct.14 lit.a) – „conducătorului îi este interzis să conducă vehicolul în stare de ebrietate”, deoarece conducătorul auto nu deţinea permis de conducere şi potrivit examinării medicale pentru stabilirea stării de ebrietate şi naturii ei , s­a constatat că, concentraţia de alcool în sîngele şoferului xxxxNUMExxxx este de 1,03 g/l , iar concentraţia vaporilor de alcool în aerul expirat de 0,63 mg/l , care conform art.134/12 al.(3) din Codul Penal al RM se califică ca stare de ebrietate alcoolică cu grad avansat. Vina inculpatului xxxxNUMExxxx în comiterea acestei infracţiuni a fost dovedită în cadrul cercetărilor judecătoreşti prin declaraţiile martorilor şi prin materialele dosarului penal. Astfel martorul Muştuc Mihail a declarat în instanţa de judecată că activează în SPR a CPR Rezina în funcţie de inspector pentru Sistematizarea Circulaţiei Rutiere. La 22.01.2011 efectua serviciul în grupa operativă a CPR Rezina. Pe la vre­o orele 05.30 min. pe str.27 August în or.Rezina a stopat pentru verificare automobilul de model „BMW” , care avea o deplasare neadecvată. La volanul automobilului respectiv se afla şoferul xxxxNUMExxxx, care era de unul singur în automobil. A simţit miros puternic de alcool de la şofer şi i­a cerut actele la control. Nasaev în mod categoric a refuzat să­i prezinte actele. L­a supus verificării la alcotestul „Drager” , în urma la ce s­a stabilit că concentraţia vaporilor de alcool în aerul expirat constituie 0,63 mg/litru. În continuare xxxxNUMExxxx. a fost condus la secţia de internare a spitalui raional Rezina , unde a fost supus examinării medicale de către medicul Renchez Valentina. În urma controlului medical s­a constat că întradevăr xxxxNUMExxxx este în stare de ebrietate alcoolică. Tot atunci i­au fost recoltate probe biologice , sînge din venă pentru analiza de laborator.Verificînd datele Centrului de informaţie s­a constatat că, cet.xxxxNUMExxxx nu dispune de permisul de conducere. Martorul Renchez Valentina a declarat judecăţii că la 21.01.2011 a intrat în serviciul de gardă la spital. Aproximativ pe la orele 05.40 pe data de 22.01.2011 în spital a fost adus de către inspectorul poliţiei rutiere Muştuc M. pentru examinarea medicală şi aprecierea stării de ebrietate cet. xxxxNUMExxxx. În urma examinării

--------------------------------------------- Result 52 ---------------------------------------------
[[0 (94%)]] --> [[1 (54%)]]

XXXXXXXXX, la data de 13.09.2014, aproximativ pe la orele 19:00, aflîndu­se în locuinţa cet. XXXXXXXXX Tudor, a.n. 01.01.1975, situată pe teritoriul Întovărăşirii pomicole «Raduga» din s.[[Corlăteni]] r­nul Rîşcani, fiind în stare de ebrietate alcoolică, în rezultatul unui conflict care a apărut între el şi cet. XXXXXXXXX Tudor, cu care au servit băuturi alcoolice, intenţionat, l­a ameninţat cu omor pe cet.XXXXXXXXX Tudor, după care, cu ajutorul unui topor pe care l­a găsit în locuinţa ultimului, a încercat să­l lovească pe cet.Vizir Ştefan Tudor în regiunea capului, existînd pericolul realizării acestei ameninţări, însă acţiunile de violenţă au fost contracarate de către victimă, care au fost percepute ca reale. În cadrul şedinţei de judecată [[inculpatul]] XXXXXXXXX a recunoscut integral vinovăţia în faptele comise şi a declarat că dorește să se împace cu partea vătămată. [[Necătînd]] la faptul recunoaşterii vinovăţiei inculpatului XXXXXXXXX, culpa acestuia se devedeşte şi de declarațiile: Părții vătămate XXXXXXXXX care a declarat că, la data de 13.09.2014, la orele 19:00 a servit băuturi alcoolice. Între el și Postoronco Stanislav s­a iscat un conflict. Ambii se aflau în stare de ebrietate. Postoronco Stanislav în timpul conflictului se afla cu toporul în mînă. Cînd dînsul a vrut să­i i­a toporul, în timpul dînsul s­a lovit de topor. Concubina a chemat salvarea care a comunicat la poliție. La moment careva pretenții materiale sau morale față de Postoronco Stanislav nu are. Solicită încetarea procesului penal în privința lui Postoronco Stanislav, și de materialele cauzei penale administrate în cadrul cercetării judecătorești şi anume: * Procesul­[[verbal]] de sesizare despre săvârşirea sau pregătirea pentru săvârşirea infracţiunii din 13.09.2014 – Vizir Ştefan Tudor. (f.d. 5 ) * Proces­[[verbal]] de cercetare la faţa locului din 13.09.2014 (f.d. 7­9 ) * Planşa fotografică (f.d. 10­15) * Ordonanţă de ridicare din 13.09.2014 (f.d. 16, 18) * Proces­verbal de ridicare din 13.09.2014 (f.d. 17, 19) * Raportul de expertiză medico­legală nr.1337 din XXXXXXXXX, conform căruia în mostrele de sînge prelevat de la cet. XXXXXXXXX Tudor s­a depistat alcool etilic în cantitate de 2,63o/ , echivalent a 2,63 mg/l. ( f.d. 30) 00 * Raportul de expertiză medico­legală nr.1338 din XXXXXXXXX, conform căruia în mostrele de sînge prelevat de la cet. XXXXXXXXX s­a depistat alcool etilic în cantitate de 3,93o/ , echivalent a 3,93 mg/l. ( f.d. 30) 00 * Proces­verbal privind corectarea erorilor materiale din 30.102014. (f.d. 58 ) Astfel, examinând probele cerecetate în cadrul şedinţei de judecată în raport cu declaraţiile inculpaților de recunoaştere a vinovăţiei, instanţa ajunge la concluzia că acţiunile inculpatului, corect, au fost încadrate în componenţa de infracţiune prevăzută de art. 155 CP RM cu indicii de calificare: amenințarea cu omor, dacă a existat pericolul realizării acestei amenințări. Partea vătămată XXXXXXXXX a înaintat o cerere prin care a solicitat instanţei de a înceta procesul penal în privinţa lui XXXXXXXXX în legătură cu faptul că s­au împăcat şi careva pretenţii faţă de el nu are şi nu doreşte să fie atras la răspundere penală. În consecinţă, elucidînd motivele de fapt şi de drept, instanţa reţine că, potrivit cererii părții vătămate XXXXXXXXX depuse în cadrul cercetărilor judecătoreşti, acesta solicită încetarea procedurii în privinţa

XXXXXXXXX, la data de 13.09.2014, aproximativ pe la orele 19:00, aflîndu­se în locuinţa cet. XXXXXXXXX Tudor, a.n. 01.01.1975, situată pe teritoriul Întovărăşirii pomicole «Raduga» din s.[[Colrăteni]] r­nul Rîşcani, fiind în stare de ebrietate alcoolică, în rezultatul unui conflict care a apărut între el şi cet. XXXXXXXXX Tudor, cu care au servit băuturi alcoolice, intenţionat, l­a ameninţat cu omor pe cet.XXXXXXXXX Tudor, după care, cu ajutorul unui topor pe care l­a găsit în locuinţa ultimului, a încercat să­l lovească pe cet.Vizir Ştefan Tudor în regiunea capului, existînd pericolul realizării acestei ameninţări, însă acţiunile de violenţă au fost contracarate de către victimă, care au fost percepute ca reale. În cadrul şedinţei de judecată [[inuclpatul]] XXXXXXXXX a recunoscut integral vinovăţia în faptele comise şi a declarat că dorește să se împace cu partea vătămată. [[Necătnîd]] la faptul recunoaşterii vinovăţiei inculpatului XXXXXXXXX, culpa acestuia se devedeşte şi de declarațiile: Părții vătămate XXXXXXXXX care a declarat că, la data de 13.09.2014, la orele 19:00 a servit băuturi alcoolice. Între el și Postoronco Stanislav s­a iscat un conflict. Ambii se aflau în stare de ebrietate. Postoronco Stanislav în timpul conflictului se afla cu toporul în mînă. Cînd dînsul a vrut să­i i­a toporul, în timpul dînsul s­a lovit de topor. Concubina a chemat salvarea care a comunicat la poliție. La moment careva pretenții materiale sau morale față de Postoronco Stanislav nu are. Solicită încetarea procesului penal în privința lui Postoronco Stanislav, și de materialele cauzei penale administrate în cadrul cercetării judecătorești şi anume: * Procesul­[[verabl]] de sesizare despre săvârşirea sau pregătirea pentru săvârşirea infracţiunii din 13.09.2014 – Vizir Ştefan Tudor. (f.d. 5 ) * Proces­[[verabl]] de cercetare la faţa locului din 13.09.2014 (f.d. 7­9 ) * Planşa fotografică (f.d. 10­15) * Ordonanţă de ridicare din 13.09.2014 (f.d. 16, 18) * Proces­verbal de ridicare din 13.09.2014 (f.d. 17, 19) * Raportul de expertiză medico­legală nr.1337 din XXXXXXXXX, conform căruia în mostrele de sînge prelevat de la cet. XXXXXXXXX Tudor s­a depistat alcool etilic în cantitate de 2,63o/ , echivalent a 2,63 mg/l. ( f.d. 30) 00 * Raportul de expertiză medico­legală nr.1338 din XXXXXXXXX, conform căruia în mostrele de sînge prelevat de la cet. XXXXXXXXX s­a depistat alcool etilic în cantitate de 3,93o/ , echivalent a 3,93 mg/l. ( f.d. 30) 00 * Proces­verbal privind corectarea erorilor materiale din 30.102014. (f.d. 58 ) Astfel, examinând probele cerecetate în cadrul şedinţei de judecată în raport cu declaraţiile inculpaților de recunoaştere a vinovăţiei, instanţa ajunge la concluzia că acţiunile inculpatului, corect, au fost încadrate în componenţa de infracţiune prevăzută de art. 155 CP RM cu indicii de calificare: amenințarea cu omor, dacă a existat pericolul realizării acestei amenințări. Partea vătămată XXXXXXXXX a înaintat o cerere prin care a solicitat instanţei de a înceta procesul penal în privinţa lui XXXXXXXXX în legătură cu faptul că s­au împăcat şi careva pretenţii faţă de el nu are şi nu doreşte să fie atras la răspundere penală. În consecinţă, elucidînd motivele de fapt şi de drept, instanţa reţine că, potrivit cererii părții vătămate XXXXXXXXX depuse în cadrul cercetărilor judecătoreşti, acesta solicită încetarea procedurii în privinţa


--------------------------------------------- Result 53 ---------------------------------------------
[[0 (98%)]] --> [[[SKIPPED]]]

xxxxNUMExxxx este învinuit pentru faptul că, urmărind intenţia de a comite o infracţiune privind circulaţia ilegală a substanţelor narcotice, fără scop de înstrăinare, a colectat şi a păstrat în domiciliului său situat în xxxxSATxxxx r­ul Ştefan Vodă, 41,36 grame de marihuană (Canabis) şi 3,28 g, de paie de mac pînă la data de 12.09.2014, cînd această masă vegetală, a fost depistată şi ridicată de către colaboratorii de poliţie. Conform raportului de constatare tehnico­ştiinţifică nr. 8349 din 01.10.2014, a fost constatat că masa vegetală depistată şi ridicată de la domiciliul cet. xxxxNUMExxxx în cantitate de 31,36 g, reprezintă marihuana care se atribuie la substanţe narcotice, iar masa vegetală în cantitate de 3,28 g reprezintă paie de mac, care conţin alcoloizi narcotici morfină tebeină, substanţe narcotice cantitatea cărora este în proporţii mari. Astfel, xxxxNUMExxxx este învinuit pentru faptul că, prin acţiunile sale intenţionate, a comis infracţiunea prevăzută de art. 217 al. (2) Cod penal conform indicilor: ­ păstrarea plantelor ce conţin substanţe narcotice, fără scop de înstrăinare, în proporţii mari. Fiind audiat în ședința de judecată, inculpatul vinovăția nu și­a recunoscut și a declarat că, locuiește în xxxxSATxxxx în casa surorii. Sora lui, care este proprietara casei, locuiește în xxxxORAȘxxxx. La data de 12.09.2014 a fost chemat la primăria xxxxSATxxxx, unde colaboratorii de poliție i­au explicat că, la domiciliul lui va fi efectuată percheziția. Au mers la domiciliul lui, unde au intrat în casă. Percheziția a fost efectuată de două grupuri de polițiști, el fiind într­o cameră, iar o parte din polițiști în altă cameră. Au fost găsite sacoșe cu masa vegetală, însă el nu știe cine a adus aceste sacoșe și de unde au apărut la el la domiciliu. A mai declarat că locuiește singur, însă uneori vine sora lui, cu soțul, se mai intîmplă că, la el vin și oaspeți. Nu este consumător de droguri și nu are prieteni care consumă droguri. Invocă procurorul că, vina inculpatului a fost demonstrată integral prin probele administrate în cadrul urmăririi penale și cele cercetate în cadrul ședinței de judecată. Martorul xxxxNUMExxxx, a declarat că activează în calitate de şef de post a IP Ştefan Vodă. Într­o zi de vară, aflîndu­se la serviciu în baza ordonanţei de efectuarea percheziţiei, autorizată de către Judecătoria Ştefan Vodă, împreună cu colaboratorii de poliţie xxxxNUMExxxx, xxxxNUMExxxx, xxxxNUMExxxx, xxxxNUMExxxx au efectuat o percheziţie la domiciliul unde locuieşte cet. xxxxNUMExxxx, din xxxxSATxxxx, r­nul Ştefan Vodă, pe motiv că din informaţii operative s­a aflat că ultimul păstra la domiciliu o armă de foc de model necunoscut. În urma efectuării percheziţiei la domiciliu menţionat mai sus, a fost depistat şi ridicat un pachet din polietilenă, în care se află o cantitate de plantă verde uscată asemănătoare cu cînepa şi în altă camera un pachet din polietilenă de culoare albastră străvezie în care se află o cantitate de seminţe asemănătoare cu seminţe de plante de mac. Nu ține minte cine a depistat aceste pachete. xxxxNUMExxxx, a declarat că, cunoaște de pachetele depistate, însă nu ține minte unde le­a pus. Instanța de judecată apreciază critic această declarație, ea fiind combatută prin declarațiile inculpatului și a martorilor

--------------------------------------------- Result 54 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

Prin sentinţa Judecătoriei xxxxORAS_SATxxxx din 20.05.201xxxxAPARTxxxx xxxxNUMExxxx a fost condamnată în baza art.217 alin.2, art.217 alin.xxxxAPARTxxxx lit.c), art.186 alin.2 lit.c, d CP, şi în baza art.84 alin.1, 85 CP i­a fost aplicată pedeapsa definitive de 6 ani închisoare cu ispăşirea pedepsei îi penitenciar pentru femei de tip închis. La data de 21.08.2014 condamnata a depus cerere îi instanţa de judecată, solicitînd executarea pedepsei în Penitenciarul nr.11 Bălţi. În motivarea cererii condamnata a invocat că, Penitenciarul nr.11 Bălţi corespunde tipului de penitenciar stabilit prin sentinţă şi aici va avea posibilitate de a participa activ la programele socio­culturale. Prin încheierea Judecătoriei Bălţi din 02.09.2014 cererea condamnatei xxxxNUMExxxx a fost respinsă ca fiind neîntemeiată. În motivarea soluţiei adoptate, instanţa a reţinut că reieşind din prevederile art.198 Cod de executare, condamnata nu este la prima abatere, execută pedeapsa în penitenciar de tip închis, din care considerente cererea urmează a fi respinsă. Nefiind de acord cu încheierea instanţei de fond, la data de 16.09.2014 şi respectiv 19.09.2014 condamnata xxxxNUMExxxx şi avocatul acesteia xxx au înaintat recurs, solicitînd admiterea acestuia, casarea încheierii din 02.09.2014 cu pronunţarea unei noi hotărîri prin care să fie admisă cererea condamnatei. În motivarea recursurilor au invocat că, cu încheierea instanţei din 02.09.2014 nu sunt de acord, o consideră neîntemeiată, deoarece Penitenciarul nr.11 din mun.Bălţi corespunde condiţiilor în care poate să­şi ispăşească pedeapsa xxxxNUMExxxx. Ea este de origine din or.xxxxORAS_SATxxxx. Fiul său minor la moment locuieşte în xxxxORAS_SATxxxx, care împreună cu rudele sale ar putea­o vizita mai uşor şi ajuta să treacă barierele psihologice de condamnat şi stările depresive în care se află. În ultima perioadă xxxxNUMExxxx nu are nici o încălcare de regim în penitenciar, se caracterizează pozitiv şi doreşte să participe la lucrările neremunerate şi activităţile cultural­educative organizate în penitenciar. Aceasta poate fi realizat doar prin schimbarea penitenciarului. În şedinţa instanţei de recurs avocatul xxx a susţinut recursul înaintat din motivele invocate, solicitînd admiterea acestuia. Condamnata în şedinţa instanţei de recurs nu s­a prezentat, depunînd la data de 18.0xxxxAPARTxxxx.2015 cerere prin care solicită să nu fie etapată la şedinţa de judecată, pe motiv de boală, fapt confirmat prin procesul­verbal de refuz anexat la materialele cauzei. Instanţa de recurs a considerat posibil de a examina cauza în lipsa condamnatei xxxxNUMExxxx. În instanţa de recurs procurorul a solicitat respingerea recursului înaintat ca nefondat. Reprezentantul Penitenciarului nr.11 Bălţi în şedinţa instanţei de recurs fiind citat legal, nu s­a prezentat, instanţa dispunînd examinarea cauzei în lipsa acestuia. Audiind participanţii la proces, verificînd argumentele invocate în recurs şi verificînd legalitatea şi temeinicia încheierii atacate, Colegiul penal ajunge la concluzia că recursul declarat urmează a fi respins ca fiind nefondat cu menţinerea încheierii instanţei de fond reieşind din următoarele considerente. Conform art.449 alin.(1) pct.1 lit.a) CPP, Judecînd recursul, instanţa adoptă una din următoarele decizii: respinge recursul, menţinînd hotărîrea atacată, dacă recursul este nefondat. Potrivit art.198 alin.(1) Cod de executare, pentru executarea lucrărilor de deservire gospodărească în izolatoarele de urmărire penală sînt lăsate, cu acordul lor scris şi la decizia şefului izolatorului de urmărire penală, persoanele condamnate cărora li s­a stabilit executarea pedepsei într­un penitenciar de tip semiînchis şi,

--------------------------------------------- Result 55 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

În una din zilele lunii septebrie 2014, aproximativ la ora 08.00, Gumeniuc Irina a pătruns în casa cet.Ceban Natalia, situată în s.Țambul XXXXXXXXX, de unde a sustras pe ascuns un inel din aur cu pietre mici cu greutatea de 3 grame cu prețul de 2000 lei, un lănțișor din aur cu greut grame cu prețul de 2000 lei, un lănțișor din aur cu greutatea de 1,5 grame cu prețul de 1000 lei, o cruce din aur cu greutatea de un gram cu prețul de o pereche de cercei cu greutatea de un gram și prețul de 800 lei, cauzînd în așa mod părții vătămate o daună materială în proporții considerabile î totală de 6600 lei. Tot ea, la 01septembrie 2014, în jurul orelor 0830­0900, continuînd activitatea infracțională, intenţionat, cu scopul sustragerii pe ascuns a bunurilor altei persoane, de profit, cu folosirea cheilor, a pătruns în casa cet. Onița Lidia Ivan, din satul Octeabrscoie, raionul XXXXXXXXX, de unde, pe ascuns, a sustras bijuterii din aur și inel bărbătesc din aur cu prețul de 3000 de lei, un lănţişor din aur cu preţul de 4000 lei, o brăţara de mînă din aur cu preţul de 3500 lei, două cruciuliţi din aur cu preţu lei, cîte 1750 de lei fiecare, patru inele din aur pentru femei cu preţul de 8000 lei, cîte 2000 de lei fiecare, o pereche de cercei din aur cu preţul de 3500 lei, un apar model Exilim, cu preţul de 3000 lei, un card bancar de la SA Banca de Economii pentru restabilirea cardului dat a achitat 1 euro, echivalentul la 20 de lei, cauzîndu­i un material considerabil în cuantum de 28520 lei. Tot ea, continuînd activitatea infracțională, la 11 octombrie 2014, aproximativ la ora 1900, urmărind scopul sustragerii bunurilor altei persoane, prin descuierea intrarea în casa de locuit a cet. Simac Anna Alexandr situat în satul Ţambula r. XXXXXXXXX, a pătruns în interior, de unde pe ascuns a sustras o verighetă din aur cu de 4,06g la preţul de 1500 lei, un ghiul (inel bărbătesc) din aur cu greutatea de 5,1g la preţul de 3000 lei, un lănţişor din aur cu greutatea de 6,52g la preţul de 4000 lei din aur cu greutatea de aproximativ 1g la preţul de 1000 lei, un lănţişor din aur cu greutatea de 1,67g la preţul de 2000 lei, un inel din aur cu greutatea de aproximativ 3 de 2000 lei şi un inel din aur cu greutatea de aproximativ 2g la preţul de 1500 lei, cauzîndu­i astfel părţii vătămate Simac Anna, o pagubă materială considerabilă în sum 15000 lei. Astfel, în perioada lunilor septembrie­octombrie 2014, Gumeniuc Irina a sustras bunuri ale altor persoane în sumă totală de 50120 lei, adică în mari. În ședința de judecată, inculpata Gumeniuc Irina, pînă la începerea cercetării judecătoreşti, a recunoscut în totalitate faptele indicate în rechizit recunoscut vina, nesolicitînd administrarea de probe noi, prin cerere scrisă personal, a solicitat examinarea cauzei penale în baza probelor admin urmărirea penală, pe care le recunoaște și asupra cărora nu are obiecții. Constatînd că probele administrate la urmărirea penală stabilesc fapta inculpatului,


--------------------------------------------- Result 56 ---------------------------------------------
[[1 (56%)]] --> [[[SKIPPED]]]

La data de 13.09.2013 a fost pornită urmărirea penală pe cauza dată, în baza elementelor infracţiunii prevăzute de art.361 alin.2 lit.b) Cod Penal, pe faptul că la data de 12.07.2011, aproximativ la orele 08:40, două persoane neidentificate de organul de urmărire penală, aflîndu­se în incinta Oficiului Cadastral Teritorial Bălţi filiala I.S.”CADASTRU”, amplasată pe str.M.Sadoveanu 1, avînd intenţia de falsificare a documentelor oficiale care­i acordă drepturi, cu ajutorul unui pix cu colorant albastru, a executat în rubrica „semnătura solicitantului” a cererii de înregistrare a ipotecii, asupra imobilului amplasat pe adresa: mun.Bălţi, str.xxx (pasaj) 7, o semnătura din numele cet.xxxxNUMExxxx , iar mai apoi, în aceeași zi a prezentat registratorului OCT Bălţi filiala Î.S.„CADASTRU” cererea nr.0300/11/11154 din 12.07.2011 de înregistrare a ipotecii asupra imobilului amplasat pe adresa: mun.Bălţi, xxx (pasaj) 7, unde ca proprietar figurează cet.xxxxNUMExxxx , adică au falsificat semnătura din numele solicitantului xxxxNUMExxxx. În urma investigării cazului dat, s­a constatat că, la data de 11.07.2011, între Banca Comercială „EuroCreditBank”SA şi „AGROMAGNAT"’ SRL, în persoana administratorului xxx, a fost încheiat contractul de credit nr.C.L.2­498 privind acordarea creditului bancar în sumă de 500000 lei, conform căruia „AGROMAGNAT” SRL asigură rambursarea în termenul stabilit a creditului, achitarea dobînzii şi altor plăţi aferente prin constituirea în favoarea băncii a garanţiilor şi anume a ipotecii bunului imobil, situat în mun.Bălţi, str.xxx166 ap.l19, ce reprezintă apartament compus din două odăi şi o suprafaţă locativă; a ipotecii terenului pentru construcţii, a casei de locuit individuală şi a construcţiei accesorii, toate fiind situate pe adresa mun.Bălţi, xxx pasaj 7. În aceeaşi zi, la 11.07.2011 a fost încheiat contractul de ipotecă între Barca Comercială „EuroCreditBank” S.A. şi cet.xxxxNUMExxxx, conform căruia ultimul instituie în favoarea. B.C. „EuroCreditBank” S.A. ipoteca asupra bunurilor sale şi anume a terenului pentru construcţii, a casei de locuit individuală şi a construcţiei accesorii, toate fiind situate pe adresa mun.Bălţi, xxx pasaj 7. Deci, pentru asigurarea obligaţiunilor faţă dc creditor de către xxx (administratorul „AGROMAGNAT” SRL) şi cet.xxxxNUMExxxx (tatăl lui xxx managerul „AGROMIAGNAT" SRL), a fost instituit creditul ipotecar asupra bunurilor imobile ce le aparțin şi anume: mun.xxxxORAS_SATxxxx, str.xxx 166 ap.19, respectiv mun.Bălţi, pasaj xxx 7, fiind încheiat contract de ipotecă cu fiecare dintre părţi. Conform pct.20 al contractului de ipotecă încheiat între BC ”EuroCreditBank”SA şi cet.xxxxNUMExxxx, prezentul contract urmează a fi înregistrat la Oficiul Cadastral Teritorial în a cărui rază teritorială este amplasat bunul imobil ipotecat, nefiind specificat de cine anume urmează a fi prezentat spre înregistrare la OCT. Deasemenea s­a constatat, că cet.xxx personal a prezentat contractul de ipotecă a bunului său imobil la OCT Bălţi, unde la 12.07.2011 a semnat în cererea de înregistrare a altor drepturi reale­ipotecare cu nr.0300/11/11153 asupra bunului imobil amplasat pe adresa: mun.Bălţi, str.xxx 166 ap.119. În aceeași zi, a fost semnată şi cererea de înregistrare a altor drepturi reale­ipotecare cu nr.0300/11/11154, asupra bunului imobil amplasat pe adresa: mun.Bălţi, pasaj xxx7. La momentul semnării ambelor cereri în incinta OCT Bălţi s­au aflat atît cet.xxx, cît şi companionul său de la ,.AGROMAGNAT” xxx. Conform raportului de expertiză nr.287 din 28.03.2014, semnătura executată în rubrica „data şi semnătura solicitantului” a cererii nr.0300/11/11154 din 12.07.2011

--------------------------------------------- Result 57 ---------------------------------------------
[[0 (100%)]] --> [[1 (51%)]]

xxxxNUMExxxx la 24.12.[[2014]], aproximativ la ora 23.30 minute, conducînd autoturismul de model “Ford [[Escort]]”, cu numărul de înmatriculare BLCE 271, în a s. Drăgăneşti r­l Sîngerei, a fost stopat de către colaborotorii de poliţie şi fiind suspectat în consum de băuturi alcoolice, a fost supus testării alcoolscopice cu ajutorul tehnic “Drager­[[Alcotest]] 6810”, fiind stabilită concentraţia vaporilor de alcool în aereul expirat de 0,52 mg/l, ceea ce conform art. 13412 alin. (3) din Codul penal, se stare de ebrietate alcoolică cu [[grad]] avansat. Fiind audiat în ședința de judecată, inculpatul xxxxNUMExxxx a recunoscut vina integral, [[declarînd]] că, la 24.12.2014, aproximativ pe la o conducea automobilul său de model „Ford [[Escort]]” cu numerele de înregistrare BL CE 271 din s. Serbeşti r. Floreşti de la nişte prieteni spre s. Drăgăneşti r­l Sîngerei. A apropierea s. Drăgăneşti a fost [[stopat]] de către o persoană care se afla lîngă un automobil, la început nu a observat că sunt colaboratorii de poliţie şi nu a stopat automobi era cu nişte prieteni. Apoi automobilul i­a urmărit şi deja ulterior a observat că sunt colaboratorii de poliţie fiindcă au aprins şi girofarul. El deja a stopat maşina. Col poliţiei rutiere i­au cerut să iasă din automobil şi să ridice mîinile sus, l­au [[urcat]] în automobillul poliţiei rutiere şi au [[mers]] la Inspectoratul de poliţie [[Sîngerei]]. Permis deţine, însă l­a pierdut. Colaboratorii i­au spus că este suspectat în conducerea mijlocului de transport în stare de ebrietate şi că trebuie să fie supus expertizei [[alcoosco]] la Inspectoratul de Poliţie Sîngerei a fost supus expertizei şi a [[suflat]] într­un aparat unde rezultatul a fost de 0,52 mg/l. Recunoaşte că a servit băuturi alcoolice înainte volanul automobilului. De cele întîmplate se căieşte sincer [[Pînă]] la începerea cercetării judecătoreşti, [[inculpatul]] a declarat, [[personal]] prin înscris [[autentic]], că recunoaşte săvîrşirea [[faptelor]] in rechizitoriu şi solicită ca judecata să se [[facă]] pe [[baza]] probelor administrate în faza de urmărire [[penală]]. Astfel, [[instanța]] de judecată prin în protocolară din 02 martie 2015, a [[acceptat]] ca judecata să se facă pe [[baza]] [[probelor]] administrate în [[faza]] de [[urmărire]] penală. Pe lîngă faptul că [[inculpatul]] xxxxNUMExxxx a [[recunoscut]] [[vina]], în [[ședința]] de judecată vinovăția acestuia este dovedită prin [[următoarele]] probe ­ raport privind circumstanţele comiterii infracţiunii (f.d. 3); ­ raport privind recepţionarea apelului telefonic (f.d. 5); ­ procesul­verbal privind constatarea faptei de conducere a mijlocului de transport în stare de ebrietate alcoolică (f.d. 6­7); ­ procesul­verbal de testare alcooloscopică (f.d. 9); ­ procesul­verbal al examinării medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate şi a naturii ei (f.d. 12­13); ­ declaraţiile martorului Bucliş Mihail Mihail, (f.d.18); ­ declaraţiile martorului Coşieru Oleg Alexandru, (f.d.19). Analizînd probele cercetate în ședința de judecată prin prisma prevederilor art.101 CPP, în virtutea cărora, fiecare probă urmează să fie apre punct de vedere al pertinenței, concludenței, utilității și veridicității ei, iar toate aspectele și în mod obiectiv, călăuzindu‐se de lege, se ajunge la con în ședința de judecată cu certitudine s‐a dovedit vinovăția inculpatului xxxxNUMExxxx în comiterea infracțiunii prevăzute la art.2641 alin.(1) Co adică conducerea mijlocului de transport de către o

xxxxNUMExxxx la 24.12.[[2104]], aproximativ la ora 23.30 minute, conducînd autoturismul de model “Ford [[Escrot]]”, cu numărul de înmatriculare BLCE 271, în a s. Drăgăneşti r­l Sîngerei, a fost stopat de către colaborotorii de poliţie şi fiind suspectat în consum de băuturi alcoolice, a fost supus testării alcoolscopice cu ajutorul tehnic “Drager­[[Alcotset]] 6810”, fiind stabilită concentraţia vaporilor de alcool în aereul expirat de 0,52 mg/l, ceea ce conform art. 13412 alin. (3) din Codul penal, se stare de ebrietate alcoolică cu [[gard]] avansat. Fiind audiat în ședința de judecată, inculpatul xxxxNUMExxxx a recunoscut vina integral, [[declaîrnd]] că, la 24.12.2014, aproximativ pe la o conducea automobilul său de model „Ford [[Escrot]]” cu numerele de înregistrare BL CE 271 din s. Serbeşti r. Floreşti de la nişte prieteni spre s. Drăgăneşti r­l Sîngerei. A apropierea s. Drăgăneşti a fost [[sotpat]] de către o persoană care se afla lîngă un automobil, la început nu a observat că sunt colaboratorii de poliţie şi nu a stopat automobi era cu nişte prieteni. Apoi automobilul i­a urmărit şi deja ulterior a observat că sunt colaboratorii de poliţie fiindcă au aprins şi girofarul. El deja a stopat maşina. Col poliţiei rutiere i­au cerut să iasă din automobil şi să ridice mîinile sus, l­au [[ucrat]] în automobillul poliţiei rutiere şi au [[mres]] la Inspectoratul de poliţie [[Sîngeeri]]. Permis deţine, însă l­a pierdut. Colaboratorii i­au spus că este suspectat în conducerea mijlocului de transport în stare de ebrietate şi că trebuie să fie supus expertizei [[alocosco]] la Inspectoratul de Poliţie Sîngerei a fost supus expertizei şi a [[sufalt]] într­un aparat unde rezultatul a fost de 0,52 mg/l. Recunoaşte că a servit băuturi alcoolice înainte volanul automobilului. De cele întîmplate se căieşte sincer [[Pnîă]] la începerea cercetării judecătoreşti, [[inculptaul]] a declarat, [[pesronal]] prin înscris [[auetntic]], că recunoaşte săvîrşirea [[fpatelor]] in rechizitoriu şi solicită ca judecata să se [[fcaă]] pe [[bzaa]] probelor administrate în faza de urmărire [[peanlă]]. Astfel, [[instațna]] de judecată prin în protocolară din 02 martie 2015, a [[acecptat]] ca judecata să se facă pe [[bzaa]] [[porbelor]] administrate în [[fzaa]] de [[umrărire]] penală. Pe lîngă faptul că [[incuplatul]] xxxxNUMExxxx a [[recunocsut]] [[vnia]], în [[șeidnța]] de judecată vinovăția acestuia este dovedită prin [[urămtoarele]] probe ­ raport privind circumstanţele comiterii infracţiunii (f.d. 3); ­ raport privind recepţionarea apelului telefonic (f.d. 5); ­ procesul­verbal privind constatarea faptei de conducere a mijlocului de transport în stare de ebrietate alcoolică (f.d. 6­7); ­ procesul­verbal de testare alcooloscopică (f.d. 9); ­ procesul­verbal al examinării medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate şi a naturii ei (f.d. 12­13); ­ declaraţiile martorului Bucliş Mihail Mihail, (f.d.18); ­ declaraţiile martorului Coşieru Oleg Alexandru, (f.d.19). Analizînd probele cercetate în ședința de judecată prin prisma prevederilor art.101 CPP, în virtutea cărora, fiecare probă urmează să fie apre punct de vedere al pertinenței, concludenței, utilității și veridicității ei, iar toate aspectele și în mod obiectiv, călăuzindu‐se de lege, se ajunge la con în ședința de judecată cu certitudine s‐a dovedit vinovăția inculpatului xxxxNUMExxxx în comiterea infracțiunii prevăzute la art.2641 alin.(1) Co adică conducerea mijlocului de transport de către o

--------------------------------------------- Result 58 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Inculpatul xxxxNUMExxxx Nichita, la data de 30.10.2013, pe la orele 16.00, în rîpa din preajma s. Lalova rl. Rezina, în timpul unui conflict spantan apărut pe fondalul relaţiilor ostile persistante i­a aplicat cet. Josan Victor, multiple lovituri cu pumnii în regiunea feţii, în rezultatul cărora lui Josan Igor i­au fost provocate, potrivit raportului de expertiză medico­ legală nr. 397 D din 27.11.2013, vătămări corporale MEDII sub formă de fractură a mandibulei în regiunea unghiului pe dreapt, comoţie cerebrală, ce duc la o dereglare a sănătăţii de lungă durată. Inculpatul xxxxNUMExxxx Nichita pînă la începerea cercetării judecătoreşti a declarat personal prin înscris autentic, că recunoaşte săvîrşirea faptelor indicate în rechizitoriu şi solicită ca judecata să se facă pe baza probelor administarte în faza de urmărîre penală pe care le cunoaşte şi asupra cărora nu are obiecţii. Procuror şi avocat sînt de acord cu cererea inculpatului xxxxNUMExxxx Nichita. Prin încheierea din 03.04.2014, instanţa a admis inscrisul autentic depus de către inculpatul xxxxNUMExxxx Nichita, reieşind din fapt că din probele administrate rezultă că faptele lu sînt stabilite şi sînt suficiente date cu privire la persoana sa pentru a permite stabilirea unei pedepse. Fiind audiat în calitate de martor, inculpatul xxxxNUMExxxx Nichita a declarat că este originar şi locuitor al s. Lalova r. Rezina, are o fiică pe nume Iancevscaia Aliona şi fiul xxxxNUMExxxxitalii, care la moment locuieşte în r. Ocniţa. În anul 2000 consăteanul xxxxCUSTOM1xxxx l­a bătut pe fiul Vitalii şi de atunci sunt în relaţii ostile. Pe data de 30.10.2013, a plecat pe imaşul din preajma satului ca să­şi aducă acasă caii; între timp pe rîpă se apropia de sat cireada cu bovine, ce era condusă de xxxxCUSTOM1xxxx şi Caraman Ion; ultimul mergea în fruntea cirezii. El l­a întrebat pe Caraman Ion de ce vitele sunt flămînde, la ce dînsul i­a răspuns să­l întrebe pe Josan Igor, care de fapt era cu rîndul. Între timp de dînsul s­a apropiat Josan Igor, care s­a interesat de ce­i nemulţumit, acesta după aprecierele lui era în stare de ebrietate, la ce i­a reproşat că vitele sunt flămînde. Au început a se contra verbal şi şi­a mînat vaca spre casă, încît locuieşte în apropiere de rîpă şi l­a strigat pe fiul xxxxNUMExxxxitali ca dînsul se preia vaca, iar el să aducă caii. Josan Igor mînînd vitele cu o vergea de lemn se apropia de el, rotind­o. xxxxNUMExxxx a intenţionat să­l apuce de vergea, dar acela a fugit la vale; el a mers după dînsul şi­n rîpă acela iar rotea vergeau spre CaramanV, lovindu­l peste mîina stîngă, însă xxxxNUMExxxx l­a apucat de vergea şi i­a luat­o din mîină, după ce l­a lovit de două ori cu pumnul în regiunea feţei, apoi peste corp; la fel l­a lovit pe acesta şi cu vergeaua peste corp. Între timp la faţa locului a apărut fiul xxxxNUMExxxxitali, care s­a implicat în conflict şi i­a despărţit; fiul nu l­a lovit pe Josan Igor niciodată şi nici nu l­a imobilizat pe acesta, pur simplu dînsul a intervenit între ei, dispersîndu­i. Bătaia s­a finisat şi xxxxNUMExxxxitali i­a luat vergeaua din mîini şi i­a dat­o lui Josan

--------------------------------------------- Result 59 ---------------------------------------------
[[1 (86%)]] --> [[[FAILED]]]

Prin sentința nominalizată xxxxNUMExxxx a fost recunoscută culpabilă și condamnataă pentru, că în luna decembrie 2008 prin înțelegere prealabilă și împreună cu Iftodi Olesea, încurajînd­o și convingînd­o pe xxxNUMExxxcă va obține venituri considerabile pe cont propriu ca rezultat al practicării prostituției în Turcia, trezindu­i interesul față de această îndeletnicire, îndemnînd­o și încurajînd­ o, au determinat­o să­și dea consimțămîntul de a practica acest gen de activitate. Respectivele acțiuni a inculpatei fiind încadrate de către instanța de fond la art. 220 alin. (1) Cod penal cu calificativele ”îndemnul și determinarea la prostituție, înlesnirea practicii prostituției, tragerea de foloase de pe urma practricării prostituției” (f.d. 246­247). Totodată, prin învinuirea formulatră în rechizitoriu, xxxxNUMExxxx a fost acuzată de faptul, că: ”indentificînd victima, dîndu­ și seama că prin acțiunile sale recrutează, transportă și adăpostește o persoană în scop de expluatare sexuală comercială și dorind aceasta, atentînd la lupta statelor pentru prevenirea și reprimarea acestor forme de parazitism social josnic (concretizate în Convenția internațională pentru suprimarea traficului de femei și copii, adoptată la Geneva la 20.09.1921, Convenția internațională privitoare la reprimarea traficului de dfemei majore din 11.10.1933, Convenția pentru repprimarea traficvului de ființe umane și expluatării prostituării altuia, adoptată de Adunarea Gennerală ONU la 22.12.1949 și Convenția privind lupta cu traficul de oameni cu expluatarea prostituției de către terșe persoane din 21.03.1980), în luna decembrie 2008, la o dată nestabilită de către organul de urmărire penală, intenționat din interes material, prin intermediul Olesei Iftodii, ce se afla în or. Șoldănești, str. C. Stamati, 16, la domiciliul xxxNUMExxx, urmărind scopul expluatării sexuale comerciale, prin înșelăciune manifestată prin promisiunea de angajare în calitate de prostituată în or. Istambul, Turcia, prin abuz de vulnerabilitate, manifestată prin situația financiară grea și apartenența la categoria familiilor social­vulnerabile, a recrutat­o pe cea din urmă cu consimțămîntul dat de ea. Ulterior, întru atingerea scopului infracțional, xxxxNUMExxxx a organizat plecarea xxxNUMExxx și a xxxxNUMExxx în Turcia, achitîndu­le plata pentru deplasare în sumă de 2000 dol. SUA, adăpostindu­le în locuința sa din or. Antalia, unde acestea au practicat prostituția în următoarele două luni.” Acuzarea a încădrat respectivele acțiuni a inculpatei xxxxNUMExxxx la art. 165 alin. (1) lit. b), c) Cod penal cu calificativele ”traficul de ființe umane, manifestat prin recrutarea, transportarea, adăpostirea persoanei cu consimțămîntul acesteea, în scop de expluatare sexuală comercială, săvîrșită prin înșelăciune sau abuz de vulnerabilitate” (f.d. 212­213). Învinuirea dată a fost susținută de către acuzatorul Ion Mînza și în instanța de fond, cu propunearea condamnării inculpatei xxxxNUMExxxx pe art. 165 alin. (1) lit. b), c) Cod penal, stabilindu­i pedeapsa închisorii pe un termen de cinci ani cu aplicarea dispozițiilor art. 90 Cod penal, dispunîndu­se executarea ei condiționată pe un termen de probă de patru ani (f.d. 251­255). Dispunînd reîncadrarea acțiunilor inculpatei xxxxNUMExxxx de la componența traficului de ființe umane la cea de proxenitism, instanța a concluzionat lipsa probelor ce ar demonstrează vinovăția formulată, considerînd că acțiunile ei urmează a fi încadrate la art. 220 alin. (1) Cod penal, așa precum a fost condamnată și Iftodii Olesea, printr­o sentință definitivă fiind constatat, că ea a participat în complicitate cu inculpata xxxxNUMExxxx (f.d.134­136). Legalitatea și

[Succeeded / Failed / Skipped / Total] 24 / 26 / 10 / 60: 100%|██████████| 50/50 [09:58<00:00, 11.98s/it]

--------------------------------------------- Result 60 ---------------------------------------------
[[0 (99%)]] --> [[1 (63%)]]

[[Inculpatul]] xxxxNUMExxxx activînd în calitate de inspector­şofer (grupa operativă) al Dispetceratului pază al Filialei [[Rezina]] Întreprinderii de Stat „Servicii Pază Republicii Moldova , în perioada de timp începînd cu luna decembrie 2010, susţinînd că are influenţă asupra unor funcţionari din cadrul Comisariatului raional de poliţie [[Rezin]] Procuratura raionului Rezina , în gestiunea şi conducerea cărora se afla cauza penală nr.[[20100297]] pornită în privinţa cet.xxxxCUSTOM2xxxx Mihai, Muntean Vasi [[xxxxCUSTOM1xxxx]] Diana şi xxxxCUSTOM1xxxx Alexei conform art.217/1 al.(4) lit.d) CP, în scopul de ai [[detrmina]] pe aceştea la îndeplinirtea unor acţiuni ce într obligaţiunile de serviciu legate de încetarea urmărirei penale pe cauza penală dată , prin extorcare a pretins bani în sumă de 800 dolari SUA de la cet.xxxxCUSTOM1x Alexei , care ulterior la 05.01.2011 aproximativ la orele 14.44 în or.[[Rezina]] pe str.Şciusev nr.5 în faţa Centrului Medicilor de famile din or.[[Rezina]] i­a primit pentru sine d ultimul, fiind reţinut în flagrant delict. Fapta dată prejudiciabilă a fost recunoscută de [[către]] [[inculpatul]] [[xxxxNUMExxxx]] în acordul de recunoaştere a vinovaţiei încheiat la 27 ianuarie 2011 între dînsu procurorul în serviciul Nord al Procuraturii AnticorupţiexxxxNUMExxxx Dulghier , însoţit de apărătorulxxxxNUMExxxx Rotari. [[Vina]] inculpatului xxxxNUMExxxx în comiterea infracţiunii se dovedeşte pe deplin prin depoziţiile lui recunoscătoare date în şedinţa de judecată din 02.03.2011 şi probele prezentate de către procuror şi recunoscute de către inculpatul , şi anume : ­ proces­verbal de primire a denunţului de la cet.xxxxCUSTOM1xxxx Alexei D. din 04.01.2011 ( p.d.5­6); ­ proces – verbal privind marcarea bancnotelor în sumă totală de 800 dolari SUA din 05.01.2011 ( p.d.16); ­raport de expertiză judiciară fizico­chimice a bancnotelor marcate nr.038 din 10.01.2011 (p.d.27­31); ­ proces­verbal de ridicare a dictofonului digital şi a minivideocamerei digitale de la xxxxCUSTOM1xxxx Alexei din 05.01.2011 ( p.d.36 ); ­ proces – verbal din 05.01.2011 de efectuare a interceptării şi înregistrării comunicărilor între xxxxCUSTOM1xxxx Alexei şi xxxxNUMExxxx şi stenograma intercept comunicărilor ( p.d.37­39); ­ proces­verbal de percheziţie corporală a lui xxxxNUMExxxx. din 05.01.2011 (p.d.50­51); ­ proces­verbal de examinare a obiectelor şi a documentelor ridicate în procesul urmărirei penale şi în procesul percheziţiei corporale a lui xxxxNUMExxxx. şi ordonanţa recunoaştere şa ataşare la dosar a mijloacelor materiale de probă ( p.d.53­56); ­ copiile materialelor din dosarul penal nr.20100297 pornit în privinţa cet.xxxxCUSTOM2xxxx Mihai, Muntean Vasile , xxxxCUSTOM1xxxx Diana şi xxxxCUSTOM1x Alexei conform art.217/1 al.(4) lit.d) CP ( p.d.62­159). Instanţa de judecată găseşte că probele prezentate dovedesc vina inculpatului xxxxNUMExxxx în comiterea infracţiunii ce i se impută şi că el a semnat acordul recunoaştere a vinovaţiei binevol, prin voinţa liberă,fără a fi impus de cineva. Acţiunile inculpatului sînt just încadrate în baza art.326 al.(1) CP – traficul de influenţă , adică primirea de bani, personal pentru sine săvîrşită intenţionat de cătr persoană care are influenţă sau care susţine că are influenţă asupra unui funcţionar, în scopul de a­l face să îndeplinească ori să nu îndeplinească acţiuni ce intră în obligaţiil de serviciu, indiferent dacă asemenea acţiuni au fost sau nu săvîrşite. La stabilirea măsurii de pedeapsă instanţa ia în consideraţie gradul şi nivelul pericolului social a infracţiunii săvîrşită , personalitatea inculpatului , circumstanţele agravează şi

[[Incuplatul]] xxxxNUMExxxx activînd în calitate de inspector­şofer (grupa operativă) al Dispetceratului pază al Filialei [[Reznia]] Întreprinderii de Stat „Servicii Pază Republicii Moldova , în perioada de timp începînd cu luna decembrie 2010, susţinînd că are influenţă asupra unor funcţionari din cadrul Comisariatului raional de poliţie [[Reizn]] Procuratura raionului Rezina , în gestiunea şi conducerea cărora se afla cauza penală nr.[[20100927]] pornită în privinţa cet.xxxxCUSTOM2xxxx Mihai, Muntean Vasi [[xxxCxUSTOM1xxxx]] Diana şi xxxxCUSTOM1xxxx Alexei conform art.217/1 al.(4) lit.d) CP, în scopul de ai [[dtermina]] pe aceştea la îndeplinirtea unor acţiuni ce într obligaţiunile de serviciu legate de încetarea urmărirei penale pe cauza penală dată , prin extorcare a pretins bani în sumă de 800 dolari SUA de la cet.xxxxCUSTOM1x Alexei , care ulterior la 05.01.2011 aproximativ la orele 14.44 în or.[[Reizna]] pe str.Şciusev nr.5 în faţa Centrului Medicilor de famile din or.[[Reznia]] i­a primit pentru sine d ultimul, fiind reţinut în flagrant delict. Fapta dată prejudiciabilă a fost recunoscută de [[ctăre]] [[inclupatul]] [[xxxNxUMExxxx]] în acordul de recunoaştere a vinovaţiei încheiat la 27 ianuarie 2011 între dînsu procurorul în serviciul Nord al Procuraturii AnticorupţiexxxxNUMExxxx Dulghier , însoţit de apărătorulxxxxNUMExxxx Rotari. [[Vnia]] inculpatului xxxxNUMExxxx în comiterea infracţiunii se dovedeşte pe deplin prin depoziţiile lui recunoscătoare date în şedinţa de judecată din 02.03.2011 şi probele prezentate de către procuror şi recunoscute de către inculpatul , şi anume : ­ proces­verbal de primire a denunţului de la cet.xxxxCUSTOM1xxxx Alexei D. din 04.01.2011 ( p.d.5­6); ­ proces – verbal privind marcarea bancnotelor în sumă totală de 800 dolari SUA din 05.01.2011 ( p.d.16); ­raport de expertiză judiciară fizico­chimice a bancnotelor marcate nr.038 din 10.01.2011 (p.d.27­31); ­ proces­verbal de ridicare a dictofonului digital şi a minivideocamerei digitale de la xxxxCUSTOM1xxxx Alexei din 05.01.2011 ( p.d.36 ); ­ proces – verbal din 05.01.2011 de efectuare a interceptării şi înregistrării comunicărilor între xxxxCUSTOM1xxxx Alexei şi xxxxNUMExxxx şi stenograma intercept comunicărilor ( p.d.37­39); ­ proces­verbal de percheziţie corporală a lui xxxxNUMExxxx. din 05.01.2011 (p.d.50­51); ­ proces­verbal de examinare a obiectelor şi a documentelor ridicate în procesul urmărirei penale şi în procesul percheziţiei corporale a lui xxxxNUMExxxx. şi ordonanţa recunoaştere şa ataşare la dosar a mijloacelor materiale de probă ( p.d.53­56); ­ copiile materialelor din dosarul penal nr.20100297 pornit în privinţa cet.xxxxCUSTOM2xxxx Mihai, Muntean Vasile , xxxxCUSTOM1xxxx Diana şi xxxxCUSTOM1x Alexei conform art.217/1 al.(4) lit.d) CP ( p.d.62­159). Instanţa de judecată găseşte că probele prezentate dovedesc vina inculpatului xxxxNUMExxxx în comiterea infracţiunii ce i se impută şi că el a semnat acordul recunoaştere a vinovaţiei binevol, prin voinţa liberă,fără a fi impus de cineva. Acţiunile inculpatului sînt just încadrate în baza art.326 al.(1) CP – traficul de influenţă , adică primirea de bani, personal pentru sine săvîrşită intenţionat de cătr persoană care are influenţă sau care susţine că are influenţă asupra unui funcţionar, în scopul de a­l face să îndeplinească ori să nu îndeplinească acţiuni ce intră în obligaţiil de serviciu, indiferent dacă asemenea acţiuni au fost sau nu săvîrşite. La stabilirea măsurii de pedeapsă instanţa ia în consideraţie gradul şi nivelul pericolului social a infracţiunii săvîrşită , personalitatea inculpatului , circumstanţele agravează şi



+-------------------------------+--------+
| Attack Results                |        |
+-------------------------------+--------+
| Number of successful attacks: | 24     |
| Number of failed attacks:     | 26     |
| Number of skipped attacks:    | 10     |
| Original accuracy:            | 83.33% |
| Accuracy under attack:        | 43.33% |
| Attack success rate:          | 48.0%  |
| Average perturbed word %:     | 1.83%  |
| Average num. words per input: | 521.1  |
| Avg num queries:              | 679.18 |
+-------------------------------+--------+

[<textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c1c1ee0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c122690>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7ca02750>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7ca31a60>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d3d1fd0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c8d6ab0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c8eeae0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c19c530>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8c19f6b0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c4e28d0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dc3e360>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c51afc0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7dbea360>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d6cb680>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d5e7590>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d5e4800>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7da49760>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7de6b7d0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d842060>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d309700>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d5e74a0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c35e480>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d9579b0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8c19c770>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c95b830>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c7db290>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d8016a0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d358800>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffecfba23f0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c6898e0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a109a510>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c376f60>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c6caf90>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dee9550>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c5fc950>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d93ef90>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x7002a1a1a9f0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7dc8dd00>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d38f980>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffecfc74980>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x7002a0283380>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c956630>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d953950>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c38e960>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a32d7bf0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x7002a356c2c0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c3fcd10>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7da8cc20>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d40bfb0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c8c2db0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dec6510>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d4ffe60>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d420c80>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dcfcef0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c8b7110>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7c8b7d70>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a04035c0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7da250a0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d4202f0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7c886900>]

In [33]:
# 6. Format dataset
attack_samples = []
for item in val_raw.select(range(200)):
    truncated_text = " ".join(item["text"].split()[:512]) 
    attack_samples.append((truncated_text, int(item["label"])))
textattack_dataset = Dataset(attack_samples)

# 7. Force execution over a wider evaluation block to confirm the ~20% rate
attack_args = AttackArgs(
    num_examples=100, # Evaluates until it gets 30 valid samples to build a stable metric
    attack_n=True
)

attacker = Attacker(attack, dataset=textattack_dataset, attack_args=attack_args)
attacker.attack_dataset()

Attack(
  (search_method): GreedyWordSwapWIR(
    (wir_method):  unk
  )
  (goal_function):  UntargetedClassification
  (transformation):  WordSwapNeighboringCharacterSwap(
    (random_one):  True
  )
  (constraints):
    (0): RepeatModification
    (1): StopwordModification
  (is_black_box):  True
)

[Succeeded / Failed / Skipped / Total] 0 / 1 / 0 / 1:   1%|          | 1/100 [00:13<22:58, 13.92s/it]

--------------------------------------------- Result 1 ---------------------------------------------
[[1 (85%)]] --> [[[FAILED]]]

xxxxNUMExxxx, pretinzînd că este avocata xxxxNUMExxxx, care activează în baza licenței nr. 2295 din 21.12.2011, urmărind scop de profit, prin înșelăciune și abuz de încredere, a încheiat contract de asistență juridică, nr. 26 din 16.01.2014, cu xxxxNUMExxxx, succesorul părții vătămate pe cauza penală nr. 2013320554, de învinuire a lui Petcu Viorel, în comiterea infracțiunii prevăzute de art. 145 alin. (1) Cod Penal, și a prezentat în instanța de judecată, mandatul nr. 0474957 din 16.01.2014, prin care s­a împuternicit să acorde lui xxxxNUMExxxx asistență juridică în toate instanțele de judecată, dobîndind ilicit de la ultimul mijloace bănești în sumă de 5000 lei. În cadrul părţii pregătitoare a şedinţei de judecată, partea vătămată xxxxNUMExxxx a depus cerere prin care a solicitat încetarea procesului penal din motivul că s­a împăcat cu inculpata xxxxNUMExxxx şi careva pretenţii faţă de ea nu are. Inculpata xxxxNUMExxxx vina în comiterea infracţiunii încriminate a recunoscut­o integral, de asemenea a depus cerere, prin care a solicitat încetarea procesului penal în legătură că s­a împăcat cu partea vătămată xxxxNUMExxxx, paguba materială fiind restituită integral. Vina inculpatei xxxxNUMExxxx în comiterea faptei prejudiciabile mai este confirmată prin: procesul­verbal cu declaraţiile părții vătămate xxxxNUMExxxx (f. d.71), care a declarat că 19 septembrie 2013, a fost omorît fiul U.M.. Pe cazul dat a fost intentată o cauză penală în cadrul căreia a fost recunoscut în calitate de succesor al părții vătămate. Fiica O., care locuiește în Federația Rusă, i­a comunicat că are o prietenă, care activează în calitate de avocat în mun. Chișinău și poate să­l ajute în instanța de judecată. După discuția cu fiica, s­a întîlnit cu xxxxNUMExxxx (la acel moment nu cunoştea numele ei adevărat), cu care a semnat un contract, potrivit căruia ultima se angaja s­i apere interesele. În instanța de judecată persona în cauză s­a prezentat ca fiind avocatul xxxxNUMExxxx. Pentru serviciile acordate i­a achitat suma de 5000 lei. Ulterior, a plecat în Federația Rusă, solicitînd în baza cererii examinarea cauzei în lipsa sa, interesele în continuare urmînd a­i fi apărate de către avocat. În timp ce se afla în Federația Rusă, a aflat că persoana cu care a încheiat contract de asistență juridică, nu este avocat și în instanța de judecată s­a prezentat din numele altei persoane. La revenirea în Republica Moldova, a aflat că persoana în cauză este xxxxNUMExxxx. Ultima i­a restituit integral paguba pricinuită și careva pretenții față de ea nu are; procesul­verbal cu declaraţiile martorului xxxxNUMExxxx (f. d.73), care a declarat că, activează în calitate de președinte al Centrului de Investigații și Apărare a Drepturilor Omului. Avocatul xxxxNUMExxxx este în contract de colaborare cu centrul, din care motiv toate scrisorile, răspunsurile și citațiile ce țin de dosarele sale, le deschide, le citește și le înregistrează în registru de evidență. În ceea ce privește cealaltă corespondență, doar semnează avizul de recepție, fără a o deschide. Scrisoarea din 19.05.2014, expediată în adresa avocatului xxxxNUMExxxx, a primit­o, iar ulterior i­a transmis­o ultimei; procesul­verbal cu declaraţiile martorului xxxxNUMExxxxxxxxNUMExxxxu (f. d.74­75), care a declarat că, activează în calitate de avocat în mun. Chișinău. La 14.01.2014, i­a transmis lui xxxxNUMExxxx, mandatul nr. 0474957 din

[Succeeded / Failed / Skipped / Total] 1 / 1 / 0 / 2:   2%|▏         | 2/100 [00:23<19:27, 11.92s/it]

--------------------------------------------- Result 2 ---------------------------------------------
[[1 (98%)]] --> [[0 (50%)]]

[[Prin]] sentinţa nominalizată xxxxNUMExxxx a fost [[condamnat]] [[pentru]], că în noaptea de 08.10.2012, intenționat, cu scopul sustragerii bunurilor altei persoane, aflîndu­se în casa lui G R de pe str.r.din or.[[xxxxORAS_SATxxxx]], a atacat­o pe G R cu un cuțit de bucătărie și i­a aplicat acesteia mai multe lovituri în regiunea [[toracelui]] și abdomenului cauzîndu­i astfel leziuni corporale grave periculoase pentru viață sub formă de plagă [[nepenetrantă]] la peretele abdominal anterior pe stînga cu dimensiunile 2,5 cm x 0,8 cm și [[adîncimea]] de 2,3 cm, trei plăgi [[nepetetrante]] în regiunea [[toracelui]] pe stînga la nivelul intercostal 3­5 linia anatomică [[parasternală]] cu dimensiunile 1,6 cm x 0,5 cm, 1,8 cm x0,5 cm, 2,9 cm x 0,7 cm și adfîncimea de pînă la 1,8 cm, o plagă penetrabtă în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică [[parasternală]] amplasată inferior la glanda [[mamară]] cu dimensiunile 4,6 cm x 1,3 cm cu lezarea lobului superior a pulmonului stîng pe suprafața anterior laterală stînga, hematorox masiv pe stînga, două plăgi tăiate la degetele patru și cinci a mîinii stîngi la falanga distală cu dimensiunile de 1,1 x 0,2 cm și 1,5 x 0,2 cm, [[excoreație]] în regiunea [[zigomatică]] stînga în urma cărora GR a decedat pe loc, luînd din casă un telefon mobil de model „” cu prețul de 600 lei, un lanț din aur cu greutatea de 19 gr. la prețul de 13680 lei și un pandativ din aur cu greutatea de 2 gr. la prețul de 1440 lei. Tot el, în [[noaptea]] de 08.10.2012, aproximativ în jurul orelor 03:00, fiind în stare de [[ebrietate]] alcoolică, aflîndu­se în lociunța cet.G R, asmplasată în orașul xxxxORAS_SATxxxx, str., [[intenționat]], urmărind scopul de profit, de sustragere a bunurilor altei persoane, avînd în mînă un cuțit de bucătărie, care l­a utilizat în calitate de armă, aplicînd o violență periculoasă pentru viața și sănătatea persoanei agresate, a atacat gazda casei, lovind­o în repetate rînduri cu pumnul, piciorul, precum și cu cuțitul în regiunea toracelui și abdomenului, pricinuindu­i lui G R leziuni corporale Grave periculoase pentru viața persoanei sub formă de plagă nepenetrantă la peretele abdominal anterior pe stînga cu dimensiunile 2,5 cm x 0,8 cm și adîncimea 2,3 cm, trei plăgi nepenetrante în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică parasternală, cu dimensiunile 1,6 cm x 0,5 cm, 1,8 cm x 0,5 cm, 2,9 cm x 0,7 cm și adîncimea de pînă la 1,8 cm, o plagă penetrantă în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică parasternală amplasată inferior la glnda mamară cu dimensiunile 4,6 cm x 1,3 cm cu lezarea lobului superior a pulmonului stîng pe suprafața anterioar – laterală stînga, hematorox masiv pe stînga, două plăgi tăiate la degetele 4 și 5 a mînei stîngi la falanga distală cu dimensiunile de 1,1 x 0,2 cm și 1,5 x 0,2 cm, excoreație în regiunea zigomatică stînga, după care în mod deschis a sustras de la victimă un telefon mobil de model „ la prețul de 600 lei, un lanț din aur cu greutatea de 19 grame la preț de 13680 lei și un

[[Pirn]] sentinţa nominalizată xxxxNUMExxxx a fost [[condamant]] [[pnetru]], că în noaptea de 08.10.2012, intenționat, cu scopul sustragerii bunurilor altei persoane, aflîndu­se în casa lui G R de pe str.r.din or.[[xxxxORASS_ATxxxx]], a atacat­o pe G R cu un cuțit de bucătărie și i­a aplicat acesteia mai multe lovituri în regiunea [[toracleui]] și abdomenului cauzîndu­i astfel leziuni corporale grave periculoase pentru viață sub formă de plagă [[nepenterantă]] la peretele abdominal anterior pe stînga cu dimensiunile 2,5 cm x 0,8 cm și [[adînciema]] de 2,3 cm, trei plăgi [[npeetetrante]] în regiunea [[troacelui]] pe stînga la nivelul intercostal 3­5 linia anatomică [[paratsernală]] cu dimensiunile 1,6 cm x 0,5 cm, 1,8 cm x0,5 cm, 2,9 cm x 0,7 cm și adfîncimea de pînă la 1,8 cm, o plagă penetrabtă în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică [[paarsternală]] amplasată inferior la glanda [[mmaară]] cu dimensiunile 4,6 cm x 1,3 cm cu lezarea lobului superior a pulmonului stîng pe suprafața anterior laterală stînga, hematorox masiv pe stînga, două plăgi tăiate la degetele patru și cinci a mîinii stîngi la falanga distală cu dimensiunile de 1,1 x 0,2 cm și 1,5 x 0,2 cm, [[excoerație]] în regiunea [[zigoamtică]] stînga în urma cărora GR a decedat pe loc, luînd din casă un telefon mobil de model „” cu prețul de 600 lei, un lanț din aur cu greutatea de 19 gr. la prețul de 13680 lei și un pandativ din aur cu greutatea de 2 gr. la prețul de 1440 lei. Tot el, în [[noatpea]] de 08.10.2012, aproximativ în jurul orelor 03:00, fiind în stare de [[ebriettae]] alcoolică, aflîndu­se în lociunța cet.G R, asmplasată în orașul xxxxORAS_SATxxxx, str., [[intențoinat]], urmărind scopul de profit, de sustragere a bunurilor altei persoane, avînd în mînă un cuțit de bucătărie, care l­a utilizat în calitate de armă, aplicînd o violență periculoasă pentru viața și sănătatea persoanei agresate, a atacat gazda casei, lovind­o în repetate rînduri cu pumnul, piciorul, precum și cu cuțitul în regiunea toracelui și abdomenului, pricinuindu­i lui G R leziuni corporale Grave periculoase pentru viața persoanei sub formă de plagă nepenetrantă la peretele abdominal anterior pe stînga cu dimensiunile 2,5 cm x 0,8 cm și adîncimea 2,3 cm, trei plăgi nepenetrante în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică parasternală, cu dimensiunile 1,6 cm x 0,5 cm, 1,8 cm x 0,5 cm, 2,9 cm x 0,7 cm și adîncimea de pînă la 1,8 cm, o plagă penetrantă în regiunea toracelui pe stînga la nivelul intercostal 3­5 linia anatomică parasternală amplasată inferior la glnda mamară cu dimensiunile 4,6 cm x 1,3 cm cu lezarea lobului superior a pulmonului stîng pe suprafața anterioar – laterală stînga, hematorox masiv pe stînga, două plăgi tăiate la degetele 4 și 5 a mînei stîngi la falanga distală cu dimensiunile de 1,1 x 0,2 cm și 1,5 x 0,2 cm, excoreație în regiunea zigomatică stînga, după care în mod deschis a sustras de la victimă un telefon mobil de model „ la prețul de 600 lei, un lanț din aur cu greutatea de 19 grame la preț de 13680 lei și un

[Succeeded / Failed / Skipped / Total] 1 / 2 / 0 / 3:   3%|▎         | 3/100 [00:38<20:32, 12.71s/it]

--------------------------------------------- Result 3 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Prin sentinţa Judecătoriei Soroca din 21.10.2004 x a fost condamnat în baza art.172 al.(3) pct.c) Cod penal RM la pedeapsă sub formă de 15 ani închisoare în peniteciar de tip închis. Începutul termenului –03.09.2004, sfîrşitul termenului ­02.09.2019. La data de 28.06.2016 șeful­adjunct al Penitenciarului nr.6 Soroca Cebotari Alexandru a înaintat în instanța de judecată demers, prin care a solicitat examinarea posibilității liberării condiționate de pedeapsă înainte de termen a condamnatului x. În motivarea demersului a indicat, că condamnatul x a ispășit ¾ din pedeapsa stabilită în conformitate cu legislația în vigoare, se caraterizează satisfăcător, pe perioada executării pedepsei a fost stimulat de două ori, a fost sancționat disciplinar o singură dată cu mustrare la data de 21.12.2005, sancțiune care la moment este stinsă, anterior a participat la muncile neremunerate, prejudiciul material lipsește și menține relațiile cu rudele. Prin încheierea Judecătoriei Soroca din XXXXXXXXX s­a dispus respingerea demersului administrației Penitenciarului nr.6 Soroca privind liberarea condiționată de pedeapsă înainte de termen a condamnatului x ca fiind neîntemeiat. Împotriva încheierei nominalizate în termen a declarat recurs condamnatul x, care nu este de acord cu încheierea instanței de fond. În motivarea recursului a indicat că a executat deja 11 ani din pedeapsa stabilită, este bonav de tuberculoză de formă deschisă și nu poate lucra din cauza bolii de care suferă. Solicită admiterea recursului, cu aplicarea în privința sa a prevederilor art.91 Cod penal RM și liberarea condiționată de pedeapsă înainte de termen. În instanţa de recurs condamnatul x a susținut recursul declarat și a solicitat admiterea acestuia din motivele invocate, cu aplicarea în privința sa a prevederilor art.91 Cod penal RM. Avocatul Pralea Grigore a solicitat admiterea recursului, casarea încheierii şipronunţarea unei noi hotărîri, prin care în privința condamnatului să fie aplicate prevederile art.91 Cod penal RM. Procurorul participant Prisacari Lilia a solicitat respingerea recursului declarat de condamnat ca fiind nefondat, cu menţinerea încheierii instanţei de fond ca fiind legală şi întemeiată. Verificînd argumentele invocate în recurs în raport cu materialele cauzei prezentate instanţei şi audiind opinia participanţilor la proces, Colegiul penal ajunge la concluzia, că recursul declarat de condamnatul x urmează a fi respins ca fiind nefondat din următoarele considerente. Conform art.449 al.(1) pct.1) lit.a) CPP RM judecînd recursul, instanţa adoptă una din următoarele decizii: 1) respinge recursul, menţinînd hotărîrea atacată, dacă: lit.a) recursul este nefondat. În conformitate cu prevederile art.91 al.(1) Cod penal RM persoanelor care execută pedeapsa cu închisoare, care au reparat integral daunele cauzate de infracţiunea pentru care sînt condamnate, care au participat la executarea şi care nu au refuzat executarea, în conformitate cu prevederile art.253 din Codul de executare, a muncilor remunerate sau neremunerate de îngrijire sau amenajare a penitenciarului şi a teritoriului, de îmbunătăţire a condiţiilor de trai şi medico­sanitare de detenţie li se poate aplica liberarea condiţionată de pedeapsă înainte de termen dacă instanţa de judecată va considera posibilă corectarea condamnatului fără executarea deplină a pedepsei. Totodată, persoana poate fi liberată, în întregime sau parţial, şi de pedeapsa complementară. Colegiul consideră că instanţa de fond la examinarea demersului înaintat de șeful adjunct al penitenciarului nr.6 Soroca Cebotari Alexandru a

[Succeeded / Failed / Skipped / Total] 2 / 2 / 0 / 4:   4%|▍         | 4/100 [00:46<18:47, 11.74s/it]

--------------------------------------------- Result 4 ---------------------------------------------
[[1 (84%)]] --> [[0 (74%)]]

Inculpații xxxxNUMExxxx și xxxxNUMExxxx se învinuiesc de că către organul de urmărire penală de faptul că, la 10.05.2014, ora 15:30, fiind efectuată de către colaboratorii Penitenciarului nr. 17 Rezina, percheziţia corporală a deţinutului xxxxNUMExxxx, la finele întrevederii de scurtă durată a acestuia cu soţia sa xxxxNUMExxxx, s­a depistat la acesta un pachet din material polimeric de culoare galben­transparent, o seringă medicală de unică folosinţă capacitatea de 20 ml., două „bile” din material polimeric transparent, în care în care se afla o masă vegetală uscată, de culoare verde, mărunţită, cu miros specific, asemănător cu cel de cînepă. Conform concluziei raportului de constatare tehnico­ştiinţifică nr. 4444 din 20.05.2014, masele vegetale de culoare verde, mărunţită, uscată, prezentată la examinare într­un pachet din material polimeric de culoare galben­transparent (21,20 grame), într­o seringă medicală de unică folosinţă capacitatea de 20 ml ( 16,72 grame) şi în două „bile” din material polimeric transparent (19,42 grame şi 4,50 grame), depistate şi ridicate la 10.05.2014 de către colaboratorii Penitenciarului nr. 17 Rezina, reprezintă marihuană, care face parte in categoria substanţelor narcotice. Cantitatea substanţei narcotice ­ marihuana constituie 61,84 grame (stare uscată), care conform Hotărîrei de Guvern nr.79 din 23.01.2006 privind aprobarea listei substanţelor narcotice, psihotrope şi a plantelor care conţin astfel de substanţe depistate în trafic ilicit, precum şi cantităţile acestora, reprezintă substanţe narcotice în proporţii mari. Inculpații xxxxNUMExxxx și xxxxNUMExxxx se învinuiesc că prin acţiunile lor intenţionate au săvîrşit infracţiunile prevăzute de art. 217/1 alin. (3) lit. b), e), f) şi art. 322 alin. (1) Cod [[penal]], adică păstrarea substanţelor narcotice în proporţii mari, de două persoane, pe teritoriul instituţiilor penitenciare, săvîrşite în scop de instrănare, substanţe care au fost transmise tănuit de la control, deţinutului în penitenciar. În ședința de judecată s­a constatat că, la 10.05.2014, ora 15:30, fiind efectuată de către colaboratorii Penitenciarului nr. 17 Rezina, percheziţia corporală a deţinutului xxxxNUMExxxx , la finele întrevederii de scurtă durată a acestuia cu soţia sa xxxxNUMExxxx , la el s­a depistat un pachet din material polimeric de culoare galben­transparent, o seringă medicală de unică folosinţă capacitatea de 20 ml., două „bile” din material polimeric transparent, în care se afla o masă vegetală uscată, de culoare verde, mărunţită, cu miros specific, asemănător cu cel de cînepă. xxxxNUMExxxx nu a fost prezentă la efectuarea percheziției lui xxxxNUMExxxx. În cadrul efectuării percheziției corporale a xxxxNUMExxxxristinei , atît la trecerea punctului de control,cît și la finele întrevederii, nu au fost depistate nici un fel de obiecte sau substanțe interzise. Inculpatul xxxxNUMExxxx, în cadrul urmăririi penale în calitate de bănuit și învinuit nu a recunoscut vina și nu a dorit să depună careva declarații, folosindu­se de dreptul de a tăcea. În şedinţa de judecată, inculpatul, la fel, a negat vina și a declarat că, se deține în Penitenciarul nr. 17 din februarie 2014. A avut întrevederi cu soția. A început a consuma marihuana de cînd era la libertate, iar în IP­17 Rezina s­a interesat la băieți cum obține marihuană. Condamnatul , cu care se deținea în aceeași celulă i­a spus că cunoaște pe cineva din colaboratori care poate să hotăracă întrebarea și i­l va

Inculpații xxxxNUMExxxx și xxxxNUMExxxx se învinuiesc de că către organul de urmărire penală de faptul că, la 10.05.2014, ora 15:30, fiind efectuată de către colaboratorii Penitenciarului nr. 17 Rezina, percheziţia corporală a deţinutului xxxxNUMExxxx, la finele întrevederii de scurtă durată a acestuia cu soţia sa xxxxNUMExxxx, s­a depistat la acesta un pachet din material polimeric de culoare galben­transparent, o seringă medicală de unică folosinţă capacitatea de 20 ml., două „bile” din material polimeric transparent, în care în care se afla o masă vegetală uscată, de culoare verde, mărunţită, cu miros specific, asemănător cu cel de cînepă. Conform concluziei raportului de constatare tehnico­ştiinţifică nr. 4444 din 20.05.2014, masele vegetale de culoare verde, mărunţită, uscată, prezentată la examinare într­un pachet din material polimeric de culoare galben­transparent (21,20 grame), într­o seringă medicală de unică folosinţă capacitatea de 20 ml ( 16,72 grame) şi în două „bile” din material polimeric transparent (19,42 grame şi 4,50 grame), depistate şi ridicate la 10.05.2014 de către colaboratorii Penitenciarului nr. 17 Rezina, reprezintă marihuană, care face parte in categoria substanţelor narcotice. Cantitatea substanţei narcotice ­ marihuana constituie 61,84 grame (stare uscată), care conform Hotărîrei de Guvern nr.79 din 23.01.2006 privind aprobarea listei substanţelor narcotice, psihotrope şi a plantelor care conţin astfel de substanţe depistate în trafic ilicit, precum şi cantităţile acestora, reprezintă substanţe narcotice în proporţii mari. Inculpații xxxxNUMExxxx și xxxxNUMExxxx se învinuiesc că prin acţiunile lor intenţionate au săvîrşit infracţiunile prevăzute de art. 217/1 alin. (3) lit. b), e), f) şi art. 322 alin. (1) Cod [[peanl]], adică păstrarea substanţelor narcotice în proporţii mari, de două persoane, pe teritoriul instituţiilor penitenciare, săvîrşite în scop de instrănare, substanţe care au fost transmise tănuit de la control, deţinutului în penitenciar. În ședința de judecată s­a constatat că, la 10.05.2014, ora 15:30, fiind efectuată de către colaboratorii Penitenciarului nr. 17 Rezina, percheziţia corporală a deţinutului xxxxNUMExxxx , la finele întrevederii de scurtă durată a acestuia cu soţia sa xxxxNUMExxxx , la el s­a depistat un pachet din material polimeric de culoare galben­transparent, o seringă medicală de unică folosinţă capacitatea de 20 ml., două „bile” din material polimeric transparent, în care se afla o masă vegetală uscată, de culoare verde, mărunţită, cu miros specific, asemănător cu cel de cînepă. xxxxNUMExxxx nu a fost prezentă la efectuarea percheziției lui xxxxNUMExxxx. În cadrul efectuării percheziției corporale a xxxxNUMExxxxristinei , atît la trecerea punctului de control,cît și la finele întrevederii, nu au fost depistate nici un fel de obiecte sau substanțe interzise. Inculpatul xxxxNUMExxxx, în cadrul urmăririi penale în calitate de bănuit și învinuit nu a recunoscut vina și nu a dorit să depună careva declarații, folosindu­se de dreptul de a tăcea. În şedinţa de judecată, inculpatul, la fel, a negat vina și a declarat că, se deține în Penitenciarul nr. 17 din februarie 2014. A avut întrevederi cu soția. A început a consuma marihuana de cînd era la libertate, iar în IP­17 Rezina s­a interesat la băieți cum obține marihuană. Condamnatul , cu care se deținea în aceeași celulă i­a spus că cunoaște pe cineva din colaboratori care poate să hotăracă întrebarea și i­l va

[Succeeded / Failed / Skipped / Total] 3 / 2 / 0 / 5:   5%|▌         | 5/100 [00:56<17:45, 11.21s/it]

--------------------------------------------- Result 5 ---------------------------------------------
[[1 (53%)]] --> [[0 (93%)]]

Prin sentinţa Judecătoriei raionale Sankt Petersburg Federaţia Rusă din 20.02.2013, GA a fost condamnat în baza art.30 alin.(1), art. 228­1 alin.(3) CP al Federaţiei Ruse la 8 ani închisoare cu regim înăsprit. Prin încheierea Judecătoriei Buiucani mun.Chişinău din 20.11.2014, condamnatul GA a fost transferat pentru ispășirea pedepsei penale în instituţiile penitenciare din R.Moldova, fiindu­i recunoscută condamnarea în baza art.26, 217/1 alin.(4) lit.d) CP la pedeapsa închisorii pe un termen de 8 ani şi calcularea termenului din 22.07.2010 cu posibilitatea liberării condiționate de pedeapsă înainte de termen la ispășirea efectivă a 3/4 din termenul de pedeapsă stabilit. Începutul termenului 22.07.2010 și sfârșitul termenului 21.07.2018. GA s­a adresat în instanța de judecată cu o cerere privind liberarea condiționată de pedeapsă înainte de termen, motivând că a sesizat comisia administrației Penitenciarului nr.6 Soroca, unde i­a fost refuzat de a fi prezentate materialele în instanţa de judecată, fapt cu care nu a fost de acord. Judecând cererea condamnatului, [[instanța]] a stabilit, că GA, la 22.07.2016 a executat fracția de 3/4 din pedeapsă pentru aplicarea prevederilor cu privire la liberarea condiționată înainte de termen, deci condiția legală relativă la timpul din pedeapsă ce trebuie executat este îndeplinită şi depășită cu 3 luni. Pe lângă acest criteriu obiectiv, instanța a notat că condamnatul nu are sancțiuni disciplinare valabile şi dă dovezi temeinice de îndreptare. Conform extrasului din procesul verbal al comisiei Penitenciarului nr.6 Soroca, GA a fost prezentat la comisie la 15.08.2016, în urma căreia i­a fost refuzat în aplicarea art.91 CP, din motiv că pe perioada ispășirii pedepsei a fost sancționat de 3 ori, toate în F.Rusă, ultima la 14.08.2013, sancțiuni care la moment sunt stinse, nu participă la procesul de instruire generală şi/sau profesională, nu este implicat în activități de educație socială şi nu este încadrat în câmpul muncii. Instanţa a apreciat, că caracteristica prezentată de administrație nu conține o concluzie corectă privind comportamentul lui GA, de unde reiese, că regimul de detenție în ultimii 3 ani nu­l încalcă, în conflicte cu administrația nu intră, pe parcursul ispășirii termenului de pedeapsă a dat dovadă de un comportament satisfăcător, nu se bucură de autoritate în mediul deținuților care mențin tradițiile hoțești sau care necesită supraveghere sporită, menține legătura cu familia şi rudele, la moment se caracterizează ca tip echilibrat, sociabil, prezintă risc de recidivă mediu. Instanța a notat, că atitudinea şi comportamentul condamnatului din ședința de judecată, precum şi raportul de evaluare prezentat, dau temei de a avea încredere că riscul lui de recidivare a scăzut considerabil. Făcând referire la prevederile art.240 alin.(1),(5),(7) Codului de executare instanța a reținut, că GA are studii superioare de scurtă durată şi în asemenea condiții nu există careva perspective de a­i evalua calitățile profesioniste ca negative. Instanța a concluzionat, că nu există dovezi că GA nu s­ar fi îndreptat şi nu ar fi înțeles rolul pedepsei și că ar fi refuzat vreodată de a munci. Poziția administrației instituției unde își ispășește pedeapsa condamnatul şi a procurorului instanța a considerat­o formală, nejustificată, or, nu are la bază dovezi din care să rezulte contrariul situației de îndreptare al condamnatului şi comportamentului corespunzător. În

Prin sentinţa Judecătoriei raionale Sankt Petersburg Federaţia Rusă din 20.02.2013, GA a fost condamnat în baza art.30 alin.(1), art. 228­1 alin.(3) CP al Federaţiei Ruse la 8 ani închisoare cu regim înăsprit. Prin încheierea Judecătoriei Buiucani mun.Chişinău din 20.11.2014, condamnatul GA a fost transferat pentru ispășirea pedepsei penale în instituţiile penitenciare din R.Moldova, fiindu­i recunoscută condamnarea în baza art.26, 217/1 alin.(4) lit.d) CP la pedeapsa închisorii pe un termen de 8 ani şi calcularea termenului din 22.07.2010 cu posibilitatea liberării condiționate de pedeapsă înainte de termen la ispășirea efectivă a 3/4 din termenul de pedeapsă stabilit. Începutul termenului 22.07.2010 și sfârșitul termenului 21.07.2018. GA s­a adresat în instanța de judecată cu o cerere privind liberarea condiționată de pedeapsă înainte de termen, motivând că a sesizat comisia administrației Penitenciarului nr.6 Soroca, unde i­a fost refuzat de a fi prezentate materialele în instanţa de judecată, fapt cu care nu a fost de acord. Judecând cererea condamnatului, [[insatnța]] a stabilit, că GA, la 22.07.2016 a executat fracția de 3/4 din pedeapsă pentru aplicarea prevederilor cu privire la liberarea condiționată înainte de termen, deci condiția legală relativă la timpul din pedeapsă ce trebuie executat este îndeplinită şi depășită cu 3 luni. Pe lângă acest criteriu obiectiv, instanța a notat că condamnatul nu are sancțiuni disciplinare valabile şi dă dovezi temeinice de îndreptare. Conform extrasului din procesul verbal al comisiei Penitenciarului nr.6 Soroca, GA a fost prezentat la comisie la 15.08.2016, în urma căreia i­a fost refuzat în aplicarea art.91 CP, din motiv că pe perioada ispășirii pedepsei a fost sancționat de 3 ori, toate în F.Rusă, ultima la 14.08.2013, sancțiuni care la moment sunt stinse, nu participă la procesul de instruire generală şi/sau profesională, nu este implicat în activități de educație socială şi nu este încadrat în câmpul muncii. Instanţa a apreciat, că caracteristica prezentată de administrație nu conține o concluzie corectă privind comportamentul lui GA, de unde reiese, că regimul de detenție în ultimii 3 ani nu­l încalcă, în conflicte cu administrația nu intră, pe parcursul ispășirii termenului de pedeapsă a dat dovadă de un comportament satisfăcător, nu se bucură de autoritate în mediul deținuților care mențin tradițiile hoțești sau care necesită supraveghere sporită, menține legătura cu familia şi rudele, la moment se caracterizează ca tip echilibrat, sociabil, prezintă risc de recidivă mediu. Instanța a notat, că atitudinea şi comportamentul condamnatului din ședința de judecată, precum şi raportul de evaluare prezentat, dau temei de a avea încredere că riscul lui de recidivare a scăzut considerabil. Făcând referire la prevederile art.240 alin.(1),(5),(7) Codului de executare instanța a reținut, că GA are studii superioare de scurtă durată şi în asemenea condiții nu există careva perspective de a­i evalua calitățile profesioniste ca negative. Instanța a concluzionat, că nu există dovezi că GA nu s­ar fi îndreptat şi nu ar fi înțeles rolul pedepsei și că ar fi refuzat vreodată de a munci. Poziția administrației instituției unde își ispășește pedeapsa condamnatul şi a procurorului instanța a considerat­o formală, nejustificată, or, nu are la bază dovezi din care să rezulte contrariul situației de îndreptare al condamnatului şi comportamentului corespunzător. În

[Succeeded / Failed / Skipped / Total] 3 / 3 / 0 / 6:   6%|▌         | 6/100 [01:09<18:12, 11.63s/it]

--------------------------------------------- Result 6 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Inculpata XXXXXXXXXX, la 11.03.2015, în a doua jumătate a zilei, ora exactă nu a fost posibil de stabilit în cadrul urmăririi penale, aflându­se în s. XXXXXXXXX, r­1 Ştefan Vodă, urmărind scopul răpirii copiilor săi minori, comuni cu fostul soţ XXXXXXXXX, şi anume XXXXXXXXa, a. n. XXXXXXX. XXXXX. a. n. XXXXXX şi XXXXXa, a. n. XXXXXX, care conform hotărârii Judecătoriei Ştefan Vodă, din 30.03.2011, au fost determinați cu traiul, la tatăl său, i­a luat pe aceștea împotriva voinţei cet. XXXXXXi, care este responsabil de educaţia copiilor sus indicaţi, şi i­a dus în s. XXXXXX r­1 Căuşeni, schimbându­i locul de trai, la domiciliul concubinului său, XXXXXXXXi. În şedinţa de judecată, pînă la începerea cercetării judecătoreşti, prin înscris autentic, inculpata XXXXXXXa declarat personal că recunoaşte săvîrşirea faptelor indicate în rechizitoriu şi solicită ca judecata să se facă pe baza probelor administrate în faza de urmărire penală, fără cercetarea martorilor. Obiecţii asupra probelor administrate nu are şi le recunoaşte fără careva rezerve. Apărătorul Olesea Durguz și acuzatorul de stat Diana Cernomorcenco au susţinut demersul inculpatei XXXXXX care în opinia lor a recunoscut în fond şi în totalitate faptele indicate în rechizitoriu, nu solicită administrarea de noi probe şi a solicitat ca judecata să se facă pe baza probelor administrate în faza de urmărire penală. În faţa instanţei inculpata XXXXXXX, sub jurămînt, prin expunerea factologică, ce nu contravine învinuirii formulate în rechizitoriu și­a recunoscut integral vinovăția și a declarat, că în una din zilele lunii martie 2015, se afla la domiciliul fostului său soţ, XXXXXX situat s. XXXXXXXXX r­nul Ştefan Vodă. Seara, XXXXXXXXi a început să o numească cu cuvinte înjurioase, cerîndu­i să plece. Ea a început să­şi strângă hainele pentru a merge în s. XXXXXXXX. Înainte de a se porni, fiicele sale minore, XXXX,XXXXXX şi XXXXXXX, au început să plângă, spunând că doresc să meargă cu ea, astfel a acceptat, deoarece îi era milă de acestea. Dînsa a îmbrăcat fiicele sale şi s­au dus în s. XXXXXXXXX, r­1 Căuşeni, fără a­1 informa pe fostul său soţ, care dormea. Împreună cu fiicele ei, au mers la domiciliul concubinului său, XXXXXXXXXX, la care şi locuieşte în prezent. Ulterior dînsa i­a comunicat fiicelor că urmează să plece la şcoală, la ce dînsele au început a plângă şi i­au spus că nu doresc acasă, deoarece le este frică de tatăl lor. A fost telefonată de către poliţistul de sector din s. XXXXXXXXX r­1 Ştefan Vodă, căruia i­a comunicat că fiicele sunt la ea. În următoarea zi, la domiciliul unde locuieşte, a venit poliţistul din satul XXXXXXXXX r­nul Ștefan Vodă și a luat fiicele. De cele comise se căieşte şi regretă. Culpa lui XXXXXXXXXX în răpirea minorelor de către o rudă apropiată, se confirmă și prin următoarele probe examinate în ședința de judecată, administrate la urmărirea penală: ­ plîngerea cetățeanului XXXXXXXXX, prin care solicită de a lua măsuri cu fosta soțieXXXXXXXX care la data de 11.03.2015 în jurul orelor 21:00 a luat copii de acasă fără voia lui, fără a­i comunica despre aceasta (f.d.­6); ­ proces ­ verbal de audiere a martorului XXXXXXXXX și XXXXXXXX(f.d.10­11); ­ hotărîrea instanței de judecată Ștefan

[Succeeded / Failed / Skipped / Total] 4 / 3 / 0 / 7:   7%|▋         | 7/100 [01:18<17:27, 11.27s/it]

--------------------------------------------- Result 7 ---------------------------------------------
[[1 (60%)]] --> [[0 (51%)]]

Prin sentinţa Judecătoriei C din 08 iulie 2014, T D a fost recunoscut [[vinovat]] de săvîrşirea infracţiunilor prevăzute de 1 art.361 alin.(2) lit.b), c), art.264 alin.(1) Cod penal, şi i s­a stabilit pedeapsă: ­ în baza art. 361 alin.(2) lit.b),c) Cod penal­2 ani închisoare; 1 ­ în baza art. 264 alin.(1) Cod penal – amendă în mărime de 450 unități convenționale, echivalentul a 9000 lei, cu privarea de dreptul de a conduce mijloace de transport pe un termen de 3 ani. În conformitate cu art.84 alin.(3) Cod penal, pedepsele stabilite de executat de sine stătător. În conformitate cu art.85 Cod penal,prin cumul de sentințe, de cumulat parțial la pedeapsa aplicată prin noua sentință, pedeapsa neexecutată stabilită prin sentința Judecătoriei B, mun.Chișinău din 29 iunie 2011, stabilindu­i inculpatului XXXXXXXXX pedeapsa definitivă de 4 ani și 01 lună închisoare, cu executarea pedepsei în penitenciar de tip semiînchis și amendă în mărime de 450 unități convenționale, echivalentul a 9000 lei, care vor fi executate de sine stătător, cu privarea de dreptul de a conduce mijloace de transport pe un termen de 3 ani și de a exercita activitate ce ține de perfectarea documentelor pe un termen de 3 ani. Pentru a pronunța sentința instanța de fond a reținut următoarele: XXXXXXXXX, în perioada lunii mai 2011, avînd scopul confecționării documentelor oficiale false, care acordă drepturi, la solicitarea lui B I G, acționînd coordonat cu alte persoane nestabilite, a confecționat și deținut declarații cu numerele 1250, 1253, 1261, 1262, 1263, 1272 și 1273, din numele notarului public „I V” cu sediul mun.C, str.C nr.6, din 10 mai 2011, pe numele lui RS A, născută la 19 decembrie 19xx, D C I, născut la 23 decembrie 19xx și L O A, născut la 05 mai 19xx, toți locuitori ai satului L, r.n. C, care conțin date vădit false, privind eliberarea declarațiilor sub numerele sus indicate, așa cum sub acele numere au fost deja înregistrate la 10 mai 2011, potrivit registrului de evidență a actelor notariale a notarului public „I V” altor persoane și alte acte notariale, acte care ulterior în perioada lunii mai 2011, în apropierea stației de alimentare „L” din or.C, prin intermediul unei persoane neidentificate au fost vîndute contra sumei de 300 euro și 500 lei, cetățeanului B I G. Tot el, la data de 27 decembrie 2011, aproximativ la ora 18.30 minute, deținînd permis de conducere categoria „A”, „B”, „C”, „D”, „E” nr.109300391, a condus automobilul de model „O A” cu n/î SV AK xxx, pe traseul interurban C­C, în stare de ebrietate alcoolică prin ce a încălcat cerințele pct.14 lit.a) al Regulamentului Circulației Rutiere, potrivit căruia: conducătorului de vehicul îi este interzis să conducă vehiculul în stare de ebrietate, sub influența drogurilor sau alte substanțe contraindicate, sub influența preparatelor medicamentoase care provoacă reducerea reacției, fiind bolnav, traumatizat sau într­o stare avansată de oboseală de natură să­i afecteze capacitatea de conducere. Fiind stopat de către colaboratorii poliției în apropiere de barul „H S” de pe traseul R­34, la ieșirea din orașul C, și fiind supus testului prin metoda alcooscopică s­a constatat că, concentrația vaporilor de

Prin sentinţa Judecătoriei C din 08 iulie 2014, T D a fost recunoscut [[vniovat]] de săvîrşirea infracţiunilor prevăzute de 1 art.361 alin.(2) lit.b), c), art.264 alin.(1) Cod penal, şi i s­a stabilit pedeapsă: ­ în baza art. 361 alin.(2) lit.b),c) Cod penal­2 ani închisoare; 1 ­ în baza art. 264 alin.(1) Cod penal – amendă în mărime de 450 unități convenționale, echivalentul a 9000 lei, cu privarea de dreptul de a conduce mijloace de transport pe un termen de 3 ani. În conformitate cu art.84 alin.(3) Cod penal, pedepsele stabilite de executat de sine stătător. În conformitate cu art.85 Cod penal,prin cumul de sentințe, de cumulat parțial la pedeapsa aplicată prin noua sentință, pedeapsa neexecutată stabilită prin sentința Judecătoriei B, mun.Chișinău din 29 iunie 2011, stabilindu­i inculpatului XXXXXXXXX pedeapsa definitivă de 4 ani și 01 lună închisoare, cu executarea pedepsei în penitenciar de tip semiînchis și amendă în mărime de 450 unități convenționale, echivalentul a 9000 lei, care vor fi executate de sine stătător, cu privarea de dreptul de a conduce mijloace de transport pe un termen de 3 ani și de a exercita activitate ce ține de perfectarea documentelor pe un termen de 3 ani. Pentru a pronunța sentința instanța de fond a reținut următoarele: XXXXXXXXX, în perioada lunii mai 2011, avînd scopul confecționării documentelor oficiale false, care acordă drepturi, la solicitarea lui B I G, acționînd coordonat cu alte persoane nestabilite, a confecționat și deținut declarații cu numerele 1250, 1253, 1261, 1262, 1263, 1272 și 1273, din numele notarului public „I V” cu sediul mun.C, str.C nr.6, din 10 mai 2011, pe numele lui RS A, născută la 19 decembrie 19xx, D C I, născut la 23 decembrie 19xx și L O A, născut la 05 mai 19xx, toți locuitori ai satului L, r.n. C, care conțin date vădit false, privind eliberarea declarațiilor sub numerele sus indicate, așa cum sub acele numere au fost deja înregistrate la 10 mai 2011, potrivit registrului de evidență a actelor notariale a notarului public „I V” altor persoane și alte acte notariale, acte care ulterior în perioada lunii mai 2011, în apropierea stației de alimentare „L” din or.C, prin intermediul unei persoane neidentificate au fost vîndute contra sumei de 300 euro și 500 lei, cetățeanului B I G. Tot el, la data de 27 decembrie 2011, aproximativ la ora 18.30 minute, deținînd permis de conducere categoria „A”, „B”, „C”, „D”, „E” nr.109300391, a condus automobilul de model „O A” cu n/î SV AK xxx, pe traseul interurban C­C, în stare de ebrietate alcoolică prin ce a încălcat cerințele pct.14 lit.a) al Regulamentului Circulației Rutiere, potrivit căruia: conducătorului de vehicul îi este interzis să conducă vehiculul în stare de ebrietate, sub influența drogurilor sau alte substanțe contraindicate, sub influența preparatelor medicamentoase care provoacă reducerea reacției, fiind bolnav, traumatizat sau într­o stare avansată de oboseală de natură să­i afecteze capacitatea de conducere. Fiind stopat de către colaboratorii poliției în apropiere de barul „H S” de pe traseul R­34, la ieșirea din orașul C, și fiind supus testului prin metoda alcooscopică s­a constatat că, concentrația vaporilor de

[Succeeded / Failed / Skipped / Total] 4 / 4 / 1 / 9:   8%|▊         | 8/100 [01:29<17:07, 11.16s/it]

--------------------------------------------- Result 8 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Inculpatul, xxxxxxxxx, la data de 06.11.2013, în perioada de timp cupinsă între orele 18:00­21:00, aflîndu­se în apartamentul xxxxxxxxx, ce aparține unchiului său xxxxx, folosindu­se de faptul că nu este observat de nimeni, prin acces liber, a sustras pe ascun bani în sumă de 3300 lei, cauzîndu­i părții vătămate xxxxxxxx o daună în proporții considerabile, eschivîndu­se cu cele sustrase de la locul infracțiunii. În cadrul şedinţei judiciare inculpatul xxxxxxxx şi­a recunoscut vinovăţia de comiterea celor incriminate şi a menţionat că la data de 06.11.2013 a fost la unchiul său xxxxxxxxxxx, unde a stat ceva timp. Avînd nevoie de bani a sustras de la unchiul său bani în sumă de 3300 lei. În ședința de judecată partea vătămată a înaintat o cerere prin care solicită instanţei de judecată încetarea procesului penal în privinţa lui xxxxxxxxxx în legătură cu faptul împăcării cu inculpatul. Procurorul și avocatul inculpatului au susţinut cererea părţii vătămate, invocând că legea penală prevede încetarea procesului penal în cazul împăcării părţilor. Astfel, vinovăţia inculpatului se confirmă prin probele prezentate de acuzatorul de stat în şedinţă şi acceptate de inculpat. Prin justeţea probelor instanţa de judecată consideră acţiunile inculpatului xxxxxxxxx corect încadrate în baza art.186 alin.(2) lit.d) Codului penal conform indicilor: furt, adică, sustragerea pe ascuns a bunurilor altei personae, săvîrşit cu cauzarea de daune în proporţii considerabile. Faptul dat şi­a găsit confirmare prin declaraţiile inculpatului şi materialele dosarului elucidate în cadrul anchetei judiciare. Analizând probele administrate, audiind participanţii la proces, instanţa de judecată conchide că demersul părţii vătămate privind încetarea cauzei penale este întemeiat şi posibil admiterii. Inculpatul Cușciuc Evghenii şi­a recunoscut vinovăţia, se căieşte sincer în cele comise. Părţile s­au împăcat şi partrea vătămată nu are pretenţii materiale şi morale faţă de inculpat şi solicită încetarea procesului penal în privinţa inculpatului xxxxxxxxxxxxx. Având în vedere cele expuse, călăuzindu­se de prevederile art. 391 al.(1) p.1) Codului de procedură penală, instanţa de judecată consideră că poate fi încetat procesul penal faţă de inculpatul xxxxxxx intentat în baza art.186 alin.(2) lit.d) Codului penal, deoarece părţile s­au împăcat şi legea penală permite împăcarea. Călăuzindu­se de prevederile art.109 Codului penal, art.332, 391 al.(1) p.1), 396 Codului de procedură penală, instanţa de judecată,


--------------------------------------------- Result 9 ---------------------------------------------
[[0 (97%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut, că inculpatul xxxxNUMExxxx, activînd în calitate de comisar­adjunct, şef poliţie de ordine publică a CPR Edineţ, numit în această funcţie prin ordinul MAI nr. 228 EF din 15.05.2009 şi fiind, astfel, la acel moment, conform art. 123 alin. (1) din Codul penal persoană cu funcţie de răspundere, contrar prevederilor art. 3 din Convenţia Europeană pentru Apărarea Drepturilor Omului şi a Libertăţilor Fundamentale, adoptată la Roma la 04.11.1950, la care Republica Moldova a aderat la 12.09.1997; art. 24, alin. (l) şi (2), art. 25, art. 27 alin. (l), din Constituţia Republicii Moldova, adoptată la 29.07.1994; art. 1­4, 12, 15 ale Legii nr. 416­XII din 18.12.1990 cu privire la poliţie (în vigoare la data săvîrşirii infracţiunii), art. 10, 11 din Codul de procedură penală, pct. 2, 4 şi 10 ale Statutului disciplinar al organelor afacerilor interne, aprobat prin Hotărîrea Guvernului Republicii Moldova nr. 2 din 04.02.1996 şi fişa postului, care­1 obligau să­şi desfăşoare activitatea pe baza respectării stricte a legilor, să protejeze viaţa, sănătatea şi libertăţile cetăţenilor, interesele societăţii şi ale statului de atentate criminale şi de alte atacuri nelegitime; să prevină şi curme crimele şi alte infracţiuni; să ia măsuri pentru apărarea vieţii, sănătăţii, onoarei, demnităţii cetăţenilor, să le asigure dreptul la libera circulaţie; să nu aplice nejustificat forţa fizică şi mijloacele speciale iar în caz de aplicare să comunice despre aceasta şefului său direct; să nu supună pe nimeni torturii, pedepselor sau tratamentelor crude, inumane ori degradante; să oprească pe cei din jur de la încălcarea ordinii de drept şi să contribuie activ la menţinerea prestigiului colaboratorului organelor afacerilor interne şi a demnităţii cetăţenilor; să educe subordonaţii săi în spiritul devotamentului faţă de Patrie şi popor, al întăririi continue a disciplinei de serviciu, regulilor de convieţuire socială şi a ordinii de drept ­ în loc de aceasta, intenţionat, a comis acte de tortură în privinţa cet. xxxxCUSTOM2xxxx în următoarele împrejurări. Astfel, la 14.03.2013, între orele 12­13, xxxxNUMExxxx, fiind persoană cu funcţie de răspundere şi acţionând cu titlu oficial, reprezentând Ministerul Afacerilor Interne, aflându­ se în biroul său de serviciu amplasat în incinta CPR Edineţ, or. Edineţ str. Ştefan Vodă 5, sub pretextul, că inspectorul grupei de autorizări al CPR Edineţ xxxxCUSTOM2xxxx, căruia îi era şef nemijlocit, nu a acceptat să procure şi să consume cu el băuturi alcoolice, cu scopul de a­1 pedepsi pentru acest fapt, l­a instigat pe cet. xxxxCUSTOM1xxxx să­l lovească pe numit, ceea ce ultimul a şi realizat prin aplicarea unui şir de lovituri cu picioarele şi pumnii peste cap, acţiuni care fiind efectuate la instigarea cet. xxxxNUMExxxx precum şi comise în incinta unei instituţii de stat, au căpătat calitatea celor săvîrşite cu titlul oficial. În acelaşi timp şi circumstanţe, după ce xxxxCUSTOM2xxxx a căzut la podea în rezultatul loviturilor aplicate de către cet. xxxxCUSTOM1xxxx, xxxxNUMExxxx, sub acelaşi pretext, că nu a îndeplinit o solicitare ilegală, cu acelaşi scop, de a­1 pedepsi pentru nesupunere, personal i­a aplicat intenţionat lui xxxxCUSTOM2xxxx multiple lovituri cu pumnii şi cu picioarele peste mai multe părţi ale corpului, acţiuni care în

[Succeeded / Failed / Skipped / Total] 5 / 4 / 1 / 10:   9%|▉         | 9/100 [01:37<16:26, 10.84s/it]

--------------------------------------------- Result 10 ---------------------------------------------
[[0 (65%)]] --> [[1 (86%)]]

Inculpatul Bezzub Maria Piotr, în luna iunie a anului 2010 urmărind scopul exploatării sexuale comerciale a lui Alina Cojocari, prin înşelăciune, sub pretextul angajării la muncă în calitate de vânzătoare într-un magazin din or. Antalya, Turcia, prin înţelegere prealabilă şi cu participarea unei persoane neidentificate de organul de urmărire penală cu numele „Tuba”, au recrutat-o, transportat-o şi a adăpostit-o pe Alina Cojocari într-o locuinţă din or. Antalya, Turcia, unde i-a sechestrat acesteia paşaportul, după care amenințând-o cu aplicarea violenţei fizice, au exploatat-o pe Alina Cojocari pe parcursul a două luni, fiind impusă să presteze servicii sexuale contra plată. Procedura de citare legală a fost respectată. Inculpata Bezzub Maria în şedinţa de judecată a declarat că, nu se consideră vinovată în comiterea infracţiunii incriminate şi instanţei de judecată a relatat că, cu partea vătămată Alina Cojocari a făcut cunoștința aproximativ în anul 2008 prin intermediul unei prietene pe nume Feodora Țurcan, la care Alina Cojocari locuia cu chirie. Peste o perioada de timp Alina Cojocari s-a întors acasă la ţară în r-nul Ungheni. A revăzut-o în luna aprilie 2010, tot la Feodora Țurcan acasă şi s-au împrietenit. Din conversația cu Feodora Țurcan partea vătămată Alina Cojocari a aflat că ea are un prieten de origine turcă şi că intenționează să plece în Turcia. La fel, a menţionat [[inculpata]] că, Cojocari Alina a observat că ea este bine îmbrăcată, posedă telefon mobil performant şi nu se limitează în nimic și atunci a rugat - o să o ia şi pe ea în Turcia și poate prietenul ei îi va face cunoștință cu vre-un bărbat în Turcia. Ea i-a spus lui Alina Cojocari că pentru deplasare în Turcia, are necesitate de 1000 dolari SUA, pentru a prezenta la vamă. Alina Cojocari nu a avut de la cine să se împrumute cu această suma de bani. Peste o perioadă de timp Feodora Țurcan o alungat - o pe Alina Cojocari de la gazdă, motivul nu-l şi Alina Cojocari i-a cerut să locuiască la ea. Partea vătămată, a aflat că familia ei realizează apartamentul din str. Alba Iulia 4 și se transferă cu traiul în r-nul Dubăsari. Alina Cojocari a rugat ca să întrebe dacă mama ei nu poate să o împrumute cu suma de 1000 dolari SUA. Însă, apelând la mamă ei, ultima a refuzat deoarece banii erau preconizați pentru procurarea altui imobilului din Dubăsari. După ce au vândut apartamentul și au plecat cu traiul la Dubăsari a luat cu ea și pe Alina Cojocari deoarece nu a vrut să o lase în stradă. La Dubăsari, Alina Cojocari, aflând că, casa au procurat-o de la unchiul ei, a rugat - o să apeleze la el dacă poate să-i împrumute suma de 1000 dolari SUA. De la început unchiul ei a refuzat, însă i-au promis că, îi vor întoarce în schimb 1500 dolari SUA şi îl voi invita pentru a-l cinsti într-un local. Deoarece, moșul ei nu o cunoștea pe Alina Cojocari el i - a împrumutat banii sub garanția ei personală. După ce unchiul i-a împrumutat banii, ea l-a telefonat pe prietenul ei Orhan în Antalya,

Inculpatul Bezzub Maria Piotr, în luna iunie a anului 2010 urmărind scopul exploatării sexuale comerciale a lui Alina Cojocari, prin înşelăciune, sub pretextul angajării la muncă în calitate de vânzătoare într-un magazin din or. Antalya, Turcia, prin înţelegere prealabilă şi cu participarea unei persoane neidentificate de organul de urmărire penală cu numele „Tuba”, au recrutat-o, transportat-o şi a adăpostit-o pe Alina Cojocari într-o locuinţă din or. Antalya, Turcia, unde i-a sechestrat acesteia paşaportul, după care amenințând-o cu aplicarea violenţei fizice, au exploatat-o pe Alina Cojocari pe parcursul a două luni, fiind impusă să presteze servicii sexuale contra plată. Procedura de citare legală a fost respectată. Inculpata Bezzub Maria în şedinţa de judecată a declarat că, nu se consideră vinovată în comiterea infracţiunii incriminate şi instanţei de judecată a relatat că, cu partea vătămată Alina Cojocari a făcut cunoștința aproximativ în anul 2008 prin intermediul unei prietene pe nume Feodora Țurcan, la care Alina Cojocari locuia cu chirie. Peste o perioada de timp Alina Cojocari s-a întors acasă la ţară în r-nul Ungheni. A revăzut-o în luna aprilie 2010, tot la Feodora Țurcan acasă şi s-au împrietenit. Din conversația cu Feodora Țurcan partea vătămată Alina Cojocari a aflat că ea are un prieten de origine turcă şi că intenționează să plece în Turcia. La fel, a menţionat [[icnulpata]] că, Cojocari Alina a observat că ea este bine îmbrăcată, posedă telefon mobil performant şi nu se limitează în nimic și atunci a rugat - o să o ia şi pe ea în Turcia și poate prietenul ei îi va face cunoștință cu vre-un bărbat în Turcia. Ea i-a spus lui Alina Cojocari că pentru deplasare în Turcia, are necesitate de 1000 dolari SUA, pentru a prezenta la vamă. Alina Cojocari nu a avut de la cine să se împrumute cu această suma de bani. Peste o perioadă de timp Feodora Țurcan o alungat - o pe Alina Cojocari de la gazdă, motivul nu-l şi Alina Cojocari i-a cerut să locuiască la ea. Partea vătămată, a aflat că familia ei realizează apartamentul din str. Alba Iulia 4 și se transferă cu traiul în r-nul Dubăsari. Alina Cojocari a rugat ca să întrebe dacă mama ei nu poate să o împrumute cu suma de 1000 dolari SUA. Însă, apelând la mamă ei, ultima a refuzat deoarece banii erau preconizați pentru procurarea altui imobilului din Dubăsari. După ce au vândut apartamentul și au plecat cu traiul la Dubăsari a luat cu ea și pe Alina Cojocari deoarece nu a vrut să o lase în stradă. La Dubăsari, Alina Cojocari, aflând că, casa au procurat-o de la unchiul ei, a rugat - o să apeleze la el dacă poate să-i împrumute suma de 1000 dolari SUA. De la început unchiul ei a refuzat, însă i-au promis că, îi vor întoarce în schimb 1500 dolari SUA şi îl voi invita pentru a-l cinsti într-un local. Deoarece, moșul ei nu o cunoștea pe Alina Cojocari el i - a împrumutat banii sub garanția ei personală. După ce unchiul i-a împrumutat banii, ea l-a telefonat pe prietenul ei Orhan în Antalya,

[Succeeded / Failed / Skipped / Total] 5 / 5 / 1 / 11:  10%|█         | 10/100 [01:52<16:50, 11.23s/it]

--------------------------------------------- Result 11 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

La 01.05.2014, aproximativ pe la orele 20:00, fiind efectuată de către colaboratorii Penitenciarului nr.17 Rezina percheziţia corporală inopinantă a deţinutei xxxxNUMExxxx din celula nr.61 a blocului de regim nr. 2 a IP­17, aceasta nu s­a supus cerinţelor legale ale colaboratorilor penitenciarului, aflați în exercițiul funcțiunilor şi a agresat­o fizic pe santinela­operator a IP­17 Rezina, plutonier de justiţie xxxxCUSTOM1xxxx prin aplicarea loviturilor cu picioarele în regiunea abdomenului, cauzîndu­i ultimei vătămări corporale sub formă de echimoze în regiunea iliacă bilateral, regiunea umărului stîng, care conform concluziei raportului de expertiză medico­ legală nr.187 D din 17 mai 2014 se referă la vătămări neînsemnate. Pînă la începerea cercetării judecătorești, inculpata xxxxNUMExxxx s­a adresat către instanță cu o cerere în scris, prin care a solicitat ca judecata să se facă în baza probelor administrate la faza de urmărire penală, menționînd că recunoaște necondițonat fapta incriminată și nu solicită administrarea de probe noi. Avocatul A.M a susținut cererea depusă de către inculpată. Judecarea cauzei, în baza probelor administrate la faza urmăririi penale a fost acceptată și de către procuror. Potrivit probelor anexate la dosar, fapta incriminată inculpatei xxxxNUMExxxx se dovedește incontestabil, din care considerente instanța a admis cererea acesteia, privind judecarea cauzei în baza probelor administrate în faza de urmărire penală. Audiată pe marginea învinuirii înaintate de către organul de urmărire penală, potrivit regulilor de audiere a martorului, inculpata xxxxNUMExxxx a declarat instanței, că la data de 01 mai 2014, aproximativ la ora 2000 în celula nr.61 a IP­17 unde se deținea în baza deciziei instanței judecătorești, au intrat colaboratorii penitenciarului să facă percheziția corporală. Întrucît avea la ea un telefon mobil, care este obiect interzis, a refuzat să fie percheziționată, știind că i se v­a lua telefonul. A început a se certa cu angajații penitenciarului, exprimîndu­se cu cuvinte necenzurate. Pînă la urmă, totuș, i s­a luat telefonul. A împins­o pe T.xxxxCUSTOM1xxxx, deoarece aciasta a ținut­o ca să­i fie luat telefonul. În timpul acțiunilor sale de nesupunere, i­a rupt T.xxxxCUSTOM1xxxx un epolet. Opunîndu­se acțiunilor colaboratorilor penitenciarului de a­i lua telefonul, a lovit­o pe T.xxxxCUSTOM1xxxx cu picioarele în abdomen. Recunoaște că leziunile corporale stabilite la xxxxCUSTOM1xxxx Tatiana i­au fost provocate acesteia prin acțiunile sale. Consideră că nu a procedat corect. Regretă cele întîmplate. De rînd cu declarațiile sale din ședința de judecată, vina inculpatei xxxxNUMExxxx în comiterea infracțiunii de care se învinuiește se mai dovedește prin materialele dosarului penal, și anume: ­depoziţiile părţii vătămate xxxxCUSTOM1xxxx , potrivit cărora, activînd în calitate de santinelă­operator în cadrul Penitenciarului nr.17 Rezina, la 01 mai 2014, aflîndu­se în serviciu, aproximativ la orele 1940 a primit indicaţia de la ofiţerul de serviciu Constantin xxxxCUSTOM2xxxx şi şeful SRS Igor Guţu de a se prezenta la postul intern nr.6 a blocului de regim nr. 2, pentru efctuarea percheziţiei inopinate în celula nr.61. La intrare în celula s­a propus deţinutelor de a preda benevol obiectele interzise, dacă le deţin, la ce au primit răspuns negativ. După acesta au încercat de a efectua percheziţia corporală a deţinutei xxxxNUMExxxx, care se comporta neadecvat şi nu le permitea efectuarea procedurii menţionate, prin lovirea cu mîinile a detectorului de metal, înjurarea

[Succeeded / Failed / Skipped / Total] 6 / 5 / 1 / 12:  11%|█         | 11/100 [02:01<16:22, 11.04s/it]

--------------------------------------------- Result 12 ---------------------------------------------
[[0 (95%)]] --> [[1 (65%)]]

1. Prin sentința Judecătoriei [[raionale]] [[Dorogomilovskii]] or. Moscova, Federația Rusă, din 27 decembrie 2013, ***** [[Mihail]] a fost condamnat, pentru comiterea infracţiunilor prevăzute de: art. 30 alin. 3 pct. g), 228/1 alin. 3 Codul penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertății; art. 229/1 alin. 3 Cod penal al Federaţiei Ruse la 10 ani închisoare fără amendă sau limitarea libertăţii; art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertății; potrivit prevederilor art.69 alin.3 Codul penal al Federaţiei Ruse, prin cumul parţial de pedepse, i s-a aplicat definitiv 13 ani închisoare fără amendă, fără privarea dreptului de a ocupa anumite funcţii sau de a exercita o anumită activitate cu executarea pedepsei în penitenciar cu regim sever; calcularea termenului de executare a pedepsei se face din 19 octombrie 2012. 2. Ministerul Justiţiei al Republicii Moldova a înaintat în instanţa de judecată demers privind transferul [[condamnatului]] ***** Mihail pentru continuarea executării pedepsei penale în Republica Moldova. Demersul este întemeiat pe prevederile art. 556 Cod de procedură penală al Republicii Moldova şi art. 2-6 ale Convenţiei europene asupra transferului persoanelor condamnate (Strasbourg 21.03.1983)La data de 07.07.2017, Ministerul Justiţiei al Republicii Moldova s-a adresat Judecătoriei Chişinău (sediul Buiucani) cu un demers prin care a solicitat acceptarea transferării dlui ***** Mihail pentru continuarea ispășirii pedepsei. 3. Prin încheierea Judecătoriei Chișinău (sediul Ciocana) nr.8-9/2019 din 24 aprilie 2019: 1) a fost admis demersul Ministrului Justiţiei al Republicii Moldova privind transferul lui ***** Mihail condamnat de statul străin, pentru executarea în continuare a pedepsei în instituțiile penitenciare ale Republicii Moldova; 2) a [[fost]] acceptată, pentru executarea în continuare a pedepsei în instituțiile penitenciare ale Republicii Moldova, transferul [[condamnatului]] ***** Mihail, condamnat prin sentinţa Judecătoriei raionale Dorogomilovskii or. Moscova, Federaţia Rusă din 27 decembrie 2013, pentru comiterea infracţiunilor prevăzute de: art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertăţii; art. 229/1 alin. 3 Cod penal al Federaţiei Ruse la 10 ani închisoare fără amendă sau limitarea libertăţii; art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertăţii; 3) potrivit prevederilor art. 69 alin. 3 Cod penal al Federaţiei Ruse, prin cumul parţial de pedepse, i s-a aplicat definitiv 13 ani închisoare fără amendă, fără privarea dreptului de a ocupa anumite funcţii sau de a exercita o anumită activitate cu executarea pedepsei în penitenciar cu regim sever. Procedura de executare a pedepsei urmează să schimbarea condamnării; 4) în cazul acceptării transferului condamnatului pentru continuarea executării pedepsei în Republica Moldova de către instanţa competentă a statului de condamnare a lui ***** Mihail, acesta se va considera condamnat pentru comiterea infracţiunilor prevăzute de: art. 27, 217/1 alin. 4 lit. d) Cod penal la 8 ani închisoare; art. 248 alin. (2) Cod penal la 5 ani închisoare; art. 27, 217/1 alin. 4 lit. d) Cod penal la 8 ani închisoare; 5) prin aplicarea art. 84 alin. (1) CP, prin

1. Prin sentința Judecătoriei [[rainoale]] [[Doorgomilovskii]] or. Moscova, Federația Rusă, din 27 decembrie 2013, ***** [[Mihial]] a fost condamnat, pentru comiterea infracţiunilor prevăzute de: art. 30 alin. 3 pct. g), 228/1 alin. 3 Codul penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertății; art. 229/1 alin. 3 Cod penal al Federaţiei Ruse la 10 ani închisoare fără amendă sau limitarea libertăţii; art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertății; potrivit prevederilor art.69 alin.3 Codul penal al Federaţiei Ruse, prin cumul parţial de pedepse, i s-a aplicat definitiv 13 ani închisoare fără amendă, fără privarea dreptului de a ocupa anumite funcţii sau de a exercita o anumită activitate cu executarea pedepsei în penitenciar cu regim sever; calcularea termenului de executare a pedepsei se face din 19 octombrie 2012. 2. Ministerul Justiţiei al Republicii Moldova a înaintat în instanţa de judecată demers privind transferul [[condamnautlui]] ***** Mihail pentru continuarea executării pedepsei penale în Republica Moldova. Demersul este întemeiat pe prevederile art. 556 Cod de procedură penală al Republicii Moldova şi art. 2-6 ale Convenţiei europene asupra transferului persoanelor condamnate (Strasbourg 21.03.1983)La data de 07.07.2017, Ministerul Justiţiei al Republicii Moldova s-a adresat Judecătoriei Chişinău (sediul Buiucani) cu un demers prin care a solicitat acceptarea transferării dlui ***** Mihail pentru continuarea ispășirii pedepsei. 3. Prin încheierea Judecătoriei Chișinău (sediul Ciocana) nr.8-9/2019 din 24 aprilie 2019: 1) a fost admis demersul Ministrului Justiţiei al Republicii Moldova privind transferul lui ***** Mihail condamnat de statul străin, pentru executarea în continuare a pedepsei în instituțiile penitenciare ale Republicii Moldova; 2) a [[fsot]] acceptată, pentru executarea în continuare a pedepsei în instituțiile penitenciare ale Republicii Moldova, transferul [[condamnautlui]] ***** Mihail, condamnat prin sentinţa Judecătoriei raionale Dorogomilovskii or. Moscova, Federaţia Rusă din 27 decembrie 2013, pentru comiterea infracţiunilor prevăzute de: art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertăţii; art. 229/1 alin. 3 Cod penal al Federaţiei Ruse la 10 ani închisoare fără amendă sau limitarea libertăţii; art. 30 alin. 3 pct. g), 228/1 alin. 3 Cod penal al Federaţiei Ruse la 8 ani închisoare fără amendă sau limitarea libertăţii; 3) potrivit prevederilor art. 69 alin. 3 Cod penal al Federaţiei Ruse, prin cumul parţial de pedepse, i s-a aplicat definitiv 13 ani închisoare fără amendă, fără privarea dreptului de a ocupa anumite funcţii sau de a exercita o anumită activitate cu executarea pedepsei în penitenciar cu regim sever. Procedura de executare a pedepsei urmează să schimbarea condamnării; 4) în cazul acceptării transferului condamnatului pentru continuarea executării pedepsei în Republica Moldova de către instanţa competentă a statului de condamnare a lui ***** Mihail, acesta se va considera condamnat pentru comiterea infracţiunilor prevăzute de: art. 27, 217/1 alin. 4 lit. d) Cod penal la 8 ani închisoare; art. 248 alin. (2) Cod penal la 5 ani închisoare; art. 27, 217/1 alin. 4 lit. d) Cod penal la 8 ani închisoare; 5) prin aplicarea art. 84 alin. (1) CP, prin

[Succeeded / Failed / Skipped / Total] 7 / 5 / 1 / 13:  12%|█▏        | 12/100 [02:11<16:04, 10.96s/it]

--------------------------------------------- Result 13 ---------------------------------------------
[[1 (62%)]] --> [[0 (50%)]]

Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut, că În noaptea de 30 aprilie spre 01 mai 2013, xxNUMExx intenționat, urmărind scop de profit și sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la propunerea și imițiativa sa, avînd acces liber au sustras din [[gardul]] de la gospodăria cet. xxNUMExx, din satul xxSATxx, r­ul Teleneşti, 10 secţii de [[gard]] metalic, cu preţul unuia de 2500 lei, prin ce au cauzat părții vătămate un prejudiciu material considerabil în sumă totală de 32 200 lei. Tot el, în noaptea de 13 spre 14 aprilie 2014, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu [[xxNUMExx]], la inițiativa și propunerea sa, peste gard au pătruns în gospodăria cet. [[xxNUMExx]], locuitor al satului xxSATxx, raionul Telenești, de unde au sustras 2 freze agricole de la motocultivatorul de model ,,Zubr”, cu prețul uneia de 600 lei, prin ce i­a cauzat părți vătămate un prejudiciu material considerabil în sumă totală de 1 800 lei. Tot el, în noaptea de 15 aprilie 2014, aflîndu­se în stare de ebrietate produsă de alcool, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la inițiativa și propunerea sa, prin deteriorarea cu cleștele a gardului din plasă metalică, au pătruns în gospodăria cet. xxNUMExx, locuitoare a satatului xxSATxx, r­ul Teleneşti, de unde au sustras un motocultivator de modelul "Zubr", prin ce i­a cauzat proprietarului un prejudiciu material considerabil în sumă totală 11 400 lei. Tot el, în perioada lunii iulie 2014, intenționat, urmărind scop de profit și sustragere pe ascuns a bunurilor altei persoane, pe poartă a pătruns în gospodăria cet. xxNUMExx, din [[satului]] xxSATxx, raionul Telenești, apoi prin forţarea geamului de la garaj, a pătruns în interior de unde a sustras următoarele bunuri materiale: o bicicletă la prețul de 2000 lei, motoferestrău de tăiat [[lemne]] de model "MODINA" la [[prețul]] de 4000 lei, doua [[ferestrăie]] pendulare de model "BOSH" la preţul de 2000 lei [[fiecare]], în sumă totală de 4000 lei, două seturi de chei tubulare la preţ de 1500 lei fiecare, în sumă totală de 3000 lei, un set de surubelniţe la preţul de 1000 lei, o maşina de şlefuit electrică la preţ de 3000 lei, o pereche de clește de tăiat metal la preţul de 1500 1ei, un perforator electric la preţul de 3000 lei, doua burghii electrice la prețul de 1500 lei fiecare, în sumă totală de 3000 lei, un aparat de frezat arbuști la preț de 4000 lei, un prelungitor cu lungimea de 50 metri, la pretul de 1300 lei, prin ce i­au cauzat acestuia un prejudiciu material considerabil in suma de 39 500 lei. Tot el, în noaptea de 02 spre 03 august 2014, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la inițiativa și propunerea sa, au pătruns în gospodăria cet. xxNUMExx, locuitoare a satatului xxSATxx, r­ul Teleneşti, de unde au sustras o betonieră, prin ce i­a cauzat proprietarului un

Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut, că În noaptea de 30 aprilie spre 01 mai 2013, xxNUMExx intenționat, urmărind scop de profit și sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la propunerea și imițiativa sa, avînd acces liber au sustras din [[gradul]] de la gospodăria cet. xxNUMExx, din satul xxSATxx, r­ul Teleneşti, 10 secţii de [[grad]] metalic, cu preţul unuia de 2500 lei, prin ce au cauzat părții vătămate un prejudiciu material considerabil în sumă totală de 32 200 lei. Tot el, în noaptea de 13 spre 14 aprilie 2014, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu [[xxNUMxEx]], la inițiativa și propunerea sa, peste gard au pătruns în gospodăria cet. [[xxNMUExx]], locuitor al satului xxSATxx, raionul Telenești, de unde au sustras 2 freze agricole de la motocultivatorul de model ,,Zubr”, cu prețul uneia de 600 lei, prin ce i­a cauzat părți vătămate un prejudiciu material considerabil în sumă totală de 1 800 lei. Tot el, în noaptea de 15 aprilie 2014, aflîndu­se în stare de ebrietate produsă de alcool, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la inițiativa și propunerea sa, prin deteriorarea cu cleștele a gardului din plasă metalică, au pătruns în gospodăria cet. xxNUMExx, locuitoare a satatului xxSATxx, r­ul Teleneşti, de unde au sustras un motocultivator de modelul "Zubr", prin ce i­a cauzat proprietarului un prejudiciu material considerabil în sumă totală 11 400 lei. Tot el, în perioada lunii iulie 2014, intenționat, urmărind scop de profit și sustragere pe ascuns a bunurilor altei persoane, pe poartă a pătruns în gospodăria cet. xxNUMExx, din [[sautlui]] xxSATxx, raionul Telenești, apoi prin forţarea geamului de la garaj, a pătruns în interior de unde a sustras următoarele bunuri materiale: o bicicletă la prețul de 2000 lei, motoferestrău de tăiat [[lmene]] de model "MODINA" la [[preuțl]] de 4000 lei, doua [[freestrăie]] pendulare de model "BOSH" la preţul de 2000 lei [[feicare]], în sumă totală de 4000 lei, două seturi de chei tubulare la preţ de 1500 lei fiecare, în sumă totală de 3000 lei, un set de surubelniţe la preţul de 1000 lei, o maşina de şlefuit electrică la preţ de 3000 lei, o pereche de clește de tăiat metal la preţul de 1500 1ei, un perforator electric la preţul de 3000 lei, doua burghii electrice la prețul de 1500 lei fiecare, în sumă totală de 3000 lei, un aparat de frezat arbuști la preț de 4000 lei, un prelungitor cu lungimea de 50 metri, la pretul de 1300 lei, prin ce i­au cauzat acestuia un prejudiciu material considerabil in suma de 39 500 lei. Tot el, în noaptea de 02 spre 03 august 2014, intenţionat, urmărind scop de profit şi sustragere pe ascuns a bunurilor altei persoane, înțelegîndu­se în prealabil cu xxNUMExx, la inițiativa și propunerea sa, au pătruns în gospodăria cet. xxNUMExx, locuitoare a satatului xxSATxx, r­ul Teleneşti, de unde au sustras o betonieră, prin ce i­a cauzat proprietarului un

[Succeeded / Failed / Skipped / Total] 8 / 5 / 1 / 14:  13%|█▎        | 13/100 [02:20<15:38, 10.79s/it]

--------------------------------------------- Result 14 ---------------------------------------------
[[0 (91%)]] --> [[1 (86%)]]

Inculpatul Brașevan Valerii, fiind preîntîmpinat de răspunderea penală pentru prezentarea cu bună știință a declarațiilor mincinoase, precum și posibilitatea refuzului de a depune declarații în privința fratelui său Brașevan Valentin Pavel, la 22.06.2011 în timpul interogării acestuia în CPS Rîșcani mun. [[Chișinău]] în calitate de martor în cadrul cauzei penale 2011021034, pornite la 20.05.2011 după semnele componenței de infracțiune prevăzute de art. 187 alin. 2 lit. f) Cod Penal al RM, a [[declarat]] că telefonul sustras de model „Nokia” recunoscut și anexat în calitate de corp delict în cauza menționată l-a preluat de la fratele său Brașevan Valentin, după care la 08.11.2011, fiind audiat în ședința de judecată pe aceiași cauză penală, și-a schimbat depozițiile și a declarat, că nu a preluat telefonul de model „Nokia” de la fratele său, dar a cumpărat un telefon mobil de model „Nokia” la piața de lîngă gara feroviară, aproximativ în luna mai 2011 și s-a folosit de el aproximativ o lună și jumătate. În şedinţa de judecată, [[inculpatul]] Brașevan Valerii vina a recunoscut şi a explicat că, în vara a.2011 a fost interogat în calitate de martor în cadrul dosarului penal de învinuire a fratelui său Braşevan Valentin Vladimir la CPs Rîşcani, şi el a spus atunci că, telefonul sustras de model „Nokia”, care era în acel dosar ca corp delict, i-a dăruit acel telefon fratele său. Ulterior pe aceiaşi cauză penală în şedinţa de judecată, fiind preîntîmpinat de răspundere penală în cazul de dare a declaraţiilor false şi de faptul că putea să nu dea mărturii deoarece inculpat era fratele său, el a spus că el nu a luat telefonul de model „Nokia” de la fratele său, dar că el a cumpărat acel telefon de la piaţa de la Gara Feroviară aproximativ în luna mai 2011 şi că el s-a folosit de acel telefon aproximativ o lună şi jumătate. De cele comise se căieşte. Pe lîngă explicaţiile lui Brașevan Valerii de recunoaştere a vinei, vina acestuia se mai dovedeşte și prin următoarele probe: Proces verbal de audiere a martorului Brașevan Valerii Pavel, din 22.06.2011 unde a declarat că, la moment locuiește cu soția sa pe nume Popova Aliona pe str. Mircea cel Bătrîn 28/1 ap.82, referitor la cazul dat ultimul a declarat că la mijlocul lunii mai anul 2011, fratele său pe nume Brașevan Valentin a venit în ospeție la el, timpul exact nu cunoaște, dar acesta a fost pînă la masă. Ultimii au început să discute despre serviciul lui Brașevan Valentin și la un moment dat, ultimul s-a interesat dacă lui Brașevan Valerii îi trebuie un telefon de model Nokia, culoare neagră cu ecranul deteriorat la care ultimul i-a răspuns că, dorește un astfel de telefon. După aceasta Brașevan Valerii l-a întrebat pe fratele său Brașevan Valentin de unde are acest telefon la care ultimul i-a răspuns că l-a găsit pe stradă, dar unde anume ultimul nu a comunicat. Tot în ziua respectivă, cînd Brașevan Valerii se gătea pentru a pleca la serviciu a întrodus în telefonul mobil de model Nokia cartela sim cu numărul 078384676. Brașevan Valerii mai adaugă că, pe lîngă

Inculpatul Brașevan Valerii, fiind preîntîmpinat de răspunderea penală pentru prezentarea cu bună știință a declarațiilor mincinoase, precum și posibilitatea refuzului de a depune declarații în privința fratelui său Brașevan Valentin Pavel, la 22.06.2011 în timpul interogării acestuia în CPS Rîșcani mun. [[Chișiănu]] în calitate de martor în cadrul cauzei penale 2011021034, pornite la 20.05.2011 după semnele componenței de infracțiune prevăzute de art. 187 alin. 2 lit. f) Cod Penal al RM, a [[delcarat]] că telefonul sustras de model „Nokia” recunoscut și anexat în calitate de corp delict în cauza menționată l-a preluat de la fratele său Brașevan Valentin, după care la 08.11.2011, fiind audiat în ședința de judecată pe aceiași cauză penală, și-a schimbat depozițiile și a declarat, că nu a preluat telefonul de model „Nokia” de la fratele său, dar a cumpărat un telefon mobil de model „Nokia” la piața de lîngă gara feroviară, aproximativ în luna mai 2011 și s-a folosit de el aproximativ o lună și jumătate. În şedinţa de judecată, [[inuclpatul]] Brașevan Valerii vina a recunoscut şi a explicat că, în vara a.2011 a fost interogat în calitate de martor în cadrul dosarului penal de învinuire a fratelui său Braşevan Valentin Vladimir la CPs Rîşcani, şi el a spus atunci că, telefonul sustras de model „Nokia”, care era în acel dosar ca corp delict, i-a dăruit acel telefon fratele său. Ulterior pe aceiaşi cauză penală în şedinţa de judecată, fiind preîntîmpinat de răspundere penală în cazul de dare a declaraţiilor false şi de faptul că putea să nu dea mărturii deoarece inculpat era fratele său, el a spus că el nu a luat telefonul de model „Nokia” de la fratele său, dar că el a cumpărat acel telefon de la piaţa de la Gara Feroviară aproximativ în luna mai 2011 şi că el s-a folosit de acel telefon aproximativ o lună şi jumătate. De cele comise se căieşte. Pe lîngă explicaţiile lui Brașevan Valerii de recunoaştere a vinei, vina acestuia se mai dovedeşte și prin următoarele probe: Proces verbal de audiere a martorului Brașevan Valerii Pavel, din 22.06.2011 unde a declarat că, la moment locuiește cu soția sa pe nume Popova Aliona pe str. Mircea cel Bătrîn 28/1 ap.82, referitor la cazul dat ultimul a declarat că la mijlocul lunii mai anul 2011, fratele său pe nume Brașevan Valentin a venit în ospeție la el, timpul exact nu cunoaște, dar acesta a fost pînă la masă. Ultimii au început să discute despre serviciul lui Brașevan Valentin și la un moment dat, ultimul s-a interesat dacă lui Brașevan Valerii îi trebuie un telefon de model Nokia, culoare neagră cu ecranul deteriorat la care ultimul i-a răspuns că, dorește un astfel de telefon. După aceasta Brașevan Valerii l-a întrebat pe fratele său Brașevan Valentin de unde are acest telefon la care ultimul i-a răspuns că l-a găsit pe stradă, dar unde anume ultimul nu a comunicat. Tot în ziua respectivă, cînd Brașevan Valerii se gătea pentru a pleca la serviciu a întrodus în telefonul mobil de model Nokia cartela sim cu numărul 078384676. Brașevan Valerii mai adaugă că, pe lîngă

[Succeeded / Failed / Skipped / Total] 8 / 6 / 2 / 16:  14%|█▍        | 14/100 [02:34<15:48, 11.02s/it]

--------------------------------------------- Result 15 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

xxxxNUMExxxx, la data de 28 februarie 2014, aproximativ la orele 02 00 , aflîndu‐se la domiciliul său din or. xxxxORAS_SATxxxx str. M. Sadoveanu în stare de ebrietate,țelegînd caracterul prejudiciabil al acțiunilor sale, acționînd intenționat, din motivul relațiilor ostile apărute spontan în rezult conflict cu fecior ău xxxxNUMExxxxadim Iurie i‐a aplicat o lovitură cu un cuțit de bucătărie în regiunea gîtului acestuia şi în consecință cauzîndu‐ traumatic hemoragic ca urmare aăgii tăiate înțepate a gîtului cu penetrare în cavitatea pleurală stînga cu lezarea vaselor sangvine de calibrul mare, stîng cu hemoragie maă internă‐externă şi în rezultatul cărora ultimul a decedat. Fiind audiat în ședința de judecată, inculpatul, xxxxNUMExxxx a recunoscut vina integral, declarînd că, la data de 28 februarie 2014, aproximativ 00 , aflîndu‐se la domiciliul său din or. xxxxORAS_SATxxxx str. M. Sadoveanu 16, fiind în stare de ebrietate, din motivul relațiilor ostile apărute sp rezultatul unui conflict cu fecior ău xxxxNUMExxxxadim Iurie i‐a aplicat o lovitură cu un cuțit de bucătărie în regiunea gîtului, iar ultimul a deceda u de cele comise Pînă la începerea cercetării judecătoreşti, inculpatul a declarat, personal prin înscris autentic, că recunoaşte săvîrşirea faptelor indicate în rechi solă ca judecata să se facă pe baza probelor administrate în faza de urmărire penală. Astfel, instanța de judecată prin încheierea protocolară din 2014, a accep ca judecata să se facă pe baza probelor administrate în faza de urmărire penală. Necătînd la faptul că inculpatul vinovăția a recunoscut, vinovăția acestuia în şedința de judecată se dovedeşte prin: ‐ Prin declarațiile succesorului părții vătămate, xxxxNUMExxxx care a explicat că, la 27 februarie 2014 au sărbătorit ziua de naştere a xxxxNUMExxxx. Lărbătoare au participat Stăvilă Anatolie, Sîrbu Vitalie, Fărîmă Vitalie şi Lilia, Hadîrcă Vitalie şi Eugenia, Frumusachi Igor şi Li Ludmşi Ion, soțul xxxxNUMExxxx şi fiul xxxxNUMExxxxadim. Oaspeții au plecat pe rînd, ultimii au plecat fratele sîu Sîrbu Vitalie, Frumuschi Igor vilă Anatolie, pe la orele 00.30 min. Ulterior ea strîngea masa, iar xxxxNUMExxxx şxxxxNUMExxxx Vadim discutau la masa din bucătărie. În timpul între ‐a iscat o ceartă şi anume Iurie îi zice lui Vadim că este un nimeni, că nu este căsătorit, că vrea nepoți, că nu se ocupă cu nimic. Prin cuvin xxxxNUMExxxxadim a fost înjosit, la ce ultim‐a reproşat şi încerca să‐i explice că are 26 de ani, că are planuri şi că se va căsători mai tîrziu. Ea vă siția se agravează i‐a făcut lui xxxxNUMExxxx observație şi i‐a spus să se liniştească că nu este corect. Iurie a început a‐l numi pe Vadim cu necenzurate, zicîn‐i că‐i un nimeni şi nu a obținut nimic în viață. Văzînd că Vadim îi reproşeză şi‐i explică inversul, xxxxNUMExxxx brusc a luat cuțit ă, care se afla în farfuria cu tort şi s‐a năpustit asupra lui Vadim. Vadim a încercat să‐l apuce de mîmă să‐i ia cuțitul, însă xxxxNUMExxxx i‐a loviă în regiunea gîtului. Grăjdiru Victoria văzînd cele întămplate a sărit peste masă la xxxxNUMExxxx să‐l oprească. Tot în acel moment ea i‐a a xxxxNUMExxxx lovituri pesteță şi cap, exact nu‐şi aminteşte locul. Văzînd că xxxxNUMExxxxadim îşi pierde cunoştința, a luat un


--------------------------------------------- Result 16 ---------------------------------------------
[[0 (84%)]] --> [[[SKIPPED]]]

xxxxNUMExxxx se învinuiește de către organul de urmărire penală pentru faptul că, în perioada de timp din 21.07.2014 și pînă pe data de 31.12.2014, aflîndu­se la domiciliul său de pe str., or.xxxxORAS_SATxxxx, unde locuiește împreună cu părinții B.A., născută în anul 1940 și xxxxNUMExxxxalentin , născut la 1936, periodic, avînd intenția directă de răfuială fizică cu caracter de violență în familie asupra părinților săi, fiind în stare de ebrietate, se adresa la b.a. și la xxxxNUMExxxxalentin cu cuvinte necenzurate și amenințări, le aplica lovituri cu pumnii peste diferite părți ale corpului, din care motive B.A. și xxxxNUMExxxxalentin le­au fost cauzate suferințe psihice și fizice, fiind nevoiți să părăsească domiciliul și să solicite ajutor. Astfel el, la data de 21.07.2014, în jurul orei 13.00, aflîndu­se la domiciliul din str.xxxxORAS_SATxxxx 5, or.xxxxORAS_SATxxxx și fiind în stare de ebrietate, i­a amenințat pe B.A. și xxxxNUMExxxxalentin cu omorul și răfuiala fizică, numindu­i cu cuvinte necenzurate, întinzîndu­i de haine, din care motixxxxNUMExxxx a fost nevoită să fugă de acasă. Ulterior, în aceiași zi, în jurul orei 18.00, continuîndu­și acțiunile sale criminale, aflîndu­se la domiciliul, fiind în stare de ebrietate, a lovit cu pumnii și picioarele în ușa și geamurile casei, i­a amenințat pe B.A. și xxxxNUMExxxxalentin cu răfuiala fizică, din care motixxxxNUMExxxx Anna a fost nevoită iarăși să fugă de acasă după ajutor. Tot el, la data de 31.10.2014, aflîndu­se la domiciliul din str.xxxxORAS_SATxxxx 5, or. xxxxORAS_SATxxxx și fiind în stare de ebrietate, i­a aplicat lui B.A. și xxxxNUMExxxxalentin mai multe lovituri cu pumnii în regiunea capului și i­a amenințat cu moartea, cauzîndu­le dureri fizice și suferințe psihice. Tot el, la data de 05.11.2014, în jurul orei 09.00, aflîndu­se la domiciliul din str. xxxxORAS_SATxxxx 5, or. xxxxORAS_SATxxxx și fiind în stare de ebrietate, i­a numit pe B.A.a și xxxxNUMExxxxalentin cu cuvinte necenzurate, i­a amenințat cu răfuială fizică și cu omorul, cauzîndu­le suferințe psihice, apoi i­a răsucit lui B.A. mîinile, cauzîndu­i dureri fizice, iar din motivul acțiunilor sale violente, xxxxNUMExxxxalentin Mihail a fost nevoit să fugă de acasă după ajutor. Tot el, pe data de 17.11.2014, în jurul orei 13.00, aflîndu­se la domiciliul din str. xxxxORAS_SATxxxx 5, or. xxxxORAS_SATxxxx și fiind în stare de ebrietate, a lovit cu pumnii și picioarele în ușă și geamurile casei, stricînd sticla ușii de la intrare, i­a amenințat pe B.A. și xxxxNUMExxxxalentin cu răfuiala fizică și omorul, continuîndu­și acțiunile sale deficiente insistent, pînă la sosirea colaboratorilor poliției, prin ce i­a cauzat lui B.A. și xxxxNUMExxxxalentin suferințe psihice. Tot el, pe data de 31.11.2014, în jurul orei 13.00, venind la domiciliul din str. xxxxORAS_SATxxxx 5, or. xxxxORAS_SATxxxx, fiind în stare de ebrietate, a amenințat­o pe Banco Ana cu răfuiala fizică și omorul, a îmbrîncit­o și izbit­o la pămînt, o trăgea pe ultima de haine pe podele, continuîndu­și acțiunile sale violente insistent, prin ce i­a cauzat A.B. dureri fizice și 1 suferințe psihice, fapte pentru care a fost pus sub învinuire în baza art. 201 alin. (2) lit. a) CP. La data de 23.03.2015, de către procurorul în procuratura xxxxORAS_SATxxxx, V.J. a fost înaintat instanței de judecată demers privind aplicarea măsurii preventive sub formă

[Succeeded / Failed / Skipped / Total] 9 / 6 / 2 / 17:  15%|█▌        | 15/100 [02:43<15:25, 10.89s/it]

--------------------------------------------- Result 17 ---------------------------------------------
[[1 (98%)]] --> [[0 (62%)]]

Inculpatul O. la 10 septembrie 2011, în jurul orei 08:30, deținînd permis de conducere a mijloacelor de transport categoria „B,C,” consumînd preventiv alcool și deplasîndu-se cu autoturismul de model „Citroen Jamper ” cu n/î C NM 543, pe traseul 174 km, în preajma cafenelei „Nistru” din or. Rezina, a fost stopat de colaboratorul de poliție a CPR Rezina Coval Nicolae și ulterior, fiind supus testului alcooscopic „Drager”, s-a stabilit că concentrația vaporilor de alcool în aerul expirat constituia 0,71 mg/l.Fiind condus la Spitalul raional Rezina și examinat de medicul de gardă M., potrivit procesului-verbal nr.92 al examinării medicale de constatare a faptului de consum a alcoolului, stări de ebrietate și naturii ei, s-a concluzionat „consum de alcool, treaz”. Fiindu-i propus să fie recoltate probe biologice pentru analiza de laborator, necesară pentru stabilirea stării de ebrietate și concentrației alcoolului în sînge, Odobesco Victor a refuzat categoric, prin ce a încălcat prevederile art.21 al Regulamentului privind modul de testate alcooscopică și examinare medicală pentru stabilirea stării de ebrietate și naturii ei, aprobat prin Hotărîrea Guvernului nr. 296 din 16.04.2009. În partea pregătitoare a şedinţei de judecată inculpatul O. a înaintat o cerere, conform [[căreea]] recunoaşte deplin vina în săvărşirea infracţiunii prevăzută de art. 2641 alin. (3 ) Cod Penal şi în temeiul art. 60 alin.(1) lit. a) Cod penal, art. 332 alin.(5) Cod de procedură penală solicită liberarea sa de răspunderea penală în legătură cu intervenirea termenului de prescripţie de tragere la răspundere penală. Apărătorul [[Lefter]] Stela a susţinut demersul înaintat de inculpatul O. şi a solicitat admiterea lui. Procurorul G.[[consideră]] că demersul urmează a fi satisfăcut, deoarece infracţiunea săvărşită de inculpatul O. este una uşoară, de la comiterea ei au trecut mai mult de doi ani şi conform art. 60 alin.(1) lit.a)Cod [[penal]] acesta urmează a fi liberat de răspundere penală. Ascultînd opiniile părţilor, studiind materialele dosarului, înstanţa de judecată [[consideră]] că [[procesul]] [[penal]] în privinţa inculpatului O. urmează a fi [[încetat]] din următoarele considerente. Potrivit art. 60 alin.(1) lit. a) Cod penal persoana se liberează de răspunderea penală dacă din ziua săvărşirii infracţiunii au expirat termenele de 2 ani de la săvărşirea unei infracţiuni uşoare. Prin acţiunile sale inculpatul O. la 10 septembrie 2011a săvîrşit o infracţiune mai puţin gravă şi acţiunile lui just a fost încadrate în baza art. 2641 alin.(3) Cod penal - refuzul conducătorului mijlocului de transport de la recoltarea probelor biologice în cadrul examenului medical în vederea stabilirii stării de ebrietate și naturii ei. Conform art. 332 alin.(1) CPP în cazul în care, pe parcursul judecării cauzei se constată că a intervenit termenul de prescripţie / art. 275 pct.4) CPP/ şi inculpatul solicită încetarea procesului penal, instanţa prin sentinţă motivată, încetează procesul penal în cauza respectivă. Din considerentele enunţate instanţa de judecată conchide că procesul penal în cauza lui Odobesco Victor privind învinuirea adusă în baza art. 2641 alin. (3 ) Cod penal urmează a fi încetat. În conformitate cu prevederile art. 60 alin.(1) lit. a) Cod penal, art.art. 275 pct.4), 332 alin.(1), 391 alin.(1) pct.6, 392-393, 394 alin.(4), 396 Cod de porcedură penală, instanţa de judecată ,-

Inculpatul O. la 10 septembrie 2011, în jurul orei 08:30, deținînd permis de conducere a mijloacelor de transport categoria „B,C,” consumînd preventiv alcool și deplasîndu-se cu autoturismul de model „Citroen Jamper ” cu n/î C NM 543, pe traseul 174 km, în preajma cafenelei „Nistru” din or. Rezina, a fost stopat de colaboratorul de poliție a CPR Rezina Coval Nicolae și ulterior, fiind supus testului alcooscopic „Drager”, s-a stabilit că concentrația vaporilor de alcool în aerul expirat constituia 0,71 mg/l.Fiind condus la Spitalul raional Rezina și examinat de medicul de gardă M., potrivit procesului-verbal nr.92 al examinării medicale de constatare a faptului de consum a alcoolului, stări de ebrietate și naturii ei, s-a concluzionat „consum de alcool, treaz”. Fiindu-i propus să fie recoltate probe biologice pentru analiza de laborator, necesară pentru stabilirea stării de ebrietate și concentrației alcoolului în sînge, Odobesco Victor a refuzat categoric, prin ce a încălcat prevederile art.21 al Regulamentului privind modul de testate alcooscopică și examinare medicală pentru stabilirea stării de ebrietate și naturii ei, aprobat prin Hotărîrea Guvernului nr. 296 din 16.04.2009. În partea pregătitoare a şedinţei de judecată inculpatul O. a înaintat o cerere, conform [[crăeea]] recunoaşte deplin vina în săvărşirea infracţiunii prevăzută de art. 2641 alin. (3 ) Cod Penal şi în temeiul art. 60 alin.(1) lit. a) Cod penal, art. 332 alin.(5) Cod de procedură penală solicită liberarea sa de răspunderea penală în legătură cu intervenirea termenului de prescripţie de tragere la răspundere penală. Apărătorul [[Letfer]] Stela a susţinut demersul înaintat de inculpatul O. şi a solicitat admiterea lui. Procurorul G.[[considreă]] că demersul urmează a fi satisfăcut, deoarece infracţiunea săvărşită de inculpatul O. este una uşoară, de la comiterea ei au trecut mai mult de doi ani şi conform art. 60 alin.(1) lit.a)Cod [[pneal]] acesta urmează a fi liberat de răspundere penală. Ascultînd opiniile părţilor, studiind materialele dosarului, înstanţa de judecată [[consiedră]] că [[proecsul]] [[peanl]] în privinţa inculpatului O. urmează a fi [[încteat]] din următoarele considerente. Potrivit art. 60 alin.(1) lit. a) Cod penal persoana se liberează de răspunderea penală dacă din ziua săvărşirii infracţiunii au expirat termenele de 2 ani de la săvărşirea unei infracţiuni uşoare. Prin acţiunile sale inculpatul O. la 10 septembrie 2011a săvîrşit o infracţiune mai puţin gravă şi acţiunile lui just a fost încadrate în baza art. 2641 alin.(3) Cod penal - refuzul conducătorului mijlocului de transport de la recoltarea probelor biologice în cadrul examenului medical în vederea stabilirii stării de ebrietate și naturii ei. Conform art. 332 alin.(1) CPP în cazul în care, pe parcursul judecării cauzei se constată că a intervenit termenul de prescripţie / art. 275 pct.4) CPP/ şi inculpatul solicită încetarea procesului penal, instanţa prin sentinţă motivată, încetează procesul penal în cauza respectivă. Din considerentele enunţate instanţa de judecată conchide că procesul penal în cauza lui Odobesco Victor privind învinuirea adusă în baza art. 2641 alin. (3 ) Cod penal urmează a fi încetat. În conformitate cu prevederile art. 60 alin.(1) lit. a) Cod penal, art.art. 275 pct.4), 332 alin.(1), 391 alin.(1) pct.6, 392-393, 394 alin.(4), 396 Cod de porcedură penală, instanţa de judecată ,-

[Succeeded / Failed / Skipped / Total] 10 / 6 / 2 / 18:  16%|█▌        | 16/100 [02:52<15:05, 10.78s/it]

--------------------------------------------- Result 18 ---------------------------------------------
[[0 (97%)]] --> [[1 (55%)]]

Prin încheierea judecătorului de instrucţie din 23.07.2015 s­a respins ca inadmisibilă [[plîngerea]] înaintată de [[Dogotari]] Alexandru în baza art. 313 Cod Procedură Penală privind contestarea ordonanței procurorului Lilia Selevestru din 29.05.2015. Nefiind de acord cu încheierea emisă, la data de 28.07.2015, Dogotari Alexandru a înaintat recurs, solicitînd anularea încheierii Judecătoriei Bălți din 23.07.2015 ca ilegală cu emiterea unei noi hotărîri în beneficiul său. În motivarea recursului a invocat că judecătorul de instrucție [[Eremciuc]] Ghenadie la examinarea cauzei a încălcat prevederile art. 313 alin. (1) Cod Procedură Penală, și anume el a tăinuit faptul că procurorul Lilia Selevestru a încălcat termenul de examinare pe cauza penală nr. B20159780008 din 19.05.2015 R­1, invocînd că el a primit ordonanța din 29.05.2015 a procuraturii Anticorupție cu o mare întîrziere și anume la 09.07.2015. Procurorul și judecătorul din Bălți au încălcat drepturile și interesele legitime prevăzute la art. 1,19 alin. (3), 95, 100,252, 254 Cod procedură Penală și nu a 1 1 fost efectuată de către aceștia o cercetare obiectivă și completă fiind încălcate prevederile art. 6 p.37 , 52 alin. (2) p.3 , 231, 255 Cod procedură penală. Dogotari Alexandru a refuzat să fie escortat în şedinţa instanței de recurs, totodată prezentînd cerere prin care susține recursul declarat, solicitînd examinarea cauzei în absența sa, Colegiul considerînd posibil și dispunînd judecarea recursului în lipsa lui. Avocatul Rotari Mihaela în ședința instanței de recurs a indicat că recursul înaintat este întemeiat, solicitînd admiterea acestuia cu anularea încheierii judecătorului de instrucție. În ședința instanței de recurs procurorul participant Lilia Selevestru a solicitat respingerea recursului, pe motiv că încheierea judecătorului de instrucție este irevocabilă și nu se supune căilor ordinare de atac, iar în afară de aceasta potrivit ordinii stabilite de [[legiuitor]] condamnatul nu a atacat ordonanța procurorului la procurorul ierarhic superior. Verificînd argumentele invocate în recurs în raport cu materialele cauzei şi cu prevederile legii, Colegiul penal consideră recursul inadmisibil şi pasibil de respins, cu menţinerea încheierii judecătorului de instrucţie din 23.07.2015 din următoarele considerente. Instanța de recurs menționează că, Codul de procedură penală prevede expres actele şi acţiunile organului de urmărire penală care pot fi atacate judecătorului de instrucţie. Conform art.313 alin.(1,2) CPP, [[plîngerile]] împotriva acţiunilor şi actelor ilegale ale organului de urmărire penală şi ale organelor care exercită activitate specială de investigaţii pot fi înaintate judecătorului de instrucţie de către bănuit, învinuit, apărător, partea vătămată, de alţi participanţi la proces sau de către alte persoane drepturile şi interesele legitime ale cărora au fost încălcate de aceste organe, în cazul în care persoana nu este de acord cu rezultatul examinării plîngerii sale de către procuror sau nu a primit răspuns la plîngerea sa de la procuror în termenul prevăzut de lege. (2) Persoanele indicate în alin.(1) sînt în drept de a ataca judecătorului de instrucţie: 1) refuzul organului de urmărire penală: a) de a primi plîngerea sau denunţul privind pregătirea sau săvîrşirea infracţiunii; b) de a satisface demersurile în cazurile prevăzute de lege; c) de a începe urmărirea penală; 2) ordonanţele privind încetarea urmăririi penale, clasarea cauzei penale sau scoaterea persoanei de sub urmărire penală; 3) alte acţiuni

Prin încheierea judecătorului de instrucţie din 23.07.2015 s­a respins ca inadmisibilă [[plîgnerea]] înaintată de [[Dogotrai]] Alexandru în baza art. 313 Cod Procedură Penală privind contestarea ordonanței procurorului Lilia Selevestru din 29.05.2015. Nefiind de acord cu încheierea emisă, la data de 28.07.2015, Dogotari Alexandru a înaintat recurs, solicitînd anularea încheierii Judecătoriei Bălți din 23.07.2015 ca ilegală cu emiterea unei noi hotărîri în beneficiul său. În motivarea recursului a invocat că judecătorul de instrucție [[Erecmiuc]] Ghenadie la examinarea cauzei a încălcat prevederile art. 313 alin. (1) Cod Procedură Penală, și anume el a tăinuit faptul că procurorul Lilia Selevestru a încălcat termenul de examinare pe cauza penală nr. B20159780008 din 19.05.2015 R­1, invocînd că el a primit ordonanța din 29.05.2015 a procuraturii Anticorupție cu o mare întîrziere și anume la 09.07.2015. Procurorul și judecătorul din Bălți au încălcat drepturile și interesele legitime prevăzute la art. 1,19 alin. (3), 95, 100,252, 254 Cod procedură Penală și nu a 1 1 fost efectuată de către aceștia o cercetare obiectivă și completă fiind încălcate prevederile art. 6 p.37 , 52 alin. (2) p.3 , 231, 255 Cod procedură penală. Dogotari Alexandru a refuzat să fie escortat în şedinţa instanței de recurs, totodată prezentînd cerere prin care susține recursul declarat, solicitînd examinarea cauzei în absența sa, Colegiul considerînd posibil și dispunînd judecarea recursului în lipsa lui. Avocatul Rotari Mihaela în ședința instanței de recurs a indicat că recursul înaintat este întemeiat, solicitînd admiterea acestuia cu anularea încheierii judecătorului de instrucție. În ședința instanței de recurs procurorul participant Lilia Selevestru a solicitat respingerea recursului, pe motiv că încheierea judecătorului de instrucție este irevocabilă și nu se supune căilor ordinare de atac, iar în afară de aceasta potrivit ordinii stabilite de [[legiutior]] condamnatul nu a atacat ordonanța procurorului la procurorul ierarhic superior. Verificînd argumentele invocate în recurs în raport cu materialele cauzei şi cu prevederile legii, Colegiul penal consideră recursul inadmisibil şi pasibil de respins, cu menţinerea încheierii judecătorului de instrucţie din 23.07.2015 din următoarele considerente. Instanța de recurs menționează că, Codul de procedură penală prevede expres actele şi acţiunile organului de urmărire penală care pot fi atacate judecătorului de instrucţie. Conform art.313 alin.(1,2) CPP, [[plîngeirle]] împotriva acţiunilor şi actelor ilegale ale organului de urmărire penală şi ale organelor care exercită activitate specială de investigaţii pot fi înaintate judecătorului de instrucţie de către bănuit, învinuit, apărător, partea vătămată, de alţi participanţi la proces sau de către alte persoane drepturile şi interesele legitime ale cărora au fost încălcate de aceste organe, în cazul în care persoana nu este de acord cu rezultatul examinării plîngerii sale de către procuror sau nu a primit răspuns la plîngerea sa de la procuror în termenul prevăzut de lege. (2) Persoanele indicate în alin.(1) sînt în drept de a ataca judecătorului de instrucţie: 1) refuzul organului de urmărire penală: a) de a primi plîngerea sau denunţul privind pregătirea sau săvîrşirea infracţiunii; b) de a satisface demersurile în cazurile prevăzute de lege; c) de a începe urmărirea penală; 2) ordonanţele privind încetarea urmăririi penale, clasarea cauzei penale sau scoaterea persoanei de sub urmărire penală; 3) alte acţiuni

[Succeeded / Failed / Skipped / Total] 11 / 6 / 2 / 19:  17%|█▋        | 17/100 [03:01<14:46, 10.69s/it]

--------------------------------------------- Result 19 ---------------------------------------------
[[1 (95%)]] --> [[0 (51%)]]

xxxxNUMExxxx, este învinuit în faptul că, în noaptea de 17.10.2014 spre 18.10.2014, aflîndu­se împreună cu cet. L. I. M., a.n.­­, locuitor s. U., raionul R., precum și minorul L. V. I., a.n. ­­, în locuința situată în s. U., raionul R., cu care au servit băuturi alcoolice, având scopul de ­l omoră, intenționat, cu o deosebită cruzime, i­au aplicat ultimului multiple lovituri cu pumnii și picioarele peste diferite ărți ale corpului, după care, cu ajutorul unui băț din lemn, pe care­l avea la sine, i­au aplicat cet. S. D.A., multiple lovituri, peste organele de importa ță vitală­cutie toracică și cap, astfel cauzîndu­i ultimului, conform raportului de examinare medico­legale nr. 115„c” din 20.10.2014, leziuni corporale GRAVE, periculoase pentru viața și sănătatea persoanei, sub formă de: Hemoragii în țesuturile moi percraniene, hemoragii subarahnoidiene, ruptuă postraumatică a [[aparatului]] ligamentar a vertebre II cervicale, echimoze, plăgi contuze pe diferite regiuni ale corpului, în rezultatul ărora ultimul a decedat. Prin acțiunile sale intenționate xxxxNUMExxxx a săvîrșit infracțiunea prevăzută și sancționată de prevederile art. 145 alin.(2) lit.i),j) Cod penal al R. Moldova (omorul inte ționat) cu indicii de calificare: omorul intenționat al unei persoane, săvîrșit de două persoane, cu deosebiă cruzime. La 18 octombrie 2014, de către organul de urmărire penală al IP R. pe [[cazul]] dat a fost pornită urmărirea penală cu nr. 2014300367, în baza elementelor constitutive ale infra ţiunii prevăzute de art. 145 alin. (2 lit. i), j) Cod penal.. La 18 octombrie 2014, la ora 13:15, xxxxNUMExxxx a fost reţinut în ordinea prevederilor art. 165­166 CPP al R. Moldova. La 21 octombrie 2014, xxxxNUMExxxx a fost pus sub învinuire de comitere a infracţiunii [[prevăzute]] de art.145 alin.(2) lit. i), j) Cod [[penal]] La 21 octombrie 2014, în [[privința]] învinuitului xxxxNUMExxxx a fost aplicată măsura preventivă­arestul preventiv, și eliberat mandat de arest pe un termen de 30 (treizeci) yile, din momentul r ținerii, pînă la 17 noiembrie 2014, ora 13:15. La data de 13 noiembrie 2014, în privința învinuitului xxxxNUMExxxx, a fost prelungită durata ținerii în stare de arest preventiv pe un termen de 30 zile, pî ă la data de 17 decembrie, ora 13:15. La data de 15 decedmbrie 2014, în privința învinuitului xxxxNUMExxxx, a fost prelungită durata ținerii în stare de arest preventiv pe un termen de 30 zile, pî ă la data de 16 ianuarie 2015, ora 13:15. La data de 06 ianuarie 2015, procurorul în procuratura raionului Rîșcani Victor Rauh a înaintat demers privind prelungirea duratei inerii sub arest preventiv a învinuitului xxxxNUMExxxx pentru o perioadă de 30 zile, invocînd următoarele motive: Actualmente la momentul reținerii organul de urmărire penală are suspiciuni că învinuitul ar putea să se ascundă de la prezența în f ța organului de urmărire penală, să împiedice stabilirea adevărului în procesul penal sau să săvîrșească acțiuni criminale asupra eventualilor martori și victime, să­i influințeze în continuare la darea depozițiilor false sau prin diferite metode ilegale să influențeze organul de ur ărire în vederea tărăgănării și examinării injuste a cazului. Conform datelor operative de investigație, care pot fi dezvăluite confidențial doar judecătorului de instrucție, precum celor rezultate din

xxxxNUMExxxx, este învinuit în faptul că, în noaptea de 17.10.2014 spre 18.10.2014, aflîndu­se împreună cu cet. L. I. M., a.n.­­, locuitor s. U., raionul R., precum și minorul L. V. I., a.n. ­­, în locuința situată în s. U., raionul R., cu care au servit băuturi alcoolice, având scopul de ­l omoră, intenționat, cu o deosebită cruzime, i­au aplicat ultimului multiple lovituri cu pumnii și picioarele peste diferite ărți ale corpului, după care, cu ajutorul unui băț din lemn, pe care­l avea la sine, i­au aplicat cet. S. D.A., multiple lovituri, peste organele de importa ță vitală­cutie toracică și cap, astfel cauzîndu­i ultimului, conform raportului de examinare medico­legale nr. 115„c” din 20.10.2014, leziuni corporale GRAVE, periculoase pentru viața și sănătatea persoanei, sub formă de: Hemoragii în țesuturile moi percraniene, hemoragii subarahnoidiene, ruptuă postraumatică a [[apartaului]] ligamentar a vertebre II cervicale, echimoze, plăgi contuze pe diferite regiuni ale corpului, în rezultatul ărora ultimul a decedat. Prin acțiunile sale intenționate xxxxNUMExxxx a săvîrșit infracțiunea prevăzută și sancționată de prevederile art. 145 alin.(2) lit.i),j) Cod penal al R. Moldova (omorul inte ționat) cu indicii de calificare: omorul intenționat al unei persoane, săvîrșit de două persoane, cu deosebiă cruzime. La 18 octombrie 2014, de către organul de urmărire penală al IP R. pe [[czaul]] dat a fost pornită urmărirea penală cu nr. 2014300367, în baza elementelor constitutive ale infra ţiunii prevăzute de art. 145 alin. (2 lit. i), j) Cod penal.. La 18 octombrie 2014, la ora 13:15, xxxxNUMExxxx a fost reţinut în ordinea prevederilor art. 165­166 CPP al R. Moldova. La 21 octombrie 2014, xxxxNUMExxxx a fost pus sub învinuire de comitere a infracţiunii [[prevzăute]] de art.145 alin.(2) lit. i), j) Cod [[pneal]] La 21 octombrie 2014, în [[pirvința]] învinuitului xxxxNUMExxxx a fost aplicată măsura preventivă­arestul preventiv, și eliberat mandat de arest pe un termen de 30 (treizeci) yile, din momentul r ținerii, pînă la 17 noiembrie 2014, ora 13:15. La data de 13 noiembrie 2014, în privința învinuitului xxxxNUMExxxx, a fost prelungită durata ținerii în stare de arest preventiv pe un termen de 30 zile, pî ă la data de 17 decembrie, ora 13:15. La data de 15 decedmbrie 2014, în privința învinuitului xxxxNUMExxxx, a fost prelungită durata ținerii în stare de arest preventiv pe un termen de 30 zile, pî ă la data de 16 ianuarie 2015, ora 13:15. La data de 06 ianuarie 2015, procurorul în procuratura raionului Rîșcani Victor Rauh a înaintat demers privind prelungirea duratei inerii sub arest preventiv a învinuitului xxxxNUMExxxx pentru o perioadă de 30 zile, invocînd următoarele motive: Actualmente la momentul reținerii organul de urmărire penală are suspiciuni că învinuitul ar putea să se ascundă de la prezența în f ța organului de urmărire penală, să împiedice stabilirea adevărului în procesul penal sau să săvîrșească acțiuni criminale asupra eventualilor martori și victime, să­i influințeze în continuare la darea depozițiilor false sau prin diferite metode ilegale să influențeze organul de ur ărire în vederea tărăgănării și examinării injuste a cazului. Conform datelor operative de investigație, care pot fi dezvăluite confidențial doar judecătorului de instrucție, precum celor rezultate din

[Succeeded / Failed / Skipped / Total] 11 / 7 / 2 / 20:  18%|█▊        | 18/100 [03:10<14:29, 10.60s/it]

--------------------------------------------- Result 20 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

XXse învinuieşte în aceia, că în a doua jumătate a zilei de 10 decembrie 2015, aflîndu­se la locuinţa familiei XXdin satul XXa, din intenţii de profit, avînd scopul sustragerii bunurilor altei persoane, a sustras pe ascuns dintr­o cutie de carton, bani în sumă totală de 1800 (una mie opt sute) lei. În rezultatul furtului dat proprietarului XX i­a fost cauzată o daună materială considerabilă. Acţiunile inculpatei XXau fost calificate de către organul de urmărire penală în baza art.186 alin.2 lit. d) Cod Penal, furtul, adică sustragerea pe ascuns a bunurilor altei persoane săvîrşite cu cauzarea de daune în proporţii considerabile. În partea pregătitoare a şedinţei de judecată partea vătămată XXa depus o cerere, solicitînd încetarea procesului penal de învinuire a lui XX în legătură cu împăcarea sa cu inculpata. Pretenţii materiale sau morale faţă XX nu are. Inculpata XX în ședința de judecată a confirmat faptul împăcării sale cu partea vătămată XX, acceptînd ca procesul penal, pornit împotriva sa fie încetat în legătură cu împăcarea. Potrivit dispoziei alin.(1) art.109 CP, împăcarea este actul de înlăturare a răspunderii penale pentru o infracţiune uşoară sau mai puţin gravă, infracţiuni prevăzute de de capitolul II­VI din Partea specială, precum şi în cazurile pervăzute de procedura penală. Sancţiunea alin.(2) art.186 prevede amendă în mărime de la 300 la 1000 unităţi convenţionale sau muncă neremunerată în folosul comunităţii de la 180 la 240 de ore, sau închisoare de pînă la 4 ani, şi conform art.16 CP, infracțiunea respectivă este considerată mai puţin gravă. În cazul dat, legea penală permite admite împăcarea părţilor. Procurorul a susţinut poziţia părţii vătămate şi a solicitat încetarea procesului penal. Pentru această soluţie a pledat şi apărătorul inculpatei. Din considerentele enunţate, instanţa de judecată conchide că procesul penal în cauza ce o privește pe MXX privind învinuirea adusă în baza art.186 alin.(2) lit.d) CP urmează a fi încetat. În temeiul celor elucidate şi expuse, călăuzindu­se de art.109 alin.1 CP, 340,384, 385, 391 al.1 pct1), art.392­394, 396 şi 397 CPP, instanţa de judecată,

[Succeeded / Failed / Skipped / Total] 11 / 8 / 2 / 21:  19%|█▉        | 19/100 [03:19<14:12, 10.52s/it]

--------------------------------------------- Result 21 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

La data de 23.02.2015, consilierul de probațiune din cadrul Biroului de Probațiune xxxxORAS_SATxxxx­V.Vacarciuc a înaintat un deners instanței de n judecată, prin care solicită anunțarea în căutare a condamnatului Brînză xxxxNUMExxxx, a.n.xxxxDATA_NASTERIIxxxx, domiciliat s.Răspopeni r.xxxxORAS_SATxxxx. Consilierul de probațiune V.Vacarciuc a invocat în demersul înaintat că, la data de 17.02.2014 în adresa Biroului de Probațiune xxxxORAS_SATxxxx a fost n expediată spre executare copia sentinței nr.1­3/2014 din 28.01.2014 emisă de Judecătoria Militară mun.Chișinău privind condamnarea, în baza art.188 alin.(2) lit.b), e), f) CP, a lui Brînză xxxxNUMExxxx stabilindu­i ca pedeapsă închisoare pe termen de 4 (patru)ani, cu suspendarea condiționată a pedepsei în conformitate cu prevederile art.90 Cod Penal pe un termen de probă de 5(cinci) ani, cu obigarea să nu­şi schimbe locul de trai fără acordul organului competent. Pe perioada ispășirii pedepsei, condamnatul Brînză Serghei Noicolai a încălcat obligațiunile și cerințele legale, neprezentîndu­se în termenii stabiliți la Biroul de n Probațiune xxxxORAțS_SATxxxx. Iar în urma măsurșilor dțe rigoare întreprinse de Biroul de Probațiune s­a constatat că condamnatul Brînză Serghei nu se află la domiciliu și este plecat într­o direcție necunoscută ț Consilierul de probaiune V. Vacarciuc, a solicită în edină de judecată admiterea demersului şi anunţarea în căutare a condamnatului Brînză Serghei. n Procurorul a susținut demersul reprezentantului Biroului de probaiune. n n Analizînd materialețle demersului, audiind opinia consilierșului de probațiune și cea a procurorului, instanţa consideră demȘersul întșemeiat şi necesar a fi satisfăcut deoarece sînt prezentate probe suficiente pentru confirmarea faptului că condamnatul Brînză xxxxNUMExxxx se ascunde de la organul care pune în executare sentina Judecătoriei Militare mun.Chișinău i anume : certificatul eliberat de primăria s. Răspopeni raionul oldăne ti, ce confirmă că condamnatul în timpul actual nșu se află pe teritoriul primăriei, şi raportul ispectorului de sector M.Timercan, potrivit căruia nici rudele apropiate nu cunosc locul aflării condamnatului Brînză Serghei. În baza celor expuse, de fapt i de drept, conform art. 469 p.10 ,470 – 472 , instanţa de judecată,­ n

[Succeeded / Failed / Skipped / Total] 12 / 8 / 2 / 22:  20%|██        | 20/100 [03:29<13:56, 10.46s/it]

--------------------------------------------- Result 22 ---------------------------------------------
[[0 (98%)]] --> [[1 (63%)]]

Prin sentinţa judecătoriei or. Căușeni din 04 iunie 2014, xxxxNUMExxxx a fost condamnat la muncă [[neremunerată]] în folosul comunităţii pe un termen de 160 ore, pentru comiterea infracţiunii prevăzute de art. 287al. (1) CP RM, din care el nu a executat nici o ora. În demersul înaintat, se solicită înlocuirea muncii neremunerate în folosul comunităţii,cu închisoarea motivînd cu faptul, că xxxxNUMExxxx se [[eschivează]] cu rea voinţă de la executarea pedepsei aplicate. În şedinţa de judecata consilierul de [[probatiune]] a susţinut demersul înaintat pe deplin. [[Condamnatul]] in sedinta de judecata nu s­a prezentat, desi a fost legal citat si nici n­a comunicat motivele [[neprezentarii]]. Nu a fost posibil de executat nici aducerea silita a [[condamnatului]] din motiv ca el a parasit locul de trai, de aceia instanta a decis examinarea cauzei in lipsa lui. Procurorul si aparatorul in sedinta de judecata au solicitat respingerea demersului ca fiind [[neintemeiat]]. [[Ascultînd]] consilierul de probatiune, apărătorul si procurorul,examinînd materialele cauzei,judecata consideră demersul intemeiat si care urmeaza a fi admis din urmatoarele considerente. Astfel,conform art.67 p.3 CP, condamnatilor ce se [[eschiveaza]] cu rea vointa de la executarea pedepsei sub forma de munca [[neremunerata]] in folosul comunitatii, pedeapsa aplicata, se inlocuieste cu inchisoare, calculindu­se o zi de inchisoare pentru 2 ore de munca neremunerata in folosul comunitatii. Conform Regulamentului cu privire la modul de executare a muncii neremunerate in folosul comunitatii,adoptat prin [[Hotarirea]] Guvernului nr.1643 din 31.12.2003,p. 33,se consideră eschivare cu rea voinţă de la executarea pedepsei sub formă de muncă neremunerată, neprezentarea la citarea serviciului de executare a condamnatului de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei,încălcarea de către [[condamnat]] a disciplinei muncii de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei (sosirea la locul de muncă cu întîrziere sau părăsirea acestuia înainte de termen, neexecutarea sau executarea intenţionat eronată a dispoziţiilor şi indicaţiilor persoanei responsabile de executarea lucrărilor etc. ,neprezentarea condamnatului la muncă fără motive întemeiate de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei. Conform art. 191 Cod de executare,condamnatul la munca neremunerată în folosul comunităţii este obligat să se prezinte la citare la organul de probaţiune, să respecte modul şi condiţiile de executare a pedepsei, regulamentul de ordine interioară a organizaţiei în care este antrenat la muncă, să lucreze conştiincios la obiectele la care a fost repartizat, să execute termenul de prestare a muncii neremunerate în folosul comunităţii, să informeze oficiul de executare despre schimbarea domiciliului sau despre imposibilitatea temporară de a presta munca. Aliniatul (2) al acestui articol stipuleaza ca dacă persoana condamnată la munca neremunerată în folosul comunităţii nu execută această pedeapsă sau, în timpul executării, are o conduită necorespunzătoare manifestată prin neîndeplinirea obligaţiilor care îi revin sau prin îndeplinirea lor defectuoasă, organul de probaţiune adresează instanţei de judecată un demers privind înlocuirea muncii neremunerate în folosul comunităţii cu o altă pedeapsă. In cazul dat,insa instanta de judecata considera,ca de catre Biroul de probatiune nu s­a dovedit faptul ca condamnatul xxxxNUMExxxx se eschiveaza cu rea vointa de la executarea pedepsei aplicate.Desi indata dupa

Prin sentinţa judecătoriei or. Căușeni din 04 iunie 2014, xxxxNUMExxxx a fost condamnat la muncă [[nreemunerată]] în folosul comunităţii pe un termen de 160 ore, pentru comiterea infracţiunii prevăzute de art. 287al. (1) CP RM, din care el nu a executat nici o ora. În demersul înaintat, se solicită înlocuirea muncii neremunerate în folosul comunităţii,cu închisoarea motivînd cu faptul, că xxxxNUMExxxx se [[eschievază]] cu rea voinţă de la executarea pedepsei aplicate. În şedinţa de judecata consilierul de [[porbatiune]] a susţinut demersul înaintat pe deplin. [[Condmanatul]] in sedinta de judecata nu s­a prezentat, desi a fost legal citat si nici n­a comunicat motivele [[neprezentairi]]. Nu a fost posibil de executat nici aducerea silita a [[cnodamnatului]] din motiv ca el a parasit locul de trai, de aceia instanta a decis examinarea cauzei in lipsa lui. Procurorul si aparatorul in sedinta de judecata au solicitat respingerea demersului ca fiind [[neinetmeiat]]. [[Asclutînd]] consilierul de probatiune, apărătorul si procurorul,examinînd materialele cauzei,judecata consideră demersul intemeiat si care urmeaza a fi admis din urmatoarele considerente. Astfel,conform art.67 p.3 CP, condamnatilor ce se [[eschivezaa]] cu rea vointa de la executarea pedepsei sub forma de munca [[neremunreata]] in folosul comunitatii, pedeapsa aplicata, se inlocuieste cu inchisoare, calculindu­se o zi de inchisoare pentru 2 ore de munca neremunerata in folosul comunitatii. Conform Regulamentului cu privire la modul de executare a muncii neremunerate in folosul comunitatii,adoptat prin [[Hotariera]] Guvernului nr.1643 din 31.12.2003,p. 33,se consideră eschivare cu rea voinţă de la executarea pedepsei sub formă de muncă neremunerată, neprezentarea la citarea serviciului de executare a condamnatului de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei,încălcarea de către [[condanmat]] a disciplinei muncii de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei (sosirea la locul de muncă cu întîrziere sau părăsirea acestuia înainte de termen, neexecutarea sau executarea intenţionat eronată a dispoziţiilor şi indicaţiilor persoanei responsabile de executarea lucrărilor etc. ,neprezentarea condamnatului la muncă fără motive întemeiate de două sau mai multe ori timp de o jumătate din termenul stabilit al pedepsei. Conform art. 191 Cod de executare,condamnatul la munca neremunerată în folosul comunităţii este obligat să se prezinte la citare la organul de probaţiune, să respecte modul şi condiţiile de executare a pedepsei, regulamentul de ordine interioară a organizaţiei în care este antrenat la muncă, să lucreze conştiincios la obiectele la care a fost repartizat, să execute termenul de prestare a muncii neremunerate în folosul comunităţii, să informeze oficiul de executare despre schimbarea domiciliului sau despre imposibilitatea temporară de a presta munca. Aliniatul (2) al acestui articol stipuleaza ca dacă persoana condamnată la munca neremunerată în folosul comunităţii nu execută această pedeapsă sau, în timpul executării, are o conduită necorespunzătoare manifestată prin neîndeplinirea obligaţiilor care îi revin sau prin îndeplinirea lor defectuoasă, organul de probaţiune adresează instanţei de judecată un demers privind înlocuirea muncii neremunerate în folosul comunităţii cu o altă pedeapsă. In cazul dat,insa instanta de judecata considera,ca de catre Biroul de probatiune nu s­a dovedit faptul ca condamnatul xxxxNUMExxxx se eschiveaza cu rea vointa de la executarea pedepsei aplicate.Desi indata dupa

[Succeeded / Failed / Skipped / Total] 13 / 8 / 3 / 24:  21%|██        | 21/100 [03:39<13:44, 10.44s/it]

--------------------------------------------- Result 23 ---------------------------------------------
[[0 (96%)]] --> [[1 (52%)]]

1.1.***** în noaptea de 09.08.2018 în jurul orelor 02:00, aflîndu-se în s. Grigorăuca, r-nul Sîngerei, acționînd în scopul răpirii mijlocului de transport, în comun cu minorii ***** (în privința cărora dosarul este disjungat pentru examinare într-o procedură separată) profitînd de faptul că nu sunt observați de [[cineva]] au răpit autocamionul de model ”Mercedes Vito 112C” cu numărul de înmatriculare FUE 746 de culoare albastru închis, în valoare de 80 000 lei, ce-i aparține lui *****, care era parcat în ograda casei, cheile acestuia fiind în lacătul de la ușă. ***** împreună cu minorii ***** (în privința cărora dosarul este disjungat pentru examinare într-o procedură separată) s-au folosit de aceste autocamion după propriul lor plac [[pînă]] la 09.08.2018 orele 06:00 cînd epuizînd carburanții l-au abandonat în preajma s. Hîrtopul Mare, r-nul Criuleni. 1.2.Tot, el împreună și de comun acord cu minorul *****, în noaptea de 20.03.2019 spre 21.03.2019, au pătruns în biserica sat. Flămînzeni r-nul Sîngerei, de unde prin deteriorarea ușii unui dulap unde se păstrau surse bănești a [[bisericii]], pe ascuns au sustras 3 200 euro, echivalentul a 62 688 lei și 54 000 lei, prin ce i-au cauzat victimei un prejudiciu material în proporții considerabile în sumă de 116 688 lei. 1.3.Tot el, împreună și de comun acord cu minorul ***** în noaptea de 20.03.2019 spre 21.03.[[2019]], folosindu-se de faptul că nu sunt observați de [[nimeni]], prin spargerea geamului au pătruns în [[biserica]] „Sf. Ar. Gavriil și Mihail” din sat. Coșcodeni r-nul Sîngerei, de unde pe ascuns au sustras 10 000 lei, prin ce i-au cauzat [[victimei]] un prejudiciu material în proporții [[considerabile]] în sumă de 10 000 lei. 1.4.Tot el, împreună și de comun acord cu [[minorul]] ***** la data de 22.03.[[2019]] aproximativ în jurul orelor 00:30 min., urmărind scopul sustragerii [[bunurilor]] altei persoane, [[folosindu-se]] de faptul că nu sunt observați de nimeni, prin deteriorarea ferestrei au pătruns în biserica „Sf. Nicolai” din sat. Chișcăreni r-nul Sîngerei, de unde au încercat să sustragă pe ascuns mai multe bunuri din biserică, acțiuni însă, care nu și-au produs efectul din motive independente de voința făptuitorilor și anume din motivul că au fost observați de către o persoană, astfel ne permițându-le realizarea scopului de a sustrage bunurile, totodată determinându-i să înceteze acțiunile sale ilegale. 2.ANALIZA PROBELOR. Fiindcă cauza s-a judecat în procedura simplificată, prevăzută de art.364/1 CPP pe baza probelor administrate în faza de urmărire penală, instanţa de judecată a analizat următoarele probe prezentate de procuror şi acceptate de inculpatul minor şi care demonstrează integral vinovăţia acestuia: 2.1.EPISODUL RĂPIRII MIJLOCULUI DE TRANSPORT FĂRP SCOP DE ÎNSTRĂINARE DE LA GADÎRCA GHEORGHE. -declarațiile părții vătămate ***** depuse în cadrul urmăririi și din care în esență rezultă că din primăvara anului 2015 are în proprietate un autocamion de model ”Mercedes Vito 112C” cu n/î FUE 746 de culoare albastru închis, care valorează aproximativ 80 000 lei. În seara de 08 august 2018 a parcat acest mijloc de transport în ograda casei. A doua zi dimineața, în jurul orelor 05:00 fiul său trezindu-l din somn i-a comunicat că autocamionul lipsește în ogradă și respectiv a fost răpit.

1.1.***** în noaptea de 09.08.2018 în jurul orelor 02:00, aflîndu-se în s. Grigorăuca, r-nul Sîngerei, acționînd în scopul răpirii mijlocului de transport, în comun cu minorii ***** (în privința cărora dosarul este disjungat pentru examinare într-o procedură separată) profitînd de faptul că nu sunt observați de [[cinvea]] au răpit autocamionul de model ”Mercedes Vito 112C” cu numărul de înmatriculare FUE 746 de culoare albastru închis, în valoare de 80 000 lei, ce-i aparține lui *****, care era parcat în ograda casei, cheile acestuia fiind în lacătul de la ușă. ***** împreună cu minorii ***** (în privința cărora dosarul este disjungat pentru examinare într-o procedură separată) s-au folosit de aceste autocamion după propriul lor plac [[pnîă]] la 09.08.2018 orele 06:00 cînd epuizînd carburanții l-au abandonat în preajma s. Hîrtopul Mare, r-nul Criuleni. 1.2.Tot, el împreună și de comun acord cu minorul *****, în noaptea de 20.03.2019 spre 21.03.2019, au pătruns în biserica sat. Flămînzeni r-nul Sîngerei, de unde prin deteriorarea ușii unui dulap unde se păstrau surse bănești a [[bsiericii]], pe ascuns au sustras 3 200 euro, echivalentul a 62 688 lei și 54 000 lei, prin ce i-au cauzat victimei un prejudiciu material în proporții considerabile în sumă de 116 688 lei. 1.3.Tot el, împreună și de comun acord cu minorul ***** în noaptea de 20.03.2019 spre 21.03.[[2109]], folosindu-se de faptul că nu sunt observați de [[nimnei]], prin spargerea geamului au pătruns în [[bsierica]] „Sf. Ar. Gavriil și Mihail” din sat. Coșcodeni r-nul Sîngerei, de unde pe ascuns au sustras 10 000 lei, prin ce i-au cauzat [[vitcimei]] un prejudiciu material în proporții [[considreabile]] în sumă de 10 000 lei. 1.4.Tot el, împreună și de comun acord cu [[minroul]] ***** la data de 22.03.[[2109]] aproximativ în jurul orelor 00:30 min., urmărind scopul sustragerii [[buunrilor]] altei persoane, [[foloisndu-se]] de faptul că nu sunt observați de nimeni, prin deteriorarea ferestrei au pătruns în biserica „Sf. Nicolai” din sat. Chișcăreni r-nul Sîngerei, de unde au încercat să sustragă pe ascuns mai multe bunuri din biserică, acțiuni însă, care nu și-au produs efectul din motive independente de voința făptuitorilor și anume din motivul că au fost observați de către o persoană, astfel ne permițându-le realizarea scopului de a sustrage bunurile, totodată determinându-i să înceteze acțiunile sale ilegale. 2.ANALIZA PROBELOR. Fiindcă cauza s-a judecat în procedura simplificată, prevăzută de art.364/1 CPP pe baza probelor administrate în faza de urmărire penală, instanţa de judecată a analizat următoarele probe prezentate de procuror şi acceptate de inculpatul minor şi care demonstrează integral vinovăţia acestuia: 2.1.EPISODUL RĂPIRII MIJLOCULUI DE TRANSPORT FĂRP SCOP DE ÎNSTRĂINARE DE LA GADÎRCA GHEORGHE. -declarațiile părții vătămate ***** depuse în cadrul urmăririi și din care în esență rezultă că din primăvara anului 2015 are în proprietate un autocamion de model ”Mercedes Vito 112C” cu n/î FUE 746 de culoare albastru închis, care valorează aproximativ 80 000 lei. În seara de 08 august 2018 a parcat acest mijloc de transport în ograda casei. A doua zi dimineața, în jurul orelor 05:00 fiul său trezindu-l din somn i-a comunicat că autocamionul lipsește în ogradă și respectiv a fost răpit.


--------------------------------------------- Result 24 ---------------------------------------------
[[1 (95%)]] --> [[[SKIPPED]]]

xxxxNUMExxxx, fiind în stare de iresponsabilitate a comis fapta prejudiciabilă vătămarea intenţionată gravă a integrităţii corporale, care a provocat decesul victimei în următoarele circumstanţe. xxxxNUMExxxx la 09.07.2011 ora 23:10 aflîndu­se în odaia nr.7 blocul 3 a internatului psihoneurologic din m.Bălţi str. 4, în ospeţie la cet.Boguş Ion, aflîdu­se în stare de ebrietate alcoolică, în procesul conflictului apărzt între ei, l­a lovit de cîteva ori în regiunea corpului, după ce victim a căzut şos şi folosindu­se de aceasta, xxxxNUMExxxx a continuat să­i provoace vătămări lui Boguş Ion, lovindu­l cu piciorul în regiunea gîtului, cauzîndu­i potrivit raprtului de expertiză medico­legală nr. 279D din 27.07.2011, leziuni corporale sub formă de echimoză masivă pe partea anterioară a gîtului cu răspîndire pe regiunea toracală, hemoragii difuze pronunţate în ţesuturile moi ale gîtului, fractura aschiată a cartilajului ureodian cu deplasare, hemoragii sub pleurale şi sub epicardiene, care au adus la decesul victimei prin asfexie mecanică prin comprimare /lovire/. Prin acţiunile sale xxxxNUMExxxx a săvîrşit infracţiunea prevăzută de art.151 al.(4) Cod penal ­ vătămarea intenţionată gravă a integrităţii corporale, care este periculoasă pentru viaţă şi a provocat decesul victimei. Comiterea faptei prejudiciabile de către xxxxNUMExxxx este dovedită şi confirmată prin: ­depoziţiile reprezentantului legal al persoanei iresponsabile – Goncear Nina, care a menţionat că lucrează medic la internatului psihoneurologic din m.Bălţi str. 4. xxxxNUMExxxx este beneficiarul instituţiei medicale, adică pacientă, prezintă diagnosticul “retard mintal sever”. La fel şi Boguş Ion a fost beneficiarul instituţiei medicale, adică pacient. Despre moartea violentă a cet. Boguş Ion din iulie 2011, a menţionat că cadavrul acestuia a fost depistat în odaia nr.7 blocul 3 a internatului psihoneurologic din m.Bălţi str. 4. xxxxNUMExxxx, cît şi alţi pacienţi mergeau în ospeţie unul la altul, inclusiv şi la Boguş Ion, care avea bani, ţigări, poate că şi alcool, ce­l vindea la pacienţi pe ascuns, deoarece conform regulilor se interzice consumul de alcool pe terituriul instituţiei. Presupune că xxxxNUMExxxx şi Boguş Ion erau în relaţii mai aproape, inclusiv intime. În convorbire cu xxxxNUMExxxx, acesta i­a spus că a la lovit pe Boguş Ion, dar nu ţine minte amănuntele conflictului. xxxxNUMExxxx în situaţii de criză prezintă periol, poate manifesta violenţă /f.d.___/. ­depoziţiile martorului Chiatol Lilia, care a declarat că lucrează la internatul psihoneurologic din m.Bălţi str. 4 şi adat delaraţii similare declaraţiilor reprezentantului legal a inculpatei Goncear Nina /f.d.142­143/. ­depoziţiile martorului reprezentantului părţii vătămate BoguşxxxxNUMExxxx, care a relatat că este sora victimei Boguş Ion, fratele s­a aflat ca pacient la internatului psihoneurologic din m.Bălţi str. 4, deoarece suferea de boli mintale. Despre moartea violentă a fratelui său cet. Boguş Ion a aflat în iulie 2011 cadavrul acestuia a fost depistat în odaia sa din instutuţia medicală vizată. Circumstanţele decesului nu le cunoaşte /f.d.141­143, 190/. ­depoziţiile martorului Şaptefraţi Galina, făcute la organul de urmărire penală şi citite în cadrul şedinţei de judecată, care a declarat că este pacientă al internatului psihoneurologic din m.Bălţi str. 4, este în relaţii bune cu xxxxNUMExxxx şi locuiesc într­o odaie. La 09.07.2011 ora 17:00 ea cu xxxxNUMExxxx s­au dus în ospeţie la Boguş Ion,car ia dat bani şi a trimis­o să cumpere o sticlă de

[Succeeded / Failed / Skipped / Total] 13 / 9 / 3 / 25:  22%|██▏       | 22/100 [03:54<13:50, 10.65s/it]

--------------------------------------------- Result 25 ---------------------------------------------
[[0 (86%)]] --> [[[FAILED]]]

XXXXXXXXX la data de 25.06.2013 aproximativ la ora 11.00 împreună cu Preida Vasili, au procurat de la cet. Andrieş Alexandru o cantitate nestabilită a substanţelor narcotice sub formă de marihuană, iar ulterior aflîndu­se în apropierea Dispanserului Ftiziologic, pe strada Ştefan cel Mare din mun. Bălţi, contra sumei de 100 lei au înstrăinat lui Dubovicov Maxim substanţele narcotice procurate ilegal, din care ultimul o parte a consumat personal, iar o altă parte, a predat benevol colaboratorilor de poliţie, sub formă de masă vegetală uscată, mărunţită de culoare verde, care conform raportului de expertiză nr.1663 din 05.07.2013, reprezintă marihuana, cu greutatea de 1,1 gr., în care a fost depistat componentul narcotic activ – tetrahydrocannabinol, prin urmare se atribuie către substanţele narcotice. Marihuana – este inclusă în lista Nr.1, tabelul Nr.1 „Substanţele narcotice, substanţele psohotrope neutilizate în scopuri medicale aprobată prin Hotărîrea Guvernului R.Moldova Nr.1088 din 05.10.2004 şi lista “Substanţelor narcotice, psihotrope şi a plantelor car conţin astfel de substanţe, depistate în trafic ilicit, precum şi cantităţile acestora” aprobată prin Hotărîrea Guvernului nr.79 di 25.01.2006. XXXXXXXXX la data de 25.06.2013 aproximativ la ora 11.00 împreună cu Groşovan Roman, au procurat de la cet.Andrieş Alexandru o cantitate nestabilită a substanţelor narcotice sub formă de marihuană, iar ulterior aflîndu­se în apropierea Dispanserului Ftiziologic, pe strada Ştefan cel Mare, mun. Bălţi contra sumei de 100 lei au înstrăinat lui Dubovicov Maxim substanţele narcotice procurate ilegal, din care ultimul o parte a consumat personal, iar o altă parte, a predat benevol colaboratorilor de poliţie, sub formă de masă vegetală uscată, mărunţită de culoare verde, care conform raportului de expertiză nr.1663 din 05.07.2013, reprezintă marihuana, cu greutatea de 1,1 gr., în care a fost depistat componentul narcotic activ – tetrahydrocannabinol, prin urmare se atribuie către substanţele narcotice. Marihuana – este inclusă în lista Nr.1, tabelul Nr.1 „Substanţele narcotice, substanţele psohotrope neutilizate în scopuri medicale” aprobată prin Hotărîrea Guvernului R.Moldova Nr.1088 din 05.10.2004 şi lista “Substanţelor narcotice, psihotrope şi a plantelor care conţin astfel de substanţe, depistate în trafic ilicit, precum şi cantităţile acestora” aprobată prin Hotărîrea Guvernului nr.79 din 25.01.2006. Inculpatul Preida Vasili Nicolae, după cum s­a constatat în cadrul cercetării judecătoreşti, la data de 23 august 2014, a decedat, fapt confirmat prin extrasul din Registrul de Stat al Populaţiei. Instanţa de judecată a dispus judecarea în continuare a cauzei de învinuire a dînsului cu participarea avocaţilor: XXXXXXXXX şi Rodica Palade. Inculpatul Groşovan Roman în cadrul şedinţei de judecată vina şi­a recunoscut­o integral, declarînd instanţei următoarele: Dînsul în perioada verii anului 2013 se afla la tratament la Dispensarul Ftiziologic din mun. Bălţi; tot acolo se trata şi Preida Vasili, însă într­o altă secţie. În ziua respectivă de ei, care se aflau afară şi fumau împreună cu mai mulţi băieţi, s­a apropiat Dubovicov Maxim care a întrebat dacă poate procura marihuana. Pentru 50 lei, i­a vîndut lui Dubovicov Maxim o cantitate de marihuană care era pusă într­o cutie de chibrituri; această cantitate a luat de la un moş pe nume Andrieş care se afla atunic la fel în spital la tratament. A precizat că afară împreună cu mai mulţi băieţi, la

[Succeeded / Failed / Skipped / Total] 13 / 10 / 3 / 26:  23%|██▎       | 23/100 [04:09<13:56, 10.86s/it]

--------------------------------------------- Result 26 ---------------------------------------------
[[1 (95%)]] --> [[[FAILED]]]

Cet. CURTEAN GHENADIE este învinuit de organul de urmărire penală în aceia că el în perioada de timp al anilor 2009 ­ luna mai 2010, aflându­se în mun.Bălți, acționând în comun acord cu alte persoane nestabilite de organul de urmărire penală, în scopul exploatării sexuale comerciale, prin abuz de poziţia de vulnerabilitate a victimelor, datorită situaţiei precare a acestora, din punct de vedere a supravieţuirii sociale şi prin înșelăciune, sub pretextul angajării la un lucru bine plătit în calitate de dansatoare, le­a recrutat pe Solonari Anna Valeri, născută la 26.11.1986 şi Sugac (Eremciuc) Alexandra, născută la 05.12.1990. Ulterior, cet. Curtean Ghenadie, acționând în comun acord cu alte persoane neidentificate de către organul de urmărire penală, întru realizarea intențiilor sale infracționale, aproximativ la 05.05.2010 a organizat transportarea cet.Sugac (Eremciuc) Alexandra şi Solonari Anna în or.Peatigorsc, Federaţia Rusă, pentru exploatare sexuală. Ajungând în or. Peatigorsc, Sugac (Eremciuc) Alexandra şi Solonari Anna au fost transmise de către Curtean Ghenadie persoanei nestabilite pe nume „Aşot”, care le­a transportat în or.Essentuki, Federaţia Rusă şi le­a adăpostit într­un hotel, confiscând pașapoartele acestora, de unde ultimele regulat au fost transferate către deferiți beneficiari de servicii intime, fiind exploatate sexual aproximativ o lună jumătate. Ulterior, Eremciuc Alexandra şi Solonari Anna, împreună cu paşapoartele lor au fost transmise de către persoana nestabilită pe nume „Aşot”, persoanei nestabilite pe nume „Liliana”, care le­a transportat şi adăpostit într­o saună din același oraş, unde ultimele regulat au fost transferate către deferiți beneficiari, fiind exploatate sexual aproximativ o lună. Aceste acţiuni ale lui Curtean Ghenadie au fost calificate de organul de urmărire penală ca infracţiune prevăzută de art.165 alin.(2) lit.b),d) Cod penal, traficul de fiinţe umane, adică recrutarea, transportarea unei persoane, cu consimţământul acesteia, în scop de exploatare sexuală comercială, săvîrşită prin confiscare a documentelor, precum și prin înșelăciune și abuz de poziţie de vulnerabilitate, de mai multe personae, asupra a mai multe persoane. Tot Curtean Ghenadie, este învinuit de organul de urmărire penală în aceia că el în perioada lunilor martie ­ mai 2010, aflându­se în mun. Bălţi, acţionând în comun acord cu alte persoane nestabilite de organul de urmărire penală, în scopul organizării practicării prostituţiei de către alte persoane pe teritoriul Federaţiei Ruse, a îndemnat şi înlesnit practicarea prostituţiei, prin acordarea contra plată a unor servicii sexuale de către cet. Dibijeva (Daraban) Vera Anatolie, născută la 01.12.1988. Ulterior cet.Curtean Ghenadie, acționând în comun acord cu alte persoane neidentificate de către organul de urmărire penală, întru realizarea intenţiilor sale infracționale, aproximativ la 05.05.2010 a organizat transportarea cet.Dibijeva (Daraban) Vera în or. Peatigorsc, Federaţia Rusă, pentru practicarea prostituției. Ajungând în or. Peatigorsc, Dibijeva (Daraban) Vera a fost transmisă de către Curtean Ghenadie persoanei nestabilite pe nume „Aşot”, care a transportat­o în or.Essentuki, Federaţia Rusă, unde ultima a practicat prostituția aproximativ 2 săptămâni. Aceste acţiuni ale lui Curtean Ghenadie au fost calificate de organul de urmărire penală ca infracţiune prevăzută de art.220 alin.(2) lit.a),c) Cod penal, proxenetism, adică îndemnul şi înlesnirea practicării prostituţiei de către alte persoane, acţiuni săvîrşite de două sau mai multe persoane, asupra a două sau mai multor persoane. În şedinţa de judecată

[Succeeded / Failed / Skipped / Total] 13 / 11 / 3 / 27:  24%|██▍       | 24/100 [04:23<13:55, 11.00s/it]

--------------------------------------------- Result 27 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Prin sentința nominalizată instanța a reținut, că la 22 decembrie 2013, aproximativ pe la orele 20.00, XXX XXX, aflîndu­se în incinta magazinului nr.2 ce aparţine ’’Universcoop Drochia”, amplasat în or.Drochia str.Cecal a scos din buzunarul hainei un cuţit, s­a repezit spre vînzătoarea magazinului XXX XXX a.n. 19XX, ameninţînd­o cu cuţitul dat pe care l­a îndreptat înspre ea în regiunea pieptului, însă el nu şi­a dus acţiunile sale pînă la realizare, deoarece a fost îmbrîncit de către vînzătoarea magazinului, care a fugit afară chemînd în ajutor. Ameninţările lui XXX XXX ­ pătimita XXX XXX, în circumstanţele date le­a perceput ca reale. În şedinţa instanței de fond inculpatul XXX XXX nu a fost prezent, din motive necunoscute, fiind respectată citarea legală, fiind supus aducerii silite, s­a constat că ultimul a părăsit domiciliul şi a plecat într­o direcţie necunoscută. Instanţa considerînd necesar de a examina cauza penală pe învinuirea lui XXX XXX în lipsa inculpatului deoarece ultimul intenţionat s­a ascuns de la prezentarea în instanța de judecată. Examinarea cauzei fiind cu participarea avocatului inculpatului Alexandru Covdii. Apreciind în ansamblu probele administrate în şedinţa judiciară, instanța a conchis, că vinovăţia lui XXX XXX este dovedită integral, în aceia că a comis infracțiunea prevăzută de art. 155 Cod penal al RM, deoarece amenințarea a fost reală. La stabilirea categoriei și termenului pedepsei prima instanță a ținut cont de prevederile art. 75 Cod penal și circumstanțele cauzei, ajungînd la concluzia că corectarea și reeducarea lui XXX XXX este posibilă cu numirea unei pedepse cu aplicarea art. 90 Cod penal. Împotriva sentinței instanței de fond, în termen la 17.06.2015, a declarat cerere de apel avocatul Guțu Tatiana în interesele inculpatului XXX XXX, pe motivul ilegalității sentinței. În apelul declarat se solicită admiterea apelului, casarea sentinței și dispunerea rejudecării cauzei date. În argumentarea apelului a indicat următoarele: concluziile instanței privind sustragerea lui XXX de la examinarea cauzei sunt eronate, dat fiind faptul, că ultimul nu a fost citat legal la locul său de trai, din declarațiile martorului XXX XXX, mama inculpatului pe care o solicită a fi audiată în calitate de martor se va constata, că anterior nu au fost recepționate la domiciliu careva citații din instanța de judecată, iar colaboratorii de poliție i­au vizitat la domiciliu doar după primirea sentinței; XXX XXX este o persoană ce se afla la evidenţa medicului psihiatru avînd dereglări de personalitate, fapt ce şi a făcut imposibilă participarea inculpatului la examinare cauzei, reieşind din circumstanțele create ultimul pe motiv de boală s­a aflat în mănăstire, loc în care se simte bine, însă deoarece colaboratorii de poliţe nu au vizitat la domiciliu inculpatul în s. Şuri r. Drochia, informația despre locul aflării acestuia nu a fost adusă la cunoștința instanței de judecată; instanţa făcînd trimitere la prevederile procesual legale prevăzute de art. 321 al.2 CPP, a indicat posibilitatea judecării cauzei în lipsa inculpatului şi anume cînd inculpatul se ascunde de la participarea în instanţă, pentru aplicarea acestor prevederi consideră, că instanţă de judecată urma iniţial să dispună căutarea lui XXX XXX şi numai după ce avea probe incontestabile despre faptul că ultimul se ascunde, să

[Succeeded / Failed / Skipped / Total] 13 / 12 / 4 / 29:  25%|██▌       | 25/100 [04:38<13:54, 11.12s/it]

--------------------------------------------- Result 28 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

La data de , în jurul orei inculpatul ără a deţine permis de conducere, fiind în stare de ebrietate alcoolică, încălcînd cerinţele art. 14 lit. a) al Regulamentului Circulaţiei Rutiere: coătorului de vehicul îi este interzis să conducă vehiculul dacă a consumat băuturi alcoolice, droguri sau alte substanţe contraindicate conducerii, ce se află sub influenţa preparatelor medicamentoase care duc la reducereaţiei”, s­a urcat la volanul automobilului de model „MS” şi conducîndu­l pe centura or. S, a fost stopat de colaboratorii poliţie i în exercţiul funcţiei. Ulterior, fiind suspectat de conducerea vehiculului în stare de ebrietate alcoolică a fost verificat cu aparatul „D A” care a indicat vaporii în aer expirat în volum de 0,85 mg/l care conform art. 134/12 CP costituie starea de ebrietate ală cu grad avansat. Prțiunile sale intenționate, inculpatul XXXXXXXXX a comis conducerea mijlocului de transport de către o persoană care se află în stare de ebrietate alcoolică cu grad avansat şită de către o persoană care nu deţine permis de conducere, faptă prejudiciabilă prevăzută de art. 264/1 alin. (4) Cod Penal. În cședinței de judecată, inculpatul XXXXXXXXX a înaintat o cerere prin care a solicitat examinarea cauzei în ordinea prevederilor art. 364/1 Cod procedură penală, deoarec recşte în totalitate săvârșirea faptelor indicate în rechizitoriu şi solicită examinarea cauzei penale în privința acestora în baza probelor administrate în faza de urmărire penală. Apărătorul inculpatului XXXXXXXXX a susținut cererea înaintată de inculpat și a solicitat ca examinarea cauzei să fie petrecută în ordinea prevăzută de art. 364/1 pro ă penală. Procurorul XXXXXXXXX nu a invocat careva obiecții și a solicitat examinarea cauzei în baza probelor administrate în faza de urmărire penală, dat fiind faptul că incul recşte vina și probele administrate la dosarul penal. Avînd în vedere faă inculpatul XXXXXXXXX își recunoaşte integral vina și solicită ca judecarea cauzei să se facă în baza probelor administrate în faza de urmărire penală, iar alte probe, care ar putea fi administrate la materialele cauzei penale nu dispune, ița de judecată, asigurîndu­se că din probele administrate în cursul urmăririi penale reiese că fa inculpatului sunt stași sunt suficiente date cu privire la persoana sa, a admis demersul inculpatului şi a dispus examinarea cauzei în ordinea prevederilor art. 364/1 CPP, totodat inculpatului ­i explicate consecințele opțiunii sale. tînd la faptul că inculpatul XXXXXXXXX recunoaşte vina în comiterea infracţiunii prevăzute de art. 264/1 alin. (4) Cod Penal, vina inculpatului se demonstrează prin probele administrate în cadruăririi penale şi anume: ţinutul declaraţiilor martorului XXXXXXXXX A care, în cadrul urmăririi penale, a declarat că la 18 iulie 2016, se afla în exerciţiul funcţiunii împreună cu II al PP al S­F Regim„N”, XXXXXXXXX pe str. O, din or. S şi anume centura or. Soroca, pe traseul M­2. În jurul orei 17:10colaboratorii de poliţie pe traseu au stopat automobilul de model ­S” cu nr./în. . Şoferul autoturismului s­a dovedit a fi XXXXXXXXX, a.n. XXXXXXXXX, domiciliat în or. Soroca, str. Burebista 6. Din discuţie cu acesta, martorul XXXXXX ţit un miros puternic de alcool, din cavitatea bucală astfel conducătorului i­a fost propus să respire în aparatul „D”, pentru verificarea concentraţiei


--------------------------------------------- Result 29 ---------------------------------------------
[[1 (97%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse mai sus instanţa de fond a reţinut, că xxxxNUMExxxx, la data de 12.07.2013, aproximativ pe la orele 07.20, fiind în stare de ebrietate, deținînd permisul de conducere cu nr.095800482 din 10.03.2009 pe categoria „B”, conducea automobilul de model „Opel­Vectra” cu n/î EDBF 716, deplasîndu­se prin orașul Edineț, cercul cu sens giratoriu „Gordinești”, unde a fost stopat de către IIPR al plutonului Edineț­Briceni­Ocnița, compania Nr.2, sergentul major de poliție V.Tabuica. Bănuind că șoferul xxxxNUMExxxx a consumat alcool, acesta a fost condus la SP Edineț pentru supunerea unei examinări medicale pentru stabilirea stării de ebrietate și conform acestei examinări, xxxxNUMExxxx se află în stare de ebrietate în timpul conducerii automobilului. Pentru stabilirea gradului de alcoolemie de la el a fost colectat sînge intravenos. Conform raportului cu nr.1131 de cercetare medico­legală toxicologică s­a constatat că în sîngele lui xxxxNUMExxxx s­a depistat alcool etilic în cantitate de 1,1% 1,1g/l și concentrația vaporilor de alcool în aerul expirat este 0,40 mg/l, ce corespunde stării de ebrietate cu grad avansat. Sentinţa a fost atacată cu recurs de către avocatul Gheorghii Radeanu în interesele inculpatului xxxxNUMExxxx, care consideră sentința instanței de fond ilegală. În motivarea recursului indică, că conform art.134/12 Cod penal RM (în vigoare din 26.10.2013), prin stare de ebrietate alcoolică cu grad avansat se înțelege starea persoanei care are concentrația de alcool în sînge de la 1,0g/l și mai mult sau concentrația de alcool în aerul expirat de la 0,5 mg/l și mai mult. La xxxxNUMExxxx concentrația de alcool în aerul expirat a fost depistat în mărime de 0,4 mg/l. Astfel consideră că în cazul dat xxxxNUMExxxx urma să fie atras la răspundere administrativă conform art.233 al.(1) Cod contravențional cu încetarea procesului penal. În recurs se solicită admiterea recursului, casarea sentinţei Judecătoriei Edineţ din 20.11.2013, recalificarea acțiunilor lui xxxxNUMExxxx conform art.233 al.(1) Cod Contravențional, cu încetarea procesului administrativ în legătură cu expirarea termenului de prescripție. În şedinţa instanţei de recurs avocatul Martin Vasile, care l­a asistat pe inculpat, a susţinut recursul şi a solicitat admiterea lui în sensul declarat. Inculpatul xxxxNUMExxxx a susținut recursul declarat și a solicitat admiterea acestuia în sensul declarat de avocat. Procurorul participant Valeriu Dubăsari a solicitat respingerea recursului declarat de avocat, cu menținerea sentinței instanței de fond fără careva modificări. Verificînd argumentele invocate în recursul declarat prin prizma probelor administrate şi în raport cu materialele cauzei penale prezentate instanţei, audiind opiniile participanţilor la proces, Colegiul penal ajunge la concluzia, că recursul declarat este nefondat şi urmează a respins. Conform art.449 al.(1) pct.1) lit.a) CPP, judecînd recursul, instanţa de recurs respinge recursul, menţinînd hotărîrea atacată, dacă recursul este nefondat. Judecînd cauza penală în privinţa lui xxxxNUMExxxx, instanţa de fond a verificat complet, sub toate aspectele şi în mod obiectiv circumstanţele cauzei şi a dat probelor administrate o apreciere legală din punct de vedere al pertinenţei, concludenţei, utilităţii şi veridicităţii lor, iar toate în ansamblu din punct de vedere al coroborării lor, corect ajungînd la concluzia privind vinovăţia inculpatului în fapta incriminată şi făcînd o încadrare juridică justă a acţiunilor lui în baza învinuirii aduse prevăzute

[Succeeded / Failed / Skipped / Total] 13 / 13 / 4 / 30:  26%|██▌       | 26/100 [04:53<13:56, 11.30s/it]

--------------------------------------------- Result 30 ---------------------------------------------
[[1 (97%)]] --> [[[FAILED]]]

De către organul de urmărire penală Cojocari Maxim Grigore, este învinuit precum că, urmărind scopul comiterii infracțiunii de contrabandă în vederea obținerii unui profit nejustificat, rezultat din săvârșirea infracțiunii, în perioada anului 2018, fiind în înțelegere prealabilă, de comun acord şi împreună cu persoane nestabilite de organul de urmărire penală, au elaborat un plan criminal în vederea trecerii peste frontiera vamală a Republicii Moldova a mărfurilor în proporții deosebit de mari, prin nedeclarare şi tăinuire de controlul vamal pentru a fi înstrăinate terțelor persoane. Astfel, în perioada lunilor ianuarie - mai 2018, în vederea realizării intențiilor sale criminale, conform rolurilor stabilite în baza planului anterior întocmit cu persoane neidentificate de organul de urmărire penală, prin intermediul unor însoțitori de vagon al trenului de pe ruta internațională “Moscova-Chișinău” au expediat din or. Moscova, Federația Rusă pentru a fi transportate în Republica Moldova, prin nedeclarare și tăinuire de controlul vamal un laptop marca “Macbook Pro”, 13 inch, model “MPXV2LL/A” anul fabricării 2017, număr de serie: C02VMGG3HV2L; căști fără fir “Airpods” - 1 unit; două telefoane mobil model ‘‘iPhone X” cu memoria de 256 GB; un laptop marca “Macbook Pro”, 13 inch, model “MPXQ2LL/A” anul fabricării 2017; un laptop marca “Macbook Pro”, 15 inch, model “MPTT2LL/A” anul fabricării 2017, număr de serie: C02W5AYYHTD6; un laptop marca “Macbook Pro”, 15 inch, model “MPTT2LL/A” anul fabricării 2017, număr de serie: C02VQBPOHTD6; un laptop marca “Macbook Pro”, 13 inch, anul fabricării 2017, cu memoria de 256 GB; un laptop marca “Macbook Pro”, 13 inch, model “MPXQ2LL/A” anul fabricării 2017, valoarea în vamă a cărora potrivit Raportului Secției reglementări tarifare și netarifare a biroului vamal Centru constituie 173 637,40 lei, mărfuri care au fost procurate din Federația Rusă de către Cojocari Maxim Grigore și alte persoane nestabilite de organul de urmărire penală prin intermediul magazinelor on-line specializate și care au fost recepționate de către Cojocari Maxim Grigore, după ce au fost introduse prin postul vamal “Vălcineț (PVFI feroviar)” prin nedeclarare și tăinuire de controlul vamal, fiind ulterior comercializate de către cel din urmă mai multor persoane fizice, prin intermediul anunțurilor publicate pe panoul de publicitate www.999.md. În aceeași perioadă de timp, Cojocari Maxim Grigore a mai organizat introducerea pe teritoriul Republicii Moldova a unui magic mouse număr serie: CC281060KG2J51XAZ; căști fără fir “Airpods” număr serie: FWYWKC4JH8TT; căști fără fir “Airpods” număr serie: GFHW14RSH8TT; căști fără fir “Airpods” număr serie:FWYWJMULH8TT; căști fără fir “Airpods” număr serie: GFDVXAN0H8TT; unui media Player “Apple TV” număr serie: C07W2X7HJ1WF; unui media Player “Apple TV” număr serie: C07W2D49J1WF; unui quadrocopter “DJI Mavic Air” model “U11X” număr serie: 0K1DF141AD37SP; unui notebook “Macbook Pro” Space Gray 512 GB .model “MPTT2LL/A” număr serie: C02W36URHTD6; unui smartwach “Aple Watch” model “3 series 42 mm Space Gray Aluminium Black Sport BAnd (GPS) MQL12LL/A” număr serie: FHLWD3N1J5X4; unui smartwach “Aple Watch” model “3 series 42 mm Space Gray Aluminium Black Sport Band (GPS) MQL12LL/A” număr serie: FHLW9MSPJ5X4; unui calculator “iMac” model MNE92RU/A, 27 inch, număr serie: C02VT6AGJ1GG; unui smartwach “Aple Watch” model “3 series 38 mm Space Gray Al Black Sport (GPS+Cellular) MQKH2B/A” număr serie: FHVR83EJ6GT; unui smartwach “Aple Watch” model

[Succeeded / Failed / Skipped / Total] 14 / 13 / 4 / 31:  27%|██▋       | 27/100 [04:59<13:30, 11.10s/it]

--------------------------------------------- Result 31 ---------------------------------------------
[[1 (98%)]] --> [[0 (60%)]]

Inculpatul xxxxNUMExxxx, în perioada lunii ianuarie a anului 2014, acţionînd cu intenţie, prin înşelăciune şi abuz de încredere, sub pretextul reparaţiei automobilului, [[proprietatea]] lui xxxxNUMExxxx, ilegal a dobîndit de la ultimul bani în sumă de 200 euro, echivalent a 3800 lei, prin ce i­a cauzat părţii vătămate xxxxNUMExxxx pagubă materială în sumă totală de [[3800]] lei. Acţiunile inculpatului au fost încadrate de către organele de urmărire penală în baza art.190 al.(1) Cod penal RM. Inculpatul xxxxNUMExxxx, în şedinţa de judecată, a recunoscut integral vina, a declarat că de cele comise se căieşte sincer. Partea [[vătămată]] xxxxNUMExxxx, în şedinţa de judecată, a [[depus]] cerere scrisă, prin care [[cere]] [[încetarea]] [[procesului]] penal în privinţa inculpatului xxxxNUMExxxx, indicînd că s­a împăcat cu inculpatul, nu are pretenţii faţă de inculpat. Vinovăţia inculpatului în comiterea infracţiunii a fost stabilită în şedinţa de judecată, găsindu­şi confirmare în materialele cauzei, după cum urmează: ­ plîngerea părţii vătămate (f.d.3,6); ­ proces­verbal de audiere a părţii vătămate (f.d.15); ­ proces­[[verbal]] de confruntare din 24.07.2014 (f.d.35­36); ­ procese­[[verbale]] de audiere a martorilor, care coroborate cu celelalte probe scrise anexate la materialele dosarului sînt probe concludente, pertinente şi utile cauzei. Instanţa reţine că, fapta inculpatului există, este comisă de acesta şi întruneşte elementele constitutive ale infracţiunii prevăzute de art.190 al.(1) Cod penal RM, escrocheria, adică dobîndirea ilicită a bunurilor altei persoane prin înşelăciune sau abuz de încredere. Avînd în vedere faptul că, [[partea]] vătămată s­a împăcat cu inculpatul, infracţiunea comisă este clasificată mai puţin gravă, iar conform art.109 al.(1) Cod penal RM, împăcarea este actul de înlăturare a răspunderii penale pentru o infracţiune uşoară sau mai puţin gravă, instanţa de judecată ajunge la concluzia că, [[procesul]] [[penal]] în privinţa lui xxxxNUMExxxx urmează de încetat. În temeiul celor expuse, conform art.109 alin.(1) CP RM, art.art.275, 332, 384­385, 394, 396 CPP RM, instanţa de judecată

Inculpatul xxxxNUMExxxx, în perioada lunii ianuarie a anului 2014, acţionînd cu intenţie, prin înşelăciune şi abuz de încredere, sub pretextul reparaţiei automobilului, [[prporietatea]] lui xxxxNUMExxxx, ilegal a dobîndit de la ultimul bani în sumă de 200 euro, echivalent a 3800 lei, prin ce i­a cauzat părţii vătămate xxxxNUMExxxx pagubă materială în sumă totală de [[3080]] lei. Acţiunile inculpatului au fost încadrate de către organele de urmărire penală în baza art.190 al.(1) Cod penal RM. Inculpatul xxxxNUMExxxx, în şedinţa de judecată, a recunoscut integral vina, a declarat că de cele comise se căieşte sincer. Partea [[vătmăată]] xxxxNUMExxxx, în şedinţa de judecată, a [[dpeus]] cerere scrisă, prin care [[cree]] [[îcnetarea]] [[procesuuli]] penal în privinţa inculpatului xxxxNUMExxxx, indicînd că s­a împăcat cu inculpatul, nu are pretenţii faţă de inculpat. Vinovăţia inculpatului în comiterea infracţiunii a fost stabilită în şedinţa de judecată, găsindu­şi confirmare în materialele cauzei, după cum urmează: ­ plîngerea părţii vătămate (f.d.3,6); ­ proces­verbal de audiere a părţii vătămate (f.d.15); ­ proces­[[vrebal]] de confruntare din 24.07.2014 (f.d.35­36); ­ procese­[[verable]] de audiere a martorilor, care coroborate cu celelalte probe scrise anexate la materialele dosarului sînt probe concludente, pertinente şi utile cauzei. Instanţa reţine că, fapta inculpatului există, este comisă de acesta şi întruneşte elementele constitutive ale infracţiunii prevăzute de art.190 al.(1) Cod penal RM, escrocheria, adică dobîndirea ilicită a bunurilor altei persoane prin înşelăciune sau abuz de încredere. Avînd în vedere faptul că, [[pratea]] vătămată s­a împăcat cu inculpatul, infracţiunea comisă este clasificată mai puţin gravă, iar conform art.109 al.(1) Cod penal RM, împăcarea este actul de înlăturare a răspunderii penale pentru o infracţiune uşoară sau mai puţin gravă, instanţa de judecată ajunge la concluzia că, [[prcoesul]] [[peanl]] în privinţa lui xxxxNUMExxxx urmează de încetat. În temeiul celor expuse, conform art.109 alin.(1) CP RM, art.art.275, 332, 384­385, 394, 396 CPP RM, instanţa de judecată

[Succeeded / Failed / Skipped / Total] 14 / 14 / 4 / 32:  28%|██▊       | 28/100 [05:14<13:29, 11.24s/it]

--------------------------------------------- Result 32 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Prin încheierea Judecătoriei Soroca din 12.06.2014 a fost respins demersul sefului Penitenciarului nr.6 Soroca privind stabilirea termenului de pedeapsă a condamnatului xxxxNUMExxxx ca neîntemeiat. În termen încheierea instanţei a fost contestată cu recurs de către condamnatul xxxxNUMExxxx, care solicită corectarea erorilor admise de instanța de judecată, cu aplicarea prevederilor art.84 al.4 CP și nu prevederile art.85 CP RM prin care a fost condamnat. În instanţa de recurs condamnatul xxxxNUMExxxx a declarat că nu este de acord cu încheierea instanţei de judecată. Avocatul Gligor Vadim în şedinţa instanţei de recurs a susținut recursul și a solicitat admiterea lui, deoarece instanţa de fond nu a soluţionat cererea adresată de administraţia penitenciarului. În instanţa de recurs procurorul Dubăsari Valeriu a solicitat admiterea recursului din alte motive decît cele invocate de condamnat, cu casarea încheierii și dispunerea rejudecării cauzei în prima instanță în alt complet de judecată. Audiind participanţii la proces, verificînd argumentele invocate în recurs şi verificînd legalitatea şi temeinicia încheierii atacate, Colegiul penal ajunge la concluzia că recursul declarat de condamnat urmează a fi admis, cu casarea încheierii contestate, din alte motive decît cele invocate, cu remiterea cauzei la rejudecare reeşind din următoarele considerente. Conform art. 449 al.1 p.2 lit.c CPP RM judecînd recursul, instanţa adoptă una din următoarele decizii: 2) admite recursul, casînd hotărîrea, parţial sau integral, şi ia una din următoarele soluţii: c) dispune rejudecarea cauzei de către instanţa de fond dacă este necesară administrarea de probe suplimentare. Colegiul penal conchide, că la examinarea demersului şefului Penitenciarului nr.6 Soroca privind stabilirea termenului de pedeapsă a condamnatului xxxxNUMExxxx, instanţa de fond nu a respectat normele procesuale şi nu a verificat complet şi în mod obiectiv circumstanţele cauzei, de fapt nu a soluţionat fondul demersului. Din materialele prezentate pentru verificare rezultă, că administrația Penitenciarului nr.6 Soroca, unde își execută pedeapsa condamnatul xxxxNUMExxxx, la 22.04.2014 a înaintat demers în fața instanței prin care solicită verificarea timpului aflării în stare de arest inclus în termenul de pedeapsă condamnatului, conform sentinței de condamnare a Judecătoriei Soroca din 04.10.2013 lui xxxxNUMExxxx i­a fost inclus timpul aflării în stare de arest de la 04.10.2013, însă conform procesului­verbal de reținere xxxxNUMExxxx a fost reținut la 17.04.2013. Colegiul penal ţine să menţioneze în sensul dat, că conform art.88 al.3 CP RM timpul aflării persoanei sub arest preventiv pînă la judecarea cauzei se include în termenul închisorii, calculîndu­se o zi pentru o zi, iar în termenul muncii neremunerate în folosul comunităţii – calculîndu­se o zi de arest preventiv pentru 2 ore de muncă neremunerată în folosul comunităţii. Prin sentința Judecătoriei Soroca din 04.10.2013 xxxxNUMExxxx a fost condamnat în baza art.186 al.2 lit.b,c,d CP RM, art.85 CP RM cu stabilirea pedepsei definitive 3 ani 2 luni închisoare în penitenciar de tip închis, termenul de pedeapsă fiind calculat din 04.10.2013. Colegiul penal constată, că instanța de fond eronat a motivat referitor la soluționarea corectării erorii solicitate privind aplicarea art.84 al.4 CP RM şi 85 CP RM, de fapt prin demersul administrației Penitenciarului nr.6 Soroca fiind solicitată verificarea includerii timpului aflării în stare de arest al inculpatului, care nici nu a fost examinat în fond.

[Succeeded / Failed / Skipped / Total] 15 / 14 / 4 / 33:  29%|██▉       | 29/100 [05:28<13:25, 11.34s/it]

--------------------------------------------- Result 33 ---------------------------------------------
[[0 (100%)]] --> [[1 (54%)]]

La 09 noiembrie 2013, aproximativ la ora 1200, [[xxxxNUMExxxx]] aflîndu­se pe lotul său de teren arabil, situat la marginea satului, în aproierea traseului [[Rezina]] ­ [[Orhei]], ca urmare a unui conflict apărut între el şi consăteanul xxxxCUSTOM1xxxx Serghei, i­a aplicat ultimului trei lovituri cu pumnul în regiunea feţei, cauzîndu­i astfel părţii vătămate xxxxCUSTOM1xxxx Serghei potrivit concluziei raportului de expertiză medico­legală nr.498 D din 22.12.2014 o vătămare medie sub formă de: fractură dublă a [[madibulei]] stîngi cu deplasare. [[Pînă]] la începerea cercetării judecătorești, [[inculpatul]] xxxxNUMExxxx s­a adresat către instanță cu o cerere în scris, prin care a solicitat ca judecata să se facă în baza probelor administrate la faza de urmărire penală, menționînd că [[recunoaște]] [[necondițonat]] fapta incriminată și nu solicită administrarea de probe noi. Avocatul A.M susținut cererea depusă de către [[inculpat]]. Judecarea cauzei, în baza probelor administrate la faza urmăririi penale a fost acceptată și de către procuror. Potrivit probelor anexate la dosar, fapta [[incriminată]] inculpatului se dovedește incontestabil, din care considerente instanța a admis cererea acestuia privind judecarea cauzei în baza probelor administrate în faza de urmărire penală. [[Audiat]] pe marginea învinuirii înaintate de către organul de urmărire penală, potrivit regulilor de audiere a martorului, [[inculpatul]] xxxxNUMExxxx a declarat instanței, că la data de 09 noiembrie [[2013]] s­a înțeles cu [[tractoristul]] M I să­i are cota de teren arabil. Fiind vecini cu terenurile, urma să plece în cîmp și xxxxCUSTOM1xxxx Serghei, dar ultimul n­a fost de găsit acasă. Împreună cu fiul său cel mic a plecat la cota de teren. I­a atătat tractoristului sectorul său, continuînd să rămînă acolo. Între timp a venit și S.xxxxCUSTOM1xxxx. Anterior a avit cu el neînțelegeri, privitor la hotar. A [[măsurat]] cu [[pasul]] și i­a [[arătat]] că cu patru metri a trecut hotarul. Fiind în stare de ebrietate S.[[xxxxCUSTOM1xxxx]], care ave în mîni o [[lopată]], l­a [[înjurat]] și l­a înjosit. N­ a putut să se abțină și i­a [[aplicat]] 3 ori cu pumnul în regiunea [[feței]]. El s­a urcat în căruță să plece. [[Calul]] s­a [[speriat]] și s­a izbit, el căzînd jos. [[Peste]] [[două]] săptămîni de la polițist a aflat că S.xxxxCUSTOM1xxxx s­a adresat la poliție. Recunoaște că leziunile corporale stabilite la S.xxxxCUSTOM1xxxx i­au fost pricinuite în urma acțiunilor sale. Regretă cele întîmplate și promite că nu v­a mai comite așa fapte. Este de acord, în baza documentelor, să­i restituie lui S.xxxxCUSTOM1xxxx cheltuielile pentru tratament. Și­a cerut scuze de la partea vătămată, acesta depunînd cerere de împăcare la poliție, iar mai tîrziu și­a retras­o. De rînd cu declarațiile sale din ședința de judecată, vina inculpatului xxxxNUMExxxx în comiterea infracțiunii de care se învinuiește se mai dovedește prin materialele dosarului penal, și anume: ­depoziţiile părţii vătămate xxxxCUSTOM1xxxx Serghei, potrivit cărora, la 09.11.2013 aproximativ la ora 1200 în timp ce se afla pe terenul său arabil situat lîngă Cuizăuca raionul Rezina, a venit consăteanul său xxxxNUMExxxx pentru a­şi ara terenul arabil care se mărgineşte cu al său. În timpul discuţiei s­au referit la delimitarea terenurilor arabile, în urma la ce între ei s­a iscat o ceartă, în rezultatul căruia ambii sau numit cu cuvinte înjurioase. Ulterior, V.M

La 09 noiembrie 2013, aproximativ la ora 1200, [[xxxNxUMExxxx]] aflîndu­se pe lotul său de teren arabil, situat la marginea satului, în aproierea traseului [[Reizna]] ­ [[Orehi]], ca urmare a unui conflict apărut între el şi consăteanul xxxxCUSTOM1xxxx Serghei, i­a aplicat ultimului trei lovituri cu pumnul în regiunea feţei, cauzîndu­i astfel părţii vătămate xxxxCUSTOM1xxxx Serghei potrivit concluziei raportului de expertiză medico­legală nr.498 D din 22.12.2014 o vătămare medie sub formă de: fractură dublă a [[maidbulei]] stîngi cu deplasare. [[Pnîă]] la începerea cercetării judecătorești, [[icnulpatul]] xxxxNUMExxxx s­a adresat către instanță cu o cerere în scris, prin care a solicitat ca judecata să se facă în baza probelor administrate la faza de urmărire penală, menționînd că [[recnuoaște]] [[necodnițonat]] fapta incriminată și nu solicită administrarea de probe noi. Avocatul A.M susținut cererea depusă de către [[inculapt]]. Judecarea cauzei, în baza probelor administrate la faza urmăririi penale a fost acceptată și de către procuror. Potrivit probelor anexate la dosar, fapta [[incrmiinată]] inculpatului se dovedește incontestabil, din care considerente instanța a admis cererea acestuia privind judecarea cauzei în baza probelor administrate în faza de urmărire penală. [[Aduiat]] pe marginea învinuirii înaintate de către organul de urmărire penală, potrivit regulilor de audiere a martorului, [[inculaptul]] xxxxNUMExxxx a declarat instanței, că la data de 09 noiembrie [[2103]] s­a înțeles cu [[tractorsitul]] M I să­i are cota de teren arabil. Fiind vecini cu terenurile, urma să plece în cîmp și xxxxCUSTOM1xxxx Serghei, dar ultimul n­a fost de găsit acasă. Împreună cu fiul său cel mic a plecat la cota de teren. I­a atătat tractoristului sectorul său, continuînd să rămînă acolo. Între timp a venit și S.xxxxCUSTOM1xxxx. Anterior a avit cu el neînțelegeri, privitor la hotar. A [[măusrat]] cu [[psaul]] și i­a [[artăat]] că cu patru metri a trecut hotarul. Fiind în stare de ebrietate S.[[xxxxCUSTO1Mxxxx]], care ave în mîni o [[loptaă]], l­a [[înjruat]] și l­a înjosit. N­ a putut să se abțină și i­a [[apliact]] 3 ori cu pumnul în regiunea [[fțeei]]. El s­a urcat în căruță să plece. [[Caull]] s­a [[spreiat]] și s­a izbit, el căzînd jos. [[Petse]] [[duoă]] săptămîni de la polițist a aflat că S.xxxxCUSTOM1xxxx s­a adresat la poliție. Recunoaște că leziunile corporale stabilite la S.xxxxCUSTOM1xxxx i­au fost pricinuite în urma acțiunilor sale. Regretă cele întîmplate și promite că nu v­a mai comite așa fapte. Este de acord, în baza documentelor, să­i restituie lui S.xxxxCUSTOM1xxxx cheltuielile pentru tratament. Și­a cerut scuze de la partea vătămată, acesta depunînd cerere de împăcare la poliție, iar mai tîrziu și­a retras­o. De rînd cu declarațiile sale din ședința de judecată, vina inculpatului xxxxNUMExxxx în comiterea infracțiunii de care se învinuiește se mai dovedește prin materialele dosarului penal, și anume: ­depoziţiile părţii vătămate xxxxCUSTOM1xxxx Serghei, potrivit cărora, la 09.11.2013 aproximativ la ora 1200 în timp ce se afla pe terenul său arabil situat lîngă Cuizăuca raionul Rezina, a venit consăteanul său xxxxNUMExxxx pentru a­şi ara terenul arabil care se mărgineşte cu al său. În timpul discuţiei s­au referit la delimitarea terenurilor arabile, în urma la ce între ei s­a iscat o ceartă, în rezultatul căruia ambii sau numit cu cuvinte înjurioase. Ulterior, V.M

[Succeeded / Failed / Skipped / Total] 15 / 15 / 4 / 34:  30%|███       | 30/100 [05:43<13:21, 11.45s/it]

--------------------------------------------- Result 34 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

1. Conform sentinței Judecătoriei Bălți din 14.12.2015 xxx au fost recunoscuți vinoveți în săvîrşirea infracţiunii prevăzută de art.312 alin.(2) lit.a) Cod Penal, și le­au fost numite următoarele pedepse: ­ xxx a fost declarat vinovat de comiterea infracţiunii prevăzute de art.312 alin.(2) lit.a) Cod Penal şi în baza acestei legi i s­a aplicat pedeapsă cu închisoare pe un termen de 2 (doi) ani, fără privare de dreptul de a ocupa anumite funcții sau de a exercita o anumită activitate. Conform art.90 Cod penal a fost dispusă suspendarea condiţionată a executării pedepsei aplicate vinovatului cu închisoare pe un termen de probă de 2 (doi) ani, obligînd condamnatul să nu­şi schimbe domiciliul fără consimţămîntul organului competent. Măsura preventivă aplicată în privinţa lui xxx pînă la intrarea sentinţei în vigoare se menţine obligarea de a nu părăsi ţara. ­ xxx a fost declarată vinovată de comiterea infracţiunii prevăzute de art.312 alin.(2) lit.a) Cod penal, şi în baza acestei legi i s­a stabilit pedeapsă sub formă de închisoare pe un termen de 2 (doi) ani, fără privarea de dreptul de a ocupa anumite funcţii sau de a exercita o anumită activitate. Conform art.90 Cod penal dispune suspendarea condiţionată a executării pedepsei aplicate cu închisoare pe un termen de probă de 2 (doi) ani, obligînd condamnata să nu­şi schimbe domiciliul fără consimţămîntul organului competent. Măsura preventivă aplicată în privinţa lui xxx pînă la intrarea sentinţei în vigoare se menţine obligarea de a nu părăsi ţara. 2. Instanța de fond a reținut că xxx, avînd scopul prezentării cu bună­ştiinţă a declaraţiei mincinoase, pe parcursul efectuării urmăririi penale pe cauza penală cu nr.2012978119 pornită de către Procuratura Anticorupţie la 10.08.2012 în baza art.324 alin.(2) lit.b) şi c) Cod penal, pe faptul coruperii pasive comise de colaboratorii Secţiei ’’Nord” a Direcţiei Combaterea Crimei Organizate a Direcţiei Generale Servicii Operative din cadrul Ministerului Afacerilor de Interne, care ulterior la data de 28.09.2012 a fost conexată la cauza penală nr.2010990418, fiind recunoscut şi audiat la 14.08.2012 în calitate de martor, iar la 27.09.2012 participînd în calitate de parte vătămată la confruntări cu învinuiţii xxx, fiindu­i explicat faptul survenirii răspunderii penale conform art.312 Cod penal, în caz de prezentare cu bună­ştiinţă a declaraţiei mincinoase, fapt confirmat prin semnăturile acestuia în rubricile corespunzătoare a proceselor­ verbale ale acţiunilor procesuale nominalizate, intenţionat şi cu bună­ştiinţă a prezentat în cadrul audierilor date declaraţii mincinoase, legate de învinuirea lui xxx de săvîrşirea coruperii pasive prevăzute la art.324 alin.(2) lit.b) şi c) Cod penal, infracţiune ce s­a manifestat prin pretinderea şi primirea banilor de la el în sumă de 1000 euro pentru eliberarea mărfii şi microbuzului reţinut şi care în cazul dat conform prevederilor art.16 alin.(4) Cod penal se clasifică la categoria infracţiunilor grave. Ulterior, fiind audiat în calitate de parte vătămată în cadrul şedinţelor de judecată, pe cauza penală de învinuire a cet.xxx de săvîrșirea infracțiunii prevăzute de art.324 alin.(2) lit.b) şi c) Cod penal, petrecute în perioada de timp 16.09.2013 ­ 06.11.2014, cet.xxx a declarat că declaraţiile anterioare date în cadrul urmăririi penale în calitate de martor și ca parte vătămată în cadrul confruntărilor, precum că cet.xxx

[Succeeded / Failed / Skipped / Total] 15 / 16 / 6 / 37:  31%|███       | 31/100 [05:58<13:18, 11.58s/it]

--------------------------------------------- Result 35 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

În Judecătoria xxxxORAS_SATxxxx a parvenit plîngerea înaintată de avocatul T.Guțu declarată în interesele părților vătămate E.P și M.M împotriva ordonanței procurorului în procuratura xxxxORAS_SATxxxx A.Gordilă din 05.01.2015 și împotriva ordonanței procurorului ierarhic superior din procuratura xxxxORAS_SATxxxx V.Tureac din 31.01.2015. Prin încheierea Judecătoriei Ungheni din 02.03.2015 respectiva plîngere a fost respinsă ca neîntemeiată. Nefiind de acord cu încheierea nominalizată, avocatul T.Guțu, în termen, a atacat­o cu recurs. Recurentul solicită admiterea recursului și anularea încheierii atacate. În motivarea recursului recurentul invocă, că instanța la emiterea încheierii nu a ținut cont de obiecțiile înaintate de avocat în interesele părților vătămate în plîngerea depusă. Consideră că de către organul de urmărire penală verificarea plîngerii a fost efectuată formal cu deviere de la normele de drept. Se consideră, că concluzia formulată este contrară declarațiilor făcute de părțile vătămate referitior la aplicarea violenței, constrîngerea de a face declarații și relinerea ilegală de către colaboratorii poliției. În ședința de judecată a instanței de recurs recurenta T.Guțu și părțile vătămate E.P și M. M au solicitat admiterea recursului pe motivele invocate, anularea încheierii contestate cu remiterea materialelor pentru un control suplimentar procuraturii xxxxORAS_SATxxxx. Procurorul participant a solicitat respingerea recursului cu menținerea încheierii Judecătoriei xxxxORAS_SATxxxx din 02.03.2015 pe cazul dat fără modificări. Verificînd argumentele recursului în raport cu materialele cauzei şi cu prevederile legii, Colegiul penal consideră recursul neîntemeiat şi pasibil de a fi respins, păstrînd fără modificări încheierea Judecătoriei xxxxORAS_SATxxxx din 02.03.2015. Conform art. 274 alin.(1) CPP, ”Organul de urmărire penală sau procurorul sesizat în modul prevăzut în art.262 şi 273 dispune în termen de 30 de zile, prin ordonanţă, începerea urmăririi penale în cazul în care, din cuprinsul actului de sesizare sau al actelor de constatare, rezultă o bănuială rezonabilă că a fost săvîrşită o infracţiune şi nu există vreuna din circumstanţele care exclud urmărirea penală, informînd despre aceasta persoana care a înaintat sesizarea sau organul respectiv”. După cum denotă actele cauzei, la 03.12.2014 și respectiv la 10.12.2014 în adresa procuraturii xxxxORAS_SATxxxx au parvenit plîngerile lui E.P și M.M, prin care a solicitat atragerea la răspundere a colaboratorilor poliției A.S și A.M, pe faptul aplicării violenței fizice și psihice aplicate de aceștea în cadrul instrumentării unei cauze penale de trafic de ființe umane unde ele sunt recunoscute în calitate de părți vătămate. Conform art. 274 alin. (5) CPP, ”În cazul în care procurorul refuză pornirea urmăririi penale, el confirmă faptul prin ordonanța motivată și anunță despre aceasta, într­un termen cît mai scurt posibil, dar nu maimare de 15 zile, persoana care a înaintat sesizarea. În cazul în care consideră că lipsesc temeiurile pentru a începe urmărirea penal, procurorul, prin ordonanță, abrogă ordonanța de începere a urmăririi penale și dispune refuzul în pornirea urmăririi penale și clasarea procesului penal”. Prin ordonanța din 05.01.2015 procurorul A.Gordilă a dispus neînceperea pe caz a urmăririi penale pe motivul lipsei faptei infracționale in acțiunile colaboratorilor poliției. Prin respectiva ordonanță procesul penal a fost clasat. În conformitate cu art. 275 CPP ”Urmărirea penală nu poate fi pornită, iar dacă a fost pornită, nu poate fi efectuată, și va fi încetată în cazurile în care: ...


--------------------------------------------- Result 36 ---------------------------------------------
[[1 (52%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse instanţa de fond a reţinut că xxx, la 19 iulie 2015, în jurul orelor 22.30, deţinînd permisul de conducere cu numărul de înregistrare 988301152, eliberat la 03.06.1998, intenţionat, încălcând cerinţele pct.14 lit.a) din Regulamentul circulaţiei rutiere, care stipulează că conducătorului de vehicul îi este interzis să conducă vehiculul dacă a consumat băuturi alcoolice, droguri sau alte substanţe contraindicate conducerii conducînd în stare de ebrietate alcoolică automobilul de model „Wolkswagen T4” cu n/î xxx, în timpul deplasării prin satul xxx raionul xxx, a fost stopat de către colaboratorii secţiei poliţiei rutiere ai PP Soroca­Floreşti pentru verificarea actelor. Tot atunci, din motiv că a fost suspectat de ultimii că conducea mijlocul de transport în stare de ebrietate alcoolică, a fost supus de către colaboratorii de poliţie testării alcooscopice cu alcotestul din dotare „Drager” şi s­a constatat că concentraţia vaporilor de alcool în aerul expirat de către acesta este de 0,71 mg/L, ceea ce constituie stare de ebrietate cu grad avansat. Conform art.134/12 al.3 din Codul Penal, starea persoanei care are concentraţia de alcool în sînge de la 1,0 g/l şi mai mult sau concentraţia vaporilor de alcool în aerul expirat de la 0,5 mg/l şi mai mult, corespunde stării de ebrietate alcoolică cu grad avansat. În baza art.134 al.3 din Codul penal, prin stare de ebrietate alcoolică cu grad avansat se înţelege starea persoanei care are concentraţia de alcool în sînge de la 1,0 g/l şi mai mult sau concentraţia vaporilor de alcool în aerul expirat de la 0,5 mg/l şi mai mult. Cauza penală în privința lui xxx a fost examinată pe baza probelor administrate în faza de urmărire penală, în conformitate cu prevederile art.364/1 CPP RM. În termen sentinţa a fost contestată cu recurs de către avocatul Olșanski Alexandr în interesele inculpatului xxx, care în motivare invocă următoarele considerente: ­nu este deacord cu sentința în partea aplicării pedepsei complementare, deoarece instanţa n­a luat în consideraţie conţinutul actelor medicale prezentate de inculpat şi anexate la materialele cauzei, la inculpatul xxx s­a constatat: necroza aseptică a capului femural etapa V, fractura impresională a şoldului drept (ce se confirmă prin certificat de tomografie computerizată spiralată nr.2826 din 31.10.2015, f.d.56), în legătură cu ce, în certificatul medical nr.434 din 31.10.2015 fiind notate recomandări: limita presiune asupra articulaţiilor, a exclude plimbări lungi: a se deplasa cu automobul (f.d.55), cu boala de care suferă a fost îndreptat la Spitalul Republican, secţia de raumatologie, pentru operaţie (f.d.57), ­fiind audiat în calitate de bănuit, învinuit şi inculpat, xxx a recunoscut vina sa şi s­a căit în cele omise, fără antecedente penale, la locul de trai se caracterizează pozitiv, ­ţinînd cont de circumstanţele exepţionale ale cauzei prezente, legate de comportarea vinovatului în timpul şi după consumarea infracţiunii, de starea sănătăţii a lui şi de recomandările medicului relevate, consideră că prima instanţă în conformitate cu art.79 al.1 CP avea temei şi putea să nu aplice pedeapsa complementară obligatorie, ­solicitînd admiterea apelului, casarea sentinței instanței de fond în partea aplicării inculpatului a pedepsei complementare și pronunțarea unei hotărîri noi, fără privarea de dreptul de a


--------------------------------------------- Result 37 ---------------------------------------------
[[1 (62%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse mai sus, instanţa de fond a reţinut, că inculpatul XXXXXXXXX la data de 29.06.2015 aproximativ la orele 10.30, fiind la volanul automobilului de model „Opel Omega” cu n/î BL BD 945, deplasîndu­se pe str.Ştefan cel Mare mun.Bălţi, din direcţia autogării în direcţia regiunii „Molodovo” mun.Bălţi, în preajma blocului numărul 52 de pe str.Ştefan cel Mare din mun.Bălţi, încălcînd grosolan art.45 al.(1) al Regulamentului Circulaţiei Rutiere, care prevede că conducătorul trebuie să conducă vehiculul în conformitate cu limita de viteză stabilită, ţinînd permanent seama de următorii factori: a) starea psihofiziologică ce influenţează atenţia şi reacţia; b) dexteritatea în conducere care i­ar permite să prevadă situaţiile periculoase; c) starea tehnică a vehiculului şi particularităţile încărcăturii; d) situaţia rutieră, precum şi art.45 al.(2) al Regulamentului Circulaţiei Rutiere, potrivit căruia în cazul în care în limita vizibilităţii apar obstacole care pot fi observate de conducător, el trebuie să reducă viteza sau chiar să oprească, pentru a nu pune în pericol siguranţa traficului, a tamponat pietonul Graur Ion Ananie, a.n.04.05.1949, care traversa partea carosabilă a străzii Ştefan cel Mare din partea dreaptă la stînga după direcţia de deplasare a automobilului. Conform raportului de expertiză medico­legală nr 275 D din 16.07.2015 pietonul Graur Ion Ananie în urma accidentului rutier s­a ales cu leziuni corporale grave, sub formă de traumatism cranio­cerebral acut închis sub formă de hematom subcutanat, hematom epidural masiv occipital pe stînga în fază acută, fractură os parietal pe stînga cu trecere pe bază. În cadrul urmării penale XXXXXXXXX Anton a încheiat acord de recunoaştere a vinovăţiei, care a fost acceptat de instanţa de judecată prin încheierea judiciară din 18.01.2016 şi în şedinţa de judecată a recunoscut pe deplin vinovăţia de săvîrşirea infracţiunii încriminate şi probele înaintate de acuzare. Împotriva sentinței în termen a declarat recurs procurorul în procuratura mun.Bălți Gagiu Leonid, care în motivarea recursului a indicat, că: ­fiind audiat sub jurămînt inculpatul XXXXXXXXX vina în cele incriminate a recunoscuta pe deplin; ­în pofida faptului că inculpatul XXXXXXXXX vina sa a recunoscut­o integral, fapta inputată se dovedeşte deplin prin următoarele probe: declaraţiile învinuitului XXXXXXXXX Anton, declaraţiile părţii vătămate XXXXXXXXX, declaraţiile martorilor Oganovscaia Maria Petru, Şevciuc Elena Vasile, Revenco Nina, proces­verbal de cercetare a locului accidentului rutier din 29.06.2015, foto­tabel anexă la procesul­verbal de cercetare a locului accidentului rutier din 29.06.2015, schiţa accidentului rutier întocmită la data de 29.06.2015, certificatul accidentului rutier din 29.06.2015, proces­verbal despre examinarea şi verificarea stării tehnice a unităţii de transport, proces­verbal de experiment, raport de expertiză judiciară nr.1330 din 21.08.2015, precum şi prin alte materiale ale cauzei penale; ­considerînd că activitatea infracţională a lui XXXXXXXXX pe deplin se încadrează conform art.264 al.(3) lit.a) Cod penal RM şi ţinînd cont de faptul că nu are antecedente penale, a săvîrşit o infracţiune din imprudenţă, se căieşte sincer în cele comise, a încheiat acord de recunoaştere a vinovăţiei, s­a solicitat instanţei a recunoaşte culpabil pe XXXXXXXXX de comiterea infracţiunii prevăzute de art.264 al.(3) lit.a) Cod penal RM şi în baza aceluiaşi articol a­i stabili pedeapsă sub formă de închisoare pe un termen de 4 ani cu aplicarea

[Succeeded / Failed / Skipped / Total] 16 / 16 / 6 / 38:  32%|███▏      | 32/100 [06:09<13:04, 11.53s/it]

--------------------------------------------- Result 38 ---------------------------------------------
[[0 (94%)]] --> [[1 (52%)]]

[[Prin]] încheierea [[Judecătoriei]] Rîșcani, mun.Chișinău din 17.04.[[2014]] s-a dispus [[respingerea]] ca fiind neîntemeiată a plîngerii depuse de Colțov Vadim privind obligarea Procuraturii Generale a [[Republicii]] Moldova să examineze plîngerea sa din 19.11.[[2013]], în baza art.274 Cod de procedură penală privind pretinsa pronunțare cu bună-știință de către judecătorii Curții de Apel Chișinău a unei încheieri contrare Legii din 17.11.2010 în cauza civilă cu nr.2a-523/10. Pentru a emite încheierea dată, prima instanță a [[constatat]] că, la 19.11.2013, petiţionarul Colţov Vadim a depus o plîngere la Procuratura Generală a Republicii Moldova privind pronunţarea cu bună-ştiinţă de către judecătorii Curţii de Apel Chişinău a unei încheieri contrare legii, în cauza civilă nr.2a-523/10. Prin scrisoarea procurorului pentru misiuni speciale a Procuraturii Generale, Radeţchi Viorel, cu nr.36-194/13-756 din 02.12.2013, Colţov Vadim a fost informat că, nu sunt temeiuri, plîngerea fiind apreciată ca un act înaintat în conformitate cu prevederile Legii cu privire la petiţionare, motiv din care aceasta nu poate să fie examinată potrivit art.274 Cod de procedură penală or, [[examinarea]] acestei plîngeri în [[fond]], poate fi considerată ca un amestec în înfăptuirea justiţiei. Nefiind de acord, petiţionarul Colţov Vadim a depus din nou o plîngere la Procuratura Generală a Republicii Moldova, prin care a solicitat pornirea urmăririi penale în baza art.307 Cod penal în privinţa completului de judecători ai Curţii de Apel Chişinău, care au emis la 17.11.2010, о încheiere contrară legii în cauza civilă nr.2a-523/10, iar prin scrisoarea procurorului pentru misiuni speciale a Procuraturii Generale, Radeţchi Viorel, cu nr.36- 194/13-71 din 21.01.2014, Colţov Vadim a fost informat că, în plîngerea depusă nu se conţin fapte sau argumente, ce ar putea fi examinate în conformitate cu prevederile art.274 Cod de procedură penală. La 18.02.2014, Colţov Vadim a depus o plîngere prin care a solicitat recunoaşterea ca fiind ilegale refuzurile Procuraturii Generale în pornirea urmăririi penale în baza denunţului înaintat la 19.11.2013 şi examinarea acestuia în conformitate cu prevederile Legii cu privire la petiţionale, precum şi obligarea procurorului la înregistrarea acestuia în mod respectiv şi efectuarea unui control în conformitate cu prevederile art.274 Cod de procedură penală. În motivarea plîngerii, petiționarul a indicat că, potrivit hotărârii Judecătoriei Rîşcani, mun.Chişinău, în pricina civilă nr.3c/a-222/2011, intentată la 27.01.2011, acţiunea sa împotriva Comisiei pentru Etică şi Disciplină a Uniunii Avocaţilor din Republica Moldova, cu intervenienţii Uniunea Avocaţilor din Republica Moldova şi SRL „Lima” privind anularea fără efecte juridice pentru viitor a hotărîrii Comisiei privind retragerea licenţei, a fost admisă, hotărârea fiind menţinută fără modificări, prin Decizia Curţii de Apel Chişinău din 05 iunie 2013, astfel, fiind în prezența puterii lucrului judecat, s-a constatat următoarele. În baza contractului de asistenţă juridică nr.22 din 25.03.2008, procura fiind eliberată de SRL „Lima” din 03.03.2008 cu termenul de valabilitate de un an de zile şi a mandatului de avocat eliberat la 26.03.2008, pentru perioada 26 martie 2008-15 iulie 2009, el, Colțov Vadim a exercitat obligaţiunile contractuale, acordarea asistenţei juridice clientului - SRL „Lima”, inclusiv la 19 aprilie 2008. Prin scrisoarea recomandată nr.44746, a înaintat conform procedurii, o cerere de apel asupra unei hotărîri a primei instanţe, care a fost înregistrată de cancelaria Judecătoriei Ialoveni cu

[[Pirn]] încheierea [[Judecătroiei]] Rîșcani, mun.Chișinău din 17.04.[[2104]] s-a dispus [[rsepingerea]] ca fiind neîntemeiată a plîngerii depuse de Colțov Vadim privind obligarea Procuraturii Generale a [[Rpeublicii]] Moldova să examineze plîngerea sa din 19.11.[[2103]], în baza art.274 Cod de procedură penală privind pretinsa pronunțare cu bună-știință de către judecătorii Curții de Apel Chișinău a unei încheieri contrare Legii din 17.11.2010 în cauza civilă cu nr.2a-523/10. Pentru a emite încheierea dată, prima instanță a [[cnostatat]] că, la 19.11.2013, petiţionarul Colţov Vadim a depus o plîngere la Procuratura Generală a Republicii Moldova privind pronunţarea cu bună-ştiinţă de către judecătorii Curţii de Apel Chişinău a unei încheieri contrare legii, în cauza civilă nr.2a-523/10. Prin scrisoarea procurorului pentru misiuni speciale a Procuraturii Generale, Radeţchi Viorel, cu nr.36-194/13-756 din 02.12.2013, Colţov Vadim a fost informat că, nu sunt temeiuri, plîngerea fiind apreciată ca un act înaintat în conformitate cu prevederile Legii cu privire la petiţionare, motiv din care aceasta nu poate să fie examinată potrivit art.274 Cod de procedură penală or, [[exmainarea]] acestei plîngeri în [[fnod]], poate fi considerată ca un amestec în înfăptuirea justiţiei. Nefiind de acord, petiţionarul Colţov Vadim a depus din nou o plîngere la Procuratura Generală a Republicii Moldova, prin care a solicitat pornirea urmăririi penale în baza art.307 Cod penal în privinţa completului de judecători ai Curţii de Apel Chişinău, care au emis la 17.11.2010, о încheiere contrară legii în cauza civilă nr.2a-523/10, iar prin scrisoarea procurorului pentru misiuni speciale a Procuraturii Generale, Radeţchi Viorel, cu nr.36- 194/13-71 din 21.01.2014, Colţov Vadim a fost informat că, în plîngerea depusă nu se conţin fapte sau argumente, ce ar putea fi examinate în conformitate cu prevederile art.274 Cod de procedură penală. La 18.02.2014, Colţov Vadim a depus o plîngere prin care a solicitat recunoaşterea ca fiind ilegale refuzurile Procuraturii Generale în pornirea urmăririi penale în baza denunţului înaintat la 19.11.2013 şi examinarea acestuia în conformitate cu prevederile Legii cu privire la petiţionale, precum şi obligarea procurorului la înregistrarea acestuia în mod respectiv şi efectuarea unui control în conformitate cu prevederile art.274 Cod de procedură penală. În motivarea plîngerii, petiționarul a indicat că, potrivit hotărârii Judecătoriei Rîşcani, mun.Chişinău, în pricina civilă nr.3c/a-222/2011, intentată la 27.01.2011, acţiunea sa împotriva Comisiei pentru Etică şi Disciplină a Uniunii Avocaţilor din Republica Moldova, cu intervenienţii Uniunea Avocaţilor din Republica Moldova şi SRL „Lima” privind anularea fără efecte juridice pentru viitor a hotărîrii Comisiei privind retragerea licenţei, a fost admisă, hotărârea fiind menţinută fără modificări, prin Decizia Curţii de Apel Chişinău din 05 iunie 2013, astfel, fiind în prezența puterii lucrului judecat, s-a constatat următoarele. În baza contractului de asistenţă juridică nr.22 din 25.03.2008, procura fiind eliberată de SRL „Lima” din 03.03.2008 cu termenul de valabilitate de un an de zile şi a mandatului de avocat eliberat la 26.03.2008, pentru perioada 26 martie 2008-15 iulie 2009, el, Colțov Vadim a exercitat obligaţiunile contractuale, acordarea asistenţei juridice clientului - SRL „Lima”, inclusiv la 19 aprilie 2008. Prin scrisoarea recomandată nr.44746, a înaintat conform procedurii, o cerere de apel asupra unei hotărîri a primei instanţe, care a fost înregistrată de cancelaria Judecătoriei Ialoveni cu

[Succeeded / Failed / Skipped / Total] 16 / 17 / 7 / 40:  33%|███▎      | 33/100 [06:24<13:00, 11.64s/it]

--------------------------------------------- Result 39 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Potrivit sentinței Romanadze David Temur a fost condamnat pentru, că urmărind scopul obținerii unor beneficii ilicite, în circumstanțe nestabilite de către organul de urmărire penală, a intrat în posesia a 600 formulare de timbre de acciz falsificate și fără a deține licența corespunzătoare pentru genul anumit de activitate în domeniul băuturilor alcoolice tari (vodcă), le­a aplicat pe 600 sticle cu volumul de 0,5 litri de băutură alcoolică tare ”Black Cristal”, pe care la 17.05.2014, aproximativ la ora 14:00, le transporta pe traseul Brest­Chișinău ­Odessa în automobilul propriu de model ”Mitsubischi Pajero”, cu numărul de înmatriculare BL DS 451, moment în care, angajații Ministerului Afacerilor Interne, l­au stopat pe teritoriul administrativ al satului Corlăteni, Rîșcani, respectivele acțiuni fiindu­i încadrate la art. 361 alin. (1) Cod penal cu calificativele „confecţionarea, deţinerea, vânzarea sau folosirea documentelor oficiale false, care acordă drepturi sau eliberează de obligaţii, confecţionarea sau vânzarea imprimatelor, ştampilelor sau a sigiliilor false ale unor întreprinderi, instituţii, organizaţii, indiferent de tipul de proprietate şi forma juridică de organizare”. Legalitatea și temeinicia sentinței de condamnare a fost contestată de către: ­avocatul Victor Dolghi în interesele inculpatului Romanadze David, care necontestând legalitatea încadrării juridice a faptei penale, solicită casarea sentinței în latura stabilirii pedepsei penale, cu adoptarea în această parte a unei soluții noi privind atenuarea pedepsei penale, prin stabilirea celei cu amendă, pe care inculpatul este disponibil să o achite. În motivarea cerințelor formulate invocându­se un șir de circumstanțe atenuante a cauzei penale, cum ar fi: vârsta tânără, recunoașterea vinovăției și căința sinceră, prezența la întreținere a doi copii minori, precum și intenția a se încadra în câmpul muncii, inclusiv după hotarele RM, pedeapsa lui aplicată creându­i incomodități în legătură cu aceasta. ­procurorul Igor Gherasim ce a reprezentat învinuirea în instanță de fond, care necontestând legalitatea încadrării juridice a acțiunilor infracționale, solicită casarea acestei în latura stabilirii pedepsei penale, cu pronunțarea unei soluții noi privind atenuarea pedepsei penale, fiindu­i stabilită cea cu amendă în mărime de 225 u. c., ce constituie 4500 lei, considerând, că la numirea ei instanța nu a ținut cont de prevederile art.75 Cod penal, fapt prin ce a neglijat recomandările expuse în pct.9 al Hotărârea Plenului CSJ nr. 8 din 11.11.2013 ”Cu privire la unele chestiuni ce vizează individualizarea pedepsei penale”., eronat fiind stabilită prezența circumstanței agravante prevăzute la art.77 Cod penal și anume faptul, că inculpatul anterior a comis o infracțiune analogică, mai ales că achitarea amenzii stabilite prin sentința Judecătoriei Bălți din 20.11.2013 și stingerea antecedentelor penale au fost adeverite prin certificatul prezentat de către inculpatul Romanadze David în cadrul cercetărilor judecătorești. Totodată, ne cătând la faptul că au stabilite circumstanțe atenuante și nu existau în fapt circumstanțe agravante, instanța a aplicat pedeapsa maximă prevăzută de art.361 alin.(1) Cod penal, calculată prin prisma art.364/1 Cod pr. penală, astfel că concluzia instanței cu privire la aplicarea unei pedepse mai aspre urma a fi motivată. Or, ne cătând la faptul, că acuzatorul de stat, apărătorul precum și inculpatul au solicitat aplicarea pedepsei sub formă de amendă, instanța, fără a­și motiva decizia și fără a argumenta faptul, de ce nu este echitabilă


--------------------------------------------- Result 40 ---------------------------------------------
[[1 (83%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut, că inculpatul xxxxNUMExxxx la data de 08.02.2014, în jurul orei 22.00, aflîndu­se în incinta magazinului „xxxxNUMExxxx” din sat. Chirileni r­ul xxxxORAS_SATxxxx, văzînd că cumnatul său xxxxNUMExxxx are un conflict cu cet. xxxxNUMExxxx, s­a implicat şi i­a aplicat ultimului cîteva lovituri cu pumnul în faţă, dupa care cet. xxxxNUMExxxx a fugit acasă. Peste cîteva minute după conflictul dat cet. xxxxNUMExxxx, s­a întors înapoi avînd cu sine o bărdiţă şi a încercat să discute cu cet. xxxxNUMExxxx şi xxxxNUMExxxx, însă ultimul i­a luat bardiţa din mînă și i­a mai aplicat cu ea cîteva lovituri peste corp şi peste piciorul stîng, provocîndu­i vătămăti corporale grave, sub formă de fractura deschisă a osului tibial a gambei stîngi, sector excoriat în regiunea zigomatică, plagă contuză în regiunea sprîncenoasă a ochiului stîng, edeme traumatice a ţesuturilor moi a pleoapelor ochiului stîng cu revărsat sangvin în scleră, excoreaţii în regiunea articulaţiei cotului stîng şi antebraţului stîng, plagă scalpată în regiunea nazală. Instanţa de fond a pronunţat sentinţa sus indicată. Împotriva sentinţei a declarat apel partea vătămată xxxxNUMExxxx, care solicită casarea sentinţei în latura civilă, cu dispunerea încasării de la inculpat a prejudiciului moral în sumă de 100000 lei. În motivarea apelului invocă, că prin încasarea prejudiciului moral în sumă de 2000 lei s­au ignorat prevederile art. 1423 Cod civil, ne fiind luate în calcul suferinţele la care a fost supus, şi anume că prin lovitura de topor i­a fost pricinuită fractura deschisă a piciorului, fapt care l­a imobilizat pe o perioadă de lungă durată şi din aceste considerente a fost privat de posibilitatea de a­şi întreţine familia, el lucrînd ca muncitor sezonier după hotare, avînd la întreţinere doi copii mici, că a suportat timp îndelungat dureri fizice. Consideră, că pedeapsa penală stabilită inculpatului nu echivalează cu o compensare morală, fiind doar o măsură de constrîngere pentru infracţiunea comisă, iar inculpatul nici nu a conştientizat că a fost supus unei pedepse penale. Partea vătămată xxxxNUMExxxx, fiind citată în mod legal, în şedinţa instanţei de apel nu s­a prezentat. În şedinţa instanţei de apel procurorul, inculpatul şi avocatul acestuia au solicitat respingerea apelului părţii vătămate ca nefondat, cu menținerea sentinţei instanței de fond. Verificând argumentele apelantului în raport cu materialele cauzei, ascultînd opiniile participanţilor la proces, Colegiul penal vine la concluzia, că apelul declarat este nefondat şi urmează a fi respins. În concluzia respectivă instanța de apel statuază pe prevederile art. 414, 415 al. (1) pct. 1 lit. c), 24 CPP. Așa, potrivit art. 415 al. (1) pct. 1 lit. c) CPP, instanța de apel, judecînd cauza în ordine de apel, respinge apelul dacă acesta este nefondat. Potrivit art. 414 al. (1) CPP, instanța de apel, judecînd apelul, verifică legalitatea și temeinicia hotărîrii atacate în baza probelor examinate de prima instanță, conform materialelelor din cauza penală, și în baza oricăror probe noi prezentate instanței de apel. Analizînd probele administrate de instanța de fond, materialele cauzei, Colegiul penal reține, că la examinarea cauzei respective s­a dat eficiență prevederilor art. 93­101, 26­27 Cod de procedură penală, instanța a cercetat cauza

[Succeeded / Failed / Skipped / Total] 16 / 18 / 7 / 41:  34%|███▍      | 34/100 [06:38<12:54, 11.73s/it]

--------------------------------------------- Result 41 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Inculpatul Fediuc Vladimir la data de 22 ianuarie 2013, aproximativ la ora 21.00, aflându­se la domiciliul său din s. Tăura­Veche, r­nul Sângerei și fiind în stare de ebrietate alcoolică, acționând intenționat, cu scopul sistării activității de serviciu legate de examinarea adresării cet. Fediuc Eugen nr. 322 din 22.01.2013 despre acțiunile de amenințare cu arma, verbal l­a amenințat cu moartea pe șeful de post, ofițerul operativ superior de sector al postului de poliție Tăura­Veche al CPR Sângerei Ceban Gheorghe, care este persoană cu funcție de răspundere, deoarece se afla în exercițiul funcției și era investită prin lege cu obligațiuni de menținere a ordinii publice și prevenire a infracțiunilor, fapt care i­a provocat temere reală și n­a intervenit în continuare. Tot el, continuând acțiunile infracționale, la 23 ianuarie 2013, aproximativ la ora 09.00, la domiciliul său din s. Tăura­Veche, r­nul Sângerei, fiind în stare de ebrietate alcoolică, intenționat, cu scopul sistării activității de cercetare a cazului de amenințare cu arma înregistrat cu nr. 322 din 22.01.2013, cu un cuțit de bucătărie ce­l avea în mână, l­a atacat pe polițistul­ șofer al serviciului de patrulă și santinelă al CPR Sângerei Podgurschi Nicolae, care era persoană cu funcție de răspundere, deoarece se afla în exercițiul funcției și era investit cu obligațiuni de menținere a ordinii publice și prevenire a infracțiunilor. Polițistul Podgurschi N. a respins atacul și cu ajutorul colaboratorilor de poliție Petrov Marcel și Ceban Gheorghe, Fediuc Vladimir a fost deposedat de cuțit și imobilizat. Procurorul Vitalie Crigan, procuror în Procuratura r­lui Sângerei a susţinut în instanţă acuzarea de stat, pledând pentru recunoaşterea inculpatului Fediuc Vladimir vinovat în conformitate cu art. 349 alin. 1 CP al RM şi în baza acestei Legi și a prevederilor art. 364/1 CPP al RM, luînd în considerație circumstanțele atenuante și agravante, principiile individualizării pedepsei a­i stabili o pedeapsă sub formă de muncă neremunerată în folosul comunității în mărime de 120 ore. Corpul delict­ cuțitul­ a fi nimicit la intrarea sentinței în vigoare. Avocatul Vasile Țâbârnă, cabinet individual de avocat, cu sediul în or. Sângerei, apărând interesele inculpatului în baza mandatului din 23.10.2013, Seria MA nr. 0379781, a pledat în dezbateri judiciare pentru aplicarea unei pedepse echitabile, fiind de acord cu cea propusă de acuzatorul de stat, luînd în consideraţie căinţa sinceră și recunoașterea vinovăției, precum și toate circumstanțele atenuante. În cadrul şedinţei judiciare inculpatul Fediuc Vladimir, fiind interogat sub jurământ, a recunoscut vina integral, explicând că în perioada sărbătorilor de iarnă 2013, exact data nu mai ține minte, a fost la cimitir la mormântul fiicei sale, acolo a consumat alcool și revenind acasă în s. Tăura­Nouă, r­nul Sângerei soția l­a certat, astfel iscându­se scandal între ei. Ține minte că a coborât în beci unde a continuat să bea, evenimentele ulterioare însă nu și le mai aduce aminte, deoarece era foarte beat. A mai declarat, că recunoaște vina integral, se căiește de cele comise și solicită să nu­i fie aplicată sancțiunea amenzii, deoarece situația sa financiară nu­i va permite s­o achite. În schimb, este de acord să muncească în folosul comunității. Părțile vătămate Ceban Gheorghe și Podgurschi Nicolae au solicitat

[Succeeded / Failed / Skipped / Total] 16 / 19 / 7 / 42:  35%|███▌      | 35/100 [06:53<12:47, 11.81s/it]

--------------------------------------------- Result 42 ---------------------------------------------
[[1 (100%)]] --> [[[FAILED]]]

Prin sentinţa nominalizată inculpatul xxxxNUMExxxx a fost recunoscut culpabil și condamnat pentru că în seara zilei de 28.06.2010 pe la orele 21:30, aflîndu­se pe una din străzile sat. xxxxORAS_SATxxxx, Sîngerei, în apropierea gospodăriei cet. Chișcă Natalia, din motivul relațiilor receproc ostile, în timpil cerții cu xxxxNUMExxxx, i­a aplicata acestui cîteva lovituri cu pumnii în regiunea feții, apoi cu un baston din lemn i­a aplicat mai multe lovituri peste corp, mîini și cap, cauzîndu­i vătămări corporale medii, cu dereglare de lungă durată a sănătății, acțiunile lui fiind încadrate la art. 152 alin. (1) Cod penal. Legalitatea sentinţei în termenul şi modul prevăzut de art. 402 Cod pr. penală a fost atacată cu apel de către partea vătămată xxxxNUMExxxx, care necontestînd legalitatea încadrării juridice a acțiunilor infractorice a inculpatului xxxxNUMExxxx la art. 152 alin. (1) Cod penal precum și măsura de pedeapsa lui numită, își expune dezacordul în ce privește admiterea parțială a acțiunii civile, solicitînd casarea ei în această parte, cu rejudecarea cauzei și admiterea integrală a cerințelor formulate de recuperare a daunei materiale în sumă de 1396, 83 lei pentru tratament, 382 lei cheltuieli pentru transport, 2000 lei pentru servivciul apărătorului și 5000 lei cu statut de despăgubiri morale. În fața instanței de apel apelantul a pledat pentru admiterea cererii de apel pe motivele invocate în ea, dispunîndu­se încasarea de la inculpat în beneficiul său a sumei de 2000 lei cheltuieli pentru acordarea asistenței juridice și 5000 lei cu titlu de despăgubiri morale, în rest păstrîndu­se fără modificări soluția primei instanțe. Reprezentantul acuzării a pledat pentru admiterea cerințelor formulate de apelant, pe motivele invocate de el. Inculpatul xxxxNUMExxxx și avocatul ce­i asigură apărarea garantată de stat au pledat pentru respingerea apelului ca fiind nefondat, păstrînd fără modificări sentința contestată. Verificînd legalitatea verdictului contestat și temeinicia argumentelor invocate de apelant în raport cu materialele cauzei penale, ascultînd pledoriile participanţilor procesului penal, Colegiul conchide posibilitatea admiterii în tot a cerințelor formulate de apelantul xxxxNUMExxxx în cererea de apel, dispunînd casarea sentinței în latura civilă, cu adoptarea în această parte a unei soluții noi de încasare de la Gobjilă Mihail în beneficiul lui a despăgubirilor morale în suma de 5000 lei și 2000 lei cheltuieli pentru asistența juridică, în rest păstrînd fără modificări sentința judiciară. Din start Colegiul reține, că apelul părții vătămate xxxxNUMExxxx urmează a fi considerat ca fiind depus în termenul legal, dat faptului că în materialele cauzei penale lipsesc date ce ar confirma informarea lui despre sentința redactată. Potrivit recipisei anexată pe coperta cauzei, inculpatului i­a fost înmînată copia sentinței redactate la data de 17.05.2011, dată de la care urmează a se calcula curgerea termenilor de declarare a apelului. Ținînd cont de faptul că alte date în cauză lipsesc, Colegiul consideră necesar de a considera apelul declarat de xxxxNUMExxxx ca fiind depus în termen. În motivarea concluziei adoptate, Colegiului în limita împuternicirilor procesuale de care dispune potrivit art. 414 Cod pr. penală, reține examinarea amplă, multelaterală și obiectivă a cauzei penale în ce privește constatarea faptei criminale, cu cercetarea profundă a probelor administrate de către organul de urmărire penală prin prisma dispozițiilor

[Succeeded / Failed / Skipped / Total] 17 / 19 / 7 / 43:  36%|███▌      | 36/100 [07:02<12:31, 11.74s/it]

--------------------------------------------- Result 43 ---------------------------------------------
[[1 (70%)]] --> [[0 (54%)]]

Prin sentinţa Judecătoriei C. din 29 ianuarie 2013 T. V. P. a [[fost]] recunoscut [[vinovat]] de săvîrşirea infracţiunilor prevăzute de 1 art.art. 188 alin.(2) lit.b), fşi 192 alin.(2) lit.a) Cod penal şi i s­a stabilit pedeapsa: ­în baza art.188 alin.(2) lit.b), f) Cod penal­ 8 ani închisoare; 1 ­în baza art.192 alin.(2) lit.a) Cod penal ­4 ani închisoare; ­în baza art.84 alin.(1) Cod penal, prin cumul total al pedepselor aplicate, s­a stabilit lui T. V. pedeapsa definitivă de 12 ani [[închisoare]] cu executarea pedepsei în penitenciar de tip închis. xxxxNUMExxxx a fost recunoscut vinovat de săvîrşirea infracţiunilor prevăzute de art.art.42 alin.(5), 188 alin.(2) lit.b), f) şi 1 art.art.42 alin.(5), 19 alin.(2) lit.a) Cod penal şi i s­a stabilit pedeapsa: 1 în baza art.art.42 alin.(5), 188 alin.(2) lit.b), f) Cod penal ­ 6 ani închisoare, ­în baza art.art.42 alin.(5), 192 alin.(2) lit.a) Cod pena­2 ani închisoare, în baza art.84 alin. (1) Cod penal, prin cumul paţial al pedepselor aplicate, s­a stabilit lui xxxxNUMExxxx pedeapsa definitivă de 7 an închisoare cu executarea pedepsei în penitenciar de tip închis; ­în baza art.85 alin. (1) Cod penal, la pedeapsa stabilită prin prezenta sentinţă, s­a adăugat parţial pedeapsa neexecutată potrivit sentiţei din 02 martie 2006, stabilind lui xxxxNUMExxxx pedeapsa definitivă de 8 ani închisoare cu executarea pedepsei în penitenciar de tip închis Acţiunea civilă depusă de xxxxNUMExxxx a fost admisă parţial. S­a încasat de la T. V. în beneficiul luxxxxNUMExxxx , 11 lei cu titlu de prejudiciul material cauzat prin infracţiune în foră de mijloacele băneşti sustrase. S­a încasat în mod solidar de la T. V. şi xxxxNUMExxxx. în [[beneficiul]] luxxxxNUMExxxx 30000 lei cu titlu de prejudiciul moral cauzat prin infraţiune. Acţiunea civilă depusă de xxxxNUMExxxxon cu privire la [[încasarea]] a 5000 lei pentru tratament, [[12000]] lei cheltuieli pentru repararea automobilului a fos admisă în principiu, urmînd ca asupra cuantumului despăgubirilor să se pronunţe instanţa în ordinea procedurii civil Pentru a se pronunţa, instanţa de fond a constatat că: T. V. P. în complicitate cu xxxxNUMExxxx, ce s­a exprimat prin faptul că xxxxNUMExxxx. la indicaţia lui T.V., pe data de 30 august 2012, aproximati la ora 17.00, prin înşelăciune 1­a chemat pe taxistul xxxxNUMExxxx , care a sosit la chemare la casa de locuit, amplasă pe str.C. 85, s.C., ce aparţine lui xxxxNUMExxxx., unde cu scopul sustragerii bunurilor altei persoane, T. V. s­ a ăpustit asupra luxxxxNUMExxxx din spate, i­a legat mîinile şi picioarele cu scotch şi o frînghie, în cap i­a pus un pachet de polietileă, l­a doborât la pământ, cerînd transmiterea banilor, a început să­1 lovească cu mîinile şi picioarele pe diferite părţi ale corpului, aplicînd violeţa periculoasă pentru viaţa şi sănătatea părţii vătămate, cauzîndu­i leziuni corporale uşoare sub formă de trauma crani­cerebrală acută, contuzie, echimoze în regiunea parieto­occipitala, pe cutia toracică din stânga, escoriaţii pe ambele picioare, antebţul drept, după ce au sustras din buzunarul pantalonilor lui xxxxNUMExxxxon 200 lei, cît şi banii din automobilul de mode M , n/î , care era parcat în faţa casei de locuit sus­indicate în sumă de 600 euro, 100 dolari SUA şi 4000 lei, iar total au

Prin sentinţa Judecătoriei C. din 29 ianuarie 2013 T. V. P. a [[fsot]] recunoscut [[vinoavt]] de săvîrşirea infracţiunilor prevăzute de 1 art.art. 188 alin.(2) lit.b), fşi 192 alin.(2) lit.a) Cod penal şi i s­a stabilit pedeapsa: ­în baza art.188 alin.(2) lit.b), f) Cod penal­ 8 ani închisoare; 1 ­în baza art.192 alin.(2) lit.a) Cod penal ­4 ani închisoare; ­în baza art.84 alin.(1) Cod penal, prin cumul total al pedepselor aplicate, s­a stabilit lui T. V. pedeapsa definitivă de 12 ani [[închisaore]] cu executarea pedepsei în penitenciar de tip închis. xxxxNUMExxxx a fost recunoscut vinovat de săvîrşirea infracţiunilor prevăzute de art.art.42 alin.(5), 188 alin.(2) lit.b), f) şi 1 art.art.42 alin.(5), 19 alin.(2) lit.a) Cod penal şi i s­a stabilit pedeapsa: 1 în baza art.art.42 alin.(5), 188 alin.(2) lit.b), f) Cod penal ­ 6 ani închisoare, ­în baza art.art.42 alin.(5), 192 alin.(2) lit.a) Cod pena­2 ani închisoare, în baza art.84 alin. (1) Cod penal, prin cumul paţial al pedepselor aplicate, s­a stabilit lui xxxxNUMExxxx pedeapsa definitivă de 7 an închisoare cu executarea pedepsei în penitenciar de tip închis; ­în baza art.85 alin. (1) Cod penal, la pedeapsa stabilită prin prezenta sentinţă, s­a adăugat parţial pedeapsa neexecutată potrivit sentiţei din 02 martie 2006, stabilind lui xxxxNUMExxxx pedeapsa definitivă de 8 ani închisoare cu executarea pedepsei în penitenciar de tip închis Acţiunea civilă depusă de xxxxNUMExxxx a fost admisă parţial. S­a încasat de la T. V. în beneficiul luxxxxNUMExxxx , 11 lei cu titlu de prejudiciul material cauzat prin infracţiune în foră de mijloacele băneşti sustrase. S­a încasat în mod solidar de la T. V. şi xxxxNUMExxxx. în [[benefciiul]] luxxxxNUMExxxx 30000 lei cu titlu de prejudiciul moral cauzat prin infraţiune. Acţiunea civilă depusă de xxxxNUMExxxxon cu privire la [[încasraea]] a 5000 lei pentru tratament, [[10200]] lei cheltuieli pentru repararea automobilului a fos admisă în principiu, urmînd ca asupra cuantumului despăgubirilor să se pronunţe instanţa în ordinea procedurii civil Pentru a se pronunţa, instanţa de fond a constatat că: T. V. P. în complicitate cu xxxxNUMExxxx, ce s­a exprimat prin faptul că xxxxNUMExxxx. la indicaţia lui T.V., pe data de 30 august 2012, aproximati la ora 17.00, prin înşelăciune 1­a chemat pe taxistul xxxxNUMExxxx , care a sosit la chemare la casa de locuit, amplasă pe str.C. 85, s.C., ce aparţine lui xxxxNUMExxxx., unde cu scopul sustragerii bunurilor altei persoane, T. V. s­ a ăpustit asupra luxxxxNUMExxxx din spate, i­a legat mîinile şi picioarele cu scotch şi o frînghie, în cap i­a pus un pachet de polietileă, l­a doborât la pământ, cerînd transmiterea banilor, a început să­1 lovească cu mîinile şi picioarele pe diferite părţi ale corpului, aplicînd violeţa periculoasă pentru viaţa şi sănătatea părţii vătămate, cauzîndu­i leziuni corporale uşoare sub formă de trauma crani­cerebrală acută, contuzie, echimoze în regiunea parieto­occipitala, pe cutia toracică din stânga, escoriaţii pe ambele picioare, antebţul drept, după ce au sustras din buzunarul pantalonilor lui xxxxNUMExxxxon 200 lei, cît şi banii din automobilul de mode M , n/î , care era parcat în faţa casei de locuit sus­indicate în sumă de 600 euro, 100 dolari SUA şi 4000 lei, iar total au

[Succeeded / Failed / Skipped / Total] 17 / 20 / 7 / 44:  37%|███▋      | 37/100 [07:16<12:23, 11.81s/it]

--------------------------------------------- Result 44 ---------------------------------------------
[[1 (98%)]] --> [[[FAILED]]]

Prin sentinţa pronunţată instanţa de fond a reţinut, că inculpata PL la 13.01.2005, intenționat, avînd drept scop privatizarea unui imobil, în cadrul dosarului nr.124 despre privatizarea fondului locativ, deschis la cererea cet.L P și L P, pentru privatizarea apartamentului nr.14­a de pe strada , orașul , i­a prezentat cet. V, specialist­principal în problemele privatizării și postrivatizării a Secției economice a Consiliului raional Soroca, secretar al Comisiei privind privatizarea fondului de locuințe, în original, blanchetele „лицевой счет” și “поквартирная карточка” neîndeplinite, eliberate și confirmate prin ștampila Comitetului Sindical al SU­61, filiala SA “”, care de fapt nu era împuternicit cu eliberarea acestora, determinînd­o pe cet.R V, să le completeze cu date false, indicînd în „лицевой счет” faptul, că cet.L P deține apartamentul nr.96 de pe strada , orașul în baza orderului nr.15 din 24.10.2002, cu toate că ultima a prezentat orderul nr.10 din 22.01.2001, potrivit căruia i­a fost repartizată odaia nr.14­a din căminul de pe strada , orașul , totodată înscriind la solicitarea cet.L P în blanchetele „лицевой счет” și “поквартирная карточка”, că cet.L P și L P locuiesc în apartamentul nr. de pe strada , orașul , pe cînd în buletinele de identitate a ambelor persoane domiciliul era indicată strada , orașul . Tot ea, în luna februarie 2005, intenționat, în cadrul dosarului nr.124 despre privatizarea fondului locativ, deschis la cererea cet.L P, pentru privatizarea apartamentului nr.a de pe strada orașul , a determinat­o pe cet.S R, tehnologul Oficiului Cadastral Teritorial Soroca și cet.D M, șef al Secției de Inventariere Tehnică la Oficiul Cadastral Teritorial Soroca, să îndeplinească certificatul­ caracterizare pentru privatizarea locuințelor din 10.02.2005, întocmit de către tehnologul S R și semnat de către D M, în calitate de manager al Oficiului Cadastral Teritorial Soroca, în care statutul de încăpere nelocuibilă a odăii nr.14­a din căminul de pe strada , orașul a fost schimbat în locuibil, neținîndu­se cont de faptul, că la 08.02.2005 nu exista nici un document oficial, eliberat de către Primăria orașului , care ar cataloga încăperea dată în una locuibilă, totodată acordînd ilegal încăperii date statut de apartament sub nr, pe care l­a prezentat la Comisia pentru privatizarea fondului de locuințe, în rezultatul cărui fapt, prin Hotărîrea nr.1 din 14.02.2005 a Comisiei privind privatizarea fondului de locuințe, cet.L P și cet.P L le­a fost permisă privatizarea apartamentului nr., amplasat în căminul de pe strada , orașul . Sentinţa adoptată de instanţa de fond a fost atacată cu apel de către inculpata L.P, motivul invocat fiind ilegalitatea sentinței. Apelanta consideră, că instanța de fond a emis sentința în baza unui act de învinuire din care nu este clar care acțiuni concrete comise de ea i se pun în învinuire, astfel fiind lipsită de posibilitatea de a se apăra. În apel se indică faptul, că procesul penal în privința inculpatei nu putea fi încetat în legătură cu intervenția termenului de prescripție în condițiile inexistenței în acțiunile puse în învinuire a componenței de infracțiune. Solicită admiterea apelului, casarea sentinţei judecătoriei Soroca din 02.06.2015 cu pronunţarea unei noi hotărâri prin care L.P să fie achitată. În şedinţa instanţei de apel inculpata L.P

[Succeeded / Failed / Skipped / Total] 18 / 20 / 8 / 46:  38%|███▊      | 38/100 [07:25<12:06, 11.72s/it]

--------------------------------------------- Result 45 ---------------------------------------------
[[1 (96%)]] --> [[0 (55%)]]

1. Prin sentința Judecătoriei Ungheni din 26 decembrie 2016, Savciuc Alexandru, a fost [[recunoscut]] [[vinovat]] în comiterea infracțiunilor prevăzute de art.48, 145 alin.(2) lit.i), j) şi art.287 alin.(3) Cod penal al RM, fiindu-i stabilită pedeapsa: - în baza art.145 alin. (2) lit. i), j) Cod penal – 16 ani închisoare; - în baza art. 287 alin. (3) Cod penal – 4 ani închisoare. În conformitate cu art.84 Cod penal, pentru concurs de infracţiuni, prin cumul parţial al pedepselor aplicate, i-a fost stabilită pedeapsa definitivă – 17 ani închisoare, cu executarea în penitenciar de tip închis. Concomitent a fost respinsă cererea acuzatorului de stat de a încasa din contul inculpatului cheltuielile în legătură cu extrădarea acestuia, în sumă de 20265,46 lei și 46 bani. 2. Pentru a pronunţa sentinţa, prima [[instanță]] a [[constatat]] că, Savciuc Alexandru, la data de 29.06.2015, aproximativ la orele 00.15 min., din motive huliganice, încălcând grosolan ordinea publică, în participaţie simplă cu Grecu D. şi Daraban I., ultimul având motiv de răzbunare, după un plan bine chibzuit cu repartizarea rolurilor, având toţi trei o înţelegere prealabilă de a-i cauza vătămări corporale lui Şişcanu Ruslan, iar ulterior lui Savciuc Alexandru şi [[Daraban]] I., apărându-le scopul [[lipsirii]] ilegale de viaţă a unei alte persoane, au intrat în ograda lui Nemţanu V. din *****, ***** şi în timp ce acolo se afla Şişcanu Ruslan care dormea, [[Savciuc]] Alexandru cu o ştachetă, împreună şi Daraban I. cu o coadă de hârleţ i-au aplicat lui Şişcanu Ruslan multiple lovituri peste toată suprafaţa corpului, iar Grecu D. i-a aplicat ultimului câteva lovituri cu picioarele în regiunea abdomenului. Tot el, Savciuc Alexandru, în aceleaşi circumstanţe sus menţionate şi în baza aceloraşi intenţii huliganice, conform raportului de [[expertiză]] medico-legală nr.105 din 06.07.2015 i-a cauzat lui Şişcanu [[Ruslan]] [[traumatism]] cranio-cerebral acut închis, hemoragii în ţesuturile moi ale capului în regiunea tempora-occipitală pe dreapta; hemoragie subdurală lichidă; hemoragie subarahnoidală difuză a ambelor emisfere a creierului covescital şi bazai la emisfera dreaptă şi a cerebelului; fractura ambelor oase zigomatice, oaselor nazale multe aşchiate; fractura mandibulei pe dreapta în protecţia dinţilor 6,7 cu deplasarea fragentelor; fractura coastelor bilateral fără lezarea pleurei parietale; multiple echimoze difuze la faţă şi a toracelui; excoriaţii la ambele mâini suprafaţa dorsală; multiple excoriaţii la faţă şi la torace, cauzându-i leziuni corporale grave în urma căruia Şişcanu Ruslan a decedat. Cauza decesului este traumatismul cranio-cerebral închis cu fractura oaselor faciale-zigomatice şi nazale, contuzia cerebrală, plaga contuză stelată masivă a ţesuturilor moi ale capului în regiunea occipitală, hemoragia subdurală şi subarahnoidală. 3. Sentința pronunțată integral la 26 decembrie 2016, a fost atacată cu apeluri de către: - procurorul în Procuratura Ungheni, Steclari Ion, la 29 decembrie 2016, prin care a solicitat casarea sentinţei, rejudecarea cauzei şi pronunţarea unei noi hotărâri, potrivit modului stabilit, pentru prima instanţă, prin care: Savciuc Alexandru să fie recunoscut culpabil în comiterea infracţiunii prevăzute de art. 48, 145 alin. (2) lit. i), j) și art. 287 alin.(3) Cod penal, și prin prisma art. 84 Cod penal, să-i fie stabilită pedeapsa sub formă de închisoare pe un termen de 17 ani cu executarea pedepsei în

1. Prin sentința Judecătoriei Ungheni din 26 decembrie 2016, Savciuc Alexandru, a fost [[recuonscut]] [[vionvat]] în comiterea infracțiunilor prevăzute de art.48, 145 alin.(2) lit.i), j) şi art.287 alin.(3) Cod penal al RM, fiindu-i stabilită pedeapsa: - în baza art.145 alin. (2) lit. i), j) Cod penal – 16 ani închisoare; - în baza art. 287 alin. (3) Cod penal – 4 ani închisoare. În conformitate cu art.84 Cod penal, pentru concurs de infracţiuni, prin cumul parţial al pedepselor aplicate, i-a fost stabilită pedeapsa definitivă – 17 ani închisoare, cu executarea în penitenciar de tip închis. Concomitent a fost respinsă cererea acuzatorului de stat de a încasa din contul inculpatului cheltuielile în legătură cu extrădarea acestuia, în sumă de 20265,46 lei și 46 bani. 2. Pentru a pronunţa sentinţa, prima [[intsanță]] a [[constaatt]] că, Savciuc Alexandru, la data de 29.06.2015, aproximativ la orele 00.15 min., din motive huliganice, încălcând grosolan ordinea publică, în participaţie simplă cu Grecu D. şi Daraban I., ultimul având motiv de răzbunare, după un plan bine chibzuit cu repartizarea rolurilor, având toţi trei o înţelegere prealabilă de a-i cauza vătămări corporale lui Şişcanu Ruslan, iar ulterior lui Savciuc Alexandru şi [[Draaban]] I., apărându-le scopul [[lipisrii]] ilegale de viaţă a unei alte persoane, au intrat în ograda lui Nemţanu V. din *****, ***** şi în timp ce acolo se afla Şişcanu Ruslan care dormea, [[Sacviuc]] Alexandru cu o ştachetă, împreună şi Daraban I. cu o coadă de hârleţ i-au aplicat lui Şişcanu Ruslan multiple lovituri peste toată suprafaţa corpului, iar Grecu D. i-a aplicat ultimului câteva lovituri cu picioarele în regiunea abdomenului. Tot el, Savciuc Alexandru, în aceleaşi circumstanţe sus menţionate şi în baza aceloraşi intenţii huliganice, conform raportului de [[expertziă]] medico-legală nr.105 din 06.07.2015 i-a cauzat lui Şişcanu [[Rsulan]] [[traumatsim]] cranio-cerebral acut închis, hemoragii în ţesuturile moi ale capului în regiunea tempora-occipitală pe dreapta; hemoragie subdurală lichidă; hemoragie subarahnoidală difuză a ambelor emisfere a creierului covescital şi bazai la emisfera dreaptă şi a cerebelului; fractura ambelor oase zigomatice, oaselor nazale multe aşchiate; fractura mandibulei pe dreapta în protecţia dinţilor 6,7 cu deplasarea fragentelor; fractura coastelor bilateral fără lezarea pleurei parietale; multiple echimoze difuze la faţă şi a toracelui; excoriaţii la ambele mâini suprafaţa dorsală; multiple excoriaţii la faţă şi la torace, cauzându-i leziuni corporale grave în urma căruia Şişcanu Ruslan a decedat. Cauza decesului este traumatismul cranio-cerebral închis cu fractura oaselor faciale-zigomatice şi nazale, contuzia cerebrală, plaga contuză stelată masivă a ţesuturilor moi ale capului în regiunea occipitală, hemoragia subdurală şi subarahnoidală. 3. Sentința pronunțată integral la 26 decembrie 2016, a fost atacată cu apeluri de către: - procurorul în Procuratura Ungheni, Steclari Ion, la 29 decembrie 2016, prin care a solicitat casarea sentinţei, rejudecarea cauzei şi pronunţarea unei noi hotărâri, potrivit modului stabilit, pentru prima instanţă, prin care: Savciuc Alexandru să fie recunoscut culpabil în comiterea infracţiunii prevăzute de art. 48, 145 alin. (2) lit. i), j) și art. 287 alin.(3) Cod penal, și prin prisma art. 84 Cod penal, să-i fie stabilită pedeapsa sub formă de închisoare pe un termen de 17 ani cu executarea pedepsei în


--------------------------------------------- Result 46 ---------------------------------------------
[[1 (67%)]] --> [[[SKIPPED]]]

În conformitate cu prevederile art.art.3641, 382-399 Cod de procedură penală, instanța de judecată,

[Succeeded / Failed / Skipped / Total] 18 / 21 / 8 / 47:  39%|███▉      | 39/100 [07:39<11:58, 11.78s/it]

--------------------------------------------- Result 47 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Adoptînd sentinţa în cauză instanţa de fond a reţinut, că xxxxNUMExxxx la 22.05.2014, în jurul orelor 20.00, aflîndu­se în s. xxxxORAS_SATxxxx r­l , pe ascuns și întenționat, a pătruns în gospodăria cet.xxxxNUMExxxx, unde din casa acestuia ­o geantă care se pe dulap, a sustras și însușit suma de 1400 lei, cauzînd astfel părții vătămate o daună materială considerabilă. Cauza penală a fost examenată de către instanța de fond în lipsa inculpatului, care se eschiva de la prezentare în fața instanței și care prin încheierea din 23.09.2014 a fost anunțat în căutare, fiind dispusă eliberarea pe numele acestuia a unui mandat de arestare pe un termen de 30 zile. Instanţa de fond a pronunţat sentinţa nominalizată. Inculpatul după reținerea sa și îmînarea copiei sentinței a atacat cu apel sentinţa invocînd ca motive că: consideră pedepsa stabilită de către instanţa de fond ca fiind prea aspră, dat fiind faptul, că vina în comiterea infracţiunii incriminate a recunoscut­o pe deplin şi sincer se căieşte de cele comise; invocă că executarea pedepsei în penitenciar va influenţa în mod negativ asupra sa. El a plecat la lucru peste hotare din dorința de a recupera dauna materială, însă nu a putut reveni la timp acasă. Pe aceste motive apelantul solicită admiterea apelului declarat, cu casarea sentinţei judecătoriei Soroca din 12.12.2014 şi pronunţarea unei noi hotărîri prin care să­i fie stabilită o pedepsă mai blînde nonprivative de libertate. După reluarea cercetării judecătoreşti potrivit modului stabilit pentru prima instanţă și audierea nemijlocită în şedinţa instanţei de apel a inculpatului xxxxNUMExxxx dat fiind faptul, că acesta nu a fost audiat și nu a participat în ședința instanței de fond, a parvenit o cerere în ședința instanței de apel la data de 06.05.2015 din partea părții vătămate xxxxNUMExxxx prin care a solicitat încetarea procesului penal în legătură cu faptul împăcării lui cu inculpatul. În şedinţa instanţei de apel partea vătămată xxxxNUMExxxx a susținut cererea sa cu privire la încetarea procesului penal în legătură cu împăcarea părților. Inculpatul xxxxNUMExxxx și avocatul Muntean Violina, care i­a reprezentat interesele în instanța de apel, au solicitat încetarea procesului penal în legătură cu împăcarea părților. Procurorul participant a pledat pentru respingerea cererii de încetare a procesului penal în legătură cu împăcarea părților și respingerea apelului inculpatului ca nefondat. Colegiul penal, audiind părţile, examinînd materialele dosarului, consideră posibilă admiterea cererii de împăcare a părților cu încetarea procesului penal în privința inculpatului xxxxNUMExxxx. Conform prevederilor art.391 alin.(1) pct.1) CPP sentința de încetare a procesului penal se adoptă dacă lipsește plîngerea părții vătămate, plîngerea a fost retrasă sau părțile s­au împăcat. Potrivit art.16 alin.(3) CP infracțiunea prevăzute de art.186 alin.(2) CP se califică ca mai puțin gravă, deoarece prevede pedeapsă maximă a închisorii pe un termen de pînă la 4 ani. Potrivit art.109 alin.(1) CP împăcarea este actul de înlăturare a răspunderii penale pentru o infracțiune ușoară sau mai puțin gravă, iar în cazul minorilor, și pentru o infracțiune gravă, infracțiuni incorporate în capitolele II­VI din Partea specială, precum și în cazurile prevăzute de procedura penală. Potrivit alin. (2) art. 109 CP împăcarea este personală şi produce efecte juridice din

[Succeeded / Failed / Skipped / Total] 19 / 21 / 8 / 48:  40%|████      | 40/100 [07:52<11:48, 11.81s/it]

--------------------------------------------- Result 48 ---------------------------------------------
[[0 (99%)]] --> [[1 (50%)]]

Grințevici Serghei, la data de 17.08.2015, aproximativ la ora 03:00, fiind în stare de ebrietate, înțelegînd caracterul prejudiciabil al acțiunilor sale, a condus autocamionul de model „Fiat Scudo” cu nr. de înmatriculare SG AM 213, prin s. Alexăndreni, r­nul Sîngerei unde a fost stopat de colaboratorii poliției și fiind suspectat în consum de băuturi alcoolice, a fost supus testării alcoolscopice, prin care s­a constatat o concentrație de alcool în aerul expirat de 0,5 mg/l. În ședința de [[judecată]] [[inculpatul]] Grințevici vina și­a recunoscut­o pe deplin, se căiește în cele săvîrșite de el și a [[declarat]] că la data de 17.08.2015, aproximativ la ora 03:00, fiind în stare de ebrietate, a condus autocamionul de model „Fiat Scudo” cu nr. de înmatriculare SG AM 213, prin s. Alexăndreni, r­nul [[Sîngerei]] unde a fost stopat de colaboratorii poliției și supus testării alcoolscopice, prin care s­a constatat o concentrație de alcool în aerul expirat de 0,5 mg/l. [[Inculpatul]] în ședința de judecată a solicitat aplicarea unei pedepse sub formă de amendă. În afară de recunoașterea faptei de [[către]] inculpat, vina lui în ședința judiciară este dovedită și de: ­ Raportul privind recepționarea [[apelului]] telefonic. /f.d. 7/; ­ Proces­verbal de testare alcoolscopicăcși anexe. /f.d. 9­10/; ­ Proces­verbal de constatare a faptei de conducere a mijlocuui de transport în stare de ebrietate alcoolică. /f.d. 11/; ­ Proces­[[verbal]] nr. 268 al [[examinării]] medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate și naturii ei, conform căruia Grințevici [[Serghei]] se afla în stare de ebrietate alcoolică cu [[grad]] avansat. /f.d. 10­11/; În aşa mod, instanţa consideră vina inculpatului Grințevici [[Serghei]] dovedită şi confirmată pe [[deplin]] în şedinţa [[judiciară]], iar acţiunile lui le califică în [[baza]] art. [[2641]] alin. (1) CP al Republicii [[Moldova]] după [[semnele]]: ­ [[Conducerea]] mijlocului de transport de [[către]] o persoană [[care]] se află în stare de ebrietate alcoolică cu [[grad]] [[avansat]]. Conform art. 76, 77 CP RM la stabilirea măsurii de [[pedeapsă]] in privinţa [[inculpatului]], judecata ţine cont de circumstanţele [[atenuante]] şi agravante la săvîrşirea infracţiunii. Circumstanţe atenuante în [[ședința]] de [[judecată]] nu au [[fost]] stabilite. Circumstanţe agravante în privinţa inculpatului XXXXXXXXX – săvîrșirea infracțiunii în stare de ebrietate. Prin sentința Judecătoriei Sîngerei din 13 octombrie 2015, Grințevici Serghei a fost condamnat în baza art. 27, 186 alin. (2) lit. c), d) CP RM, fiindu­i stabilită o pedeapsă sub formă de închisoare pe un termen de 2 (doi) ani, în penitenciar de tip semiînchis. Potrivit art. 87 CPP – (1) La cumularea diferitelor pedepse principale aplicate în cazul unui concurs de infracţiuni sau al unui cumul de sentinţe, unei zile de închisoare îi corespund 2 ore de muncă neremunerată în folosul comunităţii. (2) Celelalte pedepse cumulate cu închisoarea se execută de sine stătător. Ţinînd cont de circumstanţele expuse mai sus, de faptul că Grințevici Serghei și­a recunoscut vina integral, se căiește de cele săvîrșite, instanța de judecată ajunge la concluzia de a aplica în privința lui Grințevici Serghei o pedeapsă sub formă de amendă. În conformitate cu art.art. 384­386 CPP al RM instanţa de judecată,­

Grințevici Serghei, la data de 17.08.2015, aproximativ la ora 03:00, fiind în stare de ebrietate, înțelegînd caracterul prejudiciabil al acțiunilor sale, a condus autocamionul de model „Fiat Scudo” cu nr. de înmatriculare SG AM 213, prin s. Alexăndreni, r­nul Sîngerei unde a fost stopat de colaboratorii poliției și fiind suspectat în consum de băuturi alcoolice, a fost supus testării alcoolscopice, prin care s­a constatat o concentrație de alcool în aerul expirat de 0,5 mg/l. În ședința de [[judectaă]] [[icnulpatul]] Grințevici vina și­a recunoscut­o pe deplin, se căiește în cele săvîrșite de el și a [[declaart]] că la data de 17.08.2015, aproximativ la ora 03:00, fiind în stare de ebrietate, a condus autocamionul de model „Fiat Scudo” cu nr. de înmatriculare SG AM 213, prin s. Alexăndreni, r­nul [[Sîgnerei]] unde a fost stopat de colaboratorii poliției și supus testării alcoolscopice, prin care s­a constatat o concentrație de alcool în aerul expirat de 0,5 mg/l. [[Inculptaul]] în ședința de judecată a solicitat aplicarea unei pedepse sub formă de amendă. În afară de recunoașterea faptei de [[cărte]] inculpat, vina lui în ședința judiciară este dovedită și de: ­ Raportul privind recepționarea [[apleului]] telefonic. /f.d. 7/; ­ Proces­verbal de testare alcoolscopicăcși anexe. /f.d. 9­10/; ­ Proces­verbal de constatare a faptei de conducere a mijlocuui de transport în stare de ebrietate alcoolică. /f.d. 11/; ­ Proces­[[vrebal]] nr. 268 al [[examinrăii]] medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate și naturii ei, conform căruia Grințevici [[Serhgei]] se afla în stare de ebrietate alcoolică cu [[gard]] avansat. /f.d. 10­11/; În aşa mod, instanţa consideră vina inculpatului Grințevici [[Sergehi]] dovedită şi confirmată pe [[depiln]] în şedinţa [[juidciară]], iar acţiunile lui le califică în [[bzaa]] art. [[2461]] alin. (1) CP al Republicii [[Modlova]] după [[senmele]]: ­ [[Cnoducerea]] mijlocului de transport de [[cărte]] o persoană [[crae]] se află în stare de ebrietate alcoolică cu [[gard]] [[aavnsat]]. Conform art. 76, 77 CP RM la stabilirea măsurii de [[pedeaspă]] in privinţa [[inculpatluui]], judecata ţine cont de circumstanţele [[aetnuante]] şi agravante la săvîrşirea infracţiunii. Circumstanţe atenuante în [[șeidnța]] de [[jduecată]] nu au [[fsot]] stabilite. Circumstanţe agravante în privinţa inculpatului XXXXXXXXX – săvîrșirea infracțiunii în stare de ebrietate. Prin sentința Judecătoriei Sîngerei din 13 octombrie 2015, Grințevici Serghei a fost condamnat în baza art. 27, 186 alin. (2) lit. c), d) CP RM, fiindu­i stabilită o pedeapsă sub formă de închisoare pe un termen de 2 (doi) ani, în penitenciar de tip semiînchis. Potrivit art. 87 CPP – (1) La cumularea diferitelor pedepse principale aplicate în cazul unui concurs de infracţiuni sau al unui cumul de sentinţe, unei zile de închisoare îi corespund 2 ore de muncă neremunerată în folosul comunităţii. (2) Celelalte pedepse cumulate cu închisoarea se execută de sine stătător. Ţinînd cont de circumstanţele expuse mai sus, de faptul că Grințevici Serghei și­a recunoscut vina integral, se căiește de cele săvîrșite, instanța de judecată ajunge la concluzia de a aplica în privința lui Grințevici Serghei o pedeapsă sub formă de amendă. În conformitate cu art.art. 384­386 CPP al RM instanţa de judecată,­

[Succeeded / Failed / Skipped / Total] 20 / 21 / 8 / 49:  41%|████      | 41/100 [08:05<11:38, 11.84s/it]

--------------------------------------------- Result 49 ---------------------------------------------
[[0 (96%)]] --> [[1 (52%)]]

La 30.07.2015 [[condamnatul]], XXXXXXXXX, a înaintat recurs împotriva încheierii din 23.07.2015 a judecătoriei Soroca. Drept motiv, în argumentarea şi susţinerea recursului, recurentul invocă, că instanţa de fond n­a calculat corect termenul de executare a pedepsei penale şi că acesta urmează a fi de 15 ani şi 1 lună, dar nu 15 ani şi 6 luni de închisoare în penitenciar de tip închis. Avocatul D.Duca a solicitat admiterea recursului. În şedinţa instanţei de recurs procurorul a solicitat respingerea recursului. Condamnatul XXXXXXXXX a solicitat examinarea cauzei în lipsa sa, solicitînd remiterea copiei deciziei. Verificînd argumentele recurentului, ascultînd participanţii, studiind materialele cauzei, Colegiul penal consideră, că recursul declarat urmează a fi respins ca nefondat. Conform prevederilor art.449 alin.(1) pct.1) lit.a) Cod de procedură penală, ,,Judecînd recursul, instanţa adoptă una din următoarele decizii 1) respinge recursul, menţinînd hotărîrea atacată, dacă a) recursul este nefondat;” Prin sentinţa judecătoriei Ciocana mun.Chişinău din 24.05.2007, XXXXXXXXX xxxxx a fost condamnat în baza art.145 alin.(2) lit.c) Cod penal la 17 ani de închisoare cu ispăşirea în penitenciar de tip închis, fiind inclus şi termenul de ţinere în [[stare]] de arest 15.12.2006­03.05.2007. Prin sentinţa judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, XXXXXXXXX xxxxxr a fost condamnat în baza art.217 alin.(2) Cod penal la 6 luni de închisoare şi conform art.84 alin.(4) Cod penal, prin cumul partial al pedepsei stabilite prin sentinţa judecătoriei Ciocana mun.Chişinău din 24.05.2007, i­a fost stabilit definitiv 17 ani şi 1 lună de închisoare cu ispăşirea în [[penitenciar]] de tip închis, fiind inclus termenul arestului preventive din 15.12.2006­XXXXXXXXX. Prin încheierea judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, a fost admisă cererea [[condamnatului]] XXXXXXXXX Victor şi au [[fost]] recalificate acţiunile lui din prevederile art.145 [[alin]].(2) lit.c) Cod penal în prevederile art.145 alin.(1) Cod penal, stabilindu­i pedeapsă de 15 ani de închisoare cu executarea pedepsei în [[penitenciar]] de tip [[închis]], fiind înclus termenul de la 15.12.2006 pînă la XXXXXXXXX. Prin încheierea judecătoriei Soroca din XXXXXXXXX lui xxxxxx i­a fost stabilit pedeapsa penală definitivă de 15 ani şi 6 luni închisoare în penitenciar de tip închis. Instanţa de fond a adoptat o încheiere legală şi întemeiată, fiind luate în consideraţie hotărîrile de condamnare anterioare, cît şi prevederile art.84 alin.(4) Cod penal. Corect a fost calculat termenul pedepsei de 15 ani şi 6 luni de închisoare, aşa cum XXXXXXXXX xxx a fost condamnat în baza art.217 alin.(2) Cod penal la 6 luni de închisoare prin sentinţa judecătoriei Buiucani mun.Chişinău din XXXXXXXXX şi la 15 ani de închisoare prin încheierea judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, iar prin art.84 alin.(4) Cod penal aceste pedepse au fost cumulate total, aceasta rezultînd atît din parte descriptivă, cît şi din parte dispozitivă a încheierii. Prevederile art.84 alin.(4) Cod penal au fost corect aplicate de către instanţa de fond. Argumentele expuse în recurs nu pot prevala situaţiei de fapt reţinute şi prevederilor legale. În baza celor menţionate, Colegiul penal a ajuns la concluzia, că recursul este nefondat şi urmează a fi respins, cu menţinerea încheierii atacate. Conducîndu­se de art.art.447­ 448, art.449 alin.(1), p.1), lit.a) Cod de procedură penală al RM, Colegiul penal,­

La 30.07.2015 [[condamnautl]], XXXXXXXXX, a înaintat recurs împotriva încheierii din 23.07.2015 a judecătoriei Soroca. Drept motiv, în argumentarea şi susţinerea recursului, recurentul invocă, că instanţa de fond n­a calculat corect termenul de executare a pedepsei penale şi că acesta urmează a fi de 15 ani şi 1 lună, dar nu 15 ani şi 6 luni de închisoare în penitenciar de tip închis. Avocatul D.Duca a solicitat admiterea recursului. În şedinţa instanţei de recurs procurorul a solicitat respingerea recursului. Condamnatul XXXXXXXXX a solicitat examinarea cauzei în lipsa sa, solicitînd remiterea copiei deciziei. Verificînd argumentele recurentului, ascultînd participanţii, studiind materialele cauzei, Colegiul penal consideră, că recursul declarat urmează a fi respins ca nefondat. Conform prevederilor art.449 alin.(1) pct.1) lit.a) Cod de procedură penală, ,,Judecînd recursul, instanţa adoptă una din următoarele decizii 1) respinge recursul, menţinînd hotărîrea atacată, dacă a) recursul este nefondat;” Prin sentinţa judecătoriei Ciocana mun.Chişinău din 24.05.2007, XXXXXXXXX xxxxx a fost condamnat în baza art.145 alin.(2) lit.c) Cod penal la 17 ani de închisoare cu ispăşirea în penitenciar de tip închis, fiind inclus şi termenul de ţinere în [[satre]] de arest 15.12.2006­03.05.2007. Prin sentinţa judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, XXXXXXXXX xxxxxr a fost condamnat în baza art.217 alin.(2) Cod penal la 6 luni de închisoare şi conform art.84 alin.(4) Cod penal, prin cumul partial al pedepsei stabilite prin sentinţa judecătoriei Ciocana mun.Chişinău din 24.05.2007, i­a fost stabilit definitiv 17 ani şi 1 lună de închisoare cu ispăşirea în [[peintenciar]] de tip închis, fiind inclus termenul arestului preventive din 15.12.2006­XXXXXXXXX. Prin încheierea judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, a fost admisă cererea [[codnamnatului]] XXXXXXXXX Victor şi au [[fsot]] recalificate acţiunile lui din prevederile art.145 [[ailn]].(2) lit.c) Cod penal în prevederile art.145 alin.(1) Cod penal, stabilindu­i pedeapsă de 15 ani de închisoare cu executarea pedepsei în [[pentienciar]] de tip [[îcnhis]], fiind înclus termenul de la 15.12.2006 pînă la XXXXXXXXX. Prin încheierea judecătoriei Soroca din XXXXXXXXX lui xxxxxx i­a fost stabilit pedeapsa penală definitivă de 15 ani şi 6 luni închisoare în penitenciar de tip închis. Instanţa de fond a adoptat o încheiere legală şi întemeiată, fiind luate în consideraţie hotărîrile de condamnare anterioare, cît şi prevederile art.84 alin.(4) Cod penal. Corect a fost calculat termenul pedepsei de 15 ani şi 6 luni de închisoare, aşa cum XXXXXXXXX xxx a fost condamnat în baza art.217 alin.(2) Cod penal la 6 luni de închisoare prin sentinţa judecătoriei Buiucani mun.Chişinău din XXXXXXXXX şi la 15 ani de închisoare prin încheierea judecătoriei Buiucani mun.Chişinău din XXXXXXXXX, iar prin art.84 alin.(4) Cod penal aceste pedepse au fost cumulate total, aceasta rezultînd atît din parte descriptivă, cît şi din parte dispozitivă a încheierii. Prevederile art.84 alin.(4) Cod penal au fost corect aplicate de către instanţa de fond. Argumentele expuse în recurs nu pot prevala situaţiei de fapt reţinute şi prevederilor legale. În baza celor menţionate, Colegiul penal a ajuns la concluzia, că recursul este nefondat şi urmează a fi respins, cu menţinerea încheierii atacate. Conducîndu­se de art.art.447­ 448, art.449 alin.(1), p.1), lit.a) Cod de procedură penală al RM, Colegiul penal,­

[Succeeded / Failed / Skipped / Total] 21 / 21 / 8 / 50:  42%|████▏     | 42/100 [08:13<11:21, 11.76s/it]

--------------------------------------------- Result 50 ---------------------------------------------
[[1 (58%)]] --> [[0 (77%)]]

Prin sentința Judecătoriei Vulcănești din 12 iulie 2013 xxxxxxxxxxxx a fost achitat de învinuirea de săvârşire a infracţiunilor prevăzută de art. 287 alin.(3) și art. 151 alin.(1) Cod penal din motivul că acțiunile inculpatului au fost săvârșite în stare de legitimă apărare. Pentru a pronunța sentința de achitare în privința inculpatului xxxxxxxxxx prima [[instanță]] a reţinut că, xxxxxxxxxxx se învinuiește că la 29 octombrie 2011, pe timp de noapte, în încăperea pentru animale a fostei ferme de produse lactate ”xxxxxxxxxx”, din intenții huliganice, în prezența altor persoane,intenționat, încălcând grosolan ordinea publică și liniștea cetățenilor, acționând cu o deosebită obrăznicie, fiind înarmat cu un cuțit, a aplicat în privința lui xxxxxxxxxxn și xxxxxxxxxxx, violența fizică, manifestată prin cauzarea diferitor leziuni corporale, de asemenea a încercat să aplice violența fizică cu cuțitul în privința lui xxxxxxxxxxxxx. Tot, el, la 29 octombrie 2011, pe timp de noapte, în încăperea pentru animale a fostei ferme de produse lactate SRL”xxxxxxxxx”, din intenții huliganice, în prezența altor persoane,intenționat, încălcând grosolan ordinea publică și liniștea cetățenilor, acționând cu o deosebită obrăznicie, fiind înarmat cu un cuțit, a aplicat în privința lui xxxxxxxxxx, violența fizică, manifestată prin cauzarea leziunilor corporale sub formă de plagă tăiată a cutiei toracice pe stânga penetrantă în cavitatea pleurei, cu lezarea părții de jos a plămânului; plagă a peretelui cavității abdominale fără penetrare în cavitatea abdominală, care conform raportului de expertiză cu nr. 48d din 16.11.2011, au fost produse prin acțiunea traumatică a unui obiect ascuțit­tăietor, posibil cu cuțit, și se califică ca leziuni corporale grave, periculoase pentru viață. Împotriva sentinței enunțate, la data de 24 iulie 2013, procurorul în Procuratura raionului Vulcănești, xxxxxxxxx, a declarat apel, prin care a solicitat casarea cesteia, cu pronunțarea unei noi hotărâri, prin care xxxxxxxxxxx să fie recunoscut vinovat în comiterea infracțiunilor prevăzute de art. 287 alin.(3) și art. 151 alin.(1) Cod penal, cu aplicarea pedepsei în baza art. 287 alin.(3) Cod penal la 03 ani închisoare, în baza art. 151 alin.(1) Cod penal, la 03 ani închisoare. Conform art. 84 Cod penal, pentru concurs de infracțiuni prin cumul parțial al pedepselor aplicate, de a stabili pedeapsa definitivă sub formă de 04 ani închisoare cu executarea pedepsei în penitenciar de tip semiînchis. Conform art. 90 Cod penal, să­i fie suspendată condiţionat executarea pedepsei pe un termen de probă de 04 ani, și cu stabilirea conform art. 90 alin.(6) Cod penal, obligații inculpatului. Concomitent, potrivit art. 90 alin.(5) și 67 Cod penal, să­i fie aplicată inculpatului pedeapsa complementară sub formă de muncă neremunerată în folosul comunității în mărime de 200 ore. În motivarea apelului s­a indicat că, acuzatorul de stat nu contestă concluzia instanței de judecată în partea cât privește prezența în acțiunile inculpatului xxxxxxxx a elementelor infracțiunilor prevăzute de art. 287 alin.(3) și art. 151 alin.(1) Cod penal, însă contestă concluzia instanței că în acțiunile inculpatului este prezentă legitima apărare, adică circumstanța care înlătură caracterul penal al faptei. Motivele dezacordului cu concluziile instanței de judecată rezultă din faptul că instanța nu a cercetat și nu a argumentat toate criteriile prevăzute la art. 36 Cod penal, fiind descris doar faptul

Prin sentința Judecătoriei Vulcănești din 12 iulie 2013 xxxxxxxxxxxx a fost achitat de învinuirea de săvârşire a infracţiunilor prevăzută de art. 287 alin.(3) și art. 151 alin.(1) Cod penal din motivul că acțiunile inculpatului au fost săvârșite în stare de legitimă apărare. Pentru a pronunța sentința de achitare în privința inculpatului xxxxxxxxxx prima [[isntanță]] a reţinut că, xxxxxxxxxxx se învinuiește că la 29 octombrie 2011, pe timp de noapte, în încăperea pentru animale a fostei ferme de produse lactate ”xxxxxxxxxx”, din intenții huliganice, în prezența altor persoane,intenționat, încălcând grosolan ordinea publică și liniștea cetățenilor, acționând cu o deosebită obrăznicie, fiind înarmat cu un cuțit, a aplicat în privința lui xxxxxxxxxxn și xxxxxxxxxxx, violența fizică, manifestată prin cauzarea diferitor leziuni corporale, de asemenea a încercat să aplice violența fizică cu cuțitul în privința lui xxxxxxxxxxxxx. Tot, el, la 29 octombrie 2011, pe timp de noapte, în încăperea pentru animale a fostei ferme de produse lactate SRL”xxxxxxxxx”, din intenții huliganice, în prezența altor persoane,intenționat, încălcând grosolan ordinea publică și liniștea cetățenilor, acționând cu o deosebită obrăznicie, fiind înarmat cu un cuțit, a aplicat în privința lui xxxxxxxxxx, violența fizică, manifestată prin cauzarea leziunilor corporale sub formă de plagă tăiată a cutiei toracice pe stânga penetrantă în cavitatea pleurei, cu lezarea părții de jos a plămânului; plagă a peretelui cavității abdominale fără penetrare în cavitatea abdominală, care conform raportului de expertiză cu nr. 48d din 16.11.2011, au fost produse prin acțiunea traumatică a unui obiect ascuțit­tăietor, posibil cu cuțit, și se califică ca leziuni corporale grave, periculoase pentru viață. Împotriva sentinței enunțate, la data de 24 iulie 2013, procurorul în Procuratura raionului Vulcănești, xxxxxxxxx, a declarat apel, prin care a solicitat casarea cesteia, cu pronunțarea unei noi hotărâri, prin care xxxxxxxxxxx să fie recunoscut vinovat în comiterea infracțiunilor prevăzute de art. 287 alin.(3) și art. 151 alin.(1) Cod penal, cu aplicarea pedepsei în baza art. 287 alin.(3) Cod penal la 03 ani închisoare, în baza art. 151 alin.(1) Cod penal, la 03 ani închisoare. Conform art. 84 Cod penal, pentru concurs de infracțiuni prin cumul parțial al pedepselor aplicate, de a stabili pedeapsa definitivă sub formă de 04 ani închisoare cu executarea pedepsei în penitenciar de tip semiînchis. Conform art. 90 Cod penal, să­i fie suspendată condiţionat executarea pedepsei pe un termen de probă de 04 ani, și cu stabilirea conform art. 90 alin.(6) Cod penal, obligații inculpatului. Concomitent, potrivit art. 90 alin.(5) și 67 Cod penal, să­i fie aplicată inculpatului pedeapsa complementară sub formă de muncă neremunerată în folosul comunității în mărime de 200 ore. În motivarea apelului s­a indicat că, acuzatorul de stat nu contestă concluzia instanței de judecată în partea cât privește prezența în acțiunile inculpatului xxxxxxxx a elementelor infracțiunilor prevăzute de art. 287 alin.(3) și art. 151 alin.(1) Cod penal, însă contestă concluzia instanței că în acțiunile inculpatului este prezentă legitima apărare, adică circumstanța care înlătură caracterul penal al faptei. Motivele dezacordului cu concluziile instanței de judecată rezultă din faptul că instanța nu a cercetat și nu a argumentat toate criteriile prevăzute la art. 36 Cod penal, fiind descris doar faptul

[Succeeded / Failed / Skipped / Total] 21 / 22 / 8 / 51:  43%|████▎     | 43/100 [08:27<11:12, 11.80s/it]

--------------------------------------------- Result 51 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Pe data de 22 ianuarie 2011 , în intervalul de timp cuprins între ora 05.00 – 05.47 , inculpatul xxxxNUMExxxx conducînd automobilul de marca „BMW” model 520 , cu numărul de înregistrare WW­KS 751 în or.Rezina , str.27 August a încălcat prevederile Regulamentului Circulaţiei Rutiere, aprobat prin HG RM nr.357 din 13.05.2009 , şi anume : pct.3 , care prevede – „participanţii la trafic sînt obligaţi să respecte regulile de circulaţie , condiţiile tehnice ale prezentului Regulament şi prin acţiunile lor să nu cauzeze prejudicii altor participanţi la trafic , să nu­i expună pericolului , precum şi să nu creeze neîntemeiat obstacole circulaţiei care ar depăşi pe acele care sînt provocate de circumstanţe iminente” ; pct.10 al.(2) lit.a) – „persoana care conduce un autovehicul trebuie să posede , şi la cererea lucrătorului de poliţie , ofiţerului echipe mobile al serviciului vamal , este obligată să înmîneze pentru control permisul de conducere perfectat pe numele său, valabil pentru categoria, din care face parte autovehicolul condus ; pct.14 lit.a) – „conducătorului îi este interzis să conducă vehicolul în stare de ebrietate”, deoarece conducătorul auto nu deţinea permis de conducere şi potrivit examinării medicale pentru stabilirea stării de ebrietate şi naturii ei , s­a constatat că, concentraţia de alcool în sîngele şoferului xxxxNUMExxxx este de 1,03 g/l , iar concentraţia vaporilor de alcool în aerul expirat de 0,63 mg/l , care conform art.134/12 al.(3) din Codul Penal al RM se califică ca stare de ebrietate alcoolică cu grad avansat. Vina inculpatului xxxxNUMExxxx în comiterea acestei infracţiuni a fost dovedită în cadrul cercetărilor judecătoreşti prin declaraţiile martorilor şi prin materialele dosarului penal. Astfel martorul Muştuc Mihail a declarat în instanţa de judecată că activează în SPR a CPR Rezina în funcţie de inspector pentru Sistematizarea Circulaţiei Rutiere. La 22.01.2011 efectua serviciul în grupa operativă a CPR Rezina. Pe la vre­o orele 05.30 min. pe str.27 August în or.Rezina a stopat pentru verificare automobilul de model „BMW” , care avea o deplasare neadecvată. La volanul automobilului respectiv se afla şoferul xxxxNUMExxxx, care era de unul singur în automobil. A simţit miros puternic de alcool de la şofer şi i­a cerut actele la control. Nasaev în mod categoric a refuzat să­i prezinte actele. L­a supus verificării la alcotestul „Drager” , în urma la ce s­a stabilit că concentraţia vaporilor de alcool în aerul expirat constituie 0,63 mg/litru. În continuare xxxxNUMExxxx. a fost condus la secţia de internare a spitalui raional Rezina , unde a fost supus examinării medicale de către medicul Renchez Valentina. În urma controlului medical s­a constat că întradevăr xxxxNUMExxxx este în stare de ebrietate alcoolică. Tot atunci i­au fost recoltate probe biologice , sînge din venă pentru analiza de laborator.Verificînd datele Centrului de informaţie s­a constatat că, cet.xxxxNUMExxxx nu dispune de permisul de conducere. Martorul Renchez Valentina a declarat judecăţii că la 21.01.2011 a intrat în serviciul de gardă la spital. Aproximativ pe la orele 05.40 pe data de 22.01.2011 în spital a fost adus de către inspectorul poliţiei rutiere Muştuc M. pentru examinarea medicală şi aprecierea stării de ebrietate cet. xxxxNUMExxxx. În urma examinării

[Succeeded / Failed / Skipped / Total] 22 / 22 / 9 / 53:  44%|████▍     | 44/100 [08:35<10:56, 11.72s/it]

--------------------------------------------- Result 52 ---------------------------------------------
[[0 (94%)]] --> [[1 (54%)]]

XXXXXXXXX, la data de 13.09.2014, aproximativ pe la orele 19:00, aflîndu­se în locuinţa cet. XXXXXXXXX Tudor, a.n. 01.01.1975, situată pe teritoriul Întovărăşirii pomicole «Raduga» din s.[[Corlăteni]] r­nul Rîşcani, fiind în stare de ebrietate alcoolică, în rezultatul unui conflict care a apărut între el şi cet. XXXXXXXXX Tudor, cu care au servit băuturi alcoolice, intenţionat, l­a ameninţat cu omor pe cet.XXXXXXXXX Tudor, după care, cu ajutorul unui topor pe care l­a găsit în locuinţa ultimului, a încercat să­l lovească pe cet.Vizir Ştefan Tudor în regiunea capului, existînd pericolul realizării acestei ameninţări, însă acţiunile de violenţă au fost contracarate de către victimă, care au fost percepute ca reale. În cadrul şedinţei de judecată [[inculpatul]] XXXXXXXXX a recunoscut integral vinovăţia în faptele comise şi a declarat că dorește să se împace cu partea vătămată. [[Necătînd]] la faptul recunoaşterii vinovăţiei inculpatului XXXXXXXXX, culpa acestuia se devedeşte şi de declarațiile: Părții vătămate XXXXXXXXX care a declarat că, la data de 13.09.2014, la orele 19:00 a servit băuturi alcoolice. Între el și Postoronco Stanislav s­a iscat un conflict. Ambii se aflau în stare de ebrietate. Postoronco Stanislav în timpul conflictului se afla cu toporul în mînă. Cînd dînsul a vrut să­i i­a toporul, în timpul dînsul s­a lovit de topor. Concubina a chemat salvarea care a comunicat la poliție. La moment careva pretenții materiale sau morale față de Postoronco Stanislav nu are. Solicită încetarea procesului penal în privința lui Postoronco Stanislav, și de materialele cauzei penale administrate în cadrul cercetării judecătorești şi anume: * Procesul­[[verbal]] de sesizare despre săvârşirea sau pregătirea pentru săvârşirea infracţiunii din 13.09.2014 – Vizir Ştefan Tudor. (f.d. 5 ) * Proces­[[verbal]] de cercetare la faţa locului din 13.09.2014 (f.d. 7­9 ) * Planşa fotografică (f.d. 10­15) * Ordonanţă de ridicare din 13.09.2014 (f.d. 16, 18) * Proces­verbal de ridicare din 13.09.2014 (f.d. 17, 19) * Raportul de expertiză medico­legală nr.1337 din XXXXXXXXX, conform căruia în mostrele de sînge prelevat de la cet. XXXXXXXXX Tudor s­a depistat alcool etilic în cantitate de 2,63o/ , echivalent a 2,63 mg/l. ( f.d. 30) 00 * Raportul de expertiză medico­legală nr.1338 din XXXXXXXXX, conform căruia în mostrele de sînge prelevat de la cet. XXXXXXXXX s­a depistat alcool etilic în cantitate de 3,93o/ , echivalent a 3,93 mg/l. ( f.d. 30) 00 * Proces­verbal privind corectarea erorilor materiale din 30.102014. (f.d. 58 ) Astfel, examinând probele cerecetate în cadrul şedinţei de judecată în raport cu declaraţiile inculpaților de recunoaştere a vinovăţiei, instanţa ajunge la concluzia că acţiunile inculpatului, corect, au fost încadrate în componenţa de infracţiune prevăzută de art. 155 CP RM cu indicii de calificare: amenințarea cu omor, dacă a existat pericolul realizării acestei amenințări. Partea vătămată XXXXXXXXX a înaintat o cerere prin care a solicitat instanţei de a înceta procesul penal în privinţa lui XXXXXXXXX în legătură cu faptul că s­au împăcat şi careva pretenţii faţă de el nu are şi nu doreşte să fie atras la răspundere penală. În consecinţă, elucidînd motivele de fapt şi de drept, instanţa reţine că, potrivit cererii părții vătămate XXXXXXXXX depuse în cadrul cercetărilor judecătoreşti, acesta solicită încetarea procedurii în privinţa

XXXXXXXXX, la data de 13.09.2014, aproximativ pe la orele 19:00, aflîndu­se în locuinţa cet. XXXXXXXXX Tudor, a.n. 01.01.1975, situată pe teritoriul Întovărăşirii pomicole «Raduga» din s.[[Colrăteni]] r­nul Rîşcani, fiind în stare de ebrietate alcoolică, în rezultatul unui conflict care a apărut între el şi cet. XXXXXXXXX Tudor, cu care au servit băuturi alcoolice, intenţionat, l­a ameninţat cu omor pe cet.XXXXXXXXX Tudor, după care, cu ajutorul unui topor pe care l­a găsit în locuinţa ultimului, a încercat să­l lovească pe cet.Vizir Ştefan Tudor în regiunea capului, existînd pericolul realizării acestei ameninţări, însă acţiunile de violenţă au fost contracarate de către victimă, care au fost percepute ca reale. În cadrul şedinţei de judecată [[inuclpatul]] XXXXXXXXX a recunoscut integral vinovăţia în faptele comise şi a declarat că dorește să se împace cu partea vătămată. [[Necătnîd]] la faptul recunoaşterii vinovăţiei inculpatului XXXXXXXXX, culpa acestuia se devedeşte şi de declarațiile: Părții vătămate XXXXXXXXX care a declarat că, la data de 13.09.2014, la orele 19:00 a servit băuturi alcoolice. Între el și Postoronco Stanislav s­a iscat un conflict. Ambii se aflau în stare de ebrietate. Postoronco Stanislav în timpul conflictului se afla cu toporul în mînă. Cînd dînsul a vrut să­i i­a toporul, în timpul dînsul s­a lovit de topor. Concubina a chemat salvarea care a comunicat la poliție. La moment careva pretenții materiale sau morale față de Postoronco Stanislav nu are. Solicită încetarea procesului penal în privința lui Postoronco Stanislav, și de materialele cauzei penale administrate în cadrul cercetării judecătorești şi anume: * Procesul­[[verabl]] de sesizare despre săvârşirea sau pregătirea pentru săvârşirea infracţiunii din 13.09.2014 – Vizir Ştefan Tudor. (f.d. 5 ) * Proces­[[verabl]] de cercetare la faţa locului din 13.09.2014 (f.d. 7­9 ) * Planşa fotografică (f.d. 10­15) * Ordonanţă de ridicare din 13.09.2014 (f.d. 16, 18) * Proces­verbal de ridicare din 13.09.2014 (f.d. 17, 19) * Raportul de expertiză medico­legală nr.1337 din XXXXXXXXX, conform căruia în mostrele de sînge prelevat de la cet. XXXXXXXXX Tudor s­a depistat alcool etilic în cantitate de 2,63o/ , echivalent a 2,63 mg/l. ( f.d. 30) 00 * Raportul de expertiză medico­legală nr.1338 din XXXXXXXXX, conform căruia în mostrele de sînge prelevat de la cet. XXXXXXXXX s­a depistat alcool etilic în cantitate de 3,93o/ , echivalent a 3,93 mg/l. ( f.d. 30) 00 * Proces­verbal privind corectarea erorilor materiale din 30.102014. (f.d. 58 ) Astfel, examinând probele cerecetate în cadrul şedinţei de judecată în raport cu declaraţiile inculpaților de recunoaştere a vinovăţiei, instanţa ajunge la concluzia că acţiunile inculpatului, corect, au fost încadrate în componenţa de infracţiune prevăzută de art. 155 CP RM cu indicii de calificare: amenințarea cu omor, dacă a existat pericolul realizării acestei amenințări. Partea vătămată XXXXXXXXX a înaintat o cerere prin care a solicitat instanţei de a înceta procesul penal în privinţa lui XXXXXXXXX în legătură cu faptul că s­au împăcat şi careva pretenţii faţă de el nu are şi nu doreşte să fie atras la răspundere penală. În consecinţă, elucidînd motivele de fapt şi de drept, instanţa reţine că, potrivit cererii părții vătămate XXXXXXXXX depuse în cadrul cercetărilor judecătoreşti, acesta solicită încetarea procedurii în privinţa


--------------------------------------------- Result 53 ---------------------------------------------
[[0 (98%)]] --> [[[SKIPPED]]]

xxxxNUMExxxx este învinuit pentru faptul că, urmărind intenţia de a comite o infracţiune privind circulaţia ilegală a substanţelor narcotice, fără scop de înstrăinare, a colectat şi a păstrat în domiciliului său situat în xxxxSATxxxx r­ul Ştefan Vodă, 41,36 grame de marihuană (Canabis) şi 3,28 g, de paie de mac pînă la data de 12.09.2014, cînd această masă vegetală, a fost depistată şi ridicată de către colaboratorii de poliţie. Conform raportului de constatare tehnico­ştiinţifică nr. 8349 din 01.10.2014, a fost constatat că masa vegetală depistată şi ridicată de la domiciliul cet. xxxxNUMExxxx în cantitate de 31,36 g, reprezintă marihuana care se atribuie la substanţe narcotice, iar masa vegetală în cantitate de 3,28 g reprezintă paie de mac, care conţin alcoloizi narcotici morfină tebeină, substanţe narcotice cantitatea cărora este în proporţii mari. Astfel, xxxxNUMExxxx este învinuit pentru faptul că, prin acţiunile sale intenţionate, a comis infracţiunea prevăzută de art. 217 al. (2) Cod penal conform indicilor: ­ păstrarea plantelor ce conţin substanţe narcotice, fără scop de înstrăinare, în proporţii mari. Fiind audiat în ședința de judecată, inculpatul vinovăția nu și­a recunoscut și a declarat că, locuiește în xxxxSATxxxx în casa surorii. Sora lui, care este proprietara casei, locuiește în xxxxORAȘxxxx. La data de 12.09.2014 a fost chemat la primăria xxxxSATxxxx, unde colaboratorii de poliție i­au explicat că, la domiciliul lui va fi efectuată percheziția. Au mers la domiciliul lui, unde au intrat în casă. Percheziția a fost efectuată de două grupuri de polițiști, el fiind într­o cameră, iar o parte din polițiști în altă cameră. Au fost găsite sacoșe cu masa vegetală, însă el nu știe cine a adus aceste sacoșe și de unde au apărut la el la domiciliu. A mai declarat că locuiește singur, însă uneori vine sora lui, cu soțul, se mai intîmplă că, la el vin și oaspeți. Nu este consumător de droguri și nu are prieteni care consumă droguri. Invocă procurorul că, vina inculpatului a fost demonstrată integral prin probele administrate în cadrul urmăririi penale și cele cercetate în cadrul ședinței de judecată. Martorul xxxxNUMExxxx, a declarat că activează în calitate de şef de post a IP Ştefan Vodă. Într­o zi de vară, aflîndu­se la serviciu în baza ordonanţei de efectuarea percheziţiei, autorizată de către Judecătoria Ştefan Vodă, împreună cu colaboratorii de poliţie xxxxNUMExxxx, xxxxNUMExxxx, xxxxNUMExxxx, xxxxNUMExxxx au efectuat o percheziţie la domiciliul unde locuieşte cet. xxxxNUMExxxx, din xxxxSATxxxx, r­nul Ştefan Vodă, pe motiv că din informaţii operative s­a aflat că ultimul păstra la domiciliu o armă de foc de model necunoscut. În urma efectuării percheziţiei la domiciliu menţionat mai sus, a fost depistat şi ridicat un pachet din polietilenă, în care se află o cantitate de plantă verde uscată asemănătoare cu cînepa şi în altă camera un pachet din polietilenă de culoare albastră străvezie în care se află o cantitate de seminţe asemănătoare cu seminţe de plante de mac. Nu ține minte cine a depistat aceste pachete. xxxxNUMExxxx, a declarat că, cunoaște de pachetele depistate, însă nu ține minte unde le­a pus. Instanța de judecată apreciază critic această declarație, ea fiind combatută prin declarațiile inculpatului și a martorilor

[Succeeded / Failed / Skipped / Total] 22 / 23 / 9 / 54:  45%|████▌     | 45/100 [08:50<10:48, 11.79s/it]

--------------------------------------------- Result 54 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

Prin sentinţa Judecătoriei xxxxORAS_SATxxxx din 20.05.201xxxxAPARTxxxx xxxxNUMExxxx a fost condamnată în baza art.217 alin.2, art.217 alin.xxxxAPARTxxxx lit.c), art.186 alin.2 lit.c, d CP, şi în baza art.84 alin.1, 85 CP i­a fost aplicată pedeapsa definitive de 6 ani închisoare cu ispăşirea pedepsei îi penitenciar pentru femei de tip închis. La data de 21.08.2014 condamnata a depus cerere îi instanţa de judecată, solicitînd executarea pedepsei în Penitenciarul nr.11 Bălţi. În motivarea cererii condamnata a invocat că, Penitenciarul nr.11 Bălţi corespunde tipului de penitenciar stabilit prin sentinţă şi aici va avea posibilitate de a participa activ la programele socio­culturale. Prin încheierea Judecătoriei Bălţi din 02.09.2014 cererea condamnatei xxxxNUMExxxx a fost respinsă ca fiind neîntemeiată. În motivarea soluţiei adoptate, instanţa a reţinut că reieşind din prevederile art.198 Cod de executare, condamnata nu este la prima abatere, execută pedeapsa în penitenciar de tip închis, din care considerente cererea urmează a fi respinsă. Nefiind de acord cu încheierea instanţei de fond, la data de 16.09.2014 şi respectiv 19.09.2014 condamnata xxxxNUMExxxx şi avocatul acesteia xxx au înaintat recurs, solicitînd admiterea acestuia, casarea încheierii din 02.09.2014 cu pronunţarea unei noi hotărîri prin care să fie admisă cererea condamnatei. În motivarea recursurilor au invocat că, cu încheierea instanţei din 02.09.2014 nu sunt de acord, o consideră neîntemeiată, deoarece Penitenciarul nr.11 din mun.Bălţi corespunde condiţiilor în care poate să­şi ispăşească pedeapsa xxxxNUMExxxx. Ea este de origine din or.xxxxORAS_SATxxxx. Fiul său minor la moment locuieşte în xxxxORAS_SATxxxx, care împreună cu rudele sale ar putea­o vizita mai uşor şi ajuta să treacă barierele psihologice de condamnat şi stările depresive în care se află. În ultima perioadă xxxxNUMExxxx nu are nici o încălcare de regim în penitenciar, se caracterizează pozitiv şi doreşte să participe la lucrările neremunerate şi activităţile cultural­educative organizate în penitenciar. Aceasta poate fi realizat doar prin schimbarea penitenciarului. În şedinţa instanţei de recurs avocatul xxx a susţinut recursul înaintat din motivele invocate, solicitînd admiterea acestuia. Condamnata în şedinţa instanţei de recurs nu s­a prezentat, depunînd la data de 18.0xxxxAPARTxxxx.2015 cerere prin care solicită să nu fie etapată la şedinţa de judecată, pe motiv de boală, fapt confirmat prin procesul­verbal de refuz anexat la materialele cauzei. Instanţa de recurs a considerat posibil de a examina cauza în lipsa condamnatei xxxxNUMExxxx. În instanţa de recurs procurorul a solicitat respingerea recursului înaintat ca nefondat. Reprezentantul Penitenciarului nr.11 Bălţi în şedinţa instanţei de recurs fiind citat legal, nu s­a prezentat, instanţa dispunînd examinarea cauzei în lipsa acestuia. Audiind participanţii la proces, verificînd argumentele invocate în recurs şi verificînd legalitatea şi temeinicia încheierii atacate, Colegiul penal ajunge la concluzia că recursul declarat urmează a fi respins ca fiind nefondat cu menţinerea încheierii instanţei de fond reieşind din următoarele considerente. Conform art.449 alin.(1) pct.1 lit.a) CPP, Judecînd recursul, instanţa adoptă una din următoarele decizii: respinge recursul, menţinînd hotărîrea atacată, dacă recursul este nefondat. Potrivit art.198 alin.(1) Cod de executare, pentru executarea lucrărilor de deservire gospodărească în izolatoarele de urmărire penală sînt lăsate, cu acordul lor scris şi la decizia şefului izolatorului de urmărire penală, persoanele condamnate cărora li s­a stabilit executarea pedepsei într­un penitenciar de tip semiînchis şi,

[Succeeded / Failed / Skipped / Total] 22 / 24 / 10 / 56:  46%|████▌     | 46/100 [09:03<10:37, 11.81s/it]

--------------------------------------------- Result 55 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

În una din zilele lunii septebrie 2014, aproximativ la ora 08.00, Gumeniuc Irina a pătruns în casa cet.Ceban Natalia, situată în s.Țambul XXXXXXXXX, de unde a sustras pe ascuns un inel din aur cu pietre mici cu greutatea de 3 grame cu prețul de 2000 lei, un lănțișor din aur cu greut grame cu prețul de 2000 lei, un lănțișor din aur cu greutatea de 1,5 grame cu prețul de 1000 lei, o cruce din aur cu greutatea de un gram cu prețul de o pereche de cercei cu greutatea de un gram și prețul de 800 lei, cauzînd în așa mod părții vătămate o daună materială în proporții considerabile î totală de 6600 lei. Tot ea, la 01septembrie 2014, în jurul orelor 0830­0900, continuînd activitatea infracțională, intenţionat, cu scopul sustragerii pe ascuns a bunurilor altei persoane, de profit, cu folosirea cheilor, a pătruns în casa cet. Onița Lidia Ivan, din satul Octeabrscoie, raionul XXXXXXXXX, de unde, pe ascuns, a sustras bijuterii din aur și inel bărbătesc din aur cu prețul de 3000 de lei, un lănţişor din aur cu preţul de 4000 lei, o brăţara de mînă din aur cu preţul de 3500 lei, două cruciuliţi din aur cu preţu lei, cîte 1750 de lei fiecare, patru inele din aur pentru femei cu preţul de 8000 lei, cîte 2000 de lei fiecare, o pereche de cercei din aur cu preţul de 3500 lei, un apar model Exilim, cu preţul de 3000 lei, un card bancar de la SA Banca de Economii pentru restabilirea cardului dat a achitat 1 euro, echivalentul la 20 de lei, cauzîndu­i un material considerabil în cuantum de 28520 lei. Tot ea, continuînd activitatea infracțională, la 11 octombrie 2014, aproximativ la ora 1900, urmărind scopul sustragerii bunurilor altei persoane, prin descuierea intrarea în casa de locuit a cet. Simac Anna Alexandr situat în satul Ţambula r. XXXXXXXXX, a pătruns în interior, de unde pe ascuns a sustras o verighetă din aur cu de 4,06g la preţul de 1500 lei, un ghiul (inel bărbătesc) din aur cu greutatea de 5,1g la preţul de 3000 lei, un lănţişor din aur cu greutatea de 6,52g la preţul de 4000 lei din aur cu greutatea de aproximativ 1g la preţul de 1000 lei, un lănţişor din aur cu greutatea de 1,67g la preţul de 2000 lei, un inel din aur cu greutatea de aproximativ 3 de 2000 lei şi un inel din aur cu greutatea de aproximativ 2g la preţul de 1500 lei, cauzîndu­i astfel părţii vătămate Simac Anna, o pagubă materială considerabilă în sum 15000 lei. Astfel, în perioada lunilor septembrie­octombrie 2014, Gumeniuc Irina a sustras bunuri ale altor persoane în sumă totală de 50120 lei, adică în mari. În ședința de judecată, inculpata Gumeniuc Irina, pînă la începerea cercetării judecătoreşti, a recunoscut în totalitate faptele indicate în rechizit recunoscut vina, nesolicitînd administrarea de probe noi, prin cerere scrisă personal, a solicitat examinarea cauzei penale în baza probelor admin urmărirea penală, pe care le recunoaște și asupra cărora nu are obiecții. Constatînd că probele administrate la urmărirea penală stabilesc fapta inculpatului,


--------------------------------------------- Result 56 ---------------------------------------------
[[1 (56%)]] --> [[[SKIPPED]]]

La data de 13.09.2013 a fost pornită urmărirea penală pe cauza dată, în baza elementelor infracţiunii prevăzute de art.361 alin.2 lit.b) Cod Penal, pe faptul că la data de 12.07.2011, aproximativ la orele 08:40, două persoane neidentificate de organul de urmărire penală, aflîndu­se în incinta Oficiului Cadastral Teritorial Bălţi filiala I.S.”CADASTRU”, amplasată pe str.M.Sadoveanu 1, avînd intenţia de falsificare a documentelor oficiale care­i acordă drepturi, cu ajutorul unui pix cu colorant albastru, a executat în rubrica „semnătura solicitantului” a cererii de înregistrare a ipotecii, asupra imobilului amplasat pe adresa: mun.Bălţi, str.xxx (pasaj) 7, o semnătura din numele cet.xxxxNUMExxxx , iar mai apoi, în aceeași zi a prezentat registratorului OCT Bălţi filiala Î.S.„CADASTRU” cererea nr.0300/11/11154 din 12.07.2011 de înregistrare a ipotecii asupra imobilului amplasat pe adresa: mun.Bălţi, xxx (pasaj) 7, unde ca proprietar figurează cet.xxxxNUMExxxx , adică au falsificat semnătura din numele solicitantului xxxxNUMExxxx. În urma investigării cazului dat, s­a constatat că, la data de 11.07.2011, între Banca Comercială „EuroCreditBank”SA şi „AGROMAGNAT"’ SRL, în persoana administratorului xxx, a fost încheiat contractul de credit nr.C.L.2­498 privind acordarea creditului bancar în sumă de 500000 lei, conform căruia „AGROMAGNAT” SRL asigură rambursarea în termenul stabilit a creditului, achitarea dobînzii şi altor plăţi aferente prin constituirea în favoarea băncii a garanţiilor şi anume a ipotecii bunului imobil, situat în mun.Bălţi, str.xxx166 ap.l19, ce reprezintă apartament compus din două odăi şi o suprafaţă locativă; a ipotecii terenului pentru construcţii, a casei de locuit individuală şi a construcţiei accesorii, toate fiind situate pe adresa mun.Bălţi, xxx pasaj 7. În aceeaşi zi, la 11.07.2011 a fost încheiat contractul de ipotecă între Barca Comercială „EuroCreditBank” S.A. şi cet.xxxxNUMExxxx, conform căruia ultimul instituie în favoarea. B.C. „EuroCreditBank” S.A. ipoteca asupra bunurilor sale şi anume a terenului pentru construcţii, a casei de locuit individuală şi a construcţiei accesorii, toate fiind situate pe adresa mun.Bălţi, xxx pasaj 7. Deci, pentru asigurarea obligaţiunilor faţă dc creditor de către xxx (administratorul „AGROMAGNAT” SRL) şi cet.xxxxNUMExxxx (tatăl lui xxx managerul „AGROMIAGNAT" SRL), a fost instituit creditul ipotecar asupra bunurilor imobile ce le aparțin şi anume: mun.xxxxORAS_SATxxxx, str.xxx 166 ap.19, respectiv mun.Bălţi, pasaj xxx 7, fiind încheiat contract de ipotecă cu fiecare dintre părţi. Conform pct.20 al contractului de ipotecă încheiat între BC ”EuroCreditBank”SA şi cet.xxxxNUMExxxx, prezentul contract urmează a fi înregistrat la Oficiul Cadastral Teritorial în a cărui rază teritorială este amplasat bunul imobil ipotecat, nefiind specificat de cine anume urmează a fi prezentat spre înregistrare la OCT. Deasemenea s­a constatat, că cet.xxx personal a prezentat contractul de ipotecă a bunului său imobil la OCT Bălţi, unde la 12.07.2011 a semnat în cererea de înregistrare a altor drepturi reale­ipotecare cu nr.0300/11/11153 asupra bunului imobil amplasat pe adresa: mun.Bălţi, str.xxx 166 ap.119. În aceeași zi, a fost semnată şi cererea de înregistrare a altor drepturi reale­ipotecare cu nr.0300/11/11154, asupra bunului imobil amplasat pe adresa: mun.Bălţi, pasaj xxx7. La momentul semnării ambelor cereri în incinta OCT Bălţi s­au aflat atît cet.xxx, cît şi companionul său de la ,.AGROMAGNAT” xxx. Conform raportului de expertiză nr.287 din 28.03.2014, semnătura executată în rubrica „data şi semnătura solicitantului” a cererii nr.0300/11/11154 din 12.07.2011

[Succeeded / Failed / Skipped / Total] 23 / 24 / 10 / 57:  47%|████▋     | 47/100 [09:16<10:27, 11.85s/it]

--------------------------------------------- Result 57 ---------------------------------------------
[[0 (100%)]] --> [[1 (51%)]]

xxxxNUMExxxx la 24.12.[[2014]], aproximativ la ora 23.30 minute, conducînd autoturismul de model “Ford [[Escort]]”, cu numărul de înmatriculare BLCE 271, în a s. Drăgăneşti r­l Sîngerei, a fost stopat de către colaborotorii de poliţie şi fiind suspectat în consum de băuturi alcoolice, a fost supus testării alcoolscopice cu ajutorul tehnic “Drager­[[Alcotest]] 6810”, fiind stabilită concentraţia vaporilor de alcool în aereul expirat de 0,52 mg/l, ceea ce conform art. 13412 alin. (3) din Codul penal, se stare de ebrietate alcoolică cu [[grad]] avansat. Fiind audiat în ședința de judecată, inculpatul xxxxNUMExxxx a recunoscut vina integral, [[declarînd]] că, la 24.12.2014, aproximativ pe la o conducea automobilul său de model „Ford [[Escort]]” cu numerele de înregistrare BL CE 271 din s. Serbeşti r. Floreşti de la nişte prieteni spre s. Drăgăneşti r­l Sîngerei. A apropierea s. Drăgăneşti a fost [[stopat]] de către o persoană care se afla lîngă un automobil, la început nu a observat că sunt colaboratorii de poliţie şi nu a stopat automobi era cu nişte prieteni. Apoi automobilul i­a urmărit şi deja ulterior a observat că sunt colaboratorii de poliţie fiindcă au aprins şi girofarul. El deja a stopat maşina. Col poliţiei rutiere i­au cerut să iasă din automobil şi să ridice mîinile sus, l­au [[urcat]] în automobillul poliţiei rutiere şi au [[mers]] la Inspectoratul de poliţie [[Sîngerei]]. Permis deţine, însă l­a pierdut. Colaboratorii i­au spus că este suspectat în conducerea mijlocului de transport în stare de ebrietate şi că trebuie să fie supus expertizei [[alcoosco]] la Inspectoratul de Poliţie Sîngerei a fost supus expertizei şi a [[suflat]] într­un aparat unde rezultatul a fost de 0,52 mg/l. Recunoaşte că a servit băuturi alcoolice înainte volanul automobilului. De cele întîmplate se căieşte sincer [[Pînă]] la începerea cercetării judecătoreşti, [[inculpatul]] a declarat, [[personal]] prin înscris [[autentic]], că recunoaşte săvîrşirea [[faptelor]] in rechizitoriu şi solicită ca judecata să se [[facă]] pe [[baza]] probelor administrate în faza de urmărire [[penală]]. Astfel, [[instanța]] de judecată prin în protocolară din 02 martie 2015, a [[acceptat]] ca judecata să se facă pe [[baza]] [[probelor]] administrate în [[faza]] de [[urmărire]] penală. Pe lîngă faptul că [[inculpatul]] xxxxNUMExxxx a [[recunoscut]] [[vina]], în [[ședința]] de judecată vinovăția acestuia este dovedită prin [[următoarele]] probe ­ raport privind circumstanţele comiterii infracţiunii (f.d. 3); ­ raport privind recepţionarea apelului telefonic (f.d. 5); ­ procesul­verbal privind constatarea faptei de conducere a mijlocului de transport în stare de ebrietate alcoolică (f.d. 6­7); ­ procesul­verbal de testare alcooloscopică (f.d. 9); ­ procesul­verbal al examinării medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate şi a naturii ei (f.d. 12­13); ­ declaraţiile martorului Bucliş Mihail Mihail, (f.d.18); ­ declaraţiile martorului Coşieru Oleg Alexandru, (f.d.19). Analizînd probele cercetate în ședința de judecată prin prisma prevederilor art.101 CPP, în virtutea cărora, fiecare probă urmează să fie apre punct de vedere al pertinenței, concludenței, utilității și veridicității ei, iar toate aspectele și în mod obiectiv, călăuzindu‐se de lege, se ajunge la con în ședința de judecată cu certitudine s‐a dovedit vinovăția inculpatului xxxxNUMExxxx în comiterea infracțiunii prevăzute la art.2641 alin.(1) Co adică conducerea mijlocului de transport de către o

xxxxNUMExxxx la 24.12.[[2104]], aproximativ la ora 23.30 minute, conducînd autoturismul de model “Ford [[Escrot]]”, cu numărul de înmatriculare BLCE 271, în a s. Drăgăneşti r­l Sîngerei, a fost stopat de către colaborotorii de poliţie şi fiind suspectat în consum de băuturi alcoolice, a fost supus testării alcoolscopice cu ajutorul tehnic “Drager­[[Alcotset]] 6810”, fiind stabilită concentraţia vaporilor de alcool în aereul expirat de 0,52 mg/l, ceea ce conform art. 13412 alin. (3) din Codul penal, se stare de ebrietate alcoolică cu [[gard]] avansat. Fiind audiat în ședința de judecată, inculpatul xxxxNUMExxxx a recunoscut vina integral, [[declaîrnd]] că, la 24.12.2014, aproximativ pe la o conducea automobilul său de model „Ford [[Escrot]]” cu numerele de înregistrare BL CE 271 din s. Serbeşti r. Floreşti de la nişte prieteni spre s. Drăgăneşti r­l Sîngerei. A apropierea s. Drăgăneşti a fost [[sotpat]] de către o persoană care se afla lîngă un automobil, la început nu a observat că sunt colaboratorii de poliţie şi nu a stopat automobi era cu nişte prieteni. Apoi automobilul i­a urmărit şi deja ulterior a observat că sunt colaboratorii de poliţie fiindcă au aprins şi girofarul. El deja a stopat maşina. Col poliţiei rutiere i­au cerut să iasă din automobil şi să ridice mîinile sus, l­au [[ucrat]] în automobillul poliţiei rutiere şi au [[mres]] la Inspectoratul de poliţie [[Sîngeeri]]. Permis deţine, însă l­a pierdut. Colaboratorii i­au spus că este suspectat în conducerea mijlocului de transport în stare de ebrietate şi că trebuie să fie supus expertizei [[alocosco]] la Inspectoratul de Poliţie Sîngerei a fost supus expertizei şi a [[sufalt]] într­un aparat unde rezultatul a fost de 0,52 mg/l. Recunoaşte că a servit băuturi alcoolice înainte volanul automobilului. De cele întîmplate se căieşte sincer [[Pnîă]] la începerea cercetării judecătoreşti, [[inculptaul]] a declarat, [[pesronal]] prin înscris [[auetntic]], că recunoaşte săvîrşirea [[fpatelor]] in rechizitoriu şi solicită ca judecata să se [[fcaă]] pe [[bzaa]] probelor administrate în faza de urmărire [[peanlă]]. Astfel, [[instațna]] de judecată prin în protocolară din 02 martie 2015, a [[acecptat]] ca judecata să se facă pe [[bzaa]] [[porbelor]] administrate în [[fzaa]] de [[umrărire]] penală. Pe lîngă faptul că [[incuplatul]] xxxxNUMExxxx a [[recunocsut]] [[vnia]], în [[șeidnța]] de judecată vinovăția acestuia este dovedită prin [[urămtoarele]] probe ­ raport privind circumstanţele comiterii infracţiunii (f.d. 3); ­ raport privind recepţionarea apelului telefonic (f.d. 5); ­ procesul­verbal privind constatarea faptei de conducere a mijlocului de transport în stare de ebrietate alcoolică (f.d. 6­7); ­ procesul­verbal de testare alcooloscopică (f.d. 9); ­ procesul­verbal al examinării medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate şi a naturii ei (f.d. 12­13); ­ declaraţiile martorului Bucliş Mihail Mihail, (f.d.18); ­ declaraţiile martorului Coşieru Oleg Alexandru, (f.d.19). Analizînd probele cercetate în ședința de judecată prin prisma prevederilor art.101 CPP, în virtutea cărora, fiecare probă urmează să fie apre punct de vedere al pertinenței, concludenței, utilității și veridicității ei, iar toate aspectele și în mod obiectiv, călăuzindu‐se de lege, se ajunge la con în ședința de judecată cu certitudine s‐a dovedit vinovăția inculpatului xxxxNUMExxxx în comiterea infracțiunii prevăzute la art.2641 alin.(1) Co adică conducerea mijlocului de transport de către o

[Succeeded / Failed / Skipped / Total] 23 / 25 / 10 / 58:  48%|████▊     | 48/100 [09:30<10:17, 11.88s/it]

--------------------------------------------- Result 58 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Inculpatul xxxxNUMExxxx Nichita, la data de 30.10.2013, pe la orele 16.00, în rîpa din preajma s. Lalova rl. Rezina, în timpul unui conflict spantan apărut pe fondalul relaţiilor ostile persistante i­a aplicat cet. Josan Victor, multiple lovituri cu pumnii în regiunea feţii, în rezultatul cărora lui Josan Igor i­au fost provocate, potrivit raportului de expertiză medico­ legală nr. 397 D din 27.11.2013, vătămări corporale MEDII sub formă de fractură a mandibulei în regiunea unghiului pe dreapt, comoţie cerebrală, ce duc la o dereglare a sănătăţii de lungă durată. Inculpatul xxxxNUMExxxx Nichita pînă la începerea cercetării judecătoreşti a declarat personal prin înscris autentic, că recunoaşte săvîrşirea faptelor indicate în rechizitoriu şi solicită ca judecata să se facă pe baza probelor administarte în faza de urmărîre penală pe care le cunoaşte şi asupra cărora nu are obiecţii. Procuror şi avocat sînt de acord cu cererea inculpatului xxxxNUMExxxx Nichita. Prin încheierea din 03.04.2014, instanţa a admis inscrisul autentic depus de către inculpatul xxxxNUMExxxx Nichita, reieşind din fapt că din probele administrate rezultă că faptele lu sînt stabilite şi sînt suficiente date cu privire la persoana sa pentru a permite stabilirea unei pedepse. Fiind audiat în calitate de martor, inculpatul xxxxNUMExxxx Nichita a declarat că este originar şi locuitor al s. Lalova r. Rezina, are o fiică pe nume Iancevscaia Aliona şi fiul xxxxNUMExxxxitalii, care la moment locuieşte în r. Ocniţa. În anul 2000 consăteanul xxxxCUSTOM1xxxx l­a bătut pe fiul Vitalii şi de atunci sunt în relaţii ostile. Pe data de 30.10.2013, a plecat pe imaşul din preajma satului ca să­şi aducă acasă caii; între timp pe rîpă se apropia de sat cireada cu bovine, ce era condusă de xxxxCUSTOM1xxxx şi Caraman Ion; ultimul mergea în fruntea cirezii. El l­a întrebat pe Caraman Ion de ce vitele sunt flămînde, la ce dînsul i­a răspuns să­l întrebe pe Josan Igor, care de fapt era cu rîndul. Între timp de dînsul s­a apropiat Josan Igor, care s­a interesat de ce­i nemulţumit, acesta după aprecierele lui era în stare de ebrietate, la ce i­a reproşat că vitele sunt flămînde. Au început a se contra verbal şi şi­a mînat vaca spre casă, încît locuieşte în apropiere de rîpă şi l­a strigat pe fiul xxxxNUMExxxxitali ca dînsul se preia vaca, iar el să aducă caii. Josan Igor mînînd vitele cu o vergea de lemn se apropia de el, rotind­o. xxxxNUMExxxx a intenţionat să­l apuce de vergea, dar acela a fugit la vale; el a mers după dînsul şi­n rîpă acela iar rotea vergeau spre CaramanV, lovindu­l peste mîina stîngă, însă xxxxNUMExxxx l­a apucat de vergea şi i­a luat­o din mîină, după ce l­a lovit de două ori cu pumnul în regiunea feţei, apoi peste corp; la fel l­a lovit pe acesta şi cu vergeaua peste corp. Între timp la faţa locului a apărut fiul xxxxNUMExxxxitali, care s­a implicat în conflict şi i­a despărţit; fiul nu l­a lovit pe Josan Igor niciodată şi nici nu l­a imobilizat pe acesta, pur simplu dînsul a intervenit între ei, dispersîndu­i. Bătaia s­a finisat şi xxxxNUMExxxxitali i­a luat vergeaua din mîini şi i­a dat­o lui Josan

[Succeeded / Failed / Skipped / Total] 23 / 26 / 10 / 59:  49%|████▉     | 49/100 [09:44<10:08, 11.92s/it]

--------------------------------------------- Result 59 ---------------------------------------------
[[1 (86%)]] --> [[[FAILED]]]

Prin sentința nominalizată xxxxNUMExxxx a fost recunoscută culpabilă și condamnataă pentru, că în luna decembrie 2008 prin înțelegere prealabilă și împreună cu Iftodi Olesea, încurajînd­o și convingînd­o pe xxxNUMExxxcă va obține venituri considerabile pe cont propriu ca rezultat al practicării prostituției în Turcia, trezindu­i interesul față de această îndeletnicire, îndemnînd­o și încurajînd­ o, au determinat­o să­și dea consimțămîntul de a practica acest gen de activitate. Respectivele acțiuni a inculpatei fiind încadrate de către instanța de fond la art. 220 alin. (1) Cod penal cu calificativele ”îndemnul și determinarea la prostituție, înlesnirea practicii prostituției, tragerea de foloase de pe urma practricării prostituției” (f.d. 246­247). Totodată, prin învinuirea formulatră în rechizitoriu, xxxxNUMExxxx a fost acuzată de faptul, că: ”indentificînd victima, dîndu­ și seama că prin acțiunile sale recrutează, transportă și adăpostește o persoană în scop de expluatare sexuală comercială și dorind aceasta, atentînd la lupta statelor pentru prevenirea și reprimarea acestor forme de parazitism social josnic (concretizate în Convenția internațională pentru suprimarea traficului de femei și copii, adoptată la Geneva la 20.09.1921, Convenția internațională privitoare la reprimarea traficului de dfemei majore din 11.10.1933, Convenția pentru repprimarea traficvului de ființe umane și expluatării prostituării altuia, adoptată de Adunarea Gennerală ONU la 22.12.1949 și Convenția privind lupta cu traficul de oameni cu expluatarea prostituției de către terșe persoane din 21.03.1980), în luna decembrie 2008, la o dată nestabilită de către organul de urmărire penală, intenționat din interes material, prin intermediul Olesei Iftodii, ce se afla în or. Șoldănești, str. C. Stamati, 16, la domiciliul xxxNUMExxx, urmărind scopul expluatării sexuale comerciale, prin înșelăciune manifestată prin promisiunea de angajare în calitate de prostituată în or. Istambul, Turcia, prin abuz de vulnerabilitate, manifestată prin situația financiară grea și apartenența la categoria familiilor social­vulnerabile, a recrutat­o pe cea din urmă cu consimțămîntul dat de ea. Ulterior, întru atingerea scopului infracțional, xxxxNUMExxxx a organizat plecarea xxxNUMExxx și a xxxxNUMExxx în Turcia, achitîndu­le plata pentru deplasare în sumă de 2000 dol. SUA, adăpostindu­le în locuința sa din or. Antalia, unde acestea au practicat prostituția în următoarele două luni.” Acuzarea a încădrat respectivele acțiuni a inculpatei xxxxNUMExxxx la art. 165 alin. (1) lit. b), c) Cod penal cu calificativele ”traficul de ființe umane, manifestat prin recrutarea, transportarea, adăpostirea persoanei cu consimțămîntul acesteea, în scop de expluatare sexuală comercială, săvîrșită prin înșelăciune sau abuz de vulnerabilitate” (f.d. 212­213). Învinuirea dată a fost susținută de către acuzatorul Ion Mînza și în instanța de fond, cu propunearea condamnării inculpatei xxxxNUMExxxx pe art. 165 alin. (1) lit. b), c) Cod penal, stabilindu­i pedeapsa închisorii pe un termen de cinci ani cu aplicarea dispozițiilor art. 90 Cod penal, dispunîndu­se executarea ei condiționată pe un termen de probă de patru ani (f.d. 251­255). Dispunînd reîncadrarea acțiunilor inculpatei xxxxNUMExxxx de la componența traficului de ființe umane la cea de proxenitism, instanța a concluzionat lipsa probelor ce ar demonstrează vinovăția formulată, considerînd că acțiunile ei urmează a fi încadrate la art. 220 alin. (1) Cod penal, așa precum a fost condamnată și Iftodii Olesea, printr­o sentință definitivă fiind constatat, că ea a participat în complicitate cu inculpata xxxxNUMExxxx (f.d.134­136). Legalitatea și

[Succeeded / Failed / Skipped / Total] 24 / 26 / 12 / 62:  50%|█████     | 50/100 [09:53<09:53, 11.87s/it]

--------------------------------------------- Result 60 ---------------------------------------------
[[0 (99%)]] --> [[1 (63%)]]

[[Inculpatul]] xxxxNUMExxxx activînd în calitate de inspector­şofer (grupa operativă) al Dispetceratului pază al Filialei [[Rezina]] Întreprinderii de Stat „Servicii Pază Republicii Moldova , în perioada de timp începînd cu luna decembrie 2010, susţinînd că are influenţă asupra unor funcţionari din cadrul Comisariatului raional de poliţie [[Rezin]] Procuratura raionului Rezina , în gestiunea şi conducerea cărora se afla cauza penală nr.[[20100297]] pornită în privinţa cet.xxxxCUSTOM2xxxx Mihai, Muntean Vasi [[xxxxCUSTOM1xxxx]] Diana şi xxxxCUSTOM1xxxx Alexei conform art.217/1 al.(4) lit.d) CP, în scopul de ai [[detrmina]] pe aceştea la îndeplinirtea unor acţiuni ce într obligaţiunile de serviciu legate de încetarea urmărirei penale pe cauza penală dată , prin extorcare a pretins bani în sumă de 800 dolari SUA de la cet.xxxxCUSTOM1x Alexei , care ulterior la 05.01.2011 aproximativ la orele 14.44 în or.[[Rezina]] pe str.Şciusev nr.5 în faţa Centrului Medicilor de famile din or.[[Rezina]] i­a primit pentru sine d ultimul, fiind reţinut în flagrant delict. Fapta dată prejudiciabilă a fost recunoscută de [[către]] [[inculpatul]] [[xxxxNUMExxxx]] în acordul de recunoaştere a vinovaţiei încheiat la 27 ianuarie 2011 între dînsu procurorul în serviciul Nord al Procuraturii AnticorupţiexxxxNUMExxxx Dulghier , însoţit de apărătorulxxxxNUMExxxx Rotari. [[Vina]] inculpatului xxxxNUMExxxx în comiterea infracţiunii se dovedeşte pe deplin prin depoziţiile lui recunoscătoare date în şedinţa de judecată din 02.03.2011 şi probele prezentate de către procuror şi recunoscute de către inculpatul , şi anume : ­ proces­verbal de primire a denunţului de la cet.xxxxCUSTOM1xxxx Alexei D. din 04.01.2011 ( p.d.5­6); ­ proces – verbal privind marcarea bancnotelor în sumă totală de 800 dolari SUA din 05.01.2011 ( p.d.16); ­raport de expertiză judiciară fizico­chimice a bancnotelor marcate nr.038 din 10.01.2011 (p.d.27­31); ­ proces­verbal de ridicare a dictofonului digital şi a minivideocamerei digitale de la xxxxCUSTOM1xxxx Alexei din 05.01.2011 ( p.d.36 ); ­ proces – verbal din 05.01.2011 de efectuare a interceptării şi înregistrării comunicărilor între xxxxCUSTOM1xxxx Alexei şi xxxxNUMExxxx şi stenograma intercept comunicărilor ( p.d.37­39); ­ proces­verbal de percheziţie corporală a lui xxxxNUMExxxx. din 05.01.2011 (p.d.50­51); ­ proces­verbal de examinare a obiectelor şi a documentelor ridicate în procesul urmărirei penale şi în procesul percheziţiei corporale a lui xxxxNUMExxxx. şi ordonanţa recunoaştere şa ataşare la dosar a mijloacelor materiale de probă ( p.d.53­56); ­ copiile materialelor din dosarul penal nr.20100297 pornit în privinţa cet.xxxxCUSTOM2xxxx Mihai, Muntean Vasile , xxxxCUSTOM1xxxx Diana şi xxxxCUSTOM1x Alexei conform art.217/1 al.(4) lit.d) CP ( p.d.62­159). Instanţa de judecată găseşte că probele prezentate dovedesc vina inculpatului xxxxNUMExxxx în comiterea infracţiunii ce i se impută şi că el a semnat acordul recunoaştere a vinovaţiei binevol, prin voinţa liberă,fără a fi impus de cineva. Acţiunile inculpatului sînt just încadrate în baza art.326 al.(1) CP – traficul de influenţă , adică primirea de bani, personal pentru sine săvîrşită intenţionat de cătr persoană care are influenţă sau care susţine că are influenţă asupra unui funcţionar, în scopul de a­l face să îndeplinească ori să nu îndeplinească acţiuni ce intră în obligaţiil de serviciu, indiferent dacă asemenea acţiuni au fost sau nu săvîrşite. La stabilirea măsurii de pedeapsă instanţa ia în consideraţie gradul şi nivelul pericolului social a infracţiunii săvîrşită , personalitatea inculpatului , circumstanţele agravează şi

[[Incuplatul]] xxxxNUMExxxx activînd în calitate de inspector­şofer (grupa operativă) al Dispetceratului pază al Filialei [[Reznia]] Întreprinderii de Stat „Servicii Pază Republicii Moldova , în perioada de timp începînd cu luna decembrie 2010, susţinînd că are influenţă asupra unor funcţionari din cadrul Comisariatului raional de poliţie [[Reizn]] Procuratura raionului Rezina , în gestiunea şi conducerea cărora se afla cauza penală nr.[[20100927]] pornită în privinţa cet.xxxxCUSTOM2xxxx Mihai, Muntean Vasi [[xxxCxUSTOM1xxxx]] Diana şi xxxxCUSTOM1xxxx Alexei conform art.217/1 al.(4) lit.d) CP, în scopul de ai [[dtermina]] pe aceştea la îndeplinirtea unor acţiuni ce într obligaţiunile de serviciu legate de încetarea urmărirei penale pe cauza penală dată , prin extorcare a pretins bani în sumă de 800 dolari SUA de la cet.xxxxCUSTOM1x Alexei , care ulterior la 05.01.2011 aproximativ la orele 14.44 în or.[[Reizna]] pe str.Şciusev nr.5 în faţa Centrului Medicilor de famile din or.[[Reznia]] i­a primit pentru sine d ultimul, fiind reţinut în flagrant delict. Fapta dată prejudiciabilă a fost recunoscută de [[ctăre]] [[inclupatul]] [[xxxNxUMExxxx]] în acordul de recunoaştere a vinovaţiei încheiat la 27 ianuarie 2011 între dînsu procurorul în serviciul Nord al Procuraturii AnticorupţiexxxxNUMExxxx Dulghier , însoţit de apărătorulxxxxNUMExxxx Rotari. [[Vnia]] inculpatului xxxxNUMExxxx în comiterea infracţiunii se dovedeşte pe deplin prin depoziţiile lui recunoscătoare date în şedinţa de judecată din 02.03.2011 şi probele prezentate de către procuror şi recunoscute de către inculpatul , şi anume : ­ proces­verbal de primire a denunţului de la cet.xxxxCUSTOM1xxxx Alexei D. din 04.01.2011 ( p.d.5­6); ­ proces – verbal privind marcarea bancnotelor în sumă totală de 800 dolari SUA din 05.01.2011 ( p.d.16); ­raport de expertiză judiciară fizico­chimice a bancnotelor marcate nr.038 din 10.01.2011 (p.d.27­31); ­ proces­verbal de ridicare a dictofonului digital şi a minivideocamerei digitale de la xxxxCUSTOM1xxxx Alexei din 05.01.2011 ( p.d.36 ); ­ proces – verbal din 05.01.2011 de efectuare a interceptării şi înregistrării comunicărilor între xxxxCUSTOM1xxxx Alexei şi xxxxNUMExxxx şi stenograma intercept comunicărilor ( p.d.37­39); ­ proces­verbal de percheziţie corporală a lui xxxxNUMExxxx. din 05.01.2011 (p.d.50­51); ­ proces­verbal de examinare a obiectelor şi a documentelor ridicate în procesul urmărirei penale şi în procesul percheziţiei corporale a lui xxxxNUMExxxx. şi ordonanţa recunoaştere şa ataşare la dosar a mijloacelor materiale de probă ( p.d.53­56); ­ copiile materialelor din dosarul penal nr.20100297 pornit în privinţa cet.xxxxCUSTOM2xxxx Mihai, Muntean Vasile , xxxxCUSTOM1xxxx Diana şi xxxxCUSTOM1x Alexei conform art.217/1 al.(4) lit.d) CP ( p.d.62­159). Instanţa de judecată găseşte că probele prezentate dovedesc vina inculpatului xxxxNUMExxxx în comiterea infracţiunii ce i se impută şi că el a semnat acordul recunoaştere a vinovaţiei binevol, prin voinţa liberă,fără a fi impus de cineva. Acţiunile inculpatului sînt just încadrate în baza art.326 al.(1) CP – traficul de influenţă , adică primirea de bani, personal pentru sine săvîrşită intenţionat de cătr persoană care are influenţă sau care susţine că are influenţă asupra unui funcţionar, în scopul de a­l face să îndeplinească ori să nu îndeplinească acţiuni ce intră în obligaţiil de serviciu, indiferent dacă asemenea acţiuni au fost sau nu săvîrşite. La stabilirea măsurii de pedeapsă instanţa ia în consideraţie gradul şi nivelul pericolului social a infracţiunii săvîrşită , personalitatea inculpatului , circumstanţele agravează şi


--------------------------------------------- Result 61 ---------------------------------------------
[[1 (87%)]] --> [[[SKIPPED]]]

xxxxNUMExxxx, activînd în perioada 01.09.2010 ­ 19.07.2012 în baza contractului individual de muncă nr.55 din 01.09.2010, în calitate de specialist în domeniul politicilor fiscale la primăria Solonceni raionul xxxxORAS_SATxxxx, fiiind persoană cu funcţie de răspundere materială, abilitată cu drepturi şi obligaţii în vederea exercitării funcţiilor autorităţii publice, din intenţii de profit, folosindu­se de situaţia de serviciu, încălcînd prevderile art. 136 lit.p) al Codului fiscal potrivit căruia funcţionarul fiscal are obligaţia de a nu folosi situaţia de serviciu în scopuri personale meschine, şi art.158 lit.b) al Codului fical cît priveşte transferarea la buget a sumelor încasate ca impozite, nu a transferat pe contul bancar al primăriei Solonceni ci a însuşit în scopuri personale suma de 14087, 20 lei, încasaţi în exercitarea atribuţiilor de serviciu, de la locuitorii satului xxxxORAS_SATxxxx în perioada anilor 2010­2012. Vina inculpatei E.Pascari în delapidarea averii străine se dovedeşte prin: ‐ acordul de recunoaştere a vinovăției, incheiat între inculpată şi acuzatorul de stat şi acceptat de către instanța de judecată; ‐ declarațiile inculpatei E.Pascari in şedința de judecată, prin care ea şi‐a recunoscut vina în însușirea banilor de primiți ca impozite de locuitorii satului xxxxORAS_SATxxxx; ‐ actul de control al Inspectoratului Fiscal de Stat pe raionul xxxxORAS_SATxxxx și materialele anexate la el(f.d.7‐68) potrivit cărora se constată faptul însușirii de către E.Pascari a mijloacelor bănești în sumă de 14087, 20 lei; ‐ dispoziția nr.49C din 01.09.2010 a primarului comunei Solonceni A.Chirtoacă(f.d.74),prin care se confirmă faptul angajării Elenei Pascari în funcția de preceptor fiscal în satul xxxxORAS_SATxxxx. ‐alte probe, anexate la dosar şi acceptate de către inculpată . În probelor menționate menționate, instanța de judecață consideră dovedită pe deplin vina inculpatei xxxxNUMExxxx în însușirea ilegală a mijloacelor bănești în sumă de 14087, 20 lei, iar acțiunile ei le încadrează în baza art.191alin.2 lit. d) Cod Penal, adică ca delapidare a averii străine, ‐ însușire ilegală a bunurilor altei persoane, încredințate în administrarea vinovatului, cu folosirea situației de serviciu. La stabilirea pedepsei, instanța de judecată ține cont de gravitatea infracțiunii săvîrşite, de persoana celui vinovat, de circumstanțele cauzei care atenuează ori agravează răspunderea, de influiența pedepsei asupra corecțării şi reeducării vinovatului. Inculpata E.Pascari a comis o infracțiune mai puțin gravă, la locul de trai se caracterizază pozitiv, are la întreținere un copil minor, anterior nu a fost tras la răspundere penală. Circumstanțe agravante n‐au fost stabilite. Circumstanțe atenuante pentru inculpată sînt: săvîrșirea unei infracțiuni ca urmare a unui concurs de împrejurări grele de ordin personal sau familial; recunoașterea vinii și contribuirea activă la descoperirea infracțiunii. În temeiul celor menționate, instanța de judecată ajunge la concluzia că, corectarea inculpatei este posibilă fără izolarea ei de societate prin stabilirea unei pedepse cu închisoare pe un termen minimal și suspendarea condiționată a executării acesteia pe termen de probă. Totodată, instanța consideră nesesară aplicarea față de inculpata E.Pascari și a pedepsei complementare, ‐ privarea de dreptul de a deține anumite funcții. In conformitate cu art.art. 80 Cod Penal, 506‐509 Cod de procedură penală instanța de judecată,


--------------------------------------------- Result 62 ---------------------------------------------
[[0 (96%)]] --> [[[SKIPPED]]]

La data de 03.08.2016, în adresa procuraturii raionului Ungheni a parvenit raportul procurorului în procuratura de nivelul Curții de Apel A. Formusatii, potrivitărui în cadrul examinării cauzei penale de învinuire a cet. xxx și xxx pe art. 145 alin. (2) lit. i), j), k) , art. 188 alin. (2 b), d), eși 217 alin. (3) lit. c) Cod penal ultimii au invocat că au fost constrînși psihic de colaboratorii de poliție din cadrul IP Ungheni ș tre procurorul în procuratura raionului Ungheni D. Foros care i­a impus să recunoască vina. Prin ordonanța procurorului în procuratura raionului Ungheni Ion Steclari din XXXXXXXXX s­a dispus a nu porni urmărirea penal cazul dat pe motivul lipsei elementelor constitutive ale infrțiunii, cu clasarea procesului penal. Nefiind de acord cu ordonanța procurorului în procuratura raionului Ungheni Ion Steclari din XXXXXXXXX, aceasta a fost contestat 1 tre xxx și xxx la data de 01.09.2016 în ordinea prevăzută de art. 299 Cod procedură penală procurorului ierarhic superior, solici reinvestigarea cazulu Prin ordonanța procurorului, adjunctului procurorului raionului Ungheni Oleg Potînga din 13.09.2016, s­a dispus respingerea contest înaintate de cet. xxși xxx în privința ordonanței procurorului din XXXXXXXXX. Nefiind de acord cu ordonanțele emise (XXXXXXXXX și 13.09.2016) acestea au fost contestate în ordinea revăzută de art. 313 procedă penală în instanța de judecată. Totodată, la data de 04.09.2016, xxx și xxx, au remis în adresa Procuraturii Generale a RM plîngere asupra acțiunilor ilegale ale procuror D. Foros, indicîndă acesta i­a constrâns pentru ca ei să recunoască vina, plîngerea fiind înregistrată sub nr.9 la data de 12.09.2016. La de 15.09.2016, plîngerea ă a fost expediată în adresa Procuraturii raionului Ungheni pentru soluționare, iar ulterior fiind examinat procedă cu plîngerile inițiale. Prin încheierea Judecătoriei Ungheni din 07.10.2016, a fost respinsă ca neîntemeiată plîngerea înaintată de xxx și xxx asupra acțiu organului de urărire penală, inclusiv și a acțiunilor procurorului D.Foros. În susținerea soluției adoptate instanța de fond a reținut, că xxx și xxxi au recunoscut vina ambii depunînd o cerere de examinare a ca 1 conform prevederilor art. 3 Cod procedură penală, într­o procedură specială pe baza probelor acumulate în faza urmăririi penale, cer respective fiind sținute în cadrul ședinței preliminare de către avocații inculpaților cît și de reprezentanții lor legali. La fel, s­a constatat, că pe parcursul examinării cauzei penale petiționarii nu au depus careva plîngeri asupra acțiunilor organului de urm pe ă pe faptul aplicării în privința lor a violenței fizice și psihice sau că au fost presați de către reprezentanții organului de urmărire penală. Nefiind de acord cu încheierea emisă de instanța de fond la data de17.10.2016, aceasta a fost contestată cu recurs de către inculpatul care a indicat,ă adresîndu­se cu plîngere în instanța de judecată privind intentarea procesului penal în privința procurorului în procura raionului Ungheni Dorin Foros aceasta a fost respiă, ceea ce consideră, că contravine legii, deoarece orice persoană în privința căreia au aplicate țiuni care prevăd careva pedeapsă au dreptul să se adreseze către organele competente, ceea ce a și făcut. Invocă, că instanța a considerat că procurorul a admis în privința lui anumite acțiuni ilegale,

[Succeeded / Failed / Skipped / Total] 24 / 27 / 12 / 63:  51%|█████     | 51/100 [10:08<09:44, 11.93s/it]

--------------------------------------------- Result 63 ---------------------------------------------
[[0 (95%)]] --> [[[FAILED]]]

XXXXXXXXX, în perioada lunilor ianuarie­februarie anul 2013, activînd în calitate de șef al oficiului poștal al satului Iorjnița, r­nul Soroca în baza contractului individual de muncă nr.148 din 03.12.2012 și fiind persoană publică, intenţionat cu folosirea situaţiei de serviciu, în interes material și anume în scopul de a delapida mijloacele financiare încredințate în gestiunea sa, a falsificat semnătura cet. Bejenari Iurie Iosif, în dispoziția de plată a pensiei pentru invaliditate din 11.02.2013, însușind astfel suma de 789,40 lei, prin ce a cauzat părții vătămate o pagubă materială considerabilă. Continuîndu­și acțiunile infracționale în circumstanțe similare, în perioada lunilor februarie­iunie 2014, deținînd aceeași funcție, a falsificat semnătura cet.Șestacov Vera Timofei, în dispoziția de plată a pensiei de invaliditate stabilite minorului Șestacov Gabriel, a.n.03.12.2005, invalid de gradul I și în lista de plată a beneficiarilor de compensație, pentru călătorie în transport pe primul semestru al anului 2014, acordată lui Șestacov Gabriel, însușind astfel suma de 1 061,38 lei, prin ce a cauzat părții vătămate o pagubă materială considerabilă Continuîndu­și acțiunile infracționale în circumstanțe similare, în perioada noiembrie­decembrie 2014, deținînd aceeași funcție, a falsificat semnătura cet. Meșcov Nina Vasile în lista de plată nr. 15, aprobată conform deciziei nr.40 din 20.11.2014 a Fondului Raional de Susținere Socială a Populației, privind acordarea ajutorului material, în legătură cu ziua internațională a invalizilor, însușind astfel suma de 350,00 lei, prin ce a cauzat părții vătămate o pagubă materială considerabilă. Tot ea, în perioada lunilor ianuarie­februarie anul 2013, activînd în calitate de șef al oficiului poștal al satului Iorjnița r­nul Soroca, în baza contractului individual de muncă nr.148 din 03.12.2012 și fiind persoană publică, intenţionat, din interes material și anume în scopul de a delapida mijloacele financiare încredințate în gestiunea sa, a falsificat semnătura cet. XXXXXXXXX, în dispoziția de plată a pensiei pentru invaliditate din 11.02.2013, care este document oficial, însușind astfel suma de 789,40 lei, prin ce a cauzat părții vătămate o pagubă materială considerabilă. Conform raportului de expertiză grafologică nr.544 din 16.03.2015 s­a stabilit că semnătura din dispoziția de plată prin oficiile poștale, la poziția „COMP.1”, a fost executată nu de Bejenari Iurii Iosif, dar de o altă persoană prin imitarea semnăturii autentice. Continuîndu­și acțiunile infracționale în circumstanțe similare, în perioada lunilor februarie­iunie 2014, deținînd aceiași funcție, a falsificat semnătura cet.XXXXXXXXX în dispoziția de plată a pensiei de invaliditate a minorului XXXXXXXXX a.n. 2005, invalid de gradul I și în lista de plată a beneficiarilor de compensație pentru călătorie în transport pe primul semestru al anului 2014 acordată lui XXXXXXXXX, care sunt documente oficiale, însușind astfel suma de 1061,38 lei, prin ce a cauzat părții vătămate o pagubă materială considerabilă. Conform raportului de expertiză grafologică nr.543 din 16.03.2015, s­a stabilit că semnăturile examinate din dispoziția de plată prin oficiile poștale, perioada 2/2014 la poziția „COMP.1” și „FEBRUARIE” precum și semnătura din Lista beneficiarilor de compensație pentru călătorie în transport pentru semestrul I al anului 2014 la poziția 13, au fost executate probabil nu de XXXXXXXXX, dar de altă persoană prin imitarea semnăturii originale. Continuîndu­și acțiunile infracționale în circumstanțe similare, în perioada noiembrie­decembrie 2014, deținînd aceeași funcție, a falsificat

[Succeeded / Failed / Skipped / Total] 25 / 27 / 12 / 64:  52%|█████▏    | 52/100 [10:17<09:29, 11.87s/it]

--------------------------------------------- Result 64 ---------------------------------------------
[[0 (67%)]] --> [[1 (81%)]]

Pentru a se pronunţa în sensul celor expuse mai sus, instanţa de fond a reţinut, că [[inculpatul]] [[xxxxNUMExxxx]], la data de 22.03.2013, aproximativ la ora 00.10, documentat cu permisul de conducere nr. xxNUMxx din 11 mai 1998, fiind în stare de ebrietate alcoolică cu grad avansat, dîndu­şi seama de caracterul prejudiciabil al acţiunilor sale, prevăzînd urmările lor prejudiciabile şi dorind în mod conştient survenirea lor, conducea automobilul de model Volkswagen Transpo cu n/î xxNUMxx şi deplasîndu­se pe str. Conev la intersecţia cu str. Al. cel Bun, mun. Bălţi, avînd o traectorie neuniformă de deplasare, a fost stopat de către inspectorii patrulare rutieră a Companiei de patrulare nr. l Bălţi a RP Nord al INP. În cadrul discuţiei xxxxNUMExxxx a fost suspectat de întrebuinţarea alcoolului, deoarece avea simptome vizibile de consumare de alcool, exprimate prin vorbă neclară, miros de alcool din cavitatea bucală, după ce el a fost escortat la Dispensarul narcologic al Spitalului clinic municipal Bălţi, unde conform procesului­verbal al examinării medicale de constatare a faptului stării de ebrietate nr. 1132 din 22 martie 2014, s­a stabilit că xxxxNUMExxxx se afla în stare de ebrietate alcoolică cu grad avansat. Totodată, de la xxxxNUMExxxx au fost recoltate probe biologice de sînge pentru examinare toxicologică. Conform raportului de expertiză medico­legală nr. 161 din 26 martie 2014, concentraţia de alcool etilic în sîngele lui xxxxNUMExxxx constituie 2,97 g/l, cantitate care, Conform art. 134 Cod penal RM, se atribuie la stare de ebrietate cu grad avansat. Instanţa a adoptat sentinţa sus indicată. În recursul declarat în termen de către inculpat se solicită casarea parţială a sentinței judecătoreşti, prin care i­a fost aplicată pedeapsa complementară de privare de dreptul de a conduce mijloace de transport pe un termen de 3 ani, cu aplicarea prevederilor art. 79 CP. În motivarea recursului invocă, că anterior nu a avut careva încălcări în domeniul circulaţiei rutiere. La moment este încadrat în cîmpul muncii în calitate de şofer la ÎI „xxNUMExx”, iar permisul este unica sa sursă de venit pentru a­şi întreţine familia. Are la întreţinere 2 copii minori şi soţia nu are loc de muncă, el fiind unicul întreţinător al familiei. Consideră, că existenţa la întreţinerea sa a celor doi copii minori poate fi considerată situaţie excepţională, în privinţa sa urmînd a fi aplicate prevederile art. 79 CP şi să nu­i fie aplicată pedeapsa complimentară sub formă de privarea de dreptul de a conduce mijloace de transport. Inculpatul şi avocatul ce l­a asistat în şedinţa instanţei de recurs au susţinut recursul declarat şi solicită admiterea lui integrală. Procurorul participant în instanţa de recurs consideră sentinţa legală şi întemeiată, solicitând respingerea recursului ca nefondat. Ascultând părţile, verificând materialele dosarului, instanţa de recurs, socoate, că recursul este nefondat şi se respinge din următoarele considerente: Colegiul penal reţine că, instanţa de fond, în baza probelor administrate legal de către organul de urmărire penală şi verificate în şedinţa de judecată cu respectarea prevederilor art. 100 alin. (4) Cod de procedură penală, le­a dat o apreciere justă potrivit art. 101 Cod de procedură penală din punct de vedere al pertinenţei, utilităţii, concludenţei, veridicităţii şi coroborării reciproce,

Pentru a se pronunţa în sensul celor expuse mai sus, instanţa de fond a reţinut, că [[inuclpatul]] [[xxxNxUMExxxx]], la data de 22.03.2013, aproximativ la ora 00.10, documentat cu permisul de conducere nr. xxNUMxx din 11 mai 1998, fiind în stare de ebrietate alcoolică cu grad avansat, dîndu­şi seama de caracterul prejudiciabil al acţiunilor sale, prevăzînd urmările lor prejudiciabile şi dorind în mod conştient survenirea lor, conducea automobilul de model Volkswagen Transpo cu n/î xxNUMxx şi deplasîndu­se pe str. Conev la intersecţia cu str. Al. cel Bun, mun. Bălţi, avînd o traectorie neuniformă de deplasare, a fost stopat de către inspectorii patrulare rutieră a Companiei de patrulare nr. l Bălţi a RP Nord al INP. În cadrul discuţiei xxxxNUMExxxx a fost suspectat de întrebuinţarea alcoolului, deoarece avea simptome vizibile de consumare de alcool, exprimate prin vorbă neclară, miros de alcool din cavitatea bucală, după ce el a fost escortat la Dispensarul narcologic al Spitalului clinic municipal Bălţi, unde conform procesului­verbal al examinării medicale de constatare a faptului stării de ebrietate nr. 1132 din 22 martie 2014, s­a stabilit că xxxxNUMExxxx se afla în stare de ebrietate alcoolică cu grad avansat. Totodată, de la xxxxNUMExxxx au fost recoltate probe biologice de sînge pentru examinare toxicologică. Conform raportului de expertiză medico­legală nr. 161 din 26 martie 2014, concentraţia de alcool etilic în sîngele lui xxxxNUMExxxx constituie 2,97 g/l, cantitate care, Conform art. 134 Cod penal RM, se atribuie la stare de ebrietate cu grad avansat. Instanţa a adoptat sentinţa sus indicată. În recursul declarat în termen de către inculpat se solicită casarea parţială a sentinței judecătoreşti, prin care i­a fost aplicată pedeapsa complementară de privare de dreptul de a conduce mijloace de transport pe un termen de 3 ani, cu aplicarea prevederilor art. 79 CP. În motivarea recursului invocă, că anterior nu a avut careva încălcări în domeniul circulaţiei rutiere. La moment este încadrat în cîmpul muncii în calitate de şofer la ÎI „xxNUMExx”, iar permisul este unica sa sursă de venit pentru a­şi întreţine familia. Are la întreţinere 2 copii minori şi soţia nu are loc de muncă, el fiind unicul întreţinător al familiei. Consideră, că existenţa la întreţinerea sa a celor doi copii minori poate fi considerată situaţie excepţională, în privinţa sa urmînd a fi aplicate prevederile art. 79 CP şi să nu­i fie aplicată pedeapsa complimentară sub formă de privarea de dreptul de a conduce mijloace de transport. Inculpatul şi avocatul ce l­a asistat în şedinţa instanţei de recurs au susţinut recursul declarat şi solicită admiterea lui integrală. Procurorul participant în instanţa de recurs consideră sentinţa legală şi întemeiată, solicitând respingerea recursului ca nefondat. Ascultând părţile, verificând materialele dosarului, instanţa de recurs, socoate, că recursul este nefondat şi se respinge din următoarele considerente: Colegiul penal reţine că, instanţa de fond, în baza probelor administrate legal de către organul de urmărire penală şi verificate în şedinţa de judecată cu respectarea prevederilor art. 100 alin. (4) Cod de procedură penală, le­a dat o apreciere justă potrivit art. 101 Cod de procedură penală din punct de vedere al pertinenţei, utilităţii, concludenţei, veridicităţii şi coroborării reciproce,

[Succeeded / Failed / Skipped / Total] 25 / 28 / 12 / 65:  53%|█████▎    | 53/100 [10:30<09:19, 11.90s/it]

--------------------------------------------- Result 65 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Prin sentința nominalizată inculpatul xxxxNUMExxxx a fost condamnat pentru, că pe parcursul unei perioade nedeterminate a înce lunii decembrie 2012, prin înțelegere prealabilă cu minorii Savciuc Mihail, care executa pedeapsa închisorii și Chilari Radu, care se a arest preventiv, aflându­se în celula nr.13 a Penitenciarului nr.11 din mun. xxxxORAS_SATxxxx, au făcut o gaură în tavanul celulei cu evadării din această instituție penitenciară, însă din cauze independente de voința făptuitorilor, acțiunile lor nu și­au produs efectul, într data de 11.12.2012, aproximativ la orele 22:30 au fost depistați de colaboratorii serviciului regim și supraveghere a Penitenciarulu xxxxORAS_SATxxxx, respectivele acțiuni fiindu­i încadrate la art. 27, 317 al. (2) lit. b) Cod penal cu calificativele „tentativa de evad locurile de deținere, săvârșită de persoana ce execută pedeapsa cu închisoare, precum și de către două sau mai multe persoane, care di independente de voința făptuitorilor, nu și­a produs efectul”. Legalitatea și temeinicia sentinței de condamnare a fost atacată cu apel în termenul și ordinea prevăzută de art. art. 401­402 C penală, de către procurorul Tocaiuc Ghenadie ce a reprezentat învinuirea în instanță de fond, care necontestând legalitatea încadrării jur acțiunilor infracționale, solicită casarea acesteia în latura stabilirii pedepsei penale, cu pronunțarea unei soluții noi privind înăsprirea inculpatul xxxxNUMExxxx a pedepsei penale, fiindu­i stabilită cea cu închisoare pe termen de 9 (nouă) ani. În motivarea cerințelor for invocând intenția cu care a fost comisă tentativa de evadare din instituția penitenciară, unde condamnatul își execută pedeapsa închisorii comiterea cu intenție a unei infracțiuni excepțional de grave, ceea ce denotă lipsa unei căințe sincere față de cele comise și ne dorința de a calea corectării. La fel se invocă și agresivitatea de care a dat dovadă inculpatul la ședințele de judecată, refuzând să depună decla marginea învinuirii lui formulate în rechizitoriu, ceea ce în opinia recurentului ar servi temei pentru înăsprirea pedepsei penale. De r aceasta se invocă eroarea de drept material admisă de către instanța de judecată la adoptarea și pronunțarea sentinței, prin care inculpat xxxxNUMExxxxu i s­a stabilit pedeapsa definitivă prin cumul de sentințe (art. 85 alin. (1) Cod penal, deși urma a fi stabilită pentru con infracțiuni, cu aplicarea prevederilor art. 84 alin. (4) Cod penal, infracțiunea de evadare fiind comisă de el, până la pronunțarea deci condamnare a CA xxxxORAS_SATxxxx pe precedenta cauză de omor. Totodată, apelantul solicită și înăsprirea categoriei penitenciar infracțiunea de omor pentru care inculpatul deja își execută pedeapsa penală, face parte din categoria infracțiunilor excepțional de grave alin. 6) Cod penal), ceea ce determină necesitatea stabilirii lui pentru executare penitenciarul de tip închis. La apelul de bază declarat de partea acuzării, s­a alăturat cu apel suplimentar procurorul Pasat Liliana ce reprezintă învinu instanța de apel, completându­l cu concretizarea pedepsei penale solicitate pentru inculpat pe art. art. 27.317 alin. (2) lit. b) Cod penal, de un an închisoare, cu executare în penitenciar de tip închis și cu aplicarea prevederilor art. 84 alin. (4) Cod penal fiindu­i stabilită pe definitivă de 9 (nouă) ani închisoare în penitenciar de tip închis, termenul executării ei fiind calculat începând cu data de 30.01.20 momentul reținerii inculpatului pe

[Succeeded / Failed / Skipped / Total] 26 / 28 / 12 / 66:  54%|█████▍    | 54/100 [10:39<09:04, 11.84s/it]

--------------------------------------------- Result 66 ---------------------------------------------
[[1 (97%)]] --> [[0 (58%)]]

[[Inculpatul]] xxxxx, la 22.08.2015, aflîndu­se în incinta IMSP SR Soroca ”A.Prisacaru”, situat pe adresa str.Testimițeanu nr.68, or.Soroca, urmărind scop de însușire și avînd acces liber a întrat în biroul medicului din cadrul Secției de Internare și profitînd de faptul că nu este observat de nimeni, din sertarul unei mese a sustras pe ascuns telefonul mobil de modelul ”Samsung GT S5610”, cu cartela SIM nr.[[068008614]], care aparține cet.xxxxx, cauzînd astfel părții vătămate o [[pagubă]] considerabilă în sumă de 2000 lei. În şedinţa de judecată inculpatul xxxxxi vina şi­a recunoscut­o pe deplin, s­a căit sincer în cele săvîrşite şi a povestit detaliat despre circumstanţele săvîrşirii crimei, menţionînd că, la data de 22.08.2015 se afla la spitalul rauonal Soroca. A întrat în secția de primire și văzînd că nu este nimeni a vîzut pe masă un telefon mobil pe care la luat și a plecat acasă. Cu partea vătămată s­a împăcat, paguba a restituit­o pe deplin. Este deacord să fie procesul încetat în legătură cu împăcarea părţilor. [[Partea]] [[vătămată]] xxxxx în şedinţa de judecată a declarat că, la data de 22.08.2015 se afla la serviciu la spitalul raional Soroca în secția de pimire în birul medicului. A ieșit pe vre­o cîtevai minute din birou, dar înainte de aceasta a vorbit la telefon, pe care l­a lăsdat în sertarul mesei. Cînd s­a întors în birou, undeva peste o oră a depistat că telefonul lipsește pe care îl evaluiază de 2000 lei. Ultima s­a adresat la polițier și peste un timp a aflat că telefonul a fost sustras de către xxxxx Ultima a solicitat [[încetarea]] [[procesului]] pe motivul împăcării cu inculpatul Despre vina lui xxxxx mai probează: ­ Procesul verbal de cercetare la fața locului din 22.08.2015, în cadrul [[căreia]] a fost cercetat biroul medicului din cadrul Secției de internare, situat pe str. Testimițeanu nr.68, locul unde a fost comisă sustragerea ­ Procesul verbal de cercetare la fața locului din 25.08.2015, prin care a fost cercetată cutia de la telefonul mobil de model ”Samsung GT S5610”, care se păstrează în biroul [[medicului]] din cadrul Secției de internare, situat pe str. [[Testemițeanu]] nr.68, or.Soroca. ­ Procesul verbal de cercetare la fața locului din 01.09.2015, prin care a fost cercetat cutia telefonul mobil de model ”Samsung GT S5610” ­ Ordonanța de recunoaștere a corpului delict din XXXXXXXXX, prin care a fost recunoscut drept corp delict telefonul mobil de model ”Samsung GT S5610”. ­ Alte materiale ale dosarului penal. Acuzatorul de stat a pledat a pledat pentru încetarea procesului penal în cauză în legătură cu împăcarea părţilor. Apărătorul a fost de acord să fie încetat procesul în legătură cu împăcarea părților. Examinînd materialele cauzei, ascultînd argumentele şi considerentele participanţilor la proces, instanţa de judecată ajunge la concluzia despre necesitatea încetării procesului penal în privinţa inculpatului xxxxxx i pe motivul împăcării părţilor. Acţiunile inculpatului xxxxx au fost calificate corect de către organul de urmărire penală în baza art. 186 alin. (2) lit. d) Cod penal cu indicii de calificare: furtul, adică sustragerea pe ascuns a bunurilor altei persoane, cu cauzarea de daune în proporţii considerabile. Concluzia instanţei de judecată se bazează

[[Incuplatul]] xxxxx, la 22.08.2015, aflîndu­se în incinta IMSP SR Soroca ”A.Prisacaru”, situat pe adresa str.Testimițeanu nr.68, or.Soroca, urmărind scop de însușire și avînd acces liber a întrat în biroul medicului din cadrul Secției de Internare și profitînd de faptul că nu este observat de nimeni, din sertarul unei mese a sustras pe ascuns telefonul mobil de modelul ”Samsung GT S5610”, cu cartela SIM nr.[[068080614]], care aparține cet.xxxxx, cauzînd astfel părții vătămate o [[pgaubă]] considerabilă în sumă de 2000 lei. În şedinţa de judecată inculpatul xxxxxi vina şi­a recunoscut­o pe deplin, s­a căit sincer în cele săvîrşite şi a povestit detaliat despre circumstanţele săvîrşirii crimei, menţionînd că, la data de 22.08.2015 se afla la spitalul rauonal Soroca. A întrat în secția de primire și văzînd că nu este nimeni a vîzut pe masă un telefon mobil pe care la luat și a plecat acasă. Cu partea vătămată s­a împăcat, paguba a restituit­o pe deplin. Este deacord să fie procesul încetat în legătură cu împăcarea părţilor. [[Patrea]] [[vătmăată]] xxxxx în şedinţa de judecată a declarat că, la data de 22.08.2015 se afla la serviciu la spitalul raional Soroca în secția de pimire în birul medicului. A ieșit pe vre­o cîtevai minute din birou, dar înainte de aceasta a vorbit la telefon, pe care l­a lăsdat în sertarul mesei. Cînd s­a întors în birou, undeva peste o oră a depistat că telefonul lipsește pe care îl evaluiază de 2000 lei. Ultima s­a adresat la polițier și peste un timp a aflat că telefonul a fost sustras de către xxxxx Ultima a solicitat [[înceatrea]] [[proecsului]] pe motivul împăcării cu inculpatul Despre vina lui xxxxx mai probează: ­ Procesul verbal de cercetare la fața locului din 22.08.2015, în cadrul [[crăeia]] a fost cercetat biroul medicului din cadrul Secției de internare, situat pe str. Testimițeanu nr.68, locul unde a fost comisă sustragerea ­ Procesul verbal de cercetare la fața locului din 25.08.2015, prin care a fost cercetată cutia de la telefonul mobil de model ”Samsung GT S5610”, care se păstrează în biroul [[mediuclui]] din cadrul Secției de internare, situat pe str. [[Tetsemițeanu]] nr.68, or.Soroca. ­ Procesul verbal de cercetare la fața locului din 01.09.2015, prin care a fost cercetat cutia telefonul mobil de model ”Samsung GT S5610” ­ Ordonanța de recunoaștere a corpului delict din XXXXXXXXX, prin care a fost recunoscut drept corp delict telefonul mobil de model ”Samsung GT S5610”. ­ Alte materiale ale dosarului penal. Acuzatorul de stat a pledat a pledat pentru încetarea procesului penal în cauză în legătură cu împăcarea părţilor. Apărătorul a fost de acord să fie încetat procesul în legătură cu împăcarea părților. Examinînd materialele cauzei, ascultînd argumentele şi considerentele participanţilor la proces, instanţa de judecată ajunge la concluzia despre necesitatea încetării procesului penal în privinţa inculpatului xxxxxx i pe motivul împăcării părţilor. Acţiunile inculpatului xxxxx au fost calificate corect de către organul de urmărire penală în baza art. 186 alin. (2) lit. d) Cod penal cu indicii de calificare: furtul, adică sustragerea pe ascuns a bunurilor altei persoane, cu cauzarea de daune în proporţii considerabile. Concluzia instanţei de judecată se bazează

[Succeeded / Failed / Skipped / Total] 26 / 29 / 12 / 67:  55%|█████▌    | 55/100 [10:53<08:54, 11.88s/it]

--------------------------------------------- Result 67 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

Șișcov Anatoli *****, la 21.10.2014 având scopul sustragerii pe ascuns a bunurilor altei persoane, aflându-se în rutiera nr. 121 care se deplasa pe str. Ion Creangă mun. Chişinău spre sect. Rîşcani, str. Visterniceni, mun. Chişinău, folosindu-se de neatenţia pasagerului Colesnic Liuba ***** pe ascuns i-a sustras din geanta personală, portmoneul în care se afla buletinul de identitate, legitimaţi de serviciu, legitimaţia de pensioner, certificatul VTĂG, 3 carduri bancare şi bani în sumă de 750 lei, în rezultat cauzând părţii vătămate Colesnic Liuba un prejudiciu material în sumă de 750 lei. Tot el, la 30.01.2015, aproximativ la orele 08:45, deplasîndu-se cu microbuzul de pe ruta municipală nr. 115 de la str. Alba Iulia pînă la staţia de intersecţia str. Bucureşti cu str. Maria Cibotari, mun. Chişinău, avînd scopul sustragerii pe ascuns a bunurilor altei persoane din genţi, din motive de cupiditate, nefiind observat de nimeni, profitînd de neatenţia proprietarului aglomeraţia din rutieră, a sustras din geanta cet.Cîrnaţ Cristina un portmoneu culoare galbenă, confecţionat din piele la preţul de 200 lei, în care se aflau bani în sumă de 80 lei, 40 euro, care conform cursului oficial al Băncii Naţionale a Moldovei pentru acea zi constituiau suma de 819,72 lei, un card bancar al BC „EuroCreditBank” şi un card bancar al BC „Citadele”, după care cu bunurile sustrase a părăsit locul comiterii infracţiunii, cauzînd părţii vătămate Cîrnaţ Cristina daune în sumă totală de 1099,72 lei. Tot el, la 30.01.2015, în perioada de timp cuprinsă între orele 08:30-09:10, în timpul deplasării cu microbusul rutei nr.123, pe traseul cuprins între str.Igor Vieru pînă la str.Calea Ieşilor nr.8, din mun. Chişinău, urmărind scopul sustragerii bunurilor altei persoane şi acţionînd cu intenţie directă, în vederea realizării intenţiei sale criminale, dîndu-şi seama de caracterul prejudiciabil al acţiunilor sale, prevăzînd urmările lor şi admiţînd în mod conştient survenirea acestor urmări, a sustras din geanta cet. Botnari Ludmila, un portmoneu din piele, la preţul de 500 lei, în care se aflau buletinul de identitate, permisul de conducere şi poliţa de asigurare medicală, toate pe numele ultimei, precum şi bani în sumă de 5 lei MD, 30 Euro, care conform cursului oficial de schimb al BNM constituie echivalentul a 605 lei 10 bani şi 2 dolari SUA, ceea ce conform cursului oficial de schimb al BNM constituie echivalentul a 35 lei 70 bani, după care, cu bunurile sustrase a părăsit locul comiterii infracţiunii, cauzîndu-i astfel părţii vătămate o daună materială în sumă totală de 1145 lei şi 80 bani MD. Tot el, având scopul sustragerii pe ascuns a bunurilor altei persoane, la 31.05.2016 în jurul orelor 11:30, în timp ce se deplasa cu microbusul nr.127 pe str. Alecu Russo în direcţia str. Vasile Lupu, mun. Chişinău, pentru realizarea scopului său infracţional, acţionînd cu intenţie directă, conform unui plan bine chibzuit, dându-şi seama de carcaterul prejudiciabil al acţiunilor sale, prevăzând urmările lor şi admiţând în mod conştient survenirea acestora, aflându-se în apropierea nemijlocită de cet. Chirică Livia, care la fel se deplasa în microbusul menţionat, asigurându-se de faptul că aceasta nu-l observă şi nu-i urmăreşte acţiunile, i-a sustras din geantă care se afla

[Succeeded / Failed / Skipped / Total] 27 / 29 / 12 / 68:  56%|█████▌    | 56/100 [11:02<08:40, 11.83s/it]

--------------------------------------------- Result 68 ---------------------------------------------
[[1 (91%)]] --> [[0 (51%)]]

Pentru a se pronunţa în [[sensul]] celor expuse instanţa de fond a reţinut că la [[data]] de 15.10.2012 soții U.M.M. și U.L.N. au încheiat contract de vînzare­cumpărare cu ORMI din Republica Moldova, obiectul căruia constituie bunul imobil ce constă din: terenul cu modul de folosință – pentru construcții cu suprafața de 1,3353 ha, numărul cadastral 4101224781, cu construcție comercială pentru prestarea serviciilor cu suprafața totală de 825,50 m2, cu numărul cadastral 4101224781.01 și cu construcție nefinalizată cu suprafața totală de 1868,20 m2, cu numărul cadastral 4101224781.02, situate în orașul ­­­, strada ­­­ încasînd prețul vînzării bunurior indicate de [[2045776]],00 lei. Astfel suma totală nedeclarată de către U.M. și de către soția lui U.L. a impozitului pe venit din venitul obținut în rezultatul încheierii contractului de vînzare­cumpărare indicat constituie 144286,20 lei. În conformitate cu art.83 din Codul Fiscal al RM U.M.M. și U.L.N. au fost obligați să prezinte pînă la data de 31.03.2013 declarație cu privire la impozitul pe venit, declarînd și achitînd impozitul pe venit pentru anul 2012 în sumă de 72143,10 lei fiecare. Însă, U.M.M. și U.L.N. s­au eschivat de la prezentarea declarației cu privire la impoziul pe venit și de achitare a impozitului pe venit, prin ce statului i­a fost adus prejudiciul în sumă totală de 144286,20 lei sau de [[72143]],10 lei de la U.M.M. și U.L.N. Sentinţa instanţei a fost atacată cu [[apel]] în termen de către inculpații U.M.M. și U.L.N., care în motivare invocă că pedeapsa aplicată prin sentința instanței de fond este prea aspră, nu au cunoscut despre faptul că în urma încheierii contractului de înstrăinare a imobilelor era necesar de a face declarații pe venit, [[consideră]] că la aplicarea pedepsei instanța nu a ținut cont de faptul că prima dată au fost atrași la răspundere penală, au comis infracțiune ușoară, nu sunt angajați în cîmpul muncii, sunt de o vîrstă înaintată și nu au posibilitate de a achita așa amendă mare, solicitînd admiterea apelului, [[casarea]] sentinței în partea aplicării pedepsei penale, cu numirea unei pedepse sub formă de ore muncă neremunerată în folosul comunității, cîte 240 ore pentru fiecare. În şedinţa instanţei de apel inculpatul U.M. a declarat că susţine apelul declarat şi solicită să fie admis, cu numirea unei pedepse sub formă de ore muncă neremunerată în folosul comunității, amenda stabilită este mare şi nu poate să o achite. În şedinţa instanţei de apel inculpata U.L. a declarat că susţine apelul declarat şi solicită să fie admis, cu numirea unei pedepse sub formă de ore muncă neremunerată în folosul comunității. Avocatul inculpaților U.M. și U.L., M.V. în ședința instanţei de apel a susţinut apelul declarat de inculpați, solicitînd să fie numită pedeapsă sub formă de ore de muncă neremunerată în folosul comunității. Procurorul participant s­a pronunţat pentru respingerea apelului inculpaților ca nefondat, consideră sentinţa atacată în privinţa condamnării şi stabilirii pedepsei în privinţa inculpaţilor legală. Audiind participanţii la proces, verificînd argumentele invocate în apel prin prizma probelor administrate, verificînd legalitatea şi temeinicia hotărîrii atacate, Colegiul penal ajunge la concluzia că apelul declarat de inculpați urmează a fi admis, cu casarea parţială a sentinţei atacate, cu

Pentru a se pronunţa în [[snesul]] celor expuse instanţa de fond a reţinut că la [[dtaa]] de 15.10.2012 soții U.M.M. și U.L.N. au încheiat contract de vînzare­cumpărare cu ORMI din Republica Moldova, obiectul căruia constituie bunul imobil ce constă din: terenul cu modul de folosință – pentru construcții cu suprafața de 1,3353 ha, numărul cadastral 4101224781, cu construcție comercială pentru prestarea serviciilor cu suprafața totală de 825,50 m2, cu numărul cadastral 4101224781.01 și cu construcție nefinalizată cu suprafața totală de 1868,20 m2, cu numărul cadastral 4101224781.02, situate în orașul ­­­, strada ­­­ încasînd prețul vînzării bunurior indicate de [[2054776]],00 lei. Astfel suma totală nedeclarată de către U.M. și de către soția lui U.L. a impozitului pe venit din venitul obținut în rezultatul încheierii contractului de vînzare­cumpărare indicat constituie 144286,20 lei. În conformitate cu art.83 din Codul Fiscal al RM U.M.M. și U.L.N. au fost obligați să prezinte pînă la data de 31.03.2013 declarație cu privire la impozitul pe venit, declarînd și achitînd impozitul pe venit pentru anul 2012 în sumă de 72143,10 lei fiecare. Însă, U.M.M. și U.L.N. s­au eschivat de la prezentarea declarației cu privire la impoziul pe venit și de achitare a impozitului pe venit, prin ce statului i­a fost adus prejudiciul în sumă totală de 144286,20 lei sau de [[71243]],10 lei de la U.M.M. și U.L.N. Sentinţa instanţei a fost atacată cu [[aepl]] în termen de către inculpații U.M.M. și U.L.N., care în motivare invocă că pedeapsa aplicată prin sentința instanței de fond este prea aspră, nu au cunoscut despre faptul că în urma încheierii contractului de înstrăinare a imobilelor era necesar de a face declarații pe venit, [[conisderă]] că la aplicarea pedepsei instanța nu a ținut cont de faptul că prima dată au fost atrași la răspundere penală, au comis infracțiune ușoară, nu sunt angajați în cîmpul muncii, sunt de o vîrstă înaintată și nu au posibilitate de a achita așa amendă mare, solicitînd admiterea apelului, [[casaera]] sentinței în partea aplicării pedepsei penale, cu numirea unei pedepse sub formă de ore muncă neremunerată în folosul comunității, cîte 240 ore pentru fiecare. În şedinţa instanţei de apel inculpatul U.M. a declarat că susţine apelul declarat şi solicită să fie admis, cu numirea unei pedepse sub formă de ore muncă neremunerată în folosul comunității, amenda stabilită este mare şi nu poate să o achite. În şedinţa instanţei de apel inculpata U.L. a declarat că susţine apelul declarat şi solicită să fie admis, cu numirea unei pedepse sub formă de ore muncă neremunerată în folosul comunității. Avocatul inculpaților U.M. și U.L., M.V. în ședința instanţei de apel a susţinut apelul declarat de inculpați, solicitînd să fie numită pedeapsă sub formă de ore de muncă neremunerată în folosul comunității. Procurorul participant s­a pronunţat pentru respingerea apelului inculpaților ca nefondat, consideră sentinţa atacată în privinţa condamnării şi stabilirii pedepsei în privinţa inculpaţilor legală. Audiind participanţii la proces, verificînd argumentele invocate în apel prin prizma probelor administrate, verificînd legalitatea şi temeinicia hotărîrii atacate, Colegiul penal ajunge la concluzia că apelul declarat de inculpați urmează a fi admis, cu casarea parţială a sentinţei atacate, cu

[Succeeded / Failed / Skipped / Total] 27 / 30 / 12 / 69:  57%|█████▋    | 57/100 [11:16<08:30, 11.87s/it]

--------------------------------------------- Result 69 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

Prin încheierea Judecătoriei Bălţi din 26.05.2014 a fost admis parţial demersul procurorului Procuraturii Anticorupţie Victor Muntean privind prelungirea duratei arestării la domiciliu a inculpatului xxxxNUMExxxx învinuit în comiterea infracţiunii prevăzute de art. 42 alin. (2), (3), (4), 45, 324 alin. (2) lit. b),c),d) Cod penal pe un termen de 90 zile, fiind prelungit termenul cu 40 zile, adică pînă la 05.07.2014, ora 14.50, cu păstrarea restricţiilor şi obligaţiunilor stabilite prin decizia Curţii de Apel Chişinău din 30.01.2014. Împotriva acestei încheieri a fost declarat recurs de avocatul Eduard Ceornea în interesele inculpatului xxxxNUMExxxx, invocînd că argumentele acuzării şi concluziile instanţei poartă un caracter subiectiv, lipsite de temeiuri şi probe ce ar demonstra temeinicia necesităţii prelungirii duratei măsurii preventive, lipsind şi pericolele pretins ca fiind existente. Consideră că instanţa de fond a ignorat prevederile art.176 CPP, şi n­a argumentat prin probe prezenţa temeiurilor rezonabile de a presupune că inculpatul se va eschiva de la urmărirea penală, va influenţa martorii, va crea obstacole în vederea desfăşurării normale şi obiective a procesului de acumulare a probelor, ori să săvîrşească alte infracţiuni. Susţine că, inculpatul pe parcursul urmăririi penale şi în special pe parcursul aflării în arest la domiciliu, nu a efectuat tentative de a se eschiva de la organul de urmărire penală, nu a comis acţiuni de distrugere a probelor sau tăinuire a acestora, probele fiind deja administrate, martorii fiind audiaţi, lipsind orice pericol de distrugere a probelor. Mai indică că, inculpatul anterior n­a fost condamnat, are loc permanent de trai, pe parcursul activităţii a fost menţionat pentru merite în serviciu, are la întreţinere doi copii minori, s­a prezentat la orice citare a organului de urmărire penală. La moment xxxxNUMExxxx nu mai activează, fiind eliberat din funcţie. Astfel, are nevoie de un loc de muncă pentru a întreţine familia. Solicită casarea încheierii instanţei de fond ca fiind neîntemeiată, respingerea demersului procurorului şi aplicarea măsurii preventive ­ obligarea de a nu părăsi localitatea. Inculpatul şi avocatul ce l­a asistat în şedinţa instanţei de recurs au susţinut recursul declarat în interesele inculpatului xxxxNUMExxxx şi au solicitat admiterea lui din motivele invocate. Procurorul în şedinţa instanţei de recurs a solicitat respingerea recursului cu menţinerea încheierii instanţei de fond. Verificînd argumentele invocate în recurs, în raport cu materialele cauzei penale prezentate pentru verificarea legalităţii încheierii contestate şi audiind opiniile participanţilor la proces, Colegiul penal ajunge la concluzia că recursul urmează a fi respins cu menţinerea încheierii contestate reieşind din următoarele considerente. Conform art.312 alin.5 pct.2 CPP, în urma controlului judiciar efectuat, instanţa de recurs respinge recursul. Prelungirea termenului de arest la domiciliu a inculpatului este determinată de complexitatea cauzei penale, caracterul social periculos al faptei imputate, personalitatea inculpatului, faptul că ar putea să împiedice la stabilirea adevărului, deoarece activînd anterior în organele MAI, ar putea prin diverse metode să influenţeze martorii, ceea ce este în detrimentul scopului procesului penal. Astfel, riscurile care au justificat arestarea şi prelungirea termenului arestului la domiciliu al inculpatului nu s­au diminuat. Totodată, măsura preventivă sub formă de arest la domiciliu este oportună şi necesară pentru a asigura examinarea cauzei în termeni rezonabili şi a exclude

[Succeeded / Failed / Skipped / Total] 27 / 31 / 12 / 70:  58%|█████▊    | 58/100 [11:29<08:19, 11.90s/it]

--------------------------------------------- Result 70 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

Prin încheierea Judecătoriei Buiucani, m. Chişinău din 22 martie 2013, au fost admise demersul Ministrului Justiţiei al Republicii Moldova şi cererea condamnatului Mardari Igor Valeriu, 08 noiembrie 1978 a.n., originar din s. Gura Bâcului, r. Anenii Noi, domiciliat în m. Chişinău, s. Bubueci, str. Frunze 1A, cetăţean al Republicii Moldova, cu studii medii, căsătorit, la întreţinere doi copii minori, ne angajat la muncă, anterior necondamnat, privind transferul pentru continuarea executării pedepsei cu închisoare în instituţiile penitenciare din Republica Moldova, acceptându-se transferul acestuia, considerându-l condamnat prin sentinţa Judecătoriei or. Moscova , Federaţia Rusă din 26 decembrie 2011 în baza art. 171 alin. (2) lit. b), art. 171 alin. (2) lit. b), art. 172 alin. (2) lit. b) CP RM şi stabilindu-i pedeapsa, în conformitate cu art. 84 CP, 13 ani închisoare, în penitenciare de tip semiînchis, cu calcularea termenului ispăşirii pedepsei de la 25 iunie 2011, cu posibilitatea liberării condiţionate înainte de termen la ispăşirea efectivă a 2/3 din termenul de pedeapsă stabilit. Prejudiciul moral încasat de la condamnatul Mardari Igor în partea sumelor nerecuperate la data transferului în Republica Moldova urmează de încasat potrivit regulilor stabilite de Codul de executare a RM, cu preluarea actelor executorii deschise în baza titlurilor executorii a statului străin, cu încasarea sumelor în lei RM potrivit cursului de schimb stabilit de Banca Naţională a Moldovei la data încasării. 1 Pentru a hotărî astfel, instanţa de fond a stabilit că Mardari Igor a fost condamnat prin sentinţa Judecătoriei or. Moscova , Federaţia Rusă din 26 decembrie 2011 în baza art. 131 alin. 3 pct. a), 132 alin. 3 pct. a), 131 alin. 3 pct. a), 69 CP a Federaţiei Ruse la 13 ani închisoare, în penitenciar de tip sever, cu calcularea termenului ispăşirii pedepsei de la 25 iunie 2011. Prin sentinţă s-a dispus încasarea de la condamnat a prejudiciului moral în folosul lui Cecina Angelica Vladimirovna în sumă de 500000 rub. Ministrul Justiţiei al RM a înaintat în Judecătoria Buiucani m. Chişinău demers de transfer în care se indică că, în cadrul Ministerului Justiţiei al Republicii Moldova se soluţionează cauza privind transferul din Federaţia Rusă în Republica Moldova a cet. Mardari Igor , pentru continuarea executării pedepsei, stabilite de instanţa rusă, într-un penitenciar din Republica Moldova, în baza;în baza art. 6 din Convenţia europeană asupra transferării persoanelor condamnate, din 21.03.1983, şi art. 556 din Codul de Procedură Penală al Republicii Moldova. Potrivit art. 551 CPP RM, transferul persoanelor condamnate se efectuează în baza tratatului internaţional la care Republica Moldova şi statul respectiv sînt părţi sau în condiţii de reciprocitate stabilite printr-un acord scris între Ministerul Justiţiei al Republicii Moldova şi instituţia respectivă a statului străin. Republica Moldova şi Federaţia Rusă au ratificat Convenţia Europeană asupra transferului persoanelor condamnate (Strasburg din 21 martie 1983) şi careva impedimente în acest sens nu au fost stabilite. Temei pentru transferul persoanelor condamnate poate fi cererea persoanei condamnate la închisoare de către o instanţă judecătorească străină de a fi transferată pentru executarea pedepsei în Republica Moldova, prescrie aceiaşi lege şi o asemenea cerere condamnatul Mardari Igor a înaintat la 29.03.2012, a declarat că

[Succeeded / Failed / Skipped / Total] 28 / 31 / 12 / 71:  59%|█████▉    | 59/100 [11:38<08:05, 11.84s/it]

--------------------------------------------- Result 71 ---------------------------------------------
[[1 (99%)]] --> [[0 (61%)]]

1. [[Inculpatul]] Floreac Alexandr Alexandr la data de 09.05.2016, ne fiind posesor al permisului de conducere, fiind în stare de ebrietate alco ă şi fiind conştient de caracterul prejudiciabil al acţiunilor sale şi urmările lor, s­a aşezat la volan și a condus automobilul de model „Audi A ” nr/în. C RH 410, iar în jurul orelor 03.00, [[deplasîndu]]­se pe str.Ștefan cel Mare din mun.Bălți, în regiunea imobilului nr.54A a provocat XXXXXXX accident rutier neînsemnat, din care motiv de către colaboratorii poliției, fiind suspectat de întrebințarea băuturilor alcoolice, acesta avî semne vizibile de ebrietate alcoolică, exprimate prin dereglarea vorbirii, miros specific de alcool din cavitatea bucală, a fost supus tării alcooscopice prin metoda alcotest „Drager”, în rezultatul căreia a fost stabilit că concentraţia vaporilor de alcool în aerul expirat de către el a constituit 1,10 mg/l. În ătură cu acest fapt XXXXXXXXX a fost condus la Serviciului Narcologic al [[Spitalului]] municipal Bălţi, unde conform proces ­verbal al examinării medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate și naturii ei nr.2216 din 09.05.201­a stabilit că Floreac Alexandr se afla în stare de ebrietate alcoolică cu grad avansat. Ulterior, de la el au fost recoltate mostre biologice de sînge pentru cercetare med­legală toxicologică. Conform raportului de expertiză medico­legală nr.174 din 13.05.2016 în sîngele c XXXXXXXXX s­a depistat alcool etilic în cantitate de 2,64%, echivalent a 2,64g/l, cantitatea care conform art. 134/12 CP se atribuie la stare de ebrietate alco ă cu grad avansat. 2. Inculpatul XXXXXXXXX, fiind audiat în cadrul examinării cauzei, chestionat sub jurămînt în conformitate cu art.108 şi art.364/1 Cod de proce ă penală al RM, vina în săvîrşirea acţiunilor ilegale a recunoscut­o pe deplin şi a [[explicat]] [[instanței]] că, la data de 09.05.2006 se deplasa automobilul de model „Audi A 80” nr/în. C RH 410, fiind în stare de ebrietate și, nereușind să frîneze, s­a tamponat într­un gard, speriin­se a plecat acasă. Mai tîrziu la el au venit colaboratorii de poliție și, fiind supus testării alcoolscopice, s­a stabilit că se afla în stare de ebriet. La întrebările adresate inculpatul XXXXXXXXX a declarat instanței că, recunoaște integral vina, se căiește și regretă de cele comise, solicitînd în acest sens eliberarea de pedeapsa peă și aplicarea amnistiei. Careva obiecţii în privinţa probelor acumulate de către organul de urmărire penală nu a invocat şi nu a prezentat probe noi. 2.1. La fel, vina în comiterea infracţiunii inculpatul XXXXXXXXX a recunoscut­o integral, solicitînd prin cerere semnată personal, cu cţinutul expres şi neechivoc şi cu renunţarea de a fi prezentate probe suplimentare, examinarea cauzei în ordinea prevăzută de art. 364/1 Cod de proce ă penală al RM. În ordinea prevăzută au fost solicitate opiniile participanţilor la proces. Procurorul nu a invocat obiecţii cu privire la examinarea cauzei în ordinea prevăzută de art. 364/1 CPP al RM. Apărătorul a susţinut cererea inculpatului. Instanţa de judecată, analizînd cererea inculpatului şi ascultînd opiniile participanţilor la proces, ţinînd cont de recunoaşterea totală şi necoţionată a vinovăţiei, şi­a găsit posibilă de a admite cererea inculpatului XXXXXXXXX, dat fiind faptul că din probele administrate reză că faptele inculpatului sînt

1. [[Inculptaul]] Floreac Alexandr Alexandr la data de 09.05.2016, ne fiind posesor al permisului de conducere, fiind în stare de ebrietate alco ă şi fiind conştient de caracterul prejudiciabil al acţiunilor sale şi urmările lor, s­a aşezat la volan și a condus automobilul de model „Audi A ” nr/în. C RH 410, iar în jurul orelor 03.00, [[deplsaîndu]]­se pe str.Ștefan cel Mare din mun.Bălți, în regiunea imobilului nr.54A a provocat XXXXXXX accident rutier neînsemnat, din care motiv de către colaboratorii poliției, fiind suspectat de întrebințarea băuturilor alcoolice, acesta avî semne vizibile de ebrietate alcoolică, exprimate prin dereglarea vorbirii, miros specific de alcool din cavitatea bucală, a fost supus tării alcooscopice prin metoda alcotest „Drager”, în rezultatul căreia a fost stabilit că concentraţia vaporilor de alcool în aerul expirat de către el a constituit 1,10 mg/l. În ătură cu acest fapt XXXXXXXXX a fost condus la Serviciului Narcologic al [[Siptalului]] municipal Bălţi, unde conform proces ­verbal al examinării medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate și naturii ei nr.2216 din 09.05.201­a stabilit că Floreac Alexandr se afla în stare de ebrietate alcoolică cu grad avansat. Ulterior, de la el au fost recoltate mostre biologice de sînge pentru cercetare med­legală toxicologică. Conform raportului de expertiză medico­legală nr.174 din 13.05.2016 în sîngele c XXXXXXXXX s­a depistat alcool etilic în cantitate de 2,64%, echivalent a 2,64g/l, cantitatea care conform art. 134/12 CP se atribuie la stare de ebrietate alco ă cu grad avansat. 2. Inculpatul XXXXXXXXX, fiind audiat în cadrul examinării cauzei, chestionat sub jurămînt în conformitate cu art.108 şi art.364/1 Cod de proce ă penală al RM, vina în săvîrşirea acţiunilor ilegale a recunoscut­o pe deplin şi a [[exlpicat]] [[intsanței]] că, la data de 09.05.2006 se deplasa automobilul de model „Audi A 80” nr/în. C RH 410, fiind în stare de ebrietate și, nereușind să frîneze, s­a tamponat într­un gard, speriin­se a plecat acasă. Mai tîrziu la el au venit colaboratorii de poliție și, fiind supus testării alcoolscopice, s­a stabilit că se afla în stare de ebriet. La întrebările adresate inculpatul XXXXXXXXX a declarat instanței că, recunoaște integral vina, se căiește și regretă de cele comise, solicitînd în acest sens eliberarea de pedeapsa peă și aplicarea amnistiei. Careva obiecţii în privinţa probelor acumulate de către organul de urmărire penală nu a invocat şi nu a prezentat probe noi. 2.1. La fel, vina în comiterea infracţiunii inculpatul XXXXXXXXX a recunoscut­o integral, solicitînd prin cerere semnată personal, cu cţinutul expres şi neechivoc şi cu renunţarea de a fi prezentate probe suplimentare, examinarea cauzei în ordinea prevăzută de art. 364/1 Cod de proce ă penală al RM. În ordinea prevăzută au fost solicitate opiniile participanţilor la proces. Procurorul nu a invocat obiecţii cu privire la examinarea cauzei în ordinea prevăzută de art. 364/1 CPP al RM. Apărătorul a susţinut cererea inculpatului. Instanţa de judecată, analizînd cererea inculpatului şi ascultînd opiniile participanţilor la proces, ţinînd cont de recunoaşterea totală şi necoţionată a vinovăţiei, şi­a găsit posibilă de a admite cererea inculpatului XXXXXXXXX, dat fiind faptul că din probele administrate reză că faptele inculpatului sînt

[Succeeded / Failed / Skipped / Total] 28 / 32 / 12 / 72:  60%|██████    | 60/100 [11:52<07:54, 11.87s/it]

--------------------------------------------- Result 72 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

XXXXXXXXX, la XXXXXXXXX, în jurul orelor 21:00, deţinând permis de conducere nr.128301518, eliberat la 25.10.2012 categoria „B”, fiind în stare de ebrietate alcoolică, încălcând cerinţele art.14 lit.a) a Regulamentului Circulaţiei Rutiere, care determină că „conducătorului de vehicul îi este interzis să conducă vehiculul dacă a consumat băuturi alcoolice, droguri sau alte substanţe contraindicate conducerii, ce se află sub influenţa preparatelor medicamentoase care duc la reducerea reacţiei”, s­a urcat la volanul automobilului personal de model „VAZ 2106”, cu nr/î EDAH 377, şi conducându­l prin satul Niorcani, r­nul Soroca, a fost stopat de colaboratorii poliţiei aflaţi în exerciţiul funcţiei. Ulterior, fiind suspectat de conducerea autovehiculului în stare de ebrietate alcoolică, a fost verificat cu aparatul „Dräger Alcotest 8510 RO”, care a indicat vaporii în aer expirat în măsură de 0,99 mg/l care conform 12 art.134 din Codul penal, constituie starea de ebrietate alcoolică cu grad avansat (mai mult de 1,0 g/l de alcool în sînge şi concentraţia aerului expirat de la 0,5 mg/l şi mai mult). 12 În conformitate cu prevederile art. 134 alin. (3) din Codul Penal, concentraţia vaporilor de alcool în aerul expirat de la 0,5 mg/l şi mai mult constituie stare de dereglare psihofuncţională a organismului în urma consumului de alcool, calificată ca stare de ebrietate alcoolică cu grad avansat. 1 În cadrul efectuării urmăririi penale acţiunile lui XXXXXXXXXX au fost calificate potrivit infracţiunii prevăzute de art. 264 alin. (1) din Codul Penal. În şedinţa judiciară inculpatul XXXXXXXXX, a solicitat judecarea cauzei pe baza probelor administratea în faza de urmărire penală, a declarat că recunoaşte în totalitate faptele indicate în rechizitoriu şi nu solicită administrarea de noi probe. Vina în comiterea infracţiunii incriminate a recunoscut­o integral, declarînd sub jurămînt că, toate împrejurările în care a fost comisă infracţiunea. Este căsători şi sincer se căieşte de cele comise. Deşi inculpatul vina în comiterea infracţiunii a recunoscut integral, vina acestuia a mai fost dovedită în şedinţa de judecată prin următoarele probe, prezentate de către acuzatorul de stat şi acceptate de inculpat: Prin declaraţiile martorului XXXXXXX, care în cadrul urmăririi penale, a declarat că, care a declarat că la data de XXXXXXXXX a fost implicat în serviciu de patrulare rutieră şi menţinere ordinii publice, conform dislocaţiei prin raionul Soroca, împreună cu inspectorul inferior de patrulare rutieră, plutonier adjutant XXXXXXXX. În jurul orelor 20.50 min., aflându­se prin s.Niorcani r­l Soroca a observat deplasându­se un automobil de model VAZ 2106 cu n/î EDAH 377. Prezentul mijloc de transport a fost stopat ulterior XXXXXXXXX a solicitat de la conducătorul automobilul actele pe mașină, (permis, pașaportul tehnic, revizia tehnică, asigurarea auto) șoferul a declarat că nu dispune de nici de un act din cele solicitate deoarece le­a pierdut. Totodată, șoferul s­ a prezentat ca fiind XXXXXXX, a.n. locuitor a s.Tolocănești r­l Soroca, iar în timpul discuției din cavitatea bucală a ultimului se simțea miros puternic de alcool. Astfel XXXXXXXX i­a propus lui XXXXXXXX să fie testat cu alcooltestul Drager, ultimul a căzut de acord rezultatul final fiind 0.99 mg/l de alcool în aerul expirat. Conducătorul XXXXXXXXX, a fost de acord cu prezentul rezultat semnând în acest sens o

[Succeeded / Failed / Skipped / Total] 29 / 32 / 13 / 74:  61%|██████    | 61/100 [12:00<07:40, 11.82s/it]

--------------------------------------------- Result 73 ---------------------------------------------
[[0 (98%)]] --> [[1 (69%)]]

Pe data de 06.10.2010 aproximativ pe la orele 02.00 inculpatul xxxxNUMExxxx fiind în stare de ebrietate alcoolică , din intenţii huliganice a pătruns în [[ograda]] casei cet. xxxxCUSTOM2xxxx Ludmila , domiciliată în sat. Păpăuţi r­l [[Rezina]] şi fără nici un motiv i­a aplicat lovituri cu pumnul în regiunea frunţii şi pieptului , provocîndu­i [[dureri]] fizice şi a ameninţat­o cu moartea. Vina inculpatului xxxxNUMExxxx în comiterea acestei infracţiuni a fost dovedită pe deplin în cadrul [[cercetărilor]] judecătoreşti prin declaraţiile părţii vătămate , martorului , materialele dosarului penal. Astfel partea vătămată [[xxxxCUSTOM1xxxx]] a declarat judecăţii că, pe data de 06.10.2010 pe la orele 02.00 se afla la domiciliul său în sat.Păpăuţi Rezina şi se odihnea. Auzind că cineva strigă şi bate la uşă a eşit şi l­a văzut pe cet.Gatarag Denis care era în stare de ebrietate. Tot atunci l­a întrebat ce caută la dînsa în gospodărie. xxxxNUMExxxx. i­a [[cominicat]] că are nevoie de chibrite, la ce i­a spus că este tîrziu.Gadarag a numit­o cu fel de fel cuvinte [[necenzurate]] şi i­a aplicat două lovituri cu pumnul una în regiunea pieptului şi alta în regiunea frunţii. Tot atunci l­a strigat pe tatăl său şi i­a spus lui Gadarag că va anunţa poliţia despre cele întîmplate. Peste puţin timp a eşit tata xxxxCUSTOM2xxxx Ambrosie , care şi el l­a întrebat ce caută xxxxNUMExxxx. în gospodăria lor. I­a spus şi tata că se va adresa la poliţie. [[Gadarag]] le­a spus că nu se teme , va plăti poliţiştilor 1000 de lei , dar cu ei va face ce vrea. Cuvintele lui au sunat pentru dînşii ca o ameninţare reală. Apoi Gadarag a plecat. Tot în ziua ceea pe data de 06.10.2010 s­a adresat cu cerere la şeful de post şi a fost îndreptată la medicul [[legist]] , însă nu s­a dus deoarece la momentul cela nu dispunea de suma necesară de bani. Martorul Şumila Ambrosie a declarat judecăţii că, pe data de 06.10.2010 la orele 02.00 se afla la domiciliul său în sat. Păpăuţi [[Rezina]] împreună cu fiica sa xxxxCUSTOM1xxxx şi un strănepot , se odihneau. Într­un timp din comn a auzit cum fiica lui Ludmila îl cheamă în ajutor din motivul că cineva o bate.Eşind afară l­a văzut pe xxxxNUMExxxx , care era în stare de ebrietate.Fiica era înnsîngerată la faţă. L­a întrebat pe Gadarag ce caută aşa tîrziu în ograda gospodăriei lor şi că va anunţa poliţia .Gadarag le­a spus că nu se teme de poliţie şi le face tot ce vrea.Cuvintele lui au sunat ca o ameninţare. Apoi Gadarag a plecat , dar fiica i­a povestit că Gadarag a venit după chibrite şi fără careva temei a lovit­o cu pumnul în piept şi la nas. Îi curgea sînge. Pînă la cazul dat nu au avut careva conflicte cu inculpatul. Inculpatul xxxxNUMExxxx în şedinţa de judecată a declarat că recunoaşte vina , că pe data de 06.10.2010 pe la orele 02.00 întradevăr a întrat în gospodăria cet. Şumila L. , a strigat mai întîi la poartă, apoi a bătut la uşă . Cînd a eşit d­na xxxxCUSTOM1xxxx a cerut de la dînsa chibrite .Deoarece

Pe data de 06.10.2010 aproximativ pe la orele 02.00 inculpatul xxxxNUMExxxx fiind în stare de ebrietate alcoolică , din intenţii huliganice a pătruns în [[ogarda]] casei cet. xxxxCUSTOM2xxxx Ludmila , domiciliată în sat. Păpăuţi r­l [[Reizna]] şi fără nici un motiv i­a aplicat lovituri cu pumnul în regiunea frunţii şi pieptului , provocîndu­i [[durrei]] fizice şi a ameninţat­o cu moartea. Vina inculpatului xxxxNUMExxxx în comiterea acestei infracţiuni a fost dovedită pe deplin în cadrul [[cecretărilor]] judecătoreşti prin declaraţiile părţii vătămate , martorului , materialele dosarului penal. Astfel partea vătămată [[xxxxCUSTOMx1xxx]] a declarat judecăţii că, pe data de 06.10.2010 pe la orele 02.00 se afla la domiciliul său în sat.Păpăuţi Rezina şi se odihnea. Auzind că cineva strigă şi bate la uşă a eşit şi l­a văzut pe cet.Gatarag Denis care era în stare de ebrietate. Tot atunci l­a întrebat ce caută la dînsa în gospodărie. xxxxNUMExxxx. i­a [[comniicat]] că are nevoie de chibrite, la ce i­a spus că este tîrziu.Gadarag a numit­o cu fel de fel cuvinte [[necenuzrate]] şi i­a aplicat două lovituri cu pumnul una în regiunea pieptului şi alta în regiunea frunţii. Tot atunci l­a strigat pe tatăl său şi i­a spus lui Gadarag că va anunţa poliţia despre cele întîmplate. Peste puţin timp a eşit tata xxxxCUSTOM2xxxx Ambrosie , care şi el l­a întrebat ce caută xxxxNUMExxxx. în gospodăria lor. I­a spus şi tata că se va adresa la poliţie. [[Gaadrag]] le­a spus că nu se teme , va plăti poliţiştilor 1000 de lei , dar cu ei va face ce vrea. Cuvintele lui au sunat pentru dînşii ca o ameninţare reală. Apoi Gadarag a plecat. Tot în ziua ceea pe data de 06.10.2010 s­a adresat cu cerere la şeful de post şi a fost îndreptată la medicul [[legsit]] , însă nu s­a dus deoarece la momentul cela nu dispunea de suma necesară de bani. Martorul Şumila Ambrosie a declarat judecăţii că, pe data de 06.10.2010 la orele 02.00 se afla la domiciliul său în sat. Păpăuţi [[Reznia]] împreună cu fiica sa xxxxCUSTOM1xxxx şi un strănepot , se odihneau. Într­un timp din comn a auzit cum fiica lui Ludmila îl cheamă în ajutor din motivul că cineva o bate.Eşind afară l­a văzut pe xxxxNUMExxxx , care era în stare de ebrietate.Fiica era înnsîngerată la faţă. L­a întrebat pe Gadarag ce caută aşa tîrziu în ograda gospodăriei lor şi că va anunţa poliţia .Gadarag le­a spus că nu se teme de poliţie şi le face tot ce vrea.Cuvintele lui au sunat ca o ameninţare. Apoi Gadarag a plecat , dar fiica i­a povestit că Gadarag a venit după chibrite şi fără careva temei a lovit­o cu pumnul în piept şi la nas. Îi curgea sînge. Pînă la cazul dat nu au avut careva conflicte cu inculpatul. Inculpatul xxxxNUMExxxx în şedinţa de judecată a declarat că recunoaşte vina , că pe data de 06.10.2010 pe la orele 02.00 întradevăr a întrat în gospodăria cet. Şumila L. , a strigat mai întîi la poartă, apoi a bătut la uşă . Cînd a eşit d­na xxxxCUSTOM1xxxx a cerut de la dînsa chibrite .Deoarece


--------------------------------------------- Result 74 ---------------------------------------------
[[1 (84%)]] --> [[[SKIPPED]]]

XXXXXXXXX, la data de 18 noiembrie 2014, aproximativ la ora 09:00, aflîndu­se în incinta liceului teoretic „D. Cantemir” din or.Rîşcani, acţionînd intenţionat, în scopul sustragerii bunurilor altei persoane, în timpul lecţiei de educaţie fizică, din vestiar, a sustras pe ascuns din buzunarul scurtei elevului Verijja Durim telefonul mobil de model „Nokia 206” cu cartela SIM 078892699, cauzîndu­i proprietarei Ducătari Dina o daună în proporţii considerabile în valoare de 3000 lei. Tot el, prelungind acţiunile sale criminale, acţionînd perin aceeaşi metodă şi în acelaşi scop, la 18 noiembrie 2014, aproximativ la ora 09:05, aflîndu­se în incinta liceului teoretic „D.Cantemir” din or.Rîşcani, în timpul lecţiei de educaţie fizică, din vestiar, a sustras pe ascuns din buzunarul scurtei elevului Butnari Dumitru telefonul mobil de model „Samsung GT­S7262” cu cartela SIM, cazîndu­i proprietarei Butnari Inga o daună în proporţii considerabile în valoare de 3000 lei. Tot el, în noaptea din 02 mai 2015, împreună cu Climuşchin Pavel Fiodor, şi Timotin Artiom, intenţionat avînd scop de cupiditate, au pătruns în gospodăria cet.Tcaci Andrei Vasili din s.Balanul Nou, raionul Rîşcani, de unde pe ascuns au sustras un aparat electric de sudat, în sumă de 2000 lei, astfel, pricinuind părţii vătămate o daună în proporţii considerabile. Climuşchin Pavel Fiodor, în noaptea din 02 mai 2015, împreună cu XXXXXXXXX, şi Timotin Artiom, intenţionat avînd scop de cupiditate, au pătruns în gospodăria cet.Tcaci Andrei Vasili din s.Balanul Nou, raionul Rîşcani, de unde pe ascuns au sustras un aparat electric de sudat, în sumă de 2000 lei, astfel, pricinuind părţii vătămate o daună în proporţii considerabile. În cadrul urmării penale XXXXXXXXX și XXXXXXXXX au încheiat acord de recunoaştere a vinovăţiei care au fost acceptate de instanţa de judecată prin încheierea judiciară din 04 martie 2016 şi în şedinţa de judecată au recunoscut pe deplin vinovăţia de săvîrşirea infracţiunilor încriminate şi probele înaintate de acuzare şi au declarat: XXXXXXXXX că, a venit la şcoală pe data de 18.11.2014, înainte de lecţia de educaţie fizică. Se afla în sala sportivă unde dintr­ o scurtă şi geantă a sustras 2 telefoane mobile de la colegii săi din clasele paralele. Telefoanele mobile au fost reîntoarse. Împreună cu Timotin Artiom şi Climuşchin Pavel a sustras de la Tcaci Andrei aparatul electric de sudat. Despre existenţa aparatului electric de sudare cunoştea Timotin Artiom care este nepotul ultimului. Aparatul electric de sudat, era preconizat de al duce la punctul de primire a metalului. Prejudiciul lui Tcaci Andrei a fost reîntors, fiecare a achitat cîte 800 lei. Este de acord cu cererea depusă de către partea vătămată Tcaci Andrei şi Bucătari Dina cu privire la încetarea procesului penal pe motivul împăcării părţilor. În vestiarul liceului „D. Cantemir” din or. Rîşcani se afla scurta şi geanta de unde a sustras telefoanele mobile. Un telefon mobil fiind de culoare neagră – „senser”, iar altul fiind cu butoane. Un tele ţinea lui Verijja Durim, iar altul lui Butnari Dumitru. După ce a furat telefoanele, ultimul nu a mai fost la lecţie. Pe data de 02.05.2015 minorul Nirca Oleg a furat aparatul electric de sudat. Persoanele la care a sustars bunurile date nu îi

[Succeeded / Failed / Skipped / Total] 29 / 33 / 17 / 79:  62%|██████▏   | 62/100 [12:14<07:30, 11.85s/it]

--------------------------------------------- Result 75 ---------------------------------------------
[[0 (98%)]] --> [[[FAILED]]]

xxxxNUMExxxx, în decursul mai multor ani, sistematic, aflându­se în stare de ebrietate alcoolică, îşi abuzează fizic şi psihic concubina ­ xxxxNUMExxxx, cu care locuieşte împreună în domiciliu ei situat xxxxSATxxxx, r­ul Ştefan Vodă, înjosindu­i onoarea şi demnitatea acestea şi cauzîndu­i dureri fizice, din acest motiv în cadrul procesului penal înregistrat în R­1 a IP Ştefan Vodă sub nr.20143400614 din 04.08.2014, de către judecătoria r­ul Ştefan Vodă, la data de 02.09.2014, a fost eliberată ordonanţă de protecţie în privinţa xxxxNUMExxxx, de la acţiunile violente al concubinului xxxxNUMExxxx, pe un termen de 3 luni fiind stabilite masuri de protecţie. La data de 08.09.2014, aproximativ la orele 23:00, xxxxNUMExxxx, încălcând măsurile de protecţie, aplicate prin ordonanţa de protecţie din 02.09.2014, şi fiind în stare de ebrietate alcoolică, invocând faptul că, concubina xxxxNUMExxxx, îl înşeală cu cet. xxxxNUMExxxx a aplicat violenţă psihică asupra concubinei sale numind­o cu diferite cuvinte necenzurate înjosindu­i onoarea şi demnitatea şi din cauza comportamentului agresiv ultima a fost nevoită să se ascundă cu copii minori în grădina casei proprii. Tot, el continuîndu­şi acţiunile sale de violenţă la data de 09.09.2014, aproximativ la orele 07:00, cînd concubina s­a întors la domiciliu, negând măsurile de protecţie stabilite prin ordonanţa de protecţie din 02.09.2014, iarăşi invocând faptul că, ultima la înşelat cu xxxxNUMExxxx, a iscat o ceartă, în urmă căruia a numit­o cu diferite cuvinte necenzurate înjosindu­i onoarea şi demnitatea acestea, apoi a aplicat violenţa fizică manifestată prin aceea că, a tras­o cu mîinele de păr, în urmă căruia ea a căzut jos şi luând un ferestrău a efectuat câteva tăieturi în regiunea gâtului cauzându­i dureri fizice. Ultimul caz de violenţă în familie comis de către cet. xxxxNUMExxxx a avut loc la data de 15.10.2014, aproximativ la orele 12:00, iarăşi încălcând ordonanţa de protecţie din data de 02.09.2014, fiind în stare de ebrietate alcoolică, a venit la domiciliul concubinei a iniţiat un conflict, în urmă căruia numit­o cu cuvinte injurioase pe concubina sa, xxxxNUMExxxx şi ameninţat­o cu răfuială fizică, astfel cauzîndu­i suferinţă psihică. Fiind audiat în ședința de judecată, inculpatul vinovăția sa de comiterea faptei incriminate a recunoscut integral, a depus declarația scrisă privind judecarea cauzei pe baza probelor administrate în faza de urmărire penală și a declarat că, locuieşte împreună cu xxxxNUMExxxx în casa ei proprie situată în xxxxSATxxxx, r­ul Ştefan Vodă şi împreună cu ei locuieşte copilul lor minor şi mai au la întreţinere 3 copii ai concubinei din căsătoria anterioară. La data de 09.09.2014 el a început să se certe cu concubina lui xxxxNUMExxxx, din cauză că era gelos pe ea şi a trîntit­o la pămînt şi din apropiere a luat de jos un ferestrău de tăiat fier şi a început să o lovească cu ferestrăul. După aceasta concubina lui a plecat de acasă împreună cu copii într­o direcţie necunoscută. El cu concubina au mai avut un conflict și a fost eliberată ordonanţă de protecţie de către Judecătoria raionului Ştefan Vodă. La data de 07.09.2014 el a încălcat ordonanţa de protecţie, ducîndu­se acasă, deoarece nu avea unde să se ducă. Concubina lui a acceptat să intre în casă, însă din cauza geloziei


--------------------------------------------- Result 76 ---------------------------------------------
[[1 (94%)]] --> [[[SKIPPED]]]

Inculpatul Florea Nicolae Nicolai, se învinuiește de către organul de urmărire penală, că la data de 21.02.2015 aproximativ la ora 00.30, împreună şi de comun acord cu Rudi Ion şi încă două persoane necunoscute, avînd scopul sustragerii pe ascuns a bunurilor altei persoane, a pătruns în gospodăria cet. Ciocănari Ivan situată în sat. Micleuşeni, r­nul Străşeni, de unde intenţionat a sustras un motobloc de model "Zubr" seria Q78E nr.12120894 la preţul de 13500 lei, după care cu bunul sustras a părăsit locul comiterii infracţiunii, astfel cauzându­i părţii vătămate XXXXXXXXX o daună materială în proporţii considerabile în sumă totală de 13500 lei. Inculpatul XXXXXXXXX, la 14.06.2015 aproximativ pe la orele 11.00, împreună şi de comun acord cu XXXXXXXXX, aflîndu­se pe imaşul din sat. Ghelăuza, r­ nul Străşeni şi avînd scopul sustragerii pe ascuns a bunurilor altei persoane, intenţionat prin acces liber au sustras un viţel care era priponit pe imaş, şi care aparţinea cet. Ala Elena, astfel cauzîndu­i părţii vătămate un prejudiciu material în proporţii considerabile în sumă totală de 3000 lei. Inculpatul XXXXXXXXX Iurie la 21.02.2015, aproximativ la orele 00:30, de comun acord cu XXXXXXXXX, Nița Vasile și Bîzgan Andrei avînd scopul sustragerii pe ascuns a bunurilor altei persoane, a pătruns în gospodăria cet. XXXXXXXXX, situat în s. Micleușeni, r­nul Strășeni de unde intenționat a sustras un motobloc de model ,,Zubr,, seria Q78E nr. 12120894 la prețul de 13500 lei, după care cu bunul sustras a părăsit locul comiterii infracțiunii, astfel cauzîndu­i părții vătămate o daună în proporții considerabile în sumă totală de 13500 lei. Tot el, la 14.06.2015, aproximativ la orele 14.00, împreună și de comun acord cu XXXXXXXXX, aflîndu­se pe imașul din s. Ghelăuza, r­nul Strășeni și scopul sustragerii pe ascuns a bunurilor altei persoane, intenționat prin acces luber au sustras vițelul care era priponit la imaș și care aparținea cet. XXXXXXXXX, cauzîndu­i părții vătămate o daună în proporții considerabile în sumă totală de 3000 lei. Tot el, în perioada de timp 11.02.2015­.16.02.2015, aproximativ la ora 01.00, împreună cu Bîzgan Andrei și XXXXXXXXX, acționînd cu intenții de profit, avînd scopul sustragerii bunurilor altei persoane, a pătruns la domiciliul cet. Rădvan Luiza situat în s. Roșcani, r­nul Strășeni, de unde în mod ascuns a sustras 12 calorifere din aluminiu la prețul de 29400 lei și un flex electric de model ACR la prețul de 850 lei, după care cu bunurile sutrase a părăsit locul comiterii infracțiunii, astfel cauzîndu­i părții vătămate o daună materială în proporții considerabile în mărime de 30250 lei. Inculpatul XXXXXXXXX în ședința de judecată nu s­a prezentat din motive necunoscute pentru instanța de judecată, din care considerente instanța de judecată a dispus prin încheierea din 23.06.2016 anunțarea în căutare a inculpatului și aplicarea măsurii preventive arestul preventiv pe un termen de 30 zile din momentul reținerii inculpatului. Prin informația din 06.07.2016, sub nr. 7602, s­a înștiințat instanța de judecată despre pornirea dosarului de căutare nr. 2016330125 în privința lui XXXXXXXXX Nicolai și în privința căruia se întreprind măsuri de căutare a acestuia. Astfel, că în conformitate cu prevederile art. 321,al.2, pct.1) CPP al RM, judecarea cauzei în lipsa


--------------------------------------------- Result 77 ---------------------------------------------
[[1 (72%)]] --> [[[SKIPPED]]]

Prin sentința Judecătoriei xdin 17.08.2011 x a fost recunoscut vinovat de comiterea infracțiunii prevăzute de art.287 alin.(2) lit.b) CP și în baza acestei Legi i­a fost stabilită pedeapsa sub formă de închisoare pe un termen de 2 (doi) ani, executarea pedepsei fiind suspendată condiționat pe un termen de probă de 2 (doi) ani. Prin sentința în cauză au fost condamnați deasemenea, x. La 21.01.2014 x a depus apel împotriva sentinței Judecătoriei x din 17.08.2011 care prin Decizia Colegiului penal al Curții de Apel x din 23.04.2014 a fost respins ca fiind depus peste termen. La 23.07.2014 Decizia Colegiului penal al Curții de Apel x din 23.04.2014 a fost remisă spre executare Biroului de probațiune x. La data de 19.11.2014 consilierul de probațiune a înaintat instanței de judecată demers, prin care a solicitat anunțarea în căutare a condamnatului x, motivîndu­l prin faptul, că la 23.07.2014 a parvenit spre executare sentința Judecătoriei xi din 17.08.2011 în privința lui x și ultimul fiind citat nu s­a prezentat la consilierul de probațiune. A mai invocat, că prin efectuarea mai multor verificări s­a stabilit, că x nu se deține în instituțiile penitenciare, frontiera de stat nu a traversat, nefiind posibil de stabilit locul aflării acestuia. Prin încheierea Judecătoriei x din 24.12.2014 a fost admis demersul înaintat de către consilierul de probațiune, x a fost anunțat în căutare, totodată fiind suspendată curgerea prescripției executării pedepsei stabilite prin sentința Judecătoriei x din 17.08.2011 pînă la găsirea condamnatului. La data de 28.04.2015 consilierul de probațiune a adresat instanței de judecată un alt demers prin care a solicitat anularea condamnării cu suspendarea condiționată a executării pedepsei și trimiterea condamnatului x la închisoare pentru executarea pedepsei stabilite prin sentința Judecătoriei x din 17.08.2011. Prin încheierea Judecătoriei x din XXXXXXXXX demersul consilierului de probațiune a fost admis, condamnarea cu suspendarea condiționată a executării pedepsei a fost anulată, cu trimiterea condamnatului x în penitenciar de tip semiînchis pentru executarea pedepsei stabilite prin sentința Judecătoriei x din 17.08.2011. La data de 11.11.2015 în cancelaria instanței de judecată a fost înregistrat recursul declarat de către avocatul x în interesele condamnatului x, împotriva încheierilor Judecătoriei Bălți din 24.12.2014 și din XXXXXXXXX. Recurentul a solicitat casarea încheierii Judecătoriei Bălți din XXXXXXXXX, cu rejudecarea cauzei și adoptarea unei noi hotărîri, prin care să fie respins ca neîntemeiat demersul Biroului de probațiune Bălți, precum și casarea încheierii Judecătoriei Bălți din 24.12.2014 și încetarea măsurilor de căutare în privința lui Secureanu Eugeniu. În motivarea cerințelor formulate, recurenta a indicat, că la emiterea acestora instanța de judecată nu a ținut cont de faptul, că Secureanu Eugeniu a ispășit pedeapsa stabilită, fapt confirmat prin certificatul Biroului de Probațiune x nr.1671 din 09.11.2015, în care se specifică, că x la 03.09.2013 a fost exclus de la evidență în legătură cu expirarea termenului de probă și astfel, a executat pedeapsa aplicată prin sentința Judecătoriei x din 17.08.2011. Urmare a executării pedepsei în anul 2013 x cu familia a plecat la muncă în Federația Rusă. Suplimentar a indicat, că la momentul examinării demersurilor consilierului de probațiune, a fost prezentată informația privind trecerea frontierei doar pentru anul


--------------------------------------------- Result 78 ---------------------------------------------
[[0 (95%)]] --> [[[SKIPPED]]]

I. Privind procedura. 1. Cauza penală, înregistrată cu nr.1-849/2015(nr.*****) în învinuirea lui Bojac Leonid Fiodor în comiterea infracțiunii prevăzute de art.190 alin.(5), 352 alin. (2) lit.c), d), 186 alin. (5) Cod penal a parvenit în instanța de judecată, în 5 volume, la data de 12.01.2015 şi primită în procedura judecătorului Nina Arabadji prin încheierea din 12.01.2015 (f.d.1,3, vol.XVII). 2. Cauza penală, înregistrată cu nr.1-879/2015 (nr.2015020037) în învinuirea lui Malcoci Iurie Mihail în comiterea infracţiunii prevăzute de art.190 alin.(5), 42 alin.(3), 352 alin. (2) lit.d) Cod penal a parvenit în instanța de judecată, în 5 volume, la data de 21.01.2015 şi primită în procedura judecătorului Oleg Melniciuc la 21.01.2015. Prin încheierea Judecătoriei Rîșcani, mun.Chișinău din 02.02.2015 cauza dată a fost conexată cu cauza nr.1-849/2015, aflată în procedura judecătorului Nina Arabadji, pentru examinare în fond(f.d.161,162,170,vol.X). 3. Cauza penală, înregistrată cu nr.1-909/2015 (nr.2015020105) în învinuirea lui Palamarciuc Sergiu Constantin în comiterea infracţiunii prevăzute de art.352 alin. (2) lit.d), 186 alin. (5) Cod penal a parvenit în instanța de judecată, în 6 volume, la data de 02.02.2015 şi primită în procedura judecătorului Igor Barbacaru la 05.02.2015. Prin încheierea Judecătoriei Rîșcani, mun.Chișinău din 17.02.2015 cauza dată a fost conexată cu cauza penală nr.1-849/2015, aflată în procedura judecătorului Nina Arabadji (f.d.92,94,102,vol.XVI). II. Privind descrierea faptei de către organul de urmărire penală, conform rechizitoriului și ordonanței de punere sub învinuire din 20.02.2023 se învinuește: 4. Inculpatul Bojac Leonid Fiodor că a comis infracțiunile de escrocherie, samovolnicie și furt în următoarele circumstanțe: În perioada lunilor octombrie- noiembrie 2010, Bojac Leonid Fiodor acționînd în comun acord și înțelegere prealabilă că Malcoci Iurie Mihail, urmărind scopul de a dobîndi ilicit prin înșelăciune și abuz de încredere bunurile material altei personae, dar neplanificînd asumarea și executarea unor obligații, repartizînd de comun acord rolurile între ei s-au deplasat pe *****, la locul de activitate a cet. Lupu Petru Nicolae ***** care avea în posesie în baza contractului de arendă nr. 0900810 din 09.08.2010 de la SRL “Camalox” în persoana lui Bujac Leonid un teren pentru realizarea materialelor de construcție cu suprafața de 120 m2, promițîndu-i lui Lupu Petru Nicolae că ar putea devein pînă la 01.12.2010 proprietarul acstui teren pe care este amplasat și un butic precum și proprietarul a trei containere amplasate în piața de comercializare a materialelor de construcție situate pe ***** numerotate cu nr. 66,67 și 76, i-au cerut acestuia și au primit ulterior de la el suma de 7000 euro cee ace conform cursului valutar BNM RM din 01.10.2011 constituie 113540 lei pe care au însușit-o, negînd ulterior acest fapt precum și amînînd executarea documentală a obligațiunilor asumate anterior, permițîndu-I lui Lupu Petru Nicolae ***** accesul în containerele menționate cu depozitarea mărfii sale, fără a perfect creva acte privind dreptul la activitatea acestuia în containerele menționate. Ca urmare, prin acțiunile sale intenționate Bojac Leonid Feodor a săvîrșit infracțiunea de escrocherie, adică dobândirea bunurilor altei persoane prin înșelăciune și abuz de încredere, de două persoane în proporții deosebit de mari, infracțiune prevăzută de art.190 alin.(5) Cod Penal, iar prin ordonanța din 20.02.2023 - art.190 alin.(2) lit.b) și c) Cod penal. Tot


--------------------------------------------- Result 79 ---------------------------------------------
[[1 (97%)]] --> [[[SKIPPED]]]

Prin sentința pronunțată instanța a reținut, că inculpatul XXX XXX XXX la 20.11.2014, aproximativ la ora 19.00, fiind în stare de ebrietate alcoolică, la domiciliul său din or. Sângerei, str. Independenței 194, înțelegând caracterul prejudiciabil al acţiunilor sale, din motivul relațiilor ostile existente, acționând cu scopul omorului intenționat al lui XXX XXX XXX, cu un cuţit de bucătărie i­a aplicat o lovitură în regiunea abdominală, după ce a încercat să­i aplice o lovitură cu cuţitul în regiunea gâtului, însă nu şi­a dus intenţia până la capăt, din motive independente de voinţa lui, şi anume din cauza rezistenței active opuse de victimă, ultima blocând lovitura de cuţit cu ajutorul mâinilor, după ce l­a îmbrâncit pe XXX XXX şi a fugit de la locul faptei şi s­a adresat la urgență. În rezultatul acțiunilor sale, părţii vătămate XXX XXX i­au fost cauzate vătămări corporale grave sub formă de plagă de cuţit penetrantă a abdomenului cu lezarea ligamentului gastrocolic, arterei epigastrice superioare şi mușchiul drept abdomenul pe stânga, hemoragie intraabdominală, plagă tăiată braţul drept. Instanţa de fond analizând şi apreciind probele în ansamblu, sub toate aspectele şi în mod obiectiv, din punctul de vedere al pertinenţei şi concludenţei, după intima convingere, a ajuns la concluzia, că probele analizate dovedesc integral vinovăţia inculpatului XXX XXX XXX în cele incriminate și acțiunile inculpatului XXX XXX XXX corect sânt încadrate în baza art. art. 27­145 alin. 1 Cod penal al RM, conform semnelor calificative ale infracțiunii de tentativă de omor intenționat a unei persoane. Instanța a conchis, că acțiunile inculpatului XXX XXX n­au fost duse până la capăt doar datorită comportamentului activ de apărare al părţii vătămate XXX XXX, ultimul făcând tot posibilul să scape din mâinile şi din strânsoarea inculpatului, care, după prima lovitură cu cuţitul, continua să facă uz de acesta, îndreptându­1 spre gâtul lui XXX X., dar acesta în încercarea de a bara lovitura cu mâna, a primit a doua lovitură, fapt confirmat şi prin raportul de expertiză medico­legală nr. 262D din 11.12.2014, prin care ultimului i s­au depistat leziuni sub formă de plagă de cuţit penetrantă a abdomenului cu lezarea ligamentului gastrocolic, arterei epigastrice superioare şi muşchiul drept abdomenul pe stânga, hemoragie intraabdominală, plagă tăiată braţul drept, care au fost cauzate posibil în termenul şi circumstanțele indicate de la acțiunea traumatică a unui corp, obiect ascuțit­tăios. Leziunile corporale sunt în concordanţă şi cu declaraţiile părţii vătămate despre proveniența acestora şi care adeveresc rolul activ al victimei de opunere de rezistență. Anume prin acțiunile acestuia inculpatul a fost împiedicat să­şi ducă gândul criminal până la capăt. La stabilirea categoriei şi mărimii pedepsei instanța s­a condus de prevederile art. art. 61, 72, 75 şi 81 CP al RM. Luând în considerație scopul pedepsei definit de art. 61 CP al RM: care urmărește restabilirea echității sociale, corectarea şi reeducarea condamnatului, precum şi prevenirea săvârşirii de noi infracțiuni atât din partea condamnaților, cât şi a altor persoane, or şi atitudinea inculpatului faţă de cele comise, personalitatea inculpatului, care se caracterizează pozitiv (f.d. 65), anterior a fost atras la răspundere penală, antecedentele fiind stinse (f.d. 72, 74­88), inclusiv pentru infracțiuni

[Succeeded / Failed / Skipped / Total] 30 / 33 / 17 / 80:  63%|██████▎   | 63/100 [12:23<07:16, 11.80s/it]

--------------------------------------------- Result 80 ---------------------------------------------
[[0 (68%)]] --> [[1 (51%)]]

Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut, că inculpatul xxNUMExx, la data 01.11.2014 ora 20:59, conducînd automobilul model ”VW Passat” n/î xxNUMxx, şi deplasîndu­se pe str. Dubinovschi dinspre str. Vlahuţa spre str. Unghenilor mun. Bălţi, în apropierea blocului locativ nr. 17 de pe str. Dubinovschi mun. Bălţi, conştientizînd caracterul social periculos al acţiunilor sale, încălcînd grosolan prevederile Regulamentului Circulaţiei Rutiere, aprobat prin Hotărîrea Guvernului R. Moldova nr.357 din 15.05.2009 /în continuare RCR/, p. 2 ”În Republica Moldova vehiculele se conduc pe partea dreaptă a carosabilului în sensul de mers”, p.45 al.1 ”conducătorul trebuie să conducă vehiculul în conformitate cu limita de viteză stabilită, ţinînd permanent seama de următorii factori: a) starea psihofiziologică ce influenţează atenţia şi reacţia; b) dexteritatea în conducere care i­ar permite să prevadă situaţiile periculoase; c) starea tehnică a vehiculului şi particularităţile încărcăturii; d) situaţia rutieră”, p. 45 al.2 ”în cazul în care în limita vizibilităţii apar obstacole care pot fi observate de conducător, el trebuig să reducă viteza sau chiar să oprească, pentru a nu pune în pericol siguranţa traficului”, precum şi p. 56 al.2 care prevede ”în cazul virştrii la stînga saiş întoarcerii conducătorul de vehicul trebuie să cedeze trecerea vehiculelor care vin din sens opus şi se vor deplasa înainte sau la dreapta”, fără să se încredinţeze de faptul că manevra nu va crea pericol pentru alţi participanţi la traficul rutier, a ieşit pe contrasens şi a tamponat motoreta model ”Honda CRE 50 HM” n/î xxNUMxx condusă de minorul xxNUMExx, care se deplasa regulamentar în sensul opus al automobilului, pe str. Dubinovschi dinspre str. Unghenilor spre direcţia str. Vlahuţa mun. Bălţi. În urma accidentului rutier, conform raportului de expertiză medico­legală nr. 487D din 17.11.2014 xxNUMExx s­a ales cu leziuni corporale grave, sub formă de traumatism asociat – traumă cranio­cerebrală închisă cu contuzie cerebrală de gr. I, fractură închisă a oaselor antebraţului drept, fractură închisă a osului femoral stîng, multiple excoreaţii pe faţă şi plagă contuză a buzei superioare. Instanţa de fond a pronunţat sentinţa sus indicată. Împotriva sentinţei a declarat recurs [[inculpatul]] xxNUMExx, care solicită casarea sentinţei, cu numirea pedepsei sub formă de 160 ore muncă neremunerată în folosul comunităţii, cu aplicarea art. 79 CP, fără privarea de dreptul de a conduce mijloace de transport. În motivarea recursului invocă, că pe parcursul examinării cauzei vina în săvîrşirea infracţiunii incriminate şi­a recunoscut­o pe deplin, sincer s­a căit în cele întîmplate. Pînă la momentul comiterii acestei crime devieri sau abateri de lege nu a avut, iar după comiterea acestei infracţiuni de asemenea nu a comis crime sau devieri de la lege, inclusiv şi comiterea încălcărilor de ordin contravenţional. Şi­a făcut concluziile necesare în urma comiterii infracţiunii incriminate, s­a corectat şi pe viitor nu va mai comite abateri de lege. Benevol a încheiat pînă la examinarea cauzei penale în instanţa de fond acordul de recunoaştere a vinovăţiei. Este căsătorit şi are la întreţinere un copil minor, iar la moment soţia este însărcinată. Este încadrat în cîmpul muncii şi activează în calitate de şofer, avînd nevoie de permisul de conducere, aceasta este unica lui

Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut, că inculpatul xxNUMExx, la data 01.11.2014 ora 20:59, conducînd automobilul model ”VW Passat” n/î xxNUMxx, şi deplasîndu­se pe str. Dubinovschi dinspre str. Vlahuţa spre str. Unghenilor mun. Bălţi, în apropierea blocului locativ nr. 17 de pe str. Dubinovschi mun. Bălţi, conştientizînd caracterul social periculos al acţiunilor sale, încălcînd grosolan prevederile Regulamentului Circulaţiei Rutiere, aprobat prin Hotărîrea Guvernului R. Moldova nr.357 din 15.05.2009 /în continuare RCR/, p. 2 ”În Republica Moldova vehiculele se conduc pe partea dreaptă a carosabilului în sensul de mers”, p.45 al.1 ”conducătorul trebuie să conducă vehiculul în conformitate cu limita de viteză stabilită, ţinînd permanent seama de următorii factori: a) starea psihofiziologică ce influenţează atenţia şi reacţia; b) dexteritatea în conducere care i­ar permite să prevadă situaţiile periculoase; c) starea tehnică a vehiculului şi particularităţile încărcăturii; d) situaţia rutieră”, p. 45 al.2 ”în cazul în care în limita vizibilităţii apar obstacole care pot fi observate de conducător, el trebuig să reducă viteza sau chiar să oprească, pentru a nu pune în pericol siguranţa traficului”, precum şi p. 56 al.2 care prevede ”în cazul virştrii la stînga saiş întoarcerii conducătorul de vehicul trebuie să cedeze trecerea vehiculelor care vin din sens opus şi se vor deplasa înainte sau la dreapta”, fără să se încredinţeze de faptul că manevra nu va crea pericol pentru alţi participanţi la traficul rutier, a ieşit pe contrasens şi a tamponat motoreta model ”Honda CRE 50 HM” n/î xxNUMxx condusă de minorul xxNUMExx, care se deplasa regulamentar în sensul opus al automobilului, pe str. Dubinovschi dinspre str. Unghenilor spre direcţia str. Vlahuţa mun. Bălţi. În urma accidentului rutier, conform raportului de expertiză medico­legală nr. 487D din 17.11.2014 xxNUMExx s­a ales cu leziuni corporale grave, sub formă de traumatism asociat – traumă cranio­cerebrală închisă cu contuzie cerebrală de gr. I, fractură închisă a oaselor antebraţului drept, fractură închisă a osului femoral stîng, multiple excoreaţii pe faţă şi plagă contuză a buzei superioare. Instanţa de fond a pronunţat sentinţa sus indicată. Împotriva sentinţei a declarat recurs [[inculptaul]] xxNUMExx, care solicită casarea sentinţei, cu numirea pedepsei sub formă de 160 ore muncă neremunerată în folosul comunităţii, cu aplicarea art. 79 CP, fără privarea de dreptul de a conduce mijloace de transport. În motivarea recursului invocă, că pe parcursul examinării cauzei vina în săvîrşirea infracţiunii incriminate şi­a recunoscut­o pe deplin, sincer s­a căit în cele întîmplate. Pînă la momentul comiterii acestei crime devieri sau abateri de lege nu a avut, iar după comiterea acestei infracţiuni de asemenea nu a comis crime sau devieri de la lege, inclusiv şi comiterea încălcărilor de ordin contravenţional. Şi­a făcut concluziile necesare în urma comiterii infracţiunii incriminate, s­a corectat şi pe viitor nu va mai comite abateri de lege. Benevol a încheiat pînă la examinarea cauzei penale în instanţa de fond acordul de recunoaştere a vinovăţiei. Este căsătorit şi are la întreţinere un copil minor, iar la moment soţia este însărcinată. Este încadrat în cîmpul muncii şi activează în calitate de şofer, avînd nevoie de permisul de conducere, aceasta este unica lui

[Succeeded / Failed / Skipped / Total] 30 / 34 / 18 / 82:  64%|██████▍   | 64/100 [12:36<07:05, 11.82s/it]

--------------------------------------------- Result 81 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

Prin sentinţa Judecătoriei Soroca sediul Central din 25.07.2017, modificată prin decizia Colegiului penal al Curţii de Apel Bălţi din 22.11.2017 şi încheierea Judecătoriei Soroca sediul Central din 14.12.2018, Revenco Emil ***** a fost condamnat în baza art. 192/1 alin. (2) lit. a), c); art. 186 alin. (2) lit. b), c), d); art. 186 alin. (2) lit. b), c), d); art. 186 alin. (2) lit. b), c), d); art. 186 alin. (2) lit. b), c), d); art. 192/1 alin. (2) lit. a), c); art. 186 alin. (2) lit. b), c), d); art. 186 alin. (2) lit. b), c), d); art. 186 alin. (2) lit. b), c), d); art. 84 alin. (1); art. 84 alin. (4) Cod penal la 4 ani 4 luni închisoare, cu executarea pedepsei în penitenciar de tip semiînchis. Începutul termenului-26.12.2016; Sfârşitul termenului-25.04.2021. La 07.11.2018, condamnatul Revenco Emil s-a adresat cu o cerere privind liberarea condiţionată de pedeapsă înainte de termen, considerând că întruneşte condiţiile prevăzute de art. 91 Cod penal. Prin încheierea Judecătoriei Soroca sediul Central din 01.03.2019 a fost respinsă ca neîntemeiată cererea condamnatului Revenco Emil privind liberarea condiționată de pedeapsă înainte de termen. Împotriva încheierii a depus recurs în termen condamnatul Revenco Emil, prin care își exprimă dezacordul cu încheierea primei instanțe. În motivarea recursului indică, că prima instanță neîntemeiat a respins cererea sa privind liberarea condiţionată de pedeapsă înainte de termen, și astfel solicită admiterea cererea sale în baza art. 91 CP. În şedinţa instanţei de recurs condamnatul şi avocatul ce l-a asistat au susţinut recursul declarat, solicitând admiterea lui pe motivele invocate. Reprezentantul Penitenciarului nr. 6 Soroca, fiind citat în mod legal, în ședința instanței de recurs nu s-a prezentat, totodată, a depus cerere, prin care a solicitat examinarea recursului în lipsa sa. Examinând materialele prezentate, verificând argumentele recurentului în raport cu materialele prezentate, audiind participanţii la proces, Colegiul penal constată că instanţa de fond a pronunţat o hotărâre legală, întemeiată şi motivată, neconstatându-se temei de casare a acesteia, iar în situaţia în care instanţa de fond şi-a motivat decizia luată, permiţând părţilor să utilizeze eficient orice drept de recurs eventual, o curte de apel poate, în principiu, să se mulţumească de a relua motivele jurisdicţiei de primă instanţă (hotărârea CtEDO Garcia Ruiz versus Spania). Astfel, Colegiul penal conchide că recursul este nefondat şi urmează a fi respins. Potrivit prevederilor art. 91 alin. (1) CP, Persoanei care execută pedeapsa cu închisoare i se poate aplica liberarea condiţionată de pedeapsă înainte de termen dacă a realizat programul individual de executare a pedepsei, a reparat integral daunele cauzate de infracţiunea pentru care a fost condamnată, cu excepţia cazului cînd dovedeşte că nu a avut nicio posibilitate să le îndeplinească, şi dacă se constată că corectarea ei este posibilă fără executarea deplină a pedepsei. Persoana poate fi liberată, în întregime sau parţial, şi de pedeapsa complementară. Instanţa de fond întemeiat a dedus, că condamnatul Revenco Emil nu a realizat programul individual de executare a pedepsei și întruneşte condiţiile necesare pentru aplicarea prevederilor art. 91 CP, astfel nu poate fi liberat condiţionat înainte de termen de pedeapsa restantă. Potrivit materialelor


--------------------------------------------- Result 82 ---------------------------------------------
[[0 (72%)]] --> [[[SKIPPED]]]

XXXXXXXXXX, în noaptea spre XXXXXXXXX, urmărind scop de profit, în absenţa a careva persoane şi acţionînd cu convingerea că, cele comise rămîn neobservate, prin forţarea belciugului, a pătruns în barul ­ terasă, ce se află în faţa hotelului „Central”, amplasat în or. Soroca, str. M. Kogîlniceanu 20, care aparţine SC„Sergiu”SRL, de unde intenţionat, a sustras pe ascuns 12 sticle cu bere „Cronenberg” la preţ de 25 lei fiecare, în sumă totală de 300,00 lei, patru sticle cu şampanie „Cricova” la preţ de 100 lei fiecare, în total 400,00 lei, o sticlă cu şampanie „Călăraşi” la preţ de 60 lei, o sticlă cu rachiu „Hortiţa” la preţ de 220,00 lei, o sticlă cu rachiu „Hortiţa” la preţ de 154,00 lei, 300 grame de rachiu „Ruskii Standart” la preţ de 168,00 lei, 750 grame de rachiu „Absolut” la preţ de 345,00 lei, o sticlă cu băutură „Sambuca” la preţ de 350,00 lei, 900 grame de rom „Bacardi” la preţ de 378,00 lei, o sticlă cu whisky la preţ de 200,00 lei, 300 grame de coniac „Regal” la preţ de 210,00 lei, două sticle cu coniac „Călăraşi” la preţ total de 360,00 lei, o sticlă cu coniac „Bardar” la preţ de 350,00 lei, 3 sticle cu coniac „Călăraşi” la preţ de 200,00 lei fiecare, în total 600,00 lei, 300 grame de coniac „Călăraşi” la preţ de 102 lei, 300 grame de coniac „Kvint” la preţ de 108,00 lei, o sticlă cu vin „Buchet Moldavii” la preţ de 120,00 lei, o sticlă cu „Martini” la preţ de 230,00 lei, o sticlă cu gin „Beefeater” la preţ de 300,00 lei, 350 grame de gin la preţ de 175,00 lei, 2 pachete de chipsuri la preţ de 35 lei fiecare, în total 70 lei, 4 pachete de chipsuri la preţ de 25 lei fiecare, la preţ de 100 lei, 2 pachete cu alune „Banzai” la preţ de 15 lei fiecare, în total 30 lei, o sticlă cu coniac „Bardar” la preţ de 220,00 lei, o sticlă cu coniac „Bardar” la preţ de 200,00 lei, cauzînd astfel părţii vătămate o daună în sumă de 5 650,00 lei. Organul de urmărire penală, a calificat acţiunile lui XXXXXXXXXX în baza art. 186 alin. (2) lit. c) Cod penal cu indicii de calificare: furtul, adică sustragerea pe ascuns a bunurilor altei persoane, săvîrşit prin pătrunderea în alt loc pentru depozitare. În şedinţa judiciară inculpatul XXXXXXXXX, a solicitat judecarea cauzei pe baza probelor administrate în faza de urmărire penală, a declarat că, recunoaşte în totalitatea faptele indicate în rechizitoriu şi nu solicită administrarea de noi probe. Sub jurămînt a declarat că, în noaptea spre XXXXXXXXX, fiind în stare de ebrietate alcoolică avansată, a trecut pe lîngă terasa hotelului central din or.Soroca. Acolo, la terasă, lîngă tejgheaua chelnerului este amenajat un depozit, unde se păstrează pe timp de noapte băuturile alcoolice şi alte produse alimentare, ce se vînd la terasă. Acest depozit este închis cu un lacăt, agăţat de belciug. Uşa de la depozit este de lemn. Cînd a trecut pe lîngă terasă, a decis să intre în depozit şi să fure de acolo

[Succeeded / Failed / Skipped / Total] 31 / 34 / 18 / 83:  65%|██████▌   | 65/100 [12:45<06:52, 11.78s/it]

--------------------------------------------- Result 83 ---------------------------------------------
[[0 (94%)]] --> [[1 (65%)]]

Pentru a se pronunţa în sensul celor expuse instanţa de fond a reţinut că xxx, fiind privat de dreptul de a conduce mijloace de transport conform sentinței Judecătoriei raionului Telenești din 12.11.2012 în baza art.264/1 al.1 Cod Penal, fiind în stare de ebrietate și conștientizînd caracterul social­periculos al acțiunilor de conducere a mijlocului de transport în stare de ebrietate și consecințele care pot surveni, la 10.07.2015, în jurul orelor 01.30, conducînd automobilul de model ”Nissan Vaneta” cu număr de înmatriculare xxx în orașul xxx strada xxx, a fost stopat legal de către IIP al Batalionului nr.3, Orhei­Telenești, a INP al MAI, care în timpul verificării actelor a constatat că șoferul nu deține permis de conducere și a fost suspectat de faptul că se află în stare de ebrietate [[alcoolică]], din care motive i­a fost propus să treacă testarea alcoolscopică, în rezultatul căruia s­a constatat că șoferul conducea mijlocul de transport în stare de ebrietate produsă de alcool, cu conținutul de alcool etilic în [[aerul]] expirat de 0,58 mg/l, ceea ce potrivit prevederilor art.134/12 din Codul Penal, se consideră stare de ebrietate alcoolică [[avansată]]. În cadrul ședinței de [[judecată]] [[inculpatul]] xxx a înaintat o cerere, prin care a solicitat judecarea cauzei în baza probelor administrate la etapa urmăririi penale în temeiul art.364/1 CPP, cauza penală fiind judecată în ordinea prevăzută de art.364/1 CPP RM, pe baza probelor administrate în cadrul urmăririi penală. În termen sentinţa a fost atacată cu apel de către inculpatul xxx, care în motivare a invocat că nu este deacord cu sentința instanței de fond și o consideră nelegitimă și neîntemeiată din următoarele motive: În cadrul ședinței de judecată inculpatul xxx a înaintat o cerere, prin care a solicitat judecarea cauzei în baza probelor administrate la etapa urmăririi penale în temeiul art.364/1 CPP, cauza penală fiind judecată în ordinea prevăzută de art.364/1 CPP RM, pe baza probelor administrate în cadrul urmăririi penală. În termen sentinţa a fost atacată cu apel de către inculpatul xxx, care în motivare a invocat că nu este deacord cu [[sentința]] instanței de fond și o consideră nelegitimă și neîntemeiată din următoarele motive: ­infracțiunea de care este învinuit se califică ca infracțiune ușoară, stabilirea unei pedepse sub formă de închisoare este prea aspră, luîndu­se în calcul gradul pericolului social al acestei infracțiuni, examinarea dosarului respectiv a avut loc într­o procedură simplificată conform prevederilor prevăzute de art.364/1 CP, ­judecata la stabilirea pedepsei urma să ia în considerație că el a fost deacord ca să­i fie stabilită o pedeapsă sub formă de muncă neremunerată în folosul comunității, ­consideră nelegitim faptul că judecata a aplicat în privința lui prevederile art.85 CP prin cumul de sentințe, luîndu­se în calcul faptul că el la data de 12.11.2012 a fost condamnat în temeiul art.264/1 al.1 CP fiindu­i stabilită pedeapsă sub formă de muncă neremunerată în folosul comunității, pedeapsă pe care el a ispășit­o pe deplin la data de 10.02.2013, consideră că nelegitim s­a aplicat prevederile art.85 CP pe motivul că el deja a ispășit pedeapsa principală stabilită prin sentința din 12.11.2012, ­prin condamnarea lui la privațiune de libertate au fost traumate șapte

Pentru a se pronunţa în sensul celor expuse instanţa de fond a reţinut că xxx, fiind privat de dreptul de a conduce mijloace de transport conform sentinței Judecătoriei raionului Telenești din 12.11.2012 în baza art.264/1 al.1 Cod Penal, fiind în stare de ebrietate și conștientizînd caracterul social­periculos al acțiunilor de conducere a mijlocului de transport în stare de ebrietate și consecințele care pot surveni, la 10.07.2015, în jurul orelor 01.30, conducînd automobilul de model ”Nissan Vaneta” cu număr de înmatriculare xxx în orașul xxx strada xxx, a fost stopat legal de către IIP al Batalionului nr.3, Orhei­Telenești, a INP al MAI, care în timpul verificării actelor a constatat că șoferul nu deține permis de conducere și a fost suspectat de faptul că se află în stare de ebrietate [[acloolică]], din care motive i­a fost propus să treacă testarea alcoolscopică, în rezultatul căruia s­a constatat că șoferul conducea mijlocul de transport în stare de ebrietate produsă de alcool, cu conținutul de alcool etilic în [[aeurl]] expirat de 0,58 mg/l, ceea ce potrivit prevederilor art.134/12 din Codul Penal, se consideră stare de ebrietate alcoolică [[aavnsată]]. În cadrul ședinței de [[judceată]] [[inuclpatul]] xxx a înaintat o cerere, prin care a solicitat judecarea cauzei în baza probelor administrate la etapa urmăririi penale în temeiul art.364/1 CPP, cauza penală fiind judecată în ordinea prevăzută de art.364/1 CPP RM, pe baza probelor administrate în cadrul urmăririi penală. În termen sentinţa a fost atacată cu apel de către inculpatul xxx, care în motivare a invocat că nu este deacord cu sentința instanței de fond și o consideră nelegitimă și neîntemeiată din următoarele motive: În cadrul ședinței de judecată inculpatul xxx a înaintat o cerere, prin care a solicitat judecarea cauzei în baza probelor administrate la etapa urmăririi penale în temeiul art.364/1 CPP, cauza penală fiind judecată în ordinea prevăzută de art.364/1 CPP RM, pe baza probelor administrate în cadrul urmăririi penală. În termen sentinţa a fost atacată cu apel de către inculpatul xxx, care în motivare a invocat că nu este deacord cu [[snetința]] instanței de fond și o consideră nelegitimă și neîntemeiată din următoarele motive: ­infracțiunea de care este învinuit se califică ca infracțiune ușoară, stabilirea unei pedepse sub formă de închisoare este prea aspră, luîndu­se în calcul gradul pericolului social al acestei infracțiuni, examinarea dosarului respectiv a avut loc într­o procedură simplificată conform prevederilor prevăzute de art.364/1 CP, ­judecata la stabilirea pedepsei urma să ia în considerație că el a fost deacord ca să­i fie stabilită o pedeapsă sub formă de muncă neremunerată în folosul comunității, ­consideră nelegitim faptul că judecata a aplicat în privința lui prevederile art.85 CP prin cumul de sentințe, luîndu­se în calcul faptul că el la data de 12.11.2012 a fost condamnat în temeiul art.264/1 al.1 CP fiindu­i stabilită pedeapsă sub formă de muncă neremunerată în folosul comunității, pedeapsă pe care el a ispășit­o pe deplin la data de 10.02.2013, consideră că nelegitim s­a aplicat prevederile art.85 CP pe motivul că el deja a ispășit pedeapsa principală stabilită prin sentința din 12.11.2012, ­prin condamnarea lui la privațiune de libertate au fost traumate șapte

[Succeeded / Failed / Skipped / Total] 32 / 34 / 18 / 84:  66%|██████▌   | 66/100 [12:53<06:38, 11.72s/it]

--------------------------------------------- Result 84 ---------------------------------------------
[[1 (92%)]] --> [[0 (71%)]]

Prin sentință, Crijanovschi Boris a fost condamnat [[pentru]] [[conducerea]] la data de 22.11.2018 în jurul [[orelor]] 12:50, pe str. Biruinței din localitatea Lipcani, Briceni, a automobilului de model ”*****” cu n/î*****, în stare de ebrietate alcoolică cu grad avansat, fapt confirmat prin rezultatele testării alcoolscopice cu etilotestul ”Drager-Alcotester 8510 RO”, test nr. 1798, conform cărui concentrația vaporilor de alcool în aerul expirat e de 0,80 mg/l, ce în corespundere cu HG RM Nr. 296 din 16.04.2009 pct. (4) lit. b) se atribuie la stare de ebrietate cu grad avansat, respectivele acțiuni fiindu-i încadrate la art. 264/1 alin. (1) Cod penal, cu calificativele conducerea mijlocului de transport de către o persoană care se află în stare de ebrietate alcoolică cu grad avansat. Sentința de condamnare a fost atacată cu recurs în ordinea prevăzută de art. 437 Cod pr. penală de către inculpatul Crijanovschi Boris, care necontestând încadrarea juridică a faptei penale, solicită liberarea de răspunderea penală în temeiul art. 55 Cod penal, cu atragerea la răspundere contravențională sau prin păstrarea pedepsei principale, ne aplicarea potrivit art. 79 alin. (1) Cod penal, a pedeapei complimentare, invocând necesitatea deținerii permisul de conducere, pentru păstrarea locului de muncă la SA” *****”, unde activează în calitate de ajutor de mașinist, salariul rămânând a fi sursa permanentă de venit, necesară pentru întreținerea soției ce se află în concediu de îngrejire a celor doi copii minori, avându-i la întreținere și alți doi copii, care deși sunt maturi își fac studiile, neavând surse personale de venit, ținându-se cont de caracterul faptei imputate ce se califică drept una ușoară, căința sinceră, recunoașterea vinovăției și acceptarea examinării cauzei în baza probelor administrate la faza urmăririi penale, caracteristica pozitivă de la locul de trai, lipsa antecedentelor penale, împrejurări de fapt a cauzei, ce în opinia sa ar permite aplicarea prevederilor art. art. 55 sau 79 alin. (1) Cod penal. Procedura citării legale și actele procesuale preparatorii judecării cauzei în ordine de recurs au fost executate. Inculpatul Crijanovschi Boris, precum și apărătorul S. Culicov ce-i asigură apărarea, au pledat pentru admiterea recursului, solicitând aplicarea cazului din speță a prevederilor art. art. 55 sau 79 Cod penal, prin înlăturarea pedepsei complimentare obligatorii, prevăzută la art. 264/1 alin. (1) Cod penal, permisul de conducere fiindu-i necesar inculpatului, de rând ce activează în calitate de șofer la SA ”*****”, având la întreținere patru copii, dintre care trei sunt minori, fiind unicul întreținător al familiei sale. Procurorul participant Tatiana Ioniță a pledat pentru respingerea recursului ca fiind nefondat, cu menținerea fără modificări a sentinței judecătorești pe care o consideră legală și întemeiată, în cauză fiind lipsa circumstanțelor ce ar permite aplicarea în privința inculpatului a prevederilor art. art. 55 sau 79 alin. (1) Cod penal, reieșind din interdicțiile stabilite la art. 24 Cod penal. Verificând temeinicia argumentelor formulate de recurent în raport cu materialele cauzei penale, ascultând pledoariile participanților la proces, Colegiul în corespundere cu art. 449 alin. (1) pct. 1) lit. a) Cod pr. penală va dispune respingerea recursului ca fiind nefondat, păstrând fără modificări soluția judiciară pe care o consideră întemeiată. În motivarea concluziei adoptate, Colegiul

Prin sentință, Crijanovschi Boris a fost condamnat [[pnetru]] [[codnucerea]] la data de 22.11.2018 în jurul [[oreolr]] 12:50, pe str. Biruinței din localitatea Lipcani, Briceni, a automobilului de model ”*****” cu n/î*****, în stare de ebrietate alcoolică cu grad avansat, fapt confirmat prin rezultatele testării alcoolscopice cu etilotestul ”Drager-Alcotester 8510 RO”, test nr. 1798, conform cărui concentrația vaporilor de alcool în aerul expirat e de 0,80 mg/l, ce în corespundere cu HG RM Nr. 296 din 16.04.2009 pct. (4) lit. b) se atribuie la stare de ebrietate cu grad avansat, respectivele acțiuni fiindu-i încadrate la art. 264/1 alin. (1) Cod penal, cu calificativele conducerea mijlocului de transport de către o persoană care se află în stare de ebrietate alcoolică cu grad avansat. Sentința de condamnare a fost atacată cu recurs în ordinea prevăzută de art. 437 Cod pr. penală de către inculpatul Crijanovschi Boris, care necontestând încadrarea juridică a faptei penale, solicită liberarea de răspunderea penală în temeiul art. 55 Cod penal, cu atragerea la răspundere contravențională sau prin păstrarea pedepsei principale, ne aplicarea potrivit art. 79 alin. (1) Cod penal, a pedeapei complimentare, invocând necesitatea deținerii permisul de conducere, pentru păstrarea locului de muncă la SA” *****”, unde activează în calitate de ajutor de mașinist, salariul rămânând a fi sursa permanentă de venit, necesară pentru întreținerea soției ce se află în concediu de îngrejire a celor doi copii minori, avându-i la întreținere și alți doi copii, care deși sunt maturi își fac studiile, neavând surse personale de venit, ținându-se cont de caracterul faptei imputate ce se califică drept una ușoară, căința sinceră, recunoașterea vinovăției și acceptarea examinării cauzei în baza probelor administrate la faza urmăririi penale, caracteristica pozitivă de la locul de trai, lipsa antecedentelor penale, împrejurări de fapt a cauzei, ce în opinia sa ar permite aplicarea prevederilor art. art. 55 sau 79 alin. (1) Cod penal. Procedura citării legale și actele procesuale preparatorii judecării cauzei în ordine de recurs au fost executate. Inculpatul Crijanovschi Boris, precum și apărătorul S. Culicov ce-i asigură apărarea, au pledat pentru admiterea recursului, solicitând aplicarea cazului din speță a prevederilor art. art. 55 sau 79 Cod penal, prin înlăturarea pedepsei complimentare obligatorii, prevăzută la art. 264/1 alin. (1) Cod penal, permisul de conducere fiindu-i necesar inculpatului, de rând ce activează în calitate de șofer la SA ”*****”, având la întreținere patru copii, dintre care trei sunt minori, fiind unicul întreținător al familiei sale. Procurorul participant Tatiana Ioniță a pledat pentru respingerea recursului ca fiind nefondat, cu menținerea fără modificări a sentinței judecătorești pe care o consideră legală și întemeiată, în cauză fiind lipsa circumstanțelor ce ar permite aplicarea în privința inculpatului a prevederilor art. art. 55 sau 79 alin. (1) Cod penal, reieșind din interdicțiile stabilite la art. 24 Cod penal. Verificând temeinicia argumentelor formulate de recurent în raport cu materialele cauzei penale, ascultând pledoariile participanților la proces, Colegiul în corespundere cu art. 449 alin. (1) pct. 1) lit. a) Cod pr. penală va dispune respingerea recursului ca fiind nefondat, păstrând fără modificări soluția judiciară pe care o consideră întemeiată. În motivarea concluziei adoptate, Colegiul

[Succeeded / Failed / Skipped / Total] 32 / 35 / 18 / 85:  67%|██████▋   | 67/100 [13:07<06:27, 11.75s/it]

--------------------------------------------- Result 85 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

(Cauza penală a parvenit în instanţa de fond la 19.06.2014) La 22.11.201xxxxAPARTxxxx în jurul orei 2200 inculpaţii xxxxNUMExxxx şi xxxxNUMExxxx N , acţionînd împreună şi de comun acord, aflîndu­se în faţa disco clubului „Scvajina” din or. Soroca, avînd intenţie unică de a sustrage în mod deschis bunurile altei persoane, i­a urmărit pe cet. xxxxNUMExxxx şi G A care se întorceau de la disco clubul „Scvajina” la domiciliu şi profitînd de faptul că în preajmă nu se aflau alte persoane, pe str. Alecsandri din or. Soroca, aplicînd violenţă nepericuloasă pentru viaţă şi sănătate, i­a doborît la pămînt, iar ulterior cînd victimele erau neutralizate au sustras în mod deschis de la cet. xxxxNUMExxxx un telefon mobil de model „Orange” în preţ de 1118 lei precum şi mijloace băneşti în sumă de 2000 ruble ruseşti echivalent 792,2 lei, iar de la cet. G A au sustras un telefon mobil de model „Samsung” în preţ de 200 lei şi mijloace băneşti în sumă de 260 lei precum şi paşaportul pe numele său, după aceea au fugit într­o direcţie necunoscută. Astfel, în rezultatul sustragerii cet. xxxxNUMExxxx i­a fost cauzată o pagubă materială considerabilă în sumă de 1910,2 lei, iar cet. G A în sumă de 460 lei. Organul de urmărire penală a încadrat faptele inculpaţilor xxxxNUMExxxx şi xxxxNUMExxxx Nicolae în baza prevederilor art. 187 alin. (2) lit. b), e) şi f) Cod penal, cu indicii de calificare: jaf, adică sustragerea deschisă a bunurilor altei persoane, săvârşită de mai multe persoane, cu aplicarea violenţei nepericuloase pentru viaţa sau sănătatea persoanei, cu cauzarea de daune în proporţii considerabile. Pînă la începerea cercetării judecătoreşti inculpaţii xxxxNUMExxxx şi xxxxNUMExxxx Nicolae au solicitat prin înscris autentic ca judecata să aibă loc pe baza probelor administrate în faza de urmărire penală, pe care le cunosc şi asupra cărora nu au obiecţii, indicînd că recunosc săvîrşirea faptelor indicate în rechizitoriu. Prin încheierea instanţei de judecată s­a admis cererile inculpaţilor privind judecarea cauzei pe baza probelor administrate în faza de urmărire penală. În şedinţă judiciară inculpaţii xxxxNUMExxxx şi xxxxNUMExxxx N sub jurămînt au recunoscut săvîrşirea faptelor indicate în rechizitoriu şi au declarat instanţei că se căiesc sincer de cele săvîrşite şi pe viitor nu vor mai comite asemenea fapte. Pe lîngă faptul că inculpaţii xxxxNUMExxxx şi xxxxNUMExxxx N şi­au recunoscut vina, vinovăţia acestora este dovedită pe deplin şi prin cumulul de probe prezentate de către procuror, şi anume: ­ procesul­verbal de audiere a părţii vătămate xxxxNUMExxxx, care a declarat că la data de 22.11.201xxxxAPARTxxxx, aflîndu­se în stare de ebrietate alcoolică avansată împreună cu prietenii G A şi încă o persoană numele şi familia căruia nu o cunoaşte, în timp ce mergeau din direcţia disco clubului „SCVAJINA” situat în or. Soroca, spre domiciliul personal, ajungând pe str.Vasile Alexandri în apropierea sediului serviciului „Paza de Stat”, au fost ajunşi din urmă de aproximativ trei persoane necunoscute, care l­au bătut pe el şi pe G A . Cîte persoane au fost şi cine sunt ele xxxxNUMExxxx nu ţine minte din motiv că nu le­a văzut fiindcă afară era întuneric. După ce a fost lovit şi se afla la

[Succeeded / Failed / Skipped / Total] 32 / 36 / 18 / 86:  68%|██████▊   | 68/100 [13:19<06:16, 11.76s/it]

--------------------------------------------- Result 86 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

P.xxxxNUMExxxx, la 27 decembrie 2013, în jurul orelor 0820, în timp ce se afla în sediul Secției de Evidență și Documentare a Populației Soroca, împreună cu cunoscuta sa C.O., intenționat, cu scopul de a dobîndi bani prin înșelăciune și abuz de încredere, a primit de la ultima mijloace bănești în sumă de 1520 lei și buletinul de identitate pe numele acesteia, sub pretextul de a o ajuta la perfectarea pașaportului, pe care i­a însușit, iar buletinul de identitate l­a aruncat la ieșirea din Secția de Evidență și Documentare a Populației Soroca, astfel, cauzîndu­i părții vătămate o pagubă materială considerabilă. Pînă la începerea cercetării judecătoreşti inculpatul P.A. a solicitat prin înscris autentic ca judecata să aibă loc pe baza probelor administrate în faza de urmărire penală, pe care le cunoaşte şi asupra cărora nu are obiecţii, indicînd că recunoaşte săvîrşirea faptelor indicate în rechizitoriu. Prin încheierea instanţei de judecată s­a admis cererea inculpatului privind judecarea cauzei pe baza probelor administrate în faza de urmărire penală. În şedinţă judiciară inculpatul P. A.sub jurămînt a recunoscut săvîrşirea faptelor indicate în rechizitoriu şi a declarat instanţei că la 27 decembrie 2013, în jurul orelor 0800, s­a întîlinit cu C. O., cu care convenise anterior de a se prezenta împreună la Secția de Evidență și Documentare a Populației Soroca, pentru a­i ajuta la perfectarea pașaportului. La ora stabilită s­au prezentat în biroul 5 al secției, însă lui C. O. i­a fost refuzat în perfectarea pașaportului pe motiv că nu a prezentat certificatele de naștere a copiilor. În acel moment i­a venit ideea de a însuși de la C. O., suma de 1520 lei, care constituia taxa pentru perfectarea pașaportului. I­a propus O.să­i transmită banii și buletinul de identitate sub pretextul de a o ajuta la perfectarea pașaportului, ultima căzînd de acord. După ce C. O. i­a transmis banii și buletinul de identitate, a intrat în sediul SEDP Soroca, unde a lăsat pe scări buletinul de identitate, apoi a ieșit pe altă ușă pentru a nu fi văzut de C. O. Banii i­a cheltuit pentru necesitățile personale. A mai declarat că a restituit paguba materială în mărime de 1500 lei. Vina inculpatului P. A. în comiterea faptei prejudiciabile mai este confirmată prin: procesul­verbal cu declaraţiile părții vătămate C. O. (f.d. 10­11), care a declarat că, la 26 decembrie 2013, în jurul orelor 0800, în regiunea parcului central din or. Soroca, a făcut cunoștință cu un băiat pe nume G., căruia în timpul discuției i­ a comunicat că intenționează să plece în F. Rusă, dar nu deține pașaport. Tot atunci, G. i­a propus să meargă la Secția de Evidență și Documentare a Populației Soroca, ca să discute cu anumite persoane, pentru a o ajuta la perfectarea pașaportului în decurs de o zi. La secție a fost informată că pentru perfectarea pașaportului este necesar de a prezenta actele necesare. A doua zi, în jurul orelor 0800, s­a întîlnit cu G. în fața sediului Secției de Evidență și Documentare a Populației Soroca și împreună au mers în biroul nr. 5, unde a fost înștiințată că în perfectarea pașaportului îi este refuzat

[Succeeded / Failed / Skipped / Total] 32 / 37 / 18 / 87:  69%|██████▉   | 69/100 [13:26<06:02, 11.69s/it]

--------------------------------------------- Result 87 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

În gestiunea judecătoriei Șoldănești a parvenit spre examinare cauza penală privind învinuirea lui xxx pe art. 217 alin. (1) Cod penal, fiind repartizată aliatoriu, în ordinea art. 344 Cod pr. penală judecătorului xxx, care la data de 31.05.2016 pînă la începerea şedinţei de judecată, și­a declarat abținerea de la examinarea ei, pe motiv, că anterior la data de XXXXXXXXX în calitate de judecător de instrucție, a examinat în cadrul cauzei contravenționale în privința acestui pe art. 87 Cod Contravențional, demerul procurorului privind autorizarea efectuării percheziției la domiciliul, în cadrul cărei au fost depistate substanțe narcotice, ce au servit temei pentru începerea urmăririi penale cu atragerea lui xxx la răspunderea penală, referitor la care și s­a formulat abținerea pe motiv de incompatibilitate în temeiul art. 33 alin. (3) Cod pr. penală. Verificînd temeinicia motivelor pentru care a fost declarată abţinerea în raport cu materialele cauzei, Colegiul în corespundere cu art. art. 33­35 Cod pr. penală, conchide posibilitatea admiterii declarației de abținere formulată de către judecătorul xxx, incompatibilitatea soluționării cauzei fiind determină de prevederile art. 33 alin. (3) Cod pr. penală, potrivit căror ”judecătorul nu poate participa la o nouă judecare a cauzei atât în prima instanță, cât și pe cale ordinară sau extraordinară de atac și urmează a fi recuzat în cazul.... participării în aceeași cauză în calitate de judecător de instrucție”. Astfel, că întru respectarea principiului imparțialității judecătorului la judecarea cauzei penale, Colegiul prin admiterea declarației de abținere depusă de judecătorul xxx, va dispune remiterea cauzei penale în privința lui xxx pe art. 217 alin. (1) Cod penal, pentru judecare în fond judecătoriei xxx ca instanța egală în grad. Reieșind din cele expuse mai sus și în corespundere cu art. 35 Cod pr. penală Colegiul,­

[Succeeded / Failed / Skipped / Total] 32 / 38 / 19 / 89:  70%|███████   | 70/100 [13:40<05:51, 11.72s/it]

--------------------------------------------- Result 88 ---------------------------------------------
[[1 (97%)]] --> [[[FAILED]]]

Potrivit sentinței xxxxNUMExxxx a fost condamnată pentru, că exercitând funcția de contabil al Asociației de Economii și Împrumut a Cetățenilor (AEÎC) din xxxxORAS_SATxxxx, ce activează în baza licenței de categoria ”A” eliberată la 19.03.2003, prin înțelegere prealabilă cu directorul executiv al AEÎC din xxxxORAS_SATxxxx, xxxxNUMExxxx, acționând în comun acord și urmărind același rezultat infracțional, folosind situația de serviciu, urmărind scop de profit, nefiind în drept să accepte depuneri de economii în baza art. 7 alin. (1) și art. 29 alin. (2) al Legii asociațiilor de economii și împrumut nr. 139 din 21.06.2007, prin înșelăciune manifestată în promisiunea de a plăti o dobândă în mărime de 18% anual din suma de bani depusă în asociație, creând fictiv caracterul legitim al luării bunurilor prin folosirea chitanțelor de încasare false din 15.10.2008 și 28.10.2008 precum și a contractului de depunere fals nr. 4 din 15.10.2008, intenționat, în executarea aceleiași intenții infracționale a dobândit ilicit de la Jorneac Nonna la 15.10.2008 suma de 2 550 dolari SUA, echivalent a 26 261, 43 lei iar la 28.10.2008 suma de 500 dolari SUA, echivalent a 5 168,5 lei, neavând intenția de a­și onora angajamentul asumat în momentul intrării în posesie a banilor transmiși, cauzând părții vătămate daune în proporții considerabile în sumă de 31 429,9 lei MDL. Tot ea, aproximativ în luna decembrie a anului 2006, exercitând funcția de contabil al AEÎC din xxxxORAS_SATxxxx, prin înțelegere prealabilă cu directorul executiv al AEÎC din xxxxORAS_SATxxxx, Cociuc Parascovia, acționând în comun și urmărind același rezultat infracțional, folosind situația se serviciu, urmărind un scop de profit, prin înșelăciune manifestată în promisiunea de a plăti o dobândă în mărime de 16,5% anual din suma de bani depusă în asociație, intenționat a dobândit ilicit de la Rusu Valentina 1 278 lei MDL, fără a perfecta un contract de depunere și a înregistra suma respectivă în casieria asociației, neavând intenția de a­și onora angajamentul asumat în momentul intrării în posesie a banilor transmiși, cauzând astfel părții vătămate o daună în proporții considerabilă. Tot ea, aproximativ în luna iunie a anului 2010, exercitând funcția de contabil al AEÎC din xxxxORAS_SATxxxx, prin înțelegere prealabilă cu directorul executiv al AEÎC din xxxxORAS_SATxxxx, xxxxNUMExxxx, acționând în comun și urmărind același rezultat infracțional, folosind situația de serviciu, urmărind un scop de profit, prin înșelăciune manifestată în promisiunea de a plăti o dobândă în mărime de 18 % anual din suma de bani depusă în asociație, intenționat a dobândit ilicit de la Rusu Valentina 3 400 lei MDL, fără a perfecta un contract de depunere și a înregistra suma respectivă în casieria asociației, neavând intenția de a­și onora angajamentul asumat în momentul intrării în posesie a banilor transmiși, cauzând astfel părții vătămate o daună în proporții considerabilă. Tot ea, exercitând funcția de contabil al AEÎC din xxxxORAS_SATxxxx, ce activează în baza licenței de categoria A eliberată la 19.03.2003, prin înțelegere prealabilă cu directorul executiv al AEÎC din xxxxORAS_SATxxxx, xxxxNUMExxxx, acționând în comun și urmărind același rezultat infracțional, folosind situația de serviciu, urmărind un scop de profit, nefiind în drept să accepte depuneri de economii în baza art. 7 alin. (1)


--------------------------------------------- Result 89 ---------------------------------------------
[[0 (62%)]] --> [[[SKIPPED]]]

Prin sentința Judecătoriei Cahul, sediul central din 15 decembrie 2017, Vulpe Constantin a fost recunoscut vinovat de săvârșirea infracțiunii prevăzute de art. 156 Cod penal, fiindu-i stabilită pedeapsa sub formă de închisoare pe un termen de 02 ani și 06 luni, cu executarea pedepsei în penitenciar de tip semiînchis. Termenul executării pedepsei fiind necesar de a fi calculat începând cu data emiterii sentinței, adică 15 decembrie 2017, cu includerea în termenul executării pedepsei, perioada aflării în stare de reținere – arest preventiv și arest la domiciliu de la 22 iulie 2016 până la 18 septembrie 2016. La fel, i-a fost aplicată inculpatului măsura de reprimare arestul preventiv, care se execută imediat în sala de ședințe, până la intrarea sentinței în vigoare. Totodată, a fost admisă parțial acțiunea civilă, cu încasarea de la Vulpe Constantin în beneficiul părții civile Burbențeva Mariana, cu titlu de prejudiciu moral suma de 100 000 lei și suma de 4 000 lei cu titlu de cheltuieli de asistență juridică, în rest acțiunea civilă a fost respinsă ca neîntemeiată. De asemenea, s-a hotărât încasarea de la Vulpe Constantin suma de 80 lei, cu titlu de cheltuieli de judecată, în rest cererea acuzatorului de stat privind încasarea de la inculpat în beneficiul statului a cheltuielilor de judecată, a fost respinsă ca neîntemeiată. Cauza penală în prima instanță a fost examinată cu participarea inculpatului Vulpe Constantin, care a indicat că nu se consideră vinovat de moartea lui Ghencea și consideră că nu trebuie să recupereze prejudiciul cauzat. Pentru a pronunța sentința instanța de fond a reținut că, lui Vulpe Constantin i se incriminează că el, la 22.07.2016 aproximativ la ora 04:00, aflându-se pe teritoriul *****, depozitul frigorific din *****, în urma unui conflict apărut subit între dânsul și Ghencea Petru a.n.*****, locuitor al ***** cu scopul cauzării leziunilor corporale, i-a aplicat ultimului multiple lovituri cu mâinile și picioarele pe diferite părți ale corpului cauzându-i lui Ghencea Petru vătămări corporale „grave” periculoase pentru viață, manifestate prin: traumă contuză a toracelui, fractură costale directe, complete multiple bilaterale cu hemoragii în țesuturile moi adiacente, lezarea vaselor intercostale, lezarea pleurei parientale, lezarea ambilor pulmoni, hemotorace bilateral, pneumotorace bilateral. Plaga contuza pe cap, cu hemoragii în țesuturile moi adiacente, excoriații pe umeri, excoriații profunde pe ambele coapse, produse la acțiunea traumatică cu obiect contondent dur, au legătură directă cu decesul. Acțiuni, care au fost calificate de organul de urmărire penală în baza art. 151 alin. (4) Cod penal, conform indicilor: ”vătămarea intenționată gravă a integrității corporale sau a sănătății, care a provocat decesul victimei”. Nefiind de acord cu această sentință, la data de 18 decembrie 2017 procurorul în Procuratura r. Cahul Țurcanu Alexandru a depus cerere de apel, prin care solicită admiterea apelului și casarea parțială a sentinței instanței de fond și pronunțarea unei noi hotărîri, prin care Vulpe Constantin să fie recunoscut vinovat de comiterea infracțiunii prevăzute de art. 151 alin. (4) Cod penal, fiindu-i stabilită pedeapsa sub formă de închisoare pe un termen de 12 ani, cu executarea acesteia în penitenciar de tip închis și admiterea integrală a acțiunii civile. În motivarea apelului a

[Succeeded / Failed / Skipped / Total] 32 / 39 / 19 / 90:  71%|███████   | 71/100 [13:53<05:40, 11.74s/it]

--------------------------------------------- Result 90 ---------------------------------------------
[[0 (98%)]] --> [[[FAILED]]]

Inculpatul xxxxNUMExxxx, în luna octombrie 2013, data i ora concretă nu a fost posibil de stabilit, aflîndu­se în gospodăria proprie din s.Cobîlea, r­nul Şoldăneşti, cu scopul de a­şi satisface pofta sexual, a atras­o pe minora xxxxNUMExxxxaleria / născută la 07.03.2006 /, despre care ştia cu certitudine, că nu a atins vîrsta de 14 ani, în şopronul cu fîn, unde prin constrîngere fizică şi psihică, a dezbrăcat­o, propunîndu­i suma de 5 lei, apoi a încercat să săvîrşească cu aceasta un raport sexual, fără a­i cauza careva vătămări corporale, dar din cauze independente de voinţa sa, nu şi­a dus intenţia pînă la sfîrşit, deoarece a fost descoperit de catre fratele victimei minore xxxxNUMExxxxaleria ­ xxxxNUMExxxxrigore. xxxxNUMExxxx în cadrul urmăririi penale, fiind audiat în calitate de bănuit / f.d.40/ nu a recunoscut bănuiala şi a explicat, că chear dacă nu venea fratele minorei – Grigore, oricum cu ea nu putea să aibă vreun raport sexual, din motiv, că de 6 ani e impotent. Iniţial, în calitate de învinuit E.Lefter /f.d.45/ la 23.12.2013 a recunoscut vinovăţia incriminată, declarînd, că susţine depoziţiile în calitate de bănuit, iar ulterior, la 12.05.2014 fiindu­i înaintată învinuirea, în prezenţa avocatului V.Furdui a declarat, că nu recunoaşte vina, explicînd, că în luna octombrie 2013 a servit vin cu bunelul minorei xxxxNUMExxxxaleria, apoi ultima a cerut mere şi după ce i­a dat mere, ea i­a spus „Dă­mi să văd cucul”, iar el a întrebat­o „ce să vezi numai pielea ?” şi tot atunci a venit fratele mniorei – Grigore, care s­a exprimat „V­am prins”, iar după un timp a venit Valeria şi a cerut 5 lei pentru ţigări moşneagului. / f.d. 79­80 /. La 24.03.2014 victima minoră ­ xxxxNUMExxxxaleria Valeriu / născută la 07.03.2006 /, fiind audiată în cadrul urmăririi penale la judecătorul de instrucţie în condiţii speciale, potrivit art.1101 CPP, a declarat doar, că îl cunoaşte pe nanu Efim din s.Cobîlea şi el nu venea la ei / f.d. 88 /, iar psihopedagogul în cadrul şedinţei a declarat, că e imposibil de a fi audiată la moment, deoarece fetiţa s­a blocat în comunicare şi şi­a schimbat brusc comportamenul. Concomitent, din răspunsul CNPAC din 12.06.2014, adresat Procuraturii Şoldăneşti, rezultă că evaluarea psihologică cu minora V.Stancov nu a avut loc, deoarece copilul nu a povestit nimic despre situaţia suspectă de abuz sexual, refuzînd să discute despre subiectul dat. Din aceste considerente, instanţa de judecată, potrivit prevederilor art.371 alin.(1)1 CPP, a considerat că victima minoră necesită a fi audiată în instanţa de judecată în lipsa inculpatului E.Lefter. Astfel, în cadrul cercetării judecătorești victima minoră ­ xxxxNUMExxxxaleria a declarat, că are 8 ani și învață în clasa 1­a la gimnaziul din s.Şestaci, r­l Şoldăneşti. Mai are un frate mai mare Grişa, care învaţă în clasa IV. Omul care stătea pe scaun în sala de judecată, este nanu Efim, dar familia nu o cunoaște şi el locuiește în vecinătate cu dînșii în s.Cobîlea . Pe soţia lui nanu Efim o cheamă nana Raia şi nu au nici un copil. Din anul trecut locuiesc în s.Şestaci. În perioada cînd locuiau în s.Cobîlea nanu Efim cu nana Raia veneau

[Succeeded / Failed / Skipped / Total] 32 / 40 / 19 / 91:  72%|███████▏  | 72/100 [14:07<05:29, 11.77s/it]

--------------------------------------------- Result 91 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Lenţa Daniel Eugeniu, la 15.07.2018, în jurul orelor 03:30, dispunând de permis de conducere cu eliberat de autorităţile din SUA, cu seria DL F7412911 cu termen de valabilitate pînă la 19.06.2020 pentru categoria „CMl” , după ce a consumat băuturi alcoolice, ignorând şi încălcând flagrant prevederile art.14 lit.a) din Regulamentul Circulaţiei Rutiere aprobat prin Hotărârea Guvernului nr.357 din 13.05.2009, potrivit căruia „conducătorului de vehicul îi este interzis: a) să conducă vehiculul în stare de ebrietate, sub influenţa drogurilor sau altor substanţe contraindicate ”, aflându-se în stare de ebrietate cu grad avansat, a urcat la volanul automobilului de model „Toyota Auris” cu n/î AGZ 464 şi conducîndu- 1 pe str.Independenţii din mun.Soroca, în timpul deplasării a fost stopat pentru verificare şi control de către echipajul poliţiei de patrulare rutieră, unde fiind suspectat că a consumat băuturi alcoolice şi se află în stare de ebrietate, la solicitarea colaboratorilor de poliţie a fost supus testării alcoolscopice cu alcooltestul „Drager 8510 RO”, în urma cărui fapt, potrivit extrasului de tichet- chitanţier „Drager” test nr.7218 din 15.07.2018, ora 03:30 D, s-a stabilit că în aerul expirat de către conducătorul auto Lenta Daniei a fost depistată concentraţia vaporilor de alcool în mărime de 0,54 mg/L, ceia ce constituie stare de ebrietate alcoolică cu grad avansat. În conformitate cu prevederile art.13412 alin.(3) din Codul Penai, prin „stare de ebrietate cu grad avansat ” se înţelege starea persoanei care are concentraţia de alcool în sânge de la 0,5 g/1 şi mai mult sau concentraţia vaporilor de alcool în aerul expirat de la 0,3 mg/1 si mai mult. Inculpatul Lenţa Daniel Eugeniu, fiind citat legal cu aviz de recepție despre data, locul şi ora examinării cauzei în şedinţă judiciară nu s-a prezentat pentru data de 07.08.2018 ora 1500, 04.10.2018 ora 0830, 15.11.2018 ora 1330, 15.12.2018 ora 0900, 26.02.2019 ora 1100. Nu a putut fi executată nici ordonanța de aducere silită în privinţa inculpatului din care considerente Lenţa Daniel Eugeniu, a fost anunţat în căutare cu obligarea prezentării informaţiei despre intentarea dosarului de căutare al acestuia. Ulterior inculpatul sa prezentat în instanță fiind înștiințt legal consemnînd dovada de primire, însă la ședința de judecată din 09.04.2019 la fel nu s-a prezentat. Circumstanţele enunţate au fost apreciate ca probe verosimile că, persoana pusă sub învinuire şi în privinţa căreia cauza a fost trimisă în judecată, a renunţat în mod expres la exercitarea dreptului său de a apărea în faţa instanţei şi de a se apăra personal, precum şi se sustrage de la judecată, în conformitate cu art. 321 alin. (2) pct. 1) şi alin. (6) CPP, instanţa de judecată a dispus judecarea cauzei în lipsa acestuia. Fiind audiat în cadrul ședinței judiciare, martorul Nastas Mihail, a declarat instanței că, la data de 15.07.2019, în timp ce se afla în serviciu împreună cu Mazniuc D., pe la orele 0300 pe srt. Independenței la intersecție cu str. I. Creangă din mun. *****, a fost stopat automobilul de model Toyota Auris, în urma verificării actelor s-a stabilit că, Lența Daniel era conducător și din cavitatea bucală a ultimului mirosea a alcool. Fiind testat cu alcotestul Draiger,

[Succeeded / Failed / Skipped / Total] 33 / 40 / 20 / 93:  73%|███████▎  | 73/100 [14:15<05:16, 11.72s/it]

--------------------------------------------- Result 92 ---------------------------------------------
[[0 (81%)]] --> [[1 (59%)]]

Prin sentinţa Judecătoriei Bălţi din 17.02.2012 xxNUMExx a fost absolvită de răspundere penă prevăzută de art. 42 al. 5, 152 CP în privinţa acesteia fiind aplicate măsuri de constrîngere cu caracter medical într­o instituţie psihiatriă cu supreveghere obişnuită. La data de 09.06.2015, directorul interimar al Spitalului de Psihiatrie Bălţi s­a adresat cu propunerea privind prelungirea termenului de aplicare a măsurilor de constrîngere cu caracter medical, cu supraveghere obişnuită în privinţa pacientului xxNUMExx, a.n. xxDATAxx. Conform actului de expertiză medico­psihiatrică din 08.06.2015 a comisiei de profil, se recomandă prelungirea termenului de aplicare a măsurilor de constrîngere cu caracter medical în privinţa alienatei xxNUMExx, luînd în consideraţie starea sănătăţii acesteia. Prin încheierea Judecătoriei Bălţi din 29.06.2015, a fost admis demersul instituţiei medicale privind prelungirea termenului de aplicare a măsurilor de constrîngere cu caracter medical în privinţa lui xxNUMExx, fiind prelungit termenul de aplicare a măsurilor de constrîngere cu caracter medical cu regim obişnuit de supraveghere în privinţa lui xxNUMExx.. Nefiind de acord cu încheierea în cauză, avocatul N. Uncu a atacat­o cu recurs, prin care solicită casarea încheierii, cu dispunerea rejudecării cauzei în instanţa de fond, pentru administrarea de probe suplimentare. În motivarea recursului invocă, că instanţa de fond nu a luat în consideraţie că bolnavei xxNUMExx prin sentinţa din 17.02.2012 i­au fost aplicate măsuri de constrîngere cu carcater medical, adică [[pînă]] la momentul de faţă este un termen de mai mult de 4 ani, ce denotă faptul că bolnava timp de 4 ani în instituţia psihiatrică în care se află, ar fi primit asistenţa psihiatrică necesară, pentru a se ameliora situaţia şi a se însănătoşi. Indică, că instanţa de judecată nu a constatat faptul că [[bolnava]] xxNUMExx suferă de tulburări psihice grave şi totodată condiţionează un pericol pentru sine şi pentru cei din jur, sau s­a însănătoşit sau a survenit o ameliorare considerabilă şi stabilă a stării psihice a bolnavului, deoarece lipseşte în acest sens un raport psihiatric, ultimul fiind datat din 07.06.2011. Astfel, nu există un raport psihiatric al comisiei de medici psihiatri cu o argumentare în sens că, conform examenului psihiatric, s­au constatat la bolnav: tulburări psihice grave care condiţionează: a) pericolul nemijlocit pentru sine sau pentru cei din jur; b) prejudiciul grav sănătăţii sale dacă nu i se va acorda asistenţă psihiatrică; şi datele examenului psihiatric privind sănătatea mentală a persoanei examinate, conform documentaţiei medicale a acestuia. Avocatul care a reprezentat interesele lui xxNUMExx. în şedinţa instanţei de recurs a solicitat admiterea recursului din motivele invocate, cu remiterea cauzei la rejudecare pentru a fi efectuată expertiza psihiatrică a persoanei. În şedinţa de judecată procurorul participant a pledat pentru respingerea recursului ca fiind nefondat, cu menţinerea încheierii instanţei de fond. Reprezentantul Spitalului de Psihiatrie Bălți I. Dabija a solicitat respingerea recursului, cu menţinerea încheierii judecătoreşti, deoarece xxNUMExx. necesită în continuare să primească tratament. Verificând argumentele recurentului în raport cu materialele prezentate, cu cadrul legal existent, ascultînd opiniile participanţilor la proces, Colegiul penal vine la concluzia, că recursul urmează a fi respins ca nefondat. Potrivit prevederilor art.449 al.(1) pct.1) lit.a) CPP, judecînd recursul, instanța respinge recursul, menținînd hotărîrea atacată, dacă recursul este

Prin sentinţa Judecătoriei Bălţi din 17.02.2012 xxNUMExx a fost absolvită de răspundere penă prevăzută de art. 42 al. 5, 152 CP în privinţa acesteia fiind aplicate măsuri de constrîngere cu caracter medical într­o instituţie psihiatriă cu supreveghere obişnuită. La data de 09.06.2015, directorul interimar al Spitalului de Psihiatrie Bălţi s­a adresat cu propunerea privind prelungirea termenului de aplicare a măsurilor de constrîngere cu caracter medical, cu supraveghere obişnuită în privinţa pacientului xxNUMExx, a.n. xxDATAxx. Conform actului de expertiză medico­psihiatrică din 08.06.2015 a comisiei de profil, se recomandă prelungirea termenului de aplicare a măsurilor de constrîngere cu caracter medical în privinţa alienatei xxNUMExx, luînd în consideraţie starea sănătăţii acesteia. Prin încheierea Judecătoriei Bălţi din 29.06.2015, a fost admis demersul instituţiei medicale privind prelungirea termenului de aplicare a măsurilor de constrîngere cu caracter medical în privinţa lui xxNUMExx, fiind prelungit termenul de aplicare a măsurilor de constrîngere cu caracter medical cu regim obişnuit de supraveghere în privinţa lui xxNUMExx.. Nefiind de acord cu încheierea în cauză, avocatul N. Uncu a atacat­o cu recurs, prin care solicită casarea încheierii, cu dispunerea rejudecării cauzei în instanţa de fond, pentru administrarea de probe suplimentare. În motivarea recursului invocă, că instanţa de fond nu a luat în consideraţie că bolnavei xxNUMExx prin sentinţa din 17.02.2012 i­au fost aplicate măsuri de constrîngere cu carcater medical, adică [[pnîă]] la momentul de faţă este un termen de mai mult de 4 ani, ce denotă faptul că bolnava timp de 4 ani în instituţia psihiatrică în care se află, ar fi primit asistenţa psihiatrică necesară, pentru a se ameliora situaţia şi a se însănătoşi. Indică, că instanţa de judecată nu a constatat faptul că [[bolnvaa]] xxNUMExx suferă de tulburări psihice grave şi totodată condiţionează un pericol pentru sine şi pentru cei din jur, sau s­a însănătoşit sau a survenit o ameliorare considerabilă şi stabilă a stării psihice a bolnavului, deoarece lipseşte în acest sens un raport psihiatric, ultimul fiind datat din 07.06.2011. Astfel, nu există un raport psihiatric al comisiei de medici psihiatri cu o argumentare în sens că, conform examenului psihiatric, s­au constatat la bolnav: tulburări psihice grave care condiţionează: a) pericolul nemijlocit pentru sine sau pentru cei din jur; b) prejudiciul grav sănătăţii sale dacă nu i se va acorda asistenţă psihiatrică; şi datele examenului psihiatric privind sănătatea mentală a persoanei examinate, conform documentaţiei medicale a acestuia. Avocatul care a reprezentat interesele lui xxNUMExx. în şedinţa instanţei de recurs a solicitat admiterea recursului din motivele invocate, cu remiterea cauzei la rejudecare pentru a fi efectuată expertiza psihiatrică a persoanei. În şedinţa de judecată procurorul participant a pledat pentru respingerea recursului ca fiind nefondat, cu menţinerea încheierii instanţei de fond. Reprezentantul Spitalului de Psihiatrie Bălți I. Dabija a solicitat respingerea recursului, cu menţinerea încheierii judecătoreşti, deoarece xxNUMExx. necesită în continuare să primească tratament. Verificând argumentele recurentului în raport cu materialele prezentate, cu cadrul legal existent, ascultînd opiniile participanţilor la proces, Colegiul penal vine la concluzia, că recursul urmează a fi respins ca nefondat. Potrivit prevederilor art.449 al.(1) pct.1) lit.a) CPP, judecînd recursul, instanța respinge recursul, menținînd hotărîrea atacată, dacă recursul este


--------------------------------------------- Result 93 ---------------------------------------------
[[1 (72%)]] --> [[[SKIPPED]]]

Prin sentința pronunțată instanța a reținut, că xxxxNUMExxxx a comis fapte de lăsare în primejdie, soldate cu decesul victimei, în următoarele circumstanțe: La data de 01.06.2012 a fost încheiată căsătoria dintre xxxxNUMExxxx şxxxxNUMExxxx (xxNUMExx) xxNUMExx. Din căsătorie, la data de 15.01.2014, de către xxxxNUMExxxx au fost născuţi 2 copii gemeni de sex masculin, xxnUMExx şi xxxxNUMExxxx. După naşterea copiilor, familia xxNUMExx locuia în locuinţa mamei numitei xxxxNUMExxxx, xxNUMExx, pe adresa: mun.Bălţi, str.Şevcenco xx, ap.x. în virtutea faptului, că xxxxNUMExxxx era preocupat de asigurarea materială a familiei, obligaţiile de supraveghere permanentă a copiilor de vîrsta fragedă xxNUMExx şi xxxxNUMExxxx, erau pe seama numitei xxxxNUMExxxx. Astfel, la o dată şi oră neidentificată de către organul de urmărire penală, în perioada 01.04.2014­07.04.2014, xxxxNUMExxxx fiind conştientă de vîrsta fragedă a copilului său xxNUMExx, ştiind că acesta se poate afla într­o stare periculoasă pentru viaţă, fiind lipsit de posibilitatea de a se salva datorită vîrstei fragede, intenţionat, dîndu­şi seama de caracterul prejudiciabil al inacțiunii sale, prevăzînd urmările prejudiciabile şi admiţnd în mod conștient survenirea lor, încălcînd prevederile art.48 alin.(2) ale Constituţiei RM din 29.07.1994 şi prevederile art.60 alin.(2) ale Codului Familiei, adoptat prin Legea RM nr.1316 din 26.10.2000, care stipulează în datoria părinților de a asigura creşterea şi dezvoltarea fizică a copiilor, precum şi prevederile art. 18 alin.(l) şi alin.(2) ale Legii nr.338 din 15.12 1994 privind drepturile copilului, care stipulează răspunderea părinților pentru dezvoltarea fizică şi pentru lipsa de supraveghere permanentă a copiilor de vîrstă fragedă, afîndu­se în locuinţa din str.Şevcenco,76, ap.2, a lăsat copilul xxNUMExx, născut la 15.01.2014, adică de vîrstă fragedă, fără supraveghere permanentă, fapt care a dus la traumarea acestuia în circumstanțe neidentificate de către organul de urmărire penală şi provocarea lui a vătămărilor corporale grave, periculoase pentru viaţă sub formă de traumatism cranio­cerebral acut închis sub formă de hemoragii în ţesuturile moi ale capului în regiunea occipitală, hematom acut subdural parietal­ occipital cu extindere la bază; hemoragii difiize subarahnoidiană temporal­parietal­occipital bilateral. După suportarea de către copilul xxnUMExx a traumei, despre care xxxxNUMExxxx cunoştea cu certitudine, ultima deşi cunoştea despre vîrstă fragedă a copilului său şi despre starea periculoasă pentru viaţă în care copilul se afla, fiind în imposibilitate de a se salva datorită vîrstei fragede, intenţionat, dîndu­şi seama de caracterul prejudiciabil al inacţiunii sale, prevăzînd urmările prejudiciabile şi admiţnd în mod conştient survenirea lor, l­a lăsat în continuare pe xxNUMExx fără ajutor, neapelînd la asistenţa medicală şi neasigurînd acordarea oportună a ajutorului medical copilului, încălcînd prevederile art.48 alin.(2) ale Constituţiei RM din 29.07.1994 şi prevederile art.60 alin.(2) ale Codului Familiei, adoptat prin Legea RM nr.1316 din 26.10.2000, care stipulează în datoria părinților de a asigura creșterea şi dezvoltarea fizică a copiilor, precum şi prevederile art.18 alin.(l) ale Legii nr.338 din 15.12.1994 privind drepturile copilului, care stipulează răspunderea părinților pentru dezvoltarea fizică a copiilor de vîrstă fragedă, inacțiuni care au provocat din imprudență decesul copilului xxxxNUMExxxx la data de 09.04.2014, ca consecință a vătămărilor corporale grave, periculoase pentru viaţă sub formă de traumatism cranio­cerebral acut închis sub formă de hemoragii în țesuturile moi ale capului în regiunea occipitală, hematom acut subdural parietal­occipital cu

[Succeeded / Failed / Skipped / Total] 33 / 41 / 20 / 94:  74%|███████▍  | 74/100 [14:29<05:05, 11.75s/it]

--------------------------------------------- Result 94 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Prin sentinţa nominalizată inculpatul Ț A a fost condamnat pentru, că în perioada lunilor august­octombrie a anului 2014, fiind condamnat la pedeapsă cu închisoare și deținut în penitenciarul nr.6 Soroca, urmărind scopul de cupiditate, stabilind legătură telefonică cu XXXXXXXXX, a.n. , domiciliată în s. r­nul sub pretext că suferă de tuberculoză, în executarea aceleiași intenții infracționale unice, a rugat­o pe ultima de cîteva ori să­i împrumute mijloace bănești pentru a se trata, comunicînd că­i va restitui banii împrumutați cînd se va elibera din detenție. Fiind determinată prin înșelăciune, XXXXXXXXX a transmis în cîteva tranșe lui Ț A prin intermediul unor persoane nestabilite de organul de urmărire penală, bani în sumă totală de 17 000 lei, iar ultimul intrînd în posesia banilor, neavînd în realitate intenția de a­i restitui, a dobîndit ilicit mijloace bănești ce i­au fost transmise, cauzînd astfel părții vătămate prin acțiunile sale o daună în proporții considerabile. Respectivele acțiuni ale inculpatului au fost încadrate conform prevederilor art.190 alin.(2) lit.c) Cod penal, ca escrocherie, adică dobîndirea ilicită a bunurilor altei persoane prin înșelăciune sau abuz de încredere, săvîrșită cu cauzarea de daune în proporții considerabile. În termen, la 23.05.2016, sentinţa instanţei de fond a fost atacată cu apel de către partea vătămată Mu A, din motivul ilegalităţii ei în ce priveşte latura civilă, invocînd, că în afară de prejudiciul material de 17 000 lei încasat de instanță ea a mai suportat și alte cheltuieli legate de transferul banilor, cheltuielile de transport suportate de ea tur – retur și prejudiciul moral cauzat ei prin infracțiune. Toate acestea ea le apreciază în suma de 2500 lei care solicită a o încasa de la inculpat. În şedinţa instanţei de apel XXXXXXXXX a soliciatat admiterea apelului pe motivele invocate în el. Procurorul participant a pledat pentru admiterea apelului declarat. Inculpatul Ț A şi apărătorul acesteia au solicitat respingerea apelului cu menţinerea sentinţei fără modificări. Verificînd argumentele apelantului, ascultînd participanţii, studiind materialele cauzei, Colegiul penal consideră, că apelul declarat urmează a fi respins ca nefondat. Instanţa de fond, în conformitate cu prevederile art.101 CPP, a verificat complet sub toate aspectele şi în mod obiectiv circumstanţele cauzei şi a dat probelor administrate o apreciere legală din punct de vedere al pertinenţei, concludenţei, utilităţii şi veridicităţii lor, corect ajungînd la concluzia privind vinovăţia inculpatului, care se confirmă prin probele acumulate pe dosar și cercetate nemijlocit în ședința judiciară, acţiunile acestuia fiind corect calificate de către instanţă, după indicii art.190 alin.(2) lit.c) CP al RM, ­ ca ,,escrocherie, adică dobîndirea ilicită a bunurilor altei persoane prin înșelăciune sau abuz de încredere, săvîrșită cu cauzarea de daune în proporții considerabile.” La numirea mărimei şi formei pedepsei în privinţa inculpatului instanţa de fond a ţinut seama de criteriile generale de individualizare a pedepsei penale, ce ţin de gravitatea faptei penale, urmările prejudiciabile, persoana acestuia, atitudinea societăţii faţă de pedeapsa penală, ce urmează a fi stabilită inculpatului pentru fapta săvîrşită, stabilindu­i lui Ț A o pedeapsă în limitele sancţiunii articolului incriminat, iar sentința în latura încadrării juridice și pedepsei stabilite nici nu a fost contestată. Conform art.225 alin.(1) ­ (2) CPP: ,,Judecarea

[Succeeded / Failed / Skipped / Total] 34 / 41 / 20 / 95:  75%|███████▌  | 75/100 [14:37<04:52, 11.70s/it]

--------------------------------------------- Result 95 ---------------------------------------------
[[1 (59%)]] --> [[0 (52%)]]

Prin sentința Judecătoriei Leova din 02 decembrie 2015 s­a încetat procesul penal de [[învinuirea]] lui xx în săvârșirea infracțiunii prevăzută de art. 220 alin.(2) lit.c) Cod penal, pe motiv că nu s­a constatat existența faptei infracțiunii. Pentru a pronunța sentința prima instanță a reținut că inculpata xx în luna octombrie 2014, acționând împreună și de comun acord cu persoane nestabilite de către organul de urmărire penală, aflându­se în s. xx, r­nul Leova, urmărind scopul îndemnării și înlesnirii practicării prostituției de către alte persoane, în cadrul discuției pe care le­a avut cu xx, născută la 28 octombrie 1993, i­a propus ultimei să practice prostituția într­un local din Turcia, promițându­i obținerea unor venituri bănești mari. Tot, xx în aceiași perioadă, în luna august a anului 2014, obținând consimțământul lui xx de a acorda servicii sexuale contra plată în Turcia, acționând împreună și prin înțelegere prealabilă cu persoane nestabilite de către organul de urmărire penală, aflând că xx nu deține pașaport național pentru plecare în străinătate, a asigurat­o pe xx, că cheltuielile necesare pentru perfectarea pașaportului și procurarea biletului de călătorie spre Turcia vor fi suportate de o persoană neidentificată de organul de urmărire penală pe nume „xx”, care se află pe teritoriul Turciei. Ulterior, xx în aceiași perioadă, în luna august a anului 2014, împreună și de comun acord cu alte persoane neidentificate de către organul de urmărire penală, urmărind înlesnirea practicării prostituției de xx s­a deplasat cu ultima la Secția de evidență și documentare a populației amplasată în sectorul Rîșcani, mun. Chișinău, unde xx a depus cerere pentru perfectarea pașaportului, iar cheltuielile necesare pentru perfectarea pașaportului au fost achitate de către xx. În dezacord cu sentința enunțată, la data de 16 decembrie 2015, procurorul în Procuratura raionului Leova xx a declarat apel, prin care a solicitat casarea sentinței primei instanţe, cu pronunțarea unei noi hotărâri potrivit modului stabilit pentru prima instanță, prin care xx să fie recunoscută vinovată în comiterea infracțiunii prevăzută de art. 220 alin.(2) lit.c) Cod penal, stabilindu­i pedeapsa sub formă de 5 ani închisoare, care conform art. 90 CP să fie suspendată pe un termen de probă de 4 ani. În motivarea apelului a indicat că, instanța de judecată nu a analizat în cumul toate probele prezentate de către acuzare, dându­le o apreciere unilaterală, bazate doar pe declarațiile inculpatei depuse în cadrul ședinței de judecată, care vădit au fost date cu scopul de a evita răspunderea pentru faptele comise. Indică acuzatorul de stat că, vina inculpatei în comiterea infracțiunii se probează prin declarațiile martorului xx, xx, xx și probele materiale anexate la dosar care au fost greșit apreciate de către instanța de judecată. Menționează apelantul că prin îndemnul la practicarea prostituției legiuitorul prezumă acțiunea prin care are loc incitarea, trezirea interesului unei persoane pentru ca această să practice prostituția, încurajarea ei pentru a învinge ezitările care o împiedică să practice prostituția. În speță, s­a constatat că inculpata xx a realizat aceste acțiuni, deoarece dânsa a trezit interesul lui xx pentru activitatea de prestare a serviciilor sexuale contra plată, i­a propus să acorde servicii sexuale contra plată pe teritoriul Turciei și

Prin sentința Judecătoriei Leova din 02 decembrie 2015 s­a încetat procesul penal de [[învniuirea]] lui xx în săvârșirea infracțiunii prevăzută de art. 220 alin.(2) lit.c) Cod penal, pe motiv că nu s­a constatat existența faptei infracțiunii. Pentru a pronunța sentința prima instanță a reținut că inculpata xx în luna octombrie 2014, acționând împreună și de comun acord cu persoane nestabilite de către organul de urmărire penală, aflându­se în s. xx, r­nul Leova, urmărind scopul îndemnării și înlesnirii practicării prostituției de către alte persoane, în cadrul discuției pe care le­a avut cu xx, născută la 28 octombrie 1993, i­a propus ultimei să practice prostituția într­un local din Turcia, promițându­i obținerea unor venituri bănești mari. Tot, xx în aceiași perioadă, în luna august a anului 2014, obținând consimțământul lui xx de a acorda servicii sexuale contra plată în Turcia, acționând împreună și prin înțelegere prealabilă cu persoane nestabilite de către organul de urmărire penală, aflând că xx nu deține pașaport național pentru plecare în străinătate, a asigurat­o pe xx, că cheltuielile necesare pentru perfectarea pașaportului și procurarea biletului de călătorie spre Turcia vor fi suportate de o persoană neidentificată de organul de urmărire penală pe nume „xx”, care se află pe teritoriul Turciei. Ulterior, xx în aceiași perioadă, în luna august a anului 2014, împreună și de comun acord cu alte persoane neidentificate de către organul de urmărire penală, urmărind înlesnirea practicării prostituției de xx s­a deplasat cu ultima la Secția de evidență și documentare a populației amplasată în sectorul Rîșcani, mun. Chișinău, unde xx a depus cerere pentru perfectarea pașaportului, iar cheltuielile necesare pentru perfectarea pașaportului au fost achitate de către xx. În dezacord cu sentința enunțată, la data de 16 decembrie 2015, procurorul în Procuratura raionului Leova xx a declarat apel, prin care a solicitat casarea sentinței primei instanţe, cu pronunțarea unei noi hotărâri potrivit modului stabilit pentru prima instanță, prin care xx să fie recunoscută vinovată în comiterea infracțiunii prevăzută de art. 220 alin.(2) lit.c) Cod penal, stabilindu­i pedeapsa sub formă de 5 ani închisoare, care conform art. 90 CP să fie suspendată pe un termen de probă de 4 ani. În motivarea apelului a indicat că, instanța de judecată nu a analizat în cumul toate probele prezentate de către acuzare, dându­le o apreciere unilaterală, bazate doar pe declarațiile inculpatei depuse în cadrul ședinței de judecată, care vădit au fost date cu scopul de a evita răspunderea pentru faptele comise. Indică acuzatorul de stat că, vina inculpatei în comiterea infracțiunii se probează prin declarațiile martorului xx, xx, xx și probele materiale anexate la dosar care au fost greșit apreciate de către instanța de judecată. Menționează apelantul că prin îndemnul la practicarea prostituției legiuitorul prezumă acțiunea prin care are loc incitarea, trezirea interesului unei persoane pentru ca această să practice prostituția, încurajarea ei pentru a învinge ezitările care o împiedică să practice prostituția. În speță, s­a constatat că inculpata xx a realizat aceste acțiuni, deoarece dânsa a trezit interesul lui xx pentru activitatea de prestare a serviciilor sexuale contra plată, i­a propus să acorde servicii sexuale contra plată pe teritoriul Turciei și

[Succeeded / Failed / Skipped / Total] 34 / 42 / 20 / 96:  76%|███████▌  | 76/100 [14:51<04:41, 11.74s/it]

--------------------------------------------- Result 96 ---------------------------------------------
[[0 (97%)]] --> [[[FAILED]]]

La data de 11.09.2014 în adresa Procuraturii raionului xxx a parvenit plîngerea lui xxxxNUMExxxxicolai, privind acţiunile pretins ilegale ale persoanelor necunoscute, care în noaptea spre 03.09.2014, în apropierea iazurilor din xxxx, raionul Rîşcani, inclusiv şi în prezenţa colaboratorilor Inspectoratului de politie al raionului Rîşcani, l­au răpit şi l­au maltratat. În urma controlului efectuat, audierii în calitate de parte vătămată a cet.xxxxNUMExxxxxx, martorilor xxx, analizînd toate probele în ansamblu, procurorul în Procuratura raionului xxxa conchis că în acţiunile luixxxxxşi altor persoane, care se aflau în noaptea spre 03.09.2014 pe malul iazului arendat de către xxx, lipsesc elementele constitutive ale vre­unei infracţiuni, deoarece nu s­a stabilit că xxxxNUMExxxxxx a fost răpit şi maltratat de către ultimii, inclusiv şi în prezenţa colaboratorilor de poliţie. Astfel, prin ordonanţa din 06.10.2014 procurorul în Procuratura raionului xxxxx a dispus neînceperea urmăririi penale în baza plîngerii cet.xxxxNUMExxxxxx împotriva acţiunilor lui xxx şi colaboratorilor de poliţie ai xxx., din motivul că fapta nu întruneşte elementele infracţiunii, cu clasarea procesului penal şi pornirea în privinţa xxx a procesului contravenţional în baza art.78 alin.2 Cod contravenţional. Ordonanţa în cauză a fost contestată de către xxxxNUMExxxxicolai procurorului ierarhic superior, în temeiul art.299/1 CPP, care prin ordonanţa din 12.11.2014 a dispus respingerea integrală a plîngerii înaintate de xxxxNUMExxxxxxxi împotriva ordonanţei procuroruluixxx din 06.10.2014. Nefiind de acord cu ordonanţele adoptate, la data de 27.11.2014 avocatul xxx în interesul lui xxxx, a depus în instanţa de judecată o plîngere împotriva ordonanţei procurorului în procuratura raionului Rîşcani xxxx din 06 octombrie 2014 privind neînceperea urmăririi penale. În motivarea plîngerii avocatul xxx în interesul lui xxx a indicat, că procurorul xxx făcînd referire la circumstanţele cauzei contravenţionale şi a condiţiilor art.37 din CP al RM, nu a motivat în ce circumstanţe s­a exclus fapta penală şi în ce circumstanţe a fost constatată fapta contravenţională. Astfel, în timpul examinării plîngerii cet.xxxxNUMExxxx s­au admis încălcări grave privind investigarea acestei cauze, care rezultă din următoarele: ­ La baza concluziei procurorului au stat probe obţinute de către poliţiştii care investighează cauza furtului de peşte. Acest lucru este inacceptabil şi nu poate fi folosit ca argument sub nici un pretext legal şi nu constituie o investigaţie obiectivă. ­ Persoanele la care a făcut referire în cerere cet.xxxxNUMExxxxxxi, nu au fost identificate de către procuror, mai mult ca atît au fost identificate pe dosarul privind sustragerea peştelui persoane depoziţiile cărora au fost folosite de către procuror la emiterea ordonanţei de neîncepere a urmăririi penale. Totodată, procurorul nu a chemat victima să facă prezentarea spre recunoaştere a persoanelor vinovate. Din cerere cert reiese faptul, că cetăţeanului xxxxNUMExxxxxx i s­a aplicat violenţă fizică şi psihică de mai multe persoane. ­ Probele privind expertiza medico­legală cu privire la examinarea fizică a cet. xxxxNUMExxxxxx, a fost obţinută de procuror, de pe alt caz penal (anume pe cazul penal unde xxxxNUMExxxxx are calitate de bănuit) şi nu s­a efectuat o expertiză medico­legală independentă precum şi nu a fost făcută şi examinarea medico­legală psihiatrică a cet. xxxxNUMExxxx, de aceea consideră, că s­au comis încălcări grave de ordin procesual din partea procurorului; ­ Totodată, cet.xxxxNUMExxxx a prezentat procurorului probe la care

[Succeeded / Failed / Skipped / Total] 34 / 43 / 20 / 97:  77%|███████▋  | 77/100 [15:06<04:30, 11.77s/it]

--------------------------------------------- Result 97 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Prin încheierea Judecătoriei Bălți din 02.09.2016 a fost admis demersul procurorului în Procuratura mun.Bălți Monastîrschi Stanislav și s­a aplicat în privinţa lui xxx, a.n.xxx, măsura preventivă sub formă de arest preventiv pe un termen de 30/treizeci zile/ zile, cu calcularea termenului de la data de 29.09.2016, ora 16.10. Prin încheierea Judecătoriei Bălți din 26.09.2016 a fost admis demersul procurorului și s­a prelungit în privinţa lui xxx, a.n.xxx, măsura preventivă sub formă de arest preventiv pe un termen de 30/treizeci zile/ zile, cu calcularea termenului de la data reținerii pînă la data de 29.10.2016, ora 16.10. Prin încheierea Judecătoriei Bălți din XXXXXXXXX a fost admis demersul procurorului în Procuratura mun.Bălți Nadulișneac Tatiana și s­a prelungit în privinţa lui xxx, a.n.xxx, măsura preventivă sub formă de arest preventiv pe un termen de 30/treizeci zile/ zile, cu calcularea termenului de la data de 29.10.2016, ora 16.10 inclusiv pînă la data de 28.11.2016, ora 16.10 inclusiv. Încheierea în cauză a fost contestată de către inculpatul xxx cu recurs inițial, în motivare invocînd că se obligă să se prezinte la orice solicitare, nu va influența părțile pe dosar, nu se va eschiva deoarece are loc permanent de trai în mun.xxx satul xxx strada xx, solicitînd anularea măsurii preventive arestul dispus de instanța de fond și aplicarea în privința sa a arestului la domiciliu. Ulterior inculpatul xxx a depus recurs suplimentar, invocînd în motivare că nu este deacord cu încheierea instanței de fond, are loc permanent de trai și locuiește cu părinții, tatăl a decedat și a rămas numai mama, care este pensionară și bolnavă și mai îngrijește de fiul invalid, el este unicul care o poate ajuta în situația creată, nu intenționează să plece sau să fugă, nu are nici acte, este bolnav după un traumatism la cap și în fiecare an necesită de tratament medical, iar din cauza arestului i s­a înrăutățit grav starea sănătății, asigură instanța că se va afla permanent acasă, solicitînd schimbarea măsurii preventive sub formă de arest preventiv în altă măsură nonprivativă de libertate – arest la domiciliu, ținînd cont de faptul că are la întreținere un copil minor. În şedinţa instanței de recurs avocatul Movilă Corina și inculpatul xxx au susținut recursul declarat de inculpat și au solicitat să fie admis din motivele invocate. În şedinţa instanţei de recurs procurorul participant a solicitat respingerea recursului, cu menţinerea încheierii atacate ca legală. Verificînd argumentele invocate în recurs în raport cu materialele cauzei penale prezentate pentru verificarea legalităţii încheierii contestate şi audiind opiniile participanţilor la proces, Colegiul penal ajunge la concluzia că recursul declarat de inculpatul xxx urmează a fi respins ca nefondat, cu menţinerea încheierii contestate reeşind din următoarele considerente. Soluţia instanţei de recurs se bazează pe prevederile art.312 al.5 p.2 CPP RM, potrivit căruia se reglementează, că în urma controlului judiciar efectuat, instanţa de recurs pronunţă una din următoarele decizii: 2) respinge recursul. Colegiul penal conchide că instanţa de judecată, dispunînd de suficiente temeiuri rezonabile, corect a decis despre necesitatea prelungirii măsurii preventive sub formă de arestare preventivă în privința lui xxx, referitor la prelungirea măsurii preventive sub formă de arestare

[Succeeded / Failed / Skipped / Total] 34 / 44 / 20 / 98:  78%|███████▊  | 78/100 [15:20<04:19, 11.80s/it]

--------------------------------------------- Result 98 ---------------------------------------------
[[1 (99%)]] --> [[[FAILED]]]

Potrivit sentinței, xxx a fost condamnat pentru, că deținând permisul de conducere nr. xxx cu categoria ,, B”, în noaptea spre 15.10.2015 pe la orele 00:25 min., conducând contrar dispozițiilor art. 14 pct. a) din Regulamentul circulaţiei rutiere, automobilul de model xxx în stare de ebrietate alcoolică, a intrat cu viteză excesivă în curtea lăcașului cultural din localitatea xxx unde sătenii sărbătoreau hramul, aceștia fiind nevoiți de a se feri pentru a nu fi tamponați, motiv pentru care fiind suspectat de întrebuințarea băuturilor alcoolice, a fost stopat de către șeful de post xxx, antrenat în menținearea ordinii publice, ce i­a propus testarea alcooscopică cu mijlocul special de testare alcotest ”Drager”, pe care a refuzat­o, fiind îndreptat în instituția medico­sanitară spre examinarea medicală pentru stabilirea stării de ebrietate și naturii ei cu prelevarea probelor biologice, pe care la fel fără motive întemeiate a refuzat­o, fapt consemnat prin procesul­verbal al examinării medicale de constatare a faptului de consumare a alcoolului, stării de ebrietate și naturii ei nr. 372 din 15.10.2015, respectivele acțiuni fiindu­i încadrate la art. 264/1 alin. (3) Cod penal în prezența calificativelor ”refuzul conducătorului mijlocului de transport de la testarea alcoolscopică și de la recoltarea probelor biologice în vederea stabilirii stării de ebrietate și naturii ei”. Sentința de condamnare a fost contestată cu recurs în termenul și în ordinea prevăzută de art. art. 437 ­ 439 Cod pr. penală, de către inculpatul Teacă Eugen, solicitându­se casarea ei, rejudecarea cauzei cu pronunțarea unei noi hotărîri de achitatare din lipsa în acțiuni a elementelor constitutive ale infracțiunii prevăzute de art. 264/1 alin. (3) Cod Penal. În motivarea cerințelor formulate invocându­ se, examinarea superficială și neobiectivă a cauzei, cu o apreciere unilaterală și pur subiectivă a probelor administrate de către OUP, ce nu­i dovedesc refuzul de la testarea alcooscopică și examenul medical, precum și cel de prelivare a probelor biologice, or în cadrul audierii în calitate de bănuit, a menționat, că nu a refuzat să fie suspus expertizei, nici nu a negat faptul consumului băuturilor alcoolice, doar decât nu dispunea de mijloace bănești pentru achitarea costului ei, împrejurări ce potrivit dispozițiilor art. 8 alin. (3) Cod pr. penală, urmează a fi interpretate în favoarea sa. Procedura citării legale și actele procesuale preparatorii judecării cauzei în ordine de recurs, prevăzute de art. 446 Cod pr. penală au fost executate. În fața instanței de recurs, la fel ca și în cea de fond, inculpatul xxx nu s­a prezentat din motivul lipsei pe teritoriul țării, fapt confirmat de către apărătorii ce­i exercită apărarea A. Olșanschi și A. Axentii, ce au solicitat examinarea cauzei în lipsa acestui, fapt pentru care Colegiul în corespundere cu prevederile art. 447 alin. (1) Cod pr. penală, dispunând de informația referitor la ieșirea lui din țară și cu acordul părții apărării, a considerat posibilă examinarea cauzei în absența inculpatului. Respectiv, avocatul Andrei Axenti în apărarea intereselor inculpatului xxx a pledat pentru admiterea recursului pe motivele invocate în el, cu casarea sentinței și achitarea celui din urmă de sub învinuirea adusă, din lipsa probelor ce incontestabil i­ar demonstra vinovăția, or motivul penru care el nu

[Succeeded / Failed / Skipped / Total] 35 / 44 / 20 / 99:  79%|███████▉  | 79/100 [15:29<04:06, 11.76s/it]

--------------------------------------------- Result 99 ---------------------------------------------
[[1 (98%)]] --> [[0 (73%)]]

1. *****, la data 09 ianuarie 2019, aproximativ în jurul orelor 16:00, în timp ce se deplasa cu rutiera nr.8 pe sectorul ,,Dacia” din mun. Bălți, avînd scop sustragerea bunurilor altei persoane din buzunare, acționînd cu intenție directă îndreptată la atingerea scopului stabilit și asigurîndu-se că nu este văzut de nimeni, dîndu-și seama de caracterul prejudiciabil al acțiunilor sale, prevăzînd urmările și dorind în mod conștient survenirea lor, pe ascuns a sustras din buzunarul drept al scurtei********** care se deplasa în aceiași rutieră, telefonul mobil de model ,,Samsung J3” cu numărul de IMEI: 35270790387717, la prețul de 4000 lei, cauzîndu-i părții vătămate********** o daună materială în proporții considerabile în sumă totală de 4 000 lei. 2. Inculpatul *****, fiind audiat în cadrul examinării cauzei, chestionat sub jurămînt în conformitate cu art.108 şi art. 364/1 Cod de procedură penală al RM, vina în săvîrşirea acţiunilor ilegale a recunoscut-o pe deplin şi a declarat [[instanței]] că la data de 09.01.2019, deplasîndu-se în rutiera nr. 8 mun. Bălți a sustras de la partea vătămată telefonul mobil care a fost restituit părții vătămate. Careva obiecţii în privinţa probelor acumulate de către organul de urmărire penală nu a invocat şi nu a prezentat probe noi. 3. Partea vătămată*****a, prin cererea depusă a solicitat [[încetarea]] [[procesului]] penal în legătură cu faptul că s-a împăcat cu inculpatul ***** și careva pretenții de ordin material față de inculpat nu are. 4. La fel, vina în comiterea infracţiunii inculpatul ***** a recunoscut-o integral, solicitînd prin cerere semnată personal, cu conţinutul expres şi neechivoc şi cu renunţarea de a fi prezentate probe suplimentare, examinarea cauzei în ordinea prevăzută de art. 364/1 Cod de procedură penală al RM. 5. Procurorul nu a invocat obiecţii cu privire la examinarea cauzei în ordinea prevăzută de art. 364/1 CPP al RM. 6. Apărătorul a susţinut cererea inculpatului. 7. Instanţa de judecată, analizînd cererea inculpatului şi ascultînd opiniile participanţilor la proces, ţinînd cont de recunoaşterea totală şi necondiţionată a vinovăţiei, a găsit posibilă de a admite cererea inculpatului ***** dat fiind faptul că din probele administrate rezultă că faptele inculpatului sînt stabilite şi sînt suficiente date cu privire la persoana acestuia pentru a permite stabilirea unei pedepse. 8. În acest sens, vina inculpatului ***** a fost demonstrată pe deplin nu doar prin declaraţiile sale de recunoaştere a vinovăţiei, ci şi prin probele acumulate de către urmărirea penală. Inculpatul ***** a recunoscut şi nu a contestat probele prezentate. 9. Vinovăţia inculpatului ***** este confirmată prin probele cercetate în cadrul şedinţei de judecată, şi anume:  informația parvenită în Unitatea de Gardă a IP Bălți la data de 09.01.2019, ora 16:07 potrivit căreia pe str. Alexandru Cel Bun lîngă marchetul ,,Fourchette” a fost reținută o persoană ce a încercat să sustragă un telefon de la o persoană din geantă (f.d.3);  plîngerea lui*****a din 10.01.2019 (f.d.5);  procesul-verbal de audiere a părții vătămate********** (f.d.12-13);  procesul-verbal de ridicare din 09.01.2010 (f.d.15);  proces-verbal de examinare a obiectului din 09.01.2019 cu fototabel (f.d.17-21);  proces-verbal de audiere a martorului ***** din 09.01.2019 (f.d.23-24);  procesul-verbal de confruntare dintre martorul Cibotari

1. *****, la data 09 ianuarie 2019, aproximativ în jurul orelor 16:00, în timp ce se deplasa cu rutiera nr.8 pe sectorul ,,Dacia” din mun. Bălți, avînd scop sustragerea bunurilor altei persoane din buzunare, acționînd cu intenție directă îndreptată la atingerea scopului stabilit și asigurîndu-se că nu este văzut de nimeni, dîndu-și seama de caracterul prejudiciabil al acțiunilor sale, prevăzînd urmările și dorind în mod conștient survenirea lor, pe ascuns a sustras din buzunarul drept al scurtei********** care se deplasa în aceiași rutieră, telefonul mobil de model ,,Samsung J3” cu numărul de IMEI: 35270790387717, la prețul de 4000 lei, cauzîndu-i părții vătămate********** o daună materială în proporții considerabile în sumă totală de 4 000 lei. 2. Inculpatul *****, fiind audiat în cadrul examinării cauzei, chestionat sub jurămînt în conformitate cu art.108 şi art. 364/1 Cod de procedură penală al RM, vina în săvîrşirea acţiunilor ilegale a recunoscut-o pe deplin şi a declarat [[intsanței]] că la data de 09.01.2019, deplasîndu-se în rutiera nr. 8 mun. Bălți a sustras de la partea vătămată telefonul mobil care a fost restituit părții vătămate. Careva obiecţii în privinţa probelor acumulate de către organul de urmărire penală nu a invocat şi nu a prezentat probe noi. 3. Partea vătămată*****a, prin cererea depusă a solicitat [[înceatrea]] [[proecsului]] penal în legătură cu faptul că s-a împăcat cu inculpatul ***** și careva pretenții de ordin material față de inculpat nu are. 4. La fel, vina în comiterea infracţiunii inculpatul ***** a recunoscut-o integral, solicitînd prin cerere semnată personal, cu conţinutul expres şi neechivoc şi cu renunţarea de a fi prezentate probe suplimentare, examinarea cauzei în ordinea prevăzută de art. 364/1 Cod de procedură penală al RM. 5. Procurorul nu a invocat obiecţii cu privire la examinarea cauzei în ordinea prevăzută de art. 364/1 CPP al RM. 6. Apărătorul a susţinut cererea inculpatului. 7. Instanţa de judecată, analizînd cererea inculpatului şi ascultînd opiniile participanţilor la proces, ţinînd cont de recunoaşterea totală şi necondiţionată a vinovăţiei, a găsit posibilă de a admite cererea inculpatului ***** dat fiind faptul că din probele administrate rezultă că faptele inculpatului sînt stabilite şi sînt suficiente date cu privire la persoana acestuia pentru a permite stabilirea unei pedepse. 8. În acest sens, vina inculpatului ***** a fost demonstrată pe deplin nu doar prin declaraţiile sale de recunoaştere a vinovăţiei, ci şi prin probele acumulate de către urmărirea penală. Inculpatul ***** a recunoscut şi nu a contestat probele prezentate. 9. Vinovăţia inculpatului ***** este confirmată prin probele cercetate în cadrul şedinţei de judecată, şi anume:  informația parvenită în Unitatea de Gardă a IP Bălți la data de 09.01.2019, ora 16:07 potrivit căreia pe str. Alexandru Cel Bun lîngă marchetul ,,Fourchette” a fost reținută o persoană ce a încercat să sustragă un telefon de la o persoană din geantă (f.d.3);  plîngerea lui*****a din 10.01.2019 (f.d.5);  procesul-verbal de audiere a părții vătămate********** (f.d.12-13);  procesul-verbal de ridicare din 09.01.2010 (f.d.15);  proces-verbal de examinare a obiectului din 09.01.2019 cu fototabel (f.d.17-21);  proces-verbal de audiere a martorului ***** din 09.01.2019 (f.d.23-24);  procesul-verbal de confruntare dintre martorul Cibotari

[Succeeded / Failed / Skipped / Total] 36 / 44 / 20 / 100:  80%|████████  | 80/100 [15:37<03:54, 11.72s/it]

--------------------------------------------- Result 100 ---------------------------------------------
[[1 (84%)]] --> [[0 (54%)]]

1. Inculpaţii xxxx la data de 08.01.2007, în urma unei înţelegeri prealabile şi în complicitate cu xxx, a.n.xxx, în scop de expluatare sexuală comercială în Turcia, contra sumei de 1800 dolari americani, primită de la un cetăţean al Turciei, neidentificat de organul de urmărire penală, au recrutat­o pe xxx, născută în anul xxx, domiciliată în sat.xxx, r­ul Drochia, abuzînd de poziţia acesteia de vulnerabilitate, i­au prezentat realităţi false, precum că o vor angaja la o muncă decentă şi bine plătită, cu un salariu lunar de la 1500 la 2000 dolari americani, în calitate de barmen în Grecia, pe care pînă la perfectarea actelor necesare pentru plecare, au adăpostit­o în mun.Chişinău, strada xxxxx. După ce i­au perfectat în condiţii legale, din bani proprii, paşaport al cetăţeanului Republicii Moldova şi cumpărat bilet de călătorie, la 14.01.2007, de la aeroportul Chişinău, au urcat­o la bordul unei aeronave cu destinaţia Turcia. În Turcia, oraşul Istambul, xxx a fost întîlnită de o persoană de etnie turcă, neidentificată de organul de urmărire penală. Însoţită de acesta, au urcat la bordul unei alte aeronave, pînă în oraşul Antalia, Turcia, unde a fost transmisă unei alte persoane de etnie turcă, neidentificată de organul de urmărire penală, care a adăpostit­o împreună cu alte fete în locuinţa proprie, nestabilită de organul de urmărire penală, unde pe tot timpul aflării sale a fost supusă violenţei fizice şi psihice, prestînd servicii sexuale contra plată, inclusiv şi în alte locale decît la domiciliu, la 17.03.2007, fiind expulzată de autorităţile statale turce, pentru încălcarea regimului de vize. 2. Conform sentinței [[judecătoriei]] [[Drochia]] din 12 mai 2015 xxxx a fost recunoscută vinovată de comiterea infracțiunii prevăzute de art.165 alin.(1) lit.a), b), c), alin.(2) lit.d) și alin.(3) lit.a) Cod penal şi i s­a stabilit pedeapsă 10 ani (zece ani) închisoare, cu ispăşirea pedepsei în penitenciar pentru femei, cu privarea de dreptul de a ocupa anumite funcţii sau de a exercita o anumită activitate în perfectarea documentelor pentru ieşirea în afara ţârii a persoanelor pe un termen de 3 (trei) ani. Pedeapsa aplicată lui xxxx a fost dispusă spre executare după întrarea sentinţei în vigoare. Termenul ispăşirii pedepsei lui xxxx s­a dispus a fi calculată din momentul reținerii acesteia. Pretențiile materiale şi morale a lui xxx faţă de xxx şi xxxx s­au admis în principiu, urmînd ca cuantumul precis al despăgubirilor să fie stabilit de instanţa civilă. Instanța de fond s­a pronunțat și asupra corpurilor delicte. 3. Inculpata xxxxxx a depus apel împotriva sentinţei judecătoriei Drochia din 12.05.2015, prin care solicită casarea sentinţei date cu pronunţarea unei noi sentinţe prin care să fie achitată. Motivele apelului sunt următoarele: consideră că sentinţa dată este ilegală, fiind viciată inclusiv de aprecierea eronată a probelor; nu s­a luat în consideraţie faptul că ea și soțul ei nu au recrutat­o, transportat­o, adăpostit­o pe partea­vătămată pentru a fi expluatată sexual. Apelanta consideră că acuzatorul de stat nu a adus în şedinţa de judecată careva dovezi în latura dată. Consideră că din declarațiile părții­vătămate s­a constatat că ultima de 7 ori a telefonat din Turcia tatălui ei şi au avut convorbiri. Din conversaţiile telefonice, pătimita

1. Inculpaţii xxxx la data de 08.01.2007, în urma unei înţelegeri prealabile şi în complicitate cu xxx, a.n.xxx, în scop de expluatare sexuală comercială în Turcia, contra sumei de 1800 dolari americani, primită de la un cetăţean al Turciei, neidentificat de organul de urmărire penală, au recrutat­o pe xxx, născută în anul xxx, domiciliată în sat.xxx, r­ul Drochia, abuzînd de poziţia acesteia de vulnerabilitate, i­au prezentat realităţi false, precum că o vor angaja la o muncă decentă şi bine plătită, cu un salariu lunar de la 1500 la 2000 dolari americani, în calitate de barmen în Grecia, pe care pînă la perfectarea actelor necesare pentru plecare, au adăpostit­o în mun.Chişinău, strada xxxxx. După ce i­au perfectat în condiţii legale, din bani proprii, paşaport al cetăţeanului Republicii Moldova şi cumpărat bilet de călătorie, la 14.01.2007, de la aeroportul Chişinău, au urcat­o la bordul unei aeronave cu destinaţia Turcia. În Turcia, oraşul Istambul, xxx a fost întîlnită de o persoană de etnie turcă, neidentificată de organul de urmărire penală. Însoţită de acesta, au urcat la bordul unei alte aeronave, pînă în oraşul Antalia, Turcia, unde a fost transmisă unei alte persoane de etnie turcă, neidentificată de organul de urmărire penală, care a adăpostit­o împreună cu alte fete în locuinţa proprie, nestabilită de organul de urmărire penală, unde pe tot timpul aflării sale a fost supusă violenţei fizice şi psihice, prestînd servicii sexuale contra plată, inclusiv şi în alte locale decît la domiciliu, la 17.03.2007, fiind expulzată de autorităţile statale turce, pentru încălcarea regimului de vize. 2. Conform sentinței [[judectăoriei]] [[Dorchia]] din 12 mai 2015 xxxx a fost recunoscută vinovată de comiterea infracțiunii prevăzute de art.165 alin.(1) lit.a), b), c), alin.(2) lit.d) și alin.(3) lit.a) Cod penal şi i s­a stabilit pedeapsă 10 ani (zece ani) închisoare, cu ispăşirea pedepsei în penitenciar pentru femei, cu privarea de dreptul de a ocupa anumite funcţii sau de a exercita o anumită activitate în perfectarea documentelor pentru ieşirea în afara ţârii a persoanelor pe un termen de 3 (trei) ani. Pedeapsa aplicată lui xxxx a fost dispusă spre executare după întrarea sentinţei în vigoare. Termenul ispăşirii pedepsei lui xxxx s­a dispus a fi calculată din momentul reținerii acesteia. Pretențiile materiale şi morale a lui xxx faţă de xxx şi xxxx s­au admis în principiu, urmînd ca cuantumul precis al despăgubirilor să fie stabilit de instanţa civilă. Instanța de fond s­a pronunțat și asupra corpurilor delicte. 3. Inculpata xxxxxx a depus apel împotriva sentinţei judecătoriei Drochia din 12.05.2015, prin care solicită casarea sentinţei date cu pronunţarea unei noi sentinţe prin care să fie achitată. Motivele apelului sunt următoarele: consideră că sentinţa dată este ilegală, fiind viciată inclusiv de aprecierea eronată a probelor; nu s­a luat în consideraţie faptul că ea și soțul ei nu au recrutat­o, transportat­o, adăpostit­o pe partea­vătămată pentru a fi expluatată sexual. Apelanta consideră că acuzatorul de stat nu a adus în şedinţa de judecată careva dovezi în latura dată. Consideră că din declarațiile părții­vătămate s­a constatat că ultima de 7 ori a telefonat din Turcia tatălui ei şi au avut convorbiri. Din conversaţiile telefonice, pătimita

[Succeeded / Failed / Skipped / Total] 36 / 45 / 21 / 102:  81%|████████  | 81/100 [15:52<03:43, 11.76s/it]

--------------------------------------------- Result 101 ---------------------------------------------
[[1 (88%)]] --> [[[FAILED]]]

În procedura judecătoriei Bălți se află cauza penală de învinuire a lui xxx în săvîrșirea infracțiunii prevăzute de art.171 alin. (3) lit.b) C pen În cadrul examinării cauzei penale menționate, în cadrul ședinței judiciare din 14.12.2015 a fost numită una din ședințele de judec pentru data de 04.03.2016 orele 09:3și XXXXXXXXX ora 14:00 în prezența procurorului Crișciuc Ion, avocatului Igor Ciuru, inculpatu xxx,ărții vătămate xxx și reprezentantului legal al acesteia xxx. În ședința judiciară din 04:03.2016, fiind prezenți participanții la proces, iar în afară de aceasta fiind asigurată de către procuror preze unșir de martori (xxx, xxx și xxxx), președintele colegiului a comunicat că XXXXXXXXX fiind antrenat într­o altă ședință judiciară a f în imposibilitate de a se prezenta la proc În cadrul ședinței de judecată fiind pusă în discuția participanților posibilitatea examinării cauzei în lipsa avocatului Igor Ciur procurorul a considerat imposibil, mționînd că pentru ședința judiciară următoare va fi imposibil de asigurat prezența martorilor, deoare locuiesc în alt raioși nu au posibilitate de a veni de fiecare dată. Prin încheierea Judecătoriei Bălți din XXXXXXXXX, avocatului Igor Ciuru i­a fost aplicată amendă judiciară în mărime de 10 (zec uăți convenționale­200 (două sute) lei. Nefiind de acord cu încheierea judecătoriei Bălţi din XXXXXXXXX, XXXXXXXXX a înaintat recurs, solicitînd admiterea acestuia casarea încheierii instței de fond ca neîntemeiată. În motivarea recursului a invocat, că participă în calitate de avocat (delegat de CNAJGS), al inculpatului xxx învinuit de comiter infrţiunii prevăzute de art.171 a1in. (3) lit. b) Cod Penal RM, cauză ce se examinează de către judecătoria Bălţi, de completul: A. Vrîncean M. Cojocarşi N. Costaş. Indică, că ședinţa de judecată a fost numită pentru data de 04.03.2016, ora 9:30, la care s­a prezentat la ora stabilită (9:30), fiind anun de grefierul judătorului A. Vrînceanu că şedinţa de judecată va începe cu întîrziere, deoarece unul din judecătorii completului de judeca N. Co ş, participă la examinarea unei alte cauze penale ­ motiv pentru care se reţine. Menționează, că a așteptat pînă la ora 10:05, după care a preîntîmpinat verbal grefierul că trebuie să participe la examinarea unei a cauze penale, stabă la fel pentru data de 04.03.2016, ora 10:00, la judecătorul A. Guţu. Revenind din şedinţa de judecată stabilită pentru ora 10:00 la Judecătorul A. Guţu, a fost informat de către grefierul judecătorului Vrînceanuă şedinţa de judecată pe dosarul de învinuire a lui xxx s­a amînat pentru data de 10 martie 2016. La şedinţa din 10 martie 2016, preşedintele şedinţei, judecătorul A. Vrînceanu, a pus întrebarea privind motivul absenţei sale de la şedi din 04.03.2016, astfel el motivîn­și prin invocarea circumstanţelor expuse. Instanța considerînd absenţa sa de la şedinţa din 04.03.2016 ca neîntemeiată şi că s­a manifestat lipsă de respect şi desconsiderare văd ţă de instanţa de judecată, a emis încheierea contestată. Consider încheierea Judecătoriei Bălţi din 10 martie 2016 una vădit neîntemeiată, fapt pentru care a contest­o cu recurs. A menționat că încheierea atacată nu cuprinde motivele pe care se întemeiază soluţia: dispozitivul hotărîrii este expus neclar(art. 444 pct. Cauza absenţei lui de la şedinţa din 04.03.2016 a fost dictată de faptul că:


--------------------------------------------- Result 102 ---------------------------------------------
[[1 (64%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse mai sus, instanţa de fond a reţinut, că XXXXXXXXX Victor, în noaptea spre 21.11.2015, în satul Sturzovca raionul Glodeni, fiind în stare de ebrietate, avînd intenţia răpirii mijlocului de transport fără scop de însuşire, prin acces liber a intrat în casa lui Gheorghica Ion Vladimir cu care este în relaţii de rudenie, de unde a luat cheile de la automobilul de model „Peugeot 106” cu n/î NS AJ 939, ce aparţinea ultimului în bază procurii seria AF nr.946190, apoi a pătruns în automobilul „Peugeot 106” cu n/î NS AJ 939 parcat în stradă lîngă gospodăria lui Gheorghica Ion şi pornind motorul cu cheile luate din casă, s­a deplasat cu automobilul dat pe străzile satului Sturzovca, raionul Glodeni, fiind stopat în jurul orei 07.00, de către angajaţii de poliţie. Tot el, la data de 21.11.2015, în jurul orelor 07.20, după ce a răpit fără scop de însuşire autoturismul de model „Peugeot 106” cu n/î NS AJ 939, ce aparţinea lui XXXXXXXXX, în timp ce se deplasa pe străzile satului Sturzovca, raionul Glodeni fără a deţine permis de conducere, a fost stopat de către angajaţii de poliţie, iar în cadrul verificării actelor, XXXXXXXXX avea semne vizibile de stare de ebrietate, vorbă neclară, fapt care a trezit o bănuială rezonabilă precum că acesta conduce mijlocul de transport în stare de ebrietate, din care cauză ultimul a fost supus testării alcoolscopice şi examinării medicale la IMSP Spitalul raional Glodeni. Conform procesului­verbal nr.534 din 21.11.2015 s­a stabilit, că XXXXXXXXX Victor este în stare de ebrietate grad avansat, în urma testării alcoolscopice cu aparatul „Alcotest 3000”, concentraţia vaporilor de alcool în aerul expirat constituie 0,78 mg/1. Conform certificatului nr.69 din 08.12.2015 prezentat de către BÎT şi DCA Glodeni, XXXXXXXXX nu deţine permis de conducere. La începutul cercetării judecătoreşti, inculpatul Malai Maxim Victor, folosindu­se de dreptul său procesual, s­a dezis de la examinarea pricinii în procedura acordului de recunoaştere a vinovăţiei, încheiat în cadrul urmăririi penale, şi a depus cerere, potrivit prevederilor art.364/1 al.(l) CPP, prin care a declarat că, solicită examinarea cauzei în baza probelor administrate în faza urmăririi penale, pe care le recunoaşte şi asupra cărora nu are obiecţii, recunoscînd în totalitate faptele menţionate în rechizitoriu, indicînd că nu solicită alte probe, cerere care a fost admisă de către instanţă. Instanța de fond a pronunțat sentința în cauză în procedura prevăzută de art.364/1 CPP RM. Împotriva sentinţei în termen a declarat apel inculpatul XXXXXXXXX, care nu este de acord cu sentința instanței de fond în latura pedepsei stabilite, considerînd că pedeapsa aplicată în privința sa este prea dură. Solicită admiterea apelului, casarea sentinţei şi aplicarea unei pedepse mai blînde. În instanţa de apel inculpatul XXXXXXXXX a susţinut apelul declarat și a solicitat admiterea acestuia din motivele invocate, cu aplicarea în privința sa a unei pedepse neprivative de libertate. Avocatul Rotari Mihaela care l­a asistat, a susținut apelul declarat de inculpat și a solicitat admiterea acestuia în sensul declarat, cu casarea sentinței Judecătoriei Glodeni din 07.04.2016 şi pronunțarea unei noi hotărîri, prin care inulpatului să­i fie stabilită o pedeapsă nonprivativă

[Succeeded / Failed / Skipped / Total] 36 / 46 / 21 / 103:  82%|████████▏ | 82/100 [16:06<03:32, 11.79s/it]

--------------------------------------------- Result 103 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

xxxxNUMExxxx la 05.10.2014, aproximativ la orele 14 00, nedeţinînd permis de conducere, pe strada centrală din s. Pepeni r. Sîngerei, în ap domiciliul lui Spînachi Sergiu din acşi sat, conducea automobilul de model „Volkswagen Golf 3” cu nr. în. OR BK 756 şi încălcînd prevederile pct. 1 lit. b), din Regulamentul circţiei rutiere aprobat prin Hotărîrea Guvernului RM nr. 357 din 13.05.2009, care prevede că, persoana care conduce un aut trebuiă posede şi la cererea lucrătorului de poliţie, poliţistului de frontieră, ofiţerului echipei mobile a Serviciului Vamal, este obligată să înmînez control permisul de conducere perfectat pe numelău, valabil pentru categoria (subcategoria) din care face parte autovehiculul condus, pct. 45 alin. 1 l c), şi pct. 2), din acelaşi regulament potrivit căruia, conducătorul trebuie să conducă vehiculul în conformitate cu limita de viteză stabilită, ţinînd p seama de uătorii factori, starea psihofiziologică ce influenţează atenţia şi reacţia, dexteritatea în conducere care i­ar permite să prevadă situaţiile peri starea tehă a vehiculului şi particularităţile încărcăturii, situaţia rutieră şi în cazul în care în limita vizibilităţii apar obstacole care pot fi obse conător, el trebuie să reducă viteza sau chiar să oprească, pentru a nu pune în pericol siguranţa traficului, pct. 47 alin. 1), lit. a), din regulamentul no care prevedă limitele maxime de viteză a vehiculelor pe drumurile publice sînt în localităţi − 50 km/h şi ca rezultat nu s­a isprăvit cu ghidajul automobi derapat de pe carosabil un ­a tamponat pe pietonul Spînachi Sergiu care se afla pe acostament. În rezultatul impactului pietonul Spînache Sergiu a primit leziuni corporale grave periculoase pentru viaţă sub formă de traumă cranio­cerebrală î infiltrat hemoragic ţesuturile pericraniene hemoragie subdurală, hemoragie în ventriculii cerebrali, traumă închisă a toracelui cu ruptura disc j ţiunilor intervertebrale între vertebrele toracice 2 şi 3, 7 şi 8, fracturi directe a coastelor 2­10 pe linia axilară posterioră dreaptă şi 1­6 pe linia parav dreă cu infiltrate hemoragice în ţesuturile moi, două rupturi a aortei la nivel toracic, hematorace stînga – 200 ml, dreapta 300 ml, traumă î abdomenului cu zdrobirea ficatulşi hemoperitoneu ­500 ml, ruptură completă a ţesuturilor articulaţiei genunchiului stîng cu amputaţia gambei stîn echimoşi excoriaţii pe faţă, torace, abdomen şi membre. Tot el, la 05.10.2014, aproximativ la orele 14 00, după comiterea accidentului rutier cu cauzarea decesului lui Spînachi Sergiu din s. Pepeni r. inţionat, înţelegînd caracterul prejudiciabil al acţiunilor sale, în scopul de a se ascunde de organele urmăririi penale, a părăsit locul accidentul ţionat mai sus, prin ce a încălcat prevederile pct. 12 alin. 1)lit. a), b), c), f), din regulamentul circulaţiei rutier aprobat prin Hotărîrea Guvernului RM 13.05.2009, potriviăruia, conducătorul de vehicul implicat într­un accident în traficul rutier este obligat: să oprească imediat vehiculul semnaliz conformitate cu punctul 37 subpunctul 1) litera a) sau subpunctul 2) din prezentul Regulamenă nu schimbe poziţia vehiculului şi a obiectelor de pe provenite ca urmare a accidentului în traficul rutier, cu exţia cazurilor prevăzute în subpunctul 1) literele c) şi d) din prezentul punct; să acorde prim ăc heme ambulanţa în cazul în care în accident au fost cauzate traumatisme persoanelor,

[Succeeded / Failed / Skipped / Total] 37 / 46 / 23 / 106:  83%|████████▎ | 83/100 [16:16<03:19, 11.76s/it]

--------------------------------------------- Result 104 ---------------------------------------------
[[0 (99%)]] --> [[1 (63%)]]

Inculpaţii Cernei Vasile Valeriu, Rusu Eduard Igor, Roşcovan Alexandru Boris şi Ceban Serghei Victor la 13 mai 2013, în intervalul de timp 03.00­04.00, la o distanţă de aproximativ 100 m. de la Postul vamal intern “[[Rezina]] Pod”, [[aflîndu]]­se în stare de ebrietate alcoolică, împreună şi prin înţelegere prealabilă, fără careva motive întemeiate, din intenţii huliganice, încălcînd grosolan ordinea publică, exprimînd o [[obrăznicie]] deosebită i­a aplicat cet. Oprea Oleg Valeriu şi cet. [[Talpă]] Vitalie Ion, mai multe lovituri cu pumnii şi picioarele pe diferite părţi ale corpului [[cauzîndu]]­le ultimilor, potrivit concluziilor rapoartelor de constatare medico­legală nr. 1141/D din 23.05.2013 şi nr. 1142/D din 23.05.2013, vătămări corporale uşoare, deteriorîndu­le hainele acestora. De asemenea, în cadrul comiterii acţiunilor huliganice inculpaţii [[Cernei]] Vasile Valeriu şi Ceban Serghei Victor au sustras în mod deschis de la părţile vătămate Oprea Oleg Valeriu şi Talpă Vitalie Ion 2 telefoane mobile ce aparţineau acestora de model „Nokia E51” cu costul de 2000 lei şi „Nokia [[6120]] C” cu costul de 1000 lei, cauzîndu­le acestora daune materiale considerabile. Inculpaţii [[Cernei]] Vasile Valeriu, Rusu Eduard Igor, Roşcovan Alexandru Boris şi Ceban Serghei Victor [[pînă]] la [[începerea]] cercetării judecătoreşti au declarat personal prin înscris autentic, că recunosc săvîrşirea faptelor indicate în rechizitoriu şi solicită ca judecata să se facă pe baza probelor [[administarte]] în faza de [[urmărîre]] [[penală]] pe care li se cunoaşte şi asupra cărora nu au obiecţii. Procurorul şi avocaţii sînt de acord cu cererile inculpaţilor [[Cernei]] Vasile Valeriu, Rusu Eduard Igor, Roşcovan Alexandru Boris şi Ceban Serghei Victor. Prin încheierea din 05.12.2013 instanţa a admis [[cererile]] depuse de inculpaţii [[Cernei]] Vasile Valeriu, Rusu Eduard Igor, Roşcovan Alexandru Boris şi Ceban Serghei Victor, reieşind din fapt că, din probele administrate rezultă că faptele lor sînt stabilite şi sînt suficiente date cu privire la persoanele săi pentru a permite stabilirea unei [[pedepse]]. Fiind audiaţi în calitate de martori, inculpaţii Cernei Vasile Valeriu, Rusu Eduard Igor, Roşcovan Alexandru Boris şi Ceban Serghei Victor au declarat în şedinţa de judecată că în noaptea de 12 spre 13 mai 2013 toţi patru cu automobilul condus de Rusu Eduard au venit din sat. Solonceni spre or. [[Rezina]] la barul „Cetate” situat în apropierea Postul vamal intern “Rezina Pod”. Ajungînd la barul menţionat, Cernei Vasile Valeriu, Ceban Serghei Victor şi Roşcovan Alexandru Boris au servit cîte o bere apoi toţi au ieşit afară să fumeze. În timp ce se aflau afară au făcut cunoştinţă cu cet. Oprea Oleg Valeriu şi cet. Talpă Vitalie Ion persoane pe care anterior nu­i cunoştiau, ultimii fiind în stare de ebrietate alcoolică. În timpul discuţiei Oprea Oleg şi cet. Talpă Vitalie le­au propus acestora să­i transporte cu automobilul lui Rusu Eduard în or. Rezina, în schimbul că aceştia să­i servească cu bere la ce Rusu Eduard, Cernei Vasile, Ceban Serghei şi Roşcovan Alexandru au căzut de acord. Astfel toţi şase s­au urcat în automobilul condus de Rusu Eduard şi s­au pornit în direcţia or. Rezina. În drum s­au oprit la barul „Nistru” pe care toţi îl cunosc şi ca barul „Petrovca” situat nemijlocit lîngă Postul vamal intern “Rezina Pod” unde Cernei Vasile,

Inculpaţii Cernei Vasile Valeriu, Rusu Eduard Igor, Roşcovan Alexandru Boris şi Ceban Serghei Victor la 13 mai 2013, în intervalul de timp 03.00­04.00, la o distanţă de aproximativ 100 m. de la Postul vamal intern “[[Reizna]] Pod”, [[aflîdnu]]­se în stare de ebrietate alcoolică, împreună şi prin înţelegere prealabilă, fără careva motive întemeiate, din intenţii huliganice, încălcînd grosolan ordinea publică, exprimînd o [[obrzănicie]] deosebită i­a aplicat cet. Oprea Oleg Valeriu şi cet. [[Taplă]] Vitalie Ion, mai multe lovituri cu pumnii şi picioarele pe diferite părţi ale corpului [[cauznîdu]]­le ultimilor, potrivit concluziilor rapoartelor de constatare medico­legală nr. 1141/D din 23.05.2013 şi nr. 1142/D din 23.05.2013, vătămări corporale uşoare, deteriorîndu­le hainele acestora. De asemenea, în cadrul comiterii acţiunilor huliganice inculpaţii [[Cenrei]] Vasile Valeriu şi Ceban Serghei Victor au sustras în mod deschis de la părţile vătămate Oprea Oleg Valeriu şi Talpă Vitalie Ion 2 telefoane mobile ce aparţineau acestora de model „Nokia E51” cu costul de 2000 lei şi „Nokia [[6210]] C” cu costul de 1000 lei, cauzîndu­le acestora daune materiale considerabile. Inculpaţii [[Cenrei]] Vasile Valeriu, Rusu Eduard Igor, Roşcovan Alexandru Boris şi Ceban Serghei Victor [[pnîă]] la [[înecperea]] cercetării judecătoreşti au declarat personal prin înscris autentic, că recunosc săvîrşirea faptelor indicate în rechizitoriu şi solicită ca judecata să se facă pe baza probelor [[admiinstarte]] în faza de [[urmăîrre]] [[penlaă]] pe care li se cunoaşte şi asupra cărora nu au obiecţii. Procurorul şi avocaţii sînt de acord cu cererile inculpaţilor [[Crenei]] Vasile Valeriu, Rusu Eduard Igor, Roşcovan Alexandru Boris şi Ceban Serghei Victor. Prin încheierea din 05.12.2013 instanţa a admis [[cererlie]] depuse de inculpaţii [[Crenei]] Vasile Valeriu, Rusu Eduard Igor, Roşcovan Alexandru Boris şi Ceban Serghei Victor, reieşind din fapt că, din probele administrate rezultă că faptele lor sînt stabilite şi sînt suficiente date cu privire la persoanele săi pentru a permite stabilirea unei [[pdeepse]]. Fiind audiaţi în calitate de martori, inculpaţii Cernei Vasile Valeriu, Rusu Eduard Igor, Roşcovan Alexandru Boris şi Ceban Serghei Victor au declarat în şedinţa de judecată că în noaptea de 12 spre 13 mai 2013 toţi patru cu automobilul condus de Rusu Eduard au venit din sat. Solonceni spre or. [[Rzeina]] la barul „Cetate” situat în apropierea Postul vamal intern “Rezina Pod”. Ajungînd la barul menţionat, Cernei Vasile Valeriu, Ceban Serghei Victor şi Roşcovan Alexandru Boris au servit cîte o bere apoi toţi au ieşit afară să fumeze. În timp ce se aflau afară au făcut cunoştinţă cu cet. Oprea Oleg Valeriu şi cet. Talpă Vitalie Ion persoane pe care anterior nu­i cunoştiau, ultimii fiind în stare de ebrietate alcoolică. În timpul discuţiei Oprea Oleg şi cet. Talpă Vitalie le­au propus acestora să­i transporte cu automobilul lui Rusu Eduard în or. Rezina, în schimbul că aceştia să­i servească cu bere la ce Rusu Eduard, Cernei Vasile, Ceban Serghei şi Roşcovan Alexandru au căzut de acord. Astfel toţi şase s­au urcat în automobilul condus de Rusu Eduard şi s­au pornit în direcţia or. Rezina. În drum s­au oprit la barul „Nistru” pe care toţi îl cunosc şi ca barul „Petrovca” situat nemijlocit lîngă Postul vamal intern “Rezina Pod” unde Cernei Vasile,


--------------------------------------------- Result 105 ---------------------------------------------
[[0 (99%)]] --> [[[SKIPPED]]]

Prin decizia Curții de Apel Chișinău din 04.07.2013 G G a fost condamnat în baza art.264 alin.(4), art.266, art.84 CP la 6 ani închisoare cu ispășirea pedepsei în penitenciar de tip semiînchis, cu privarea de dreptul de a conduce mijloace de transport pe un termen de 4 ani. Începutul termenului – 04.06.2013; Sfîrșitul termenului – 03.06.2019. Condamnatul ispășește pedeapsa în Penitenciarul nr.2 Lipcani. Condamnatul G G a înaintat un demers privind schimbarea regimului de detenție și transferarea sa în regim de resocializare. Acest demers a fost respins de comisia Penitenciarului nr.2 Lipcani pe motiv, că condamnatul la moment nu întrunește condițiile prevăzute de art.282 Cod de executare. Condamnatul a depus împotriva respectivei hotărîri plîngere în instanță, iar de către judecătoria Briceni a fost adoptată încheierea nominalizată. Dezacord cu încheierea instanței de fond a declarat condamnatul G G. Recurentul invocă faptul, că el întrunește condițiile legale pentru transfer la regim de resocializare, însă atît comisia penitenciarului cît și instanța de fond au interpretat eronat prevederile legii. Solicită admiterea recursului, casarea încheierii judecătoriei Briceni din 27.10.2015 cu admiterea cererii condamnatului privind schimbarea regimului de detenție ca fiind întemeiată. Condamnatul G G nu a fost prezent în ședința instanței de recurs, acesta solicitînd prin recursul declarat examinarea cauzei în lipsa sa, interesele condamnatului au fost apărate de către avocatul N.Prepelița care a solicitat admiterea recursului pe motivele invocate în el. Reprezentantul penitenciarului nr.2 Lipcani în ședința instanței nu s­a prezentat, instanța considerînd posibilă examinarea cauzei în lipsa acestuia. Procurorul participant solicită respingerea recursului declarat de condamnat ca nefundat. Verificînd argumentele recurentului, ascultînd participanţii, studiind materialele cauzei, colegiul penal consideră, că recursul condamnatului urmează a fi respins ca nefondat. Conform prevederilor art.449 alin.(1) pct.1) lit.a) CPP ,, Judecînd recursul, instanţa adoptă una din următoarele decizii 1) respinge recursul, menţinînd hotărîrea atacată, dacă a) recursul este nefondat;” Argumentele invocate de condamnatul G G, privind schimbarea regimului de detenție, sînt nefondate şi contravin prevederilor art.282 alin.(1) CE care stabileşte: „În cazul eliberării condiţionate înainte de termen, în scopul pregătirii pentru eliberare, cu cel puţin 6 luni înainte de expirarea termenului de executare a pedepsei închisorii, condamnaţii care îşi execută pedeapsa în regim comun şi care nu au sancţiuni disciplinare nestinse sînt transferaţi în regim de resocializare.” Aceste prevederi ale normelor procesuale au fost respectate de către Judecătoria Briceni la examinarea demersului condamnatului privind schimbarea regimului de detenție. În cele din urmă, Colegiul penal constată, că instanţa de judecată corect a ajuns la concluzia privind respingerea ca nefondată a cererii cu privire la schimbarea regimului de detenție, dat fiind, că condamnatul G G execută pedeapsa în penitenciarul nr.2 Lipcani fiindui stabilită spre executare conform sentinței categoria penitenciarului de tip semiînchis. Începutul termenului – 04.06.2013; Sfîrșitul termenului – 03.06.2019. Astfel instanța de fond întemeiat și legal a stabilit posibilitatea de aplicare a prevederilor art.282 Cod de executare doar cu 6 luni înainte de intervenirea termenului posibilei liberări condiționate înainte de termen – 04.07.2017 ( la ispășirea a 2/3 din pedeapsă). Din aceste considerente Colegiul penal consideră motivele invocate în recurs ca nefondate şi necesar a fi respinse. Conducîndu­se de art.447­449


--------------------------------------------- Result 106 ---------------------------------------------
[[1 (93%)]] --> [[[SKIPPED]]]

Pentru a se pronunţa în sensul celor expuse instanţa de fond a reţinut că I.N. a fost învinuită de faptul că „ea la 27.04.2011 în jurul orelor 23.30, aflîndu­se sub influenţa băuturilor alcoolice la domiciliul propriu, situat în satul ­­­ comuna ­­­ raionul ­­­, pe seama relaţiilor ostile apărute între ea şi concubinul ei C.V., exprimate prin suspectarea ultimului în deţinerea relaţiilor intime cu P.A., urmărind scopul de pricinuire a leziunilor corporale şi vătămărilor corporale, intenţionat, cu ajutorul unui ciocan, cît şi cu pumnii şi picioarele, i­a aplicat multiple lovituri asupra corpului lui C.V., preponderent în regiunea capului şi pieptului, pricinuindu­i astfel conform raportului de expertiză medico­legală nd.89 D din 01.08.2011, leziuni corporale grave, periculoase pentru viaţă, sub formă de traumă cranio­cerebrală închisă, echimoze în regiunea feţei (în jurul ambilor ochi, frontal pe dreapta), hemoragii în ţesuturile moi epicraniene (frontal pe dreapta, parietală pe stînga şi occipital pe centru) hematom masiv subdural parieto­ temporal­bazal pe dreapta care au provocat decesul victimei C.V.”. În termen sentinţa a fost atacată cu apel de către procurorul procuraturii raionului Făleşti Paladi Tudor, care în motivare invocă ilegalitatea sentinţei cu indicarea următoarelor argumente: ­ concluzia instanţei de fond precum că vina inculpatei în comiterea infracţiunii incriminate nu a fost dovedită din motiv că nu au fost prezentate probe ce dovedesc vina ei este greşită, deoarece, atît în cadrul urmăririi penale, cît şi în cadrul cercetării judecătoreşti, reieşind din probele prezentate de acuzator în instanţa de judecată şi examinate, vinovăţia inculpatei I.N. a fost pe deplin dovedită, iar sentinţa urmează a fi anulată, ­ instanţa de fond nu a apreciat declaraţiile martorului P.A., care în cadrul urmăririi penale a dat declaraţii prin care a adeverit faptul prezenţei sale în seara din 27 spre 28.04.2011 în casa lui I.N. cînd ultima l­a maltratat pe V.C. cu un melesteu, apoi fiind audiată în şedinţa de judecată a declarat că C.V. nu a fost maltratat de I.N., ci de trei bărbaţi necunoscuţi, ulterior fiind audiată suplimentar în aceiaşi zi P.A. a declarat că a dat declaraţii contrare pe motiv că a fost ameninţată cu răfuială fizică de prietenii de gaşcă al inculpatei din or.­­­, instanţa neapreciind declaraţiile martorului din punct de vedere a veridicităţii lor, în coraborare cu declaraţiile succesorului victimei C.O., ­ versiunea că nu de către I.N. i­au fost cauzate leziunile corporale grave victimei, în urma cărora a survenit decesul, instanţa urma să o aprecieze critic pe motiv a existenţei divergenţelor între declaraţiile succesorului victimei date în cadrul urmăririi penale, menţinute în instanţa de judecată, şi pe de altă parte a declaraţiilor martorului Ş.P., inclupatei N.I. şi apoi chiar şi martorului A.P., care doar iniţial şi­a schimbat declaraţiile în timpul audierii sale în calitate de martor în instanţa de judecată, fiindcă reiese faptul că ultimii au luat o versiune de apărare asupra inculpatei N.I., motiv din care ambele versiuni sunt contrare, dînd o bănuială rezonabilă de crezut că victima prin aceasta la fel a încercat de a ascunde acţiunile criminale a inculpatei, ­ în motivaţia sa instanţa de fond nu a luat în consideraţie şi nici nu le­a consemnat

[Succeeded / Failed / Skipped / Total] 38 / 46 / 23 / 107:  84%|████████▍ | 84/100 [16:25<03:07, 11.73s/it]

--------------------------------------------- Result 107 ---------------------------------------------
[[0 (97%)]] --> [[1 (70%)]]

[[Pentru]] a se pronunţa în sensul celor expuse instanţa de fond a reţinut că xxxxNUMExxxx la data de 23.01.2015, aproximativ pe la orele 01.00, avînd intenţie de profit şi îmbogăţire, fiind în stare de ebrietate şi aflînduse în casa cet.xxxxNUMExxxx a.n.xxx şi cet.xxxxNUMExxxx a.n.xxx – locuitori s.xxx raionul xxx, intenţionat i­a atacat şi le­a aplicat multiple lovituri cu pumnii în regiunea feţei lui xxxxNUMExxxx care este invalid de gradul I şi este [[paralizată]], după ce a încercat să o stranguleze cu mîinile, apoi l­a atacat pe cet.xxxxNUMExxxx aplicîndu­i multiple lovituri cu pumnii în regiunea feţei şi cu un cuţit de bucătărie pe care l­a luat de pe masă din casă şi i­a aplicat o lovitură în regiunea feţei, ulterior în mod deschis a sustras de sub perna pe care dormea cet.xxxxNUMExxxx bani în sumă de 20000 lei cauzîndu­i o pagubă materială considerabilă. Conform raportului de expertiză medico­legală cu nr.22 D din 26.01.2015 cet.xxxxNUMExxxx s­a ales cu comoţia cerebrală, echimozele multiple la faţă şi antibraţe, plaga la limbă, ce se califică ca vătămări corporale uşoare cu dereglarea sănătăţii de scurtă durată. Conform raportului de expertiză medico­legală cu nr.67 din 26.01.2015 cet.xxxxNUMExxxx s­a ales cu comoţia cerebrală, echimozele şi plăgile contuze la faţa, ce se califică ca vătămări corporale uşoare cu dereglarea sănătăţii de scurtă durată. Cauza penală a fost examinată în baza probelor administrate în faza de urmărire penală în baza art.364/1 CPP RM. În termen sentinţa a fost atacată cu apel de către inculpatul xxxxNUMExxxx, care în motivare invocă că nu este deacord cu sentința instanței de fond, s­a aflat în stare de ebrietate și nu înțelegea ce face, a recunoscut vina pedeplin și sincer se căiește în cele comise, a restituit părții vătămate o parte din prejudiciu, solicitînd examinarea cauzei și a lua în vedere faptul că are mama invalidă de grupa II și în afară de el nu are cine s­o ajute. Inculpatul xxxxNUMExxxx în ședința instanței de apel a [[susținut]] [[apelul]] depus și a declarat că recunoaște vina și se căiește sincer de cele comise, a restituit o parte din prejudiciu cauzat, solicitînd aplicarea unei pedepse mai blînde, luînd în vedere că are mamă invalidă. Avocatul inculpatului xxxxNUMExxxx, Dragan Natalia în ședința instanței de apel a susținut apelul declarat de inculpat, a declarat că inculpatul a recunoscut vina, se căiește sincer, a întreprins măsuri de a recupera prejudiciul, are la întreținere mama invalidă, motive care i­ar permite instanței aplicarea unei pedepse mai blînde, nonprivative de libertate. Reprezentantul părților vătămate xxxxNUMExxxx și xxxxNUMExxxx, în baza procurii din 06.05.2015, xxx în ședința instanței de apel a solicitat respingerea apelului declarat de inculpat, cu menținerea sentinței instanței de fond fără modificări. În ședința instanței de apel procurorul Prisacari Lilia a solicitat respingerea apelului declarat de inculpat ca neîntemeiat, cu menținerea sentinței instanței de fond ca legală, deoarece consideră că instanța de fond a luat în considerație circumstanțele de fapt și de drept, a dat o apreciere corectă acțiunilor inculpatului, luînd în vedere personalitatea inculpatului care la locul de trai se caracterizează negativ, care a comis infracțiunea față de părțile vătămate care sunt

[[Penrtu]] a se pronunţa în sensul celor expuse instanţa de fond a reţinut că xxxxNUMExxxx la data de 23.01.2015, aproximativ pe la orele 01.00, avînd intenţie de profit şi îmbogăţire, fiind în stare de ebrietate şi aflînduse în casa cet.xxxxNUMExxxx a.n.xxx şi cet.xxxxNUMExxxx a.n.xxx – locuitori s.xxx raionul xxx, intenţionat i­a atacat şi le­a aplicat multiple lovituri cu pumnii în regiunea feţei lui xxxxNUMExxxx care este invalid de gradul I şi este [[parailzată]], după ce a încercat să o stranguleze cu mîinile, apoi l­a atacat pe cet.xxxxNUMExxxx aplicîndu­i multiple lovituri cu pumnii în regiunea feţei şi cu un cuţit de bucătărie pe care l­a luat de pe masă din casă şi i­a aplicat o lovitură în regiunea feţei, ulterior în mod deschis a sustras de sub perna pe care dormea cet.xxxxNUMExxxx bani în sumă de 20000 lei cauzîndu­i o pagubă materială considerabilă. Conform raportului de expertiză medico­legală cu nr.22 D din 26.01.2015 cet.xxxxNUMExxxx s­a ales cu comoţia cerebrală, echimozele multiple la faţă şi antibraţe, plaga la limbă, ce se califică ca vătămări corporale uşoare cu dereglarea sănătăţii de scurtă durată. Conform raportului de expertiză medico­legală cu nr.67 din 26.01.2015 cet.xxxxNUMExxxx s­a ales cu comoţia cerebrală, echimozele şi plăgile contuze la faţa, ce se califică ca vătămări corporale uşoare cu dereglarea sănătăţii de scurtă durată. Cauza penală a fost examinată în baza probelor administrate în faza de urmărire penală în baza art.364/1 CPP RM. În termen sentinţa a fost atacată cu apel de către inculpatul xxxxNUMExxxx, care în motivare invocă că nu este deacord cu sentința instanței de fond, s­a aflat în stare de ebrietate și nu înțelegea ce face, a recunoscut vina pedeplin și sincer se căiește în cele comise, a restituit părții vătămate o parte din prejudiciu, solicitînd examinarea cauzei și a lua în vedere faptul că are mama invalidă de grupa II și în afară de el nu are cine s­o ajute. Inculpatul xxxxNUMExxxx în ședința instanței de apel a [[susțiunt]] [[aeplul]] depus și a declarat că recunoaște vina și se căiește sincer de cele comise, a restituit o parte din prejudiciu cauzat, solicitînd aplicarea unei pedepse mai blînde, luînd în vedere că are mamă invalidă. Avocatul inculpatului xxxxNUMExxxx, Dragan Natalia în ședința instanței de apel a susținut apelul declarat de inculpat, a declarat că inculpatul a recunoscut vina, se căiește sincer, a întreprins măsuri de a recupera prejudiciul, are la întreținere mama invalidă, motive care i­ar permite instanței aplicarea unei pedepse mai blînde, nonprivative de libertate. Reprezentantul părților vătămate xxxxNUMExxxx și xxxxNUMExxxx, în baza procurii din 06.05.2015, xxx în ședința instanței de apel a solicitat respingerea apelului declarat de inculpat, cu menținerea sentinței instanței de fond fără modificări. În ședința instanței de apel procurorul Prisacari Lilia a solicitat respingerea apelului declarat de inculpat ca neîntemeiat, cu menținerea sentinței instanței de fond ca legală, deoarece consideră că instanța de fond a luat în considerație circumstanțele de fapt și de drept, a dat o apreciere corectă acțiunilor inculpatului, luînd în vedere personalitatea inculpatului care la locul de trai se caracterizează negativ, care a comis infracțiunea față de părțile vătămate care sunt

[Succeeded / Failed / Skipped / Total] 38 / 47 / 24 / 109:  85%|████████▌ | 85/100 [16:38<02:56, 11.75s/it]

--------------------------------------------- Result 108 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

La 23 august 2009 pe la orele 02.20 în or.Soroca pe str.Ştefan cel Mare, lîngă staţia de alimentare cu petrol „Lukoil” inculpatul xxxxNUMExxxx, care conducea automobilul de model „Opel­Vectra” cu nr.înm.C MH 620, a fost stopat de echipajul mobil al poliţiei rutiere CPR Soroca. În cadrul verificării actelor inculpatul xxxxNUMExxxx. a fost suspectat de consum de alcool şi i s­a propus să treacă examenul medical în vederea stabilirii faptului dacă a consumat sau nu băuturi alcoolice, şi a fost îndreptat la Spitalul raional Soroca. La spital, în cadrul examenului medical pentru stabilirea stării de ebrietate şi naturii ei, în prezenţa colaboratorului poliţiei rutiere a CPR Soroca V.Leşan şi a medicilor L.O. şi N.B., inculpatul xxxxNUMExxxx categoric a refuzat de la recoltarea probelor biologice. În şedinţa judiciară inculpatul şi­a recunoscut vinovăţia integral, a confirmat semnarea acordului de recunoaştere a vinovăţiei şi faptul că acesta corespunde voinţei lui. A povestit detaliat despre circumstanţele săvîrşirii infracţiunii şi s­a căit de cele comise, a promis să nu mai admită derogări de lege. A rugat să nu fie aspru pedepsit, să nu fie privat de dreptul de a conduce mijlocul de transport deoarece nu are loc de muncă şi cu automobilul îşi asigură existenţa. Despre vinovăţia inculpatului mai probează: ­ declaraţiile martorilor: L. V., potrivit căror la 23.08.2009 în timpul serviviului de asigurare a securităţii la traficul rutier, în preajma staţiei de alimentare cu petrol „Lukoil” din microraionul Soroca Nouă, dînsul a stopat automobilul condus de xxxxNUMExxxx. În timpul verificării actelor dînsul a simţit miros de alcool şi i­a propus conducătorului auto să treacă examenul medical. Iniţial xxxxNUMExxxx. a refuzat, apoi s­a lăsat convins şi a fost condus la spitalul raional. În cabinetul de proceduri din incinta instituţiei medicale, după ce medicul B. N. i­a explicat lui xxxxNUMExxxx. modalitatea de examinare medicală şi modul de prelevare a probelor biologice, ultimul a refuzat de la prelevarea probelor indicate. Fiind preîntîmpinat de răspundere penală pentru refuz de la prelevarea probelor biologice pentru stabilirea consumului de alcool şi aprecierea stării de ebrietate, xxxxNUMExxxx. şi­a menţinut poziţia anteriaoră, ­ p.d.17; B. N. şi O. L. ; conform căror la 23.08.2009 pe la orele 22.25 în secţia de internare a spitalului raional Soroca s­au prezentat inspectorul superior al SPR a CPR Soroca L. V. cu persoana xxxxNUMExxxx, care era bănuit de conducerea mijlocului de transport în stare de ebrietate şi urma să fie supus examinării medicale în vederea stabilirii faptului consumului de alcool şi să­i fie prelevate probele biologice de sînge. xxxxNUMExxxx. a refuzat examinarea medicală şi prelevarea probelor biologice, zicînd că are tot dreptul să refuze. Şi­a menţinut poziţia şi după ce inspectorul superior al SPR – L. V. i­a explicat că în cazul refuzului urmează răspunderea penală, ­ p.d.18, 19; ­ procesul verbal din 23.08.2009 al examinării medicale, în care este indicat refuzul lui xxxxNUMExxxx. de la colectarea probelor biologice, ­ p.d.10­11; ­ corpul delict – permisul de conducere pe numele xxxxNUMExxxx, ­ p.d.12. Analizînd şi apreciind probele cercetate, instanţa încadrează juridic acţiunile lui xxxxNUMExxxx în baza art.2641 al.(3) Cod penal – refuzul conducătorului mijlocului de transport de la recoltarea


--------------------------------------------- Result 109 ---------------------------------------------
[[0 (99%)]] --> [[[SKIPPED]]]

Inculpatul Condratiuc Vasile fiind în relaţii oficiale de căsătorie din anul 1996 cu cet. Condratiuc Elena, locuind împreună în domiciliul mamei ultimei Goncearuc Olga, situat în sat. Rădoaia, Sângerei, împreună cu mama soacră Olga Goncearuc şi copiii lor comuni minori Mihail, născut la 21.04.1999, Andrei născut la 12.12.2002, Nicolae, născut la 16.05.2006 şi Condratiuc Ana, născută la 25.02.2009, fiind în grija, educaţia şi întreţinerea inculpatului, la 20 octombrie 2014, apoximativ la ora 08.00, aflându­se în domiciliul sus­numit, fiind în stare de ebrietate alcoolică, intenționat, înțelegând caracterul prejudiciabil al acțiunilor sale, din motivul relațiilor ostile apărute spontan, s­a certat şi i­a făcut scandal soţiei sale Elena, apoi având un comportament agresiv, violent, impulsiv, a numit­o pe ultima cu cuvinte necenzurate, astfel jignindu­i onoarea, demnitatea şi cinstea, ulterior i­a aplicat două lovituri cu pumnul în regiunea capului şi a spatelui, astfel cauzându­i dureri fizice. Toate aceste acţiuni efectuate în privinţa soţiei sale Elena, au fost petrecute în prezenţa copiilor săi minori Condratiuc Mihail, Condratiuc Andrei, Condratiuc Nicolae şi Condratiuc Ana, ultimii au început a plânge şi în rezultatul căruia au suportat suferinţe psihice şi prejudiciu moral, iar Condratiuc Elena reuşind să scape din mâinile lui a fugit de la faţa locului la vecina lor Liuba Bodrug, iar comportamentul lui Condratiuc Vasile agresiv, violent şi impulsiv a durat aproximativ vreo 10­15 minute. Tot el, la 20.10.2014 pe la orele 12:00 – 13:00 aflîndu­se în gospodăria sus­menţionată, acţionînd intenționat, înțelegând caracterul prejudiciabil al acțiunilor sale, fiind în stare de ebrietate alcoolică, din motivul relațiilor ostile apărute spontan, avînd un comportament agresiv şi violent, s­a certat şi i­a făcut scandal mamei soacre Olga Goncearuc, a numit­o pe ultima cu cuvinte necenzutare, astfel jignindu­i cinstea, onoarea şi demnitatea, apoi a îmbrâncit­o de la sine de pe pragul casei, în urma căruia Olga Goncearuc a suportat dureri fizice şi suferinţe psihice. Tot el, la 22.12.2014, în timpul zilei, acţionînd intenționat, înțelegând caracterul prejudiciabil al acțiunilor sale, fiind în stare de ebrietate alcoolică, aflându­se în gospodăria sa, din motivul relațiilor ostile apărute spontan, având un comportament agresiv şi violent, s­a certat şi a numit­o cu cuvinte necenzurate pe soţia sa Condratiuc Elena şi copiii lui. Tot el, la 15.01.2015, aproximativ pe la orele 07:30, înțelegând caracterul prejudiciabil al acțiunilor sale, acţionând intenționat, fiind în stare de ebrietate alcoolică, i­a numit cu cuvinte necenzutare, pe soţia sa Condratiuc Elena, iar pe soacra sa, Goncearuc Olga a lovit­o cu mâinile şi picioarele peste diferite părţi ale corpului cauzându­i dureri fizice. Tot el, la 27.01.2015, aproximativ pe la orele 19:00, aflîndu­se în stare de ebrietate alcoolică, înțelegând caracterul prejudiciabil al acțiunilor sale, intenționat a aplicat violenţă fizică în privinţa soacrei Goncearuc Olga, ulterior a insultat­o şi a ameninţat­o verbal în propria casă, a îmbrâncit­o la care a căzut jos, aplicându­i 4 lovituri cu piciorul în spate, astfel cauzându­i leziuni corporale neînsemnate sub formă de echimoză regiunea lombară centru. Pe parcursul examinării cauzei procurorul XXXXXXXXX, procuror din cadrul Procuraturii Sângerei, jurist de rangul I, a solicitat încetarea procesului penal în legătură cu intervenirea decesului inculpatului Condratiuc Vasile. Avocatul Larisa Ganuşceac, cabinet individual de avocat

[Succeeded / Failed / Skipped / Total] 39 / 47 / 24 / 110:  86%|████████▌ | 86/100 [16:47<02:44, 11.72s/it]

--------------------------------------------- Result 110 ---------------------------------------------
[[0 (97%)]] --> [[1 (50%)]]

[[xxxxNUMExxxx]] la data de 14.10.2013, aproximativ la ora 02.30, în mod intenţionat, acţionînd împreună cu Zahariaş Maxim Saveli, cauza în privinţa căruia a fost judecată în mod separat, urmărind scopul sustragerii bunurilor altei persoane, aflîndu­se pe adresa: mun.Bălţi, strada Chişinăului, lîngă casa de locuit nr.8/1, s­au apropiat de xxxxNUMExxxx şi xxxxNUMExxxxetru, asupra cărora, aplicînd violenţă nepericuloasă pentru viaţa şi sănătatea lui xxxxNUMExxxx, l­au lovit cu mîinile şi picioarele peste diferite părţi ale corpului, prin ce i­au cauzat leziuni corporale neînsemnate, după care în mod deschis l­au deposedat pe xxxxNUMExxxxetru de bani în valoare totală de 3000 ruble ruseşti, echivalent a 1200 lei, iar mai apoi cu cele sustrase s­au eschivat de la locul comiterii infracţiunii, pricinuindu­i astfel părţilor vătămate xxxxNUMExxxx şi [[Ambarian]] Petru o daună materială în proporţii considerabile. Inculpatul xxxxNUMExxxx, s­a eschivat de la prezentare în instanţa de judecată, iar prin încheierea instanţei din 15 iulie 2014 (f.d. 181) [[inculpatul]] a fost anunţat în căutare, fiind ulterior intentat de către IP Bălţi dosarul de căutare nr.[[2014040166]]. Totodată, este necesar a menţiona că inculpatul xxxxNUMExxxx s­a aflat prezent în cadrul şedinţei de judecată din 20.01.2014 (f.d. 96) cînd de către judecătorul precedent investit cu [[judecarea]] prezentei cauze s­a anunţat că pe rolul Judecătoriei Bălţi se află spre judecare respectiva cauză; dînsul de altfel, fiind prezent şi cadrul şedinţei de judecată din 29.05.2014 în cadrul şedinţei judiciare petrecute de precedentul judecător unde s­a dat citire rechizitoriului, s­a chestionat inculpatul asupra cunoaşterii esenţei acuzaţiilor aduse împotriva sa; părţile vătămate: xxxxNUMExxxx şi xxxxNUMExxxx au fost audiate în prezenţa dînsului. În aceste circumstanţe şi odată ce instanţa a stabilit că inculpatul xxxxNUMExxxx cunoaşte despre esenţa acuzaţiilor aduse de procuror împotriva sa; despre prezenţa spre judecare a prezentei cauze pe rolul Judecătoriei Bălţi; despre faptul că este obligat să se prezinte la şedinţele de judecată (f.d. 169); în condiţiile în care s­a eschivat de la ulterioarele prezenţe la şedinţele judiciare, neînştiinţînd instanţa [[despre]] motivele sale de neprezentă, odată ce el a fost anunţat în căutare cu pornirea în privinţa lui a unui dosar în căutare, instanţa de judecată în temeiul art. 321 alin.2 pct. 1 CPP, a dispus judecarea prezentei cauze în absenţa inculpatului xxxxNUMExxxx. În condiţiile absenţei inculpatului de la şedinţa de judecată instanţa de judecată a purces la judecarea cauzei, ţinînd cont de principiul prezumţiei nevinovăţiei. Vinovăţia inculpatului xxxxNUMExxxx instanţa de judecată o constată reeşind din următoarele probe. Reeşind din declaraţiile părţii vătămate ­ xxxxNUMExxxx, urmează că la data de 13.10.2013, fratele său xxxxNUMExxxx a venit în Republica Moldova din Federaţia Rusă, unde a fost la muncă. Aproximativ pe la orele 02.00 se aflau împreună cu fratele său xxxxNUMExxxx în barul „Topolea”; la o anumită perioadă de timp fratele său ­ xxxxNUMExxxx, a ieşit afară să fumeze, lipsind de la masă timp de 10­15 minute. Atunci a ieşit afară să vadă ce face fratele său şi a observat cum ultimul discută cu inculpaţii Cazacu Alexandru şi Zahariaş Maxim. Din discuţia lor a înţeles că inculpaţilor nu le­a plăcut cum este îmbrăcat fratele său. I­a propus inculpatului Zahariaş Maxim, să discute împreună. Ulterior l­a invitat pe

[[xxxxNUEMxxxx]] la data de 14.10.2013, aproximativ la ora 02.30, în mod intenţionat, acţionînd împreună cu Zahariaş Maxim Saveli, cauza în privinţa căruia a fost judecată în mod separat, urmărind scopul sustragerii bunurilor altei persoane, aflîndu­se pe adresa: mun.Bălţi, strada Chişinăului, lîngă casa de locuit nr.8/1, s­au apropiat de xxxxNUMExxxx şi xxxxNUMExxxxetru, asupra cărora, aplicînd violenţă nepericuloasă pentru viaţa şi sănătatea lui xxxxNUMExxxx, l­au lovit cu mîinile şi picioarele peste diferite părţi ale corpului, prin ce i­au cauzat leziuni corporale neînsemnate, după care în mod deschis l­au deposedat pe xxxxNUMExxxxetru de bani în valoare totală de 3000 ruble ruseşti, echivalent a 1200 lei, iar mai apoi cu cele sustrase s­au eschivat de la locul comiterii infracţiunii, pricinuindu­i astfel părţilor vătămate xxxxNUMExxxx şi [[Ambraian]] Petru o daună materială în proporţii considerabile. Inculpatul xxxxNUMExxxx, s­a eschivat de la prezentare în instanţa de judecată, iar prin încheierea instanţei din 15 iulie 2014 (f.d. 181) [[inuclpatul]] a fost anunţat în căutare, fiind ulterior intentat de către IP Bălţi dosarul de căutare nr.[[2014041066]]. Totodată, este necesar a menţiona că inculpatul xxxxNUMExxxx s­a aflat prezent în cadrul şedinţei de judecată din 20.01.2014 (f.d. 96) cînd de către judecătorul precedent investit cu [[jduecarea]] prezentei cauze s­a anunţat că pe rolul Judecătoriei Bălţi se află spre judecare respectiva cauză; dînsul de altfel, fiind prezent şi cadrul şedinţei de judecată din 29.05.2014 în cadrul şedinţei judiciare petrecute de precedentul judecător unde s­a dat citire rechizitoriului, s­a chestionat inculpatul asupra cunoaşterii esenţei acuzaţiilor aduse împotriva sa; părţile vătămate: xxxxNUMExxxx şi xxxxNUMExxxx au fost audiate în prezenţa dînsului. În aceste circumstanţe şi odată ce instanţa a stabilit că inculpatul xxxxNUMExxxx cunoaşte despre esenţa acuzaţiilor aduse de procuror împotriva sa; despre prezenţa spre judecare a prezentei cauze pe rolul Judecătoriei Bălţi; despre faptul că este obligat să se prezinte la şedinţele de judecată (f.d. 169); în condiţiile în care s­a eschivat de la ulterioarele prezenţe la şedinţele judiciare, neînştiinţînd instanţa [[dsepre]] motivele sale de neprezentă, odată ce el a fost anunţat în căutare cu pornirea în privinţa lui a unui dosar în căutare, instanţa de judecată în temeiul art. 321 alin.2 pct. 1 CPP, a dispus judecarea prezentei cauze în absenţa inculpatului xxxxNUMExxxx. În condiţiile absenţei inculpatului de la şedinţa de judecată instanţa de judecată a purces la judecarea cauzei, ţinînd cont de principiul prezumţiei nevinovăţiei. Vinovăţia inculpatului xxxxNUMExxxx instanţa de judecată o constată reeşind din următoarele probe. Reeşind din declaraţiile părţii vătămate ­ xxxxNUMExxxx, urmează că la data de 13.10.2013, fratele său xxxxNUMExxxx a venit în Republica Moldova din Federaţia Rusă, unde a fost la muncă. Aproximativ pe la orele 02.00 se aflau împreună cu fratele său xxxxNUMExxxx în barul „Topolea”; la o anumită perioadă de timp fratele său ­ xxxxNUMExxxx, a ieşit afară să fumeze, lipsind de la masă timp de 10­15 minute. Atunci a ieşit afară să vadă ce face fratele său şi a observat cum ultimul discută cu inculpaţii Cazacu Alexandru şi Zahariaş Maxim. Din discuţia lor a înţeles că inculpaţilor nu le­a plăcut cum este îmbrăcat fratele său. I­a propus inculpatului Zahariaş Maxim, să discute împreună. Ulterior l­a invitat pe

[Succeeded / Failed / Skipped / Total] 39 / 48 / 24 / 111:  87%|████████▋ | 87/100 [16:48<02:30, 11.59s/it]

--------------------------------------------- Result 111 ---------------------------------------------
[[1 (75%)]] --> [[[FAILED]]]

În corespundere cu art. 449 alin. (1) pct. 1) lit. a) Cod pr. penală, Colegiul,-

[Succeeded / Failed / Skipped / Total] 39 / 49 / 26 / 114:  88%|████████▊ | 88/100 [17:01<02:19, 11.61s/it]

--------------------------------------------- Result 112 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

Inculpatul XXX, la data de XXXaproximativ la ora 11.25, fiind posesor al permisului de conducere nr. 1XXX659 eliberat la XXX valabil pentru categoria „B", în urma consumării băuturilor alcoolice, a urcat ia volanul automobilului de model „ForXXX” cu numerele de înmatriculare CU Al I 23 şi deplasându­ se pe strada independenţei din or. XX nu s­a isprăvit cu conducerea automobilului şi a tamponat automobilul de model „MerXXX cu numerele de înmatriculare XXX condus de către XXXX Fiind suspectat de către colaboratorii de poliţie că a consumat băuturi alcoolice şi a condus în stare de ebrietate, a fost supus testării alcoolscopice cu aparatul „Dragei'" şi conform extrasului de tichet nr.4354, eliberat de aparatul respectiv, s­a stabilit o concentraţie a vaporilor de alcool în aerul expirat de 0,66 mg/1. În cadrul şedinţei preliminare inculpatul XXXX a solicitat prin înscris autentic ca judecata să aibă loc pe baza probelor administrate în faza de urmărire penală, pe care le cunoaşte şi asupra cărora nu are obiecţii, indicînd că recunoaşte săvîrşirea faptelor indicate în rechizitoriu. Prin încheierea instanţei de judecată s­a admis cererea inculpatului privind judecarea cauzei pe baza probelor administrate în faza de urmărire penală. În şedinţă judiciară inculpatul XXX sub jurămînt a recunoscut săvîrşirea faptelor indicate în rechizitoriu şi a declarat instanţei că se căieşte sincer de cele săvîrşite şi pe viitor nu va mai comite asemenea fapte. A mai adăugat că a servit seara pînă dimineaţă la discotecă apoi a doua zi s­a urcat la volan , precum şi faptul că are la întreţinere un copil minor bolnav, din care considerente solicită să îi fie aplicată o pedeapsă sub formă de muncă neremunerată în folosul societăţii.. Pe lîngă faptul că inculpatul XXXXX şi­a recunoscut vina, vinovăţia sa este dovedită pe deplin şi prin cumulul de probe prezentate de către procuror, şi anume: ­ procesul­verbal de audiere a martorului XXX a declarat activează în calitate de inspector al poliţiei rutiere în cadrul XXXXXXXXX XXX La 05.03.2016 a fost implicat în serviciu şi aproximativ la orele 11.20 a primit indicaţia de la ofiţerul de serviciu din unitatea de gardă a IPXXde a se deplasa pe str. XXdin or. XXXX unde s­a produs un accident rutier. Ajungând la ţaţa locului a constatat că automobilul de model „FXXXeo” cu numerele de înmatriculare XXX, la volanul căruia se afla cet. XXX a. n. 1XXXdomiciliat în s. XXX, r. XXa, care a încălcat prevederile p.49 din Regulamentul Circulaţiei Rutiere şi nu a ţinut distanţa între automobilul său şi automobilul din Faţa sa şi în rezultat a tamponat automobilul de model „MXXX8 “ cu numerele de înmatriculare AAXXXXcare era condus de către XXXX, a.n.XX., în momentul verificării actelor, şoferul XXXX a fost suspectat de conducerea mijlocului de transport în stare de ebrietate. Astfel i s­a propus de a fi testat cu alcotestul „Dragei”, la ce acesta a fost de acord. Urmare a testarii cet XXX cu alcotestul „Drager” conform extrasului nr.4304, s­a stabilit o concentraţie de alcool în aerul expirat de 0,66 mg/î. ceea ce constituie stare de ebrietate grad avansat. Ultimul a fost de acord cu rezultatul testăm alcolscopice, comportându­se


--------------------------------------------- Result 113 ---------------------------------------------
[[0 (84%)]] --> [[[SKIPPED]]]

Instanţa de fond a reţinut, că xxxxNUMExxxx la data de 29.12.2013, în jurul orelor 18:30, fiind în stare de ebrietate alcoolică cu grad avansat, fapt confirmat de rezultatele testelor la alcool la care a fost supus și potrivit cărora concentrația de alcool în aerul expirat de către el constituia 0,43 mg/l, iar concentrația alcoolului etilic în sînge constituia 1,14 g/l, conducînd un automobil de model „xxxxxxxx” cu n/î xxxxxxxxxx, pe traseul republican R124+450m, Sculeni­Blîndești, cu încălcarea prevederilor pct.14 lit.a) al Regulamentului Circulației Rutiere al R.Moldova care prevede că: „Conducătorului de vehicul îi este interzis: a) să conducă vehiculul în stare de ebrietate, sub influența drogurilor sau altor substanțe contraindicate, sub influența preparatelor medicamentoase care provoacă reducerea reacției, fiind bolnav, traumatizat sau într­o stare avansată de oboseală de natură să­i afecteze capacitatea de conducere” și prevederile art.45 alin.(1) lit.a), b) și d) din același Regulament care prevăd că: „Conducătorul trebuie să conducă vehiculul în conformitate cu limita de viteză stabilită, ținînd permanent seama de următorii factori: a) starea psihofiziologică ce influențează atenția și reacția, b) dexteritatea în conducere care i­ar permite să prevadă situațiile periculoase și d) situația rutieră”, nu s­a isprăvit cu conducerea automobilului său și a ieșit pe contrasens, urmare a cărora s­a izbit violent într­un automobil de model „Skoda Fabia” cu n/î BL DT 195 condus regulamentar de către cet.xxxxNUMExxxx. La fel, în urma impactului cauzat de către xxxxNUMExxxx, pasagerul automobilului „xxxxxxxx” cu n/î xxxxxxxxxx, xxxxNUMExxxx s­a ales cu vătămări corporale grave periculoase pentru viață sub formă de traumă cranio­cerebrală închisă cu fractura complexului zigomatico­maxilar pe stînga, fractura bazei craniului pe stînga, hematom epidural frontal pe stînga cu contuzii parenchimatoase cerebrale adiacente (fronto­bazală), plagă contuză a regiunii orbitale stîngi, iar pasagerul xxxxNUMExxxx s­a ales, de asemenea, cu vătămări corporale grave periculoase pentru viață sub formă de traumă închisă a cutiei toracice cu fractura coastelor 4­9 pe dreapta, 4 și 5 pe stînga, complicată cu hemopneumotorax pe dreapta și hemotorax pe stînga, trauma cranio­cerebrală acută cu fractura liniară a osului temporal stîng și contuzie cerebrală minoră, fractura acetabul dreapta, plăgi contuzionate a regiunii frontale și genunchiului drept. Totodată, în urma impactului care a avut loc conducătorul automobilului de model „xxxxxxxxx” cu n/î xxxxxxxxxx, xxxxNUMExxxx, s­a ales cu vătămări corporale medii cu dereglarea sănătății de lungă durată sub formă de traumă închisă a cutiei toracice cu fractura coastelor 5,6,7 pe linia auxiliară anterioară pe stînga, contuzia plămînului stîng și a cordului, plaga contuză în regiunea parieto­occipitală stînga, contuzia țesuturilor moi a degetului 3 a mîinii stîngi și a regiunii meto­tarsofalangiene 3,4 plata dreaptă. Cauza a fost examinată în procedura specială prevăzută de art.364/1 CPP în baza probelor administrate în faza de urmărire penală în baza înscrisului autentic depus de inculpat în partea pregătitoare a ședinței judiciare și acceptat de către instanță. Legalitatea şi temeinicia sentinţei de condamnare a fost atacată cu apel în modul şi termenul, prevăzut de art.401­402 CPP al RM, de către avocatul A.Fetcu în interesele inculpatului xxxxxxxxxxx, care în motivarea apelului susţine, că pedeapsa aplicată inculpatului de către instanța de fond este una prea gravă, reeșind din faptul, că


--------------------------------------------- Result 114 ---------------------------------------------
[[1 (96%)]] --> [[[SKIPPED]]]

Prin sentinţa pronunţată, instanţa de fond a reţinut, că xxxxNUMExxxx a acționat în mod intenționat conștientizînd caracterul prejudiciabil al acțiunilor sale și dorind survenirea acestora, executîndu­și pedeapsa în penitenciarul nr.11 Bălți amplasat, pe str. m. Bălți, str. Ștefan cel Mare, 78 A și aflîndu­se pe teritoriul acestei instituții, la data de 12.03.2014 ilegal a intrat în posesia unor substanțe narcotice – marihuană în cantitate nestabilită și tot în acea zi aproximativ la orele 19.00 a întrebuințat prin fumat marijuana dată iar la 13.03.2014 a fost transportat la Dispensarul Narcologic a Spitalului Clinic mun. Bălți, unde în urma examinării medicale s­a stabilit concluzia – consumul de substanțe narcotice (marihuana), fapt confirmat prin procesul­verbal nr.217 din 13.03.2014 eliberat de IMSP SC mun.Bălți, al examinării medicale de constatare a stării de ebrietate și naturii ei. Marihuana este inclusă în Lista nr.1 Tabelul nr.1”Substanțe narcotice și psihotrope ce nu se întrebuințează în practica medicală”, aprobată prin Hotărîrea Guvernului RM nr.1088 din 05.10.2004 și Hotărîrea Guvernului RM nr.79 din 23.01.2006 și Lista ”Cantitățile substanțelor narcotice psihotrope și a plantelor care conțin astfel de substanțe, depistate în trafic ilicit”, aprobată prin Hotărîrea Guvernului RM nr.79 din 23.01.2006. Cauza a fost examinată în ordinea procedurii prevăzute de art.364/1 CPP, în baza probelor administrate în faza de urmărire penală, prin înscrisul autentic declarat de inculpat (f.d.51) şi care a fost acceptat prin încheierea judiciară din 16.04.2014 (f.d.53). Constatînd vinovăția lui xxxxNUMExxxx în comiterea infracțiunii prevăzute de art. 217/5 alin.(1) Cod penal și ținînd cont de prezența circumstanțelor atenuante a cauzei cum ar fi: recunoașterea vinovăției, acceptînd judecarea cauzei în temeiul art.364/1 Cod pr. penală cu cheltuieli minime de resurse, totodată ținînt cont de gravitatea infracțiunii săvîrșite, de faptul că xxxxNUMExxxx fiind anterior condamnat pentru alte acte care au relevanță pentru cauză, ispășind pedeapsa anterioară nu s­a corectat și a continuat comportamentul său infracțional, aflîndu­se în locul de detenție din nou a comis o infracțiune și în acțiunile inculpatului persistă starea de recidivă, instanța în temeiul art. 364/1 alin. (8) Cod pr. penală a dispus aplicarea în privința lui a pedepsei de 160 (una sută șaizeci) ore muncă neremunerată în folosul comunității, iar în conformitate cu art.85 și art. 87 al.1 CP prin cumul de sentințe, calculîndu­se două ore de muncă neremunerată în folosul comunității pentru o zi de închisoare, a adăuga parțial la pedeapsa aplicată pedeapsa stabilită și neexecutată prin sentința judecătoriei Rîșcani din 19.11.2012 și definitiv i­a fost stabilit lui xxxxNUMExxxx pedeapsă 3 (trei) ani 1 (una) lună închisoare cu executarea pedepsei în penitenciar de tip închis. Legalitatea și temeinicia sentinței judiciare a fost contestată cu recurs de către condamnatul xxxxNUMExxxx, care necontestînd încadrarea juridică a acțiunilor criminale solicită casarea verdictului judiciar în latura pedepsei penale, cu pronunțarea în această parte a unei soluții noi privind atenuarea pedepsei. În fața instanței de recurs recurentul xxxxNUMExxxx a solicitat admiterea recursului.El a declarant, că nu este deacord cu sentința în cauză deoarece prin sentința data a fost schimbat regimul penitenciarului unde urmează să fie executată pedeapsa. Reprezentantul acuzării a propus respingerea recursului ca fiind tardiv, în cauză fiind lipsă de date

[Succeeded / Failed / Skipped / Total] 40 / 49 / 26 / 115:  89%|████████▉ | 89/100 [17:10<02:07, 11.58s/it]

--------------------------------------------- Result 115 ---------------------------------------------
[[0 (91%)]] --> [[1 (62%)]]

Turuta Ion [[Petru]] în perioada 01.01.2013 - 31.12.2013 urmărind scopul obţinerii unui profit în proporţii deosebit de mari, a desfăşurat activităţi de [[întreprinzător]] fără înregistrarea ([[reînregistrarea]]) la organele autorizate, manifestate prin a transportat cu frecvenţă regulată (săptămânal, efectuînd cîte o rută minim între ţările Republica Moldova şi Republica Cehă), călători şi bagaje încasând astfel pentru serviciu de transport de la fiecare persoană valoarea de 80 euro. [[Întru]] realizarea intenţiilor sale criminale, cet. Turuta Ion Petru, cu ajutorul unor cărţi de vizită pe care le răspândea prin intermediul aceloraşi pasageri, îşi facea publică activitatea sa şi obţinea astfel călătorii. Potrivit informaţiilor obţinute de la poliţia de Frontieră s-a [[constatat]] că Turuta Ion pe parcursul perioadei de referinţă a efectuat 52 rute regulate tur-retur Chişinău-Praga- Chişinău cu microbuze a transportat 262 călători, de la fiecare a încasat costul mediu a călătoriei de 80 euro, obţinând astfel un venit ilicit în sumă totală de 20960 euro, care potrivit ratei oficiale de schimb a BNM pentru perioada 01.01.2013 - 31.12.2014 constituia valoarea de 350 537 lei, încălcând astfel prevederile art.8 pct.2 lit.a) şi d) a Codului fiscal nr.1163-XIII din 24.04.1997 şi art.27 din Legea nr.845-XII din 03.01.1992 “cu privire la antreprenoriat şi întreprinderi”. Astfel, Turuta Ion Petru prin acţiunile sale intenţionate a săvârşit practicarea ilegală a activităţii de întreprinzător soldate cu obţinerea unui profit în proporţii deosebit de mari, adică infracţiunea prevăzută de art. 241 alin. (2) lit.f) Cod Penal. Totodată, Popescu Eduard Anatolie în perioada anului 2013 urmărind scopul obţinerii unui profit în proporţii deosebit de mari, a desfăşurat activităţi de întreprinzător fără înregistrarea (reînregistrarea) la organele autorizate, manifestate prin a transportat cu frecvenţă regulată (săptămânal, efectuînd cîte o rută minim între ţările Republica Moldova şi Republica Cehă), călători şi bagaje încasând astfel pentru serviciu de transport de la fiecare persoană valoarea de 80 euro. Întru realizarea intenţiilor sale criminale, Popescu Eduard Anatolie, cu ajutorul unor cărţi de vizită pe care le răspândea prin intermediul aceloraşi pasageri, îşi facea publică activitatea sa şi obţinea astfel călătorii. Potrivit informaţiilor obţinute de la poliţia de Frontieră s-a constatat că Popescu Eduard Anatolie pe parcursul perioadei de referinţă a efectuat 43 rute regulate tur-retur Chişinău-Praga-Chişinău cu microbuze a transportat 240 călători, de la fiecare a încasat costul mediu a călătoriei de 80 euro, obţinând astfel un venit ilicit în sumă totală de 19200 euro, care potrivit ratei oficiale de schimb a BNM pentru perioada 01.01.2013 - 31.12.2014 constituia valoarea de ***** lei, încălcând astfel prevederile art.8 pct.2 lit.a) şi d) a Codului fiscal nr.1163-XIII din 24.04.1997 şi art.27 din Legea nr.845-XII din 03.01.1992 “cu privire la antreprenoriat şi întreprinderi”. Astfel, Popescu Eduard Anatolie prin acţiunile sale intenţionate a săvârşit practicarea ilegală a activităţii de întreprinzător soldate cu obţinerea unui profit în proporţii deosebit de mari, adică infracţiunea prevăzută de art. 241 alin. (2) lit.f) Cod Penal. În ședința de judecată inculpatul Turuta Ion Petru a declarant că nu recunoaște învinuirea adusă indicînd următoarele. Din 2007 a fost în Cehia în diferite domenii, sora saa la fel este angajată în câmpul muncii acolo. Menționează că în septembrie 2013 s-a

Turuta Ion [[Pertu]] în perioada 01.01.2013 - 31.12.2013 urmărind scopul obţinerii unui profit în proporţii deosebit de mari, a desfăşurat activităţi de [[întreprinztăor]] fără înregistrarea ([[reînregistraera]]) la organele autorizate, manifestate prin a transportat cu frecvenţă regulată (săptămânal, efectuînd cîte o rută minim între ţările Republica Moldova şi Republica Cehă), călători şi bagaje încasând astfel pentru serviciu de transport de la fiecare persoană valoarea de 80 euro. [[Îtnru]] realizarea intenţiilor sale criminale, cet. Turuta Ion Petru, cu ajutorul unor cărţi de vizită pe care le răspândea prin intermediul aceloraşi pasageri, îşi facea publică activitatea sa şi obţinea astfel călătorii. Potrivit informaţiilor obţinute de la poliţia de Frontieră s-a [[cnostatat]] că Turuta Ion pe parcursul perioadei de referinţă a efectuat 52 rute regulate tur-retur Chişinău-Praga- Chişinău cu microbuze a transportat 262 călători, de la fiecare a încasat costul mediu a călătoriei de 80 euro, obţinând astfel un venit ilicit în sumă totală de 20960 euro, care potrivit ratei oficiale de schimb a BNM pentru perioada 01.01.2013 - 31.12.2014 constituia valoarea de 350 537 lei, încălcând astfel prevederile art.8 pct.2 lit.a) şi d) a Codului fiscal nr.1163-XIII din 24.04.1997 şi art.27 din Legea nr.845-XII din 03.01.1992 “cu privire la antreprenoriat şi întreprinderi”. Astfel, Turuta Ion Petru prin acţiunile sale intenţionate a săvârşit practicarea ilegală a activităţii de întreprinzător soldate cu obţinerea unui profit în proporţii deosebit de mari, adică infracţiunea prevăzută de art. 241 alin. (2) lit.f) Cod Penal. Totodată, Popescu Eduard Anatolie în perioada anului 2013 urmărind scopul obţinerii unui profit în proporţii deosebit de mari, a desfăşurat activităţi de întreprinzător fără înregistrarea (reînregistrarea) la organele autorizate, manifestate prin a transportat cu frecvenţă regulată (săptămânal, efectuînd cîte o rută minim între ţările Republica Moldova şi Republica Cehă), călători şi bagaje încasând astfel pentru serviciu de transport de la fiecare persoană valoarea de 80 euro. Întru realizarea intenţiilor sale criminale, Popescu Eduard Anatolie, cu ajutorul unor cărţi de vizită pe care le răspândea prin intermediul aceloraşi pasageri, îşi facea publică activitatea sa şi obţinea astfel călătorii. Potrivit informaţiilor obţinute de la poliţia de Frontieră s-a constatat că Popescu Eduard Anatolie pe parcursul perioadei de referinţă a efectuat 43 rute regulate tur-retur Chişinău-Praga-Chişinău cu microbuze a transportat 240 călători, de la fiecare a încasat costul mediu a călătoriei de 80 euro, obţinând astfel un venit ilicit în sumă totală de 19200 euro, care potrivit ratei oficiale de schimb a BNM pentru perioada 01.01.2013 - 31.12.2014 constituia valoarea de ***** lei, încălcând astfel prevederile art.8 pct.2 lit.a) şi d) a Codului fiscal nr.1163-XIII din 24.04.1997 şi art.27 din Legea nr.845-XII din 03.01.1992 “cu privire la antreprenoriat şi întreprinderi”. Astfel, Popescu Eduard Anatolie prin acţiunile sale intenţionate a săvârşit practicarea ilegală a activităţii de întreprinzător soldate cu obţinerea unui profit în proporţii deosebit de mari, adică infracţiunea prevăzută de art. 241 alin. (2) lit.f) Cod Penal. În ședința de judecată inculpatul Turuta Ion Petru a declarant că nu recunoaște învinuirea adusă indicînd următoarele. Din 2007 a fost în Cehia în diferite domenii, sora saa la fel este angajată în câmpul muncii acolo. Menționează că în septembrie 2013 s-a

[Succeeded / Failed / Skipped / Total] 41 / 49 / 28 / 118:  90%|█████████ | 90/100 [17:19<01:55, 11.55s/it]

--------------------------------------------- Result 116 ---------------------------------------------
[[1 (97%)]] --> [[0 (52%)]]

1. [[Inculpatul]] Dragan Igor Gheorghe, activînd cu scopul îndreptat spre sustragerea bunurilor altei persoane și îmbogățire, conștientizînd caracterul prejudiciabil al acțiunilor sale, prevăzînd urmările lor prejudiciabile și dorind survenirea acestora, la data de 24.01.2016 în perioada de timp 04:[[00-06]]:00, aflîndu-se în incinta barului „Crona” situat în mun. Bălți str. Ștefan cel Mare, folosindu-se de faptul că nu este văzut de nimeni, de pe masa unde stătea Dociu Denis Andrei a sustras un telefon mobil de model „LG” cu IMEI [[359860061619742]], cu cartela sim „Orange” cu nr. [[069405298]] la prețul de 4500 lei, care-i aparținea ultimului, astfel, [[cauzîndu-i]] părții vătămate Dociu Denis Andrei o daună materială în proporții considerabile. 2. Fiind audiat în cadrul ședinței de judecată inculpatul Dragan Igor Gheorghe vina în săvîrşirea acţiunilor ilegale nu a recunoscut-o şi a declarat [[instanței]] că, în ziua cînd a fost sustras telefonul mobil el se afla la barul „Caucaz”, după care la barul „Randez-Vous”, care se află la autogară. Acolo a fost dus de către un cunoscut taximetrist în jurul orelor 21:00. La barul „Randez-Vous” s-a aflat pînă dimineață. În seara respectivă i-a vîndut taximetristului un sambufer și un DVD. La data de 23-24.01.2016 nu a fost la barul „Crona”. În seara respectivă de la autogară de la doi cunoscuți a procurat un telefon mobil. Telefonul era crapat la un colț și nu avea nici acumulator. De telefonul respectiv s- a folosit o singură zi, incluzînd cartela sa. Ulterior, inculpatul Dragan Igor Gheorghe fiind legal citat, în ședințele de judecată nu s-a prezentat și nici nu a comunicat instanței motivele neprezntării. Fiind dispusă aducerea fortată a inculpatului, aceasta nu s-a soldat cu nici un rezultat pozitiv, într-u cît potrivit raportului colaboratorilor de poliție din cadrul IP Bălți s-a constatat că inculpatul este plecat peste hotarele țării în Cehia. În conformitate cu art. 321 Cod de procedură penală, (1) Judecarea cauzei în primă instanţă şi în instanţa de apel are loc cu participarea inculpatului, cu excepţia cazurilor prevăzute de prezentul articol. (2) Judecarea cauzei în lipsa inculpatului poate avea loc în cazul: 1) cînd inculpatul se ascunde de la prezentarea în instanţă; 2) cînd inculpatul, fiind în stare de arest, refuză să fie adus în instanţă pentru judecarea cauzei şi refuzul lui este confirmat şi de apărătorul lui sau de administraţia locului de detenţie a acestuia; 3) examinării unor cauze privitor la săvîrşirea unor infracţiuni uşoare cînd inculpatul solicită judecarea cauzei în lipsa sa. (21) În cazul prevăzut la alin.(2) pct.2), inculpatul poate fi supus aducerii silite în instanţa de judecată pentru a-şi confirma refuzul de a participa la judecarea cauzei. (3) În cazul judecării cauzei în lipsa inculpatului, participarea apărătorului şi, după caz, a reprezentantului lui legal este obligatorie. (4) În caz de neprezentare a inculpatului în instanţă, judecarea cauzei se amînă, cu excepţia cazurilor prevăzute la alin.(2) şi alin.(21). (5) Instanţa, în cazul neprezentării nemotivate a inculpatului la judecarea cauzei, este în drept să dispună aducerea silită a inculpatului şi să-i aplice o măsură preventivă sau să o înlocuiască cu o altă măsură care va asigura prezentarea lui în instanţă, iar la demersul

1. [[Inculaptul]] Dragan Igor Gheorghe, activînd cu scopul îndreptat spre sustragerea bunurilor altei persoane și îmbogățire, conștientizînd caracterul prejudiciabil al acțiunilor sale, prevăzînd urmările lor prejudiciabile și dorind survenirea acestora, la data de 24.01.2016 în perioada de timp 04:[[000-6]]:00, aflîndu-se în incinta barului „Crona” situat în mun. Bălți str. Ștefan cel Mare, folosindu-se de faptul că nu este văzut de nimeni, de pe masa unde stătea Dociu Denis Andrei a sustras un telefon mobil de model „LG” cu IMEI [[359860016619742]], cu cartela sim „Orange” cu nr. [[064905298]] la prețul de 4500 lei, care-i aparținea ultimului, astfel, [[cuazîndu-i]] părții vătămate Dociu Denis Andrei o daună materială în proporții considerabile. 2. Fiind audiat în cadrul ședinței de judecată inculpatul Dragan Igor Gheorghe vina în săvîrşirea acţiunilor ilegale nu a recunoscut-o şi a declarat [[instnaței]] că, în ziua cînd a fost sustras telefonul mobil el se afla la barul „Caucaz”, după care la barul „Randez-Vous”, care se află la autogară. Acolo a fost dus de către un cunoscut taximetrist în jurul orelor 21:00. La barul „Randez-Vous” s-a aflat pînă dimineață. În seara respectivă i-a vîndut taximetristului un sambufer și un DVD. La data de 23-24.01.2016 nu a fost la barul „Crona”. În seara respectivă de la autogară de la doi cunoscuți a procurat un telefon mobil. Telefonul era crapat la un colț și nu avea nici acumulator. De telefonul respectiv s- a folosit o singură zi, incluzînd cartela sa. Ulterior, inculpatul Dragan Igor Gheorghe fiind legal citat, în ședințele de judecată nu s-a prezentat și nici nu a comunicat instanței motivele neprezntării. Fiind dispusă aducerea fortată a inculpatului, aceasta nu s-a soldat cu nici un rezultat pozitiv, într-u cît potrivit raportului colaboratorilor de poliție din cadrul IP Bălți s-a constatat că inculpatul este plecat peste hotarele țării în Cehia. În conformitate cu art. 321 Cod de procedură penală, (1) Judecarea cauzei în primă instanţă şi în instanţa de apel are loc cu participarea inculpatului, cu excepţia cazurilor prevăzute de prezentul articol. (2) Judecarea cauzei în lipsa inculpatului poate avea loc în cazul: 1) cînd inculpatul se ascunde de la prezentarea în instanţă; 2) cînd inculpatul, fiind în stare de arest, refuză să fie adus în instanţă pentru judecarea cauzei şi refuzul lui este confirmat şi de apărătorul lui sau de administraţia locului de detenţie a acestuia; 3) examinării unor cauze privitor la săvîrşirea unor infracţiuni uşoare cînd inculpatul solicită judecarea cauzei în lipsa sa. (21) În cazul prevăzut la alin.(2) pct.2), inculpatul poate fi supus aducerii silite în instanţa de judecată pentru a-şi confirma refuzul de a participa la judecarea cauzei. (3) În cazul judecării cauzei în lipsa inculpatului, participarea apărătorului şi, după caz, a reprezentantului lui legal este obligatorie. (4) În caz de neprezentare a inculpatului în instanţă, judecarea cauzei se amînă, cu excepţia cazurilor prevăzute la alin.(2) şi alin.(21). (5) Instanţa, în cazul neprezentării nemotivate a inculpatului la judecarea cauzei, este în drept să dispună aducerea silită a inculpatului şi să-i aplice o măsură preventivă sau să o înlocuiască cu o altă măsură care va asigura prezentarea lui în instanţă, iar la demersul


--------------------------------------------- Result 117 ---------------------------------------------
[[1 (77%)]] --> [[[SKIPPED]]]

1.O. I., la data de 31 iulie 2013, aproximativ la ora 14:00, fiind în stare de ebrietate şi aflîndu­se la domiciliul său, situat în or. xxxxCUSTOM1xxxx, str. .., avînd intenţia de a comite violenţa în familie, a iniţiat un conflict cu mama sa O.M., adresîndu­se în privinţa ei cu cuvinte înjositoare şi aplicîndu­i multiple lovituri cu mîinile şi picioarele pe diferite părţi ale corpului, în rezultatul cărora i­a cauzat, conform raportului de expertiză medico­legal nr...din 13.08.2013, echimoză pe gamba dreaptă, excoriaţie pe gamba stîngă, care se califică ca vătămări corporale neînsemnate. 1 Astfel, prin acţiunile intenţionate, xxxxCUSTOM1xxxx, a săvîrşit infracţiunea prevăzută de art. 201 alin. (1) Cod Penal, conform indicilor: violenţa în familie, adică acţiunea sau inacţiunea intenţionată, manifestată fizic sau verbal, comisă de un membru al familiei asupra unui alt membru al familiei, care a provocat suferinţă fizică, soldată cu vătămarea uşoară a integrităţii corporale sau a sănătăţii, suferinţă psihică ori prejudiciu material sau moral. 2.Prin sentinţa Judecătoriei xxxxCUSTOM1xxxx din 17 aprilie 2014 (f.d. 109­112), adoptată în procedura prevăzută de art. 1 364 CPP (pe baza probelor administrate în faza de urmărire penală) _ 1 ­xxxxCUSTOM1xxxx a fost recunoscut vinovat de săvîrşirea infracţiunii prevăzute de art. 201 alin. (1) Cod Penal, stabilindu­i pedeapsa sub formă de închisoare pe un termen de 8 luni, cu executarea acesteia în penitenciar de tip semiînchis. Măsura preventivă în privinţa lui xxxxCUSTOM1xxxx s­a menţinut aceiaşi arestul preventiv. Termenul de executare a pedepsei s­a calculat din 17 aprilie 2014, cu includerea perioadei aflării inculpatului în stare de arest preventiv de la 08 aprilie 2014 pînă la 17 aprilie 2014. 3.La data de 29.04.2014 (f.d. 115), avocatul S.E., în interesele inculpatului xxxxCUSTOM1xxxx, a declarat apel împotriva sentinţei Judecătoriei xxxxCUSTOM1xxxx din 17.04.2014, solicitînd: ­admiterea apelului şi casarea parţială a sentinţei Judecătoriei xxxxCUSTOM1xxxx din 17 aprilie 2014, cu pronunţarea unei noi hotărîri cu stabilirea unei pedepse non privative de libertate. În motivarea apelului a fost indicat faptul că, consideră sentinţa ilegală din motivul aplicării pedepsei prea aspre, deoarece, necătînd la faptul că vinovăţia a fost recunoscută integral, cauza penală fiind examinată în conformitate cu prevederile art. 3641 CPP, iar pedeapsa a fost stabilită aspru. Astfel, apelantul a făcut trimitere la prevederile art. 75 alin. (1), (2) Cod Penal, circumstanţe pe acre le consideră că în ansamblul lor fac pasibilă casarea parţială a sentinţei Judecătoriei xxxxCUSTOM1xxxx din 17.04.2014, în partea referitoare la stabilirea pedepsei. În drept, îşi întemeiază cererea de apel în baza prevederilor art. 401 alin. (1), (2), 405, 415 alin. (2) CPP şi art. 6, 8 ale Convenţiei pentru Apărarea Drepturilor şi Libertăţilor Fundamentale ale Omului. 4.Colegiul judiciar, audiind părţile, examinînd materialele cauzei penale, analizînd argumentele apelului declarat, consideră necesar de a respinge cererea de apel ca fiind nefondată cu menţinerea sentinţei primei instanţe, din următoarele considerente. În conformitate cu prevederile art. 415 alin. (1) pct.1) lit. c) Cod de procedură penală, instanţa de apel, judecînd cauza în ordine de apel, este în drept să, respingă apelul, menţinînd hotărîrea atacată, dacă apelul este nefondat. Colegiul judiciar constată că, prima instanţă, corecta a stabilit situaţia de fapt şi de drept


--------------------------------------------- Result 118 ---------------------------------------------
[[0 (99%)]] --> [[[SKIPPED]]]

La data de 08.09.2016, prin sentinţa Judecătoriei Edineţ Bortă Oleg, a fost sancţionat cu amendă în mărime de 14000 lei pentru comiterea infracţiunii prevăzute de art.2641 alin. (4) Cod penal RM. Ulterior a fost emis titlul executoriu. La 22.12.2016, în conformitate cu prevederile art. 60 alin.(3) Cod de executare, a fost emisă încheierea de primire spre executare a documentului executoriu, intentarea procedurii de executare cu propunerea de a executa documentul executoriu în termen de 15 zile. Deoarece debitorul nu s-a conformat cerinţelor înaintate, la 17.03.2017 a fost emisă încheierea privind continuarea executării silite a documentului executoriu. În baza demersului nr. 144-349/17 din 29.05.2017 a fost solicitat instanţei de judecată anunţarea în căutare a debitorului. Prin încheierea Judecătoriei Edineţ nr. 25-101/17 din 16.06.2017 condamnatul Bortă Oleg a fost anunţat în căutare. Conform notei informative expediată de IP Edineţ, a fost adus la cunoştință că dosarul de căutare a debitorului Bortă Oleg a fost clasat, pe motiv că acesta a fost găsit în mun. Chişinău, ultimul semnând un angajament, prin care şi-a asumat obligaţiunea de a se prezenta la biroul executorului judecătoresc. Prin informaţia eliberată de Agenţia Servicii Publice s-a stabilit, că după Bortă Oleg nu este înregistarat nici un drept de proprietate, unităţi de transport, conturi bancare. Ulterior, condamnatul nu se prezenta la executorul judecătoresc şi nu întreprindea măsuri în vederea achitării amenzii penale. La data de 18.05.2018 către judecătoria Edineţ a parvenit demersul executorului judecătoresc Olesea Bodean, prin care a solicitat înlocuirea pedepsei penale în privinţa condamnatului Bortă Oleg din amendă în închisoare invocînd faptul că condamnatul se eschivează cu rea-voinţă de executarea pedepsei penale. Prin încheierea Judecătoriei Edineț, sediul Central din 09.11.2018, a fost respins integral ca neîntemeiat demersul executorului judecătoresc Olesea Bodean privind înlocuirea pedepsei penale stabilite lui Bortă Oleg a.n. ***** prin sentinţa Judecătoriei Edineţ din 08.09.2016 din amenda penală de 14 000 lei în închisoare. În motivarea soluției adoptate, instanța de fond a reținut, că potrivit încheierii din 22.12.2016 a fost primit spre executare documentul executoriu cu nr. 1-67/16 privind încasarea amenzii în mărime de 14 000 lei. A mai stabilit că condamnatul a fost anunţat în căutare, şi ulterior depistat în mun. Chişinău, ultimul semnând un angajamentu prin care şi-a asumat obligaţiunea de a se prezenta la biroul executorului judecătoresc, iar în afară de aceasta condamnatul Bortă Oleg a fost citat numai prin citaţie la data de 12.10.2016, 20.09.2016, 05.03.2018 şi anexată la dosar explicaţia de la Dobic Svetlana (ridicată de colaboratorul de poliţie), care menționează că nu l-a văzut de 3 luni pe Bortă Oleg şi din cîte cunoaşte ultimul se află în mun. Chişinău. De asemenea, de către executorul judecătoresc au fost ridicate informaţii pe condamnat de la ÎS ”Cadastru” pe data de 20.03.2017, de la CNAM pe 20.03.2017, de la Inspectoratul Fiscal din 12.07.2017 din ACCES, de la ProcreditBank pe data de 07.07.2017. Potrivit materialelor din dosar, instanţa a reținut faptul, că nu s-a stabilit alte careva acţiuni efectuate de către executorul judecătoresc (proces verbal de constatare, deplasarea la domiciliul condamnatului, etc.) acţiuni efectuate pe perioada lunilor iulie 2017 -mai 2018 (pînă la depunerea

[Succeeded / Failed / Skipped / Total] 41 / 50 / 30 / 121:  91%|█████████ | 91/100 [17:34<01:44, 11.59s/it]

--------------------------------------------- Result 119 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

Cotoman Arcadie Vladimir, avînd potrivit art. 133/1 lit.a) Cod penal calitatea de membru de familie în raport cu fosta sa soție Rodica Cotoman, pe parcursul primelor luni ale anului 2019 consumînd abuziv băuturi alcoolice, aflîndu-se la domiciliul său în s. Seliștea Nouă, r-nul Călărași, sistematic aplică în privința acestea violența psihică. Astfel, el pe parcursul zilei de 22.01.2019, a inițiat un conflict cu feciorul său minor Cotoman Arcadie Arcadie, învinuindu-l că ar fi deteriorat un lacăt de la o ușă a casei și comis sustragerea unor bunurilor ce-i aparțin, l-a numit cu cuvinte necenzurate. Din cauza stării tensionate, în scopul evitării și eventualei amplificări a conflictului el împreună cu mama sa Rodica Cotoman fost nevoit să înopteze la o rudă din mahala. Tot el, la 23.01.2019, pe parcursul serii, după ce a servit alcool cu prieteni săi, fosta soție R. Cotoman i-a făcut observație să nu trântească ușile la casă. Prin urmare, el fiind deranjat de observațiile făcute, a devenit agresiv și s-a repezit spre ea cu scopul să o lovească. Însă, nu a reușit, deoarece s-a implicat feciorul Arcadie Cotoman și l-a impidicat de a-și realiza intenția violentă și a apelat la poliție după ajutor. Tot el, 07.02.2019 aproximativ la orele 09 şi 00 minute, aflându-se la domiciliul comun pe adresa menționată, fiind în stare de ebrietate alcoolică, manifestând supremație şi comportament autoritar fată de soția sa R. Cotoma, intenționat a inițiat un conflict cu aceasta, trântind ușile prin casă, numind-o cu diverse cuvinte necenzurate, amenințând-o cu răfuială fizică, încercînd să o influențeze psihic prin frică și alte acțiuni violente în scopul impunerii voinței și controlul personal asupra fostei soții. Tot el, la 10.02.2019 în jurul orelor 14:30 min. aflîndu-se în bucătăria domiciliului pe adresa menționată, a inițiat un conflict cu soția sa, numind-o cu diverse cuvinte necenzurate și agresat-o fizic cu palmele peste față, înjosindu-i demnitatea și provocându-i dureri fizice. Ulterior, la 21 februarie 2019, aproximativ orele 17 şi 30 minute, Arcadie Cotoman, fiind în stare de ebrietate alcoolică, aflîndu-se în domiciliul comun, a inițiat un conflict cu fosta sa soție și intenționat numit-o cu cuvinte necenzurate, iar la un moment a luat un cuțit în mână, comunincîndu-i că are intenția să se sinucidă, iar de consecințe ea v-a fi vinovată, astfel, insuflându-i acesteia o stare de frică, tensiune și suferință psihică exprimată prin trăiri negative profunde, generate în urma insultărilor și amenințărilor cu răfuială fizică. Acţiunile lui Cotoman Arcadie Vladimir au fost calificate de procuror în temeiul art.2011 alin.(1) lit. b) din Codul penal, adică-acţiunea și inacţiunea intenţionată, manifestată verbal, comisă de un membru al familiei asupra unui alt membru al familiei, comisă prin intimidare în scop de impunere a controlului personal asupra victimei. Tot el, la 21 februarie 2019, aproximativ orele 17:30, cunoscând despre existența ordonanței de protecție emisă de Judecătoria Străşeni, sediul Călăraşi la 12.02.2019 în favoarea victimei violenței în familie R Cotoman, prin care numitul a fost obligat pentru o perioadă de 30 zile, adică de la 12 februarie 2019 - 12 martie 2019, să părăsească temporar locuința comună situată în s. Seliştea-Nouă, r-nu Călăraşi, să


--------------------------------------------- Result 120 ---------------------------------------------
[[1 (98%)]] --> [[[SKIPPED]]]

Cet. XXXXXXXXX la data de XXXXXXXXX, în timp de zi, prin acces liber, aflîndu­se în casa amplasată pe str.Trandafirilor, 16 din s. XXXXXXXXXXlți, folosindu­se de faptul că numeni nu­i atrage atenția, de pe o canapea din odaie a suatras pe ascuns un telefon mobil de model ”Samsung GT S56” cu nr.IMEI 359158059629801, în care se afla cartela SIM nr.06116979, prin ce a cauzat cet.Bratișco Elena un prejudiciu material considerabil în sumă de 1.620 lei, după ce cu bunurile sustrase s­a eschivat de la locul comiterii infracţiunii. Prin acţiunile sale cet.XXXXXXXXXX a comis infracţiunea prevăzută de art.186 alin.(2) lit. d) Cod penal ­ furt, adică sustragerea pe ascuns a bunurilor altei persoane, cu cauzarea de daune în proporţii considerabile. Partea vătămată a solicitat încetarea procesului penal în privinţa inculpatului în legătură cu împăcarea părților, a depus cererea respectivă în acest sens, menţionînd că pretenţii materiale sau morale faţă de inculpat nu are, nedorind examinarea şi cercetarea probelor. Inculpatul a solicitat încetarea procesului penal în legătură cu împăcarea părților, recunoscînd vina în cele incriminate în rechizitoriu, nedorind examinarea şi cercetarea probelor. Conform art. 109 din Codul Penal, împăcarea este actul de înlăturare a răspunderii penale pentru o infracţiune uşoară sau mai puţin gravă, iar în cazul minorilor, şi pentru o infracţiune gravă, infracţiuni prevăzute la capitolele II – VI din Partea specială, precum şi în cazurile prevăzute de procedura penală. Împăcarea este personală şi produce efecte juridice din momentul pornirii urmăririi penale şi pînă la retragerea completului de judecată pentru deliberare. Infracţiunea prevăzute de art. 186 al.(2)Cod penal, de care se acuză cet. XXXXXXXX, conform art. 16 din codul penal, se clasifică ca infracţiune mai puţin gravă, este prevăzută de Cap.VI a părţii speciale a codului penal, deci cade sub incidenţa art.109 CP. Potrivit art.332 CPP (1) în cazul în care, pe parcursul judecării cauzei, se constată vreunul din temeiurile prevăzute în art.275 pct. 5)–9), 285 alin.(1) pct.1), 2), 4), 5), precum şi în cazurile prevăzute în art.53­60 din Codul penal, instanţa, prin sentinţă motivată, încetează procesul penal în cauza respective. (2) În cazul în care fapta persoanei constituie o contravenţie administrativă, instanţa încetează procesul penal şi, concomitent, soluţionează cauza conform prevederilor Codului contravenţional al Republicii Moldova. (3) Concomitent cu încetarea procesului penal, instanţa ia măsurile respective prevăzute în art.54 şi 55 din Codul penal, precum şi decide asupra chestiunilor prevăzute în art.285 alin.(6). (4) Sentinţa de încetare a procesului penal poate fi atacată cu apel sau, după caz, cu recurs în instanţa ierarhic superioară, în modul prevăzut de prezentul cod. (5) În cazul prevăzut la art. 275 pct. 4), încetarea procesului penal nu se admite fără acordul inculpatului. În acest caz, procedura continuă în mod obişnuit. Potrivit prevederilor art.285 CPP, încetarea urmăririi penale are loc în cazurile prevăzute în art.275, precum şi în cazul în care se constată că plîngerea prealabilă a fost retrasă de către partea vătămată sau părţile s­au împăcat – în cazurile în care urmărirea penală poate fi pornită numai în baza plîngerii prealabile sau legea penală permite împăcarea. În cazul dat instanța consideră aplicabile prevederile art­lor 109 CP și


--------------------------------------------- Result 121 ---------------------------------------------
[[0 (68%)]] --> [[[SKIPPED]]]

Elucidând şi constatând starea de lucruri descrisă mai sus, conducându-se de art. 449 alin. (1), pct. 2) lit.a) Cod de procedură penală, Colegiul judiciar,

[Succeeded / Failed / Skipped / Total] 42 / 50 / 30 / 122:  92%|█████████▏| 92/100 [17:43<01:32, 11.56s/it]

--------------------------------------------- Result 122 ---------------------------------------------
[[0 (98%)]] --> [[1 (60%)]]

Prin sentinţa judecătoriei Făleşti din 21 ianuarie 2013, [[xxxxCUSTOM1xxxx]] xxxxNUMExxxx, a.n.[[xxxxDATA_NASTERIIxxxx]], originar şi domiciliat în s.Balasineşti, r­nul Briceni, moldovean, cu studii medii incomplete, neangajat în cîmpul muncii, celibatar, nesupus militar, cetăţean al RM, cu antecedente penale, a fost recunoscut vinovat de săvîrşirea infracţiunii prevăzute de art.2011 alin. (2) lit.b) CP şi condamnat cu numirea pedepsei sub formă de închisoare pe un termen de 2 ani 6 luni. În temeiul art.85 alin.(1) CP, i s­a adăugat partea neexecutată a pedepsei stabiite prin sentinţa anterioară –8 zile închisoare, stabilindu­i­se definitiv 2 ani 6 luni 8 zile închisoare cu executarea pedepsei în penitenciar de tip închis. Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut că inculpatul xxxxCUSTOM1xxxx S. la data de 24.09.2012 în jurul orelor 19.30, fiind membru de familie cu xxxxNUMExxxx., care este tatăl său, şi aflîndu­se în gospodăria acestuia, situată în s.Balasineşti r­nul Briceni, i­a aplicat intenţionat ultimului multiple lovituri cu mîinile şi picioarele în regiunea feţei şi cutiei toracice, provocîndu­i , conform raportului de expertiză medico­legală nr.195­D din 07.11.2012, comoţie cerebrală, fractură a coastelor 5,6,7 şi 8 pe dreapta, echimoze masive la cutia toracică, care se califică ca vătămări corporale medii. Împotriva acestei sentinţe a [[declarat]] apel [[inculpatul]] xxxxNUMExxxx., [[care]] solicită casarea ei cu pronunţarea unei noi hotărîri prin care să i se aplice o pedeapsă non­privativă de libertate. Colegiul penal, verificînd argumentele invocate în [[apel]] în raport cu materialele cauzei şi cu prevederile legii de [[procedură]] penală, consideră apelul [[depus]] peste termen, urmînd a fi [[respins]] din următoarele motive. În conformitate cu art.415 alin.(1) pct.1) lit.a) CPP instanţa de apel, judecînd cauza în ordine de apel, este în drept să­l respingă în cazul în care [[este]] declarat peste termen, cu excepţia cazurilor prevăzute de art.402. Colegiul reţine şi prevederile art.402 alin.(1) CPP conform cărora termenul de apel [[este]] de 15 zile de la data pronunţării sentinţei integrale, dacă legea nu dispune altfel. Din materialele cauzei reiese că sentinţa în cauză a fost pronunţată la data de 21 martie 2013. Fiind prezent la judecrea cauzei în şedinţele instanţei de fond, precum şi la pronunţarea sentinţei în cauză la data de 21.03.2013, xxxxNUMExxxx. a primit copia de pe aceasta la aceiaşi dată, fapt confirmat prin dovada de primire (f.d.134). Apelul însă, este datat cu 17.12.2013, ­ cu omitertea evidentă a termenului de atac, fără a se solicita şi fără a se invoca careva motive, care ar servi drept temei de repunere în termen a apelului. Totodată, instanţa de apel reţine că potrivit dispoziţiei de executare (f.d.138), sentinţa în cauză a devenit definitivă la 08.04.2013 şi a fost pusă în executare. Prin urmare, Colegiul penal conchide că întîrzîierea nu este determinată de motive întemeiate. Pentru considerentele expuse, în temeiul art.415 alin.(1) pct.1) lit.a) CPP, Colegiul penal,

Prin sentinţa judecătoriei Făleşti din 21 ianuarie 2013, [[xxxxCUSOTM1xxxx]] xxxxNUMExxxx, a.n.[[xxxDxATA_NASTERIIxxxx]], originar şi domiciliat în s.Balasineşti, r­nul Briceni, moldovean, cu studii medii incomplete, neangajat în cîmpul muncii, celibatar, nesupus militar, cetăţean al RM, cu antecedente penale, a fost recunoscut vinovat de săvîrşirea infracţiunii prevăzute de art.2011 alin. (2) lit.b) CP şi condamnat cu numirea pedepsei sub formă de închisoare pe un termen de 2 ani 6 luni. În temeiul art.85 alin.(1) CP, i s­a adăugat partea neexecutată a pedepsei stabiite prin sentinţa anterioară –8 zile închisoare, stabilindu­i­se definitiv 2 ani 6 luni 8 zile închisoare cu executarea pedepsei în penitenciar de tip închis. Pentru a se pronunţa în sensul celor expuse, instanţa de fond a reţinut că inculpatul xxxxCUSTOM1xxxx S. la data de 24.09.2012 în jurul orelor 19.30, fiind membru de familie cu xxxxNUMExxxx., care este tatăl său, şi aflîndu­se în gospodăria acestuia, situată în s.Balasineşti r­nul Briceni, i­a aplicat intenţionat ultimului multiple lovituri cu mîinile şi picioarele în regiunea feţei şi cutiei toracice, provocîndu­i , conform raportului de expertiză medico­legală nr.195­D din 07.11.2012, comoţie cerebrală, fractură a coastelor 5,6,7 şi 8 pe dreapta, echimoze masive la cutia toracică, care se califică ca vătămări corporale medii. Împotriva acestei sentinţe a [[declaart]] apel [[inclupatul]] xxxxNUMExxxx., [[crae]] solicită casarea ei cu pronunţarea unei noi hotărîri prin care să i se aplice o pedeapsă non­privativă de libertate. Colegiul penal, verificînd argumentele invocate în [[aepl]] în raport cu materialele cauzei şi cu prevederile legii de [[prcoedură]] penală, consideră apelul [[deups]] peste termen, urmînd a fi [[repsins]] din următoarele motive. În conformitate cu art.415 alin.(1) pct.1) lit.a) CPP instanţa de apel, judecînd cauza în ordine de apel, este în drept să­l respingă în cazul în care [[etse]] declarat peste termen, cu excepţia cazurilor prevăzute de art.402. Colegiul reţine şi prevederile art.402 alin.(1) CPP conform cărora termenul de apel [[etse]] de 15 zile de la data pronunţării sentinţei integrale, dacă legea nu dispune altfel. Din materialele cauzei reiese că sentinţa în cauză a fost pronunţată la data de 21 martie 2013. Fiind prezent la judecrea cauzei în şedinţele instanţei de fond, precum şi la pronunţarea sentinţei în cauză la data de 21.03.2013, xxxxNUMExxxx. a primit copia de pe aceasta la aceiaşi dată, fapt confirmat prin dovada de primire (f.d.134). Apelul însă, este datat cu 17.12.2013, ­ cu omitertea evidentă a termenului de atac, fără a se solicita şi fără a se invoca careva motive, care ar servi drept temei de repunere în termen a apelului. Totodată, instanţa de apel reţine că potrivit dispoziţiei de executare (f.d.138), sentinţa în cauză a devenit definitivă la 08.04.2013 şi a fost pusă în executare. Prin urmare, Colegiul penal conchide că întîrzîierea nu este determinată de motive întemeiate. Pentru considerentele expuse, în temeiul art.415 alin.(1) pct.1) lit.a) CPP, Colegiul penal,

[Succeeded / Failed / Skipped / Total] 42 / 51 / 31 / 124:  93%|█████████▎| 93/100 [17:57<01:21, 11.59s/it]

--------------------------------------------- Result 123 ---------------------------------------------
[[0 (100%)]] --> [[[FAILED]]]

(Cauza penală a parvenit în instanţa de fond la 05.01.2015) Inculpatul xxxx, la 07 decembrie 2014, în jurul orelor 22:00, fiind în stare de ebrietate alcoolică, posesor la permisului de conducere nr. 098300993 din 24.07.2009 cu categoria „B”, încălcînd cerinţele art. 14 pct. a) din Regulamentul circulaţiei rutiere care determină, că conducătorului de vehicul îi este interzis să conducă vehiculul în stare de ebrietate, s­a urcat la volanul automobilului de model „Dacia Logan” cu n/î xxxx şi conducîndu­l pe traseul M2 km 134+65, în apropiere de s. Stoicani, r­l Soroca, neisprăvindu­se cu conducerea acestuia, a derapat de pe traseu, lovindu­se cu automobilul de copacii de pe marginea drumului. Accidentul rutier în care a fost implicat xxxx nu s­a soldat cu careva persoane traumate, iar ultimul se afla de unul singur în automobil în momentul producerii accidentului. La scurt timp, la faţa locului au sosit colaboratorii de poliţie, unde xxxxx, fiind suspectat că ar fi condus mijlocul de transport în stare de ebrietate i s­a propus de a trece alcotestul „Drager”. Conform art. 31412 alin. (3) Cod Penal, ,,prin stare de ebrietate alcoolică cu grad avansat se înţelege starea persoanei care are concentraţia de alcool în sînge de la 1,0 g/l şi mai mult, sau concentraţia vaporilor de alcool în aerul expirat de la 0,5 mg/l şi mai mult”. Fiind verificată proba alcotest, testat prin intermediul aparatului ,,Drager alcotest” s­a constatat, că la momentul verificării cet. Volontir Dumitru Ion, a.n. 10.12.1980 avea concentrația vaporilor de alcool în aerul expirat de 0,72 mg/l. Pînă la începerea cercetării judecătoreşti inculpatul xxxx a solicitat prin înscris autentic ca judecata să aibă loc pe baza probelor administrate în faza de urmărire penală, pe care le cunoaşte şi asupra cărora nu are obiecţii, indicînd că recunoaşte săvîrşirea faptelor indicate în rechizitoriu. Prin încheierea instanţei de judecată s­a admis cererea inculpatului privind judecarea cauzei pe baza probelor administrate în faza de urmărire penală. În şedinţă judiciară inculpatul xxxx sub jurămînt a recunoscut săvîrşirea faptelor indicate în rechizitoriu şi a declarat instanţei că se căieşte sincer de cele săvîrşite şi pe viitor nu va mai comite asemenea fapte. Pe lîngă faptul că inculpatul xxxx şi­a recunoscut vina, vinovăţia sa este dovedită pe deplin şi prin cumulul de probe prezentate de către procuror, şi anume: ­ procesul­verbal de audiere a martorului xxxx, care a declarat că activează în calitate de inspector inferior al serviciului supraveghere tehnică şi accidente rutiere a IP Soroca. Astfel la data de 04.12.2014 aproximativ în jurul orei 22:50 min, aflîndu­se la serviciu în calitate de membru al grupei operative a IP Soroca, de către unitatea de gardă a IP Soroca a fost anunţat precum că pe traseul M2 în apropiere de s. Stoicani r­nul Soroca un automobil a derapat de pe traseu. Deplasându­se la faţa locului în timpul examinării cazului a stabilit că automobilul de model „Dacia Logan” cu n/î xxxx care era condus de către cet. xxxx a derapat de pe traseu în urma cărui fapt automobilul a fost deteriorat parţial. Careva pasageri în automobilul dat nu se aflau. La faţa locului se aflau mai mulţi


--------------------------------------------- Result 124 ---------------------------------------------
[[1 (86%)]] --> [[[SKIPPED]]]

De către organul de urmărire penală, xxxxNUMExxxx se învinuieşte în aceea că la data de 01 februarie 2011 de pe teritoriul ÎM „Gospodăria comunal­locativă şi construcţii xxxxCUSTOM1xxxx” persoane nestabilite au furat un distribuitor de apă în valoare de 3500 lei, în legătură cu ce în următoarele zile, data nefiind putut fi stabilită în cadrul urmăririi penale, director al ÎM ,,Gospodăria Locativă –Comunală şi Construcţii” xxxxCUSTOM1xxxx G V.V. s­a adresat la colaboratorul poliţiei criminalistice CPR xxxxCUSTOM1xxxx cu cererea privind furtul distribuitorului de apă. La rîndul său, ŞE, fiind în funcţie de inspector al Secţiei criminalistice a Comisariatului de Poliţie raionului xxxxCUSTOM1xxxx şi fiind persoana publică, aflîndu­se în exerciţiul funcţiunii, urmărind interesele proprii cu scopul neexecutării atribuţiilor de funcţie de descoperire a infracţiunii, precum şi eschivarea de la evidenţă şi înregistrare a infracţiunii respective pentru îmbunătăţirea indicatorului său statistic şi creării aparenţei bunăstării în combaterea criminalităţii, n­a înregistrat în mod corespunzător cererea IM GLCC xxxxCUSTOM1xxxx şi n­a efectuat verificarea cererii respective. Totodată, cu scopul creării aparenţei că cererea IM GLCC xxxxCUSTOM1xxxx a fost examinată şi întru evitarea contestaţiilor acţiunilor acestuia, xxxxCUSTOM1xxxx E. a perfectat cu ajutorul xeroxului şi a imprimantei laser ­ un document oficial falsificat „înştiinţare” din numele comisarului CPR xxxxCUSTOM1xxxx Ş D.F. şi a introdus conştient informaţia falsă, precum că comisariatul de poliţie xxxxCUSTOM1xxxx examinează faptul de furt al distribuitorului de apă şi pe faptul acesta a fost pornită urmărirea penală nr.2010460116 pe art.186 al.2) Cod penal RM. După perfectarea acestui document falsificat, xxxxCUSTOM1xxxx E.E. la data de 05.04.2011 a înregistrat această înştiinţare în Registru de evidenţă a corespondenţei de ieşire CPR xxxxCUSTOM1xxxx cu nr.3203 şi a transmis acest document falsificat solicitantului, prin ce pe ultimul la dus în eroare, precum că pe faptul furtului de distribuitor de apă, care aparţine ÎM GLCC xxxxCUSTOM1xxxx, se exercită urmărirea penală. Pe cînd cauza penală nr.2010460116 a fost intentată de OUP D P.D. la 02.06.2010 pe art.186 al.(2) lit.c) CP RM pe faptul furtului a două motoare electrice de la ÎM,,Apă­Canal xxxxCUSTOM1xxxx”, şi nu pe faptul furtului distribuitorului de apă de pe teritoriul ÎM GLCC xxxxCUSTOM1xxxx. Astfel acţiunile lui xxxxCUSTOM1xxxx E.E. au fost încadrate pe art.332 al.(1) CP RM, ca falsul în acte publice, adică falsificarea de către o persoană publică a unor documente oficiale săvîrşită din interes personal, cu scopul neexecutării atribuţiilor de funcţie de descoperire a infracţiunii, precum şi eschivarea de la evidenţă şi înregistrare a infracţiunii respective pentru îmbunătăţirea indicatorului său statistic şi creării aparenţei bunăstării în combaterea criminalităţii. Tot lui xxxxCUSTOM1xxxx xxxxNUMExxxx i­a fost înaintată învinuirea în aceea, că fiind în funcţie de inspector al Secţiei criminalistice a Comisariatului de Poliţie raionului xxxxCUSTOM1xxxx şi persoana publică, aflîndu­se în exerciţiul funcţiunii, în perioada de 01.02.2011 pînă la 05.04.2011 (data sigură nefiind stabilită în cadrul urmăririi penale) a primit de la director al ÎM GLCC xxxxCUSTOM1xxxx G V.V. o cerere scrisă privind faptul, că la data de 01 februarie 2011 de pe teritoriul ÎM „Gospodăria Locativă –Comunală şi Construcţii” persoane nestabilite au furat distribuitorul de apă. Dar, xxxxCUSTOM1xxxx E.E., urmărind interesele proprii cu scopul neexecutării atribuţiilor de funcţie pe descoperirea infracţiunii, precum şi

[Succeeded / Failed / Skipped / Total] 43 / 51 / 31 / 125:  94%|█████████▍| 94/100 [18:06<01:09, 11.56s/it]

--------------------------------------------- Result 125 ---------------------------------------------
[[1 (57%)]] --> [[0 (97%)]]

1. [[Inculpatul]] Rabei Victor, la 11.12.2016, aproximativ la ora 04:00, dimineața, aflîndu-se în apropierea casei amplasate pe adresa mun. Bălți, str-la Apeductului, 4, urmărind scopul satisfacerii poftei sale sexuale, aplicînd față de cet. Spijavca Elena, constrîngere fizică și psihică, care s-a manifestat prin amenințări cu răfuială fizică și aplicarea loviturilor cu pumnul în regiunea capului și a altor regiuni ale corpului, a dezbrăcat-o forțat de haine și contra voinței sale, a întreținut cu ea un raport sexual în formă obişnuită. 2. În ședinţa de judecată, inculpatul Rabei Victor, care până la începerea cercetării judecătorești, a recunoscut în totalitate faptele indicate în rechizitoriu, și-a recunoscut vina, nesolicitând administrarea de probe noi, prin cerere scrisă personal, a solicitat examinarea cauzei penale în baza probelor administrate în faza de urmărire penală, pe care le recunoaște și asupra cărora nu are obiecţii. 3. Avocatul Corina Movilă, procurorul Cristina Cîrma și partea civilă ***** au susţinut cererea înaintată de inculpat. Constatând că probele administrate la urmărirea penală stabilesc faptele inculpatului, instanţa a admis cererea acestuia de judecare a cauzei în ordinea prevăzută în art. 3641 Cod de procedură penală, pe baza probelor administrare în faza de urmărire penală, care corespunde cerințelor de formă și de conținut. Inculpatul Rabei Victor, în ședinţa de judecată prin expunerea factologică, ce nu contravine învinuirii formulate în rechizitoriu, și-a recunoscut integral vinovăţia. 3.1. Partea civilă ***** a depus în cadrul examinării cauzei cerere prin care a solicitat încetarea cauzei penale intentate în privința lui *****din motivul împăcării părților, menționînd că careva pretenții față de ultimul nu are. 4. Analizând declaraţiile inculpatului, depuse în ședinţa de judecată, în raport cu cele depuse în cursul urmăririi penale, instanţa le reţine ca fiind în concordanţă cu circumstanţele de fapt ale cauzei, considerându-le veridice și convingătoare. Vina inculpatului *****în săvîrșirea infracțiunii prevăzute de art. 171 alin. (1) Cod penal, se confirmă și prin următoarele probe examinate în ședinţa de judecată, administrate la urmărirea penală: -procesul-verbal de cercetare la fața locului din 11.12.2016 (f.d.10-12); -raportul de expertiză medico-legală nr. 096 din 04.01.2017 (f.d.46-49); -raportul de expertiză judiciară nr. 08a din 01.02.2017 (f.d.60-63); -ordonanța de ridicare (f.d.30); -procesul-verbal de ridicare (f.d.31); -procesul-verbal de examinare a obiectului (f.d.32); -ordonanța de recunoaștere și anexare a corpurilor delicte la cauza penală (f.d.33); -procesul-verbal de confruntare din 13.12.2016 (f.d.80-83). 5. În conformitate cu art. 101 alin. (1), (2) Cod de procedură penală, fiecare probă urmează să fie apreciată din punct de vedere al pertinenţei, concludenţei, utilităţii şi veridicităţii ei, iar toate probele în ansamblu – din punct de vedere al coroborării lor. Judecătorul apreciază probele conform propriei convingeri, formate în urma examinării lor în ansamblu, sub toate aspectele şi în mod obiectiv, călăuzindu-se de lege. În rezultatul analizei probelor indicate, din punct de vedere al coroborării lor, instanţa a ajuns la concluzia că acţiunile inculpatului *****au fost corect încadrate în baza art. 171 alin. (1) Cod penal, violul, adică raportul sexual săvîrșit prin constrîngere fizică sau psihică a persoanei. 6. La fel, inculpatul pe lîngă cererea adresată instanței în ordinea art. 3641 Cod de procedură penală, a solicitat prin cerere și încetarea

1. [[Incuplatul]] Rabei Victor, la 11.12.2016, aproximativ la ora 04:00, dimineața, aflîndu-se în apropierea casei amplasate pe adresa mun. Bălți, str-la Apeductului, 4, urmărind scopul satisfacerii poftei sale sexuale, aplicînd față de cet. Spijavca Elena, constrîngere fizică și psihică, care s-a manifestat prin amenințări cu răfuială fizică și aplicarea loviturilor cu pumnul în regiunea capului și a altor regiuni ale corpului, a dezbrăcat-o forțat de haine și contra voinței sale, a întreținut cu ea un raport sexual în formă obişnuită. 2. În ședinţa de judecată, inculpatul Rabei Victor, care până la începerea cercetării judecătorești, a recunoscut în totalitate faptele indicate în rechizitoriu, și-a recunoscut vina, nesolicitând administrarea de probe noi, prin cerere scrisă personal, a solicitat examinarea cauzei penale în baza probelor administrate în faza de urmărire penală, pe care le recunoaște și asupra cărora nu are obiecţii. 3. Avocatul Corina Movilă, procurorul Cristina Cîrma și partea civilă ***** au susţinut cererea înaintată de inculpat. Constatând că probele administrate la urmărirea penală stabilesc faptele inculpatului, instanţa a admis cererea acestuia de judecare a cauzei în ordinea prevăzută în art. 3641 Cod de procedură penală, pe baza probelor administrare în faza de urmărire penală, care corespunde cerințelor de formă și de conținut. Inculpatul Rabei Victor, în ședinţa de judecată prin expunerea factologică, ce nu contravine învinuirii formulate în rechizitoriu, și-a recunoscut integral vinovăţia. 3.1. Partea civilă ***** a depus în cadrul examinării cauzei cerere prin care a solicitat încetarea cauzei penale intentate în privința lui *****din motivul împăcării părților, menționînd că careva pretenții față de ultimul nu are. 4. Analizând declaraţiile inculpatului, depuse în ședinţa de judecată, în raport cu cele depuse în cursul urmăririi penale, instanţa le reţine ca fiind în concordanţă cu circumstanţele de fapt ale cauzei, considerându-le veridice și convingătoare. Vina inculpatului *****în săvîrșirea infracțiunii prevăzute de art. 171 alin. (1) Cod penal, se confirmă și prin următoarele probe examinate în ședinţa de judecată, administrate la urmărirea penală: -procesul-verbal de cercetare la fața locului din 11.12.2016 (f.d.10-12); -raportul de expertiză medico-legală nr. 096 din 04.01.2017 (f.d.46-49); -raportul de expertiză judiciară nr. 08a din 01.02.2017 (f.d.60-63); -ordonanța de ridicare (f.d.30); -procesul-verbal de ridicare (f.d.31); -procesul-verbal de examinare a obiectului (f.d.32); -ordonanța de recunoaștere și anexare a corpurilor delicte la cauza penală (f.d.33); -procesul-verbal de confruntare din 13.12.2016 (f.d.80-83). 5. În conformitate cu art. 101 alin. (1), (2) Cod de procedură penală, fiecare probă urmează să fie apreciată din punct de vedere al pertinenţei, concludenţei, utilităţii şi veridicităţii ei, iar toate probele în ansamblu – din punct de vedere al coroborării lor. Judecătorul apreciază probele conform propriei convingeri, formate în urma examinării lor în ansamblu, sub toate aspectele şi în mod obiectiv, călăuzindu-se de lege. În rezultatul analizei probelor indicate, din punct de vedere al coroborării lor, instanţa a ajuns la concluzia că acţiunile inculpatului *****au fost corect încadrate în baza art. 171 alin. (1) Cod penal, violul, adică raportul sexual săvîrșit prin constrîngere fizică sau psihică a persoanei. 6. La fel, inculpatul pe lîngă cererea adresată instanței în ordinea art. 3641 Cod de procedură penală, a solicitat prin cerere și încetarea

[Succeeded / Failed / Skipped / Total] 43 / 52 / 31 / 126:  95%|█████████▌| 95/100 [18:18<00:57, 11.56s/it]

--------------------------------------------- Result 126 ---------------------------------------------
[[0 (99%)]] --> [[[FAILED]]]

Prin sentința judecătoriei Ungheni din 12.07.2013, xxxxNUMExxxx a fost condamnat în baza art.179 al.1, 171 al.1 CP al RM, cu aplicarea art.84 CP al RM, stabilindu­i definitiv pedeapsa 3 ani închisoare în penitenciar de tip semiînchis. În cadrul executării pedepsei penale, condamnatul xxxxNUMExxxx a sesizat judecătoria Bălți cu cerere privind înlocuirea părții neexecutate a pedepsei penale cu alta mai blîndă. Prin încheierea din 13.05.2014, instanța a respins solicitarea condamnatului pe motiv, că condamnatul în timpul executării pedepsei a manifestat un comportament obraznic, are sancțiuni disciplinare și n­a executat cel puțin 1/3 din termenul stabilit. Contestînd în ordinea art. 445 Cod procedură penală, legalitatea și temeinicia încheierii judiciare, condamnatul xxxxNUMExxxx prin recursul declarat și­a păstrat cerințele inițiale privind aplicarea dispozițiilor art. 92 Cod penal. Procedura citării legale și actele procesuale preparatorii judecării cauzei în instanța de recurs au fost executate. La ședința instanței de recurs condamnatul xxxxNUMExxxx și avocatul ce­i apără interesele Rodica Cojocar au susținut cererea de recurs. Procurorul participant la judecarea cauzei, consideră recursul nefondat și pasibil de a fi respins. Verificînd argumentele invocate în recurs în raport cu materialele cauzei şi cu prevederile legii, Colegiul penal consideră recursul nefondat, urmînd a fi respins din următoarele motive. Potrivit dispoziţiei art. 92 CP în privinţa persoanelor care execută pedeapsa cu închisoare pentru săvîrşirea unei infracţiuni uşoare sau mai puţin grave, instanţa de judecată, ţinînd cont de comportarea lor în timpul executării pedepsei, poate pronunţa o încheiere cu privire la înlocuirea părţii neexecutate din pedeapsă cu o pedeapsă mai blîndă. Înlocuirea părţii neexecutate a pedepsei cu o pedeapsă mai blîndă poate fi aplicată numai după ce condamnatul a executat efectiv cel puţin o treime din termenul de pedeapsă. După cum se observă din materialele cauzei xxxxNUMExxxx a fost condamnat pentru săvîrşirea unor infracţiuni mai puţin grave şi la momentul soluţionării chestiunii privind înlocuirea părţii neexecutate din pedeapsă cu o pedeapsă mai blîndă n­a executat efectiv o treime din termenul de pedeapsă, acesta urma a fi aplicabil din 14.06.2014. Conform materialelor cauzei xxxxNUMExxxx se caracterizează negativ, are un comportament obraznic, fiindu­i applicate sancțiuni disciplinare. Prin urmare, soluţia instanţei de fond este legală şi întemeiată. Instanța a ţinut cont de persoana condamnatului, de comportarea lui în timpul executării pedepsei, fapt reflectat în materialele prezentate de către administraţia penitenciarului, cît și de faptul neexecutării cel puțin 1/3 din termenul stabilit. În atare împrejurări, la judecarea recursului nu au fost constatate motive ce ar servi drept temei pentru admiterea recursului. În conformitate cu cele expuse și în temeiul art.449 alin.(1) pct.1 lit.a) CPP, Colegiul penal,

[Succeeded / Failed / Skipped / Total] 44 / 52 / 31 / 127:  96%|█████████▌| 96/100 [18:18<00:45, 11.44s/it]

--------------------------------------------- Result 127 ---------------------------------------------
[[0 (70%)]] --> [[1 (53%)]]

[[Călăuzindu-se]] de [[prevederile]] art. 448, 449, alin. (1), pct. 1), lit. b) Cod de [[procedură]] [[penală]], Colegiul judiciar, -

[[Călăuizndu-se]] de [[prevedreile]] art. 448, 449, alin. (1), pct. 1), lit. b) Cod de [[proceudră]] [[pneală]], Colegiul judiciar, -

[Succeeded / Failed / Skipped / Total] 45 / 52 / 31 / 128:  97%|█████████▋| 97/100 [18:29<00:34, 11.44s/it]

--------------------------------------------- Result 128 ---------------------------------------------
[[0 (99%)]] --> [[1 (55%)]]

XXXXXXX, fiind în relaţii de căsătorie cu XXXXXXXXXXX, locuind împreună în același domiciliul situat în XXXXXXXXXXX în noaptea d 21 septembrie 2015, aflînd­se la domiciliu nominalizat, avînd un comportament agresiv și violent, a numit­o cu cuvinte [[necenzurate]] și i­a aplicat lovituri peste diferite [[ărți]] ale corpului soției sale Nadejda [[Devițchi]] cauzîndu­i conform raportului de expertiză medico legală nr. 222D din 13.10.201 corporale neînsemnate sub foră de echimoze pe ambele brațe și antebrațe, totodată a deteriorat mai multe bunuri din domiciliu, provocîndu­i astfel fizice, psihice, prejudiciu materiași moral. În ședința de judecată, inculpatul , [[pînă]] la începerea cercetării judecătoreşti, a recunoscut în totalitate faptele indicate în rechizitoriu, și­a recuno nesolicitînd administrarea de probe noi, prin cerere scră personal, a solicitat examinarea cauzei penale în baza probelor administrate la urmărirea p care le recun ște și asupra cărora nu are obiecții. Avocatul Dandara Ion și procurorul Clevada Adrian au susținut cererea înaintată de [[inculpat]]. [[Constatînd]] că probele administrate la urmărirea penală stabilesc fapta inculpatului, instanța a admis cererea de judecare a cauzei în ordinea pre art.364/1 CPP, pe baza probelor administrate în cadrul urăririi penale. Inculpatul XXXXXXXXXX, fiind audiat în ședința de judecată, sub jurămînt conform prevederilor art.364/1 Cod de procedură penală, prin e [[factologiă]], ce nu contravine învinuirii formulate în rechizitoriu, și­a recunoscut integral vinovăția și a dat declarații care confirmă circumstanțele des sus, meționînd că­i [[pare]] rău de cele comise (a se vedea procesul­verbal al ședinței de judecată). Analizînd declarațiile inculpatului, depuse în ședința de judecată, în raport cu cele depuse în cursul [[urmăririi]] penale, instanța le reține ca concordață cu circumstanțele de fapt ale cauzei, considerîndu­le veridice și convingătoare. Pe lîngă faptul că inculpatul XXXXXXXXXX a [[recunoscut]] vina, în ședința de judecată vinovăția acestuia mai este dovedită prin următoarele probe: ­ procesul [[verbal]] de [[sesizare]] despre săvîrşirea infracţiunii.(f.d.3); ­ process­verbal de cercetare la fața locului.(f.d.4­11); ­ process­verbal de [[examinare]] a obiectului.(f.d.12); ­ raport de constatare medico­legală nr. 222D din 13.10.[[2015]].(f.d.24); ­ procesul­verbal de confruntare.(f.d.39); ­ declaraţiile părţii vătămate XXXXXXXX.(f.d.15­16); ­ declaraţiile martorului XXXXXXXXXX.(f.d.35); ­ declaraţiile martorului XXXXXXXXXX.(f.d.36­37); ­ declaraţiile martorului XXXXXXXX.(f.d.38); ­ precum și alte documente ale cauzei, care coroborate cu declarațiile inculpatului constituie probe utile, pertinente și concludente ale cauzei și for ansamblu probator ce confiră totalmente vinovăția inculpatului, fiind puse de instanță la baza sentinței. Analizînd probele cercetate în ședința de judecată prin prisma prevederilor art.101 CPP, în virtutea cărora, fiecare probă urmează să fie apre punct de vedere al pertineței, concludenței, utilității și veridicității ei, iar toate aspectele și în mod obiectiv, călăuzindu­se de lege, se ajunge la conclu edi ța de judecată cu certitudine s­a dovedit vinovăția inculpatului Devițchii Serghei în comiterea infracțiunii incriminate, acțiunile acestuia f calificate în ba art.2011 alin.(1) Cod penal ca violenţă în familie, adică acţiunea intenţionată, manifestată fizic şi verbal, comisă de un membru al asupra unui alt membru al familiei, care a provocat suferiţă fizică, psihică, prejudiciu moral. Infracțiunea prevăzută la art.201/1 alin.(1) Cod penal se pedepsește cu muncă neremunerată în folosul comunității de la 150 la 180 de or închisoare de pîă la 2 ani. În conformitate cu art.3641 alin.8

XXXXXXX, fiind în relaţii de căsătorie cu XXXXXXXXXXX, locuind împreună în același domiciliul situat în XXXXXXXXXXX în noaptea d 21 septembrie 2015, aflînd­se la domiciliu nominalizat, avînd un comportament agresiv și violent, a numit­o cu cuvinte [[neceznurate]] și i­a aplicat lovituri peste diferite [[ățri]] ale corpului soției sale Nadejda [[Devițhci]] cauzîndu­i conform raportului de expertiză medico legală nr. 222D din 13.10.201 corporale neînsemnate sub foră de echimoze pe ambele brațe și antebrațe, totodată a deteriorat mai multe bunuri din domiciliu, provocîndu­i astfel fizice, psihice, prejudiciu materiași moral. În ședința de judecată, inculpatul , [[pnîă]] la începerea cercetării judecătoreşti, a recunoscut în totalitate faptele indicate în rechizitoriu, și­a recuno nesolicitînd administrarea de probe noi, prin cerere scră personal, a solicitat examinarea cauzei penale în baza probelor administrate la urmărirea p care le recun ște și asupra cărora nu are obiecții. Avocatul Dandara Ion și procurorul Clevada Adrian au susținut cererea înaintată de [[inuclpat]]. [[Cosntatînd]] că probele administrate la urmărirea penală stabilesc fapta inculpatului, instanța a admis cererea de judecare a cauzei în ordinea pre art.364/1 CPP, pe baza probelor administrate în cadrul urăririi penale. Inculpatul XXXXXXXXXX, fiind audiat în ședința de judecată, sub jurămînt conform prevederilor art.364/1 Cod de procedură penală, prin e [[factoolgiă]], ce nu contravine învinuirii formulate în rechizitoriu, și­a recunoscut integral vinovăția și a dat declarații care confirmă circumstanțele des sus, meționînd că­i [[prae]] rău de cele comise (a se vedea procesul­verbal al ședinței de judecată). Analizînd declarațiile inculpatului, depuse în ședința de judecată, în raport cu cele depuse în cursul [[urmăirrii]] penale, instanța le reține ca concordață cu circumstanțele de fapt ale cauzei, considerîndu­le veridice și convingătoare. Pe lîngă faptul că inculpatul XXXXXXXXXX a [[recuonscut]] vina, în ședința de judecată vinovăția acestuia mai este dovedită prin următoarele probe: ­ procesul [[vrebal]] de [[sesziare]] despre săvîrşirea infracţiunii.(f.d.3); ­ process­verbal de cercetare la fața locului.(f.d.4­11); ­ process­verbal de [[exaimnare]] a obiectului.(f.d.12); ­ raport de constatare medico­legală nr. 222D din 13.10.[[2105]].(f.d.24); ­ procesul­verbal de confruntare.(f.d.39); ­ declaraţiile părţii vătămate XXXXXXXX.(f.d.15­16); ­ declaraţiile martorului XXXXXXXXXX.(f.d.35); ­ declaraţiile martorului XXXXXXXXXX.(f.d.36­37); ­ declaraţiile martorului XXXXXXXX.(f.d.38); ­ precum și alte documente ale cauzei, care coroborate cu declarațiile inculpatului constituie probe utile, pertinente și concludente ale cauzei și for ansamblu probator ce confiră totalmente vinovăția inculpatului, fiind puse de instanță la baza sentinței. Analizînd probele cercetate în ședința de judecată prin prisma prevederilor art.101 CPP, în virtutea cărora, fiecare probă urmează să fie apre punct de vedere al pertineței, concludenței, utilității și veridicității ei, iar toate aspectele și în mod obiectiv, călăuzindu­se de lege, se ajunge la conclu edi ța de judecată cu certitudine s­a dovedit vinovăția inculpatului Devițchii Serghei în comiterea infracțiunii incriminate, acțiunile acestuia f calificate în ba art.2011 alin.(1) Cod penal ca violenţă în familie, adică acţiunea intenţionată, manifestată fizic şi verbal, comisă de un membru al asupra unui alt membru al familiei, care a provocat suferiţă fizică, psihică, prejudiciu moral. Infracțiunea prevăzută la art.201/1 alin.(1) Cod penal se pedepsește cu muncă neremunerată în folosul comunității de la 150 la 180 de or închisoare de pîă la 2 ani. În conformitate cu art.3641 alin.8

[Succeeded / Failed / Skipped / Total] 46 / 52 / 31 / 129:  98%|█████████▊| 98/100 [18:38<00:22, 11.41s/it]

--------------------------------------------- Result 129 ---------------------------------------------
[[1 (96%)]] --> [[0 (78%)]]

Pentru a se expune în sensul celor expuse, instanţa de fond a reţinut că xxxxNUMExxxx, la 02.11.2014, aproximativ pe la orele 22.oo, aflîndu­se în stare de ebrietate produsă de alcool, urmărind intenția de a aplica violență psihică și fizică în privința unui membru a familiei, în propria casă situată în satul xxxxORAS_SATxxxx, raionul , sub pretextul unor conflicte cu soția sa xxxxNUMExxxx, intenționat, în scop de atingere a vieții, integrității corporale și psihologice a unui membru al familiei, în timpul unei cerți, întru demonstrarea supremației asupra soției, a manifestat violență psihică în privința acesteia, a agresat­o verbal și a intimidat­o, numind­o cu cuvinte necenzurate și injurioase, provocîndu­i sentimentul de temere, după care a aplicat violență fizică în privința ei, exprimată prin aplicarea unei lovituri de la spate cu o vargă metalică peste cap, ca rezultat i­a provocat o permamentă stare de teamă, panică și neliniște din cauza incertitudinii cu privire la ceia ce se va întîmpla. În circumstanțele menționate, ca rezultat al violenței fizice și psihice, întreprinse de către xxxxNUMExxxx, soției sale xxxxNUMExxxx, i­au fost provocate suferințe fizice și suferințe psihice, însoțite de cauzarea vătămărilor corporale sub formă de: traumatizm cranio­cerebral închis, manifestat prin hemoragie subdurală, hematom subdural 60­70 ml., hemoragie subarahnoidiană, care potrivit raportului de expertiză medico­lșegală nrl.253 (D) din 17.12.2014, corespund gradului de leziuni corporale grave, periculoase pentru viață. Instanţa de fond a pronunţat sentinţa nominalizată. Înculpatul și partea vătămată în termen a [[atacat]] cu [[apel]] sentinţa, ambii invocînd ca motive că: pedeapsa aplicată este prea aspră și solicitînd atenuarea acesteia și aplicarea unei pedepse nonprivative de libertate. În şedinţa instanţei de apel inculpatul xxxxNUMExxxx, apărătorul care i­a apărat interesele au solicitat admiterea apelulurilor declarate pe motivele invocate, casarea sentinței și pronunțarea unei noi hotărîri prin care pedeapsa stabilită inculpatului să fie atenuată. Partea vătămată xxxxNUMExxxx a declarat, că apelul declarat nu­l susține din motiv, că a fost mințită de rudele inculpatului pentru a­l semna. Inculpatul pe percursul vieții în comun sistematic a maltratat­o. Ea l­ar putea ierta doar în condiția, că respectivul va promite că pe viitor nu o va mai bate. Procurorul participant a solicitat respingerea apelurilor cu menţinerea fără modificări a sentinţei instanţei de fond. Verificînd argumentele apelului în raport cu materialele cauzei şi prevederile legii, ţinînd cont de opiniile participanţilor la proces, Colegiul a ajuns la concluzia, că apelul ca nefondat urmează a fi respins. Potrivit prevederilor art.415 alin.(1) pct.1) lit.c) CP instanţa de apel, judecînd cauza în ordine de apel, adoptă una din următoarele decizii…şi anume: respinge apelul, menţinînd hotărîrea atacată, dacă: apelul este nefondat. În argumentarea soluţiei reţinute pe caz, Colegiul ţine să menţioneze că în cadrul judecării cauzei în prima instanţă de judecată inculpatul xxxxNUMExxxx şi­a recunoscut integral vinovăţia adusă pe caz, a recunoscut săvîrşirea faptelor indicate în rechizitoriu şi a solicitat personal prin înscris autentic ca judecata să se facă pe baza probelor administrate în faza urmăririi penale, în procedura 1 prevăzută de art.364 CPP. În baza probelor acumulate la urmărirea penală şi recunoscute de inculpat, instanţa de fond corect a stabilit starea de fapt şi de 1 drept pe caz şi

Pentru a se expune în sensul celor expuse, instanţa de fond a reţinut că xxxxNUMExxxx, la 02.11.2014, aproximativ pe la orele 22.oo, aflîndu­se în stare de ebrietate produsă de alcool, urmărind intenția de a aplica violență psihică și fizică în privința unui membru a familiei, în propria casă situată în satul xxxxORAS_SATxxxx, raionul , sub pretextul unor conflicte cu soția sa xxxxNUMExxxx, intenționat, în scop de atingere a vieții, integrității corporale și psihologice a unui membru al familiei, în timpul unei cerți, întru demonstrarea supremației asupra soției, a manifestat violență psihică în privința acesteia, a agresat­o verbal și a intimidat­o, numind­o cu cuvinte necenzurate și injurioase, provocîndu­i sentimentul de temere, după care a aplicat violență fizică în privința ei, exprimată prin aplicarea unei lovituri de la spate cu o vargă metalică peste cap, ca rezultat i­a provocat o permamentă stare de teamă, panică și neliniște din cauza incertitudinii cu privire la ceia ce se va întîmpla. În circumstanțele menționate, ca rezultat al violenței fizice și psihice, întreprinse de către xxxxNUMExxxx, soției sale xxxxNUMExxxx, i­au fost provocate suferințe fizice și suferințe psihice, însoțite de cauzarea vătămărilor corporale sub formă de: traumatizm cranio­cerebral închis, manifestat prin hemoragie subdurală, hematom subdural 60­70 ml., hemoragie subarahnoidiană, care potrivit raportului de expertiză medico­lșegală nrl.253 (D) din 17.12.2014, corespund gradului de leziuni corporale grave, periculoase pentru viață. Instanţa de fond a pronunţat sentinţa nominalizată. Înculpatul și partea vătămată în termen a [[aatcat]] cu [[aepl]] sentinţa, ambii invocînd ca motive că: pedeapsa aplicată este prea aspră și solicitînd atenuarea acesteia și aplicarea unei pedepse nonprivative de libertate. În şedinţa instanţei de apel inculpatul xxxxNUMExxxx, apărătorul care i­a apărat interesele au solicitat admiterea apelulurilor declarate pe motivele invocate, casarea sentinței și pronunțarea unei noi hotărîri prin care pedeapsa stabilită inculpatului să fie atenuată. Partea vătămată xxxxNUMExxxx a declarat, că apelul declarat nu­l susține din motiv, că a fost mințită de rudele inculpatului pentru a­l semna. Inculpatul pe percursul vieții în comun sistematic a maltratat­o. Ea l­ar putea ierta doar în condiția, că respectivul va promite că pe viitor nu o va mai bate. Procurorul participant a solicitat respingerea apelurilor cu menţinerea fără modificări a sentinţei instanţei de fond. Verificînd argumentele apelului în raport cu materialele cauzei şi prevederile legii, ţinînd cont de opiniile participanţilor la proces, Colegiul a ajuns la concluzia, că apelul ca nefondat urmează a fi respins. Potrivit prevederilor art.415 alin.(1) pct.1) lit.c) CP instanţa de apel, judecînd cauza în ordine de apel, adoptă una din următoarele decizii…şi anume: respinge apelul, menţinînd hotărîrea atacată, dacă: apelul este nefondat. În argumentarea soluţiei reţinute pe caz, Colegiul ţine să menţioneze că în cadrul judecării cauzei în prima instanţă de judecată inculpatul xxxxNUMExxxx şi­a recunoscut integral vinovăţia adusă pe caz, a recunoscut săvîrşirea faptelor indicate în rechizitoriu şi a solicitat personal prin înscris autentic ca judecata să se facă pe baza probelor administrate în faza urmăririi penale, în procedura 1 prevăzută de art.364 CPP. În baza probelor acumulate la urmărirea penală şi recunoscute de inculpat, instanţa de fond corect a stabilit starea de fapt şi de 1 drept pe caz şi

[Succeeded / Failed / Skipped / Total] 47 / 52 / 31 / 130:  99%|█████████▉| 99/100 [18:48<00:11, 11.39s/it]

--------------------------------------------- Result 130 ---------------------------------------------
[[1 (88%)]] --> [[0 (51%)]]

Prin sentința Judecătoriei Drochia sediul [[Central]] din 27.12.2018, Bejan Ion ***** a [[fost]] recunoscut vinovat de comiterea infracțiunii prevăzute de art.186 alin.(2) lit.b), c), d) Codul Penal RM și ca măsură de pedeapsă, i-a fost aplicată 200 (două sute) ore muncă neremunerată în folosul cominității. Maiorov Serghei ***** a fost recunoscut vinovat de comiterea infracțiunii prevăzute de art.186 alin.(2) lit.b), c), d) Codul Penal RM și ca măsură de pedeapsă, i-a fost aplicată 200 (două sute) ore muncă neremunerată în folosul cominității. Tintiuc Andrei ***** a fost recunoscut [[vinovat]] de comiterea infracțiunilor prevăzute de art.186 alin.(2) lit.b), c), d), art.217 alin.(2), art.1921 alin.(2) lit.a), art.187 alin.(2) lit.d), e), f) Cod Penal al RM și ca măsură de pedeapsă, i-a fost aplicaă : - în baza art.186 alin.(2) lit.b), c), d) Codul Penal al RM, închisoare pe un termen de 2 (doi) ani cu ispășirea pedepsei în penitenciar de tip semiînchis; - în baza art.217 [[alin]].(2) Codul Penal al RM, [[închisoare]] pe un termen de 1 (unu) ani de zile cu ispășirea pedepsei în penitenciar de tip semiînchis; - în art.1921 alin.(2) lit.a)Codul Penal al RM, [[închisoare]] pe un termen de 3 (trei) ani de zile cu ispășirea pedepsei în penitenciar de tip semiînchis.; - în baza art.187 alin.(2) lit.d), e), f) Codul Penal al RM, închisoare pe un termen de 5 (cinci) ani de zile cu ispășirea pedepsei în penitenciar de tip semiînchis, fără amendă. [[Conform]] art.84 alin.(1) Cod Penal al RM, pentru concurs de infracțiuni, lui Tintiuc Andrei ***** i s-a [[stabilit]], prin cumul parţial al pedepselor aplicate, pedeapsa definitivă sub formă de închisoare pe un termen de 5 (cinci) ani și 2 ( două ) luni de zile, cu ispășirea pedepsei în penitenciar de tip semiînchis. Sentința în [[privința]] lui Tintiuc Andrei a fost dispusă spre executare după devenirea sentinței irevocabile. Măsura preventivă aplicată inculpatului Tintiuc Andrei s-a mențint aceiaș. Măsura preventivă aplicată inculpatului Bejan Ion și Maiorov Serghei s-a menținut aceiaș pînă la întrarea sentinței în vigoare,apoi de anulat. S-a încasat de la Tintiuc Andrei în beneficiul lui Petrova Iulia suma de 3121 (trei mii una sută douăzeci și unu) lei cu titlu de prejudiciu material și 3000 (trei mii) lei cu titlu de prejudiciu moral. S-a încasat de la Bejan Ion în beneficiul lui Petrova Iulia suma de 121 (una sută douăzeci și unu) lei cu titlu de prejudiciu material și 3000 (trei mii) lei cu titlu de prejudiciu moral. S-a încasat de la Maiorov Serghei în beneficiul lui Petrova Iulia suma de 421 (patru sute douăzeci și unu) lei cu titlu de prejudiciu material și 3000 (trei mii) lei cu titlu de prejudiciu moral. Corpul delict: un pachet cu marihuană- materie uscată în cantitate de 11,616 gr., ce se află la păstrare în camera de păstrare la IP Drochia după întrarea sentinței în vigoare de nimicit. Corpul delict: o combină ”Vitek” de culoare albă, o geantă de culoare albastră în care se află piese și instrumente pentru meșteșugărit în care se află o sacoșă de culoare neagră unde se află niște ținte, două discuri de la bulgarcă,

Prin sentința Judecătoriei Drochia sediul [[Cnetral]] din 27.12.2018, Bejan Ion ***** a [[fsot]] recunoscut vinovat de comiterea infracțiunii prevăzute de art.186 alin.(2) lit.b), c), d) Codul Penal RM și ca măsură de pedeapsă, i-a fost aplicată 200 (două sute) ore muncă neremunerată în folosul cominității. Maiorov Serghei ***** a fost recunoscut vinovat de comiterea infracțiunii prevăzute de art.186 alin.(2) lit.b), c), d) Codul Penal RM și ca măsură de pedeapsă, i-a fost aplicată 200 (două sute) ore muncă neremunerată în folosul cominității. Tintiuc Andrei ***** a fost recunoscut [[vniovat]] de comiterea infracțiunilor prevăzute de art.186 alin.(2) lit.b), c), d), art.217 alin.(2), art.1921 alin.(2) lit.a), art.187 alin.(2) lit.d), e), f) Cod Penal al RM și ca măsură de pedeapsă, i-a fost aplicaă : - în baza art.186 alin.(2) lit.b), c), d) Codul Penal al RM, închisoare pe un termen de 2 (doi) ani cu ispășirea pedepsei în penitenciar de tip semiînchis; - în baza art.217 [[ailn]].(2) Codul Penal al RM, [[închisaore]] pe un termen de 1 (unu) ani de zile cu ispășirea pedepsei în penitenciar de tip semiînchis; - în art.1921 alin.(2) lit.a)Codul Penal al RM, [[închisaore]] pe un termen de 3 (trei) ani de zile cu ispășirea pedepsei în penitenciar de tip semiînchis.; - în baza art.187 alin.(2) lit.d), e), f) Codul Penal al RM, închisoare pe un termen de 5 (cinci) ani de zile cu ispășirea pedepsei în penitenciar de tip semiînchis, fără amendă. [[Conofrm]] art.84 alin.(1) Cod Penal al RM, pentru concurs de infracțiuni, lui Tintiuc Andrei ***** i s-a [[stabliit]], prin cumul parţial al pedepselor aplicate, pedeapsa definitivă sub formă de închisoare pe un termen de 5 (cinci) ani și 2 ( două ) luni de zile, cu ispășirea pedepsei în penitenciar de tip semiînchis. Sentința în [[priivnța]] lui Tintiuc Andrei a fost dispusă spre executare după devenirea sentinței irevocabile. Măsura preventivă aplicată inculpatului Tintiuc Andrei s-a mențint aceiaș. Măsura preventivă aplicată inculpatului Bejan Ion și Maiorov Serghei s-a menținut aceiaș pînă la întrarea sentinței în vigoare,apoi de anulat. S-a încasat de la Tintiuc Andrei în beneficiul lui Petrova Iulia suma de 3121 (trei mii una sută douăzeci și unu) lei cu titlu de prejudiciu material și 3000 (trei mii) lei cu titlu de prejudiciu moral. S-a încasat de la Bejan Ion în beneficiul lui Petrova Iulia suma de 121 (una sută douăzeci și unu) lei cu titlu de prejudiciu material și 3000 (trei mii) lei cu titlu de prejudiciu moral. S-a încasat de la Maiorov Serghei în beneficiul lui Petrova Iulia suma de 421 (patru sute douăzeci și unu) lei cu titlu de prejudiciu material și 3000 (trei mii) lei cu titlu de prejudiciu moral. Corpul delict: un pachet cu marihuană- materie uscată în cantitate de 11,616 gr., ce se află la păstrare în camera de păstrare la IP Drochia după întrarea sentinței în vigoare de nimicit. Corpul delict: o combină ”Vitek” de culoare albă, o geantă de culoare albastră în care se află piese și instrumente pentru meșteșugărit în care se află o sacoșă de culoare neagră unde se află niște ținte, două discuri de la bulgarcă,

[Succeeded / Failed / Skipped / Total] 48 / 52 / 31 / 131: 100%|██████████| 100/100 [18:57<00:00, 11.37s/it]

--------------------------------------------- Result 131 ---------------------------------------------
[[0 (93%)]] --> [[1 (58%)]]

Pentru a se pronunţa în sensul celor expuse instanţa de fond a reţinut că inculpatul Cozarevici Semion Mihail la o dată neidentificată de organul de urmărire penală, în perioada de timp cuprinsă între 23.03.2017 până la 15.04.2017, aflându-se pe terenul agricol GŢ „Dutca Vădim”, [[care-i]] aparţine cu drept de proprietate lui Dutca Vadim, amplasat în extravilanul satului Grigorăuca r-nul Sîngerei, acţionând intenţionat, cu scopul sustragerii bunurilor altei persoane, înţelegând caracterul prejudiciabil al acţiunilor sale, pe ascuns a sustras 21 pomi de nuci altoiţi în valoare de 9 Euro fiecare, cauzând părţii vătămate o pagubă materială considerabilă în sumă totală de 189 Euro, echivalentul a 3931 lei MD. Sentinţa instanţei de fond a [[fost]] atacată cu apel în termen de către [[inculpatul]] Cozarevici Semion, care în motivare invocă că nu este deacord cu sentința instanței de fond din următoarele [[considerente]]: -condamnându-l în temeiul art.186 CP, instanţa judecătorească deduce din faptul că în cauza penală există o declaraţie în timpul petrecerii anchetei de către IP Sîngerei lui Dutca V. că partea vătămată în perioada de la 23.03. până la data de 15.04.2017, de la cota sa au fost sustraşi pomi de nuci altoite în cantitate de 21 puieţi de către persoane necunoscute (f.d.10), -la data de 18.04.2017 Dutca a trecut pe lângă casa lui și a văzut, că a plantat nuci și a decis că la dânsul sunt plantaţi asemenea copaci de nucă şi a decis că copacii au fost sustraţi de către el. -a fost întocmit proces-verbal din 15.04.2017 în care se indică, că de la cota lui Dutca V. lipsesc 21 de copaci de nuci, pe această bază, organele de urmărire penală au ajuns la [[concluzia]] că aceşti copaci au fost sustraşi de către el, -în timp ce, potrivit fototabelelor, a fost stabilit și numărate de către colaboratorii de urmărire penală, în conformitate cu fototabelele, procesul-verbal din 19.04.2017 ca rezultatul verificării la domiciliul lui că în gospodăria lui s-au depistat 9 puieţi de nuc, -reieşind din cele menţionate, organele de urmărire penală au decis că aceşti puieţi au fost sustraşi de la cota lui Dutca V. dar nu au indicat în baza căror semne, că puieţii plantaţi în anul 2017 de către el au fost sustraşi anume de la cota lui Dutca V. Dutca și-a plantat puieţii de nucă în 2015, dar el a plantat 9 puieţi de nuc în 2017, -judecata l-a condamnat şi a ajuns la concluzia că puieţii lui au fost sustraşi de la cota lui Dutca, dar instanţa nu a ţinut cont de faptul că puieţii de nucă a lui Dutca V. au fost plantate în 2015, iar până în 2017 erau deja copaci și dacă s-ar fi comparat, potrivit lui Dutca vârfurile copacilor au fost tăiate, iar la puieţii lui vârfurile au fost întregi, despre ceea ce au spus martorii în ședinţă - *****, *****, și conform procesului-verbal din 19.04.2017 de pe terenul lui, fără permisiunea lui au fost ridicaţi prin gard la distanţa de un 1 metru puieţii de nuc de către organele de urmărire penală, -la data de 14.04.2017 a fost emisă ordonanţa privind dispunerea

Pentru a se pronunţa în sensul celor expuse instanţa de fond a reţinut că inculpatul Cozarevici Semion Mihail la o dată neidentificată de organul de urmărire penală, în perioada de timp cuprinsă între 23.03.2017 până la 15.04.2017, aflându-se pe terenul agricol GŢ „Dutca Vădim”, [[crae-i]] aparţine cu drept de proprietate lui Dutca Vadim, amplasat în extravilanul satului Grigorăuca r-nul Sîngerei, acţionând intenţionat, cu scopul sustragerii bunurilor altei persoane, înţelegând caracterul prejudiciabil al acţiunilor sale, pe ascuns a sustras 21 pomi de nuci altoiţi în valoare de 9 Euro fiecare, cauzând părţii vătămate o pagubă materială considerabilă în sumă totală de 189 Euro, echivalentul a 3931 lei MD. Sentinţa instanţei de fond a [[fsot]] atacată cu apel în termen de către [[inculaptul]] Cozarevici Semion, care în motivare invocă că nu este deacord cu sentința instanței de fond din următoarele [[consideretne]]: -condamnându-l în temeiul art.186 CP, instanţa judecătorească deduce din faptul că în cauza penală există o declaraţie în timpul petrecerii anchetei de către IP Sîngerei lui Dutca V. că partea vătămată în perioada de la 23.03. până la data de 15.04.2017, de la cota sa au fost sustraşi pomi de nuci altoite în cantitate de 21 puieţi de către persoane necunoscute (f.d.10), -la data de 18.04.2017 Dutca a trecut pe lângă casa lui și a văzut, că a plantat nuci și a decis că la dânsul sunt plantaţi asemenea copaci de nucă şi a decis că copacii au fost sustraţi de către el. -a fost întocmit proces-verbal din 15.04.2017 în care se indică, că de la cota lui Dutca V. lipsesc 21 de copaci de nuci, pe această bază, organele de urmărire penală au ajuns la [[concluiza]] că aceşti copaci au fost sustraşi de către el, -în timp ce, potrivit fototabelelor, a fost stabilit și numărate de către colaboratorii de urmărire penală, în conformitate cu fototabelele, procesul-verbal din 19.04.2017 ca rezultatul verificării la domiciliul lui că în gospodăria lui s-au depistat 9 puieţi de nuc, -reieşind din cele menţionate, organele de urmărire penală au decis că aceşti puieţi au fost sustraşi de la cota lui Dutca V. dar nu au indicat în baza căror semne, că puieţii plantaţi în anul 2017 de către el au fost sustraşi anume de la cota lui Dutca V. Dutca și-a plantat puieţii de nucă în 2015, dar el a plantat 9 puieţi de nuc în 2017, -judecata l-a condamnat şi a ajuns la concluzia că puieţii lui au fost sustraşi de la cota lui Dutca, dar instanţa nu a ţinut cont de faptul că puieţii de nucă a lui Dutca V. au fost plantate în 2015, iar până în 2017 erau deja copaci și dacă s-ar fi comparat, potrivit lui Dutca vârfurile copacilor au fost tăiate, iar la puieţii lui vârfurile au fost întregi, despre ceea ce au spus martorii în ședinţă - *****, *****, și conform procesului-verbal din 19.04.2017 de pe terenul lui, fără permisiunea lui au fost ridicaţi prin gard la distanţa de un 1 metru puieţii de nuc de către organele de urmărire penală, -la data de 14.04.2017 a fost emisă ordonanţa privind dispunerea



+-------------------------------+--------+
| Attack Results                |        |
+-------------------------------+--------+
| Number of successful attacks: | 48     |
| Number of failed attacks:     | 52     |
| Number of skipped attacks:    | 31     |
| Original accuracy:            | 76.34% |
| Accuracy under attack:        | 39.69% |
| Attack success rate:          | 48.0%  |
| Average perturbed word %:     | 1.89%  |
| Average num. words per input: | 516.6  |
| Avg num queries:              | 656.34 |
+-------------------------------+--------+

[<textattack.attack_results.failed_attack_result.FailedAttackResult at 0x7002a0f0f410>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7db6cf80>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c0bc950>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffea4f09370>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7db09c10>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c31b410>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c44f2f0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d4ead20>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d4ea270>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a19ef290>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d7baa50>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a0334200>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d368e30>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c3b9fd0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dc774d0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7dc74470>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d476210>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a11239e0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d403170>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c17dd00>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x7002a1123bc0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d369010>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c818c50>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffeb4304410>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c70da60>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffeb42d0770>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c116630>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d7f8e00>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffeb42f6a50>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c4f71a0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7dc75eb0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c8188f0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7c7190d0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d728500>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c9f4830>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7c9f7bf0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7c9f7a40>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7c7e5040>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d5c92e0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d5ca450>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7db23680>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dd96600>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d54f800>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c8ec050>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c9559a0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8cff5010>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x7002a041b9b0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8cff7980>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d643800>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7c779160>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c7ad640>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a34fdcd0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d5295e0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dfd3710>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c64f7d0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7c64e150>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a02451c0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c7fba10>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8cbea300>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d52acf0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d52bd40>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8c9b08f0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dbd88c0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7dd2d7c0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c4bf110>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c849f10>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c40ffe0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c825d30>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x7002a0418f20>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c7ee840>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a0418b30>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffea42249b0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8dd3d5e0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8dd3cb30>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c45b7d0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8c458950>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8c4585f0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8c45ae70>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7c974a40>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8ca727b0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7df37d10>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7df97020>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c763800>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c409520>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d802060>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dbdc740>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c523ec0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d570680>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d5715e0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d72f2f0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c25a210>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8ccd4980>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d52ae70>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c210ec0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c7ae420>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c6f47a0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c4b7230>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c435c10>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d5cdca0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c7ac0b0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dc4d2b0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7dc4ea50>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7dc5ecc0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d8143e0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d815580>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7d815cd0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7c7065a0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7d899e20>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffea4f1e3f0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7c6a2f60>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffea4f25220>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7da28cb0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7da2ae10>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7da28710>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe8c84a7b0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d9e2db0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7c7da9c0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe7c7d9250>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c344e30>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8c345550>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8c347e00>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a1611af0>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe8c49e6c0>,
 <textattack.attack_results.skipped_attack_result.SkippedAttackResult at 0x6ffe8c49c800>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7d7d4110>,
 <textattack.attack_results.failed_attack_result.FailedAttackResult at 0x6ffe7c40b8c0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a324f980>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7c233ad0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffe7c8c9070>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x7002a0ec39b0>,
 <textattack.attack_results.successful_attack_result.SuccessfulAttackResult at 0x6ffea472a0c0>]

# RoGPT2

In [8]:
def prepare_dataset(path):
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    label_map = {
        "vinovat": 0,
        "nevinovat": 1
    }

    formatted_data = []
    for entry in data:
        desc = " ".join([entry.get(f"case_description_{i}", "") for i in range(1, 9)]).strip()

        # --- PROMPT ENGINEERING START ---
        instructional_prompt = (
            f"Ești un expert legal și task-ul tău este de a analiza "
            f"un caz juridic și de a decide verdictul corect. "
            f"Analizează pas cu pas informațiile oferite înainte "
            f"de a formula răspunsul final. "
            f"Decide verdictul acestui caz juridic:\n"
            f"Ai de ales între două răspunsuri: admis sau respins.\n"
            f"Descriere caz: {desc}\n" 
        )

        # --- PROMPT ENGINEERING END ---
        
        formatted_data.append({
            "text": instructional_prompt, 
            "label": label_map[entry["label"]]
        })

    train_data, val_data = train_test_split(
        formatted_data, 
        test_size=0.15, 
        stratify=[d["label"] for d in formatted_data], # Keep class ratios same
        random_state=42
    )
    
    return Dataset.from_list(train_data), Dataset.from_list(val_data)

train_raw, val_raw = prepare_dataset("data/regional-court-data.json")

In [9]:
model_name = "readerbench/RoGPT2-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_function(examples):
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=512)

tokenized_train = train_raw.map(tokenize_function, batched=True)
tokenized_val = val_raw.map(tokenize_function, batched=True)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

# Important for GPT2 padding
model.config.pad_token_id = tokenizer.pad_token_id

model = model.to(device)

print(f"Using device: {device}")

training_args = TrainingArguments(
    output_dir="results/good/dist-ro-gpt2-base",
    learning_rate=2e-5,
    lr_scheduler_type="cosine",
    warmup_steps=200,
    warmup_ratio=0.1,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    num_train_epochs=5,
    weight_decay=0.1,
    fp16=True,
    logging_steps=50,
    eval_steps=50,
    eval_strategy="steps",
    save_strategy="epoch",
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    compute_metrics=compute_metrics,
    data_collator=DataCollatorWithPadding(tokenizer=tokenizer)
)

trainer.train()

Map: 100%|██████████| 7539/7539 [00:06<00:00, 1149.23 examples/s]
Map: 100%|██████████| 1331/1331 [00:01<00:00, 1056.42 examples/s]
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at readerbench/RoGPT2-base and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Using device: cuda

KeyboardInterrupt:

In [10]:
checkpoint_path = "results/good/dist-ro-gpt2-base/checkpoint-1416"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint_path).to(device)
model.eval()
print(f"Model loaded from {checkpoint_path}")

Model loaded from results/good/dist-ro-gpt2-base/checkpoint-1416

In [11]:
import pandas as pd
from transformers import Trainer

# 1. Define Jamming Strings
# Strategy A: Heavy boilerplate text to crowd out the sequence length limit
PREFIX_JAMMING_TEXT = "Incheiere text administrativ. Monitorul Oficial nr. 1. Procedura legala in vigoare. Document intern de arhiva judiciara. " * 8 

# Strategy B: A disruptive token to inject inside the text body
INTERLEAVED_JAMMING_TOKEN = " [NOTIFICARE-SISTEM] "

# 2. Attack Functions
def apply_prefix_jamming(raw_dataset):
    def jam_prefix(example):
        example["text"] = PREFIX_JAMMING_TEXT + example["text"]
        return example
    return raw_dataset.map(jam_prefix).map(tokenize_function, batched=True)

def apply_interleaved_jamming(raw_dataset):
    def jam_interleave(example):
        words = example["text"].split()
        # Inject the jamming token every 5 words
        jammed_words = []
        for i, word in enumerate(words):
            jammed_words.append(word)
            if (i + 1) % 5 == 0:
                jammed_words.append(INTERLEAVED_JAMMING_TOKEN)
        example["text"] = " ".join(jammed_words)
        return example
    return raw_dataset.map(jam_interleave).map(tokenize_function, batched=True)

# 3. Generate Jammed Validation Sets
tokenized_val_prefix_jam = apply_prefix_jamming(val_raw)
tokenized_val_interleaved_jam = apply_interleaved_jamming(val_raw)

# 4. Evaluate using your existing RoGPT2 Trainer
print("Evaluating Baseline (Clean)...")
clean_metrics = trainer.evaluate(eval_dataset=tokenized_val)

print("Evaluating Prefix Jamming (Context Eviction)...")
prefix_jam_metrics = trainer.evaluate(eval_dataset=tokenized_val_prefix_jam)

print("Evaluating Interleaved Jamming (Attention Dilution)...")
interleaved_jam_metrics = trainer.evaluate(eval_dataset=tokenized_val_interleaved_jam)

# 5. Compile into a Thesis-ready DataFrame
results_df = pd.DataFrame({
    "Metric": clean_metrics.keys(),
    "Clean Baseline": clean_metrics.values(),
    "Prefix Jamming": prefix_jam_metrics.values(),
    "Interleaved Jamming": interleaved_jam_metrics.values()
})
print(results_df)

Map: 100%|██████████| 1331/1331 [00:00<00:00, 14968.29 examples/s]
Map: 100%|██████████| 1331/1331 [00:01<00:00, 1141.12 examples/s]
Map: 100%|██████████| 1331/1331 [00:00<00:00, 3238.73 examples/s]
Map: 100%|██████████| 1331/1331 [00:02<00:00, 506.82 examples/s]

Evaluating Baseline (Clean)...

Evaluating Prefix Jamming (Context Eviction)...
Evaluating Interleaved Jamming (Attention Dilution)...
                 Metric  Clean Baseline  Prefix Jamming  Interleaved Jamming
0             eval_loss        0.704502        0.790657             0.776139
1         eval_accuracy        0.790383        0.731781             0.673929
2         eval_f1_macro        0.787231        0.729277             0.629041
3  eval_precision_macro        0.785887        0.730911             0.672513
4     eval_recall_macro        0.794649        0.738850             0.631469

# RAG Attacks

In [12]:
import json

label_map = {
    "vinovat": 0,
    "nevinovat": 1
}

def prepare_dataset(json_file_path):
    with open(json_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    

    formatted_data = []
    for entry in data:
        entry.pop("source_path", None)
        # Combine description (1-8) and justification (1-4)
        desc = " ".join([entry.get(f"case_description_{i}", "") for i in range(1, 9)]).strip()
        just = " ".join(entry.get(f"sentence", "")).strip()
        sentence = " ".join(entry.get(f"sentence", "")).strip()
        if len(desc) < 5610:
            formatted_data.append({
                "text": f"{desc}", # Description prioritized by order
                "just": f"{just}", # Justification
                "sentence": f"{sentence}", # Sentence prioritized by order
                "label": label_map[entry["label"]]
            })
    
    # Split into train and validation (85/15)
    train_data, val_data = train_test_split(
        formatted_data, 
        test_size=0.0499, 
        stratify=[d["label"] for d in formatted_data], # Keep class ratios same
        random_state=42
    )
    
    return Dataset.from_list(train_data), Dataset.from_list(val_data)

rag_dataset, val_dataset = prepare_dataset("data/regional-court-data.json")

In [13]:
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from datasets import Dataset

# 1. Setup Model (Optimized for Romanian nuances)
# This model is excellent for Romanian and 50+ other languages.
model_name = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
embedder = SentenceTransformer(model_name)

def build_rag_system(rag_dataset):
    # 2. Encode the Knowledge Base
    print("Encoding knowledge base...")
    kb_texts = rag_dataset['text']
    kb_embeddings = embedder.encode(kb_texts, convert_to_numpy=True, show_progress_bar=True)
    
    # 3. Initialize FAISS Index
    dimension = kb_embeddings.shape[1]
    index = faiss.IndexFlatL2(dimension)
    index.add(kb_embeddings)
    
    return index, kb_texts, rag_dataset['label']

# Initialize the system
faiss_index, kb_texts, kb_labels = build_rag_system(rag_dataset)

def run_inference(query_text, k):
    # 4. Retrieval
    query_embedding = embedder.encode([query_text], convert_to_numpy=True)
    distances, indices = faiss_index.search(query_embedding, k)
    
    # Get retrieved neighbors
    retrieved_labels = [kb_labels[i] for i in indices[0]]
    retrieved_texts = [kb_texts[i] for i in indices[0]]
    
    # 5. Logic for Label, Confidence, and Explanation
    # We calculate confidence based on label agreement and distance
    label_0_count = retrieved_labels.count(0)
    label_1_count = retrieved_labels.count(1)
    
    predicted_label = 1 if label_1_count >= label_0_count else 0
    
    # Simple confidence score based on retrieval consensus
    consensus = max(label_0_count, label_1_count) / k
    # Soften score based on distance (closer = more confident)
    avg_distance = np.mean(distances[0])
    confidence_score = round(consensus * (1 / (1 + avg_distance * 0.1)), 2)
    
    # Construct Romanian explanation
    explanation = f"Bazat pe cele mai similare {k} exemple găsite: "
    explanation += f"{label_1_count} indică eticheta 1 și {label_0_count} indică eticheta 0. "
    explanation += f"Cel mai apropiat context: '{retrieved_texts[0][:100]}...'"

    return {
        "label": predicted_label,
        "confidence score": confidence_score,
        "explanation": explanation
    }, retrieved_texts, retrieved_labels

Encoding knowledge base...

Batches: 100%|██████████| 60/60 [00:01<00:00, 30.02it/s]

In [14]:
from sklearn.metrics import precision_score, recall_score, f1_score

y_true = []
y_pred = []
retrieved_texts_all = []
explanations_all = []

print("Running evaluation...")
for i in range(len(val_dataset)):
    sample = val_dataset[i]
    output, retrieved_texts, retrieved_labels = run_inference(sample['text'], k=3)
    
    y_true.append(sample['label'])
    y_pred.append(output['label'])
    explanations_all.append(output['explanation'])
    retrieved_texts_all.append(retrieved_texts)

# Calculate metrics
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)
accuracy = sum([1 if y_true[i] == y_pred[i] else 0 for i in range(len(y_true))]) / len(y_true) 

print("RESULTS FOR RECALL@3:")
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Running evaluation...
RESULTS FOR RECALL@3:
Accuracy: 0.8000
F1 Score: 0.7619
Precision: 0.7805
Recall: 0.7442

In [16]:
from sklearn.metrics import precision_score, recall_score, f1_score

y_true = []
y_pred = []
retrieved_texts_all = []
explanations_all = []

print("Running evaluation...")
for i in range(len(val_dataset)):
    sample = val_dataset[i]
    output, retrieved_texts, retrieved_labels = run_inference(sample['text'], k=10)
    
    y_true.append(sample['label'])
    y_pred.append(output['label'])
    explanations_all.append(output['explanation'])
    retrieved_texts_all.append(retrieved_texts)

# Calculate metrics
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)
accuracy = sum([1 if y_true[i] == y_pred[i] else 0 for i in range(len(y_true))]) / len(y_true) 

print("RESULTS FOR RECALL@10:")
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Running evaluation...
RESULTS FOR RECALL@10:
Accuracy: 0.7600
F1 Score: 0.7391
Precision: 0.6939
Recall: 0.7907

In [15]:
import numpy as np
import pandas as pd
from datasets import Dataset

# Ensure your original components are available:
# faiss_index, kb_texts, kb_labels, embedder, val_dataset, run_inference

# =====================================================================
# ATTACK 1: Targeted Corpus Poisoning (Tested on k=3)
# Goal: Force highly similar sentences with conflicting labels into the KB.
# =====================================================================

print("\n--- Preparing Targeted Corpus Poisoning (k=3) ---")

# Let's create malicious sentences matching your legal validation queries
# We copy some text from the validation set but explicitly invert the target label
poisoned_texts = []
poisoned_labels = []

# Take 10 samples from the validation set, tweak them, and give them the wrong label
for i in range(10):
    original_text = val_dataset[i]['text']
    original_label = val_dataset[i]['label']
    adversarial_label = 1 if original_label == 0 else 0
    
    # Injecting a legal phrase that mimics high relevance but maps to the wrong target
    adversarial_text = original_text[:200] + " [DECIDAT: Fapta nu întrunește elementele constitutive ale infracțiunii conform jurisprudenței noi.]"
    
    poisoned_texts.append(adversarial_text)
    poisoned_labels.append(adversarial_label)

# Create a poisoned knowledge base by appending the malicious rows
poisoned_kb_texts = list(kb_texts) + poisoned_texts
poisoned_kb_labels = list(kb_labels) + poisoned_labels

# Rebuild a Poisoned FAISS Index
print("Encoding poisoned knowledge base...")
poisoned_embeddings = embedder.encode(poisoned_kb_texts, convert_to_numpy=True, show_progress_bar=False)
dimension = poisoned_embeddings.shape[1]
poisoned_index = faiss.IndexFlatL2(dimension)
poisoned_index.add(poisoned_embeddings)

# Override the system inference variables to use the poisoned database
def run_poisoned_inference(query_text, k):
    query_embedding = embedder.encode([query_text], convert_to_numpy=True)
    # Search using the poisoned index
    distances, indices = poisoned_index.search(query_embedding, k)
    
    retrieved_labels = [poisoned_kb_labels[i] for i in indices[0]]
    retrieved_texts = [poisoned_kb_texts[i] for i in indices[0]]
    
    label_0_count = retrieved_labels.count(0)
    label_1_count = retrieved_labels.count(1)
    predicted_label = 1 if label_1_count >= label_0_count else 0
    
    consensus = max(label_0_count, label_1_count) / k
    avg_distance = np.mean(distances[0])
    confidence_score = round(consensus * (1 / (1 + avg_distance * 0.1)), 2)
    
    return predicted_label, confidence_score

# Evaluate Attack 1 at k=3
y_true_p1, y_pred_p1 = [], []
for i in range(10): # Testing on the target subset
    sample = val_dataset[i]
    pred, _ = run_poisoned_inference(sample['text'], k=3)
    y_true_p1.append(sample['label'])
    y_pred_p1.append(pred)

acc_k3_attack = sum([1 for i in range(10) if y_true_p1[i] == y_pred_p1[i]]) / 10
print(f"Targeted Subset Accuracy under Corpus Poisoning (k=3): {acc_k3_attack:.4f}")


# =====================================================================
# ATTACK 2: Haystack Distraction / Consensus Dilution (Tested on k=10)
# Goal: Flood the retrieval with "Neutral" background noise to kill precision.
# =====================================================================

print("\n--- Preparing Haystack Distraction Attack (k=10) ---")

# Generate completely neutral, dense legal phrases that carry label=0 
# to artificially dilute any query where the true label should be 1.
distraction_texts = [
    "Procedura administrativă standard prevede arhivarea dosarelor în format electronic conform regulamentului.",
    "Termenul de depunere a contestațiilor este de 15 zile de la comunicarea oficială a deciziei.",
    "Grefierul de ședință va consemna toate declarațiile martorilor în procesul-verbal atașat la dosar."
] * 20 # Add 60 distraction documents

diluted_kb_texts = list(kb_texts) + distraction_texts
diluted_kb_labels = list(kb_labels) + [0] * len(distraction_texts) # Label them all as 0

# Rebuild a Diluted FAISS Index
diluted_embeddings = embedder.encode(diluted_kb_texts, convert_to_numpy=True, show_progress_bar=False)
diluted_index = faiss.IndexFlatL2(dimension)
diluted_index.add(diluted_embeddings)

def run_diluted_inference(query_text, k):
    query_embedding = embedder.encode([query_text], convert_to_numpy=True)
    distances, indices = diluted_index.search(query_embedding, k)
    
    retrieved_labels = [diluted_kb_labels[i] for i in indices[0]]
    label_0_count = retrieved_labels.count(0)
    label_1_count = retrieved_labels.count(1)
    
    predicted_label = 1 if label_1_count >= label_0_count else 0
    consensus = max(label_0_count, label_1_count) / k
    return predicted_label, consensus

# Evaluate Attack 2 at k=10
y_true_p2, y_pred_p2 = [], []
for i in range(len(val_dataset)):
    sample = val_dataset[i]
    pred, _ = run_diluted_inference(sample['text'], k=10) # Testing on high k
    y_true_p2.append(sample['label'])
    y_pred_p2.append(pred)

acc_k10_attack = sum([1 for i in range(len(val_dataset)) if y_true_p2[i] == y_pred_p2[i]]) / len(val_dataset)
print(f"Global Accuracy under Haystack Distraction (k=10): {acc_k10_attack:.4f}")

--- Preparing Targeted Corpus Poisoning (k=3) ---
Encoding poisoned knowledge base...
Targeted Subset Accuracy under Corpus Poisoning (k=3): 0.7000

--- Preparing Haystack Distraction Attack (k=10) ---
Global Accuracy under Haystack Distraction (k=10): 0.7600